### ISSUE TITLE
Electric vehicle charging strategies

### ISSUE THREAD

**Issue by cjlaumans** [quintel/etmodel#1043]
I'm documenting here an idea that I've had for a long time but never got around to implementing. Maybe others can appreciate this feature suggestion and someday it can become part of the ETM.

This idea is based on my thesis work. The idea is to show users the effect of charging electric vehicles at different times of the day on the electricity demand profile. Ideally users can select a charging strategy to change the impact on the electricity grid.

Below I've added some screenshots to show what it should look like and how it should work. In short this is what would happen:
1. An icon is added next to the electric vehicles slider.
2. Clicking the icon brings up a popup showing 4 different electric vehicle charging strategies (at the end of the day, anywhere, at the office, or at night.). Users can select from the 4 strategies, with the default being "At the end of the day".
3. If users select one of the charging strategies the "simultaneousness" values of the electric cars converter (this is an attribute used for the network calculation) change. As a result the network impact changes.

I'll describe each of the above steps in more detail with the use of screenshots below. The data for the charts is found in an Excel document that I've placed in the Dropbox shared with @AlexanderWirtz and @ChaelKruip in the folder: /Network Calculation/EV charging strategies

An icon is added next to the electric vehicles slider. One concern here is that in the NL ETM, this slider already has 1 icon for the backcasting. How to deal with this, and whether having 2 icons is acceptable would need to be determined.

![](https://img.skitch.com/20120831-n426egabp2ikxqg3tdmyd9ccjw.jpg)

Clicking on the icon brings up a popup showing 4 different electric vehicle charging strategies. Users can select from the 4 strategies, with the default being "At the end of the day"

![](https://img.skitch.com/20120831-tj9349g1m23uf9yethfj7mp3t6.jpg)

The simultaneousness values change to reflect the user's choice for a strategy.

![](https://img.skitch.com/20120831-bts8pkxeexuhr4spwgtmbasqyt.jpg)

**Comment by jorisberkhout** [comment]
Assigning @ChaelKruip as this feels like it is in scope of the local ETM project.

**Comment by dennisschoenmakers** [comment]
@ChaelKruip is this already part of the new dynamic load curve? And if not, is this planned?

**Comment by antw** [comment]
> is this already part of the new dynamic load curve? And if not, is this planned?

This does sound a lot like the new ["Demand response"](https://beta-pro.energytransitionmodel.com/scenario/flexibility/electricity_storage/demand-response) sliders.

**Comment by dennisschoenmakers** [comment]
Thanks! Closing this issue.
