### ISSUE TITLE
Add chart with CWE Day Ahead prices

### ISSUE THREAD

**Issue by fvancamp** [quintel/etmodel#1667]
Within Supply>Import/Export, we want to replicate the following chart as available on http://www.apxgroup.com/market-results/cwe/

![screen shot 2013-11-15 at 15 55 08](https://f.cloud.github.com/assets/757143/1550551/08e8963a-4e06-11e3-9489-4d765b384a66.png)

Part of the data required to recreate this chart can be obtained from the JSON object that is available from http://www.apxgroup.com/rest-api/quotes/ . This is a huge array, including 5 CWE Day Ahead objects, which each contain 4 values, related to respectively:
- APX DAM Price
- Belpex DAM Price
- EPEX Spot FR Price
- EPEX Spot DE Price

The first such object in the array relates to the day of tomorrow, the second to today and so on until three days ago.

In order to create a chart with 2 weeks worth of prices, a script/CRON job should run daily to add another datapoint to the database. Upon loading a scenario, a dataset should be loaded and made available to the associated D3 chart.

**Comment by marliekeverweij** [comment]
See https://github.com/quintel/documentation/blob/master/general/import_export.md
