### ISSUE TITLE
Transformations are modeled incorrectly

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1775]
As an example, oil products such as gasoline, diesel and kerosene are produced only to fulfil local demand in the ETM. For the Netherlands this is incorrect because the Dutch export a lot of these products. In effect, the ETM **underestimates the net flow of oil through the Netherlands** and, therefore, accounts for too little loss due to conversions.

Furthermore, there are inconsistencies in they way these transformation losses are accounted for. Sometimes they are modeled as fractions of the flow through a node (as for oil products) and sometimes they are modeled as **fixed** 'own use' demands for a sector.

Solution: To solve this issue properly, the current production time-curves have to be replaced by something more realistic that allows a country to **simultaneously** import and export a given carrier (group). Also see https://github.com/quintel/etmodel/issues/1774

**Comment by RobTerwel** [comment]
Unfortunately I did not find time to do this; however, transformations could possibly be modelled in a way akin to the <a href="https://github.com/quintel/etsource/blob/master/nodes/industry/industry_refinery_transformation_crude_oil.converter.ad">refinery<a/>. 

Assigning @jorisberkhout

**Comment by jorisberkhout** [comment]
Removing milestone.
