### ISSUE TITLE
We should have a URL to point to a dataset immediately.

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#1817]
E.g.: http://energytransitionmodel.com/uk

Page could show some statistics about the Area selected (population, energy use?)

**Comment by ChaelKruip** [comment]
Moved to next deploy

**Comment by ChaelKruip** [comment]
@dennisschoenmakers what is the priority of this?

**Comment by dennisschoenmakers** [comment]
> @dennisschoenmakers what is the priority of this?

Nice-to-have

**Comment by dennisschoenmakers** [comment]
I moved it to the next deploy

**Comment by grdw** [comment]
> Page should show some statistics about the Area selected (population, energy use?)

Including @jorisberkhout @ChaelKruip @antw . Does anybody have any strong opinions what the contents of those pages should be? Are these pages purely informative?

**Comment by jorisberkhout** [comment]
I like the idea of having an overview page with some statistics for each dataset. Could you elaborate a little more on what you would like to be displayed, @dennisschoenmakers ?

**Comment by dennisschoenmakers** [comment]
> Could you elaborate a little more on what you would like to be displayed, @dennisschoenmakers ?

I would say at least:

* Country name: the Netherlands
* Present year: 2013
* Last updated: 2 months ago

Then we need to be able to start a new scenario from here (so the user should be able to input the end year)

We could add some basic energy stats, but I would start with the basics. :smile:

**Comment by grdw** [comment]
> Last updated: 2 months ago

What would be the 2 months ago, the `mtime` of the `nl.yml` file in etsource or?

**Comment by dennisschoenmakers** [comment]
> What would be the 2 months ago, the mtime of the nl.ad file in etsource or?

Good question! People want to know when the last update was. Maybe other files also count? What do you think? :smile:

**Comment by grdw** [comment]
I would say: all these timestamps:
![screen shot 2016-01-27 at 11 10 23 am](https://cloud.githubusercontent.com/assets/2676542/12610181/99b4bfdc-c4e6-11e5-8a34-b83aec31fb51.png)

**Comment by dennisschoenmakers** [comment]
Perfect!

**Comment by grdw** [comment]
![screen shot 2016-01-27 at 11 52 47 am](https://cloud.githubusercontent.com/assets/2676542/12611368/8075da14-c4ec-11e5-86ce-272817aaf93a.png)

Minor preview thusfar.

Page is rather empty though.

**Comment by dennisschoenmakers** [comment]
> Page is rather empty though.

That's okay. Maybe we can make a bullet list of the characteristics?

And I guess people need to input the end year before they can start? How do you intend on making that? :smile:

**Comment by grdw** [comment]
> That's okay. Maybe we can make a bullet list of the characteristics?

Yes. I think we could.

> And I guess people need to input the end year before they can start? How do you intend on making that?

Well the button right now links to the front page and sets the select box to the correct country value. There the user picks the end year and creates the scenario.

**Comment by grdw** [comment]
Before continueing on with this issue I'd like to discuss what this page will do. It's nice to have but how will people know that there's such a page?

I can imagine that it would be nice if there's additional information about your dataset on the website of et-model itself but more in this fashion:

![screen shot 2016-01-27 at 2 04 26 pm](https://cloud.githubusercontent.com/assets/2676542/12614242/eafcc55c-c4fe-11e5-8734-657a9d5a144b.png)

Where 'here' would link to the page in fashion. If you change the select box the link changes ofcourse.

**Comment by ChaelKruip** [comment]
> Where 'here' would link to the page in fashion. 

Very nice idea @grdw! This seems like a logical place for such a link!

**Comment by jorisberkhout** [comment]
> Where 'here' would link to the page in fashion.

I like it too!

**Comment by antw** [comment]
> ![](https://cloud.githubusercontent.com/assets/2676542/12614242/eafcc55c-c4fe-11e5-8734-657a9d5a144b.png)

I'd swap that out for "$COUNTRY dataset information" where the whole thing is a link – [for accessibility reasons](https://www.w3.org/TR/WCAG10-HTML-TECHS/#link-text) – but otherwise I like the idea also.

**Comment by grdw** [comment]
> $COUNTRY dataset information

That's a bit better. We could also go completly minimal:

![information](https://cloud.githubusercontent.com/assets/2676542/12615234/c376fe0c-c504-11e5-94ac-754d122e5b09.png)

Where the I would link to the set page. However this could also be interpreted as a possible popup thingy.

**Comment by dennisschoenmakers** [comment]
> Well the button right now links to the front page and sets the select box to the correct country value. There the user picks the end year and creates the scenario.

Great idea!

**Comment by antw** [comment]
> However this could also be interpreted as a possible popup thingy.

Reminds me of a "help" button; I half-expect a pop-up to appear explaining what the country `<select>` does. But I like that we won't have to swap out `$COUNTRY` text which would be distracting to a visitor. I'm conflicted. :grimacing:

**Comment by grdw** [comment]
> I'm conflicted

For now; I'll just use "$COUNTRY dataset information" but might there come a time when minimal design becomes (more) hip, it'll be easy to switch. :)
