### ISSUE TITLE
CO2 emissions chart should show local and imported CO2 with separate colors

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1839]
Since https://github.com/quintel/etmodel/issues/1835, a new dashboard item has been created to show the CO2 that is emitted locally (excluding CO2 of imported electricity). The chart currently associated with both CO2 dashboard items shows the **total** CO2 (including imported):
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/4526459/64607ee8-4d5f-11e4-9c84-a108cb5ef32b.png)

It would be instructive to split the CO2 emissions into two parts: local and imported. I have made the gqueries to accomplish this but the chart is a [hard-coded custom one](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/d3/co2_emissions.coffee) so adding them in the normal way does not affect the chart.

**Comment by jorisberkhout** [comment]
@ChaelKruip , somehow this new chart does not appear when I click on the 'Domestic (a.k.a. local) CO2 emission dashboard item. Do you know why?

**Comment by ChaelKruip** [comment]
> @ChaelKruip , somehow this new chart does not appear when I click on the 'Domestic (a.k.a. local) CO2 emission dashboard item. Do you know why?

This is a custom chart that is defined in [ETModel](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/views/co2_emissions_chart_view.coffee). I need @antw to change this. The queries to make the grey and blue parts of the above chart are in [this commit](https://github.com/quintel/etsource/commit/f05f8d42543ef0806febe228ffbc29f8a32bd9c9). 

Assigning to @antw.

**Comment by antw** [comment]
On beta.

![screen shot 2015-09-29 at 18 13 13](https://cloud.githubusercontent.com/assets/4383/10172156/caa7fefc-66d5-11e5-9906-249684b9832c.png)

**Comment by ChaelKruip** [comment]
Very nice! :+1:

**Comment by antw** [comment]
Forgot about the table view. :grimacing: 

I'll get that fixed before the deploy.
