### ISSUE TITLE
The title for pop-up charts (for dashboard items) should be the same as their 'output element' title

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1847]
Related to https://github.com/quintel/etmodel/issues/1846.

The charts that pop-up whenever a dashboard item is clicked show a title defined in [e.g., en_dashboard_items.yml](https://github.com/quintel/etmodel/blob/master/config/locales/en_dashboard_items.yml). I think it would be better if the same title would be used as those described in [e.g., en_output_elements.yml](https://github.com/quintel/etmodel/blob/master/config/locales/en_output_elements.yml).

The direct reason for this request is that I want to use the same chart for the two CO2 dashboard items and I think it is confusing to the user that it now shows different titles depending on which dashboard item is used to open the chart.

**Comment by antw** [comment]
I think you make a fair point, and have adjusted the local CO2 chart title to read "Total CO2 emissions". 

Changing the pop-up to instead show the output element title – as you suggest – is a better solution, but this will require us to make an explicit (database) reference between the constraint and the output element, and necessitates a couple of changes to the rendering of the pop-ups. Doing so might also allow us to eliminate [a couple of templates](https://github.com/quintel/etmodel/tree/18e8c49bfdb8b9f67151adfaa6a31637e9d301ff/app/views/constraints), which is a nice bonus.

This is certainly doable, but will have to wait until the _next_ deploy.

**Comment by ChaelKruip** [comment]
> This is certainly doable, but will have to wait until the next deploy.

:+1:

**Comment by ChaelKruip** [comment]
Moving to next deploy as discussed in the issue

**Comment by jorisberkhout** [comment]
Assigning @grdw .

**Comment by grdw** [comment]
I'm a bit confused about the relation between a `constraint` and an `output_element`. How would they relate?

**Comment by antw** [comment]
A constraint would be better called a "dashboard item": one of the seven items which appears at the bottom of the page (energy use, CO2 emissions, energy imports etc). An output element is a chart or table, typically shown on the right-hand half of each page. If you click on a dashboard item, a chart or table ("output element") is normally shown.

As I recall, [there is no explicit relation between the two](https://github.com/quintel/etmodel/issues/1847#issuecomment-70525876) and most of these pop-up charts are set up [with their own HAML views](https://github.com/quintel/etmodel/tree/6e95fc94fff8e29a9202a18d48fe8dec35c428e6/app/views/constraints). I would guess that the ideal solution to this issue would involve adding an `output_element` association to `Constraint`, and use the output element's title [here](https://github.com/quintel/etmodel/blob/6e95fc94fff8e29a9202a18d48fe8dec35c428e6/app/views/constraints/show.html.haml#L2). If we could eliminate some of those partial HAML templates (which are almost all identical except for having a different `data-chart_id`) in favour of a generic template, that would be a nice added bonus,

**Comment by grdw** [comment]
> issue would involve adding an output_element association to Constraint

Thanks for the explanation but I guess what I was trying to ask is 'How they would relate?' but I'd guess Chael would just have to add an `output_element`-id to the `Constraint`?
