### ISSUE TITLE
DISCUSSION: Should we allow changes in the start-scenario?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1857]
This is a wild idea that has been bouncing around the heads of some of us for a while now. IMO it's time to discuss this for real!

The idea is simple: "Introduce a switch that toggles between 'edit 2013' and 'edit future year'".

The advantage of having this option is that the ETM becomes (much) more flexible. It would allow the user to compare, for example, scenario's for 2020 with 2030 within the ETM frame-work. 

Additional functionality could include:
- A button to copy the 'present' scenario to the 'future' scenario
- A button to do the opposite
- The possibility to load one (saved) scenario as the 'present' scenario and another one as the 'future' scenario

This extra functionality also makes a lot of sense in the context of 'testing grounds' where the starting situation in a local scenario often is very different from the national average.

@jorisberkhout @antw @dennisschoenmakers @AlexanderWirtz please share your thoughts!

**Comment by dennisschoenmakers** [comment]
:+1:

**Comment by AlexanderWirtz** [comment]
1. Love the idea and the possibilities it creates
2. Think this is a very advanced feature that is likely to confuse people, so we need to give it some thought how we solve this user-interface wise:
  a. start page
  b. charts / tables etc need to specify the scenario-values using something like a short key
