### ISSUE TITLE
"Bart Reinders" should be "Bram Reinders"

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1858]
![energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_](https://cloud.githubusercontent.com/assets/1303760/5643094/386450f6-9654-11e4-9aec-6536bebc8426.png)

**Comment by mariatsagkaraki** [comment]
Closed with https://github.com/quintel/etsource/commit/81cedbbee9e534d0a0d19adc07d6ec9186a0ee3b.
