### ISSUE TITLE
Private git repo linked in Open Source page

### ISSUE THREAD

**Issue by twilkinson573** [quintel/etmodel#1862]
There is a link to the etdataset repo in the Open Source static page (http://beta.et-model.com/open_source).

As this is a private git repo, non-Quintellers get a 404 Page Not Found redirect.

**Comment by ChaelKruip** [comment]
Assigning @dennisschoenmakers

**Comment by dennisschoenmakers** [comment]
Good catch! Could you change it to `etdataset-public` in [quintel/etcentral](https://github.com/quintel/etcentral) ?

**Comment by ChaelKruip** [comment]
@twilkinson573 what is the status of this?

**Comment by twilkinson573** [comment]
Fixed with quintel/etcentral@bd1f6e99a844e86f6c2b0f6f0a3a4ba790c6eedb
