### ISSUE TITLE
Quintel team portraits out of date on home page

### ISSUE THREAD

**Issue by twilkinson573** [quintel/etmodel#1863]
The Quintel team portraits are out of date on the home page (beta and live). 

The current latest set on of portraits on Quintel.com are also out of date for the moment, but that will hopefully be fixed soon.

**Comment by ChaelKruip** [comment]
Assigning @twilkinson573

**Comment by twilkinson573** [comment]
Fixed with ea16c68010669662e20cafb1af5c94a54e26e325
