### ISSUE TITLE
Which converters could use an efficiency slider?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1870]
Converters that are relevant (subjective!) per sector:

# Households

* households_solar_pv_solar_radiation
* households_water_heater_micro_chp_network_gas
* households_space_heater_micro_chp_network_gas
* households_water_heater_fuel_cell_chp_network_gas

# Buildings

* buildings_solar_pv_solar_radiation

# Energy 

* energy_chp_combined_cycle_network_gas
* energy_chp_supercritical_waste_mix
* energy_chp_ultra_supercritical_coal
* energy_chp_ultra_supercritical_cofiring_coal
* energy_chp_ultra_supercritical_lignite
* energy_interconnector_imported_electricity
* energy_power_combined_cycle_ccs_coal
* energy_power_combined_cycle_ccs_network_gas
* energy_power_combined_cycle_coal
* energy_power_combined_cycle_network_gas
* energy_power_engine_diesel
* energy_power_engine_network_gas
* energy_power_geothermal
* energy_power_hydro_mountain
* energy_power_hydro_river
* energy_power_nuclear_gen2_uranium_oxide
* energy_power_nuclear_gen3_uranium_oxide
* energy_power_solar_csp_solar_radiation
* energy_power_solar_pv_solar_radiation
* energy_power_supercritical_coal
* energy_power_supercritical_waste_mix
* energy_power_transformer_mv_hv_electricity
* energy_power_turbine_network_gas
* energy_power_ultra_supercritical_ccs_coal
* energy_power_ultra_supercritical_coal
* energy_power_ultra_supercritical_cofiring_coal
* energy_power_ultra_supercritical_crude_oil
* energy_power_ultra_supercritical_lignite
* energy_power_ultra_supercritical_network_gas
* energy_power_ultra_supercritical_oxyfuel_ccs_lignite
* energy_power_wind_turbine_coastal
* energy_power_wind_turbine_inland
* energy_power_wind_turbine_offshore

**Comment by ChaelKruip** [comment]
Assigning to @AlexanderWirtz for review

**Comment by AlexanderWirtz** [comment]
@ChaelKruip good list. My thoughts:

1. I would rather start with all electricity (power) production options (not the CHP ones, although some may depend on the electricity efficiency sliders for power plants). Conventional plants excluded of course, since they will not improve anymore.
2. The car and truck already have such sliders
3. Heating options are secondary I would say

What do you think? How much time would it take to at least create the update statements to be able to adjust electricity output efficiencies for all electricity producing technologies, except the conventional ones? This way we can at least change these using the API

**Comment by ChaelKruip** [comment]
> I would rather start with all electricity (power) production options (not the CHP ones, although some may depend on the electricity efficiency sliders for power plants). Conventional plants excluded of course, since they will not improve anymore.

@AlexanderWirtz I think it would be easiest if you add the ones you have in mind to the list above since you seem to have clear ideas about which are relevant.

> The car and truck already have such sliders

I have removed them

> How much time would it take to at least create the update statements to be able to adjust electricity output efficiencies for all electricity producing technologies, except the conventional ones?

One day I would think. The main issues I foresee are:
* research for the slider caps 
* possible complexities with co-firing plants (how are the efficiencies for multiple input carriers related?)

**Comment by ChaelKruip** [comment]
@AlexanderWirtz where would you think these sliders should be placed? Next to the `number_of_units` sliders for relevant technologies? Or should we make a new sidebar item (section) for efficiencies?

**Comment by AlexanderWirtz** [comment]
HAS this issue beenanswered, @ChaelKruip

**Comment by ChaelKruip** [comment]
I think so, further discussion will follow but this can be closed.
