### ISSUE TITLE
"Testing ground" should not be used as a name anymore

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1877]
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/7606152/9d3871be-f956-11e4-9a40-7ffa200b1653.png)
and
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/7606168/b9717ea2-f956-11e4-8c02-83a3ae1c7cd4.png)
and
![ivy](https://cloud.githubusercontent.com/assets/1303760/7606192/f03b099e-f956-11e4-8150-0e20b1fe23d8.png)

need to be rephrased.

@dennisschoenmakers What do you think we should use for a name?

Suggestions:
* Testing ground => local energy solution
* ETM testing ground/ETLoader/Ivy/ETM local => ETM plus

**Comment by dennisschoenmakers** [comment]
I like 'Local Energy Solution', because you can put it in a sentence like: 

> Create Local Energy Solution (LES)

**Comment by ChaelKruip** [comment]
Closing.
