### ISSUE TITLE
Scaling page redesign

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1882]
We only support 'residences' for now.

**Comment by ChaelKruip** [comment]
![screen shot 2015-07-03 at 14 47 25](https://cloud.githubusercontent.com/assets/1303760/8499383/7574a33c-2192-11e5-8c49-99d504527239.png)

**Comment by grdw** [comment]
See #1883

**Comment by grdw** [comment]
![screen shot 2015-09-17 at 3 55 11 pm](https://cloud.githubusercontent.com/assets/2676542/9935008/a8824970-5d54-11e5-9748-8a979a07c85b.png)

Made the box white. Just like the rest. The tabs should be gone aswell but I'd like to beleive that there's a purpose for them?

**Comment by ChaelKruip** [comment]
> The tabs should be gone aswell but I'd like to beleive that there's a purpose for them?

I don't understand what you mean :confused: 
I think the option to scale saved scenario's is redundant because the user can open any saved scenario from the ETM interface and then scale it. So, the tab can go as far as I'm concerned.

**Comment by antw** [comment]
I think the "Scale saved scenario" tab can be removed completely. It made sense in an older iteration of the UI, but it seems pointless now.

Maybe make the background `#DFE8F3` (same as the footer) to make it stand out a bit more?

![screen shot 2015-09-17 at 14 59 56](https://cloud.githubusercontent.com/assets/4383/9935139/e7da159c-5d4c-11e5-8118-2e7f1ca73303.png)

**Comment by grdw** [comment]
I would result in:

![screen shot 2015-09-17 at 4 03 18 pm](https://cloud.githubusercontent.com/assets/2676542/9935240/d2ba4cbe-5d55-11e5-8b2e-03d899e6cf07.png)

It's lonely in the middle though. But I think this will do for now.

**Comment by ChaelKruip** [comment]
> But I think this will do for now.

:+1:

**Comment by antw** [comment]
Being super-picky again, sorry:

I wonder if we really need to show the country and year. The user chose these when creating their scenario; is the information useful, or is it distracting from the real purpose of the page?

![screen shot 2015-09-17 at 15 13 17](https://cloud.githubusercontent.com/assets/4383/9935460/a5304e80-5d4e-11e5-9216-cd57aff27442.png)

No need to change it to this, just soliciting feedback. :smiley:

**Comment by ChaelKruip** [comment]
> Being super-picky again, sorry

Welcome to the OCD-team!

>  just soliciting feedback.

I like the minimalistic look. :+1:

**Comment by ChaelKruip** [comment]
Removing this milestone.

**Comment by ChaelKruip** [comment]
This has been done. Closing.
