### ISSUE TITLE
Flexibility sliders, charts and sidebar item need to be hidden for now

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1884]
The sidebar item:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/9220096/37fa9df0-40e0-11e5-9886-1ba1e5453a1d.png)
The P2H slider:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/9220104/4b064818-40e0-11e5-8b1f-13187703d785.png)
The "Use of excess electricity" chart should not be selectable anymore:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/9220134/788ba440-40e0-11e5-8bd5-2c4df2e417f2.png)

**Comment by antw** [comment]
Tabs – the main sidebar items – have been made "area dependent" and a new `_always_hidden` dependancy has been added, which does as you'd expect.

The flexibility tab, P2H slider, and excess electricity chart have been hidden on beta.
