### ISSUE TITLE
CO2 mekko cannot yet use 'tonne' as unit

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1886]
I have used PJ as the unit for [the CO2 Mekko](http://beta.pro.et-model.com/admin/output_elements/165) now but this does not make sense for CO2 emissions. 

Also, I am not sure how flexible this is. I think tonne might be the right unit but perhaps megaton (Mton) would format the numbers better. For your reference: the total emission of NL is about 160 Mton.

**Comment by antw** [comment]
I set the chart unit to `T` and get this:

<img width="607" alt="screen shot 2015-09-29 at 10 47 49" src="https://cloud.githubusercontent.com/assets/4383/10160775/9169d662-6697-11e5-9092-d059840445da.png">

Looks good to me; what do you think @ChaelKruip?

**Comment by ChaelKruip** [comment]
> Looks good to me; what do you think @ChaelKruip?

:+1: :+1:
