### ISSUE TITLE
CO2 emission in dashboard: items incl. and excl. imported electricity not clearly distinguished

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#1888]
As agreed with @ChaelKruip 

There are two CO2 emissions dashboard items. The default included emissions for imported electricity. An alternative item can be chosen using the `change` button. This alternative item called `Local CO2 emissions` has some minor bugs:

1. It has the same title in the menu where items can be changed (see below)
- It doesn't have an alternative chart associated with it. The chart still shows CO2 emissions including imported electricity for `present_year` and `future_year`.
- It is not the default item

![image](https://cloud.githubusercontent.com/assets/308563/9306202/0d2fbd60-44f7-11e5-8da7-da6cb6e0587a.png)

## proposed fixes:

1. In the menu, name one `CO2 emissions incl. imported electricity` and the other `CO2 emissions` or `National CO2 emissions` or (shudder) `Local CO2 emissions`
- Create a dedicated chart that calculates local CO2 emissions for `present_year` and `future_year`
- Make this item the default item (but rename to `National CO2 emissions` or sth)
 
notifying @jorisberkhout

**Comment by ChaelKruip** [comment]
Closing this a the main points have been carried out.
