### ISSUE TITLE
CO2 charts show MT incorrectly

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1889]
This goes for all charts with MT as unit:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/9355962/d1413a9e-467d-11e5-9631-4c4c4016746b.png)
The '5' should be a '50', the '1' a '100' and the '15' a '150'...

**Comment by antw** [comment]
Seems I was a bit too aggressive in [striping zeroes](https://github.com/quintel/etmodel/commit/e5357eb9de2766a105201b8aefe1c0317fd2a9c8) when formatting numbers. That's embarrassing.
