### ISSUE TITLE
Other metals slide unclear

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#1891]
These sliders set efficiency, but you wouldn't know it until you read the text on the slide:
![image](https://cloud.githubusercontent.com/assets/308563/9518647/a9b3a3b8-4cb8-11e5-9687-990ae96b74b8.png)

Let's change this to:
nl: `Efficiëntieverbeteringen overige metalen`
en: `Efficiency improvements other metals`

@jorisberkhout 
@ChaelKruip 
let me know if you disagree

**Comment by ChaelKruip** [comment]
Fine with me! :+1:
