### ISSUE TITLE
Users should be able to retrieve their password

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1894]
With a 'I forgot my password' type of link...

Perhaps it makes sense to add a 'my profile' page where you can see your scenario's and change your account information.

@dennisschoenmakers please re-assign at your discretion.

**Comment by jorisberkhout** [comment]
After discussion with @grdw , I decided to remove the `CRITICAL` label 😉

**Comment by dennisschoenmakers** [comment]
![image](https://cloud.githubusercontent.com/assets/104830/16952176/681d584c-4dc8-11e6-8b4e-228595ce65d8.png)

**Comment by grdw** [comment]
A user should not forget his password in the first place.

![blame](https://devhumor.com/content/uploads//images/March2016/blame-user.jpg)

**Comment by michieldenhaan** [comment]
Closing, this has been implemented
