### ISSUE TITLE
Scenario scaling functionality uses 'present' value of AREA attribute 'number_of_residences'. It should use the 'future' value.

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#1895]
The scaling does not result in the desired number of residences. e.g. Scaling to 100 residences results in a number of residences that is higher, if the number of residences are higher in the future than in the present. We have determined this is because the scaling functionality uses the following ratio to scale the future numbers:

`number_of_residences_for_scaling` / `present:AREA(number_of_residences)`

I think it should be this ratio, though;

`number_of_residences_for_scaling` / `future:AREA(number_of_residences)`

Yes, I made up the first of these attributes... 

## Example:
Scaling to 250 residences for the following situation:

![image](https://cloud.githubusercontent.com/assets/308563/9763975/c7f91138-570c-11e5-8ef2-02b19d837081.png)

This results in:
`193+88=281` residences! 
This happens to equal `250 * 8.3 / 7.387`

![image](https://cloud.githubusercontent.com/assets/308563/9764042/16982306-570d-11e5-9efa-5871b708e5a8.png)

## Background
I am creating scaled scenarios for a project John and I are working on. These are due early next week and a lot remains to be done. Hence the `priority` tag.

Notifying @ChaelKruip and @dennisschoenmakers

**Comment by antw** [comment]
I have pushed and deployed a fix. I expected to have to use an ugly hack to achieve this but luckily found a workaround in the latest commit.

It should now work as you expect.

1. Set new households to 5M
2. Set old households to 5M
3. Scale to 1,000 households

The resulting scenario has 500 old and 500 new.

**Comment by AlexanderWirtz** [comment]
@antw works like a charm! :smile:
