### ISSUE TITLE
Dashboard cost item should say bln/yr

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#1896]
Now it's unclear that the costs are yearly costs. cc @AlexanderWirtz @ChaelKruip

**Comment by AlexanderWirtz** [comment]
+1

**Comment by ChaelKruip** [comment]
Good idea! I have located [where this can be done](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/views/constraint_view.coffee#L28) but I don't know how to make the string dependent on the language (e.g, 'yr' and 'jr').
I need some help from @antw for that.

Also, the Dutch abbreviation for 'jaar' is not clear to me. Is it 'jr' or 'j'? Any preferences?

**Comment by dennisschoenmakers** [comment]
I would say 'jr'

**Comment by antw** [comment]
We already had a "man_years" unit (for which the Dutch translation was set to "jr"), so I reused that.

> I have located where this can be done

Thanks for that. It's genuinely really helpful to be pointed at the appropriate lines of code (when possible); it turns a "uhh, I guess I'll have to find the offending code at some point *once I've done these other tasks*" into "I can do that right now!". :+1:

**Comment by ChaelKruip** [comment]
> It's genuinely really helpful to be pointed at the appropriate lines of code

I'll keep that in mind! :)
