### ISSUE TITLE
In the renewabilities chart, could we depict other fuels?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#1897]
e.g. when renewability percentage is 13.8%, could we indicate what the remainder consists of?

I understand that due to the complex definition of renewability this is **not** an easy task. :grin:

**Comment by ChaelKruip** [comment]
Interesting point @dennisschoenmakers!

Do you mean something like this:
![20141209_topology_interface_v1_key](https://cloud.githubusercontent.com/assets/1303760/9783347/ed1ccc60-57a3-11e5-94f5-bf677d3aaca5.png)
?

But would that not raise the question what the subdivision of 'renewable' is (solar, wind, hydro, biomass etc?)

Then, if we would also make that subdivision would it still be clear what the renewable percentage is?

**Comment by dennisschoenmakers** [comment]
> Do you mean something like this:

Yes, and I would also display the information on the left hand side (present year).

> But would that not raise the question what the subdivision of 'renewable' is (solar, wind, hydro, biomass etc?)

We could make a subdivision visible using shades of green?

![image](https://cloud.githubusercontent.com/assets/104830/9783531/38ec8562-57a5-11e5-9a27-01d601243e3e.png)

> Then, if we would also make that subdivision would it still be clear what the renewable percentage is?

That percentage will still be visible in the dashboard, right?

**Comment by ChaelKruip** [comment]
> Yes, and I would also display the information on the left hand side (present year).

I was lazy :blush: 

> We could make a subdivision visible using shades of green?

Yes, but that would be a deviation from our normal color scheme e.g.,:
![energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_](https://cloud.githubusercontent.com/assets/1303760/9783612/e9c2d904-57a5-11e5-9551-8bd7fced3d4e.png)

> That percentage will still be visible in the dashboard, right?

Good point!

**Comment by dennisschoenmakers** [comment]
> that would be a deviation from our normal color scheme e.g.

True!

**Comment by ChaelKruip** [comment]
I have kept the colours consistent with the rest of the ETM. What do you think @dennisschoenmakers @AlexanderWirtz is this enough of an improvement to justify inclusion in the upcoming deploy?
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/9791567/e81bf5c8-57db-11e5-94cc-3392310d8bcb.png)

**Comment by dennisschoenmakers** [comment]
:+1: I like it mucho!

**Comment by AlexanderWirtz** [comment]
I do too. Can we see green gas in this? Or does it all default to biomass?

**Comment by ChaelKruip** [comment]
> Can we see green gas in this? Or does it all default to biomass?

Green gas is taken together with the ingredients for making biogas (corn and manure) and other biofuels in the 'biomass' category. Perhaps I can rename that to 'biofuels'?
I think green gas does not really deserve a different status here do you @AlexanderWirtz?

**Comment by AlexanderWirtz** [comment]
biofuels is confusing too. biomass is least confusing imo

**Comment by AlexanderWirtz** [comment]
@ChaelKruip this chart is not available yet, is it?

**Comment by ChaelKruip** [comment]
> @ChaelKruip this chart is not available yet, is it?

No, unfortunately, my approach of tracing final demand back to primary carriers seems to result in a different renewability percentage than the `renewable_factor` calculation which is used to calculate the dashboard item. Once I have found out why there is a discrepancy, I will put the chart on BETA.

**Comment by ChaelKruip** [comment]
Also see https://github.com/quintel/etengine/issues/785

**Comment by ChaelKruip** [comment]
I have made a new concept chart that is in line with the current definition of renewability (based on final demand). The chart displays the final demand carrier groups. For the carriers that have partial renewability:

* heat 
* electricity
* gas

I have made two queries. One for the sustainable, and one for the fossil part of the carrier(group):
![cursor_and_energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/10044352/863d50e4-61fa-11e5-8b4b-5aac4ad176cd.png)

It can be deployed next week if you like this better than the current chart.
@dennisschoenmakers @AlexanderWirtz @jorisberkhout tell me what you think!

**Comment by ChaelKruip** [comment]
Perhaps I could tweak the color scheme a bit :smile:

**Comment by dennisschoenmakers** [comment]
Excellent work Chael! So much more informative now! I vote in favour of
making this the pop-up chart when you press the renewability percentage in
the dashboard.

**Comment by AlexanderWirtz** [comment]
hear hear! I like it a lot! :+1:
