### ISSUE TITLE
Could max value/caps of slider be a bit more forgiving?

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etmodel#1898]
Problem now is that sometimes somebody (read: @AlexanderWirtz) wants to put more than is permitted in a (scaled) scenario, but the max value of the slider does not permit that.

Could we allow the user to input _any_ value in the text field of the slider, and, when it is _larger_ than the current max of the slider, it should set the max of the slider to that value. 

Of course, this does not apply to percentage sliders :grinning: 

cc @ChaelKruip @jorisberkhout

**Comment by ChaelKruip** [comment]
> Of course, this does not apply to percentage sliders

Do you mean the percentage sliders that form a slider-group and need to add up to 100%? We also have % sliders that can be outside the 0-100 range:
![energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_](https://cloud.githubusercontent.com/assets/1303760/9785241/18c56b44-57b1-11e5-885a-7f5fa30a69f0.png)

**Comment by AlexanderWirtz** [comment]
I believe that is what @dennisschoenmakers is referring too. I mostly want to recreate the current power production park in the northeast of Groningen province. I am not allowed to build all the coal plants they actually have, though.

**Comment by dennisschoenmakers** [comment]
> Do you mean the percentage sliders that form a slider-group and need to add up to 100%? 

Yes, I do. You don't want to upset them. :smile:

> We also have % sliders that can be outside the 0-100 range:

It would be nice if they would also be flexible, you never know. We could then also restrict the max a bit more for normal users and allow elasticity whenever an expert needs it.

**Comment by antw** [comment]
While I don't see any obvious technical reason preventing this, I would estimate this has *moderate* impact.

* Our slider library enforces that values are valid (within the minimum and maximum).
* [ETEngine asserts that values are valid](https://github.com/quintel/etengine/blob/e15ac4eda9500d970019c608020e508334a86a8e/app/models/api/v3/scenario_updater.rb#L79-L94).

I think the behaviour of the slider could be a bit weird in the event you choose a larger- or smaller-than-permitted value: if the max value is 20, and you enter a custom value of 200 then touch the slider, it's going to jump back to 20.

My suggestion:

1. Add a new option to the settings menu allowing you to enter "exceptional" values. This is optional – and I'm not 100% sure about it – but I expect that it is useful to retain protection against wrong values for *most* users.

2. Allow entry of values into the text field which exceed the minima or maxima.

3. Extend the range of the slider to include the new value. In the above example, the slider's maximum value would be changed to 200 *for that scenario*.

This does still mean removing the validation from ETEngine, which is a pity, but I don't think that's a huge loss. We could likely keep validation for inputs whose unit is `%`, and those belonging to a share group.

**Comment by dennisschoenmakers** [comment]
@antw I like all of your suggestions!
