### ISSUE TITLE
Scaling of national scenario's should not scale the employment_economic_multiplier slider

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#1900]
This slider is typically `1 x`, but in the scaled scenario's for Groningen it gets scaled to: `0.076 x`
It should just stay `1 x` or am I missing something?

@ChaelKruip and @dennisschoenmakers including you two. Please decide if this is worth bothering @antw with

**Comment by antw** [comment]
It appears [the input](https://github.com/quintel/etsource/blob/23e8a9ae1c7967be8780f74b933eefb4dfb943de/inputs/modules/employment/employment_economic_multiplier.ad) doesn't have a `unit`. If we add `- unit = x`, the problem should go away.

All inputs get scaled [except those whose unit is `%`, `x`, or `m^2K/W`](https://github.com/quintel/etengine/blob/72349ac7dcf6c12d9cbc7700f763976b62f984b5/app/models/scenario_scaling.rb#L8).

**Comment by AlexanderWirtz** [comment]
@antw sounds like a solution to me. what's your opinion @ChaelKruip

**Comment by ChaelKruip** [comment]
> what's your opinion @ChaelKruip

:+1: 

Is this the only input that has to be 'unscaled' @AlexanderWirtz? I'd rather do them all at once if there are several.

**Comment by AlexanderWirtz** [comment]
haven't spotted anything
