### ISSUE TITLE
Adding Charts for Well-to-Wheel efficiencies in the transport sidebar?

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1901]
With a view to user experience,  it might be a good idea (if possible) to add a chart which shows the well-to-wheel efficiencies (i.e. efficiencies as taken over all steps from primary carriers to energy output of the vehicle) for all fuels used in the car technology slide. 

Right now, the user defines supply and demand - the efficiencies of intermediate processes are behind the scenes, so to speak. Including such a chart would allow the user to see how changes in other parts of the model reflect on the WTW efficiency, and make a good side-by-side comparison of various car technologies.

Below some initial thoughts and suggestions on what could be such a chart,  please share your ideas and feedback!

The chart could take up the form of a dynamic table with a flow from primary carriers to vehicles and include efficiencies per step, similar to the example below.

![screen shot 2015-09-10 at 16 57 09](https://cloud.githubusercontent.com/assets/14106387/9903221/f9d1c8f4-5c74-11e5-9e84-b228132d53e4.png)

The chart for the ETM could consist of the primary carriers on the left, followed by production (incl. ' production' of electricity for BEVs), followed by distribution, followed by TTW efficiency of the vehicle and lastly the WTW efficiency. The efficiencies for **production** could be the weighted average of the individual production techniques (e.g. there are many electricity generating processes and their efficiencies shouldn't be listed individually in this chart). In the **distribution** part, the various technologies yielding the same energy carrier (and 'electricity') could be funnelled together (e.g., biodiesel and diesel, their ratio also shown (as selected by the user selects in the supply - transport fuels sidebar). Lastly, the **TTW efficiencies** are already included in the converters and the **WTW efficiency** is the product of the efficiencies of the intermediate steps.

These are just some ideas, but @jorisberkhout , @ChaelKruip , @AlexanderWirtz , and @dennisschoenmakers , what do you think? Does it seem worthwhile, and feasible?

**Comment by dennisschoenmakers** [comment]
Excellent idea @RobTerwel ! :+1:

I think we could at least start with comparing two or three options. Of course, we can use the electricity fuel fix from your supply part of the scenario.

**Comment by RobTerwel** [comment]
Changing status to 'on hold'.

**Comment by jorisberkhout** [comment]
Removing milestone 'Deploy Februari 2016'.
