### ISSUE TITLE
List of links and videos in information which don't work

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1905]
This list will be updated and contains all links in the information (question marks next to sliders) which don't work.

Embedded videos - Streams not found

- [ ] Demand - Household energy demand - Space heating - Heat pump (ground)
- [ ] Demand - Household energy demand - Solar panels - PV panels
- [ ] Demand - Buildings - Space Heating - Solar thermal panels
- [ ] Demand - Transportation - Car Technology - Compressed gas
- [ ] Costs - Solar power - Solar power costs
- [ ] Costs - CO2 emissions costs - CCS - CCS investment
- [ ] Supply - Electricity - Coal Plants
 
Links

- [ ] Demand - Household energy demand - Climate

Re-assign at will.

**Comment by ChaelKruip** [comment]
Assigning @grdw

**Comment by grdw** [comment]
I found out that they come from an external resource called http://www.new-energy.tv

I'm wondering if they just moved the videos or that they are actually gone.

**Comment by grdw** [comment]
I think they switched from their own Flash video uploading tool to Youtube. And removed all the old videos.  The quick solution would be to remove the old videos from the database by hand and replace them with the Youtube one's, if the Youtube one's exist... If someone could help identify the correct Youtube movies, that would be nice? :smile:

**Comment by grdw** [comment]
### Staging database removed:

Embedded videos - Streams not found

- [ ] Demand - Household energy demand - Space heating - Heat pump (ground)
- [ ] Demand - Household energy demand - Solar panels - PV panels
- [ ] Demand - Buildings - Space Heating - Solar thermal panels
- [ ] Demand - Transportation - Car Technology - Compressed gas
- [ ] Costs - Solar power - Solar power costs
- [ ] Costs - CO2 emissions costs - CCS - CCS investment
- [ ] Supply - Electricity - Coal Plants
 
Links

- [ ] Demand - Household energy demand - Climate

---

### Production database removed

Embedded videos - Streams not found

- [ ] Demand - Household energy demand - Space heating - Heat pump (ground)
- [ ] Demand - Household energy demand - Solar panels - PV panels
- [ ] Demand - Buildings - Space Heating - Solar thermal panels
- [ ] Demand - Transportation - Car Technology - Compressed gas
- [ ] Costs - Solar power - Solar power costs
- [ ] Costs - CO2 emissions costs - CCS - CCS investment
- [ ] Supply - Electricity - Coal Plants
 
Links

- [ ] Demand - Household energy demand - Climate

---

### Production database replaced

Embedded videos - Streams not found

- [ ] Demand - Household energy demand - Space heating - Heat pump (ground)
- [ ] Demand - Household energy demand - Solar panels - PV panels
- [ ] Demand - Buildings - Space Heating - Solar thermal panels
- [ ] Demand - Transportation - Car Technology - Compressed gas
- [ ] Costs - Solar power - Solar power costs
- [ ] Costs - CO2 emissions costs - CCS - CCS investment
- [ ] Supply - Electricity - Coal Plants
 
Links

- [ ] Demand - Household energy demand - Climate

**Comment by ChaelKruip** [comment]
> @ChaelKruip maybe you could help me find those videos through http://new-energy.tv? Or should we just keep them removed for now?

Let's keep them removed. @dennisschoenmakers @AlexanderWirtz what do you think? Very few people watch movies through the ETM is my feeling.

**Comment by dennisschoenmakers** [comment]
> Let's keep them removed. @dennisschoenmakers @AlexanderWirtz what do you think? Very few people watch movies through the ETM is my feeling.

Agree.

**Comment by ChaelKruip** [comment]
Closing.
