### ISSUE TITLE
Sliders adding up to percentages slightly greater or smaller than 100%

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1906]
Some percentage sliders don't always give rise to a 100% total, but 99.9% or 100.1% e.g.:

![screen shot 2015-09-28 at 10 55 38](https://cloud.githubusercontent.com/assets/14106387/10133017/7c159098-65da-11e5-9fd1-0e62ff96fcfc.png)

This is not something that occurs for fixed ratios, because I've managed to start a new scenario and actually get to 12/76/12 %, giving the 100% total as expected. It seems to depend on the order and extent with which you change the sliders.

@antw , does this have something to do with the way in which percentages get calculated or rounded off?

**Comment by RobTerwel** [comment]
In addition to the foregoing, in a **clean** Netherlands 2050 scenario on beta the demand - buildings - space heating sliders start off totalling 100.1%.

![screen shot 2015-09-28 at 13 34 02](https://cloud.githubusercontent.com/assets/14106387/10134398/cc74599c-65e5-11e5-854e-1a97441380c7.png)

**Comment by antw** [comment]
This is just a display issue caused by rounding the numbers to one decimal place. This is fixable, but probably not in time for tomorrow's deploy.

**Comment by ChaelKruip** [comment]
> This is fixable, but probably not in time for tomorrow's deploy.

I think this very low priority.

**Comment by jorisberkhout** [comment]
Assigning, @grdw. Low priority though.

**Comment by grdw** [comment]
> This is just a display issue caused by rounding the numbers to one decimal place

It is. But with rounding in the right places this doesn't get solved .. or I don't do it in the right places. What we could do is maybe add a `title` to the output with the full value (no rounding)?

**Comment by jorisberkhout** [comment]
Not deploy critical.
