### ISSUE TITLE
Unfinished Storage Sidebar is still present on beta front-end

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1909]
![screen shot 2015-09-28 at 17 21 55](https://cloud.githubusercontent.com/assets/14106387/10139974/b934effc-6605-11e5-8f38-8dad4bc2ddb6.png)

Shouldn't the Costs - Storage section be removed from the front end before September's deploy as it is unfinished but shows up nonetheless?

Re-assign at will.

**Comment by ChaelKruip** [comment]
Assigning @antw
