### ISSUE TITLE
Ghost Appearance of Input Fuel Mix in technical and financial information

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1913]
At random, when accessing the information about a slider and clicking the `technical and financial information`, a table appears which includes the input fuel mix. This indeed seems to occur haphazardly, as it does not show up every time for the same slider and it also appears for sliders for which this is out of place (e.g. input for wind turbines, see image).

![screen shot 2015-09-29 at 10 06 47](https://cloud.githubusercontent.com/assets/14106387/10158459/90f0d0aa-6692-11e5-89f9-5e1ee7606984.png)

Re-assign at will.

**Comment by ChaelKruip** [comment]
Assigned @antw. Minor issue.

**Comment by ChaelKruip** [comment]
Moving to next deploy

**Comment by jorisberkhout** [comment]
Assigning @grdw .

**Comment by grdw** [comment]
I tried really hard clicking my way into this but "at random" is really hard to trigger :sweat_smile:

**Comment by RobTerwel** [comment]
You can reproduce it as follows:

-> Go to supply - electricity - coal plants - Co-firing coal plant for district heat (CHP) - info - technical and financial properties

You'll see input shares, as you'd expect from a co-firing coal plant. Next, 
-> go to gas plants - Gas plant for district heat (CHP) - info - technical and financial properties and ...

![image](https://cloud.githubusercontent.com/assets/14106387/12516069/ce64cf60-c12b-11e5-85ec-cfca5180b346.png)
 
we see input shares of coal, wood pellets and torrified biomass pellets, for a gas plant.

This bug seems to be triggered by opening a technical and financial properties link from a converter that does have input shares for these carriers.

**Comment by grdw** [comment]
Update: the problem lies within Et-engine. Am not sure what yet, but somehow it returns the fuel mix while it should not have returned it in the first place.

**Comment by grdw** [comment]
The reason this is going bad is because of [here](https://github.com/quintel/etengine/blob/master/app/models/api/v3/converter_presenter_data.rb#L198-L213). If you print out the `current_fuel_input_mix` to the log it will give you a set of data after the second request eventhough `out` is cleared on line 198. @antw would you know why? Is this because of the GC stats thingy?

**Comment by antw** [comment]
Is it possible that under `uses_coal_and_wood_pellets?` we just need to `out = out.dup`? It looks like [line 206](https://github.com/quintel/etengine/blob/478c572470ca294612fb9d886bd37e900a68acc4/app/models/api/v3/converter_presenter_data.rb#L206) might be editing the `*_ATTRIBUTES_AND_METHODS` constants.

**Comment by grdw** [comment]
> we just need to out = out.dup?

Yes, that works. :+1:  But I'm not sure why it works. On line 198 we say `out = {}`. How does it - after two request - maintain the `current_fuel_input_mix`? 

Previous contents:
````ruby
{"coal_input_conversion"=>{:label=>"Coal", :unit=>"%"}, "torrified_biomass_pellets_input_conversion"=>{:label=>"Torrified biomass pellets", :unit=>"%"}, "wood_pellets_input
_conversion"=>{:label=>"Wood pellets", :unit=>"%"}}
````

**Comment by antw** [comment]
> On line 198 we say out = {}. How does it - after two request - maintain the current_fuel_input_mix?

[The next line](https://github.com/quintel/etengine/blob/478c572470ca294612fb9d886bd37e900a68acc4/app/models/api/v3/converter_presenter_data.rb#L199) says: if converter is a member of the `cost_traditional_heat` group, `out = HEAT_PRODUCTION_ATTRIBUTES_AND_METHODS`. Then line 205: "if converter uses coal and wood pellets" `out[:current_fuel_input_mix] = ...`.

If a converter was a member of one of the `cost` groups, *and* uses coal and wood pellets, it would edit the hash constant. That change would persist in the Rails/Unicorn process and affect every subsequent request which uses that constant.

This is why I make a habit of calling `freeze` on constants these days. :smiley:

--

1. Request a cost_traditional_heat converter, with coal and wood pellets:
  * [Uses `HEAT_PRODUCTION_ATTRIBUTES` constant](https://github.com/quintel/etengine/blob/478c572470ca294612fb9d886bd37e900a68acc4/app/models/api/v3/converter_presenter_data.rb#L199)
  * [Edits the `current_fuel_input_mix` attribute](https://github.com/quintel/etengine/blob/478c572470ca294612fb9d886bd37e900a68acc4/app/models/api/v3/converter_presenter_data.rb#L211)
2. Request a cost_traditional_heat converter which does not use coal and wood pellets:
  * [Uses `HEAT_PRODUCTION_ATTRIBUTES`](https://github.com/quintel/etengine/blob/478c572470ca294612fb9d886bd37e900a68acc4/app/models/api/v3/converter_presenter_data.rb#L199) (`current_fuel_input_mix` is still in there from the previous request).
  * [Does not edit the `current_fuel_input_mix`](https://github.com/quintel/etengine/blob/478c572470ca294612fb9d886bd37e900a68acc4/app/models/api/v3/converter_presenter_data.rb#L205), therefore the value is unchanged from request (1).

**Comment by grdw** [comment]
@antw Thanks for explaining.

> it would edit the hash constant

:fearful: Not much of a constant than.

**Comment by antw** [comment]
> Not much of a constant than.

Yup! Constants can be reassigned in Ruby; you'll get a warning, but you're allowed to do it.

```ruby
[1] pry(main)> A = 1
=> 1
[2] pry(main)> A = 2
(pry):2: warning: already initialized constant A
(pry):1: warning: previous definition of A was here
=> 2
```

The *contents* of an object assigned to a constant (such as a string, array, or hash) can be modified with no warning given at all.

```ruby
[1] pry(main)> A = 'abc'
=> "abc"
[2] pry(main)> A[1] = 'z'
=> "z"
[3] pry(main)> A
=> "azc"
```

These days I freeze objects assigned to constants, but even that provides limited protection. For example, if you have a hash *inside* a frozen hash, you can modify it:

```ruby
[1] pry(main)> A = { a: { z: 1 }, b: 2 }.freeze
=> {:a=>{:z=>1}, :b=>2}
[2] pry(main)> A[:a][:z] = 9
=> 9
[3] pry(main)> A
=> {:a=>{:z=>9}, :b=>2}
```

[IceNine](https://github.com/dkubb/ice_nine) provides a solution. Maybe we should use it more often?

**Comment by grdw** [comment]
> For example, if you have a hash inside a frozen hash

That's the same in JavaScript ES>5

> Maybe we should use it more often?

I would say in the case of Hashes in Hashes: yes.
