### ISSUE TITLE
Liquid Biofuels changes in FCE reflected in chart, but not on dashboard

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1915]
When one changes the feedstock for `Liquid biofuels` in `Fuel chain emissions`, the chart on the right reflects the changes but the dashboard doesn't. Going from 100% `sugar beets` to 100% `sugar cane` leads to a decrease of more than 10 kg/GJ in the fuel production chart next to it but has no effect on the dashboard. 

![screen shot 2015-09-29 at 10 32 09](https://cloud.githubusercontent.com/assets/14106387/10158953/6f93356c-6695-11e5-9d36-5ab8183136ea.png)
**to**
![screen shot 2015-09-29 at 10 32 31](https://cloud.githubusercontent.com/assets/14106387/10158956/754e5108-6695-11e5-8b2f-5976dce2076e.png)

I made sure there was enough biodiesel and bio-ethanol being used by setting the diesel and gasoline composition to be 100% bio and having all cars and trucks run on gasoline and diesel. FCE was off, but that shouldn't matter as  "[y]our mix of origins will change CO2 emissions, regardless of whether 'FCE' is 'ON' or 'OFF'."

With such a consumption of biofuels, changing the production pathway should have noticeable effects on the dashboard, but it does not seem to be connected.

**Comment by ChaelKruip** [comment]
Including @AlexanderWirtz @jorisberkhout do you have any ideas why this could be?

**Comment by AlexanderWirtz** [comment]
@RobTerwel:
> FCE was off, but that shouldn't matter as "[y]our mix of origins will change CO2 emissions, regardless of whether 'FCE' is 'ON' or 'OFF'."

This is incorrect: only for carriers whose CO2 content depends on their mix of origins (the fossil fuels), will the CO2 emissions change regardless. If it is OFF, the calculation only takes into account the CO2 released in the combustion/conversion step. No CO2 is officially released when biomass is converted.

**Comment by ChaelKruip** [comment]
So, @RobTerwel can we close this?

**Comment by RobTerwel** [comment]
Yes, we can! Thanks @AlexanderWirtz
