### ISSUE TITLE
CO2 emissions in dashboard are different in LIVE and BETA

### ISSUE THREAD

**Issue by georgiasavvidou** [quintel/etmodel#1917]
When I create a new scenario, there is a 3.2% difference in the total CO2 emissions in the dashboard between the BETA and the LIVE version (and a 3.3 % difference in the local CO2 emissions)

BETA:
![image](https://cloud.githubusercontent.com/assets/12493788/10160349/2cdf2afc-669d-11e5-916f-568a6cea3890.png)

LIVE:
![image](https://cloud.githubusercontent.com/assets/12493788/10160512/5a05f08c-669e-11e5-88de-453a2c05006c.png)

There is also a difference in the CO2 emissions between the BETA and the LIVE in the scenarios SER Energieakkoord 2020  and SER Energieakkoord 2023 (3.5% difference in both scenarios) while the 100% duurzame energie in 2030 scenaario does not have any CO2 emissions difference.

**Comment by ChaelKruip** [comment]
Assigning to @AlexanderWirtz as he has the best feeling if his changes to carriers could have this impact.

**Comment by AlexanderWirtz** [comment]
@jorisberkhout is already looking into this

**Comment by ChaelKruip** [comment]
Moving to next deploy

**Comment by ChaelKruip** [comment]
Closing but for further work on this see https://github.com/quintel/etdataset/issues/609
