### ISSUE TITLE
Difference in costs between LIVE and BETA

### ISSUE THREAD

**Issue by georgiasavvidou** [quintel/etmodel#1918]
There is a difference of 3.2 bln/yr between the costs in the BETA and LIVE

BETA:
![image](https://cloud.githubusercontent.com/assets/12493788/10161116/1c159026-66a2-11e5-994d-11252fd02361.png)

LIVE:
![image](https://cloud.githubusercontent.com/assets/12493788/10161125/24b4d840-66a2-11e5-80cb-2be9f8f30c47.png)

**Comment by AlexanderWirtz** [comment]
The cause is the huge drop in dollar_to_euro. Since Oil and Coal are paid for in dollars, the lower value of the euro means you have to spend more to buy the same amount of oil.

**Comment by AlexanderWirtz** [comment]
I do not have time to look into the specifics, but I would bet this is what causes all of this difference

**Comment by jorisberkhout** [comment]
Assigning myself and adding milestone.

**Comment by jorisberkhout** [comment]
> but I would bet this is what causes all of this difference

I think you will win this bet :wink: I have looked into this issue in a little more detail and cannot find any errors in the calculation. The difference can be explained by the updated costs of many carriers (which in turn are caused by the changed dollar to euro rate).
