### ISSUE TITLE
Spanish Energetic CO2 Emissions per sector chart

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1920]
The Spanish (2030) `Energetic CO2 Emissions per sector`chart probably has a value for the `Other` section which is too large. It is given in teratonnes (I believe) and it is much bigger than the values of other sectors (which do appear in the table view). For reference, the values for this chart in the Netherlands are in Mtonnes and the `Other` section is much smaller.
![screen shot 2015-09-29 at 13 41 54](https://cloud.githubusercontent.com/assets/14106387/10163028/23483534-66b0-11e5-96e1-3bc42b27596d.png)

@ChaelKruip , could you check whether this value is correct?

Re-assign at will.

**Comment by jorisberkhout** [comment]
Good point, @RobTerwel . Interestingly, the total CO2 emissions as shown in the dashboard item are only 267.53 MT :confused:
