### ISSUE TITLE
Add a table view in dashboard

### ISSUE THREAD

**Issue by georgiasavvidou** [quintel/etmodel#1921]
Consider to add a table view in the charts in the dashboard. This is useful for example in the case of 'Renewables' option in the dashboard where the share of 'Renewable gas' , 'Renewable heat' and other carriers in the Netherlands is so small that cannot seen by pointing at the chart.

![image](https://cloud.githubusercontent.com/assets/12493788/10164279/fc85df92-66b8-11e5-9415-2243eb3abf28.png)

**Comment by RobTerwel** [comment]
Correct me if I'm wrong, but you can add a chart called `Renewability of the final demand' which seems the same. There is a table view option for that chart.

**Comment by ChaelKruip** [comment]
> which seems the same

It is :smile: 

> There is a table view option for that chart.

Yes, but it would also be nice to have it for the pop-up chart (which is indeed the same).

**Comment by RobTerwel** [comment]
>Yes, but it would also be nice to have it for the pop-up chart (which is indeed the same).

D'accord!

**Comment by ChaelKruip** [comment]
Assigning @antw to do this if he feels like it...

**Comment by ChaelKruip** [comment]
Moving to next deploy

**Comment by jorisberkhout** [comment]
Assigning @grdw.

**Comment by grdw** [comment]
Allright, I found how to turn a chart into a table. I found out where the chart is loaded but I don't get how this [fancybox](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/views/constraint_view.coffee#L48-L57) ~~~~ connects to ~~~~~> [chart_list#load](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/models/chart_list.coffee#L40-L101). According to some `console.log` statements I found out that there is something between them, but I can't figure out how to pass along more options, is that some Backbone wizardry? Could you maybe shine a little light on this matter @antw, if you know any of it. :innocent:

**Comment by antw** [comment]
I'm not very familiar with this code unfortunately, but I think what happens is that FancyBox requests [conststraints/show](https://github.com/quintel/etmodel/blob/26aad168ef64ff31ada85abfdde2c3f0a676ee19/app/views/constraints/show.html.haml), which includes [constraints/_js_init.coffee](https://github.com/quintel/etmodel/blob/26aad168ef64ff31ada85abfdde2c3f0a676ee19/app/views/constraints/_js_init.coffee). This is where the chart is set up ([lines 7-9](https://github.com/quintel/etmodel/blob/26aad168ef64ff31ada85abfdde2c3f0a676ee19/app/views/constraints/_js_init.coffee#L7-L9)).

It's a bit messy. :disappointed:
