### ISSUE TITLE
Dashboard- Disable the chart 'Profitability of power plants' if MO is disabled

### ISSUE THREAD

**Issue by georgiasavvidou** [quintel/etmodel#1922]
If the Merit Order is disabled, the chart 'Profitability of power plants' can be misleading (indicating the gas turbine as 1st in the merit order). Therefore, it is good to disable this chart if the MO is disabled.

![image](https://cloud.githubusercontent.com/assets/12493788/10164380/93745564-66b9-11e5-8cac-d86e644c7284.png)

**Comment by ChaelKruip** [comment]
Assigned @grdw and moved to next deploy

**Comment by grdw** [comment]
![screen shot 2016-01-11 at 4 06 28 pm](https://cloud.githubusercontent.com/assets/2676542/12237097/4b23b67c-b87d-11e5-857a-b828fe2ba06d.png)

Can't we just hide the whole merit-order out of the change-chart pop-up aswell if merit-order is disabled.

**Comment by grdw** [comment]
Including @ChaelKruip @jorisberkhout

**Comment by jorisberkhout** [comment]
> Can't we just hide the whole merit-order out of the change-chart pop-up aswell if merit-order is disabled?

Sounds like a good idea to me, but I would like to hear what @AlexanderWirtz and @dennisschoenmakers think.

**Comment by AlexanderWirtz** [comment]
Can the chart not be made to say: "please go to options and turn on merit order" if MO is off?

**Comment by jorisberkhout** [comment]
> Can the chart not be made to say: "please go to options and turn on merit order" if MO is off?

Interesting solution as well. What do you think, @dennisschoenmakers ?

**Comment by dennisschoenmakers** [comment]
> Can the chart not be made to say: "please go to options and turn on merit order" if MO is off?

I think that's a better solution. Otherwise people will be rightfully complaining about the fact that they cannot find the profitability chart. :smiley:

**Comment by jorisberkhout** [comment]
> Otherwise people will be rightfully complaining about the fact that they cannot find the profitability chart.

Good point, @dennisschoenmakers and @AlexanderWirtz . 

Could you implement this, @grdw?

**Comment by grdw** [comment]
Something like this:
![screen shot 2016-01-22 at 11 34 14 am](https://cloud.githubusercontent.com/assets/2676542/12508418/1a9e58ea-c0fc-11e5-921d-59316acc2d06.png)

**Comment by jorisberkhout** [comment]
I like it, @grdw . Two questions / comments:

- Is the new warning banner displayed for all three merit order charts (i.e. Merit order capacities, Merit order table and Plant profitability)? The original issue is not very clear about this, but I think it would be good to display the banner in all three instances.
- I find the current warning text a little vague and prefer changing it to 'The merit order is disabled. You can enable the merit order in the setting menu.'

**Comment by grdw** [comment]
It's now implemented for 'Merit order table and Plant profitability' I forgot the first one.

> 'The merit order is disabled. You can enable the merit order in the setting menu.'

:+1:

**Comment by AlexanderWirtz** [comment]
@grdw Much better IMO. 
Can we make it even easier and say: 
"The merit order calculation is turned off. Please go to 'Options' and turn on the merit order calculation."
Does that fit?

**Comment by grdw** [comment]
![screen shot 2016-01-22 at 12 03 37 pm](https://cloud.githubusercontent.com/assets/2676542/12509052/2fce05b8-c100-11e5-9f31-48b89a26dfeb.png)

Yes.... on two lines.

**Comment by AlexanderWirtz** [comment]
Works for me! :smile:

**Comment by antw** [comment]
I like this, but I think there's room for improvement still.

* I would prefer that the message give the user more information about *why* they need to enable the merit order. It can have a significant effect on the demands of a scenario, and with it costs, CO2 emissions, and more. Novice users may enable the option without understanding what it does. Let's help them out!

* Do these charts display meaningful data if the M/O is disabled? If not, while I agree with @dennisschoenmakers [above](https://github.com/quintel/etmodel/issues/1922#issuecomment-173515790), I think once a visitor selects the chart, the warning message should appear, and the chart or table should not be visible. It should become visible, without warning message, once the user enables the merit order.

* Red communicates that something serious has happened. The M/O being disabled is not *that* critical!

* Nitpicking: The menu title is "Settings". I can imagine some poor soul spending half their day looking for an "Options" button somewhere. :laughing:

Here's a super-quick mock-up from the Chrome inspector of what I'm imagining:

![screen shot 2016-01-22 at 12 33 53](https://cloud.githubusercontent.com/assets/4383/12510878/f427b950-c104-11e5-9227-feafe3748e8e.png)

**Comment by grdw** [comment]
That sounds a whole lot better and logical to me. However I think we still need an answer to:

> Do these charts display meaningful data if the M/O is disabled?

**Comment by dennisschoenmakers** [comment]
> Do these charts display meaningful data if the M/O is disabled?

I guess that's a **no**, and I think in the latest design by @antw the idea is also that the warning 'well' is shown **in stead** of the chart, right @antw?

**Comment by antw** [comment]
> I think in the latest design by @antw the idea is also that the warning 'well' is shown in stead of the chart, right @antw?

That's the idea. If the charts *do not* have meaningful data, I think it's confusing to show a warning but then go on to show them some data anyway.

If they *do* have meaningful data, the first paragraph would need to be reworded slightly. *"This chart will contain more accurate data if you choose to enable the merit order. To do so, ..."*

**Comment by grdw** [comment]
@antw is there already a default 'well' in the etmodel stylesheets available?

**Comment by dennisschoenmakers** [comment]
> @antw is there already a default 'well' in the etmodel stylesheets available?

Don't think so.... :smile:

**Comment by grdw** [comment]
> Don't think so....

I'll create my own than :+1:

**Comment by antw** [comment]
I threw that one together quickly in the Chrome inspector, but I don't think such a thing exists yet. It was something like:

```scss
.well {
  background-color: #f0f0f0
  border-radius: 5px;
  margin-top: 10px;
  padding: 1px 60px 5px;
  text-align: center;

  h5 {
    font-size: 15px;
  }
}

**Comment by AlexanderWirtz** [comment]
I like where this is going

**Comment by grdw** [comment]
@antw while you're at it, could you copy/paste the text in here aswell? :+1:

**Comment by dennisschoenmakers** [comment]
> I like where this is going

![image](https://cloud.githubusercontent.com/assets/104830/12512054/2e64c6d8-c116-11e5-8b6c-075e5166c34e.png)

**Comment by antw** [comment]
Argh, I closed it already. I think it was like this, but maybe the h5 was an h4? Either way I had to increase the font-size to 15px.

```html
<h5>Please enable the merit order to view this chart</h5>
<p>
  This chart relies on data from the merit order calculation, which is
  currently disabled in your scenario. To turn it on, please select the
  &ldquo;Enable merit order&rdquo; option from the &ldquo;Settings&rdquo;
  menu at the top of this page.
</p>
<p>
  To learn more about the merit order, and the effect it will have on your
  scenario, please see the <a href="#">Merit Order</a> page under the
  Costs section.
</p>
```

> I like where this is going

![](https://i.imgur.com/7drHiqr.gif)

**Comment by grdw** [comment]
Cool, thanks!

> I [like](https://youtu.be/CMNry4PE93Y?t=8s) where this is going

**Comment by grdw** [comment]
Please read and change at will:

NL:

Zet de merit order aan om deze informatie te bekijken

Deze informatie is gebaseerd op de merit order berekening, die momenteel niet aangezet is in jouw scenario. Selecteer 'Gebruik merit oder' om deze aan te zetten vanuit het 'Opties' menu bovenaan de pagina.

Om meer te leren over de merit order en het effect die het zal hebben op jouw scenario, zie de Merit Order pagina onder de sectie Kosten.

---

EN:

Please enable merit order to view this information

This chart relies on data from the merit order calculation, which is currently disabled in your scenario. To turn it on, please select the 'Enable merit order' option from the 'Settings' menu at the top of this page.

To learn more about the merit order, and the effect it will have on your scenario, please see the Merit Order page under the Costs section.

**Comment by AlexanderWirtz** [comment]
Typ-o in the Dutch bit. Also included some right-wing stuff

*NL:*

Zet de merit order aan om deze informatie te bekijken

Deze informatie is gebaseerd op de merit order berekening, die momenteel niet aangezet is in jouw scenario. Selecteer 'Gebruik merit order' om deze aan te zetten vanuit het 'Opties' menu rechts bovenaan de pagina.

Om meer te leren over de merit order en het effect die het zal hebben op jouw scenario, zie de Merit Order pagina onder de sectie Kosten.

*EN:*

Please enable merit order to view this information

This chart relies on data from the merit order calculation, which is currently disabled in your scenario. To turn it on, please select the 'Enable merit order' option from the 'Settings' menu at the top right of this page.

To learn more about the merit order, and the effect it will have on your scenario, please see the Merit Order page under the Costs section.

**Comment by dennisschoenmakers** [comment]
I don't wanna nag (okay, I do wanna nag) but IMO there should definitely be some space between the header and the well:

![image](https://cloud.githubusercontent.com/assets/104830/12891286/701fe73c-ce87-11e5-98db-b822d02c7f93.png)
