### ISSUE TITLE
Group the charts by sector in the Demand

### ISSUE THREAD

**Issue by georgiasavvidou** [quintel/etmodel#1923]
There are too many charts in the Demand and it would be more user friendly to group them by sector

![image](https://cloud.githubusercontent.com/assets/12493788/10164467/f43b7760-66b9-11e5-961f-6526bb0546eb.png)

**Comment by ChaelKruip** [comment]
Moving to February deploy.

**Comment by ChaelKruip** [comment]
Assigning @grdw

**Comment by grdw** [comment]
Couple of questions. I have looked into it:

1. Is it important that the graphs stay in the same order? 
2. Should the demand charts be 'subgrouped' or are the demand charts split up into separate first level groups?

**Comment by ChaelKruip** [comment]
> Is it important that the graphs stay in the same order?

No

> Should the demand charts be 'subgrouped' or are the demand charts split up into separate first level groups?

Subgroups I would think

**Comment by grdw** [comment]
![screen shot 2016-01-19 at 3 09 55 pm](https://cloud.githubusercontent.com/assets/2676542/12420740/b90b7db8-bebe-11e5-9e7b-e329832eb879.png)

**Comment by jorisberkhout** [comment]
> A preview

Looks good!

**Comment by grdw** [comment]
Only downside is that you have to manually set the subgroups. I think that's possible within the admin panel but I'll have to take a look.

**Comment by jorisberkhout** [comment]
As discussed is #2013 , let's pick this up after the deploy.

**Comment by grdw** [comment]
Closing due to relevant PR in https://github.com/quintel/etmodel/pull/2220

**Comment by grdw** [comment]
Only thing needed is filling in relevant sub-groups. Also we might want to use - as noted by @jorisberkhout - to use keys that can be translated. That latest part is not yet implemented but it's not that hard.

**Comment by grdw** [comment]
Superseded by https://github.com/quintel/etmodel/issues/2612
