### ISSUE TITLE
No Cooling in Poland (empty cooling demand in residences chart)

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1925]
The `cooling demand in residences` chart does not show anything for Poland, and in the table all values are zero. Is there no cooling in Poland or are we missing something here? 

@jorisberkhout , could you help out here?

![screen shot 2015-09-29 at 17 37 53](https://cloud.githubusercontent.com/assets/14106387/10169348/ec6fa09e-66d0-11e5-8b3b-85cfe1d8f294.png)
![screen shot 2015-09-29 at 17 33 16](https://cloud.githubusercontent.com/assets/14106387/10169351/f0839884-66d0-11e5-81ff-515ba3e63e10.png)

**Comment by jorisberkhout** [comment]
From the [Polish residences source analysis](https://github.com/quintel/etdataset/blob/master/source_analyses/pl/2012/6_residences/6_residences_source_analysis.md):

> It is assumed that the final demand for cooling is 0 PJ.

So this is a conscious choice. Closing.

**Comment by RobTerwel** [comment]
Thanks, @jorisberkhout !
