### ISSUE TITLE
Improve investments table 1: some converters need to be added

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#1926]
As @ChaelKruip and I agreed the improvements to the 'Investments for heat and electricity production' table have been split into two issues. This one deals with converters that should be included in this table.

## Intro
This table costs us a lot of work, because users ask for the information in this table. Since the table is incorrect and unclear, we need to do extra work in Excel.

## Converters to include

The following converters are not (explicitly) found in the table, but should be. Some *are* included in the converter group `converters_in_investment_cost_table.gql ` but are not shown. Others are missing from said group and hence not shown in the table either. @ChaelKruip please check this.

Also, some of the converters I list below do not have sliders. We need to decide whether we want to keep the converters and add sliders or remove the converters.

```
- buildings_collective_geothermal 
- energy_chp_ultra_supercritical_lignite
- energy_heat_network_backup_heater_network_gas
- energy_heater_for_heat_network_crude_oil --> converter can be removed as far as I am concerned
- energy_heater_for_heat_network_geothermal --> I would like to keep this one
- energy_heater_for_heat_network_lignite
- households_flexibility_p2h_electricity
- other_burner_coal
- other_burner_crude_oil
- other_burner_network_gas
- other_burner_wood_pellets
```
The following industry converters may need a clearer name in the table so the user can tell them apart:
```
- industry_burner_coal
- industry_burner_crude_oil
- industry_burner_network_gas
- industry_burner_wood_pellets
- industry_chemicals_burner_coal
- industry_chemicals_burner_crude_oil
- industry_chemicals_burner_network_gas
- industry_chemicals_burner_wood_pellets
- industry_chp_ultra_supercritical_coal --> this has no slider and needs research
```
## Not to be included
The following should not be in this table or the converter group
```
- industry_aluminium_burner_network_gas
- industry_other_metals_burner_network_gas
- industry_steel_blastfurnace_burner_coal_gas
- industry_steel_electricfurnace_burner_network_gas
```

 Notifying @dennisschoenmakers and @jorisberkhout

**Comment by ChaelKruip** [comment]
@AlexanderWirtz what about electric vehicles? They used to add no investment costs but now they will right?

**Comment by ChaelKruip** [comment]
> The following should not be in this table or the converter group

Can you give an explanation for this @AlexanderWirtz?

**Comment by RobTerwel** [comment]
> They used to add no investment costs but now they will right?

Electric vehicles (i.e., `transport_car_using_hydrogen` and `transport_car_using_electricity`) will receive *additional* investment costs w.r.t. ICE vehicles (whose investment costs will be considered as a 0 - baseline).
