### ISSUE TITLE
External link in Households - Climate information not working

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1929]
![screen shot 2015-09-30 at 16 34 52](https://cloud.githubusercontent.com/assets/14106387/10196108/67c7f9e2-6791-11e5-9178-23b1ecaa66d7.png)

In the Households - Climate information, there is an external link (to the KNMI website) that does not work. As decided in https://github.com/quintel/etmodel/issues/1905 , this link can be removed alltogether. Additionally, the sentence it's part of can also be removed completely.

@antw , could you please do that? Thanks!

**Comment by jorisberkhout** [comment]
I can show you how to that, @RobTerwel . Assigning you.

**Comment by jorisberkhout** [comment]
We closed this issue by removing the line 'More on the topic ... found here.' both in the production and staging database, both in the Dutch and English texts.
