### ISSUE TITLE
For absent tech, cost chart makes no sense

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#1930]
When a technology is absent in a scenario, the EUR/MWhe costs go to zero:

![image](https://cloud.githubusercontent.com/assets/104830/10196882/613b5d4a-6795-11e5-8c6b-a4cd288c23ef.png)

And the chart becomes pointless for these technologies. Could we do something about it?
E.g.:
* Hide technologies which costs are zero?
* any ideas @ChaelKruip, @grdw, @antw, @jorisberkhout, @AlexanderWirtz ?

**Comment by AlexanderWirtz** [comment]
Wow I haven't seen this issue in at least two years. It's cause is known and as I understanding fixing it wasn't easy back then.

**Comment by dennisschoenmakers** [comment]
> It's cause is known

Yeah, it's zero, because there is now energy flow through the converter. This is caused by the way the cost calculation is set up.

**Comment by ChaelKruip** [comment]
> Hide technologies which costs are zero?

That is the only thing that makes sense to me. I can imagine this to be complex to do or not @antw? 
A somewhat hacky way to achieve the hiding is by giving them negative costs instead of zero and only showing the positive axis of the chart...

**Comment by dennisschoenmakers** [comment]
Pretty straighforward, right? 

We will have to adapt:
* [block_chart_view#update_block_charts](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/views/block_chart_view.coffee#L107-L150)
* [_block_chart.html.haml](https://github.com/quintel/etmodel/blob/master/app/views/output_elements/_block_chart.html.haml#L3)

Wanna give it a try, @grdw ?

**Comment by AlexanderWirtz** [comment]
uuuuugly!

**Comment by dennisschoenmakers** [comment]
> by giving them negative costs instead of zero and only showing the positive axis of the chart...

I don't think that's necessary. :smile:

**Comment by ChaelKruip** [comment]
> uuuuugly!

I felt dirty just thinking up that solution :wink:

**Comment by antw** [comment]
> Hide technologies which costs are zero?

Seems like a sensible solution. The chart already has the ability to turn off some carriers already (with the tick-boxes). Perhaps, when the it updates, we could find any whose cost is zero and deselect it from the chart and disable the box.

The chart would have to remember which had been automatically turned off – as opposed to those intentionally hidden by the user – so that they could be turned back on when the cost becomes non-zero.
