### ISSUE TITLE
When zoomed in, would be nice if font size would be bigger.

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#1931]
I use the zoom option a lot when I project the model for a group, but fonts are still relatively small.

![image](https://cloud.githubusercontent.com/assets/104830/10197004/e6560dfe-6795-11e5-94b4-f2d7b92d6dc1.png)

**Comment by ChaelKruip** [comment]
Assigning @grdw

**Comment by grdw** [comment]
Increasing the font size looks really weird for all the 'text' (including axis-labels). Mainly where 2050 meets 0 PJ.

![screen shot 2016-01-08 at 11 34 15 am](https://cloud.githubusercontent.com/assets/2676542/12196013/c7e29392-b5fb-11e5-87a2-b05017bcaf84.png)

Without axis labels it looks a bit better:
![screen shot 2016-01-08 at 11 33 53 am](https://cloud.githubusercontent.com/assets/2676542/12196032/e20e61e2-b5fb-11e5-98bc-f476048c2013.png)

@dennisschoenmakers do you have any specific wishes towards the font-size?

**Comment by grdw** [comment]
Fixed with: https://github.com/quintel/etmodel/commit/1debf76d353aaefbd8f7727fdc6f614d50e4ebaa
