### ISSUE TITLE
Sliders disappear if you scale down a scenario in which all residences are demolished

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1933]
To reproduce this, do the following:

 - open a clean scenario (e.g. Netherlands 2050)
 - set `residences built before 1992` and `residence built after 1991` to zero
 - scale the scenario to some number (I chose 10000) of residences
 - you'll see sliders for the slide opened (`prosperity`), but open any other slide and the sliders will be gone

![screen shot 2015-10-01 at 11 45 21](https://cloud.githubusercontent.com/assets/14106387/10217793/67ff7dd0-6832-11e5-8984-488c5f0ddcf9.png)

Interestingly, in the newly scaled scenario `number of residences` is 1 (see image). This seems to happen only if you destroy all residences.

Re-assign at will.

**Comment by jorisberkhout** [comment]
After discussing with @grdw, assigning him.

**Comment by grdw** [comment]
`Status update:`

I did exactly this and noticed that there were two unit errors flying by in the console output of the browser.

One was `Unknown unit: Gln` and the other is `Unknown unit: Tln`

After adding the two units to the `BASE_UNITS` in a `quantity.coffee` something weird happened:

![screen shot 2016-01-15 at 2 41 19 pm](https://cloud.githubusercontent.com/assets/2676542/12354454/50d4eb74-bb96-11e5-9711-51b0df8e25b7.png)

I'm guessing that's not entirely the idea. So I removed the two units from `BASE_UNITS`.

**Comment by antw** [comment]
The unit for that slider [has been set to `mln`](http://beta.pro.et-model.com/admin/input_elements/335/edit) ("million"). That will be tripping up the Quantity class, since "million" should be a capital "M", i.e. `Mln`. You might also have to add a base unit called `ln` if there isn't one already.

**Comment by grdw** [comment]
> You might also have to add a base unit called ln

Thanks, that fixed it :+1:
