### ISSUE TITLE
Guide users at ETModel for ETMoses

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#1935]
On the front page of ETMoses there are three images that explain how to manouvre through ETModel in order to create a scaled scenario.

However to switch between tabs from ETMoses and ETmodel is asking a little too much from the 21 century Internet user.

So I'd like to suggest to use http://usablica.github.io/intro.js/ 

To create a small guide for ETMoses on ETModel. 

Thought? @ChaelKruip @antw @dennisschoenmakers

**Comment by ChaelKruip** [comment]
I like the idea but I have two reservations:
* These things always take a lot of time to do well
* The typical ETMoses user is not someone who stumbles on the website by accident and goes exploring on his own. Rather, we want to advertise our workshops I think (see https://github.com/quintel/etmoses/issues/495). ETMoses is too much of an expert tool to let someone loose there without proper guidance. So, having a slick introduction might actually give the wrong impression: "Hey, this is fun! Let's go explore!"

Sorry to be a negative Nancy here :disappointed:

**Comment by dennisschoenmakers** [comment]
I agree with @ChaelKruip. BTW: We used intro.js on etflex! It is awesome!

**Comment by grdw** [comment]
I agree also. I'm going to close this issue. :+1:
