### ISSUE TITLE
Merit order- PP running more than expected based on their availability in the present

### ISSUE THREAD

**Issue by georgiasavvidou** [quintel/etmodel#1936]
It appears that some Power Plants in the merit order table are running more than they should according to their availability.

An example is the nuclear 2nd generation. It appears to have 7800 FLH in the present resulting in availability of 89%
(7800/8760=0.89)

However, its availability is 87% (see 2nd picture). 

Also, the issue quintel/etsource#970 refers to a rounding issue. However, that does not seem to explain the discrepancy. Following the same example, and assuming that the 7800 FLH resulted because of rounding to the nearest 50, then the initial value would be minimum 7750. Now, 7750/8760=88% which is still higher than the availability of the PP. 

![image](https://cloud.githubusercontent.com/assets/12493788/10363557/751db79c-6db5-11e5-8f7d-7d0951062ad7.png)

![image](https://cloud.githubusercontent.com/assets/12493788/10363583/a6c15c86-6db5-11e5-93db-8cae126e5523.png)

**Comment by jorisberkhout** [comment]
Moved to 'Deploy February 2016' milestone.

**Comment by jorisberkhout** [comment]
Well spotted by @georgiasavvidou . The present FLH come straight from the 'Power and heat plant analysis' on ETDataset, where we do not check for consistency between these FLH and the availability. I did a quick check and found that the following converters have higher FLH in the present than allowed by their availability:

| converter | FLH (present) | max. FLH based on availability | availability |
|:--- |:--- |:--- |:--- |
| energy_power_nuclear_gen2_uranium_oxide | 7800 | 7621 | 0.87 |
| energy_power_hydro_mountain | 4492 | 2891 | 0.33 | 
| energy_power_ultra_supercritical_cofiring_coal | 7900 | 7709 | 0.88 |

As these FLH are better researched than the availability, I propose to update the FLH. This will have fall-out for the outcome of the merit order calculation, as these three plants will be allowed to run a little more than they do now. What do you think, @AlexanderWirtz ?

**Comment by jorisberkhout** [comment]
In addition I found the following six converters to have `0.00` availability, even though they have FLH in the present year. I know these are heat producers so they do not participate in the merit order, but still it would be nice to update them, although I have no clue to what number. @AlexanderWirtz , what do you think?


| converter | FLH (present) | max. FLH based on availability | availability |
|:--- |:--- |:--- |:--- |
| energy_heater_for_heat_network_coal | 2190 | 0 | 0.00 |
| energy_heater_for_heat_network_network_gas | 2190 | 0 | 0.00 |
| energy_heater_for_heat_network_lignite | 2190 | 0 | 0.00 |
| energy_heater_for_heat_network_wood_pellets | 2190 | 0 | 0.00 |
| energy_heater_for_heat_network_waste_mix | 2190 | 0 | 0.00 |
| energy_heater_for_heat_network_crude_oil | 2190 | 0 | 0.00 |

**Comment by AlexanderWirtz** [comment]
>I know these are heat producers so they do not participate in the merit order, but still it would be nice to update them, although I have no clue to what number. @AlexanderWirtz , what do you think?

How come they have 0.00 availability? Where have these been set? I suggest (guess) at least use the `2190` even though that seems on the low side as well (there is an old issue for this).

**Comment by AlexanderWirtz** [comment]
> As these FLH are better researched than the availability, I propose to update the FLH. This will have fall-out for the outcome of the merit order calculation, as these three plants will be allowed to run a little more than they do now. What do you think, @AlexanderWirtz ?

I think the `energy_power_hydro_mountain` FLH are a bit high relative to the availability. That one (33%) does not seem so crazy to me. What country has them with such high FLH?

The coal and nuclear plant can probably have slightly higher availability. I assume that is what you mean @jorisberkhout? To update the availabilities instead of the FLH?

**Comment by jorisberkhout** [comment]
> I assume that is what you mean @jorisberkhout? To update the availabilities instead of the FLH?

Correct, I updated my previous comment to reflect this.

> What country has them with such high FLH? (for `energy_power_hydro_mountain`)

These FLH are for NL, which has no hydro mountain, so the FLH are irrelevant. Nevertheless, I think it would be nicer to update these FLH to match the availability.

Good point about the country specific FLH. So far, I have only checked the NL dataset, but I will check the other datasets as well and see if that gives any reason to change the availabilities or FLH.

> How come they have 0.00 availability? Where have these been set?

These availabilities are set in the respective node files and have been `0.0` since the moment these are on GitHub. Let's update them and see if there is any fallout.

**Comment by AlexanderWirtz** [comment]
> Let's update them and see if there is any fallout.
Good idea

**Comment by jorisberkhout** [comment]
Not critical for the deploy, milestone removed.

**Comment by jorisberkhout** [comment]
Closed by https://github.com/quintel/etsource/pull/1172/commits/b0222d292bb1ef936bf748c353fd3cdd5adb7278. Let's keep an eye out for any major changes to the model as a result of these changes. Pinging @AlexanderWirtz , @ChaelKruip and @TessColijn .
