### ISSUE TITLE
It should be possible to make a (mekko) with km2 as the unit

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1937]
Right now, km2 is not recognized as a unit I think and neither is m2...

**Comment by ChaelKruip** [comment]
Now I have used 'PJ' instead of 'km2' in this draft of a bio-footprint Mekko:
![cursor_and_energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/10366510/40b40388-6dcb-11e5-8fbe-c6b03cf3cb7f.png)

**Comment by antw** [comment]
Is this chart only on your local machine? I can't find it on beta.

Either way, `m2` (and `km2`, `Mm2`, `Gm2`, etc) should now be useable in the Mekko chart.

**Comment by ChaelKruip** [comment]
> Is this chart only on your local machine? 

Yes, still local! 

> Either way, m2 (and km2, Mm2, Gm2, etc) should now be useable in the Mekko chart.

Thanks!

**Comment by ChaelKruip** [comment]
I just realised that the normal 'scaling law' for multiples of 1000 does not apply to m2 (because it is a square). So, 1 km2 = 1e6 m2 = 1e-6 Mm2. So, I think that the current chart shows values that are a factor 1000 too small:
![cursor_and_energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/10368598/5c872abc-6dd6-11e5-98a3-73025312468c.png)

@antw Would it be possible to force the unit to be km2? Some values will be large (order 10_000 km2) but it is a unit that people will recognise.

**Comment by antw** [comment]
> the normal 'scaling law' [...] does not apply to m2 (because it is a square)
>
> Would it be possible to force the unit to be km2? Some values will be large (order 10_000 km2) but it is a unit that people will recognise.

This isn't currently possible, but it's a sensible observation. :+1:

I'll see what I can do about it early next week.

**Comment by ChaelKruip** [comment]
> I'll see what I can do about it early next week.

:+1:

**Comment by marliekeverweij** [comment]
Possible now 🙂
