### ISSUE TITLE
How to distribute excess electricity over the available peak-shaving options?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1938]
When incorporating storage and conversion into the ETM (see https://github.com/quintel/etmodel/issues/1868), we will have to give the user some control over which technology is given precedence for taking care of the excess electricity.

Previously, the idea was to let the user 'order' the technologies according to which should be 'first' to receive a given kWh of excess electricity. So, batteries before P2G for instance.

After discussing this with @jorisberkhout I think that this is not a good approach because it will 'globally' give precedence to a technology although in reality electricity will be converted and stored by several technologies at the same time. People who have a solar panel which produces excess will not wait until all batteries in the country are charged before using their P2G installation.

We suggest to use sliders (instead of a 'merit order') that decide which fraction of each kWh is stored/converted by which technology. This is a very 'ETM' way of dealing with the issue and quite intuitive IMO. It raises the following question though:

What happens if a technology has insufficient capacity or volume to deal with the assigned electricity? In the 'merit order'-approach, once a technology is 'fully used', the next takes its place. Perhaps we can combine the two approaches: 
1. Store/Convert excess in all technologies available according to a distribution given by the sliders
2. If either the capacity or the volume of a technology is limiting, the excess should be given to next in the 'merit order' (which could be hard-coded and not an option for the user)

NB: I don't think this is a real issue in ETMoses because excess is handled on a node-by-node basis, so even though there is a 'merit order', all options are used unless they are all attached to each node in exactly the same numbers. Right @antw?

Including @dennisschoenmakers @AlexanderWirtz @jorisberkhout

**Comment by AlexanderWirtz** [comment]
> 2. If either the capacity or the volume of a technology is limiting, the excess should be given to next in the 'merit order' (which could be hard-coded and not an option for the user)

Will that lead to a cascade of problems, if the next available technology is one of those assigned a percentage by the sliders?

**Comment by ChaelKruip** [comment]
> Will that lead to a cascade of problems, if the next available technology is one of those assigned a percentage by the sliders?

It might lead to intransparent behaviour: the user chooses that technology A and B get 50% of the excess each. But in the end, A might end up with 90% because B is 'full'. Perhaps the responsibility for distributing excess over the different technologies in a smart way should lie with the user. 
This could lead to frustration because the ideal slider settings might differ for the seasons...

**Comment by ChaelKruip** [comment]
Assigning to @jorisberkhout

**Comment by jorisberkhout** [comment]
After discussion with @ChaelKruip , closing this issue as we prefer the solution described in https://github.com/quintel/etmodel/issues/1965.
