### ISSUE TITLE
Tables should not contain thousand seperators

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#1939]
As some of our users copy/paste data from these tables into Excel.

**Comment by ChaelKruip** [comment]
Assigning to @antw

**Comment by jorisberkhout** [comment]
Assigning @grdw .

**Comment by antw** [comment]
If we added an "export table as CSV" feature, would that be better? Probably isn't doable by this upcoming deploy, but it would allow us to keep the more readable numbers while also catering to those who want the raw data.

**Comment by jorisberkhout** [comment]
> If we added an "export table as CSV" feature, would that be better?

I like it. I'll close this issue in favour of the solution described in https://github.com/quintel/etmodel/issues/2005. Re-open if you feel different about that.
