### ISSUE TITLE
Latest version of IE not correctly identified.

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#1940]
One of our users with a new Windows laptop showed us the ETM, and there was a yellow warning visible with [unsuported_browser](https://github.com/quintel/etmodel/blob/3bffa7f194d115efe08c5c80f42cf242401a190b/app/controllers/application_controller.rb#L33) warning despite our [white list](https://github.com/quintel/etmodel/blob/master/lib/browser.rb#L2) containing:

```ruby
ie11 ie10 ie9 ie8 ie7
```

I think this has to do with the fact that the User-Agent string sent by ie11 [changed](http://blogs.msdn.com/b/ieinternals/archive/2013/09/21/internet-explorer-11-user-agent-string-ua-string-sniffing-compatibility-with-gecko-webkit.aspx) recently to:

```
Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko
```

There is a [whole debate](http://stackoverflow.com/questions/17907445/how-to-detect-ie11) on this issue.

**Comment by grdw** [comment]
Fixed with: https://github.com/quintel/etmodel/commit/99d3625941a95d0250c4205bff8cfa37f33a46d3
