### ISSUE TITLE
Should we show CO2, bio-footprint and primary demand of export in Mekko's?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1943]
Doing some research for Gasunie, I realised that in some scenario's the Mekko charts which are based on the primary demand calculation (those for CO2, bio-footprint and primary demand) actually miss some of the energy. The reason is that we calculate **primary demand of the nodes in the final demand group**. This includes almost all energy use in the ETM **except** that which is associated with export of electricity.

The confusing thing is that, although export of electricity only happens if must-run and volatiles are producing more than the demand, the exported mix is set equal to the year-averaged electricity mix (also see https://github.com/quintel/etmodel/issues/1942). 

Also, if the production curves for primary carriers dictate more production than locally needed in the end-year, the energy is exported as well.

My suggestion is to add a new 'sector' to the Mekko's that represents all energy use associated with export. That way, the total energy budget is represented.

**Comment by ChaelKruip** [comment]
@AlexanderWirtz @dennisschoenmakers @jorisberkhout what do you think?

**Comment by jorisberkhout** [comment]
> My suggestion is to add a new 'sector' to the Mekko's that represents all energy use associated with export. That way, the total energy budget is represented.

I like it!

**Comment by AlexanderWirtz** [comment]
1. I like it, BUT... 
THere is no doubt that primary demand for exported electricity is for the country producing the electricity. 
The production of primary carriers, however, is a bit more complicated. Let's take the example of `natural_gas`. If we *produce* e.g. `102`, resulting in `100` purified natural gas and then export `50`, what is primary demand of `natural_gas`? Primary *consumption* (an actual category in the Energy Balance) is `52`, in my opinion, the `2` used to 'purify' the natural gas (`own_use`) and the `50` actually consumed. The CO2 emissions should clearly be `52 x emission_factor`.

2. How to proceed? We add primary energy demand for exported energy to the primary energy demand mekko and dashboard queries. IMO we should do this according to the 'primary consumption' method, as this makes it consistent with the CO2 emissions mekko we want to create. @ChaelKruip and I have notices that the [Domestic CO2 emissions](https://github.com/quintel/etsource/blob/master/gqueries/output_elements/dashboard/dashboard_reduction_of_local_co2_emissions_versus_1990.gql) calculation is not correct as it simply calculated the primary CO2 of final demand. This is OK for imported electricity, but not for exported electricity if this is created in a fossil power plant or CHP.

3. Bio-footprint is a seperate case, as this is not calculated within national borders. The footprint for imported `green_gas` is also included, for example. Of course, any *domestic* footprint of exported biogenic carriers should be somehow included. Can we think of a case in which a country exports massive amounts of `green_gas`, though?

**Comment by AlexanderWirtz** [comment]
After discussions with @ChaelKruip we decided this issue needs further specification.

The central problem is that the graph contains no good information on what the actual export per carrier *IS*. For example: what is `gasoline` export in `future_year` if in the Netherlands most cars have become electric vehicles? Will we still refine `crude_oil`? Without adding sliders and converters about refineries, it's impossible to tell what the future balance will look like. Note that for the `present_year` this is not an issue, because the Energy Balance, contains all the required information.

IMO this problem makes this issue hard to solve and relates to an inherent shortcoming of the ETM graph method.

**Comment by AlexanderWirtz** [comment]
## Now for a more pragmatic approach

Any export that the engine *DOES* know about can be correctly calculated and displayed in the relevant charts. For that, a calculation identical to `primary_demand_of_final_demand` should work just fine.

**Comment by ChaelKruip** [comment]
Closing this as the charts for primary demand and CO2 are added. Bio-footprint will have to wait.
