### ISSUE TITLE
Chart 146: final_demand_mekko_mece should show solar thermal not solar

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#1944]
The series 1386 - 1391 refer to `solar` rather than `solar_thermal` and the queries are like below. How can there ever be *final* demand of solar_radiation, however, other than for solar thermal purposes?

## Solution
simply change each label from `solar` to `solar_thermal`. Less work than creating this issue. :-)

## Example of current query

''''
GQL Statment
SUM(
  V(
    FILTER(
      FILTER(
        LG(final_demand),"sector == :households"
      ),
      solar_radiation?
    ),
    value
  ),
  V(
    FILTER(
      FILTER(
        LG(final_demand),"sector == :households"
      ),
      solar_thermal?
    ),
    value
  )      
) / BILLIONS
''''

**Comment by ChaelKruip** [comment]
> How can there ever be final demand of solar_radiation?

There cannot indeed. It is included for completeness. 

> simply change each label from solar to solar_thermal. Less work than creating this issue. :-)

Done this in the database:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/10784341/d8678884-7d5d-11e5-8d3d-24dd43550b1b.png)

Closing.

**Comment by AlexanderWirtz** [comment]
@ChaelKruip I forgot to mention the same should be done in chart number 42:
http://beta.pro.et-model.com/admin/output_elements/42
![image](https://cloud.githubusercontent.com/assets/308563/10785441/806068c0-7d64-11e5-8a11-7c636ad27b5b.png)

**Comment by AlexanderWirtz** [comment]
I will do this on beta

**Comment by AlexanderWirtz** [comment]
The results:
![image](https://cloud.githubusercontent.com/assets/308563/10785490/c7bbd0c4-7d64-11e5-854b-5664a86b82c2.png)
