### ISSUE TITLE
Some sliders not appearing locally in spite of having been added (with correct keys)

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1948]
On etmodel.dev/admin I added the sliders @jorisberkhout and I had agreed to put in the front end. However, when running the model locally, some sliders refuse to show up.

![screen shot 2015-11-03 at 10 51 08](https://cloud.githubusercontent.com/assets/14106387/10905593/8805b10a-821b-11e5-9151-00594e41facb.png)

The console gives:

![screen shot 2015-11-03 at 10 51 55](https://cloud.githubusercontent.com/assets/14106387/10905656/e7f827e6-821b-11e5-9807-b92cb451ea7f.png)

And that specific line of code 

> if (!values) {
            console.warn("Missing slider information! " + (i.get('key')));
            return false;

When inspecting the web-elements I do see the particular slider `transport_shipping_mixer_lng_bio_lng_share` in there, but separated from the rest, frankly:

![screen shot 2015-11-03 at 10 52 31](https://cloud.githubusercontent.com/assets/14106387/10905708/604712ca-821c-11e5-801b-003acf1b0934.png)

In https://github.com/quintel/etmodel/pull/1947 I added the names for the sliders and interfaces and in https://github.com/quintel/etsource/pull/984 some other gqueries for other input/demand (which work fine). Strangely enough, the aforementioned input/demand `transport_shipping_mixer_lng_bio_lng_share` slider does not appear, but the `transport_shipping_mixer_diesel_bio_lng_share` one does (and also works). I checked whether the keys, share_groups and names matched between the interface and the input/demand and they did. Then I made sure these two files were exactly the same (except for the converters they refer too of course), yet the sliders  still wouldn't appear. I also checked whether the (start value) gqueries return the correct values in the sandbox, and they do as well.

The 'absent' sliders are `transport_shipping_mixer_lng_bio_lng_share` and `transport_road_mixer_lng_bio_lng_share`.

I did a quick search on Github and found https://github.com/quintel/etmodel/issues/698 which kind of resembles my problem, although this was an issue made at the time we still used factors for the start value  gqueries. @antw , if I understood later developments well, you removed those factors and wrote the start value gqueries we use now. Would you have any idea what could result in this behaviour of sliders not showing up in my case?

**Comment by antw** [comment]
This would suggest ETEngine is not sending any information about the inputs you have added. Can you confirm that your *ETModel* config/config.yml reads:

```yml
development: &DEV
  api_url: http://etengine.dev
  # ...
```

The slider which *does* appear for you [is already available on beta.et-engine.com](http://beta.et-engine.com/data/latest/inputs/transport_shipping_mixer_diesel_bio_lng_share); the two missing sliders are *not* available on beta. I think your `api_url` may be set to `beta.et-engine.com`.

**Comment by RobTerwel** [comment]
@antw , thank you very much, greatly spotted! My `api_url` for development was indeed set to `beta.et-engine.com`. I'll change it  to `http://etengine.dev` immediately.

**Comment by RobTerwel** [comment]
Strangely enough, the problem persists, these two sliders still don't appear.

**Comment by antw** [comment]
Make sure that they appear in your ETEngine at http://etengine.dev/data/latest/inputs. If they do, restart your ETModel to ensure the new ETE URL has been picked up:

```sh
cd your/etmodel/directory
touch tmp/restart.txt
```

You can assert that the correct URL is being used by creating a *new* scenario in ETModel, opening the console, and running `App.scenario_url()`. This value returned should begin with `http://etengine.dev`.

**Comment by RobTerwel** [comment]
Hmm... they don't appear in http://etengine.dev/data/latest/inputs, although I do have the files here locally.

**Comment by antw** [comment]
Restarting ETEegine might push it in the right direction. :laughing: 

```sh
cd your/etmodel/directory
touch tmp/restart.txt
```

Depending on your ETE config/config.yml settings, it may not pick up new ETSource files without being restarted, so it's worth a try.

If that doesn't work, check the following ETEngine config.yml settings:

```yml
development: &DEV
  etsource_export: your/etsource/directory
  etsource_working_copy: your/etsource/directory

  etsource_live_reload: true
  etsource_lazy_load_dataset: true
```

... and restart ETEngine again so that the changes take effect.

**Comment by RobTerwel** [comment]
Okay, I went to my ETModel directory and ran

``` touch tmp/restart.txt```

Then the  files didn't show up yet in  http://etengine.dev/data/latest/inputs .

Next, I checked the ETEngine config.yml settings and they are all as you wrote them in your post.

I restarted ETModel again (via `touch tmp/restart.txt` in the ETmodel directory) and they still didn't show up in etengine.dev/dta/latest/inputs . I also did `powder restart` in my ETEngine directory, but that didn't help either. Lastly, I also hit the 'Restart' button on etengine.dev, unfortunately without any effect  it seems. Am I maybe overlooking something very basic here?

On a different note, I noticed that the shares are actually present on master, see
[here](https://github.com/quintel/etsource/blob/master/inputs/demand/transport/transport_lng_shipping/transport_shipping_mixer_lng_bio_lng_share.ad%20) . Does that then mean that not all shares have been deployed to beta?

**Comment by RobTerwel** [comment]
There must be something up with the file: I made a copy of it (same name) and it didn't appear on  http://etengine.dev/dta/latest/inputs . I then made a copy of a different file and gave it a different name (note the two variables), but that file was picked up! 

I should be able to find a way to solve this now. An update will follow.

**Comment by antw** [comment]
I checked the ETSource branch out myself, and noticed that one of the files has a space at the end of the name:

* "transport_shipping_mixer_lng_bio_lng_share.ad " (trailing space) should be:
* "transport_shipping_mixer_lng_bio_lng_share.ad"

The space would explain why the file might not be picked up correctly: `".ad "` != `".ad"`

**Comment by RobTerwel** [comment]
Yep, you're totally right! And so does `transport_road_mixer_lng_bio_lng_share`. I changed both and now they are picked up. 

I cannot believe that this all came down to one surreptitious 'suffix' of a space... It does make sense, because I've noted this keyboard does sometimes double my spacing... Anyway, thanks a lot for your help, @antw ! I'll close this once I have confirmation the sliders also work locally.

**Comment by RobTerwel** [comment]
Everything works like a charm!

Closing.
