### ISSUE TITLE
Addition of LNG and bio LNG to charts on beta

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1950]
This is an overview ticket for the addition of LNG and bio LNG to charts. Here I included all charts to which LNG and bio LNG will have a non-zero value. Note: since we modelled regasified LNG as natural gas and regasified bio LNG as greengas, all charts which use natural gas and greengas from the grid need not be modified and have not been included here. Of course the `Greengas in gas network` graph is an exception and does include regasified LNG and regasified bio LNG.

In modifying them, I will also take care of https://github.com/quintel/etmodel/issues/1946 . Images are from my local ETM.

# Rather unequivocal

## Transport fuel mix

![screen shot 2015-11-10 at 10 12 50](https://cloud.githubusercontent.com/assets/14106387/11058524/c52c1c9a-8793-11e5-8e3b-75104d1bfdb1.png)

Addition of 
- LNG
- Bio LNG

## Primary demand of biofuels

![screen shot 2015-11-10 at 10 16 16](https://cloud.githubusercontent.com/assets/14106387/11058584/2039bf8e-8794-11e5-9c77-be701d538305.png)

Addition of
- Bio LNG

## Bio footprint of primary demand

![screen shot 2015-11-10 at 10 18 08](https://cloud.githubusercontent.com/assets/14106387/11058621/632ec618-8794-11e5-91cd-a79f2d5ceb4e.png)

Addition of
- Bio LNG

## Greengas in Gas network
![screen shot 2015-11-10 at 10 39 58](https://cloud.githubusercontent.com/assets/14106387/11059048/8866077c-8797-11e5-93fc-1dfb5f0adda7.png)

Addition of
- Regasified LNG
- Regasified Bio LNG

Moreover, using the Modelling experiments query generator LNG and Bio LNG can be added to the carrier groups and from their to all relevant queries.

# Less obvious

## Renewability of final demand
![screen shot 2015-11-10 at 10 49 02](https://cloud.githubusercontent.com/assets/14106387/11059232/c487b10a-8798-11e5-86f4-75d38dd3ad89.png)
 
- Add LNG to fossil gas
- Add Bio LNG to biomass

D'accord? I put LNG with fossil gas, as it is fossil albeit in a different state. Alternatively, we could put it separately as `LNG`.

# Worth Discussing

## Present energy imports
![screen shot 2015-11-10 at 10 43 40](https://cloud.githubusercontent.com/assets/14106387/11059108/f34f36bc-8797-11e5-850e-7e62c9e6afa8.png)

We could make LNG part of `natural_gas` and bio LNG part of `biogenic fuels`, or present them separately (or something else of course). What has your preference, @jorisberkhout , @ChaelKruip  ,@AlexanderWirtz ?

## Future energy imports

Same as above.

## Primary energy use
![screen shot 2015-11-10 at 10 21 45](https://cloud.githubusercontent.com/assets/14106387/11058714/099dc9e0-8795-11e5-8f17-7e41c49791a9.png)

Here `gas` should be `natural gas`, `biofuels` `liquid biofuels` and `biomass` `solid biomass` as noted in https://github.com/quintel/etmodel/issues/1946 

This is the primary demand, so the demand of primary carriers. Since there is a transformation (regasification) of LNG to natural gas, I think we ought to subtract the regasified LNG from the `natural gas` value. One could argue that LNG was initially natural gas, but since it is imported as LNG, LNG is the primary carrier.

Similarly, for bio LNG, we subtract the regasified bio LNG from the `green_gas` value. The question is whether to incorporate bio LNG in the existing (liquid) biofuels carrier group, or to give it its own category and present it independently as bio LNG. To my knowledge, this is the only (or one of the only) charts where we make the distinction between `solid biomass` and `liquid biofuels`, the others just have `biomass`.

An idea could be the following:
- `natural gas` , value = primary demand of natural gas - regasified LNG
- `LNG`, value = primary demand of LNG
- `greengas`, value = primary demand of greengas - regasified bio LNG
- `liquid biofuels`, value includes primary demand of bio LNG

@jorisberkhout , @AlexanderWirtz , @ChaelKruip , what are your thoughts?

**Comment by RobTerwel** [comment]
With https://github.com/quintel/etsource/pull/986 you can see for yourself how this works out on beta. 

Everything has been done as said before, so:

- for renewability of the final demand: `lng` to `fossil gas` and `bio lng` to `biomass` <--- is that the correct name by the way? I check the gquery and it is the sum of `bio ethanol`, `biodiesel`, `bio lng` and `wood pellets`.
- for present energy imports: `bio lng` to `biogenic fuels` and `lng` as a new category
- for future energy imports: idem ditto
- for primary energy use:
 - `natural gas` , **value = primary demand of natural gas** 
 - `LNG`, value = primary demand of LNG
 - `greengas`, **value = primary demand of greengas** 
 - `liquid biofuels`, value includes primary demand of bio LNG

It is not necessary to subtract the regasification flow from the natural gas primary demand, it works correctly with the values as written above (verified with sandbox).

**Comment by ChaelKruip** [comment]
> Bio footprint of primary demand

@RobTerwel What happened to this chart? Is the unit correct because it seems that the transport sector dominates everything due to LNG

**Comment by RobTerwel** [comment]
>  Is the unit correct because it seems that the transport sector dominates everything due to LNG

That is not what I observe, it is actually biodiesel that dominates the transport sector which in turn dominates the mekko. On beta I see this in a clean 2050 NL scenario:

![screen shot 2015-11-16 at 09 56 01](https://cloud.githubusercontent.com/assets/14106387/11177805/7d230828-8c48-11e5-9878-b1740874005c.png)

I checked ETSource and there is no factor difference in the gqueries which would account for a difference in units.

**Comment by jorisberkhout** [comment]
@RobTerwel , what is the status of this issue?

**Comment by RobTerwel** [comment]
@jorisberkhout , it can be closed, provided that everyone agrees with the decisions made. Beware that these screenshots are somewhat outdated and some carrier groups have received a name update already.

**Comment by jorisberkhout** [comment]
Thanks, @RobTerwel . Closing this issue.

**Comment by RobTerwel** [comment]
:+1:
