### ISSUE TITLE
4 FCE charts, but why are certain carriers added to multiple charts?

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1953]
Currently, there are 4 FCE charts in the ETM 

- 100 FCE (`fuel_chain_emissions`)
  - wood pellets
  - greengas
  - natural gas
  - LNG
  - crude oil
  - coal
- 105 FCE of uranium (`fuel_chain_emissions_scaled_for_uranium`)
  - uranium
  - wood pellets (# 2)
  - green gas (# 2)
  - natural gas (# 2)
  - coal (# 2)
- 107 FCE of greengas (`fuel_chain_emissions_scaled_for_greengas`)
  - uranium (# 2)
  - wood pellets (# 3)
  - green gas (# 3)
  - natural gas (# 3)
  - coal (# 3)
- 138 FCE of liquid biofuels `fuel_chain_emissions_scaled_for_liquid_biofuels`
  - green gas (# 4)
  - bio ethanol
  - biodiesel
  - natural gas (# 4)
  - crude oil (# 2)

I noticed the following:
 - Some chart components (carriers) like `wood_pellets` are used in several FCE's, others are used only once (e.g. `biodiesel`)
 - The liquid biofuels scaled graph also features fossil fuels like `natural_gas` and `crude_oil`, as well as gaseous biofuels `green_gas`. It does say it is *scaled for liquid biofuels*, not about liquid biofuels, but I wonder why these specific carriers have been included and others have been left out. 

@Chaelkruip , would you know whether there are reasons behind this (i.e. which carriers are added to a specific FCE chart)?

**Comment by ChaelKruip** [comment]
> @Chaelkruip , would you know whether there are reasons behind this (i.e. which carriers are added to a specific FCE chart)?

No. @AlexanderWirtz could you enlighten us?

**Comment by AlexanderWirtz** [comment]
These chart compare carriers. Some carriers are more relevant to compare to than others in each case. We cannot include all carriers in all charts, so we made some choices. The scaling is done so the information for bio carriers is not lost due to compression of the chart after scaling.

Does that make sense?

**Comment by AlexanderWirtz** [comment]
Also, @RobTerwel what is the actual issue here?

**Comment by RobTerwel** [comment]
> Does that make sense?

This is the part of the answer I assumed, but I was wondering on what grounds the selection of carriers is made. I added `LNG` to the first chart and I did not know whether to add it to any other or not, since there did not seem to be a straightforward logic behind these choices. You said 

> so we made some choices

and it is the reasons behind those that I am after.

> what is the actual issue here?

This is just an issue inasmuch as GitHub calls it that, it is merely a question, as I indicated above in the text and label.

**Comment by AlexanderWirtz** [comment]
Aha, but why add LNG to these charts? That does not seem like a good idea to me. After all, if you set your slider to 100% gas from the Middle East, natural_gas has become LNG, in essence. These charts serve a very particular purpose and adding LNG does not seem to add any information that users cannot already glean from the charts as they are. I was unaware that you wanted to add this carrier to these charts, or esel I would have spoken up before.

**Comment by RobTerwel** [comment]
> Aha, but why add LNG to these charts?

I see your point, but LNG should be added for the simple reason that if a user decides to turn on FCE, natural gas suddenly has a much higher `co2_per_mj` attribute than LNG and it becomes much more favourable to import all natural gas as LNG, regasify it and feed it into the national grid.

I agree that adding LNG to FCE's does not add much information, but it does make the carrier level (i.e., have additional `co2_per_mj` attributes other than solely conversion) with natural gas if FCE's are used, and that's the point. 

I see several options:

- We could leave things the way they are, but delete the option to import natural gas from the Middle East, since it is actually LNG and it has been incorporated in the LNG slide.
- Or, we could have the FCE attributes of LNG solely in the backend. We could then use the original distribution from the base year (e.g. 40% Norway and 60% Qatar) and simply make sure that the other `co2_per_mj` attributes (i.e. extraction, transportation and treatment) are used when a user turns on the FCE option.

**Comment by RobTerwel** [comment]
After discussing this with @AlexanderWirtz and @jorisberkhout , we found another option::

- Merging the `Natural gas` and `LNG` FCE slides, naming it `Natural gas` and make an interface group called 'Pipeline gas' and include all existing natural gas FCE's (except the Middle East, since it's LNG) and one called 'Liquefied Natural Gas (LNG)' which includes all existing LNG FCE's.

Of course, the back end and documentation will de edited too. @ChaelKruip and @jorisberkhout , what are your preferences and thoughts on these three options?

**Comment by AlexanderWirtz** [comment]
As discussed please make sure that Norwegian and Algerian pipeline and lng varieties are included in both categories.

**Comment by ChaelKruip** [comment]
> Of course, the back end and documentation will de edited too. @ChaelKruip and @jorisberkhout , what are your preferences and thoughts on these three options?

I have no strong preference. Option one seems to be the least work :smile:

**Comment by jorisberkhout** [comment]
Hmm, separating the LNG energy flows from the natural gas flows in the ETM proves to be trickier than I had anticipated resulting in, amongst others, this FCE issue. Let's put a little more thought into this issue before closing it, @RobTerwel . My 2 cents (in random order):

- LNG needs FCE attributes, otherwise LNG becomes very favourable w.r.t. natural gas if the FCE calculation is switched on
- Since we now distinguish LNG and natural in the model, the most transparent thing to do is to let the user set the mix of origins for both of them
- LNG and natural gas essentially are the same thing, hence it would be could to report their FCE attributes on the same slide
- It would be good to re-evaluate the mix of origins (for all carriers)

**Comment by RobTerwel** [comment]
I fully agree, @jorisberkhout ! I think it's safe to conclude that we have now found a solution we all think is appropriate, so I will proceed as noted above (option 3), and 
- put all LNG FCE sliders on the natural gas FCE slide
- create an interface group so as to separate `pipeline natural gas` from `liquefied natural gas` and create a pull request  for it
- in the slide's information explain the distinction between the two forms of natural gas above
- delete the old LNG FCE slide
- delete the old `natural gas from the Middle East` FCE slider which is part of the natural gas FCE slide and is in fact LNG

such that the result would be something like this (note: slide's information and order of sliders haven't been edited yet, image from my local ETM)

![screen shot 2015-11-23 at 16 03 23](https://cloud.githubusercontent.com/assets/14106387/11339860/c8e0f74e-91fb-11e5-80f6-c2e760452d91.png)
