### ISSUE TITLE
Sliders cannot be moved using Chrome on Windows

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#1955]
As witnessed by @AlexanderWirtz yesterday. He doesn't know which version it was.

**Comment by AlexanderWirtz** [comment]
Sorry, was a bit busy to ask people which versio nthey were running. I noticed it for about 1/3 of the students using Windows laptops with Chrome. I asked those who could to switch to Firefox. That worked fine, which tells me it was indeed a Chrome issue.

Those Chrome users *could* type in slider settings, by the way.

**Comment by jorisberkhout** [comment]
@grdw, could you look into this?

**Comment by dennisschoenmakers** [comment]
Yesterday we used Chrome on Windows 7 and that worked just **fine**. :unamused:

**Comment by grdw** [comment]
Hmm... this looks weird.  Considering the date, can I assume this was Windows 10?

**Comment by grdw** [comment]
*Quick overview:*

- Windows 7 - Chrome 48.0.2564.97  - Works
- Windows 11 - Chrome 48.0.2564.97  - Works

I'm in the proces of checking Win 8 and 8.1 but they're still downloading :snail:

**Comment by AlexanderWirtz** [comment]
Could well be a specific Chrome version's problem. I asked the people to email me their versions but they never dod. Let's not spend too much time on this.

**Comment by jorisberkhout** [comment]
Thanks, @AlexanderWirtz . Closing this issue then.
