### ISSUE TITLE
More realistic prices in the transport sector (and beyond)

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1959]
The prices we use throughout the ETM, are flat carrier prices with the addition of cost attributes of converters these carriers flow through. This strategy is quite comprehensive, but there are certain converters in the ETM for which prices are quite far below those in reality (this mostly occurs for carriers which are used widely across the ETM). Let me illustrate this with an example.

Liquefied natural gas (LNG) has a `cost_per_mj` attribute which is based on the LNG harbour price, i.e. the landed retail price excl. taxes. This attribute therefore reflects the actual costs of LNG for ships pretty well, but that is quite different for LNG for trucks which yet has to be distributed via expensive highly insulating trucks to some inland retail station and stored there at -162 degrees Celsius max. We therefore, in practice, have two different prices: a LNG for shipping retail price and a LNG for road retail price 

The problem comes down to the fact we have chosen universal carrier prices, which actually depend on their destination. These price difference can however be levelled quite easily: having picked the `cost_per_mj` attribute of the carrier as the baseline, we can perhaps add a `cost_per_mj_surplus` attribute to certain converters. Let me apply this to the previous example:

The LNG `cost_per_mj` price is, in fact, that of LNG for shipping (LNG for road transport is more expensive, as we saw). We could add an attribute to the `transport_final_demand_for_road_lng` converter, such that for LNG `cost_per_mj` + `cost_per_mj_surplus` equals the retail price for that destination found in research (there is data for this). 

This `cost_per_mj_surplus` can simply be included in the node source analyses and then exported to ETSource. It would, however, require a new method in ET-Engine. 

Within the transport sector, these price discrepancies (between actual and modelled prices) are most significant for LNG and CNG. This idea can also be extended to other sectors, as network gas for industrial usage comes at a different price than the network gas for your personal combi boiler, for example.

@jorisberkhout , @ChaelKruip , @AlexanderWirtz @dennisschoenmakers , what do you think about this suggestion of adding a `cost_per_mj_surplus` attribute to some converters (initially just in transport)?

**Comment by ChaelKruip** [comment]
> what do you think about this suggestion of adding a cost_per_mj_surplus attribute to some converters (initially just in transport)?

I think it is a good idea but I have some questions and an alternative idea.

* What happens **after** a converter with `cost_per_mj_surplus` with the carrier costs? In other words: does the cost of the carrier drop to its normal `cost_per_mj` level or does it stay equal to `cost_per_mj + cost_per_mj_surplus`? 

If the places in the model where we need this are limited, I would also like to consider the alternative of creating a new carrier with different cost specs. The advantage of this is that it is always crystal clear what the costs of a carrier are. Transparency FTW!

**Comment by RobTerwel** [comment]
> What happens after a converter with `cost_per_mj_surplus` with the carrier costs? In other words: does the cost of the carrier drop to its normal `cost_per_mj` level or does it stay equal to `cost_per_mj + cost_per_mj_surplus`?

The way I thought of it, it stays equal to `cost_per_mj + cost_per_mj_surplus`, since this typically happens towards the end of a fuel chain .

However, I do like your idea better, because it is indeed more transparent, easier to implement, and easier to update! We could then, to stick to the original example, have the carrier `lng` in the `transport_final_demand_lng` which flows to `transport_final_demand_for_shipping_lng` where the carrier is then converted to a new `shipping_lng` carrier (which has its own carrier source analysis in ETDataset). 

I'm very much in favour! How does everyone else feel about this?

**Comment by AlexanderWirtz** [comment]
I just have an issue with the term surplus. If we assign additional costs, I think it should be named less ambiguously. Transparency demands a clear cut approach here, in my opinion. 

In case of infrastructure or distribution costs, it would be good to call it that. 

Other than that I like the overall idea and thinking behind this.
