### ISSUE TITLE
Make it possible to download the price curve and load curves from the Merit Order

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1964]
We get this request regularly by our power users. 

The information/functionality is already available to admin users on [http://beta.et-engine.com/data/latest/merit](http://beta.et-engine.com/data/latest/merit):
![energytransitionmodel](https://cloud.githubusercontent.com/assets/1303760/11838726/27b187b2-a3e9-11e5-8797-b69738983612.png)

Perhaps we could make download links either in the Merit Order section or the options menu:
![energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_](https://cloud.githubusercontent.com/assets/1303760/11838707/14f43f20-a3e9-11e5-92cd-b6c969f9fe0b.png)

@grdw can you pick this up before the end of the year? Please involve @antw in design of your solution.

**Comment by antw** [comment]
There's no support for putting something *beneath* a slider, and placing the download links directly above the on/off toggle made it harder to notice. So, I put the links after the first paragraph of the MO description; I feel like they're quite noticeable there, without distracting attention from the on/off button.

![screen shot 2015-12-31 at 15 45 54](https://cloud.githubusercontent.com/assets/4383/12065797/9c8ef4a0-afd5-11e5-97af-e1dc2577190c.png)

http://beta.pro.et-model.com/scenario/costs/merit_order/merit-order

**Comment by ChaelKruip** [comment]
:+1:
