### ISSUE TITLE
Should we add a curtailment node to the graph?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1970]
If we want to show curtailed electricity in the front-end, we must have a place to store the amount of it. Perhaps a node is the most logical choice?

@antw what is your opinion?

**Comment by antw** [comment]
> Perhaps a node is the most logical choice?

You mean to treat it like the `*_savings_from_insulation` nodes? I agree; this seems like a nice solution, and consistent with what we already have.
