### ISSUE TITLE
Where to put the hydrogen production slide in the user interface?

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1972]
There is not really a clear-cut place where the hydrogen production slide belongs, but I see the following main options:

### Transport Fuels

![screen shot 2016-01-06 at 11 19 45](https://cloud.githubusercontent.com/assets/14106387/12140686/1e509a8c-b46a-11e5-8ba0-460efa8c0225.png)

In the 'Transport Fuels' sidebar. For now, hydrogen is only used as a transport fuel so this location makes sense. However, there are at least two points:
- perhaps confusingly, there already is a 'Road Transport' slide (and merging these slides would give a mess) 
- all other sliders grouped in this sidebar are used to set fuel compositions - not the production techniques that yield those fuels, as this slide does.

### New sidebar 'Hydrogen'

![screen shot 2016-01-06 at 11 37 06](https://cloud.githubusercontent.com/assets/14106387/12140680/080acc7a-b46a-11e5-87eb-aa73bb8be9b4.png)
Or in a new sidebar item, 'Hydrogen'. This would - possibly - avoid some confusion and the points mentioned above. However, the question might be whether hydrogen (consisting of one slide as of now) is 'worthy' of its own sidebar (also lacking tutorial videos).

Also, we should keep in mind the P2G developments and the distinction that we have so far implicitly made between 'transport hydrogen' and 'P2G hydrogen'.

@jorisberkhout @AlexanderWirtz @ChaelKruip @dennisschoenmakers , which option has your preference or do you perhaps see a better alternative?

**Comment by dennisschoenmakers** [comment]
> @jorisberkhout @AlexanderWirtz @ChaelKruip @dennisschoenmakers , which option has your preference or do you perhaps see a better alternative?

New sidebar 'Hydrogen'. Would it make sense to call it 'Hydrogen production'? 

And what do the percentages mean? (market share? of what?)

**Comment by RobTerwel** [comment]
> Would it make sense to call it 'Hydrogen production'?

If no other slides are added to it, yes, absolutely. :smile:  

> And what do the percentages mean? (market share? of what?)

Percentage of total hydrogen produced that has been produced by this technology.

**Comment by dennisschoenmakers** [comment]
> Percentage of total hydrogen produced that has been produced by this technology.

Do you also set the production of hydrogen (somewhere)?

**Comment by RobTerwel** [comment]
> Do you also set the production of hydrogen (somewhere)?

The hydrogen production converters are demand-driven.

**Comment by jorisberkhout** [comment]
John prefers the section option ('sidebar item') with two changes:

1. Rename the slide sidebar item and slide to `Hydrogen production`
2. Put the `Hydrogen production` sidebar item in between the `Renewable heat` and `Transport fuels` sidebar items

I agree with John.

One minor comment by John is that we have to explain carefully what input fuels go into the various technologies.

**Comment by jorisberkhout** [comment]
Moved to 'Hydrogen Transport' milestone.

**Comment by AlexanderWirtz** [comment]
I am not against John's preference. There are pro's and con's for everything. it only makes sense if we also put P2G there, though!

**Comment by RobTerwel** [comment]
For now I did the following (John's and @jorisberkhout's preferences )

> 
 1. Rename the slide sidebar item and slide to Hydrogen production
 2. Put the Hydrogen production sidebar item in between the Renewable heat and Transport fuels sidebar items

I'm keeping this issue open, since P2G has not been added to the user interface yet and we should make sure that their (relative) positions make sense.

**Comment by AlexanderWirtz** [comment]
:+1:

**Comment by jorisberkhout** [comment]
Moving to 'Storage' milestone.

**Comment by jorisberkhout** [comment]
Closing this issue as everyone seems to like the current positions and orders of the slides
