### ISSUE TITLE
How to label the Brazilian dataset?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#1974]
The Brazilian dataset/model has a special status as it was created by Thais and Lucas. It would be good to stress this status in the front-end.

All I can come up with now is to label the dataset `Brazil (external research)`. Do anyone have a better solution? @AlexanderWirtz , @dennisschoenmakers , @antw , @grdw or @RobTerwel ?

**Comment by AlexanderWirtz** [comment]
what is their firm called. maybe we can let Thais have a say? Brazil (by Thais) looks kinda good to me.

**Comment by dennisschoenmakers** [comment]
What do you think @thaisclv ?

**Comment by dennisschoenmakers** [comment]
By the way @thaisclv: you can already see the Brazilian dataset on our **live** server: 

[**energytransitionmodel.com**](http://energytransitionmodel.com)

**Comment by thaisclv** [comment]
Happy New Year, Quintelers!

Great to see that the Brazilian dataset is on the live server! Lucas and I are very happy and looking forward to continue improving it!

About the company, I do have one, but it is called Thais Varella because I registred as an Individual Micro-Entrepreneur. I would say that for now we can keep it "Brazil (by Thais and Lucas)". In a few months we will create one together and we can change the name. What do you think?

Cheers!

**Comment by dennisschoenmakers** [comment]
> I would say that for now we can keep it "Brazil (by Thais and Lucas)". In a few months we will create one together and we can change the name. What do you think?

Excellent! We will do that! @grdw can you make the required adjustments?

**Comment by jorisberkhout** [comment]
I believe that John also wanted to move the Brazilian dataset to a separate category. Is that correct, @dennisschoenmakers ?

The list would then look like

`France`
`Germany`
`Netherlands`
`Poland`
`Spain`
`United Kingdom`
`--`
`EU-27`
`--`
`Brazil (by Thais and Lucas)`

**Comment by dennisschoenmakers** [comment]
I thought something like this:

```
France
Germany
Netherlands
Poland
Spain
UK
---
EU-27
Brazil (by Thais and Lucas)

**Comment by jorisberkhout** [comment]
:+1:

**Comment by grdw** [comment]
> @grdw can you make the required adjustments?

Yes, I can :+1:  will ook into this.

**Comment by grdw** [comment]
Like this:

![screen shot 2016-01-11 at 3 03 55 pm](https://cloud.githubusercontent.com/assets/2676542/12235498/8e955202-b874-11e5-93c2-57fd65c349f6.png)

**Comment by jorisberkhout** [comment]
Looks good!
