### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#1975]
![screen shot 2016-01-08 at 11 38 33 am](https://cloud.githubusercontent.com/assets/2676542/12196115/6e1cbe04-b5fc-11e5-94a1-9860ad45ada5.png)

**Comment by jorisberkhout** [comment]
I fixed this by importing the latest ETSource commit on Beta ETEngine and updating the key (as well as the renamed `agriculture_chp_supercritical_wood_pellets` key) in the staging database.

Closing.
