### ISSUE TITLE
Communicate to user overall increase when setting yearly increase

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1983]
The ETM features many sliders which allow the user to indicate the yearly growth of, say, useful demand. Since these functions are exponential, it might be instructive to communicate to the user the cumulative increase or decrease as a result of the yearly increase set.

Such an implementation (as has already been done for <a href="http://pro.et-model.com/scenario/costs/fuel_costs/combustion-fuel">carrier costs<a/>) could look like this (calculated for a 2050 scenario):

![image](https://cloud.githubusercontent.com/assets/14106387/12349992/44c6ebce-bb74-11e5-9175-2cf500b94d7c.png)

A 2.0% yearly increase might seem conceivable at first, but that actually amounts to a 100% overall for 2050. Especially for efficiency improvements it might be good to have this information - a 100% efficiency improvement for ICE engines seems quite unlikely, a 2.0% yearly increase perhaps less so. Of course it should be communicated to the user that this number is an _increase_.

I propose adding this to at least the mobility growth and efficiency improvement sliders in transport, but perhaps to all useful_demand updating and efficiency_improvement sliders.

@AlexanderWirtz , @jorisberkhout @ChaelKruip @dennisschoenmakers  do you think this is a good idea, and if so, do you have a preference for where to implement this?

**Comment by ChaelKruip** [comment]
I think this is a nice idea @RobTerwel. Big question is when we can find budget to pick this up.

**Comment by jorisberkhout** [comment]
I like it, @RobTerwel ! Putting on hold for now for the reason mentioned by @ChaelKruip .
