### ISSUE TITLE
Start year in front-end for NL/2013 dataset is not correct on Beta

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#1985]
I recently imported the new dataset for NL with start year 2013; the start year in all charts and tables in the front-end, however, is not updated (see picture below). This happened last year as well and the solution is described in https://github.com/quintel/etmodel/issues/1807. Could you look into this, @grdw ?

<img width="616" alt="screen shot 2016-01-20 at 09 23 05" src="https://cloud.githubusercontent.com/assets/4669028/12443426/0faa5272-bf58-11e5-837b-8f623b1ea8eb.png">

**Comment by grdw** [comment]
Where do you set the `start_year` ? Flushing the cache for memcached doesn't do anything (?) (I can verify that there's nothing left but the `start_year` is still 2012).

**Comment by jorisberkhout** [comment]
As far as I know, the value of `start_year` is taken from the [`<area>.ad` file on ETSource](https://github.com/quintel/etsource/blob/master/datasets/nl/nl.ad), where it is called `analysis_year`.

**Comment by grdw** [comment]
I asked @antw appreantly you should also restart `et-engine` after flushing the cache and than everything should work. 

Steps to take:

````bash
# Sign in to (beta) server of et-engine
ps aux | grep memc # check if it's running and under which ip and port
echo "flush_all" | nc -q 2 0.0.0.0 11211
kill -USR2 <et-engine pid>
````

**Comment by antw** [comment]
> ```
> #1923  Sign in to (beta) server of et-engine
> ps aux | grep memc # check if it's running and under which ip and port
> echo "flush_all" | nc -q 2 0.0.0.0 11211
> kill -USR2 <et-engine pid>
> ```

This should do it:

```sh
bundle exec cap staging deploy:restart
```

In this case I shut down the app completely and started it back up since I've found Unicorn's hot reloading (`USR2`) to be a bit hit-and-miss sometimes. I guess this could also be done with Capistrano:

```sh
bundle exec cap staging unicorn:stop memcached:flush unicorn:start
```
