### ISSUE TITLE
Functionalities vs Enegy demand sectors in interface, a wish list

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#1986]
In the Netherlands after the Energierapport has come out, the debate on energy now centers on so-called 'functionalities' of energy use, rather than following a sectoral approach. Examples of such functionalities are:
- Low-temperature heat (in residences, other buildings and industry sectors)
- High-temperature heat (in industry sector)
- Mobility / Transport (in transport sector)
- Power and light (electric appliances, light, ICT etc in pretty much all sectors) 

In order for the ETM to remain relevant to this discussion, it would be great if the interface could shed some light on which functionalities are represented where. John initially suggested an alternative arrangement in the interface, but this presents obvious problems concerning which sliders to move where and whether to keep using the same sliders. 

What is easier to do is to 'map' results to functionalities and create alternative or additional charts that provide a good overview of the most basic concepts like primary energy use, final energy use and CO@ emissions per functionality. I used Excel for this in the Rli project and it is not too hard, just time-consuming.

For now, we seem to have settled on an easier approach: sidebar items, slides or charts could be somehow 'marked' as pertaining to a certain functionality. This could be done by color-coding or simply by labelling them with text. My impression is that John is mostly interested in labelling / renaming the navigation menu in the side bar and the pages and slides. 

Any bright ideas on how to pull this off? Can this be part of the deploy? Let's have a lively discussion and settle on a short-term solution that is not too cumbersome.

@dennisschoenmakers @ChaelKruip @jorisberkhout @antw @grdw @RobTerwel please let us know what you think.

**Comment by AlexanderWirtz** [comment]
Assigning @ChaelKruip feel free to re-assign

**Comment by ChaelKruip** [comment]
After some brainstorming with @dennisschoenmakers I think that the only viable option would be a separate sidebar item which shows the user one or more slides where the results of the ETM in terms of 'functionalities' are summarised.

Adding labels or text to the current charts and slides in the ETM would lead to visual clutter and would obfuscate the current front-end without really adding any real help to the user (they would have to gather the relevant information by hunting for labels in the interface). 

I don't think we must include this feature in the next Deploy because it is already very full and complex. I can take a lead in designing a sidebar item and slides for this if time permits in the coming weeks though.

**Comment by ChaelKruip** [comment]
Removing Deploy milestone for this February.

**Comment by AlexanderWirtz** [comment]
>  I think that the only viable option would be a separate sidebar item which shows the user one or more slides where the results of the ETM in terms of 'functionalities' are summarised.

I am not sure I agree. I would start by creating extra charts that show/map functionalities. I do not like adding extra slides as that would be confusing (not MECE anymore). Perhaps we should create a toggle that transforms the one into the other in charts and dashboards? This is complex, but perhaps worth it.
 
**Easy option**
The easiest way to map to these functionalities is by adding one area attribute to the dataset, which sets the `present` percentage of industrial heat demand that is low-temperature heat. Of course, this attribute should also be associated with a slider that sets the `future` percentage. The problem is that in theory this would allow a user to have only steel production industrial demand that is 100% LT. 

**Harder option**
We can complicate things further by taking heat demand that is clearly HT (refineries, steel, etc) and declaring all of that HT, while setting a percentage of the rest of the heat demand that is LT. 

**My preferred option**
OR we could take the new industrial subsectors and try and figure out whether they represent HT or LT heat demand. Food is likely to be LT for example, as is paper, construction (?) etc. Metals, refineries etc are HT.

Whaddayathink @ChaelKruip @jorisberkhout @dennisschoenmakers

**Comment by ChaelKruip** [comment]
> My preferred option
OR we could take the new industrial subsectors and try and figure out whether they represent HT or LT heat demand. Food is likely to be LT for example, as is paper, construction (?) etc. Metals, refineries etc are HT.

My preference as well 👍

**Comment by RobTerwel** [comment]
> OR we could take the new industrial subsectors and try and figure out whether they represent HT or LT heat demand.

<a href="http://www.ce.nl/art/uploads/file/Denktank/Notities/CE_Delft_3F13_Denktank_Energiemarkt_Industriele_Warmtemarkt_DEF.pdf">This publication of CE Delft on the industrial heat demand<a/> is probably going to be quite helpful for that. I've used it myself to determine which industrial subsectors could have all their heat demand met by electric boilers.

**Comment by AlexanderWirtz** [comment]
Curious what @jorisberkhout thinks of this
