### ISSUE TITLE
Make first version for Ameland

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#1991]
I suggest we track the version we create here:

First attempt by @AlexanderWirtz : http://beta.pro.et-model.com/scenarios/458633

include @jorisberkhout for the deploy

**Comment by jorisberkhout** [comment]
:+1:

**Comment by jorisberkhout** [comment]
@dennisschoenmakers, is this critical for the deploy? If not, I suggest removing the milestone.

**Comment by dennisschoenmakers** [comment]
> @dennisschoenmakers, is this critical for the deploy? If not, I suggest removing the milestone.

Well, it should

**Comment by jorisberkhout** [comment]
This is done right, @dennisschoenmakers ?

**Comment by AlexanderWirtz** [comment]
Done but not complete. :-)

**Comment by dennisschoenmakers** [comment]
Newest version here: http://beta.pro.et-model.com/scenarios/481197

@AlexanderWirtz will still adapt the following:

- [ ] Include ferry to and from the island
- [ ] Adjust CO2 1990 value
- [ ] Clean up scenario description

Once @AlexanderWirtz is done, @grdw can create a preset.

**Comment by AlexanderWirtz** [comment]
FYI, I am waiting for the correct numbers for the ferry. The rest is easy.

**Comment by AlexanderWirtz** [comment]
Removing milestone as remaining points are not deploy critical.

**Comment by dennisschoenmakers** [comment]
Just to be clear: We will add this preset **after** the deploy when we receive updated figures. @jorisberkhout

**Comment by AlexanderWirtz** [comment]
I have added 2013 CO2 emissions as if they were 1990, as there is no data on actual 1990 emissions.

**Comment by RobTerwel** [comment]
I added one 'to do' to the list: the `number_of_cars` AREA attribute. It is automatically scaled to 519 now, but that number should be corrected to its actual value.

**Comment by dennisschoenmakers** [comment]
Closed, see quintel/etengine#835
