### ISSUE TITLE
Should we remove the €-sign from the investment table?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#1995]
While reviewing the recent changes to the investment table, I noticed that the column headers read `Investment (BLN. EURO)` ánd each cell contains a €-sign. I believe one of the two should go as they are giving the same information, and would prefer to remove the €-sign from each cell.

What do you think, @ChaelKruip , @AlexanderWirtz , @dennisschoenmakers, @antw ?

<img width="616" alt="screen shot 2016-01-26 at 11 42 15" src="https://cloud.githubusercontent.com/assets/4669028/12578658/a90e3a4a-c422-11e5-9573-d4d6bc8fbd39.png">

**Comment by ChaelKruip** [comment]
I agree that the euro signs are redundant and quite repetitive...

**Comment by dennisschoenmakers** [comment]
Good idea @jorisberkhout!

**Comment by jorisberkhout** [comment]
@AlexanderWirtz agrees with this as well.

@grdw, could you remove the €-sign from all cells in this table?

**Comment by AlexanderWirtz** [comment]
unless someone actually intended the use of the well-known €<sup>2</sup> unit, which can be very useful

**Comment by grdw** [comment]
Yes I could. However, just to play Devil's advocate, if I remove those signs isn't it confusing if I scroll down a little (just as much that the table header is off the screen) and seeing all these numbers which don't look like they're about money? The €-signs provide some context to something as "non-money looking" like `0.0784` (if it were `0.08` it would be less of an issue I'd guess).

**Comment by jorisberkhout** [comment]
> The €-signs provide some context to something as "non-money looking" like `0.0784`

To be honest, I find the €-sign more confusing than helpful in that example. The numbers in the cells are BLN Euro, but by placing the €-sign before them it looks like they are just Euro.

**Comment by grdw** [comment]
> but by placing the €-sign before them it looks like they are just Euro.

I agree. :+1:

**Comment by grdw** [comment]
On a related note:

![screen shot 2016-01-27 at 4 31 26 pm](https://cloud.githubusercontent.com/assets/2676542/12618276/7375d270-c513-11e5-8a9c-b3b75a896bff.png)

After some clicking (to test if I didn't destroy any other charts with euro-signs in them) I found this graph though. For the sake of consistency shouldn't we just pick one way to display bln euro's?

**Comment by antw** [comment]
> I found this graph though

I like that more than the "BLN. EURO" header, personally.

**Comment by jorisberkhout** [comment]
> I found this graph though

I wasn't aware of that graph and agree with @antw that that way of displaying is a nicer solution.

**Comment by jorisberkhout** [comment]
What do you think, @ChaelKruip ?

**Comment by ChaelKruip** [comment]
> I agree that the euro signs are redundant and quite repetitive...

I have not changed my mind :smiling_imp:

**Comment by grdw** [comment]
> I have not changed my mind

I think the only way we can resolve this is with a good old fist fight...

On a more serious note:
Now without euro signs:

![screen shot 2016-01-27 at 4 51 43 pm](https://cloud.githubusercontent.com/assets/2676542/12618989/7e8db97c-c516-11e5-9c31-3317b5cb4b9c.png)

However I might just create another issue for the sake of consistency.

**Comment by dennisschoenmakers** [comment]
I like it a lot better without the Euro-sign in your screenshot @grdw!

**Comment by antw** [comment]
I think it takes away context from the numbers; the individual values are easier to read but the table is harder to understand. A "BLN. EURO" header can be missed by a user while "€2.3375 bln" cannot. In most tables (but not this one, to be fair) you can hold your mouse over a number to see the full un-rounded version.

![screen shot 2016-01-27 at 16 12 41](https://cloud.githubusercontent.com/assets/4383/12619660/d6ba38f6-c510-11e5-9d1a-7c20fece402f.png)

I'm not too bothered about one table – and this change should go ahead if there is support – but I'm worried this escalates into removing all units from all tables (#1999) which would be a bad move IMO.

**Comment by grdw** [comment]
> I'm worried this escalates into removing all units from all tables (#1999) which would be a bad move IMO.

Yes. That's a bad move. In my issue I'm just talking about "money"-related tables.

**Comment by dennisschoenmakers** [comment]
> [...] I'm just talking about "money"-related tables.

I know what you're talking 'bout!

![image](https://cloud.githubusercontent.com/assets/104830/12620123/39beb2f6-c51b-11e5-879b-97d2788bd80e.png)

**Comment by grdw** [comment]
We've chosen to display it as `€ <x> bln/mln/..` by using the same `valueFormatter` from the default tables.

This looks like this:

![screen shot 2016-01-29 at 12 24 31 pm](https://cloud.githubusercontent.com/assets/2676542/12675649/1141e90c-c68c-11e5-8fb4-bc958712a366.png)

I've also removed the BLN EURO headers for they are redundant.

**Comment by jorisberkhout** [comment]
> We've chosen to display it as € <x> bln/mln/.. by using the same valueFormatter from the default tables.

> We've chosen to do this due to context of the numbers and the consistency with other tables that are related to money (aka "money"-tables :dollar:).

Yeah! I like this solution a lot for, especially for its consistency with the other tables!

Notifying @AlexanderWirtz and @ChaelKruip as they use this table most often!

**Comment by ChaelKruip** [comment]
> Notifying @AlexanderWirtz and @ChaelKruip as they use this table most often!

Thanks for that. I like the table too like this. 

The only possible issue I see is that it becomes more difficult to copy-past and analyse this table in Excel now. Especially if different lines may have different units, it would require some complex find-replace tasks in Excel to make the numbers of equal order of magnitude again. @AlexanderWirtz do you think this is an issue?

**Comment by jorisberkhout** [comment]
> The only possible issue I see is that it becomes more difficult to copy-past and analyse this table in Excel now.

Thanks for this comment, @ChaelKruip . I realised this as well and discussed the possibility to download the data from the investment table directly with @grdw . That would avoid having to copy-paste the data at all. @AlexanderWirtz , should we go ahead and implement this?

**Comment by grdw** [comment]
> it becomes more difficult to copy-past and analyse this

Wouldn't we want an export function for this? Manually copy/pasting sounds really dreadful.

**Comment by AlexanderWirtz** [comment]
@jorisberkhout it would be great to be able to export the data for Excel from the tables. That also means I won't have to hassle @antw about changing number of significant digits etc.

**Comment by antw** [comment]
I love the idea of exporting tables to CSV; that could be very useful.
