### ISSUE TITLE
Redirect all trafic to energytransitionmodel.com

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etmodel#1996]
So we can purchase a wildcard SSL certficate for *.energytransitionmodel that covers:
- www.energytransitionmodel.com (etcentral)
- pro.energytransitionmodel.com
- moses.energytransitionmodel.com

You'd still be able to type: pro.et-model.com, or moses.et-model.com, but you will be redirected! :smile:

What do you think @grdw and @antw ?

**Comment by antw** [comment]
:+1:

We might need to also move ETEngine to a subdomain (otherwise requests to ETE might result in "this website is insecure" warnings), but I see no problem doing that.

**Comment by dennisschoenmakers** [comment]
> We might need to also move ETEngine to a subdomain (otherwise requests to ETE might result in "this website is insecure" warnings), but I see no problem doing that.

engine.energytransitionmodel.com ?

**Comment by antw** [comment]
> engine.energytransitionmodel.com

Sounds good.
