### ISSUE TITLE
Hydrogen production sidebar needs sidebar image

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1998]
See title, /scenario/supply/hydrogen_production/

Suggestion: H<sub>2</sub> , in sidebar image style. Plain and simple! :smile:

**Comment by dennisschoenmakers** [comment]
What do you think? 

![image](https://cloud.githubusercontent.com/assets/104830/12617592/a44a6954-c510-11e5-875c-ebcc7233ee16.png)

**Comment by RobTerwel** [comment]
> What do you think?

Perfect!
