### ISSUE TITLE
Disable charts when merit is disabled

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2001]
Like the charts described in https://github.com/quintel/etmodel/issues/1922, the following charts only display relevant information when the merit order is enabled. Could you implement the same warning you implemented in a2346ed4452fbffd664e2b23fb41ea95fd68b6c9 for these charts, @grdw ?

- Chart 163: Use of excess electricity
- Table 164: Storage options

**Comment by grdw** [comment]
@antw do you know how "Chart 163: Use of excess electricity" is rendered?

I found the `app/assets/javascripts/lib/views/vertical_stacked_bar_chart_view.coffee` file but when I alert something in the initialize method nothing much happens. Am I using the wrong file or?

**Comment by antw** [comment]
I think it's a [D3.stacked_bar](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/d3/stacked_bar.coffee). Many of the old `javascripts/lib/views/` charts were replaced with D3 versions (in `javascripts/d3/`) some time ago. I think the old ones were kept to retain support for older browsers in which D3 was not supported (IE6).

**Comment by grdw** [comment]
https://github.com/quintel/etmodel/pull/2003

**Comment by jorisberkhout** [comment]
Closed by #2003.
