### ISSUE TITLE
Make it possible to download the investment table

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2005]
As discussed in https://github.com/quintel/etmodel/issues/1995#issuecomment-176785338, it should be possible to download the contents of the investment table.

@grdw , you had a suggestion on how to format this download and make this happen, right?

**Comment by jorisberkhout** [comment]
As discussed with @grdw, it would be nice if we could make it possible to download the data in *all* tables as CSV.

**Comment by grdw** [comment]
![redodt](https://cloud.githubusercontent.com/assets/2676542/12719132/85505c5c-c8f3-11e5-8a5b-fe4982e8a289.png)

At the position of the red dot there will be an extra button; a download-like button. A bit like the icon used on the merit order page:

![screen shot 2016-02-01 at 2 56 29 pm](https://cloud.githubusercontent.com/assets/2676542/12719213/086537d4-c8f4-11e5-8dad-1a732195dac4.png)

However; I have some questions about the technical implementation of this feature. When I export the table to a CSV do I extract the literal values I see on the screen or will I fetch the 'raw' unrounded values (or both)?

**Comment by antw** [comment]
I think raw, [unrounded values](https://github.com/quintel/etmodel/blob/196e72242cbacea8594fcd8d976ed5dc523d7be6/app/assets/javascripts/lib/models/chart_serie.coffee#L7-L8). Ideally this would not be specific to the investment table; [TableView](https://github.com/quintel/etmodel/blob/196e72242cbacea8594fcd8d976ed5dc523d7be6/app/assets/javascripts/lib/views/table_view.coffee) should be a good starting point for how to get all the values.

**Comment by grdw** [comment]
> be a good starting point for how to get all the values.

I'd guess on a somewhat similar basis it's now implemented in [Etmoses](https://github.com/quintel/etmoses/blob/master/app/assets/javascripts/les/topology_load_charts/csv_download.js)?

**Comment by antw** [comment]
> similar basis it's now implemented in Etmoses?

:+1:

**Comment by jorisberkhout** [comment]
Let's pick this up as part of the broader issues described in https://github.com/quintel/etmodel/issues/2015.
