### ISSUE TITLE
Domestic shipping shouldn't be hidden for scaled scenarios

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2009]
@AlexanderWirtz is creating a (scaled) scenario for Ameland and wants to use this slider to set the domestic shipping energy use for the ferry from and to the island.

Not sure 'why' the slider is hidden. (btw: also domestic flights are hidden).

Including @antw

**Comment by jorisberkhout** [comment]
Any ideas, @RobTerwel ?

**Comment by dennisschoenmakers** [comment]
Hmmm, on **beta** it doesn't hide @AlexanderWirtz ...

### national scenario:

![image](https://cloud.githubusercontent.com/assets/104830/12780572/f1e606ec-ca6e-11e5-87dc-813e2a3a995b.png)

### local scenario

![image](https://cloud.githubusercontent.com/assets/104830/12780605/1edc657e-ca6f-11e5-8378-2ab2b3691aad.png)

**Comment by dennisschoenmakers** [comment]
But... we're missing these sliders:

### national

![image](https://cloud.githubusercontent.com/assets/104830/12780639/5394b8fc-ca6f-11e5-9ee9-b50fd26ea9ba.png)

### scaled

![image](https://cloud.githubusercontent.com/assets/104830/12780650/647a98b2-ca6f-11e5-8efc-3afa27452a5d.png)

**Comment by RobTerwel** [comment]
Hmm interesting. Not on the top of my head, I looked in `scenario_scaling.rb` and found there are some inputs which are excluded <a href="https://github.com/quintel/etengine/blob/dcb76f7dcc1aadd58765aafe1e176403640de3ff/app/models/scenario_scaling.rb#L7-L9"a>here<a/> in ETEngine, depending on the units of the input statement. However, other vehicle technologies (also having % as a unit) are not excluded.

**Comment by dennisschoenmakers** [comment]
Found it:

![image](https://cloud.githubusercontent.com/assets/104830/12780723/d0129d72-ca6f-11e5-8ee6-8789e4bf861d.png)

**Comment by dennisschoenmakers** [comment]
I removed the row from beta.et-engine.com

**Comment by dennisschoenmakers** [comment]
> Hmm interesting. Not on the top of my head, I looked in scenario_scaling.rb and found there are some inputs which are excluded here in ETEngine, depending on the units of the input statement. However, other vehicle technologies (also having % as a unit) are not excluded.

BTW: What are listed [there](https://github.com/quintel/etengine/blob/dcb76f7dcc1aadd58765aafe1e176403640de3ff/app/models/scenario_scaling.rb#L7-L9) are **unscalable** inputs, such as market shares: you do not want to scale 50% of all households having a combi heater, or the insulation level of existing houses.

**Comment by RobTerwel** [comment]
@dennisschoenmakers Thanks for explaining!
