### ISSUE TITLE
How can dependent_on by empty in area dependencies?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2010]
![image](https://cloud.githubusercontent.com/assets/104830/12780442/49d4404a-ca6e-11e5-9b7d-5577fea72842.png)

including @RobTerwel @ChaelKruip @jorisberkhout: who knows? :smile:

**Comment by antw** [comment]
The forms for these models will submit an empty area dependency if you don't select one:

![screen shot 2016-02-03 at 11 28 05](https://cloud.githubusercontent.com/assets/4383/12780970/3d0c3b1a-ca69-11e5-8faf-91230a9f03d0.png)


```json
{
"input_element": {
  "area_dependency_attributes": {
    "dependent_on": null
  }
}
```

[`accepts_nested_attributes_for`](https://github.com/quintel/etmodel/blob/fa250e70b9835374abfc7de6c6c15629a895a5c7/app/models/input_element.rb#L34) will then save a blank AreaDependency. We should probably [add a `reject_if` value](http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html) to prevent the creation of empty records; although they don't have any negative effect, they are a bit pointless.

**Comment by dennisschoenmakers** [comment]
Thanks!
