### ISSUE TITLE
BUG: Dashboard popup charts are empty on Beta

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2011]
At least:
* energy use
* CO2 emissions

including @jorisberkhout

**Comment by dennisschoenmakers** [comment]
It looks so empty:

![image](https://cloud.githubusercontent.com/assets/104830/12807637/dc4cd6f6-cb10-11e5-9080-f22a175eaefd.png)

**Comment by RobTerwel** [comment]
Interestingly enough, of all standard dashboard items Energy imports and Bio-footprint are not empty, the others are.

**Comment by jorisberkhout** [comment]
The charts themselves are still working, so it must have something to do with the pop-ups themselves. Maybe something to do with https://github.com/quintel/etmodel/issues/1921?
