### ISSUE TITLE
Population statistics is missing unit

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2012]
E.g. for Ameland the slider says 3.52k inhabitants, the chart 3.52:

![image](https://cloud.githubusercontent.com/assets/104830/12807711/b8ba943e-cb11-11e5-9988-f4c42a058056.png)

**Comment by jorisberkhout** [comment]
The same is true for an *un*scaled scenario, where the table says `16.78` inhabitants, which should be `16730348.0`.

**Comment by jorisberkhout** [comment]
Assigning @grdw as I would guess that this has to do with the way the tables are formatted.

**Comment by grdw** [comment]
This has to do with the fix for: https://github.com/quintel/etmodel/issues/1995

**Comment by grdw** [comment]
Turns out that there was a `scaleDown` boolean which was `true` by default. Setting it to false turned the numbers back to:
![screen shot 2016-02-04 at 9 50 39 am](https://cloud.githubusercontent.com/assets/2676542/12810180/c6748752-cb24-11e5-86da-320f3ecccc30.png)

Like it is on production.

**Comment by jorisberkhout** [comment]
Thanks, @grdw . One thing before we can close this issue. Could you round the `Number of inhabitants per residence` to 1 decimal (like `2.2`). Otherwise this table gives to little information.

**Comment by jorisberkhout** [comment]
Thanks for fixing this. @dennisschoenmakers , the units are back again on Beta.
