### ISSUE TITLE
New order of 'Add chart` library not an improvement

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2013]
I noticed that on Beta the order of the 'Add chart' List has been changed. It no longer starts with 'Overview' but with 'Supply'. How come? Did we have a vote on this? I for one do not think it is particularly intuitive to start with Supply.

The new order is:

1. Supply
2. Targets
3. Overview
4. Costs
5. Demand
6. Merit Order

I am a frequent user of these charts in demonstrations and at least for my demo's this is hardly the order 
in which I would like charts to appear.

Here is the order I prefer:

1. Overview
2. Merit Order
3. Costs
4. Supply
5. Demand
6. Targets

Almost not a demonstration goes by that I do not load a mekko chart from overview.
Targets is so unused, I cannot remember the last time I looked at it. 
Demand has so many charts, it is a good idea to put it relatively low in this list.

@jorisberkhout @dennisschoenmakers curious what your thoughts are

**Comment by dennisschoenmakers** [comment]
Related issue where there has been a vote on ordering charts: #1923

**Comment by jorisberkhout** [comment]
Good point, @AlexanderWirtz . As far as I am aware, we did not decide to change the order of the chart groups. All that was decided in #1923 is to add subgroups for the demand charts (per sector) to break up the lengthy list of demand charts. The order that is discussed in #1923 is the order of the charts *within* the groups.

**Comment by jorisberkhout** [comment]
> Here is the order I prefer:
>
> 1 Overview
> 2 Merit Order
> 3 Costs
> 4 Supply
> 5 Demand
> 6 Targets

@AlexanderWirtz , just to be clear, your preferred order is different from the one on LIVE. Should we go ahead and implement this?

**Comment by dennisschoenmakers** [comment]
I think [this Q&A](https://github.com/quintel/etmodel/issues/1923#issuecomment-172496419) in #1923 lead to the reshuffle:

> > Is it important that the graphs stay in the same order?

> No

**Comment by jorisberkhout** [comment]
> I think this Q&A in #1923 lead to the reshuffle

Thanks, @dennisschoenmakers . As #1923 is specifically about the charts *within* the Demand group, I don't see why the order of the groups has been altered, but I see where it happened in the code and will talk to @grdw to fix it.

**Comment by dennisschoenmakers** [comment]
Merci!

**Comment by jorisberkhout** [comment]
Also, there is this mysterious Chart Sub Group that should not be there.

<img width="432" alt="screen shot 2016-02-04 at 08 59 43" src="https://cloud.githubusercontent.com/assets/4669028/12809308/4cfd6660-cb1e-11e5-8ab7-8c9af186498d.png">

**Comment by jorisberkhout** [comment]
Assigning @grdw to fix this. Come talk to me first.

**Comment by grdw** [comment]
> Also, there is this mysterious Chart Sub Group that should not be there.

IS gone. Difference between `NULL` and `''` is still a difference. Might check for present as a fix.

**Comment by jorisberkhout** [comment]
As discussed with @AlexanderWirtz , this is not deploy critical.

So far the order of the groups was hard-coded in ETModel. As discussed with @grdw , it would be better if you can set the order through the admin interface of ETModel. Any thoughts on this, @dennisschoenmakers , @AlexanderWirtz , @ChaelKruip and @antw ?

Also, I re-opened https://github.com/quintel/etmodel/issues/1923, which is relevant for this issue.

**Comment by ChaelKruip** [comment]
> Any thoughts on this

A nice-to-have certainly

**Comment by jorisberkhout** [comment]
Would it be possible to make this happen before the September deploy, @grdw ?

**Comment by grdw** [comment]
I put FCE under Targets if that's ok? The new order is visible [here](https://github.com/quintel/etmodel/pull/2220).
