### ISSUE TITLE
New dataset information page does not work as expected

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2016]
<img width="363" alt="screen shot 2016-02-04 at 11 13 42" src="https://cloud.githubusercontent.com/assets/4669028/12812012/62a2af68-cb30-11e5-892c-5e196f3f87ac.png">

- If I hit the `Start a new scenario from this country` button, nothing happens
- If I hit the `Go back to the model` link, it opens a (new?) scenario
- (minor) I think the first `Go back to the model` link is redundant

**Comment by grdw** [comment]
> If I hit the Start a new scenario from this country button, nothing happens

No, you got to the front-page of etmodel and the country is prefilled with the country you selected. Obviously "The Netherlands" is the default so "nothing happens". This had to do with the fact that you can't specify the end-year in this layout and it would be a little double to also include it in this page.

> (minor) I think the first Go back to the model link is redundant 

I got that link for free using the 'pages' layout. Guess I could use a 'blank' layout considering the empty-state of the page - as of now.
