### ISSUE TITLE
Should we turn the merit order ON for the default scenario?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2017]
We ask ourselves this question regularly. Let's use this issue to write down the pros and cons and take a decision.

**PROS**
- with the merit order on, the behaviour of the ETM is much more realistic
- the new flexibility feature only works when merit is switched on
- quite a few charts rely on the merit order being switched on (although this has been solved quite nicely with the new merit order warning)

**CONS**
- with the merit order on, the future year and present year of a scenario are no longer identical (I know they currently aren't either because of the timecurves for gas, oil, etc., but the difference will become much more pronounced)
- with the merit order on, there will be no import if electricity for the future year of the scenario, which for the Netherlands is very different from the present

John is strongly in favour of switching the merit order ON for the default scenario, unless it puts to much load on the servers.

What about you, @AlexanderWirtz , @dennisschoenmakers , @ChaelKruip and @antw ?

**Comment by ChaelKruip** [comment]
I am in favour of turning Merit 'on'. We should put the two 'cons' in the known issue list though!

**Comment by dennisschoenmakers** [comment]
In favor of On!

**Comment by AlexanderWirtz** [comment]
On! On! On!

**Comment by antw** [comment]
> unless it puts to much load on the servers.

Load is not really a problem since the servers are not that busy and we have enough CPU cores. The issue I have is with the additional *time* it takes calculate the merit order, and that it requires the future graph to be computed twice. ETEngine response times with the M/O off are 300-500ms. With the M/O on, this rises to 700-1000ms and this makes the ETM feel a lot less responsive. The delay between moving a slider and seeing the outcome is more noticeable.

I would *like* to turn it on as well, but I think it's for you to judge if the additional latency is acceptable.

--

By the way, turning it on for *every* scenario is easy. Turning it on *by default* – so that a user may still opt to turn it off – is a bit more work. We'd probably have to set the `enable_merit_order` input to have a default value of `1` ("on") and create a migration for all the old scenarios and presets to set it back to `0` ("off").

**Comment by jorisberkhout** [comment]
> ETEngine response times with the M/O off are 300-500ms. With the M/O on, this rises to 700-1000ms and this makes the ETM feel a lot less responsive. The delay between moving a slider and seeing the outcome is more noticeable.

Good point. I personally don't mind, given all the pros of switching it ON. I will call John to see what he thinks.

> By the way, turning it on for every scenario is easy. Turning it on by default – so that a user may still opt to turn it off – is a bit more work. We'd probably have to set the enable_merit_order input to have a default value of 1 ("on") and create a migration for all the old scenarios and presets to set it back to 0 ("off").

Does it make a difference if we turn the merit on by default for all scenarios that are created *from now on*?

**Comment by jorisberkhout** [comment]
> ETEngine response times with the M/O off are 300-500ms. With the M/O on, this rises to 700-1000ms and this makes the ETM feel a lot less responsive.

John is fine with this as well (as long as the response time stays below 1s).

**Comment by antw** [comment]
> Does it make a difference if we turn the merit on by default for all scenarios that are created from now on?

Unfortunately no. We could theoretically do it by forcing every new scenario to inherit from a preset where the merit order is turned on (with no other input values set), but I think that would be to open a very messy can of worms. :laughing: 

Better to go back and turn it off for all the old scenarios.

**Comment by jorisberkhout** [comment]
> Better to go back and turn it off for all the old scenarios.

Right, let's do that then. BTW, let's do this later this afternoon the earliest as Beta needs to be stable between 12h00 and 14h00 CET for the presentation by @AlexanderWirtz and @dennisschoenmakers .

**Comment by antw** [comment]
> John is fine with this as well (as long as the response time stays below 1s).

A couple of samples with the merit order on:

![screen shot 2016-02-04 at 10 49 03](https://cloud.githubusercontent.com/assets/4383/12812956/f3e228d6-cb2c-11e5-9250-000375cf9256.png)

**Comment by dennisschoenmakers** [comment]
Is this going to be implemented? I was surprised to find it off by default on beta still.

**Comment by antw** [comment]
It is on my todo list, yes. :grimacing:

**Comment by jorisberkhout** [comment]
Reopening this. On Beta, the merit order is not switched on for the default scenario for NL. It is for all other datasets.

**Comment by jorisberkhout** [comment]
> On Beta, the merit order is not switched on for the default scenario for NL.

Never mind, I can't reproduce this and nor can @dennisschoenmakers . Closing this issue :blush:

**Comment by antw** [comment]
> I can't reproduce this

I could at the time you posted your comment, but can't now nor can I reproduce it locally. I made a small change to ETEngine anyway, just to be 100% sure that "merit order off" doesn't persist after the graph optimisation step.
