### ISSUE TITLE
Can't drag the flexibility order when there's no api_session_id set yet.

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2018]
![screen shot 2016-02-05 at 12 19 22 pm](https://cloud.githubusercontent.com/assets/2676542/12844932/c3315f46-cc02-11e5-9fcc-31c14701a820.png)

Steps to take:
1. Close Chrome
2. Open Chrome
3. Copy/paste url in browser: http://beta.pro.energietransitiemodel.nl/scenario/flexibility/electricity_storage/order-of-flexibility-options
4. Cry :sob: because it's broken
5. Refresh
6. It works again! (no matter how many times you hit the refresh button).

I think this is because there's no `api_session_id` assigned yet (aka I'm to fast).

@jorisberkhout I think this is the same problem you experience because this stops you from dragging the options.

**Comment by antw** [comment]
[This is the callback executed when the ID is set](https://github.com/quintel/etmodel/blob/843165be34d0af07090703b9229b38e797c04a7a/app/assets/javascripts/lib/app.coffee#L31-L33).

The Backbone way of doing things would – I think – be to set a listener on the Settings object so that the flexibility configured is set up when the ID is set. Something like this:

```js
// app/assets/javascripts/lib/models/chart.coffee:42

App.settings.on("change:api_session_id", function(sessionID) {
  @view.set_sortable(sessionID);
});
```

This might not trigger if the ID has been set already (not sure, so try it) in which case you may also have to add:

```js
if (var sessionID = App.settings.get('api_session_id')) {
  @view.set_sortable(sessionID);
}
```

**Comment by grdw** [comment]
Hmmmm yes. I found out the problem is a bit weirder than that. The `helper` generates the urls for me and already in that step the session_id is missing. So I removed the helper method and build up the url in the javascript. That seems to be fixing the problem :smile: 

Now I need to google a nicer way of making an url than:

````javascript
globals.api_url + 'api/v3/scenarios/' + globals.api_session_id + '/flexibility_order'
````

**Comment by antw** [comment]
Keep in mind that what you want is `App.settings.get("api_session_id")` – not `globals.api_session_id` – as `globals` won't be updated when the ID arrives.

`globals` will only have a value if the visitor is continuing a previous scenario; I expect it will be empty if they are a first-time visitor (and maybe also if starting a new scenario).

**Comment by grdw** [comment]
> Keep in mind that what you want is App.settings.get("api_session_id")

Oh yes.

![chael-clippy](https://cloud.githubusercontent.com/assets/2676542/12846145/183f5aee-cc0b-11e5-9a79-966c0a9058e6.png)
