### ISSUE TITLE
Behavior of search-bar etmodel rather strange

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2021]
![screen shot 2016-02-05 at 4 32 13 pm](https://cloud.githubusercontent.com/assets/2676542/12850653/0e241c50-cc26-11e5-9ec5-7cae83bd4a5f.png)

I find the behavior of the search button of etmodel rather weird. I get what it does after trying it a couple of times but I expect it to search within the scope of etmodel. In essence, so I can find specific sliders / information on the website / etc.

**Comment by jorisberkhout** [comment]
Good point, @grdw . I now found out that you actually search the ETM Library with this search box. Perhaps the text needs to be changed from `Search` to `Search ETM Library`. What do you think about this change, @dennisschoenmakers , @AlexanderWirtz and @ChaelKruip ?

**Comment by AlexanderWirtz** [comment]
Good point. Does it at least point to refman2?

**Comment by dennisschoenmakers** [comment]
It used to search in the scope of etmodel **and** refman. I would be in favor of reducing that to *only* etmodel: less is more.

**Comment by jorisberkhout** [comment]
> It used to search in the scope of etmodel and refman.

Really? If you use the search bar now, you get redirected to refman.energytransitionmodel.com and the term you searched for is copied to the search box in the Refman.

>  I would be in favor of reducing that to only etmodel: less is more.

I like that idea. Can I assign this to you @dennisschoenmakers (this issue was assigned to me during the  February deploy). Re-assign at will.

**Comment by dennisschoenmakers** [comment]
> Really? If you use the search bar now, you get redirected to refman.energytransitionmodel.com and the term you searched for is copied to the search box in the Refman.

Now I remember: we had a full text search using ElasticSearch, but since it crashed too often, we got rid of it, and choose the current (poor man's) solution.

**Comment by michieldenhaan** [comment]
Closing, search bar doesn't exist any more
