### ISSUE TITLE
Dragging and dropping of the flexibility options doesn't work in [IE9]

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2022]
The library I use is a little to fancy.

**Comment by grdw** [comment]
I switched to jQuery ui and used the sortable module. 

It still contains the same problem. IE9 doesn't finish the Ajax request. 

https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/views/base_chart_view.coffee#L108

Doesn't it have something to do with the fact that we use `api_url` always instead of the `proxy_url` ?

**Comment by antw** [comment]
> @antw Doesn't it have something to do with the fact that we use api_url always instead of the proxy_url ?

Yes. I found that you should use `App.api.path` instead; it will return the correct path depending on what the browser supports:

```js
App.api.path('hello')
// => "http://www.et-engine.com/api/v3/hello"
```

**Comment by grdw** [comment]
Fixed by: https://github.com/quintel/etmodel/commit/32e4f593cd35378aa77865c3437aaee86c17530e
