### ISSUE TITLE
Chart glitches before rendering [IE9]

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2023]
![virtualbox_ie9 - win7_08_02_2016_10_02_02](https://cloud.githubusercontent.com/assets/2676542/12881573/1012f546-ce4b-11e5-8460-d6f3cedf8e57.png)

It happens in a split second so it's not that much of a problem. 

Reassign at will.

**Comment by jorisberkhout** [comment]
Re-assigning @grdw . Not deploy critical.

**Comment by grdw** [comment]
Closing due to limited support IE9
