### ISSUE TITLE
When typing a wrong email address you get redirected to an unstyled page 

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2024]
When typing a wrong emailadres you get redirected to an unstyled page (is this the default Devise page?).

![screen shot 2016-02-08 at 10 04 07 am](https://cloud.githubusercontent.com/assets/2676542/12881629/83acc6f8-ce4b-11e5-9a5e-b7e2cc5cec4a.png)

@jorisberkhout  Reassign at will

- [ ] Remove two 'home' links at top and bottom of this page

This is present in the `static_page` layout. This probably needs some general TLC as most static pages don't look that great.

- [ ] Fix the 'look-and-feel' of the inputs 
- [ ] Align the radio buttons with the rest of the form

**Comment by jorisberkhout** [comment]
Re-assigning @grdw . Not deploy critical though.
