### ISSUE TITLE
Table for flexibility options needs improvement

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2026]
I am afraid I find the table quite confusing.
Below find a random pair of screenshots in NL and EN

![image](https://cloud.githubusercontent.com/assets/308563/12882965/54ad9b5c-ce55-11e5-87e1-c7733a876f0e.png)

![image](https://cloud.githubusercontent.com/assets/308563/12882998/7d9d8400-ce55-11e5-8721-925038d23a2a.png)

I would change to following to improve the clarity:

- [x] electrische auto's --> elektrische auto's
- [x] 'Curtailment' in NL version --> 'Productievermindering'
- [x] Left align leftmost column
- [x] Total capacity (MW) --> Available capacity (MW) (similar in NL)
- [x] Total volume (MWh) --> Available storage / conversion volume (MWh) (similar in NL)
- [x] Annual demand (PJ) --> Annual usage (PJ)
- [x] Jaarlijkse vraag (PJ) --> Jaarlijkse inzet (PJ)
- [x] Annual demand (MWh) --> Annual usage (MWh or TWh)
- [x] Jaarlijkse vraag (MWh) --> Jaarlijkse inzet (MWh or TWh)
- [ ] Can we add a column that displays the order of the option as the user has set it?
- [ ] Can we add another row for "Total usage"? This makes comparison with the chart easier.
- [x] The "?" symbol reveals no content. I can do this, but I do not really understand the chart
- [x] Can we include a warning that this table / calculation only works if Merit Order is on? Kind of like the profitability chart (#1922) ?
- [x] make units scale dynamically / increase the number of digits
 
Demand / Vraag is quite confusing as there is no natural demand for an option that provides relief for oversupply.

The usage in MWh, makes it easier to compare it to the volume. People cannot convert MWh to PJ easily.

Including @RobTerwel @ChaelKruip @dennisschoenmakers 
Reassign to whomever is best placed to pick this up

**Comment by jorisberkhout** [comment]
Moved to storage milestone.

**Comment by jorisberkhout** [comment]
All tables that are generated by ETEngine have a centre-aligned leftmost column. I suggest to stick with this for consistency. I suggest we re-evaluate that decision as part of https://github.com/quintel/etmodel/issues/2015.

<img width="629" alt="screen shot 2016-02-08 at 18 00 00" src="https://cloud.githubusercontent.com/assets/4669028/12892736/d0e3c29a-ce8d-11e5-834a-5c232c491ed3.png">

**Comment by jorisberkhout** [comment]
I have added a description of the table (as well as for chart 163), that is showed when you hit the '?'.

**Comment by AlexanderWirtz** [comment]
No problem for me to delay that one.

**Comment by jorisberkhout** [comment]
As noted by John, the units for the numbers in the table do not get adjusted dynamically. This means that  for scaled scenarios, the column shows just `0.0`. An easy fix would be to increase the number of digits in the table to 4. The nicer fix would be to make the units dynamic. I added this point to the list in the first post of this issue.

**Comment by jorisberkhout** [comment]
@AlexanderWirtz , given the way these tables are generated, I foresee issue when we try to add the position of technologies in the flexibility order to the table. I like the idea very much and have created a separate issue ( #2052 ).
