### ISSUE TITLE
Flexibility charts cannot be loaded in 'chart picker'

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2028]
This means I cannot see the `Use of excess electricity` chart (love it) and the `Flexibility options` table in the same screen. This is kind of annoying. not deploy critical.

Reassign at will

**Comment by jorisberkhout** [comment]
Assigning @grdw to look into this.

**Comment by jorisberkhout** [comment]
`Use of excess electricity` is shown in the chart picker (Overview -> last chart).

The `Flexibility options` table indeed isn't. @grd could you fix this?

**Comment by jorisberkhout** [comment]
As discussed with @AlexanderWirtz and @ChaelKruip , I moved both charts to the merit group in the chart picker which I renamed to `Merit order and flexibility` in c8c8cbc825fbd5114f28759b65efd936bbc1f7db.

**Comment by AlexanderWirtz** [comment]
:+1:

**Comment by jorisberkhout** [comment]
:blush: I set the both charts to `_always_hidden` because the results they were showing not making sense. Now that everything is working again, I forgot to remove the `always_hidden` tag.

Both charts are showing up in the `Merit order and flexibility` group now.
