### ISSUE TITLE
Flexibility chart color scheme needs improvements

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2029]
The two blues for P2G and storage in EV are indistinguishable to me. Granted, I only have 3 out of 4 possible color cones in my retina.

not deploy critical. Reassign at will.

![image](https://cloud.githubusercontent.com/assets/308563/12883837/b98bab54-ce5a-11e5-9cba-33cae1285a09.png)

**Comment by ChaelKruip** [comment]
> The two blues for P2G and storage in EV are indistinguishable to me.

:+1:

**Comment by jorisberkhout** [comment]
Assigning to @ChaelKruip .

**Comment by ChaelKruip** [comment]
Closed by changing stuff in the admin section.
