### ISSUE TITLE
Is P2G calculation correct? Is the allowed capacity not too low?

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2030]
I am surprised at how little H2 is produced / power is used for making H2. Compare to storage in EV. 

Is this a consequence of the low capacity for P2G allowed by slider max? I suppose so. Perhaps this needs to be more than a mere 74 MW?

![image](https://cloud.githubusercontent.com/assets/308563/12883893/0847dc9a-ce5b-11e5-887c-9e5c6ac215c0.png)

reassign at will notifying @ChaelKruip @RobTerwel @dennisschoenmakers

**Comment by RobTerwel** [comment]
> Is this a consequence of the low capacity for P2G allowed by slider max?

Yes, it is. @jorisberkhout decided to base the P2G plant on the local forecourt electrolysis plant used for transport. While many of their attributes are similar (when scaled), P2G plants typically have larger capacities (at least a few MW). 

A quick fix would involve increasing the capacity and carefully scaling relevant attributes accordingly.

**Comment by AlexanderWirtz** [comment]
I thought we had discussed and decided that these large-scale P2G units would be much bigger than the ones for transport?

**Comment by jorisberkhout** [comment]
I thought we decided to keep them the same as the transport ones for consistency reasons.

The Siemens P2G installations that Albert van der Molen recommended have a capacity of `1.25 MW`, but other specs are hard to find (see [Siemens website](http://www.industry.siemens.com/topics/global/en/pem-electrolyzer/silyzer/silyzer-systems/Pages/silyzer-systeme1105-9496.aspx?tabcardname=silyzer%20200%20basis)). This `1.25 MW` is not much higher than the `0.74 MW` of the transport electrolysers.

I agree that the potential impact of P2G in the ETM is currently low. The easiest fix would be to increase the slider cap. What would be a good cap for this, @AlexanderWirtz .

**Comment by AlexanderWirtz** [comment]
> The Siemens P2G installations that Albert van der Molen recommended have a capacity of 1.25 MW, but other specs are hard to find (see Siemens website). This 1.25 MW is not much higher than the 0.74 MW of the transport electrolysers.

OK, let's do some more research post deploy then. Not critical, as impact is not too high. Still, it is becoming a very important part of public discussions of renewable power, so this will need to be picked up at a later stage.

I truly do not know what a good cap would be, but let's do something crazy like 500 MW or even 800 MW (same as a power plant).

**Comment by jorisberkhout** [comment]
> I truly do not know what a good cap would be, but let's do something crazy like 500 MW or even 800 MW (same as a power plant).

I'll change the slider cap to 1000 then. This means that you can build 740 MW of P2G plants.

> OK, let's do some more research post deploy then. Not critical, as impact is not too high. Still, it is becoming a very important part of public discussions of renewable power, so this will need to be picked up at a later stage.

Agree!

**Comment by jorisberkhout** [comment]
> I'll change the slider cap to 1000 then. This means that you can build 740 MW of P2G plants.

Actually, assigning @RobTerwel to do this.

**Comment by AlexanderWirtz** [comment]
:+1:
