### ISSUE TITLE
Under flexibility options, greyed-out 'Curtailment' barely visible

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2031]
I failed to notice it the first 5 times. I am not your average user (rather blind), but perhaps that makes me a good person to point this out.

![image](https://cloud.githubusercontent.com/assets/308563/12883983/8ce43890-ce5b-11e5-8289-1b4d52592205.png)

reassign at will

**Comment by grdw** [comment]
It has to look 'disabled' or non-draggable. We could make it a little more black-gray instead of white-gray? And maybe change the background color to something light-gray aswell.

**Comment by AlexanderWirtz** [comment]
@grdw I understand that is what we were going for. More contrast need IMO

**Comment by grdw** [comment]
![screen shot 2016-02-08 at 3 02 25 pm](https://cloud.githubusercontent.com/assets/2676542/12887504/1bce95aa-ce75-11e5-9650-f914cdfce092.png)

Something like this?

**Comment by jorisberkhout** [comment]
> Something like this?

I liked the old style better the current style much better than this preview. Could you not just make the grey in the current flexibility options selector a little darker?

**Comment by jorisberkhout** [comment]
Moved to storage milestone.

**Comment by grdw** [comment]
> in the current flexibility options selector a little darker?

@jorisberkhout I agree, it's overdoing it a little.

![screen shot 2016-02-08 at 4 12 10 pm](https://cloud.githubusercontent.com/assets/2676542/12889351/befec61a-ce7e-11e5-8b6a-244c93cefd8b.png)

This is more readable.

**Comment by AlexanderWirtz** [comment]
much better

**Comment by jorisberkhout** [comment]
I like it
