### ISSUE TITLE
The output of the P2H node is not taken into account in the graph 

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2032]
As a result of the flexibility calculation, the P2H node (blue) might get a demand. This demand is, however, not communicated to the red node. Assigning @ChaelKruip to look into this.

<img width="462" alt="screen shot 2016-02-08 at 12 14 35" src="https://cloud.githubusercontent.com/assets/4669028/12884328/c67607b2-ce5d-11e5-933b-2094f48cc314.png">

**Comment by ChaelKruip** [comment]
Currently, the shares to the right of `households_useful_demand_for_hot_water_for_houses_with_p2h` are fixed at 0, 1 for the top and bottom edges respectively. So, even though (after https://github.com/quintel/etsource/pull/1066) the node receives a demand, 100% of that demand flows downwards to the non-p2h hot water options.

I can image two solution directions both of which I am not sure will work:
* Create an input statement which updates the shares to match the demand of `households_flexibility_p2h_electricity` (set by Merit) and the demand of `households_useful_demand_for_hot_water_for_houses_with_p2h`. Merit should somehow 'trigger' this input statement I imagine.
* Have ETE/Merit update the shares described above directly (i.e., without an update statement in AD-format). 

@antw do you have any ideas on the feasibility of these two options? Or do you see another way of doing this?
