### ISSUE TITLE
Persistency for storage options not working?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2034]
When I go to [flexibility] and I change the order of the technologies, hit command-R I get the original order back as if nothing was changed.

**Comment by dennisschoenmakers** [comment]
including @grdw

**Comment by dennisschoenmakers** [comment]
including @AlexanderWirtz

**Comment by grdw** [comment]
Is it still this way? There were some changes made in the past hour or so.

**Comment by jorisberkhout** [comment]
> Is it still this way?

Could you do some testing to see if this is solved, @grdw ?

**Comment by grdw** [comment]
Yes. I checked in Firefox/Chrome - and it seems to be functional :+1:

**Comment by grdw** [comment]
IE9 is still unstable though - it sometimes works and it sometimes doesn't ... :cry:

**Comment by jorisberkhout** [comment]
I tested it on Chrome and noticed that the first time you refresh (by hitting cmd-R), the default order is restored. When you change the order again and hit cmd-R, the new order remains. Could you see if you can improve this behaviour, @grdw ?

**Comment by grdw** [comment]
>  Could you see if you can improve this behaviour, @grdw ?

You mean, you see the original order in flash and than it orders to the order you 'set' or?

**Comment by jorisberkhout** [comment]
> You mean, you see the original order in a flash and than it orders to the order you have 'set' or?

No, it returns to the default order after you hit cmd-R and stays there. This does, however, only happen one time after you create a new scenario.

**Comment by grdw** [comment]
> No, it returns to the default order after you hit cmd-R and stays there. This does, however, only happen one time after you create a new scenario.

I know why ... moment please.

**Comment by grdw** [comment]
See relevant comment: https://github.com/quintel/etmodel/issues/2018#issuecomment-180313893

**Comment by dennisschoenmakers** [comment]
Works like a charme now here.
