### ISSUE TITLE
Population and residences table (145) won't show if MO is off.

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2041]
![screen shot 2016-02-09 at 09 06 52](https://cloud.githubusercontent.com/assets/14106387/12910650/b7d0ba5e-cf0c-11e5-94a4-98f2ed4df11a.png)

Probably not intentional, observed in a clean NL 2050 scenario. HTML table no. 145.

Re-assign at will.

**Comment by jorisberkhout** [comment]
Assigning @grdw .

**Comment by grdw** [comment]
Fixed by: https://github.com/quintel/etmodel/commit/7c6fb70d09585ddf016bb2de708cdaceeb36cd1c
