### ISSUE TITLE
Video in sliders info text not found

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2042]
## Relevant sliders

- demand - households - district heating - geothermal
- demand - industry - other - demand growth - heat

![screen shot 2016-02-09 at 09 20 49](https://cloud.githubusercontent.com/assets/14106387/12910855/6f518180-cf0e-11e5-9fc4-b9c29e024bdf.png)

![screen shot 2016-02-09 at 09 52 03](https://cloud.githubusercontent.com/assets/14106387/12911454/f8cb0856-cf12-11e5-92a1-486660b0b4f1.png)

For the previous deploy, we deleted the videos that weren't found: https://github.com/quintel/etmodel/issues/1905 . Shall we also delete this one?

Re-assign at will. You can assign me if you agree with my suggestion. :smile:

**Comment by jorisberkhout** [comment]
Assigning @grdw .

**Comment by grdw** [comment]
![screen shot 2016-02-09 at 12 22 19 pm](https://cloud.githubusercontent.com/assets/2676542/12914951/c7ef7b26-cf27-11e5-8894-d1e7db0de397.png)

You can edit it directly in the admin panel :smile: 
But I'll change it.
