### ISSUE TITLE
Should we move the P2H water heater slider to Flexibility options

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2043]
This issue is not deploy critical, but a big nice to have for me. 

In retrospect I am not very happy with the choice to put the `households_flexibility_p2h_electricity_market_penetration` slider in the HH hot_water slide for the following reasons:

1. This slider does precisely nothing until the user has made some choices under 'Flexibility options'. This is confusing and counter-intuitive to the user. Add this slider to the 'Conversion to heat' slide and adjusting it will actually have a discernible impact.
2. Until the user has made choices in the 'Flexibility options' section, the user may have no idea what `P2H` actually means. Same as point 1.
3. All other sliders relevant for Flexibility options are set in that section, so why not this one? `households_flexibility_p2p_electricity_market_penetration` is also not found in the Households section, for example.

Reassign at will. Notifying @dennisschoenmakers (who agrees) @ChaelKruip @RobTerwel

**Comment by RobTerwel** [comment]
I agree with all points, @AlexanderWirtz .

**Comment by jorisberkhout** [comment]
John agrees on moving the slider to the 'Power to heat' slide and so do I. I will move it and rephrase the texts.

**Comment by jorisberkhout** [comment]
Done. Closing.
