### ISSUE TITLE
Flexibility chart horizontal axis disappears and animates between 0 and infinity?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2047]
When you start a new scenario for NL and pull a slider in Flexability:

![feb 09 2016 12 03](https://cloud.githubusercontent.com/assets/104830/12914549/29270ad8-cf25-11e5-841f-f68bbcb8b692.gif)

![feb 09 2016 12 05](https://cloud.githubusercontent.com/assets/104830/12914609/8c5dc150-cf25-11e5-883a-f878cb21a30b.gif)

**Comment by jorisberkhout** [comment]
Assigning @grdw to look into this.

**Comment by grdw** [comment]
I can confirm this but I'm having a hard time finding where this happens in the code. My guess is that this has something to do with D3 rendering. It's a bit hard to find because the elements get removed from the dom after they animate away... :sweat_smile:

**Comment by dennisschoenmakers** [comment]
Also I note there is a fundamental difference between for example the [supply chart](http://beta.pro.et-model.com/scenario/supply/electricity/coal-plants) and the new [flexability charts](http://beta.pro.et-model.com/scenario/flexibility/electricity_storage/storage-in-batteries). The latter gets **redrawn** with every slider move, which is super annoying. The former animated between the old state and the new state, which gives you a *much* better indication of the impact of a slider.

**Comment by grdw** [comment]
Nevermind, I know where this comes from. :sweat_smile: Moment please.

**Comment by grdw** [comment]
@dennisschoenmakers Right know it does happen the first time though but not when you drag a slider.
