### ISSUE TITLE
Import/Export dashboard chart: should heat be there and should we include H2?

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2049]
![screen shot 2016-02-09 at 14 53 49](https://cloud.githubusercontent.com/assets/14106387/12918080/5b9974de-cf3d-11e5-843c-7261f3053cb4.png)

In the `net foreign imports` dashboard chart we currently display various carriers including `heat`. Since we do not have an `energy_export_heat` node anymore, is there still a reason for it to be included here?

Secondly, as discussed in https://github.com/quintel/etengine/issues/822 and https://github.com/quintel/etmodel/issues/1966 , we will now use the hydrogen produced through P2G in transport and export hydrogen when it exceeds demand. Should we then include hydrogen in this chart?

@jorisberkhout @AlexanderWirtz @ChaelKruip @dennisschoenmakers , what do you think?

**Comment by ChaelKruip** [comment]
> what do you think?

I think heat is not used for import or export so I'd be open to replacing it with hydrogen in this chart.

**Comment by jorisberkhout** [comment]
> I think heat is not used for import or export so I'd be open to replacing it with hydrogen in this chart.

Agree, could you implement this, @RobTerwel ?

**Comment by RobTerwel** [comment]
> Agree, could you implement this, @RobTerwel ?

I'm on it!
