### ISSUE TITLE
Charts look 'broken' when they're empty

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2051]
![screen shot 2016-02-09 at 3 50 15 pm](https://cloud.githubusercontent.com/assets/2676542/12919567/fd9f3c30-cf44-11e5-94e6-0fe973a559ca.png)

I think it would be more clear for users if there's an explanation why there's nothing here and display a 0 at the y-axis. 

@jorisberkhout should I assign myself? :angel:

**Comment by jorisberkhout** [comment]
> @jorisberkhout should I assign myself? :angel:

Yes, good idea!

**Comment by grdw** [comment]
I have an idea for implementing this which is really nice. I'll try to explain:

the `D3ChartView` receives two extra methods:

````coffeescript
class D3ChartView extends BaseChartView
  ...
  render: (force_redraw) =>
    ...
    @displayEmptyMessage()

  isEmpty: ->
    false

  displayEmptyMessage: ->
    if @isEmpty()
      # append some div-like element to the chart with a message
````

Than each subclass will be able to overwrite the `isEmpty()` method with their own implementation considering that there are probably multiple data-structures, values and attributes to validate before you can safely specify that a certain chart is considered to be empty.

**Comment by grdw** [comment]
<img width="610" alt="screen shot 2016-09-09 at 15 23 33" src="https://cloud.githubusercontent.com/assets/2676542/18388309/693c62d4-76a1-11e6-8547-5efb3c5065d9.png">

I'm not sure about the message in the chart, if someone could maybe suggest something better. Also I'm open for opinions. 

When I come to think of it, when the chart is empty, why do we display the legend? It's a bit confusing. Also, we could remove the weird black line on the right side of the screen. What I'm sort of pointing towards is -- if the chart is empty, just display the message (in a bigger box) and leave it at that. Why render and calculate more things if the initial calculation returns 0?

**Comment by ChaelKruip** [comment]
> When I come to think of it, when the chart is empty, why do we display the legend? It's a bit confusing. Also, we could remove the weird black line on the right side of the screen. What I'm sort of pointing towards is -- if the chart is empty, just display the message (in a bigger box) and leave it at that. Why render and calculate more things if the initial calculation is 0?

I like that.

**Comment by grdw** [comment]
So, really really really minimal looking it would be:

<img width="620" alt="screen shot 2016-09-09 at 15 57 02" src="https://cloud.githubusercontent.com/assets/2676542/18389397/129979bc-76a6-11e6-8203-f80e2757a991.png">

**Comment by grdw** [comment]
Little bit fancier:
<img width="619" alt="screen shot 2016-09-09 at 15 59 46" src="https://cloud.githubusercontent.com/assets/2676542/18389495/7a30cee0-76a6-11e6-90d9-3c5e72e69a8b.png">

**Comment by grdw** [comment]
We could even go as far as to disable the table-view button but I think that would be a little to much.

**Comment by grdw** [comment]
I need a text that can be displayed in the center of the chart. In Dutch and English. I now added a text which seems rather obvious maybe there is some better physical way to describe an empty looking chart?

I also want to say that this fix will only work for the `stacked_bar` type chart. It doesn't work for any of the other types yet.

**Comment by ChaelKruip** [comment]
>  I now added a text which seems rather obvious maybe there is some better physical way to describe an empty looking chart?

As a generic default message I would say something like:

"There is no data available for this chart"/"Er is geen data beschikbaar voor deze grafiek"

It would be good to inform the user of the reason why there is no data and what can be done to change that but that's chart-dependent. Can your implementation deal with custom texts?

**Comment by grdw** [comment]
>  Can your implementation deal with custom texts?

It could, yes.

**Comment by grdw** [comment]
![screen shot 2016-09-12 at 14 12 17](https://cloud.githubusercontent.com/assets/2676542/18435370/f331fb72-78f2-11e6-9e43-7b22cd11e34e.png)

*List of charts that can be empty:*

- 61 - Required additional infrastructure investments

**Comment by grdw** [comment]
I'm currently thinking to leave the PR right now as is. If there are more charts that can become empty I'll change that in the future. Also do you have an idea what you want as a custom text for a chart? 

In place of the question mark?

![screen shot 2016-09-13 at 11 02 59](https://cloud.githubusercontent.com/assets/2676542/18467896/f437b00c-79a1-11e6-950e-9578a8ba57fa.png)

Also is this what you would expect a "custom text" would look like.

**Comment by jorisberkhout** [comment]
I prefer the generic message to read: `There is no data to display for this chart` and `Er is geen data om te tonen voor deze grafiek`. The current text reads like something went wrong and no data is available.

As discussed with @grdw , he will provide me with a list of all charts that need a custom message and I will provide these messages.

**Comment by grdw** [comment]
As stated before this implementation now only works for `stacked_bar` type charts. The 2 charts that can be empty now are:

`hydrogen_production`
`use_of_excess_electricity`

**Comment by jorisberkhout** [comment]
I would suggest the following texts:
- `hydrogen_production`
  - `There is no demand for hydrogen for transport`
  - `Er is geen vraag naar waterstof voor transport`
- `use_of_excess_electricity`
  - `There is no excess electricity in your scenario`
  - `Er zijn geen elektriciteitsoverschotten in je scenario`

Would you be so kind to implement these texts, @grdw ?

**Comment by grdw** [comment]
I found another which can become empty if you add enough wind power:

`additional_infrastructure_investments`

**Comment by grdw** [comment]
It looks like this:

![screen shot 2016-09-13 at 13 52 18](https://cloud.githubusercontent.com/assets/2676542/18472713/4f6191ac-79b9-11e6-828f-3e5b559891c3.png)

**Comment by jorisberkhout** [comment]
> I found another which can become empty if you add enough wind power:
>
> `additional_infrastructure_investments`

I think we should leave that chart the way it is. Even when it is showing that all additional investment costs are zero, that information is quite useful.

**Comment by jorisberkhout** [comment]
BTW, I like what it looks like now!
