### ISSUE TITLE
When I build more batteries, I can store LESS(!) excess electricity?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2053]
I don't get this one:

## 0% batteries: total of 113.8 PJ of excess electricity stored

![image](https://cloud.githubusercontent.com/assets/104830/12919949/b3bd9b1e-cf46-11e5-93bd-d94965180773.png)

## 100% batteries: total of 88.8 PJ of excess electricity stored

![image](https://cloud.githubusercontent.com/assets/104830/12919955/bd55f176-cf46-11e5-9396-af6d03082437.png)

**Comment by ChaelKruip** [comment]
@dennisschoenmakers In your examples, the main contributing categories are Export and Curtailment :smile: 

In your first example, 0 PJ is stored, in the second, 1.6247 PJ.

**Comment by ChaelKruip** [comment]
I agree, however, that you would expect the total to be the same!

**Comment by dennisschoenmakers** [comment]
> I agree, however, that you would expect the total to be the same!

In the other slides, they do (more or less)

**Comment by ChaelKruip** [comment]
Closing this issue as it is superseded by https://github.com/quintel/etmodel/issues/2070
