### ISSUE TITLE
BR buildings has max intelligent control light sliders while having 0 final demand for light

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2055]
![screen shot 2016-02-10 at 09 28 58](https://cloud.githubusercontent.com/assets/14106387/12942149/f669c0ea-cfd8-11e5-9860-933e1ad32519.png)

I confirmed with the EB that the buildings section has 0 PJ final demand for light. However, the way the lighting shares are defined now this actually sets the intelligent control sliders at their max. value. This is somewhat counterintuitive and I suggest we try to make these sliders start are at 0% of their potential (in the present).

**Comment by jorisberkhout** [comment]
Well spotted and I agree with you conclusions, @RobTerwel . As it's not broken, let's pick this up after the deploy.

**Comment by jorisberkhout** [comment]
> However, the way the lighting shares are defined now this actually sets the intelligent control sliders at their max. value.

I agree wth this. In other words, if a node has two shares of which one is `share` and the other `flexible` and no energy flows through that node the `share` is set to `100 %` and the flexible to `0 %`. It feels to me like we shouldn't want to change this or make an exception just to solve this issue.

I think the better solution would be to have a look the amount of electricity for lighting in buildings. You can actually set this in the buildings analysis, where it is now set to `0 PJ`.

Re-assigning @thaisclv to pick this up if she has time.
