### ISSUE TITLE
LOLE dashboard item should take electricity from P2P into account (if available)

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2057]
Before we included P2P (batteries and EV) in the ETM, the loss of load expectation (LOLE) was more of a statistical property. The LOLE calculation, of which the result is shown as a dashboard item, would:

1. Take the demand profile, scaled by the actual electricity demand
2. Subtract any electricity production by wind turbines, solar panels and hydro river from it (if available)
3. Compare the remaining electricity demand with the available dispatchable electricity capacity production and count the hours in which this capacity cannot meet the electricity demand

P2P could lower the LOLE by supplying (some of) its stored electricity back to the grid. It does, however, act differently from a dispatchable electricity, because it might not always be charged when you need its electricity to lower the LOLE. Merit does calculate the amount of electricity stored in the battery at every hour of the year, but including it in the LOLE calculation is a little trickier. I suggest to pick this up after the February deploy.

**Comment by ChaelKruip** [comment]
> but including it in the LOLE calculation is a little trickier

I see the following complication:

Merit currently calculates a production (positive part of the load) curve for P2P *if* Merit is enabled. In this case, the production curve could be subtracted from the demand as with wind, solar etc. to yield the residual demand curve which needs to be compared to the dispatchable capacity at each point.
The current LOLE calculation does not require a full run of Merit, however, so including the effects of P2P   would still depend on whether Merit is 'on'.

@antw @dennisschoenmakers any ideas of how to ga about this?

**Comment by dennisschoenmakers** [comment]
Could we say: "the LOLE calculation is more accurate with respect to P2P when Merit is turned on"?

**Comment by ChaelKruip** [comment]
> Could we say: "the LOLE calculation is more accurate with respect to P2P when Merit is turned on"?

That would be misleading. Currently, the Merit module does not use the effects of P2P on the LOLE whether is is 'on' or 'off'.

**Comment by dennisschoenmakers** [comment]
> That would be misleading. Currently, the Merit module does not use the effects of P2P on the LOLE whether is is 'on' or 'off'.

:grinning: Well, not now: I was talking about that hypothetical situation.

**Comment by jorisberkhout** [comment]
@dennisschoenmakers and I discussed the following solution to this issue: 

- Leave the LOLE dashboard item and the underlying calculation the way it is; that way the LOLE dashboard item represents a statistical measure for the number of hours per year that the national electricity park cannot meet the national demand. This is **not** equivalent to the number of blackout hours per year, as these "LOLE" hours could be mitigated by importing electricity or making clever use of the electricity stored in batteries.
- Add a new dashboard item called "blackout hours" (or similar). This dashboard item will only be available when merit is *on* and takes into account the full results of merit including the electricity stored in batteries (see https://github.com/quintel/etmodel/issues/2058)

This solution has the following advantages:

- Both dashboard items (LOLE and blackout) are well defined and represent different approaches to the issue of supply being able to meet demand (statistical versus calculated on an hourly basis respectively)
- When merit is *off* we show the LOLE dashboard item, which does not require a full run of merit

What do you think of this solution, @AlexanderWirtz , @ChaelKruip and @antw ?

**Comment by AlexanderWirtz** [comment]
I like the general idea. It would require merit to do something it currently does not: register the generation 'shortfall' per hour, as well as the actual import capacity used each hour.

The latter would be a useful addition, as it is a step on the way to giving import capacity a 'virtual plant' status with assigned marginal costs according to an imported .csv time curve from a scenario for a neighboring country. Once we do that we can let the import capacity compete in a national market.

I do not think `import` is an available option yet in merit, is it?

**Comment by dennisschoenmakers** [comment]
@jorisberkhout: we also discussed the addition of an extra node in the graph that will represent the shortfall of electricity that cannot be produced nor imported. Perhaps it is also good to elaborate a bit on this idea here? or do we have another Issue for that somewhere else? 😄

**Comment by jorisberkhout** [comment]
> or do we have another Issue for that somewhere else? 😄

Yes, it is described in https://github.com/quintel/merit/issues/139. Implementing it as we speak 😄

**Comment by jorisberkhout** [comment]
I'll close this issue; the actionable part regarding a new dashboard item displaying blackout hours is described in https://github.com/quintel/etmodel/issues/2058.
