### ISSUE TITLE
Add a dashboard item to show the number of blackout hours

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2058]
As discussed in https://github.com/quintel/merit/issues/133#issuecomment-181413019, limiting the import capacity, could result in a situation where there is simply not enough electricity in the graph to meet the demand. In real life this would result in blackouts. I think this is very valuable information to communicate to the user, as it is much easier to understand blackouts than LOLE (see a.o. https://github.com/quintel/etmodel/issues/2057).

For now, we have decided not to limit the interconnector capacity for import as we don't fully understand the technical implications of limiting it to the graph yet. This means that currently you can always import any missing electricity. @antw did however create the functionality to limit the interconnector capacity for import, so we could pick this up to create a dashboard item showing blackouts.

I think this is not part of the deploy, but I'm putting it out there to hear your opinion on the usefulness of ad dashboard item displaying blackouts, @AlexanderWirtz , @dennisschoenmakers , @ChaelKruip , @antw and @RobTerwel .

**Comment by ChaelKruip** [comment]
I like it!

**Comment by dennisschoenmakers** [comment]
Very good idea!

**Comment by jorisberkhout** [comment]
As discussed in https://github.com/quintel/etmodel/issues/2057 and with @dennisschoenmakers and @ChaelKruip , I think we should do this. Determining the number of blackout hours from a merit order run should be relatively straightforward once we have restricted import. The latter is discussed in https://github.com/quintel/merit/issues/139, where I will describe a potential solution to that issue.

**Comment by jorisberkhout** [comment]
Assigning @grdw to create this dashboard item once https://github.com/quintel/merit/issues/144 is implemented. This dashboard item is very similar to the Loss of load expectation dashboard item and should have the following properties:

- It needs to be part of the `Energy imports` group in the dashboard item selector
- It needs to be called `Blackout hours` in English and `Stroomuitval` in Dutch
- Its units are `h/yr` in English and `u/jr` in Dutch
- When you click on this dashboard item it should show the `Merit order hourly supply` chart

**Comment by antw** [comment]
I made a couple of small tweaks (such as adding import to the load chart) and deployed this to beta:

<img width="230" alt="screen shot 2016-07-05 at 11 22 20" src="https://cloud.githubusercontent.com/assets/4383/16581691/d99a3c6e-42a2-11e6-81b0-1fffe46b61d5.png">

<img width="764" alt="screen shot 2016-07-05 at 11 22 34" src="https://cloud.githubusercontent.com/assets/4383/16581695/dcbe5524-42a2-11e6-82fa-e17f90d9cd76.png">

**Comment by ChaelKruip** [comment]
> (such as adding import to the load chart)

I don't see it in the above figure though... Am I missing something?

**Comment by antw** [comment]
It's the top-most grey series (the legend isn't visible without scrolling down).

<img width="332" alt="screen shot 2016-07-05 at 11 30 08" src="https://cloud.githubusercontent.com/assets/4383/16581916/d7edd370-42a3-11e6-95cc-18d858ade9df.png">

**Comment by ChaelKruip** [comment]
> It's the top-most grey series (the legend isn't visible without scrolling down).

Thanks! 👍
