### ISSUE TITLE
Having changed dashboard items, scaling a scenario gives back the original items 

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2060]
If you change which dashboard items are displayed and scale that scenario, the original dashboard items are displayed again (clean NL 2013 scenario).

Dashboard, pre-scaling
![screen shot 2016-02-10 at 11 48 33](https://cloud.githubusercontent.com/assets/14106387/12945230/599acc78-cfec-11e5-81da-b4de937ca4a7.png)

Dashboard post-scaling
![screen shot 2016-02-10 at 11 49 01](https://cloud.githubusercontent.com/assets/14106387/12945236/63026d0c-cfec-11e5-8795-bb6c1e4aa9fe.png)

Probably dashboard item settings are not saved/cached.

Re-assign at will.

**Comment by jorisberkhout** [comment]
@antw , any idea why this is happening?

**Comment by antw** [comment]
> @antw , any idea why this is happening?

It happens whenever you start a new scenario. Scaling works by creating a new scenario, copied from your current one, and scaling it.

I think the fix should be to preserve the user's choice of dashboard items whenever you start *any* new scenario, not just a scaled one. Would that be acceptable?
