### ISSUE TITLE
When scaling a scenario and excluding sectors, associated charts should not be available

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2061]
After scaling a clean NL 2013 scenario and excluding certain sectors, it is still possible to select charts about those sectors. 

For instance, when excluding the industry sector in scaling, it shouldn't be possible to afterwards display industry related charts since they should be void:![screen shot 2016-02-10 at 11 51 28](https://cloud.githubusercontent.com/assets/14106387/12945293/d577d9d0-cfec-11e5-8eb5-87395db166f5.png)

I suggest that we make an inventory of which charts should show and should not show depending on whether
- [ ] excludes the agriculture sector
- [ ] excludes the industry sector
- [ ] excludes the energy sector

Re-assign at will.

**Comment by jorisberkhout** [comment]
Assigning @antw . Not deploy critical, so removing the milestone.

**Comment by michieldenhaan** [comment]
Closing, scaling option has been removed.
