### ISSUE TITLE
Climate slider max_value and step_size should not scale with scenario

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2062]
After scaling a clean 2013 NL scenario to 10000 inhabitants, I see the following:

![screen shot 2016-02-10 at 11 57 36](https://cloud.githubusercontent.com/assets/14106387/12945423/8ef9f122-cfed-11e5-8176-f48d8a708f99.png)

The climate slider now has a 0.0001 `step_size` and `max_value` of 0.0067 degrees Celsius. This slider's range and `step_size` shouldn't scale with the scenario.

Re-assign at will.

**Comment by jorisberkhout** [comment]
Assigning @antw .

**Comment by RobTerwel** [comment]
@jorisberkhout  and @antw , same holds true for the P2G slider:

![screen shot 2016-02-10 at 12 17 52](https://cloud.githubusercontent.com/assets/14106387/12945843/77347852-cff0-11e5-9b27-ba922c6bc9be.png)
