### ISSUE TITLE
Domestic aviation UD slider absent in a scaled scenario while DA efficiency slider is present

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2063]
As noted by @dennisschoenmakers in https://github.com/quintel/etmodel/issues/2009 as well, the domestic aviation UD slider does not appear in a scaled scenario.

![screen shot 2016-02-10 at 12 05 33](https://cloud.githubusercontent.com/assets/14106387/12945600/dc6186a4-cfee-11e5-925c-6fa165a945e9.png)

The efficiency slider, however, is present:

![screen shot 2016-02-10 at 12 05 41](https://cloud.githubusercontent.com/assets/14106387/12945608/e8b6bf96-cfee-11e5-8560-408392ce851d.png)

I see two options: making the domestic aviation UD slider appear, or removing the domestic aviation efficiency improvement slider.

Re-assign at will.

**Comment by jorisberkhout** [comment]
Let's pick this up after the deploy. See also https://github.com/quintel/etmodel/issues/2064.

**Comment by jorisberkhout** [comment]
Assigning @ChaelKruip as he knows more about scaling. Re-assign if you want me to pick this up.

**Comment by michieldenhaan** [comment]
Closing, scaling option has been removed.
