### ISSUE TITLE
Scaling a scenario without energy sector should not show associated sidebar items and slides

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2064]
Related to https://github.com/quintel/etmodel/issues/2061, if one scales a clean NL 2013 scenario and _excludes_ the energy sector, supply and cost sidebar items of that sector still appear. In addition, sliders all do too, but they are scaled and set to zero. However, since the sector itself has been removed, these sliders don't have any effect:

![screen shot 2016-02-10 at 13 27 33](https://cloud.githubusercontent.com/assets/14106387/12947267/72cd70f2-cffa-11e5-851b-0ab414c1a68e.png)

I suggest that we make an inventory of which slides should show and should not show depending on whether
- [ ] excludes the agriculture sector
- [ ] excludes the industry sector
- [ ] excludes the energy sector

Re-assign at will.

**Comment by jorisberkhout** [comment]
Thanks for this, @RobTerwel . It agree with your suggestion to make an inventory of which sidebar items, slides, sliders and chart do not need to be shown for a scaled scenario. This includes the ones you mentioned in https://github.com/quintel/etmodel/issues/2063 and https://github.com/quintel/etmodel/issues/2061. Let's do this after the deploy.

**Comment by jorisberkhout** [comment]
Assigning @ChaelKruip as he knows more about scaling. Re-assign if you want me to pick this up.

**Comment by michieldenhaan** [comment]
Closing, scaling option has been removed.
