### ISSUE TITLE
There should be more space underneath the 'Flexibility options' table

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2066]
If I add a table underneath the `Flexibility options` table, there is no space between the bottom of the table and the header of the next chart.

<img width="615" alt="screen shot 2016-02-10 at 14 06 55" src="https://cloud.githubusercontent.com/assets/4669028/12948036/d2a577f4-cfff-11e5-876d-a0fe9e7fdb5c.png">

**Comment by grdw** [comment]
Has this something to do with resolution?

This is on a 'wide' screen:

![screen shot 2016-02-10 at 2 14 49 pm](https://cloud.githubusercontent.com/assets/2676542/12948174/afa3fe5a-d000-11e5-9e4c-56b8e0714f1c.png)

This is when I make it smaller:

![screen shot 2016-02-10 at 2 14 55 pm](https://cloud.githubusercontent.com/assets/2676542/12948175/afc3f976-d000-11e5-8b98-a3f24e309c84.png)

**Comment by jorisberkhout** [comment]
I think it has to do with the custom HTML tables, because I now see the same for e.g. the Investment table. If the custom table becomes larger than a specific size, there is no space between the top and bottom chart. Not deploy critical, let's pick this up as part of https://github.com/quintel/etmodel/issues/2015.

**Comment by jorisberkhout** [comment]
Linked to https://github.com/quintel/etmodel/issues/2015.

**Comment by jorisberkhout** [comment]
Adding to `merit order charts` milestone.

**Comment by grdw** [comment]
<img width="657" alt="screen shot 2016-06-28 at 13 50 03" src="https://cloud.githubusercontent.com/assets/2676542/16414312/3dcc3046-3d37-11e6-8e45-3d5d1a3e76db.png">

Like this, or does it need to be the same space between the header and the start of the table?

**Comment by grdw** [comment]
<img width="614" alt="screen shot 2016-06-28 at 13 52 11" src="https://cloud.githubusercontent.com/assets/2676542/16414371/8a02ced4-3d37-11e6-903f-c673fc29ba99.png">

Like this, so 10px, the above example is using 20px

**Comment by jorisberkhout** [comment]
I like the 10px better as it more closely resembles the case when you display two charts on top of each other.

<img width="615" alt="screen shot 2016-06-28 at 14 00 36" src="https://cloud.githubusercontent.com/assets/4669028/16414599/d39cfffa-3d38-11e6-9d8d-dd96ff5e6948.png">
