### ISSUE TITLE
Targets, once set, cannot be removed (not by resetting slider)

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2067]
Once you've set targets, you cannot remove them. Resetting the target sliders will simply change the target to its `start_value`, not remove the target _itself_.

![screen shot 2016-02-10 at 14 06 27](https://cloud.githubusercontent.com/assets/14106387/12948016/c1f9eef8-cfff-11e5-9582-46dbc2a49849.png)

The target sliders in the rectangular red box have been reset and are now seen as targets that have been met.

Re-assign at will.

**Comment by jorisberkhout** [comment]
Removed milestone.

**Comment by jorisberkhout** [comment]
Assigning @antw . Low priority.

**Comment by marliekeverweij** [comment]
Targets interface is not shown anymore and will be removed: see https://github.com/quintel/etmodel/issues/3027
