### ISSUE TITLE
Total costs of electricity production chart remembers ticked boxes too well

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2068]
When selecting which plants are displayed in the total costs of electricity production chart in a NL scenario (MO:on) ánd logged in as a user, the chart remembers which boxes you've ticked in such a way that resetting your scenario or starting a new does does not show you the boxes that were selected in a clean scenario.

To make this a bit more concrete, I made sure I only saw one nuclear power plant:

![screen shot 2016-02-10 at 14 27 14](https://cloud.githubusercontent.com/assets/14106387/12948583/35be44ee-d003-11e5-95de-0fc6fbbb43df.png)

But when I reset my scenario or start a new one (regardless which dataset or yeaer) and add this chart again, I see the exact same nuclear plant I saw before resetting (i.e. the image above) _exclusively_.

Re-assign at will.

**Comment by jorisberkhout** [comment]
Not critical for deploy.

**Comment by jorisberkhout** [comment]
Assigning @grdw. Low priority.

**Comment by ChaelKruip** [comment]
Too much work for little payoff. Closing.
