### ISSUE TITLE
Scaling page (/scaled) should receive Dutch translations

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2069]
![screen shot 2016-02-10 at 15 21 19](https://cloud.githubusercontent.com/assets/14106387/12949853/7cec5912-d00a-11e5-8d7c-65265c0dce46.png)

And the `show graph` option in settings as well.

Re-assign at will.

**Comment by jorisberkhout** [comment]
Good point, not deploy critical.

**Comment by jorisberkhout** [comment]
I would be happy to this, if someone could point out to me where I can add / change these translations. Do you know, @antw or @grdw ?

**Comment by grdw** [comment]
The texts are [here](https://github.com/quintel/etmodel/blob/master/app/views/pages/scaled.html.haml) and [here](https://github.com/quintel/etmodel/blob/master/app/views/pages/_scaled_common.html.haml). I see that some texts are still statically set and others are in the translations files. One moment while I try to find them or would this be enough information?

**Comment by antw** [comment]
The scaled scenario translations [are here](https://github.com/quintel/etmodel/blob/bdd700dc220f3bb3f6a3b70846d26c6a7ae74586/config/locales/nl_etm.yml#L115-L120).

The NL "Show graph" translation is missing. It needs to be added to [the nl_etm.yml file, under the `header` section](https://github.com/quintel/etmodel/blob/bdd700dc220f3bb3f6a3b70846d26c6a7ae74586/config/locales/nl_etm.yml#L60).

```
show_graph: "Words"
```

**Comment by grdw** [comment]
> Edit: @grdw beat me to it. :grinning:

I removed mine. It just pointed out in which views to look. I'm guessing your comment makes a bit more sense.

**Comment by jorisberkhout** [comment]
Thanks guys!
