### ISSUE TITLE
Excess electricity should be conserved independent of the storage options selected

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2070]
Starting with a new scenario for NL 2050 and creating excess due to wind turbines (on-shore to 25,499) the flex-charts look as follows:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/12950936/1598f972-d010-11e5-95d5-59ccd92b8d31.png)
All excess is exported and curtailed.

Increasing the storage in batteries (to 100%) changes the picture:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/12950987/67c59cb4-d010-11e5-9c7b-a640bb138f7e.png)

The total excess increases from 267 PJ to 283 PJ.

@antw is the total excess not defined as the mismatch between the demand and the volatile+must-run production? Why would it change if storage options are introduced?

**Comment by antw** [comment]
> @antw is the total excess not defined as the mismatch between the demand and the volatile+must-run production?

It should be, yes. I'll take a look into this (and the Gqueries) and see what's going on.

**Comment by jorisberkhout** [comment]
I checked if this has to do with the accounting of the losses in the conversion and storage technologies by locally making them all lossless, both for charging and discharging. This did not solve the issue, but made it smaller.

**Comment by antw** [comment]
> I checked if this has to do with the accounting of the losses in the conversion and storage technologies by locally making them all lossless, both for charging and discharging. 

I have fixed some queries locally to prevent double-counting P2P losses (I'll push them shortly) which has gone a long way toward solving the problem but there is still a small difference in my local scenario (~0.3%) between 0% batteries and 100% batteries.

**Comment by jorisberkhout** [comment]
@ChaelKruip just had a rather brilliant idea. If you store and/or convert more energy locally, less electricity flows through the HV-net converter to export and curtailment, resulting in lower losses on the HV-net, thus increasing the amount of excess electricity. Could that be the answer to the remaining 0.3% difference?

**Comment by antw** [comment]
Interestingly, in my scenario, increasing batteries to 100% reduces the amount of excess electricity by ~1PJ, which is almost the exact same amount by which HV network losses decrease.

I'll push the updated queries, but I'm still tracking down two other (likely unrelated) issues.
