### ISSUE TITLE
Destroying all households does not result in 0 useful demand for households 

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2071]
![screen shot 2016-02-10 at 16 09 42](https://cloud.githubusercontent.com/assets/14106387/12951139/250817ac-d011-11e5-967f-49db876c05ea.png)

0 households should mean 0 useful demand for households, but that's not the case. This is probably an indication that `lighting`, `applicances`, `hot water` and `cooking` demand don't scale  *at all* with the `number_of_residences`.

Re-assign at will.

**Comment by ChaelKruip** [comment]
> This is probably an indication that lighting, applicances, hot water and cooking demand don't scale at all with the number_of_residences.

True. They scale with the population. This is a feature, not a bug :smile:

**Comment by RobTerwel** [comment]
> They scale with the population. 

Ah, I see! That explains. :smile: 

However, wouldn't it then be a good idea to develop a relation between `number_of_residences` and `number_of_inhabitants`? Because not only does it not make sense to have no houses but still 17 million people, but also does it lead to even more confusing situations like this one.
