### ISSUE TITLE
Electricity production chart (99) should also display imported electricity

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2073]
![screen shot 2016-02-11 at 12 15 41](https://cloud.githubusercontent.com/assets/14106387/12975104/5d06f45e-d0b9-11e5-94a9-f3222ede1622.png)

The electricity production chart displays electricity demand, but does not display imports. The latter are very relevant, however, in scenario's with a significant volatile electricity production.

Re-assign at will.

**Comment by jorisberkhout** [comment]
I agree with @RobTerwel that it is odd that electricity import is missing from this chart. 

Adding this to the "lole calculation update" milestone as the issues in that milestone determine how we are going to deal with the import. I propose to wait with fixing this issue until we have solved the other issue in this milestone.
