### ISSUE TITLE
What do 'Load data' and 'Price data' buttons mean on 'Merit order' page? 

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2075]
I think I know, but these buttons are included without any explanation. Actually I do not know what `Load data` is for. What are we loading?

![image](https://cloud.githubusercontent.com/assets/308563/13216408/daa9e8e4-d95b-11e5-82c5-b27ea14a9d75.png)

I realise I am being difficult. Assigning to @ChaelKruip

**Comment by jorisberkhout** [comment]
I have updated the text above these download buttons to make clear what they mean. Closing this issue. Re-open if you feel that more explanation is needed.
