### ISSUE TITLE
Merit order prices should not contain 'infinity'

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2076]
Downloading prices with standard scenario gives a CSV containing "infinity" on most lines:

![price_282810_csv](https://cloud.githubusercontent.com/assets/1303760/13321554/faa4aef6-dbcf-11e5-8022-696729a78976.png)

**Comment by grdw** [comment]
Looks like there's somewhere in the code where `x > 0 / 0.0` is happening.

In irb:

````rb
irb(main):007:0> 0.1 / 0.0
=> Infinity
````

**Comment by ChaelKruip** [comment]
@grdw what is the status of this issue?

**Comment by jorisberkhout** [comment]
Technically not a merit order chart issue, but very related, so adding the milestone 'merit order charts' :smile:

**Comment by grdw** [comment]
It's a bit odd. ETModel's CSV Export returns Infinity, but when you run:
`MERIT_PRICE_CURVE()` in ETEngine, it returns - at the location where Infinity is suppose to be in the CSV - 40.58150729979275 ... 

I need to investigate a little further.

**Comment by grdw** [comment]
Allright - we use two different methods to determine the price curve for Merit.

The `MERIT_PRICE_CURVE()` is determined as follows:

````ruby
def MERIT_PRICE_CURVE
  ...
  scope.graph.plugin(:merit).order.price_curve.to_a
  ...
end
````

The CSV in ETModel is determined as follows:
````ruby
Qernel::Plugins::MeritOrder.new(
   scenario.gql.future_graph
).order.calculate.price_curve
````
