### ISSUE TITLE
The IABR 2035 scenario shouldn't export solid biomass and waste

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2077]
The new and improved primary demand mekko chart has left me a bit confused:
I see export of waste, solid biomass and the like and assume this is because the scenario exports YUUGE amounts of electricity. Somehow that won't make sense to people scrutinizing this scenario, however, as the power exported is wind power, i.e. excess production from wind turbines at times when there is insufficient demand.

Yuuge exports of windpower in Groningen 2035:
![image](https://cloud.githubusercontent.com/assets/308563/13357714/ed388634-dcab-11e5-9a0c-11df994901c8.png)

The calculation takes into account the relative shares of biomass and waste in power production and then reasons these must be exported as primary carriers. This is confusing and incorrect IMO.

![image](https://cloud.githubusercontent.com/assets/308563/13357556/3cfbad46-dcab-11e5-9d6a-18e12aec856f.png)

No actual biomass or waste is exported and the big weakness of this particular scenario is all the IMPORTED biomass.

Also, the power exported is all wind or solar power, as only those can give rise to excesses in the Merit Order calculation. In fact, merit could tell us exactly how much of each is exported. This could then be used to quantify the power export in the primary demand chart
## possible solution
1. If merit is ON, we can use merit to quantify the primary source of exported electricity instead of use the production shares per input carrier
2. If merit is OFF, could we not split exported power into `renewable` and `non-renewable` electricity? We could lump he biomass-fired power and 54% of the waste-fired power in with the renewable. 

notifying @jorisberkhout

**Comment by AlexanderWirtz** [comment]
p.s. feel the bern

**Comment by ChaelKruip** [comment]
> In fact, merit could tell us exactly how much of each is exported. This could then be used to quantify the power export in the primary demand chart

You are correct! 

I always thought that it was a statistical choice rather than a shortcoming to use the annual national mix to quantify the exported mix.
