### ISSUE TITLE
Slider cap for P2G should be higher still

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2078]
I propose something in the order of 5000 - 10000 

1000 is quite a small installed capacity of 740 MW (against planned wind capacity of 10.5 GW in 2023.

@jorisberkhout @ChaelKruip @RobTerwel lemme know what you think

**Comment by RobTerwel** [comment]
I fully agree with raising the max. possible installed capacity. If we hold on to the current implementation, 5000 - 10000 units gives a good order of magnitude in terms of output. Alternatively, we could increase the capacity of an individual unit (currently 0.4 MW output, while modules of a few MW already exist).

**Comment by AlexanderWirtz** [comment]
> Alternatively, we could increase the capacity of an individual unit (currently 0.4 MW output, while modules of a few MW already exist).

As Joris and I were discussing possible things for Joris to pick up, we thought of doing a bit more research on these units and involving Albert v/d Molen and GasUnie. One or two days might be available from the GasUnie budget, which is very much about the coupling of the electricity and gas systems.

**Comment by AlexanderWirtz** [comment]
also involving @dennisschoenmakers when he comes back, because this could affect how we spend the GasUnie time

**Comment by jorisberkhout** [comment]
The slider cap has been increased to `10,000` with https://github.com/quintel/etsource/commit/f0fb6964771f73d50f32e7af436f1114e6bca819. Leaving this issue open as some more research into this slider cap would be good

**Comment by jorisberkhout** [comment]
Assigning @RobTerwel and adding `industry in transition` milestone.

**Comment by jorisberkhout** [comment]
Assigning @DorinevanderVlies to research a realistic slider cap.

**Comment by DorinevanderVlies** [comment]
After discussion with @jorisberkhout the slider cap has been increase to `100,000` with https://github.com/quintel/etsource/commit/f31322afb1a8b60e3bd3338e4202b1a27604adcb.

### Justification
For the current Urgenda 2030 scenario 35,000 is sufficient to convert all excess electricity to hydrogen. Setting the slider cap to 100,000 allows to implement even more wind/PV. The increase of the cap also allows to explore the possibilities of using hydrogen made from excess electricity in the fertilizer industry.

**Comment by jorisberkhout** [comment]
Closed by https://github.com/quintel/etsource/commit/f31322afb1a8b60e3bd3338e4202b1a27604adcb.
