### ISSUE TITLE
Slider maximums (and sometimes also minimums) should be more dynamic

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etmodel#2080]
Problems now:
- sometimes slider ranges have been set so wide, that imputing a normal number is just ridiculously difficult
- sometimes slider ranges are too low and do not allow your value

**Comment by ChaelKruip** [comment]
One of the ideas I like (courtesy of @dennisschoenmakers) is to allow the user to drag some sliders beyond their current range:
![img_5157_jpg](https://cloud.githubusercontent.com/assets/1303760/13666180/78dec47e-e6b0-11e5-9605-0fb024dca43d.png)

This would provide a lot of flexibility without having to change the look and feel of the current interface.
