### ISSUE TITLE
Add a chart showing the hourly consumption and supply of flexibility technologies

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2082]
#### Introduction

As described in more details in https://github.com/quintel/etmodel/issues/2081, we would like to give the user of the ETM more insight into the results of the merit order calculation. The chart proposed in https://github.com/quintel/etmodel/issues/2081 deals with the hourly production and demand of electricity. I think it would be counter-intuitive to als show the consumption and production of the flexibility technologies in the same chart and propose to add a second chart dealing with just the latter.

#### Proposed implementation

Below is a sketch of the implementation that I propose. In order not to confuse the user of the ETM too much, I propose to show just the hourly demand curve and ignore how the electricity is produced (I propose to visualise this by make the area underneath the curve light grey).

- The profiles for the flexibility technologies should be displayed on top of the demand curve. This show the user straightaway when flexibility technologies consume electricity and, in the case of the two battery technologies (home batteries and electric vehicles), when the stored electricity is supplied back to the grid.

![merit_plot_2](https://cloud.githubusercontent.com/assets/4669028/13853440/fe734ae0-ec66-11e5-9133-a84f2ca9dc15.jpg)

- It should be possible to switch between a view for the entire year and a view for a specific week in that year, just like in ETMoses.
- Since only six 'technologies' are relevant for the flexibility calculation, I propose to always show the six profiles.
- It goes without saying, that this chart should only be displayed when the merit order is switched on.
- All profiles and related data are available in ETEngine.

As discussed with @AlexanderWirtz , @dennisschoenmakers and @ChaelKruip . Notifying @antw . I would be happy to hear your feedback!

Assigning @grdw to implement this. Talk to @ChaelKruip and me about the planning.

**Comment by grdw** [comment]
![screen shot 2016-04-26 at 16 56 47](https://cloud.githubusercontent.com/assets/2676542/14822700/e37b37e2-0bcf-11e6-92f6-0f832c9de33d.png)

So like this :100:

**Comment by dennisschoenmakers** [comment]
> So like this :100:

![image](https://cloud.githubusercontent.com/assets/104830/14831758/5d0c40a2-0bf7-11e6-802a-e3cbd6fe07f1.png)

**Comment by jorisberkhout** [comment]
Awesome chart, @grdw ! I see the following action items regarding this chart:

- [ ] Add y-label (**MW**)
- [ ] Display daily average in annual view
- [ ] Update translation (see https://github.com/quintel/etmodel/issues/2100)
