### ISSUE TITLE
What should the reset button next to each slider do?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2085]
This issue a continuation of the discussion in https://github.com/quintel/etsource/issues/1092. That issue consisted of two separate issues, one of a technical nature, which has been solved, and a more fundamental one, which is the subject of this issue.

The fundamental question is, what should the reset button next to each slider do? Should it:
1. reset the slider to the value in the relevant dataset (i.e. the present graph), or 
2. reset the slider to the value in the preset of 'parent' scenario?

Or, as @antw phrased it much better in https://github.com/quintel/etsource/issues/1092#issuecomment-199268488:

> If the request is “the start value should be inherited from the preset or ‘parent’ scenario” then I think I can come up with a better way to achieve that than resorting to using the future graph.

I have a preference for the second option. What do you think the reset button should do, @AlexanderWirtz , @dennisschoenmakers , @antw , @ChaelKruip and @RobTerwel ?

Assigning myself to keep track of the discussion. This issue is not urgent as the technical issues have been solved in https://github.com/quintel/etsource/issues/1092.

**Comment by antw** [comment]
> I have a preference for the second option. What do you think the reset button should do?

Both are valid, but I think the second option is what most visitors would expect, especially when using a preset. I have no strong preference either way.

**Comment by dennisschoenmakers** [comment]
> Both are valid, but I think the second option is what most visitors would expect, especially when using a preset. I have no strong preference either way.

**Comment by dennisschoenmakers** [comment]
> Both are valid, but I think the second option is what most visitors would expect, especially when using a preset. I have no strong preference either way.

Agree with @antw!

**Comment by ChaelKruip** [comment]
> Agree with @antw!

Me too!

**Comment by jorisberkhout** [comment]
I believe @AlexanderWirtz agrees with the second option as well.

@antw , when you have some time, could you give an estimate of how much time it would take to implement this? No priority.

**Comment by dennisschoenmakers** [comment]
> No priority.

I've hear about high and low priority before. Now, we have an escape! :smile:
