### ISSUE TITLE
Add instructions / how-to to scaling interface

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2089]
As noticed by @MarjoleinSchwachofer , the scaling interface lacks instructions on what it is for and how to use it. I agree and think that we should add a short text explaining this and include a link to the ETMoses wiki for those who want to read more.

As suggested by @ChaelKruip , we could you the blank space surrounding the scaling interface for this. I created the following mock-up without worrying about the text. What do you think about the layout, @MarjoleinSchwachofer , @dennisschoenmakers , @AlexanderWirtz , @antw and @ChaelKruip ? If you like it, I will come up with a suggestion for the text. 

<img width="1440" alt="screen shot 2016-04-12 at 17 11 01" src="https://cloud.githubusercontent.com/assets/4669028/14466208/262e99bc-00d6-11e6-827c-8e1d8121e0b3.png">

**Comment by jorisberkhout** [comment]
Part of https://github.com/quintel/etmoses/issues/893.

**Comment by ChaelKruip** [comment]
> What do you think about the layout,

I like it. It would be a bit far-fetched to link to other pages for an explanation of the basic functionality here in my opinion. One or two sentences and a 'read more' link would be fine I think.

**Comment by MarjoleinSchwachofer** [comment]
What's the status of this?

**Comment by michieldenhaan** [comment]
Closing, scaling option has been removed.
