### ISSUE TITLE
Should the ETM support multiple start-years?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2091]
This happens often: someone makes a scenario and we update the dataset, the scenario changes and needs to be adjusted or re-made. This is a lot of work and never leads to the exact same outcomes.

I'm wondering how hard it would be to support multiple datasets in the ETM. By default, the user will start with the latest dataset but older scenario's use the original dataset to initialise the graph and thus stay the same even though the ETM evolves.

Some of the changes to the ETM are improvements to the modelling and will affect the older scenario's as well but this happens not often in my experience. Most improvements of the ETM are additions which are completely backwards compatible (flexibility, hydrogen, lng, better charts etc.).

I think this feature would also be interesting in its own right because it allows you to compare different start-years in the same interface.

What do you think @AlexanderWirtz @jorisberkhout @dennisschoenmakers @antw?

**Comment by jorisberkhout** [comment]
I like this idea! We keep all older datasets compatible with changes to the modelling so it is already possible to 'load' an older dataset without any problems.

Apart from changes to the dataset and the modelling, I see two other things that can effect the results for a scenario:
- changes in the technical and cost parameters for technologies
- changes in the fuel costs

The fact that we store and maintain separate versions of the datasets makes it easy to roll back to a previous year. Changes to the technical and cost parameters as well as changes to the costs happen more ad hoc and we do only keep the latest version, making it harder to roll them back without using some Git magic. I do not immediately see how to solve this.

**Comment by ChaelKruip** [comment]
> The fact that we store and maintain separate versions of the datasets makes it easy to roll back to a previous year. Changes to the technical and cost parameters as well as changes to the costs happen more ad hoc and we do only keep the latest version, making it harder to roll them back without using some Git magic.

Good point! I think this is of lesser importance than the actual energy balance but it can have impact indeed. A fancier version of the above proposal could include a 'snap-shot' of the complete dataset including technical specs and carrier costs at the moment of deployment (or another standardised moment in time).

**Comment by AlexanderWirtz** [comment]
> Good point! I think this is of lesser importance than the actual energy balance but it can have impact indeed. A fancier version of the above proposal could include a 'snap-shot' of the complete dataset including technical specs and carrier costs at the moment of deployment (or another standardised moment in time).

Good point indeed. We do not always make a complete dataset complete with carrier costs, as the dataset takes ages to work out and the carriers are a quick bit of research. In principle this would require a snapshot of the complete dataset everytime we update carrier costs. Not impossible of course.

I do very much like the idea. It would even make it possible to show more than one 'present' year. Where for example both 2012 and 2013 data are plotted in a chart.
