### ISSUE TITLE
Wanted: a table that shows me if my heat network is balanced

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2092]
This is a long-standing wish: to be able to tell from the front-end if the heat network has enough heat supply, and how it is being supplied.

Right now, this is one of my favorite pages on etengine:

`energy_heat_network_steam_hot_water`
![image](https://cloud.githubusercontent.com/assets/308563/14494149/99feead2-0189-11e6-81d8-b30e6a8ca03e.png)

Perfection, as far as nerdy clarity is concerned. Maybe a bit too much for the front end.

Still, something like this is needed for users to be able to see whether their scenario's are balanced wrt the `heat_network`

**Comment by AlexanderWirtz** [comment]
A shout out for the great idea of adding this table. Who's with me? @jorisberkhout @dennisschoenmakers @robterwel

**Comment by RobTerwel** [comment]
> Who's with me?

Count me in!

**Comment by dennisschoenmakers** [comment]
![image](https://cloud.githubusercontent.com/assets/104830/14880662/62a88b9e-0d30-11e6-9a36-f1c05e8f274e.png)

**Comment by ChaelKruip** [comment]
> Perfection, as far as nerdy clarity is concerned. Maybe a bit too much for the front end.

Does anyone have an idea of how to fit the relevant information into a table or chart (preferably one we already have a 'template' for)?

**Comment by ChaelKruip** [comment]
The challenge with this information is that there is both supply and demand to be represented both for the present and the future year. A table will become quite busy if we would need four columns (demand present, demand future, supply present, supply future) and therefore not so insightful.

Perhaps a way to deal with this can be taken from ETMoses where the 'balance' for each pressure level is plotted in the positive y-direction for demand and negative for production.

**Comment by AlexanderWirtz** [comment]
> The challenge with this information is that there is both supply and demand to be represented both for the present and the future year. A table will become quite busy if we would need four columns (demand present, demand future, supply present, supply future) and therefore not so insightful.

@ChaelKruip I don't think that is needed. I would make separate charts for future and present. No need to complicate things. The etengine page also doesn't do that.

That already makes things quite a bit easier, in terms of tables, no? Present and future should each have a table that shows the supply and demand side of heat. 

Of course, this chart needs some documentation:

- [ ] Why are all sector heat networks connectect to a 'central heat network'?
- [ ] Why do some sectors provide for a possibility of supplying the central heat network, whereas others do not?

**Comment by ChaelKruip** [comment]
What about a table like this:
![screenshot_23_05_16_17_16](https://cloud.githubusercontent.com/assets/1303760/15475377/15b08f24-210a-11e6-8a01-b6401fb8966c.png)

**Comment by AlexanderWirtz** [comment]
It works. We would need to find human readable names and translation for these components, though.

I suppose deep down I was hoping for a table that may one day be a chart too. Something like the final or primary demand mekkos, except with only two equally wide columns, broken up into sections representing the various kinds of supply and demand. Only hitch is this would make for a hell of a legend.

**Comment by ChaelKruip** [comment]
This is a first attempt at a Mekko type chart for the heat network:
![screen shot 2016-05-24 at 17 03 08](https://cloud.githubusercontent.com/assets/1303760/15508817/4e192098-21d1-11e6-8b29-3f64cb4c02c3.png)

Please let me know what could be done to improve this. Also suggestions on the following points are welcome:
* further grouping of technologies
* other colours

**Comment by AlexanderWirtz** [comment]
I love it. Needs a bit of work, here and there.

- Can we group stuff in the legend? Put all Supply technologies on the right and all demand on the left?
- Can we also put all CHPs close together (consecutive lines)
- Let's rename stuff here and there: `Industry demand` is a bit confusing, but `Industry heat network` probably doesn't fit, right?
- Definitely needs some work color-wise: can we somehow not have the same colors for demand and supply? 

Will give more concrete feedback asap. Did I mention I love this?

**Comment by jorisberkhout** [comment]
This has been implemented, right @ChaelKruip , @AlexanderWirtz ? Can this issue be closed?

**Comment by ChaelKruip** [comment]
Done indeed. Can be closed!
