### ISSUE TITLE
Inconsistencies between merit order table and profitability of plants table

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2094]
This is something I notices while preparing a lecture using the famous Nigeria on the North Sea scenario.

See the following screenshot:
![image](https://cloud.githubusercontent.com/assets/308563/14640729/2a530254-0643-11e6-9b23-f05fcde09312.png)

## Plant profitability
First, I noticed the Plant Profitability table is missing quite some power plants and some installed capacity. Compare this to the Merit Order table, and you notice the installed capacities are rather low. Also, `Pulverized coal with wood-pellet co-firing` is not found in the profitability table, nor is `Coal CHP with wood-pellet co-firing` for some reason. Is this deliberate? 

Second, The discrepancy between `installed` and `available` capacity between the two tables is also misleading. I know the difference, but few users will know that availability of power plants is around 85 - 90%. 

Notifying @jorisberkhout

**Comment by AlexanderWirtz** [comment]
@jorisberkhout can you look at this since you are tackling other inconsistencies concerning the merit order table?

**Comment by TessColijn** [comment]
I took a look at the second part of this issue. To my understanding the user lacks the information about availability and might therefore get confused by the differences between installed and available. I suggest three different possible solutions:

1) add a column with availability or available capacity in the merit order table
2) change the merit order table to include available capacity instead of installed capacity and rename the capacity in both tables to "installed available capacity"
3) add available and installed capacity to both tables

Which solution do you think is more appropriate?

@AlexanderWirtz @ChaelKruip @jorisberkhout

**Comment by ChaelKruip** [comment]
> Which solution do you think is more appropriate?

I think I would opt for solution 2 but rename to "available capacity" because I think that 'installed' is implied and the labels will become too long otherwise. 

Increasing number of columns is not a good option as it will make these tables even more intimidating to the average user IMO.

**Comment by AlexanderWirtz** [comment]
I lean towards maximum transparency at the cost of clarity and opt for option 1. As horrible as that table already is, it provides a lot of detailed information. Simply replacing installed capacity with available capacity will make it more confusing as people who know a certain national power market will no longer recognize some of the installed capacities. It would at least add as many questions as it would solve.  

Option 1 might even lead to improvements in availabilities for specific plants by exposing them to criticism by others. I am not sure they are unassailable at the moment.

That said, I think this table is probably too ugly and complicated to be the default chart/table for this slide. Would the merit order chart not be better? A float over pop-up for that chart might be improved to include all information the table now lists and more: availability, %-age of time the plant is price-setting, etc.

**Comment by jorisberkhout** [comment]
> I lean towards maximum transparency at the cost of clarity and opt for option 1. As horrible as that table already is, it provides a lot of detailed information. Simply replacing installed capacity with available capacity will make it more confusing as people who know a certain national power market will no longer recognize some of the installed capacities. It would at least add as many questions as it would solve.

I couldn't have said it any better and fully agree with @AlexanderWirtz . 

> That said, I think this table is probably too ugly and complicated to be the default chart/table for this slide. Would the merit order chart not be better? A float over pop-up for that chart might be improved to include all information the table now lists and more: availability, %-age of time the plant is price-setting, etc.

Perhaps we can leave the `Full load hours, present` column out and replace it by an `Availability` column?

**Comment by ChaelKruip** [comment]
> Perhaps we can leave the Full load hours, present column out and replace it by an Availability column?

I think that those columns are quite essential. That is the main place in the model where the actual output of the Merit calculation is quantified right?

**Comment by jorisberkhout** [comment]
> That is the main place in the model where the actual output of the Merit calculation is quantified right?

I thought that the `Full load hours, present` column shows the FLH as they come out of the dataset? Merit only runs on the future graph, right?

**Comment by ChaelKruip** [comment]
> I thought that the Full load hours, present column shows the FLH as they come out of the dataset? Merit only runs on the future graph, right?

Yes sorry. I misread your comment! Still I think the present values are important to see whether the future FLHs changed, and by how much.

**Comment by AlexanderWirtz** [comment]
> Perhaps we can leave the Full load hours, present column out and replace it by an Availability column?

I agree with @ChaelKruip that the `present` and `future` values are both informative and add value in this table. It's just that the merit order is not an easy concept and this table is already not too inviting to a non-initiate. Hence my careful suggestion to add a chart rather than a table. Who would have thunk that I would one day advocate the use of pictures over words.

**Comment by TessColijn** [comment]
From the discussion i understand that all the information currently in the merit table is essential for clarity and understanding for the table. More information that relates available capacity and installed capacity can contribute to this clarity and understanding. Although adding more columns might make the table "uglier" it does help to provide all the information. 

An additional chart to help visualise the merit order can also be a positive contribution to understanding. But maybe a chart is a good addition and thus completing the table with availability could be a first step?

**Comment by TessColijn** [comment]
I have updated the Merit Order Table. It now looks like this:

![image](https://cloud.githubusercontent.com/assets/22587085/19305705/7f0e0bae-9072-11e6-8868-4602801de32c.png)

Is this good enough?

@AlexanderWirtz @ChaelKruip @jorisberkhout

**Comment by AlexanderWirtz** [comment]
> Is this good enough?

Looks good! We might want to explain what the availability means in de table documentation (the text you see when you click the "?" symbol)

> An additional chart to help visualise the merit order can also be a positive contribution to understanding. But maybe a chart is a good addition and thus completing the table with availability could be a first step?

The chart already exists. My suggestion was to make this the default thing to show on this slide, rather than the table. Do you agree @TessColijn @ChaelKruip and @jorisberkhout ?

**Comment by TessColijn** [comment]
I have also updated the profitability table to included installed capacity and availability:

![image](https://cloud.githubusercontent.com/assets/22587085/19311020/0006bb56-908d-11e6-875f-1a08633c54a3.png)

**Comment by TessColijn** [comment]
Together with Chael we also checked the first part of the issue and the two co-firing plants should now appear in the profitability table. 

@AlexanderWirtz do you mean this chart?

![image](https://cloud.githubusercontent.com/assets/22587085/19339943/ab2204ac-9126-11e6-8a14-5adef35e475d.png)

**Comment by AlexanderWirtz** [comment]
> I have also updated the profitability table to include installed capacity and availability:

👍 

>@AlexanderWirtz do you mean this chart?

Infatti!

**Comment by TessColijn** [comment]
@AlexanderWirtz I have added the chart as the default instead of the table. Can we close this issue?

**Comment by AlexanderWirtz** [comment]
let's close it. Then. Excellent work.
