### ISSUE TITLE
Counter-intuitive profitability calculation results: are these correct?

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2095]
I am puzzled as to how come the profitability results are so different in the SER 2023 scenario after the update.

1. I was playing around with this and noticed the following: if I rest coal and gas proces to `present` values, all plants become unprofitable. 
![image](https://cloud.githubusercontent.com/assets/308563/14642679/b3c398ac-064b-11e6-8e87-a96b24f07fce.png)

2. This is odd as coal and nuclear are still running full throttle. I suppose the price setting plants do not set the electricity price high enough? Let's play around with some of these: let's remove the most unprofitable ones. These are the `Gas plant for district heat` and the `Gas conventional` plants:

Removing the `Gas conventional plants` which have no FLH:
![image](https://cloud.githubusercontent.com/assets/308563/14642848/5c473d1c-064c-11e6-9459-d67d363eeb1b.png)

Strangely enough the nuclear and coal plants now make money, even though they still do the same FLH and the price setting plants are the same (`Gas conventional` had zero FLH).

Let's remove the `Gas plants for district heat` too as they almost have no FLH and are heavily loss making:
 
![image](https://cloud.githubusercontent.com/assets/308563/14642914/a7fe47dc-064c-11e6-8366-5679971bd1d8.png)

Who still gets these results? Suddenly CCGT plants are the most profitable, even though they are now the price setting plants more often and power prices must needs be **lower** on average, meaning everyone makes less money @ the same FLH. Scusa, ma io non ci capisco un cavolo.

What am I missing @jorisberkhout?

Notifying @ChaelKruip and @RobTerwel

**Comment by dennisschoenmakers** [comment]
Probably some power plants were making money before on certain moments in time when the Merit Order ran 'empty' and [a fall back price of **600** is being used](https://github.com/quintel/merit/blob/5afa92c854b6d4e8d5c754b6206c1148620a91d2/lib/merit/order.rb#L101). With more power plants in the Merit Order, this (very) high price is never attained anymore.

**Comment by AlexanderWirtz** [comment]
That solves this issue. You are very smart, @dennisschoenmakers 
The difference with the results from last year, is that there were some 'hidden' gas turbines in the mix, which were hard to spot, because they were only 6 MWe installed capacity (slider setting `0.0`). They kept this 'fall back option' to the range of 60 - 100 EUR/MWhe (depending on gas prices), rather than 600 EUR/MWh.
