### ISSUE TITLE
When downloading the price data csv from etmodel and checking the price curve from etengine I see two different result sets

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2096]
When I check etengine's MERIT_PRICE_CURVE()

![screen shot 2016-04-22 at 10 21 31](https://cloud.githubusercontent.com/assets/2676542/14735897/fffd5b84-0873-11e6-84ba-ba752d734e40.png)

I get an array with 5.633... with a length of 8760

However when I download the price data on the merit order page.

![screen shot 2016-04-22 at 10 22 33](https://cloud.githubusercontent.com/assets/2676542/14735919/25b2e092-0874-11e6-9b8f-67a971f00193.png)

I get:

````
3.459.431.440.751.960
3.459.431.440.751.960
3.459.431.440.751.960
3.459.431.440.751.960
3.459.431.440.751.960
3.459.431.440.751.960
3.459.431.440.751.960
3.459.431.440.751.960
3.459.431.440.751.960
3.459.431.440.751.960
3.459.431.440.751.960
3.459.431.440.751.960
36.603.030.127.895.600
3.459.431.440.751.960
3.459.431.440.751.960
3.459.431.440.751.960
36.603.030.127.895.600
36.603.030.127.895.600
36.603.030.127.895.600
36.603.030.127.895.600
36.603.030.127.895.600
36.603.030.127.895.600
36.603.030.127.895.600
3.459.431.440.751.960
3.459.431.440.751.960
3.459.431.440.751.960
````

Which is a little more exciting. Now I'm wondering what to draw and what the differene is between the two charts?

Related: #2083

**Comment by antw** [comment]
The CSV is correct (although I'm not sure where all the extra `.`s are coming from, because I don't see those).

I suspect the GQL sandbox may be doing something quirky, because it returns a different `Merit:Order` object than the one used to calculate the graph.

I'm curious which result you'll get when trying with a Gquery...

**Comment by antw** [comment]
Happens in a Gquery too. Investigating. 😕

**Comment by grdw** [comment]
> The CSV is correct (although I'm not sure where all the extra .s are coming from, because I don't see those).

Hmm, maybe it's my Excel layout (I copied those values from Excel :no_mouth:).
