### ISSUE TITLE
NICE TO HAVE: users can edit scenario 'user values' for scenarios they own

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2099]
Now that we are using regional scenario's to support clients from Gelderland, Groningen, Ameland and (hopefully soon) Goeree-Overflakkee, we are coming upon an unfortunate shortcoming of the way we store scenario settings. Scenario files are completely off-limits to our clients. It would be ideal if 'ETM literate' users could edit some of these themselves.

Since these regional scenario's often involve quite a bit of scaling and tweaking before 'present' energy use accurately reproduce statistics, these scenario files contain a long 'pre-amble' of input statements. Since only Quintel staff can access these scenario files, only they can perform or amend such 'tweaking'. Several clients have already inquired if they can have access. For transparency's sake and because we claim to be 'completely' open source, I believe it is desirable to have the ability to give users access to scenario files they own. 

I suggest only giving access to `scenarios` and `scenario-scaling` tables and only particular fields or columns in those tables at that. I realize this is probably a nightmare to set up and to make sure stuff doesn't break, but I would appreciate it if we gave this issue some thought.

notifying @ChaelKruip @jorisberkhout @antw @grdw @RobTerwel

**Comment by ChaelKruip** [comment]
I think it would be a bad idea or even impossible to given user (limited) access to the database. Correct me if I'm wrong here @antw. 

One possible route to a solution would be to make it possible to store scaled scenario's as presets (possibly hidden from the menu). The '.ad'-file containing the scenario would then be available on Github and can be edited by anyone with a Github account...

**Comment by AlexanderWirtz** [comment]
To clarify: we only need the user to edit the 'user_values' field of his own scenarios and perhaps the description field. No help no additional input statements. Just a possibility to change the numbers we put in there using our custom analysis for a scaled scenario project. 

This should be a plain and simple interface solution. I understand etmodel will have to talk to etengine and this requires API stuff. @Dennisschoenmakers please elaborate

**Comment by dennisschoenmakers** [comment]
There are some tricky technical issues with this, as 
* the `user_values` exist on et-engine, and cannot be set by its entirety through the API (yet), 
* access and editing through etengine would be cumbersome, since we lack user authority levels there to enable only update this field without e.g. being able to import etsource commits. 😅 

I suggest we check out updating the user_values over the API first. Will update you guys!

**Comment by AlexanderWirtz** [comment]
Updating through API seems the best idea to me. This will be a lot more intuitive to users as well.

**Comment by antw** [comment]
I'm not *entirely* sure I understand, so please correct me if I'm wrong. The problem is:

1. Scaled-down regional scenarios need the `present` scenario to be tweaked to suit the region,
2. Sliders to alter the `present` scenario do not exist in the ETM.

If so, can't just add those sliders to ETModel, with a suitable warning about it being an experimental feature, for advanced users only?

**Comment by dennisschoenmakers** [comment]
> If so, can't just add those sliders to ETModel, with a suitable warning about it being an experimental feature, for advanced users only?

We could also do that. These inputs however are a bit unusual to say the least, and of course we are lacking labels and any background information.

Perhaps a special page with a form where you can enter values of these 'special' inputs would be an alternative to editing the whole `user_values` in a text field?

**Comment by ChaelKruip** [comment]
> Perhaps a special page with a form where you can enter values of these 'special' inputs would be an alternative to editing the whole user_values in a text field?

I like this option because it will limit the number of people that end up on this page accidentally. 

Something along the lines of [this page](https://beta-engine.energytransitionmodel.com/data/latest/inputs) but with editable entries and specific for a scenario would do the trick right?

**Comment by dennisschoenmakers** [comment]
> Something along the lines of this page but with editable entries and specific for a scenario would do the trick right?

Yes, but I think this page has to be incorporated in etmodel, not etengine.

**Comment by antw** [comment]
Does something prevent these inputs being represented as sliders? Showing them a sliders has many advantages:

* The rest of the ETM uses them, so users will be familiar with how they work.
* (Nearly) instant feedback to changes.
* Little to no extra code. (!!!)

Showing a list of inputs with raw keys and simple text fields is not a very user-friendly experience.

To prevent accidental modification of the "present day" sliders, we could require the user to read a message – and click a button.

<img width="522" alt="screen shot 2016-04-28 at 13 20 13" src="https://cloud.githubusercontent.com/assets/4383/14885626/5381c9e6-0d44-11e6-9986-ee696ca07d68.png">

(click the button, we'll show the sliders, and remember not to show the message again).

**Comment by dennisschoenmakers** [comment]
I like that @antw. Do you envision a general setting like 'adjust present values' or something similar?

**Comment by antw** [comment]
> Do you envision a general setting like 'adjust present values' or something similar?

It depends what you mean by that. If you mean the user ticks a box and `future` sliders magically become `present` sliders, then no. 😆

If you mean that the `present` sliders are hidden by default – and shown once the user enables them – then sure.

<img width="239" alt="screen shot 2016-04-28 at 13 49 19" src="https://cloud.githubusercontent.com/assets/4383/14886305/0c42d5b2-0d48-11e6-8318-feecc70e598b.png">

1. We'd add a new tab to the sidebar for the "Present day scenario", and new sliders/inputs for things that the user is allowed to edit. Depending on how many sliders we need to add, perhaps it will have to be split into multiple tabs.

  <img width="237" alt="screen shot 2016-04-28 at 13 41 43" src="https://cloud.githubusercontent.com/assets/4383/14886093/f7e6b1b6-0d46-11e6-97be-9c6c4f09e2fe.png">

  I'm not sure about the styling, and perhaps even that tab can be hidden until the visitor enables a setting from the drop-down box?

  Alternatively, they could be placed with the `future` sliders like so:

  <img width="466" alt="screen shot 2016-04-28 at 13 46 44" src="https://cloud.githubusercontent.com/assets/4383/14886235/b491d9c6-0d47-11e6-94e4-7688ea523491.png">

2. When the user first tries to view the `present` sliders, show them the caution message.
3. Once they click "Continue", show the sliders.

**Comment by AlexanderWirtz** [comment]
@antw 

>I'm not entirely sure I understand, so please correct me if I'm wrong. The problem is:
>1. Scaled-down regional scenarios need the present scenario to be tweaked to suit the region,
>2. Sliders to alter the present scenario do not exist in the ETM

Well, quite a few of these input statements concern `both` statements. The reason is that when you scale `present` demand, you also want to scale `future` demand, so a graph in question appears flat when all (`future`) sliders are set to `0`. 

Part of the scenario file for GEA looks like this:
```
households_solar_pv_solar_radiation_market_penetration_both: 1.8703215012591
households_solar_pv_solar_radiation_market_penetration: 9.6
```

The first statement is used to get to the correct numbers for this area. The second is a future scenario specific statement. This is also used for `useful_demand` statements that first scale this to the right value using `households_useful_demand_heat_per_person_both` and then set a `future` slider to a particular position, because we want to communicate to GEA people that we anticipate a fall or rise in `future useful demand`.

By now I'm sure you have gotten my point. The elegant solution you are proposing would work if w ealso included `both` sliders. These don't work in all cases, though (technology shares is one), which is very confusing to users. That in turn would require us to do a lot of explaining.

The solution I am looking for only allows users to modify the existing input statements (`present`, `future` and `both`) in a scenario file, or use other existing ones not found in the scenario file IF they have the technical nous. They can copy these input statements from the analysis we have already shared with them. This analysis was made by @RobTerwel and shows exactly how we took energy numbers and arrived at input statements for the scenario. Should they change the energy numbers, the input statements will change and need to be copied into the relevant scenario files.

This also illustrates the need / desirability to be able to edit the scenario description field, where a user can document his actions.

**Comment by AlexanderWirtz** [comment]
p.s. The reason we use these `both` statements and not just the `present` and `future` statements is that this makes it (almost) possible to do all the 'tweaking' in something we might call a 'preamble' to the scenario file. All the stuff a user adds to such a scenario by saving a new version gets appended to this preamble. 

This does not quite work, as the technology share sliders cannot be set using `both` sliders, so those `future

**Comment by antw** [comment]
Thanks for the explanation @AlexanderWirtz. I agree that including the `present`/`both` sliders inline with `future` sliders is perhaps not the best solution.

However, I still think editing preset files is really user-unfriendly. Revealing internal details (such as input keys) could give us all sorts of headaches down the line. For example, maybe a visitor gets used to copy/pasting `households_solar_pv_solar_radiation_market_penetration_both` into a "preamble" field, only for something to break if we decide to rename that input.

This feature will be much more future-proof – and user friendly – if we can find a way to use sliders to take input from the visitor. Maybe we can instead put them all into a "Scenario Setup" or "Preamble" section?

![screen shot 2016-05-03 at 15 59 52](https://cloud.githubusercontent.com/assets/4383/14987592/18b16134-1148-11e6-8b10-fe16b5ce3c90.png)

In here we'd show the preamble inputs as sliders which the visitor could edit. Maybe we could even include a drop-down selection of other preamble sliders which they can add to their scenario? When they've made their changes, the scenario can be saved like any other.

![screen shot 2016-05-03 at 16 21 35](https://cloud.githubusercontent.com/assets/4383/14988292/215acb1a-114b-11e6-8344-ef56a8fb1792.png)

**Comment by dennisschoenmakers** [comment]
Thanks @antw and @AlexanderWirtz for sharing your thoughts. 

I think what adds to the complexity, is that users do not even *wish* to set slider values. It rather is a *poor man's solution*.

Let me show this by the example provided above:

```
households_solar_pv_solar_radiation_market_penetration_both: 1.8703215012591
households_solar_pv_solar_radiation_market_penetration: 9.6
```

The first line is a result of an spreadsheet calculation, where the market penetration for solar pv in the *present* graph for this local scenario is different, e.g. 12.5% in stead of the 'average' 10%. As the scenario covers 12 years (2025 - 2013), the 'yearly growth'* is calculated as 1.87% per annum. This is calculated in an Excel sheet.

It would be a bit weird if we would enable users to input this rather far fetched number, the 'yearly growth' number in a very convenient way, while really, they just want to adjust a present number. 

* = it is a bit counterintuitive that the end year is used to for yearly sliders for the present_graph, and this leads to all kinds of unwanted effects.

What I am asking myself: is there not a more **direct** way possible to get what we want? To enable users/ourselves to adjust the present dataset of scaled scenario?

**Comment by AlexanderWirtz** [comment]
> However, I still think editing preset files is really user-unfriendly. Revealing internal details (such as input keys) could give us all sorts of headaches down the line. 

Good points, @antw. Note that I am not requesting the possibility to edit preset files, but the possibility to edit the `user_values` fields in the `scenarios` tables in the etengine database. Equally ugly and error-prone, but the latter cannot be done through GitHub.

> I think what adds to the complexity, is that users do not even wish to set slider values. It rather is a poor man's solution.

Spot on. The reason we have this preamble is to really tweak numbers to fit the know energy uses in the various sectors. The example @dennisschoenmakers mentions does not concern a 'per annum' slider, but his point is still valid. 

I know we want something prettier and easier than editing these `user_values` fields. My problem right now is that clients are a little grumpy about the fact that they cannot themselves influence the input data for the regional models. 

>What I am asking myself: is there not a more direct way possible to get what we want? To enable users/ourselves to adjust the present dataset of scaled scenario?

@dennisschoenmakers there might well be, but we do not have budget to come up with one and implement it, IMO.

**Comment by ChaelKruip** [comment]
> What I am asking myself: is there not a more direct way possible to get what we want? To enable users/ourselves to adjust the present dataset of scaled scenario?

A bit out-of-the-box perhaps but why not let the user set the demands directly on the nodes (or edges) of the present graph and area variables? Essentially, changing the present graph is equivalent to making a new dataset, so why not do that?

Advantages:
* direct: what you see is what you get
* already possible through the data-analysis. This could be very similar to making a dataset for a new country which has the added value of the present scenario being thoroughly documented and version controlled

Disadvantages:
* it is quite a bit of work and requires effort from the client
* We have to investigate how the 'scaling'-aspect of the scenario can be dealt with when making a new dataset

My worry with the more indirect solutions proposed above is that we will have to assist the client anyways because it can be counter-intuitive to set the present graph with sliders (what is the reference?!). The _present and _both input statements where a hacky solution in the first place and we will make it increasingly more difficult to replace them with a more solid and future-proof solution if we facilitate outsiders to use them. 

> @dennisschoenmakers there might well be, but we do not have budget to come up with one and implement it, IMO.

If the ETM will be used for local situations more often in the future (which I hope and anticipate), the need for a better solution is worth the headache and investment now. If we don't have budget, we should not do something quick and dirty that will bite us in the behind later IMO.

**Comment by AlexanderWirtz** [comment]
> A bit out-of-the-box perhaps but why not let the user set the demands directly on the nodes (or edges) of the present graph and area variables? Essentially, changing the present graph is equivalent to making a new dataset, so why not do that?

This is very complicated for a region, because in our experience the data are essentially lacking, not to mention the know-how. It is also surprisingly time consuming. @jorisberkhout had a look at this before and warned me it was not a great idea. 
The scaling method is nice, because it allows us or other users to circumvent all kinds of questions about who is responsible for what energy use in what part of the energy system. Any additional research to tweak the numbers improves such a scaled scenario. 

 >We have to investigate how the 'scaling'-aspect of the scenario can be dealt with when making a new dataset

This is indeed very interesting. We could scale the energy balance and autoproducer table, production timecurves etc and then perform the analysis steps. If we go to that level of detail though, we might as well think about changing the EB altogether and nixing the metals sector for a region that has no metallurgic industry etc. A bit of a can of worms.

> My worry with the more indirect solutions proposed above is that we will have to assist the client anyways because it can be counter-intuitive to set the present graph with sliders (what is the reference?!). 

I understand. This is why for know i want to tell the client he can use our regional analysis to recalculate the numbers and input statements to be put into `user_values`, but any assistance from us would have to be paid for. Managing expectations can go some way to cover this. It is of course bound to go wrong at some point too.

>If we don't have budget, we should not do something quick and dirty that will bite us in the behind later IMO.

I disagree. This is a direct wish from a client who has just agreed to work with us for the coming years. If we manage expectations by saying that for no budget we can give them something that is technically complicated and likely to break, I think this is worth doing in it's most simplistic form. Also because I do not see how it will 'bite us in the ass' so badly. Scenario's can break, sure, but that is already the case for scenario's over a year old.
We can make it quite clear that if they want a more user friendly option, we need to find someone to pay for it. It may even be more user friendly for us, as it may make it easier and less risky to edit existing scenarios.

**Comment by AlexanderWirtz** [comment]
I would like to press for a conclusion as the GEA project is drawing to a close (for now) and I want to know what to tell the client about this. Can we give clients access to their own scenario files?

**Comment by dennisschoenmakers** [comment]
Weighing all ins and outs, I suggest we create a simple page where people can edit theor `user_values` and `description`, comparable to the [**compare/merge**](https://beta-pro.energytransitionmodel.com/scenarios/compare) view. We would need user authorization with this, because we wouldn't allow anybody to edit all scenarios. :smirk:

**Comment by dennisschoenmakers** [comment]
... or we could only allow the user to *only* create a 'new' scenario with this view, then we wouldn't have the authorization issue.

**Comment by AlexanderWirtz** [comment]
> ... or we could only allow the user to only create a 'new' scenario with this view, then we wouldn't have the authorization issue.

Sounds like a safe solution to me.

**Comment by antw** [comment]
> We would need user authorization with this, because we wouldn't allow anybody to edit all scenarios.

Any person can already edit any scenario by PUTing to ETEngine's `/api/v3/scenarios/:id`.

I agree that ETModel should create a new scenario when a user makes direct edits to `user_values`.

**Comment by dennisschoenmakers** [comment]
> Any person can already edit any scenario by PUTing to ETEngine's /api/v3/scenarios/:id.
reac

I know. :grin:

I agree that ETModel should create a new scenario when a user makes direct edits to user_values.

:+1: Then I think we have come to a conclusion. 🎉
