### ISSUE TITLE
Fix correct translations for output element series merit order

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2100]
I'm currently busy with the stacked hourly supply chart for merit. However, there are 56 participants so there are 56 chart labels that need to be translated to Dutch and correctly written in English. 

The thing is, I have no idea what to call each one and to do it together manually by hand and typing everything over is a bit of waste of time. I'd rather assign this to someone who actually knows what to call these technologies/carriers. 

Re-assign at will.

Related: #2081

**Comment by jorisberkhout** [comment]
I suggest to use the same translations that we use in the merit order table ([NL](https://github.com/quintel/etmodel/blob/master/config/locales/nl_output_elements.yml#L93) and [EN](https://github.com/quintel/etmodel/blob/master/config/locales/en_output_elements.yml#L95)), but I am a little puzzled by the fact there is far less than 56 keys in here. I will look into this a bit more.

**Comment by grdw** [comment]
Those keys are also not the same. This is because the gqueries that the merit order table uses are different from the ones that are called for the chart.

**Comment by jorisberkhout** [comment]
Closed with https://github.com/quintel/etmodel/commit/9f0ff243fc259f9503edf4149fcacc6198050736.
