### ISSUE TITLE
Geothermal electricity production is missing from merit order table

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2102]
I noticed that the geothermal electricity production does not show up in the merit order table even though it does in other relevant charts. Is there is reason for not including geothermal electricity production to the merit order table, @AlexanderWirtz or @ChaelKruip ? If not, I can add it.

**Comment by AlexanderWirtz** [comment]
Jeroen Alsem generated time curves for this if I am not mistaken. The issues about this (now closed) should include a mention that it should be added to merit. Does merit correctly take geothermal electricity into account?

If so, it should be added to the table.

**Comment by ChaelKruip** [comment]
Please also have a look at https://github.com/quintel/merit/issues/86

**Comment by ChaelKruip** [comment]
And https://github.com/quintel/merit/issues/69

**Comment by jorisberkhout** [comment]
Assigning @ChaelKruip .

**Comment by jorisberkhout** [comment]
Geothermal has been added to the merit order table by @ChaelKruip with https://github.com/quintel/etmodel/commit/712be1d2c4a97bb5862398627e97d5e7054587de. Closing this issue.
