### ISSUE TITLE
Concentrated solar power is missing from merit order table

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2103]
I noticed that the concentrated solar power does not show up in the merit order table even though it does in other relevant charts. It is also (rightfully) not included in the solar PV entry in the merit order table.

Is there is reason for not including concentrated solar power in the merit order table, @AlexanderWirtz or @ChaelKruip ? If not, I can add it.

**Comment by AlexanderWirtz** [comment]
I think the main reason is that we have no time curve data for it. That means we do not know when it is 'on'. 

It requires direct insolation unlike solar PV. Do the satellite measurements we use for etmoses provide a way to generate such curves?

**Comment by jorisberkhout** [comment]
Closed by https://github.com/quintel/etmodel/pull/2141 and https://github.com/quintel/etsource/pull/1127.
