### ISSUE TITLE
Primary demand of final demand group (and exported electricity) does not equal (import + production - export)

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2110]
The primary demand of the final demand group (plus the primary demand of exported electricity) does not equal (import + production - export). This has first been noticed by @ChaelKruip for natural gas in a customer's scenario on the Beta server. We thought this was caused by the fact that a compressed natural gas edge was not in the final demand edge group, but this solved only part of the problem (see https://github.com/quintel/etsource/pull/1112/commits/c7ce96808f8d0a560f736bd17dee65ec6a6496c5).

This mismatch could be caused by many different things. Any suggestions are welcome. I will first create a simplified version of this scenario and post the link in this issue.

I will also do the following:
- [x] check if the problem also occurs for a much simpler carrier (uranium oxide)
- [x] check if the problem in a much simplified scenario

Including @antw , @AlexanderWirtz , @dennisschoenmakers and @RobTerwel .

**Comment by jorisberkhout** [comment]
Fortunately, this turned out **not** to be a bug. We had neglected the primary demand of curtailed electricity in our analysis of the customers scenario, which explained the missing energy entirely.

Prior to adding the flexibility feature to the ETM, all excess electricity would be exported. The primary demand of this electricity is determined from the annual average fuel mix of the electricity production. With the addition of the flexibility feature, the export capacity is limited, meaning that any excess electricity that cannot be exported is curtailed. The primary demand of this curtailed electricity is determined in the same way as for exported electricity. The particular scenario referenced above has only one dispatchable plant, a gas plant. Any curtailed electricity will therefore have quite some primary demand of natural gas, which is exactly why so much natural gas was missing in our analysis of the scenario.

**Comment by jorisberkhout** [comment]
To avoid confusion in the future, the primary demand of curtailed electricity has to be added to the primary demand charts. This includes at least the following charts, but I will do a more thorough check to see if it needs to be added to more charts:

- [ ] Primary energy use (mekko)
- [ ] Primary energy use (chart)
- [ ] Primary CO2 emissions of final demand

I will take care of this.

**Comment by jorisberkhout** [comment]
Finally, this issue also pointed our attention to the assumption that the primary demand of this electricity is determined from the annual average fuel mix of the electricity production. In reality only electricity from renewables and must-run plants will be exported. Merit is already able to tell us when electricity is exported or curtailed and what the fuel mix of the electricity production is at that instant. This information could greatly refine our primary demand calculation. I will create a separate discussion issue for this.

**Comment by jorisberkhout** [comment]
Added to `Deploy September 2016`.

**Comment by jorisberkhout** [comment]
Removing milestone.

**Comment by ChaelKruip** [comment]
I have a few questions about this:
* Do we want to create a new category/sector for curtailment or add it to export?
* Do we also need to include curtailment in
  * Bio-footprint mekko?
  * Bio-carriers mekko?

Any clues @jorisberkhout?

**Comment by ChaelKruip** [comment]
These still have to be done at some point:

- [ ] Primary energy use (chart)
- [ ] Primary CO2 emissions of final demand

**Comment by jorisberkhout** [comment]
In view of time, shall we remove this issue from the deploy milestone, @ChaelKruip ?
