### ISSUE TITLE
Wanted: Mouse-over should show series label in 'Merit order hourly supply' chart

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2111]
The 'Merit order hourly supply' chart is awesome in every way, but a little hard to read sometimes, due to the fact that it has so many series in it. The color differences are too subtle for me to see whether I am looking at 'fuel cells' or 'storage in batteries' for example. 

This could be solved by having a pop-up show the series label when I hover my mouse pointer over the series in the chart.

![image](https://cloud.githubusercontent.com/assets/308563/15019553/cfdadf1c-121e-11e6-977c-c811e4eb0055.png)

notifying @ChaelKruip @dennisschoenmakers @jorisberkhout

**Comment by grdw** [comment]
I totally agree. I have to say that a mouseover might work for 'big' area's, but for the smaller one's (like "Windmolens aan kust") this will cause a problem. What we could also do is something similar to another awesome application I know of: ETMoses. Use a hover line to show the values?

**Comment by dennisschoenmakers** [comment]
:+1: It would be already be a big plus if it would only work for
big/visible areas.

**Comment by AlexanderWirtz** [comment]
> Use a hover line to show the values?

I am not sure values are interesting for this chart: in and of themselves they say very little. Only in the context of the other series does it all mean something. I would say series label is enough.

**Comment by jorisberkhout** [comment]
As discussed with @grdw, it should be fairly easy to implement a mouse-over in this chart. We feel that this will make the merit order supply chart a lot more comprehensible.

**Comment by AlexanderWirtz** [comment]
Good to know!

**Comment by grdw** [comment]
<img width="597" alt="bla" src="https://cloud.githubusercontent.com/assets/2676542/16416063/ae733174-3d40-11e6-9a04-51df3a5b2fc7.png">

Minor preview

**Comment by grdw** [comment]
There's one issue though but it's a bit minor. But when you move your mouse really slowly from path to path, Qtip (the ~~rapper~~ tooltip library we use) is having a bit of a problem detecting that there was movement. As shown here (wait for it):

<img src="http://g.recordit.co/1iSudE5DxM.gif"/>

**Comment by AlexanderWirtz** [comment]
Nice. The issue also exists for charts like the 'Final demand mekko', so this is a known issue.
