### ISSUE TITLE
Dashboard arrows in professional ETM are not showing up on Live and Beta server

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2113]
As reported by John, the arrows on the dashboard of the professional version of the ETM, indicating the changes in the dashboard values, are not showing up.

I have tested this on Live and Beta and on Chrome, Safari and Firefox. On none of the platform the arrows are shown.

Including @antw and @dennisschoenmakers .

**Comment by grdw** [comment]
I renamed the arrows for https://github.com/quintel/etmodel/issues/2108. Appearantly I changed [one file](https://github.com/quintel/etmodel/blob/cf516f8d1d9c7ddfb20ac2ec6b3f20cb76c51f55/app/views/layouts/etm/_dashboard_items.html.haml#L18) to many. Considering this a really really small change I'll add it to master as we speak.

**Comment by dennisschoenmakers** [comment]
Thanks @grdw ! Deployed as well? :)

**Comment by grdw** [comment]
Yes I did.
