### ISSUE TITLE
Merit order appears to be switched on after touching several cost sliders

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2116]
This bug was first noticed by Niki from Berenschot. While working on a scenario with only one type of dispatchable plant (a gas turbine) and the merit order **off**, she noticed that after touching several cost sliders, the scenario went back to the merit order **on** state.

Here's what I did to reproduce the bug:

1. Open https://beta-pro.energytransitionmodel.com/scenarios/517885
2. Switch of the merit order **off** (!) (the dashboard costs drop from 48.9 bln EUR to 45.2 bln EUR)
3. Move and reset some random cost sliders; I noticed that after 8 - 10 sliders, the dashboard costs went back to 48.9 bln EUR, which is equal to costs with the merit order switched on. Also, the FLH of the gas turbine changed from 200 (which is the value when the MO is off) to 1365, which equals the value with the MO on. Finally, I noticed that 'Total cost of electricity production' scatter plot started showing zero costs for plants that are not present in the scenario at this very same instant.
4. The merit order switch is still off, and switching it back on and off again didn't resolve the above issue.

Assigning @dennisschoenmakers to see if he can reproduce this. Re-assign at will.

**Comment by dennisschoenmakers** [comment]
Assigned @antw. This seems to be a very serious problem that needs to be dealt with asap

**Comment by jorisberkhout** [comment]
Let me know if you need any more explanation, @antw . I can now consistently reproduce this.

**Comment by dennisschoenmakers** [comment]
I also encountered the same bug:

1. When I start dashboard costs were at **48.9 bln**
1. Switch off Merit Order: costs were at **45.2 bln**
1. I moved all sliders in the first three categories: Fuel prices, transport and combustion plants.
1. I reset all those sliders.
1. Costs went back to to **48.9bln** 😒

**Comment by antw** [comment]
Fixed and pushed to beta *and production*. Explanation in quintel/etsource@bed7e477.

There may be a better fix in ETEngine – to initialize plugins lazily, so that we don't create the merit order plugin when accessing the FCE plugin. I shall look into that, but the ETSource fix is just as good for now.
