### ISSUE TITLE
Vertical unit of Merit Order chart is too much to the left

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2120]
I think it should move somewhat closer to the vertical axis. 

![image](https://cloud.githubusercontent.com/assets/104830/15426666/1c8e74f4-1e90-11e6-9f48-94c8c032a823.png)

1. Now the first pixel(s) are cropped
2. It seems like it belongs to something on the left hand side of your screen

**Comment by grdw** [comment]
<img width="609" alt="screen shot 2016-06-17 at 14 26 26" src="https://cloud.githubusercontent.com/assets/2676542/16150448/83302dde-3497-11e6-80cc-8e280a34d8b6.png">

Well I fixed point 1. Point 2 is a bit more of a 'thing'. If the Hourly price is over 100K the label
