### ISSUE TITLE
Does Merit get re-calculated with every slider movement?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2122]
Whatever I seem to do, the Merit Order price curve never moves an inch....

### Please help us out neighbours!

![image](https://cloud.githubusercontent.com/assets/104830/15474664/1cbee58a-2106-11e6-9437-237074e13fc5.png)

### Super dark coal future

![image](https://cloud.githubusercontent.com/assets/104830/15474683/2eada0f6-2106-11e6-8fb0-d21fe35c341b.png)

### Windy as ...

![image](https://cloud.githubusercontent.com/assets/104830/15474710/51fe8d2c-2106-11e6-8a8e-ea7285d53148.png)

**Comment by dennisschoenmakers** [comment]
cc @antw @grdw

**Comment by dennisschoenmakers** [comment]
Perhaps has to do with the newest release of #2117?

**Comment by dennisschoenmakers** [comment]
on request of @jorisberkhout assigned @grdw

**Comment by jorisberkhout** [comment]
I see this issue as well. Interestingly enough the price curve that you can download under Costs -> Merit Order does changes when I change some slider settings :confused:

Could you look into this, @grdw ?
