### ISSUE TITLE
User should have option to 'reset' to saved values in stead of default values

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etmodel#2123]
### Problem

I find it quite annoying, when you are working in a non-default scenario, often you want to go back to your 'original' slider setting, but all you can do is reset to the default setting. With singular sliders: that is doable to write down or remember the slider setting, but when you are changing a slider group, all you can do is reload the entire scenario. 😒 
#### Slider reset

![image](https://cloud.githubusercontent.com/assets/104830/15499373/2b439c74-21a4-11e6-88f5-f24fddfc2ead.png)
### Possible solution

We might want to add a select box in the menu where you can choose your behaviour.

![image](https://cloud.githubusercontent.com/assets/104830/15495460/60897746-2190-11e6-9200-215d1cf3df35.png)

cc @grdw @ChaelKruip @AlexanderWirtz

**Comment by grdw** [comment]
There are multiple ways of achieving this I guess. One way would be store all slider settings in the browser's `LocalStorage` (if the customer in question does not use [IE7, IE6 or Opera Mini](http://caniuse.com/#search=localstorage)). Than I think you could easily reset to `Last saved`. Another more complex way would be storing multiple scenario's (like a simple versioning system). 

I like the general idea though. 👍

**Comment by dennisschoenmakers** [comment]
Good idea. We could also use the preset_scenario's `user_values`.

**Comment by dennisschoenmakers** [comment]
What do you think @antw?

**Comment by antw** [comment]
> We could also use the preset_scenario's user_values.

Agree. I assume that "Last saved" refers to the most recent time the scenario was explicitly saved in ETModel. That being the case, we should likely set the `preset_scenario_id` of the *active* scenario to point at the saved scenario, and use those values when resetting.

The question is whether "Last saved" needs to be a user-selectable option at all; I think it should just be the default behaviour.

**Comment by dennisschoenmakers** [comment]
I realize now,  I could have been clearer in my description: with 'resetting' I mean hitting this button:

![image](https://cloud.githubusercontent.com/assets/104830/15499345/05fbc478-21a4-11e6-90ce-a1e47b4ae369.png)

I am adjusting the body of this ticket accordingly.

**Comment by antw** [comment]
Okay! So reset the slider to the value stored in the preset/saved scenario, or if no value is present there, back to the default. A big :+1: from me.

I suggest that this should just be the standard behaviour *always*; and that there's little need for the user to select between "Default" and "Last saved". Preferentially resetting to the preset scenario value is more intuitive.

*I'm getting deja vu though, I'm sure we're discussed this before.* 😆

**Comment by dennisschoenmakers** [comment]
> I suggest that this should just be the standard behaviour always; and that there's little need for the user to select between "Default" and "Last saved". Preferentially resetting to the preset scenario value is more intuitive.

> I'm getting deja vu though, I'm sure we're discussed this before. 😆

😏  me too

**Comment by RobTerwel** [comment]
Yep, we were discussing the function of the *slider reset* button in https://github.com/quintel/etmodel/issues/2085

**Comment by antw** [comment]
> Yep, we were discussing the function of the slider reset button in #2085

That's the one, thanks!

I'm guessing this is a couple of hours to implement and test; there's nothing too complex here.

**Comment by dennisschoenmakers** [comment]
I think it is worth it. I am busy working on a scenario and I need it every
5 minutes.... :P

On Tue, May 24, 2016 at 11:51 AM, Anthony Williams <notifications@github.com
> wrote:

> Yep, we were discussing the function of the slider reset button in #2085
> <https://github.com/quintel/etmodel/issues/2085>
>
> That's the one, thanks!
>
> I'm guessing this is a couple of hours to implement and test; there's
> nothing too complex here.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/quintel/etmodel/issues/2123#issuecomment-221220662>
>



-- 

Dennis Schoenmakers, *Partner*


*Quintel Intelligence*Atrium - Strawinskylaan 3051
1077 ZX  Amsterdam
The Netherlands

*Visiting Address:*
Keizersgracht 639
1017 DT Amsterdam

T  : +31 (0)20 301 22 69
F  : +31 (0)20 301 22 02
M : +31 (0)6 109 65 293

E : dennis.schoenmakers@quintel.com
I  : www.quintel.com and www.energytransitionmodel.com

*This message (including any attachments) is confidential and may be
privileged. Any review, retransmission, dissemination or other use of, or
taking any action with reference to this information by persons other than
the intended recipient is strictly prohibited. If you have received it by
mistake please notify the sender by return e-mail and delete this message
from your system. Please note that e-mails are susceptible to change. The
sender will not accept liability for the improper or incomplete
transmission of the information contained in this message.*

**Comment by antw** [comment]
It is now fixed so that pressing "reset" next to a slider will use the preset values, rather than the regional defaults. It'll fall back to the defaults if the preset has no appropriate value.

The "Reset scenario" option in the settings menu is not fixed, however. That option starts a new scenario with the same end year and region, and throws everything else away (scenario values and `preset_scenario_id` included). Resolving that will be more involved and I'm a bit short on time.

I'll leave this issue open as a reminder to do something about the settings menu option, and closed #2085 since that one is specifically about sliders.
