### ISSUE TITLE
Legend does not show entirely

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2130]
![image](https://cloud.githubusercontent.com/assets/104830/15506097/85038892-21c6-11e6-835e-49956e1bc475.png)

**Comment by jorisberkhout** [comment]
Assigning @grdw .

**Comment by grdw** [comment]
Possible duplicate: https://github.com/quintel/etmodel/issues/2114

**Comment by grdw** [comment]
Closing, this problem is already fixed
