### ISSUE TITLE
User should not be bothered with date-select for every chart

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2132]
Right now, you even have to select your week again for your zoomed-in chart. I think that's unfair. 😄 

But, when you have 3 charts open, you also have to select your new week for every chart: shouldn't we make that into one-select-to-select-them-all?

**Comment by jorisberkhout** [comment]
Assigning @grdw to look into this.

**Comment by grdw** [comment]
Do you mean that you want one select box or we could also synchronize the other select boxes? I'd rather prefer the latter. The reason behind this, is that if we have only one select box, it would be a bit of a hassle to find out where we would put that select box in the interface.
