### ISSUE TITLE
Not able to put two merit charts next to each other (still a problem part II)

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2136]
What I did yesterday (why the issue #2127 got really confusing):

1. I started a new scenario
2. Added two of the merit charts (doesn't really matter which of the two)
3. Do a hard refresh (so Cmd+shift+R)

---

Errors in the console (model breaks):

<img width="1074" alt="screen shot 2016-05-24 at 17 31 41" src="https://cloud.githubusercontent.com/assets/2676542/15531712/16578830-225c-11e6-8312-ccbb26a4e6f5.png">

---

I saw that the a `serie` (almost at random) returned no values when doing this upon the initial `draw()` method however, `refresh()` is getting the correct values (because, `@dateSelect.setVal(1)` is triggering a `refresh()`)  which is causing the drawing to be correct. I'm a bit confused by this though because it looks as though some Ajax request is triggering the success method way before it's actually finished, or half of the data is being submitted. I couldn't really find out.

I'm wondering if you could reproduce this by any chance? @antw

**Comment by dennisschoenmakers** [comment]
Assigned you @antw to have a **look** at this issue: perhaps you have got a clue where it's failing us? cc @jorisberkhout, @ChaelKruip and @AlexanderWirtz.

**Comment by antw** [comment]
No `Priority` tag! Bliss! :innocent:

I can reproduce this. It seems adding a second chart triggers a second request to ETEngine; the queries required for the chart aren't included in the first call to ETE. When the response to the first request is received, the data for the *second chart* aren't there, and this error is triggered. The second response then arrives with all the gqueries needed to render the second chart.

It's been this way for a long time (`git blame` says 2012), but it seems like a silly limitation. The ETM *should* be able to request all the needed Gqueries with the first request.

**Comment by dennisschoenmakers** [comment]
> I can reproduce this. It seems adding a second chart triggers a second request to ETEngine; the queries required for the chart aren't included in the first call to ETE. When the response to the first request is received, the data for the second chart isn't there, and this error is triggered. The second response then arrives with all the gqueries needed to render the second chart.

Good catch @antw! 

How come this behaviour isn't there (or noticeable) when you choose any other two charts?

**Comment by antw** [comment]
I think the merit charts just assume that the results are there – and that they'll be arrays (when in fact the result is going to be something like `null` or `undefined`), and that's why the error messages appear in the console.

> How come this behaviour isn't there (or noticeable) when you choose any other two charts?

It is. If you add two "normal" charts, lock them, and refresh, you'll find that the second chart renders some time after the first. I'm guessing that you don't see any warning messages because the missing results in the first request are [converted to zeroes](https://github.com/quintel/etmodel/blob/7e2f746fc4ebd0b97999658f9390f6ca760ac11f/app/assets/javascripts/lib/models/gquery.coffee#L9-L15).

It's worse than I originally thought: it performs an extra request *for each additional chart*:

<img width="725" alt="screen shot 2016-05-25 at 11 21 39" src="https://cloud.githubusercontent.com/assets/4383/15536808/eba62db2-226a-11e6-8a92-07248e047bd7.png">

I'm not sure how much effort this will take to change; I don't know why the author did it this way, but I'm sure they had their reasons.

**Comment by dennisschoenmakers** [comment]
Mmmm.... I selected **five** (non merit) charts, but all I got was only **a single request** (on live).

![image](https://cloud.githubusercontent.com/assets/104830/15543980/51ad8aa2-2297-11e6-932b-a615dd7343a7.png)

Locking all the charts does not change a thing.

**Comment by grdw** [comment]
Hmm. I also see three on live:

![screen shot 2016-05-25 at 16 53 53](https://cloud.githubusercontent.com/assets/2676542/15544513/4cf301fc-2299-11e6-940c-05491dfe1cdd.png)

With a merit curve though:
![screen shot 2016-05-25 at 16 54 13](https://cloud.githubusercontent.com/assets/2676542/15544518/5558ebea-2299-11e6-85a7-52318d4a7f57.png)

And if I remove that merit curve I still have three requests.

**Comment by antw** [comment]
> Locking all the charts does not change a thing.

You have to lock the charts, otherwise only the default (one) chart will be present when you refresh the page. The extra requests happen when opening a new page or refreshing, not when moving a slider.

>  3: Do a hard refresh (so Cmd+shift+R)

**Comment by dennisschoenmakers** [comment]
> The extra requests happen when opening a new page or refreshing, not when moving a slider.

This bug only exists when people do a hard refresh?

![image](https://cloud.githubusercontent.com/assets/104830/15545337/48403db6-229c-11e6-8db9-40161bec8312.png)

**Comment by grdw** [comment]
>  This bug only exists when people do a hard refresh?

Not really, in Firefox I still get the same problems with a normal refresh.

![image](http://i2.cdn.turner.com/cnnnext/dam/assets/160107101405-01-obama-tears-0107-super-169.jpg)

**Comment by grdw** [comment]
@antw what would be the expected outcome? 

Would it be that ETModel is smart enough to detect that there are `x` requests going to be send to ETEngine, merge them and only send one request to ETEngine and than render all `x` charts?

**Comment by dennisschoenmakers** [comment]
IMO more than one request is not an issue, the failing of the merit order charts when it happens, is. However, since this only happens when people have more than one chart, of which one is a merit order chart, and then they have to refresh, makes it quite a rare occurrence, right?

**Comment by grdw** [comment]
>  and then they have to refresh, makes it quite a rare occurrence, right?

Yes. You have to complete - relatively speaking - a lot of steps to reproduce this bug.

**Comment by antw** [comment]
> Would it be that ETModel is smart enough to detect that there are x requests going to be send to ETEngine, merge them and only send one request to ETEngine and than render all x charts?

I don't think it even needs to be that complex. When the page loads, the main request to ETEngine is for all of the gqueries needed to render the chart, dashboard, and mini-line things in the sidebar.

If I then add two more charts, refresh the page and look at the requests made:

1. The first request specifies only the gqueries needed for the first chart, and not for the second and third. 2. The second request has gqueries for the first and second charts, but not the third chart.
3. The third request asks for the gquery results for the first, second, and third.
4. And so on...

My *guess* is that the code is rendering the page with one chart, and then adding the others one-at-a-time in much the same was a user would when clicking "Add chart". That would explain why each additional chart results in an extra request.

Instead, it needs to figure out all the charts which are going to be rendered and the gqueries needed, and do this all with the first request.

> the failing of the merit order charts when it happens, is. 

I dare say even that's not a huge deal. When the second request arrives, the chart renders correctly. Needs a fix, but it's not a showstopper.

**Comment by grdw** [comment]
> Instead, it needs to figure out all the charts which are going to be rendered and the gqueries needed, and do this in the first (and only) request.

I'm a bit lost. I get the problem but I can't really seem to figure out where all of this is happening in the code. But if I have to go down the rabbit hole:

1. So in [here](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/models/gquery.coffee#L3) the `gqueries` are added to the `GqueryList`. 
2. The `window.gqueries` object is used [here](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/app.coffee#L116). 
3. `call_api` is used in relevant looking piece of coffescript [here](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/models/chart_list.coffee#L100). 
4. And the `app.coffee` calls `load_charts` [here](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/app.coffee#L84)

I get it! 👍 

Damn, that `load` method in `ChartList` looks like it needs some heavy maintenance. I'm going to take a look.
