### ISSUE TITLE
Sankey present year is still called 2012, should that be 2013?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2139]
![image](https://cloud.githubusercontent.com/assets/104830/15544128/ee0152a8-2297-11e6-8e71-179d77a156bc.png)

**Comment by jorisberkhout** [comment]
Good catch, @dennisschoenmakers . Simply renaming it to `Sankey energy flow diagram 2013` wouldn't do the trick, as we also support datasets that have present year 2012 (France, Germany, Spain, Poland, United Kingdom and NL2012) as well as present year 2011 (EU-27). Also, updating the chart title is apparently easily overlooked, given that the Dutch title of this chart still reads `Sankey diagram van energiegebruik 2010` :smile:

Could we instead rename this chart to `Sankey energy flow diagram (present)` and `Sankey diagram van energiegebruik (huidig)`? Any objections, @dennisschoenmakers , @AlexanderWirtz or @ChaelKruip ?

**Comment by jorisberkhout** [comment]
Okay, after comparison with the titles of the "Present / Future energy imports" charts, I decided to rename the Sankeys to:

- Sankey diagram of present energy flows
- Sankey diagram of future energy flows
- Sankey diagram van huidig energiegebruik
- Sankey diagram van toekomstig energiegebruik

PR is on its way to @dennisschoenmakers  as soon as GitHub collaborates!

**Comment by dennisschoenmakers** [comment]
> Could we instead rename this chart to Sankey energy flow diagram (present) and Sankey diagram van energiegebruik (huidig)? 

:+1: good idea.
