### ISSUE TITLE
LOLE information should also mention batteries

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2142]
![image](https://cloud.githubusercontent.com/assets/104830/15608151/262a2e3a-2418-11e6-9be3-109334cc0541.png)

**Comment by jorisberkhout** [comment]
I'll pick this up as part of the LOLE / blackout hours update.

**Comment by jorisberkhout** [comment]
I updated the text on the Beta server. Closing this issue. Please re-open if you feel a better explanation is needer.
