### ISSUE TITLE
Artefact in heat network mekko

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2143]
@antw do you see why there would be this artefact in this mekko?
<img width="1081" alt="energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_" src="https://cloud.githubusercontent.com/assets/1303760/15651443/fe8615e6-267f-11e6-867f-1ffd51b7181e.png">

**Comment by antw** [comment]
> do you see why there would be this artefact in this mekko?

I don't; never seen that before. It looks to be the same size as the coloured boxes in the legend. Perhaps there's a series without a label?

I'd need to be able to try the chart for myself to find out why it happens.

**Comment by ChaelKruip** [comment]
> I'd need to be able to try the chart for myself to find out why it happens.

You can choose it from the chart-picker on BETA. It's number 174

**Comment by antw** [comment]
TY! Apparently it represents "Central waste CHP Supply", but it *is* the exact same size as one of the legend boxes, which is suspicious.

**Comment by ChaelKruip** [comment]
> Apparently it represents "Central waste CHP Supply", but it is the exact same size as one of the legend boxes, which is suspicious.

Also, "Central waste CHP Supply" does not occur in the legend!

**Comment by antw** [comment]
[33727e8a renamed the series](https://github.com/quintel/etmodel/commit/33727e8ad28078113bb2dadde574c70121655bd5#diff-32cb85897a25fc58cf0760e4ac9ec7a1R60) `energy_power_supercritical_waste_mix_in_heat_network_mekko` to "Central waste CHP"; a name which was already used by `energy_chp_supercritical_waste_mix_in_heat_network_mekko`.

Apparently the Mekko chart doesn't like it if two series have the same name. 😐

**Comment by ChaelKruip** [comment]
> It turns out that the Mekko chart doesn't like it if two series have the same name

Oops! 😊

**Comment by ChaelKruip** [comment]
@AlexanderWirtz can you resolve this doubling?

**Comment by AlexanderWirtz** [comment]
@ChaelKruipi made a misatke when I mentioned in  #2137 that the converter `energy_power_supercritical_waste_mix` was a CHP that should be renamed. Turns out that CHP already exists. Hence the doubling. Oops, silly me.

For some odd reason the power plant is also connected to the `heat_network` with zero heat efficiency. This is odd and it should not be connected to it. The series can then be removed altogether from the heat network mekko.

**Comment by AlexanderWirtz** [comment]
assigned back to @ChaelKruip

**Comment by jorisberkhout** [comment]
@ChaelKruip , has this been resolved?

**Comment by ChaelKruip** [comment]
> @ChaelKruip , has this been resolved?

I think so yes. Closing.
