### ISSUE TITLE
The ETM should show the land-use of technologies somewhere

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2144]
For example, wind and solar farms.

**Comment by ChaelKruip** [comment]
@jorisberkhout @AlexanderWirtz @dennisschoenmakers what do you think?

**Comment by dennisschoenmakers** [comment]
Agree!

**Comment by AlexanderWirtz** [comment]
Agree

For wind they are shown in the 'Targets' pop-up table. Something like that could be included for solar farms. A table could also be added to the chart picker, although by now there is so much here that few people will in it.

A separate slide for land use in 'Supply' would be the coolest, but most time-consuming option.
