### ISSUE TITLE
International aviation and navigation should be included in the ETM

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2146]
I think it would be good to discuss strategies about how to find the relevant numbers and how to include them in the interface.

Including @dennisschoenmakers

**Comment by AlexanderWirtz** [comment]
Finding the numbers will not be terribly difficult for a good intern. The basic numbers are in the Energy Balance. For the interface we need to provide options for increasing or decreasing volume per option and some more choices for fuel. @RobTerwel probably already has some sources for ocean-faring ships. 
We should probably keep this topic one of the options for Tess. 

I mostly expect that if we add this to the graph, we will need to subsequently exclude it from charts and dashboard items, as this is not officially part of a country's energy use. That will mean some fall-out similar to FCE, except that we will do this for all countries. 

We may want to introduce (yet another) switch allowing people to turn this on or off, with the default option being off.

**Comment by AlexanderWirtz** [comment]
Is this one we could give to Rene Benders to pass on to students? At least the research part?

**Comment by ChaelKruip** [comment]
> Is this one we could give to Rene Benders to pass on to students? At least the research part?

Good idea! I'll make a short description of possible projects for him.

**Comment by jorisberkhout** [comment]
Closing as this is now available on the Beta server.
