### ISSUE TITLE
The industry should be able to use geothermal heat 

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2147]
@AlexanderWirtz can you shed some light on why we have not included this?

The argument that geothermal heat is mainly for low temperatures will likely not hold in a future where bio-feedstock is used more and more in industrial processes.

**Comment by AlexanderWirtz** [comment]
Indeed it should be included, but ...
I remember why we backed away from this earlier: it really requires some kind of assessment of how much heat demand of what temperature levels each industry sector has. This is not impossible to do, but tricky especially for other countries, as you need access to experts. It also requires several T-levels for steam and hot water and graph changes. 

Geothermal heat can provide heat from the lowest segment of heat demand (<130 degrees C or so). It can be 'upgraded' to temperature up to about 250-300 degrees C, using industrial heat pumps or steam (re)compression, but it cannot be used to meet demand for higher temperatures, which in the NL are a significant chunk of heat demand.

For other sectors it is fine to suggest that geothermal heat can in theory meet all heat demand. In Industry, this is simply not true. Also in a future with more bio-baed industry. @RobTerwel has done some excellent research into this and concluded that petro-based chemistry is not always a bad idea, as long as refining oil can be done economically without any fuel output, i.e. all the fractions are somehow used as feedstock.

**Comment by AlexanderWirtz** [comment]
Also... 
Let's wait and see what suggestions @RobTerwel and John have for changes to the Industry section. 
We could try something über simplified where users can indicate how much will be bio-based and how much petro-based.

**Comment by AlexanderWirtz** [comment]
This should be included on quintel.com as an interesting topic for energy interns. I should be doable now, what with newly available data from RVO on the availability of heat and geothermal potential. That leaves digging for information on the extent to which geothermal heat can supply part of industry's heat demand: supplying heat to an industrial heat pump which then upgrades it further, for example.

**Comment by michieldenhaan** [comment]
Closing, a slider for geothermal heat has been added to the central heat network, which can supply heat to several industry sub sectors
