### ISSUE TITLE
Idea for a new interface of the ETM

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2148]
Working on some Mekko charts, I had the following idea: what if we would visualise the _whole_ energy system of the ETM as two, coupled, interactive Mekko's (one for supply and one for demand). 

The Mekko's could be zoomable like in [this D3 example](http://mbostock.github.io/d3/talk/20111018/treemap.html):
![mbostock_github_io_d3_talk_20111018_treemap_html](https://cloud.githubusercontent.com/assets/1303760/15673019/6735c33e-2734-11e6-8312-c6df89dde3c8.png)

So, a sector could be a solid rectangle at the highest level but a lot of sub-rectangles (for subsectors, uses etc.) when zoomed in.

What would make this _really_ exciting in my opinion if the rectangles would be draggable with the mouse. So, a rectangle representing the heating demand for households could be dragged to become larger or smaller to signify increase or decrease of demand respectively. So, the Mekko's could be both the chart and the sliders in one!

Dragging mutually exclusive rectangles (slider groups) would leave their enclosing rectangle static but would change their relative share of the energy demand/supply.

Perhaps it would also be possible to re-shape such an interface to represent the 'energy functions' as used in the 'Energierapport'?

@dennisschoenmakers @jorisberkhout @AlexanderWirtz @antw @grdw @RobTerwel what do you think about this outlandish idea?

**Comment by grdw** [comment]
Sounds nice, like the idea! Just to clearify what do you mean by dragging? Would it be like, how I would make my current browser window smaller or bigger?

**Comment by ChaelKruip** [comment]
> Would it be like, how I would make my current browser window smaller or bigger?

Yes!

**Comment by AlexanderWirtz** [comment]
that's just f*ing awesome

**Comment by jorisberkhout** [comment]
I :heart: it!

**Comment by jorisberkhout** [comment]
And would be happy to help you out with working this out in more detail!
