### ISSUE TITLE
We would like to scale scaled scenario for ETMoses projects in regions

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2149]
The GEA and IABR projects are based on scaled scenarios for regions of the Netherlands (Gelderland and Groningen respectively). These scaled scenarios are being used to inform long-term decision making there. Currently, there are solid leads to continue our work in these regions using ETMoses. The idea is to model 'typical' neighborhoods or streets in the context of the energy systems set out in these scaled ETM scenarios.

In order to be able to do that we need to scale down the scaled-down scenarios a second time. Currently, the interface doesn't allow that, but I imagine there are more fundamental problems to this request.
A couple of things that come to mind:

- sectors that have already been excluded in the first scaling
- both `present` and `future` graphs that have been 'tweaked' in the scenario files

@antw what do you think, is this something that can be done? Please let me know if you have any questions. I realize this issue goes beyond the scope of etmodel.

Including @dennisschoenmakers @jorisberkhout @ChaelKruip

**Comment by antw** [comment]
ETEngine already supports this – including re-scaling the user input values (which, I'm guessing, covers the scenario file "tweaks") – so I don't expect this will require much work. We likely need to add the option to the settings menu and that's it.

> sectors that have already been excluded in the first scaling

Will the user be able to customise their exclusions when creating the re-scaled scenario, or should it be locked to the settings chosen in the original?

**Comment by AlexanderWirtz** [comment]
> We likely need to add the option to the settings menu and that's it.

Excellent. I assume you are quite busy working on ETMoses. Do you want me to take this up with @dennisschoenmakers and @ChaelKruip in terms of planning and priorities, or can you already give me an approximate idea if when this could be made available?

> Will the user be able to customise their exclusions when creating the re-scaled scenario, or should it be locked to the settings chosen in the original?

It makes sense to lock it to the settings chosen in the original

**Comment by antw** [comment]
I have made it so that the option is now visible in the menu. *For now*, the user is able to choose different sector excludes, but the scaling form *will* preselect the same excludes as the current scenario.

I want to disable all the sector checkboxes – since this would communicate to the user which settings will apply to their new scenario, without permitting changes – but ETEngine was disabling all three sectors when I did this. I'll get that resolved within a couple of days.

**Comment by AlexanderWirtz** [comment]
@antw when trying this today, I found that I could not uncheck any sectors when scaling. I understand from your last comment:
>For now, the user is able to choose different sector excludes, but the scaling form will preselect the same excludes as the current scenario.

that the user can choose to exclude sectors that had been included in the first scaling. Did I misunderstand?

I started from [this scenario](https://beta-pro.energytransitionmodel.com/scenarios/519784), which included all sectors. I now want to model an urban environment that is itself a part of this part of the Netherlands, so I want to exclude the agriculture and industry sectors from the newly scaled scenario. I cannot check or uncheck any of the boxes though. In fact, I notice that the energy sector is not checked, for some reason.

Can you tell me what is wrong?

![image](https://cloud.githubusercontent.com/assets/308563/17407217/c6330a8a-5a66-11e6-85a7-fbbc41fcf6fe.png)

**Comment by AlexanderWirtz** [comment]
It would be great to be able to use this feature in the upcoming project we are doing with ETMoses (ETM SA) in Groningen. That project will start in September.

Notifying @ChaelKruip

**Comment by antw** [comment]
Was this not what you wanted?

> It makes sense to lock it to the settings chosen in the original

When I wrote the original comment these checkboxes could in fact be changed by a visitor who wanted to re-scale a scenario. That was changed on [30th June](https://github.com/quintel/etmodel/commit/9e7637a3d0e72180f4886c7dfb62c8b995cfa640).

I can enable these checkboxes if desired?

> In fact, I notice that the energy sector is not checked, for some reason.

Should now be fixed.

**Comment by AlexanderWirtz** [comment]
> Was this not what you wanted?
I can enable these checkboxes if desired?

Thank you for looking at this promptly. I can see how my communication was unclear here. Yes, please enable those checkboxes that pertain to the sectors included in the original scaling effort. Needless to say, sectors that are no longer included in the original scaled scenario, cannot have enables checkboxes. 

Thanks!

**Comment by AlexanderWirtz** [comment]
notifying @DorinevanderVlies

**Comment by antw** [comment]
> Yes, please enable those checkboxes that pertain to the sectors included in the original scaling effort. Needless to say, sectors that are no longer included in the original scaled scenario, cannot have enabled checkboxes.

Got it; disabled sectors remain disabled, enabled sectors may be toggled by the visitor. This will be on beta momentarily.

**Comment by AlexanderWirtz** [comment]
Great! Thanks.
