### ISSUE TITLE
How should we determine the price of imported electricity?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2151]
Now that electricity import participates in the merit order calculation (see https://github.com/quintel/merit/issues/139), this pointed out some problems with the way we determine the hourly electricity price. This issue discusses several options to solve these problems and is intended to come to a decision on which one to implement. 

### Problems

Currently the hourly electricity price is determined by the marginal costs of the first plant not to have any load assigned. Before electricity import became part of the merit order calculation, this approach would hold until all dispatchable plants had load assigned; in that case the price would be set as `7.22` times the marginal costs of the most expensive plant. Now that import participates in the merit order, so does its price, which is artificially set to `999_999_999_999.99`, to make sure that it is always the last plant running. This means that just before you have to start using your import capacity, the electricity price becomes `999_999_999_999.99`. As soon as you start using your import capacity, the price however drops to `600`. (Could you explain why this is happening, @antw? I was expecting the price to increase to `7.22` times `999_999_999_999.99` 😕 ).

### Solutions

As pointed out in https://github.com/quintel/merit/pull/140 and references therein, the assumption that the electricity price is set by the first plant not to have any load assigned is invalid. This is fixed by https://github.com/quintel/merit/pull/140.

Solving the second problem is trickier and there are two solutions (courtesy of @ChaelKruip ):

1. We set the price of imported electricity to the price of the most expensive plant **plus** `1 EUR/MWh`. This means that import will be dynamically adjusted to be the most expensive option, but not artificially high. This is straightforward to implement, but has the downside that the price of imported electricity is set very implicitly.
2. We add a slider to the ETM which allows the user to set the price of imported electricity. This has the advantage that the price of imported electricity is set explicitly. Also setting the price to a low value means that you start importing electricity before all your own dispatchable plants have started running, which represents reality a lot better than the assumption that import is always the last resort. Downside is that this takes more time to implement and can have quite some impact on existing scenarios. (**And** in reality the price of imported electricity differs on an hourly basis, which we ignore with this implementation. But, as @ChaelKruip pointed out this could be a nice opportunity to sell a project).

Lengthy issue, but I would love to hear your opinion @AlexanderWirtz , @dennisschoenmakers , @ChaelKruip , @antw, in particular on if you prefer option 1 or 2.

**Comment by ChaelKruip** [comment]
I prefer option 2. I can help with the input statement etc. if you want.

**Comment by dennisschoenmakers** [comment]
I would prefer option 2 as well. A very good step into the right direction IMO.

**Comment by dennisschoenmakers** [comment]
> Could you explain why this is happening, @antw

It is already annotated in [merit](https://github.com/quintel/merit/blob/5afa92c854b6d4e8d5c754b6206c1148620a91d2/lib/merit/order.rb#L70-L73):

```Ruby
# Public: Returns the price for a certain moment in time. The price is
# determined by the 'price setting producer', or it is just the most
# expensive **installed** producer multiplied with a factor 7.22.
# If there is no dispatchable available, we just take 600.
#
# See https://github.com/quintel/merit/issues/66#issuecomment-12317794
# for the rationale of this factor 7.22

**Comment by jorisberkhout** [comment]
> `# If there is no dispatchable available, we just take 600.`

Thanks for the explanation @dennisschoenmakers . My confusion was caused by the fact that the `energy_interconnector_imported_electricity` is dispatchable (see [its node files](https://github.com/quintel/etsource/blob/master/nodes/energy/energy_interconnector_imported_electricity.converter.ad)). I now realise that import is a special case (see [merit](https://github.com/quintel/merit/blob/5afa92c854b6d4e8d5c754b6206c1148620a91d2/lib/merit/order.rb#L97-L103)).

**Comment by AlexanderWirtz** [comment]
I prefer option 1. Option 2 makes no real sense to me as it has little bearing on reality at all and has as its only redeeming quality that it is explicit. Why go from one incorrect static price to another? The interesting impact from imports is precisely that prices vary and that moments of surplus in a neighboring country are likely to coincide with such moments in your own. Assuming that prices are static at a certain level using a slider may look transparent, but a user learns nothing from it. It wil be like adding yet another power plant. 

To me option 1 seems like a better step up to the possibility of using an explicit price curve derived from a scenario for a neighboring country. In my opinion, that should be our ultimate aim, now that we are going for transparency and a more correct Merit Order calculation. Both 1 and 2 offer a similar sales opportunity in that respect. 

Perhaps you can explain the benefits of option 2 to me, because I really do not see them.

**Comment by ChaelKruip** [comment]
> The interesting impact from imports is precisely that prices vary and that moments of surplus in a neighboring country are likely to coincide with such moments in your own. 

Very true.

> It wil be like adding yet another power plant.

Exactly! But now the user will be able to choose *where* in the merit order import will happen. It allows you to `mimic` option 1 by setting the price equal to the most expensive plant (plus a bit) but the user can also choose to import 100% of the time by setting the price to 0 (as was basically the case in 2013 when we imported from Germany almost always).

> To me option 1 seems like a better step up to the possibility of using an explicit price curve derived from a scenario for a neighboring country. 

I don't see why... Can you elaborate?

> In my opinion, that should be our ultimate aim, now that we are going for transparency and a more correct Merit Order calculation
👍 

>  Both 1 and 2 offer a similar sales opportunity in that respect.

Except that option 1 does some magic 'under the hood' of the ETM which I think is both confusing and not very transparent. I dislike the fact that with option 1 the behaviour is always the same: import is the last resort.

**Comment by AlexanderWirtz** [comment]
Don't get me wrong. I don't like option 1 much either, but I am a little afraid we will be stuck with option 2 for a long time, despite the fact that is offers nothing realistic. Sure you can choose to do more or less importing, but according to a static criterium that has little bearing on the actual criteria that determine imports. 

The reason I like option 1 better is that it is a continuation of the currect incorrect approach and will stimulate us to actually fix that, rather than applying an incorrect and very visible and time-consuming fix that might give the impression we don't know what we are doing when it comes to modelling imports. 

Let's be clear: I understand and agree with the diagnosis and that it needs fixing. I'd rather go for a good fix than a partial and unsatisfying one.

**Comment by jorisberkhout** [comment]
As discussed with @AlexanderWirtz and @ChaelKruip earlier today, option 1 seems to be the better one in the end for the following reasons:

- Neither option 1 nor option 2 are ideal, but option 1 is closer to the current implementation
- Option 2 would require some careful thought on how to initialise the slider and how to set the slider caps
- In option 2 electricity import is also effected by the marginal costs of the other plants, as it is the relative prices that determine the merit order. These marginal costs can be changed by the user by changing the fuel and variable O&M costs. All in all the aforementioned makes the behaviour of the import cost slider very complex.

Once https://github.com/quintel/merit/pull/140 is merged, implementing option 1 would be relatively straightforward. In this pull request the hourly merit order price is set to the most expensive plant running at that hour. We would then have to set the price of import to the most expensive plant available plus `1 EUR/MWh` which would ensure that it is always the last one to switch on.

I will work this out in a bit more detail once I am back from my holidays (i.e. on 21 June).

**Comment by ChaelKruip** [comment]
> We would then have to set the price of import to the most expensive plant available plus 1 EUR/MWh which would ensure that it is always the last one to switch on.

We must also take care of the (pathological) case that the user has no dispatchable plants installed. In that case, there is no price setting plant. I think the price for import should be 1 EUR/MWh in that case.

**Comment by jorisberkhout** [comment]
As explained a few comments ago, we decided to go for option 1. The actionable part of this is described in https://github.com/quintel/merit/issues/143.

Closing this discussion issue.
