### ISSUE TITLE
BUG: Freeform is not working anymore?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2154]
I entered `10.000` in https://beta-moses.energytransitionmodel.com/testing_grounds/525/edit in business case:

![image](https://cloud.githubusercontent.com/assets/104830/16295753/da44d85a-3928-11e6-8dc5-89ebdaf627c5.png)

Then it hangs and keeps saying 'loading' forever:

![image](https://cloud.githubusercontent.com/assets/104830/16295772/fd202da2-3928-11e6-860c-f20c4f8887c4.png)

If I refresh, the `10.000` has disappeared:

![image](https://cloud.githubusercontent.com/assets/104830/16295788/0e377dac-3929-11e6-9c19-50f347ca456d.png)

**Comment by dennisschoenmakers** [comment]
Option: remove freeform all together, I never seen anybody use it.

**Comment by ChaelKruip** [comment]
> Option: remove freeform all together, I never seen anybody use it.

I don't think we should do that. It is our best answer for all not-modelled costs.

**Comment by dennisschoenmakers** [comment]
Assigned @grdw as discussed with @ChaelKruip

**Comment by grdw** [comment]
Eh, don't want to sound like a little know-it-all, but this issue is ETMoses related but currently in the ETModel repo.

**Comment by dennisschoenmakers** [comment]
> Eh, don't want to sound like a little know-it-all, but this issue is ETMoses related but currently lives in the ETModel repo.

Good point! My bad! New issue quintel/etmoses#1132
