### ISSUE TITLE
Ajax error handling: Something went wrong error in console is really non-descriptive

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2155]
Currently the `Merit order capacities and marginal costs` chart is not loading on `beta` and locally. There will be a separate issue for that. The only piece of information we receive in the console is ['Something went wrong error'](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/app.coffee#L124), which is obvious, I can see that. 

So it might help if it were a bit more descriptive. It's also weird that the textStatus is blank for the Ajax error.

**Comment by antw** [comment]
Normally this means something went wrong on ETEngine. The response from ETE should contain a useful description of what went wrong.

![screen shot 2016-06-23 at 11 15 03](https://cloud.githubusercontent.com/assets/4383/16299747/c2d16304-3933-11e6-9ccc-8413de49ce89.png)

**Comment by grdw** [comment]
> The response from ETE [..] 

How would I trigger that response, this would be grabbing the query from that `output_element` and checking in the console what goes wrong? 

> [..] should contain a useful description of what went wrong.

Ah, okay. I think it is really useful to 'forward' those messages in ETModel. Maybe not that specific but maybe we could also say, "Something went wrong; look in ETEngine for further details by performing this query in .."

**Comment by antw** [comment]
Sorry, I wasn't clear. Those messages *are* sent back to ETModel when the ETEngine action fails for some reason.

In this case, I opened ETModel and selected the "Merit order capacities" chart. An Ajax request was sent to ETEngine (`PUT api/v3/scenarios/:id`) which returned a 422 Unprocessable Entity status. The response body has `{ "errors": [] }` with a list of each error which occurred.

**Chrome:**

![screen shot 2016-06-23 at 11 26 14](https://cloud.githubusercontent.com/assets/4383/16299999/5680a712-3935-11e6-89f6-6f368292c424.png)

**Firefox:**

![screen shot 2016-06-23 at 11 27 35](https://cloud.githubusercontent.com/assets/4383/16300027/86dfdc98-3935-11e6-82ff-deefb6ae009d.png)

**Comment by grdw** [comment]
Yes it also does in Firefox. I'm just looking in the wrong tab .. 

<img width="1440" alt="screen shot 2016-06-23 at 12 55 24" src="https://cloud.githubusercontent.com/assets/2676542/16300743/c874d3be-3941-11e6-947d-ba7c12ab35a5.png">

**Comment by grdw** [comment]
I'll close the issue 👍
