### ISSUE TITLE
 Merit order capacities and marginal costs is currently broken on beta and locally

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2156]
The problem probably recides in ETEngine / ETSource due to the Ajax error that is being thrown. I'll research it a bit better when time is there.

**Comment by jorisberkhout** [comment]
Well spotted @grdw. I looked into it a found that the chart is expecting the old Gqueries in which all solar PV and wind turbines where grouped. 

```
0:"Gquery merit_order_solar_pv_capacity_in_merit_order_table does not exist"
1:"Gquery merit_order_solar_pv_operating_costs_in_merit_order_table does not exist"
2:"Gquery merit_order_solar_pv_load_factor_in_merit_order_table does not exist"
3:"Gquery merit_order_wind_turbines_capacity_in_merit_order_table does not exist"
4:"Gquery merit_order_wind_turbines_operating_costs_in_merit_order_table does not exist"
5:"Gquery merit_order_wind_turbines_load_factor_in_merit_order_table does not exist"
```

The commits in https://github.com/quintel/etsource/pull/1127 split up solar PV in three different types and the same is true for wind turbines. Somehow the chart does not know about these changes.

Can you shine some light on this, @ChaelKruip ?

**Comment by jorisberkhout** [comment]
Could you look into this, @grdw ? This chart is a bit to custom for me :)

**Comment by grdw** [comment]
Yes I now understand why the keys mattered that much ;)

**Comment by ChaelKruip** [comment]
What needs to happen here is that all types of wind turbines and solar panels need to be shown separately in chart too. The gqueries mentioned above have been replaced with more specific ones.

**Comment by jorisberkhout** [comment]
Thanks, I realised that too and am fixing it.

**Comment by grdw** [comment]
Hmm I seem to be missing some GQL statements which was the reason why the chart didn't function instantly when replacing the keys. 

> quintel/etsource#1127

I see that there's a `load_factor` missing for all `solar_radiation` related carriers which is now causing the whole chart to break. Could I put those in ETSource or? It doesn't look to complicated from a distance, or is there a reason why there are no `load_factor` gql-statements for `solar_radiation`?

**Comment by ChaelKruip** [comment]
> It doesn't look to complicated from a distance, or is there a reason why there are no load_factor gql-statements for solar_radiation?

The reason is that I forgot to put them there 😞

**Comment by grdw** [comment]
<img width="610" alt="screen shot 2016-06-27 at 10 14 45" src="https://cloud.githubusercontent.com/assets/2676542/16372989/02b9827a-3c50-11e6-9d51-278f832591ae.png">

Next problem, the names of the solar raditiaton related output are 'too long' for this chart. Instead of 4 columns, we could switch to three?

<img width="628" alt="screen shot 2016-06-27 at 10 18 05" src="https://cloud.githubusercontent.com/assets/2676542/16373047/7bd98880-3c50-11e6-958d-0ad84f90b659.png">

I do need to check what happens if one of the blocks becomes really high. Any idea how to test that?

**Comment by grdw** [comment]
<img width="615" alt="screen shot 2016-06-27 at 10 40 00" src="https://cloud.githubusercontent.com/assets/2676542/16373646/8737ff9c-3c53-11e6-91fc-46c085bded3f.png">

@jorisberkhout and I decided to move the legend to the bottom of the chart for now. Eventhough I also really like filtering the legend items, I think this can be done at some later moment in time.
