### ISSUE TITLE
Animation bug 'Merit order capacities and marginal costs' chart on production ETModel

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2157]
When you load said chart, hold the mouse in front of the chart: The bar will stop in front of where your mouse is, resulting in this:

<img width="613" alt="screen shot 2016-06-23 at 12 10 44" src="https://cloud.githubusercontent.com/assets/2676542/16299629/8d139982-393b-11e6-9d8c-99a542d98e29.png">

You can resolve it by reloading the page and moving your mousepoint somewhere else.

*How to fix:*
Add the mouse-over event listener to the bars, when the animation is done and not when the animation is still pending.

**Comment by jorisberkhout** [comment]
@grdw , what is the status of this issue?

**Comment by grdw** [comment]
I have the feeling that I probably patched this with some other issue ... but I sort of forgot to close this issue. One moment.

**Comment by grdw** [comment]
Fixed by https://github.com/quintel/etmodel/commit/e07216b78a9f90d62b6b21a445db5e8b70edeab4
