### ISSUE TITLE
Migrate static data in the merit order chart preferably to ETSource + output_element_series

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2159]
I'm talking ofcourse about these [lines of code](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/d3/merit_order.coffee#L4-L30). 

Somehow it feels a bit weird that these lines are over there. I would love to see those in an `output_element_serie`. The thing is than that the gql's responsible for handling the return data needs to return three values, the `capacity`, the `operating_costs` and the `load_factor` (in the correct order, or as a Hash?).

There are 25 keys, so times three 75 gql's? Seems a bit like a lot that can be cleaned up. 😅

**Comment by jorisberkhout** [comment]
@grdw , what is the status of this issue?

**Comment by grdw** [comment]
Fixed by https://github.com/quintel/etmodel/commit/ea3a67a1d652b2757b400896a7f7ee372bca059c
