### ISSUE TITLE
Make merit order table the table view of the merit order chart

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2162]
Why are these two separate entities? They both use the same GQL statements and data. 

I'm just wondering if it wouldn't be cleaner and more in-line of ETModel's default workflow to make the Merit order table the table-view of the merit order chart.

**Comment by ChaelKruip** [comment]
> Why are these two separate entities?

They are used quite differently. The table informs people about the difference in full load hours of the plants. The chart shows the installed capacities and marginal costs. Both are very much complementary and often shown side by side.

**Comment by grdw** [comment]
> The table informs people about the difference in full load hours of the plants
> Both are very much complementary and often shown side by side.

Agreed. Still was hoping to somehow get rid of one the static tables someday, but thanks for explaining. There's already a separate issue about [the static tables](https://github.com/quintel/etmodel/issues/2015). Therefor closing this issue.
