### ISSUE TITLE
Add a dashboard item for amount of excess hours

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2170]
We need another dashboard_item/constraint for the amount of excess hours as oppossed to the amount of blackout hours.

As specified by @jorisberkhout the following two producers must not take part in the calculation of the total amount of excess hours constraint calculation needed in merit:

````ruby
[:energy_flexibility_curtailment_electricity,
:energy_export_electricity]
````

So GQL wise:

````ruby
- query =
  V(
    GRAPH(),
    total_number_of_excess_events([
      :energy_flexibility_curtailment_electricity,
      :energy_export_electricity
    ])
  )
````

Todo:
- [x] Write (well basically copy) the GQL
- [x] Write a method for `total_number_of_excess_events` in ETEngine in the `graph_api.rb`
- [x] Expand `excess.rb` in Merit gem with the `total_number_of_excess_events`
- [x] Create another constraint in ETModel

**Comment by jorisberkhout** [comment]
As requested by John. This dashboard item should display the total number of hours per year when there is excess electricity. The method calculating this dashboard item should include the flexibility options:

- Batteries
- Electric vehicles
- Power-to-gas
- Power-to-heat

The method should **NOT** include export and curtailment. The effect of including the flexibility options is that the number of excess hours will go down when the user starts adding flexibility options to his scenario.

This dashboard item should be part of the `Energy imports` group and when you click on it, it should show the `Duration of excess events` chart. The title of the dashboard item should be `Excess electricity` and `Elektriciteitsoverschotten` and its units should be `h/yr` and `u/j`.

Picking this up as part of the `lole calculation update` milestone as @grdw indicated that it is very little work.

**Comment by grdw** [comment]
Relevant pull requests:

- ETSource: https://github.com/quintel/etsource/pull/1144
- Merit: https://github.com/quintel/merit/pull/147
- ETModel: https://github.com/quintel/etmodel/pull/2176

- ETEngine: First merit needs to be updated for this to work :)

**Comment by grdw** [comment]
Closed by all the PR's mentioned in the comment above
