### ISSUE TITLE
Could we show the delta instead of an arrow when dashboard items change value?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2173]
Now that we are talking about re-designing the dashboard (see https://github.com/quintel/etmodel/issues/2172) I would also like to bring up something that has bothered me for a long time: the arrows for the dashboard items confuse me sometimes (also see #1127).

I have two problems with the current arrows: 
- It is aligned with the right side of the 'item-box' which often brings it closer to the next item which I find confusing:
  <img width="450" alt="energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_" src="https://cloud.githubusercontent.com/assets/1303760/16546934/1d1fc11e-415b-11e6-907d-81c158c20033.png">
- It communicates a change direction but not a quantity

The first issue might be simple to fix (by aligning differently etc.). The second issue not. 

Suggestion: why don't we show the amount of change as well as the sign of that change like this:
<img width="418" alt="energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_" src="https://cloud.githubusercontent.com/assets/1303760/16546970/549f960e-415c-11e6-9193-29fccd8fb646.png">

I'm interested in other ideas and opinions! @antw @grdw @RobTerwel @dennisschoenmakers @AlexanderWirtz @jorisberkhout @DorinevanderVlies

**Comment by jorisberkhout** [comment]
I like the suggestion to show a delta!

**Comment by DorinevanderVlies** [comment]
I agree that showing the delta is a good enhancement!

**Comment by RobTerwel** [comment]
I like the idea of adding a quantitative delta as well. However, I think we should be careful to not have a visual 'number overkill' for less quantitatively minded users. Perhaps we could add a settings option somewhere along the lines of "toggle quantitative/qualitative dashboard item change", where the user can switch from a qualitative arrow-based change indication system to a quantitative percentage-based change indication system.
