### ISSUE TITLE
Move merit order slide to a more prominent position in the front-end

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2174]
As suggested by John, I am trying to find a place in the spotlights for the new merit order charts (`Electricity production per hour`, `Electricity price per hour`, `Use of flexibility options per hour` and `Duration of excess electricity events`). The obvious place would be as a default chart of some slide. The problem is that there is only one slide about the merit order and a few related to flexibility, but all of them have an appropriate default chart that I don't want to replace.

Combined with the fact that I think that the merit order slide is quite hidden in the front-end of the ETM the aforementioned problem led me to the following solution:
- rename the `Flexibility` tab to `Balance` (`Balans` in Dutch)
- move the `Merit order` sidebar item to this `Balance` tab as the first sidebar item under this tab
- add some more slides to the `Merit order` sidebar item in which we can explain the various aspects of the merit order calculation
- make the new merit order charts the default charts for these slides
- rename the `Flexibility options` sidebar item to `Flexibility`

Below is a screenshot of what this would look like. Below the screenshot is a table with details on the slides that need to be added, their contents and the default charts for each slide.

<img width="1440" alt="screen shot 2016-07-14 at 13 51 14" src="https://cloud.githubusercontent.com/assets/4669028/16838830/c3cb13ec-49cb-11e6-8b12-fdb4dc6d60e5.png">

| Sidebar item | Slide name | Content | Default chart |
| --- | --- | --- | --- |
| Merit order | Merit order | General description merit order | `Electricity production per hour` |
| Merit order | Merit order positions | Details on marginal costs and merit order position | `Merit order table` |
| Merit order | Merit order price | Details on how merit order price is calculated | `Electricity price per hour` |
| Flexibility | Excess electricity | Definition of excess electricity | `Duration of excess electricity events` |
| Flexibility | Order of flexibility options | Short description of order | `Use of flexibility options per hour` |
| Flexibility | Storage in batteries |  | `Use of excess electricity` |
| Flexibility | Storage in electric vehicles |  | `Use of excess electricity` |
| Flexibility | Conversion to heat |  | `Use of excess electricity` |
| Flexibility | Conversion to gas |  | `Use of excess electricity` |
| Flexibility | Demand increase |  | `Use of flexibility options per hour` |
| Flexibility | Wind power production cost |  | `Energy Storage` |

This means that the table `Flexibility options` will no longer be a default chart for any slide. I further suggest to leave the sidebar item `Import/Export` and the sliders therein unchanged.

I have discussed this idea with most of you in person, but would like to hear if you agree with this more detailed plan, @AlexanderWirtz , @dennisschoenmakers , @ChaelKruip , @antw , @grdw, @RobTerwel and @DorinevanderVlies .

If there are no objections, I can implemented this next week.

**Comment by jorisberkhout** [comment]
I would also like to take this opportunity to write the texts for the new merit order charts.

**Comment by AlexanderWirtz** [comment]
I like the proposed changes a lot. I am a little hesitant on the name `Balance` as to me it is not immediately clear. Also, all these options are ultimately about `electricity` items and this is not reflected in the name. I wonder if 'Electricity balance' or something like that is clearer.

Could you please weigh in too, @dennisschoenmakers, @DorinevanderVlies , @antw , @grdw , @RobTerwel , @ChaelKruip ?

**Comment by jorisberkhout** [comment]
As discussed with @AlexanderWirtz , we decided to rename the `Balance` tab to `Electricity balance` to make clear that this tab is only about electricity.

Also we decided to move the `Electricity balance` tab below `Supply` for two reasons:
- the need for electricity balance is a result of demand ánd supply
- demand and supply are about all carriers and by placing electricity balance in between we might suggest that they are only about electricity

**Comment by jorisberkhout** [comment]
I have executed the above plan with two exceptions:
- I have left the `Flexibility options` table as the default chart for the `Flexibility -> Order of flexibility options` slide
- I have made the `Flexibility options` table the default chart for the `Import/Export -> Interconnector capacity` slide

I will start writing the texts for the new slides.

**Comment by RobTerwel** [comment]
I like the new term `Electricity balance`, because it is both concrete and encompassing. I also think the new location (below `Supply`) is a good idea.

**Comment by jorisberkhout** [comment]
I have updated the texts as well. Will close this issue and send an email asking for you feedback on these changes as well as a few more regarding the merit order charts.
