### ISSUE TITLE
Scaling of scenario (excluding industry) results in server errors

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2182]
For example the scenario with ID: 564164 is invalid.

![energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_](https://cloud.githubusercontent.com/assets/1303760/17553449/16ae9026-5f06-11e6-9e9c-b68f9bafc57f.png)

**Comment by ChaelKruip** [comment]
Including @RobTerwel

**Comment by ChaelKruip** [comment]
I'm also very curious what would happen if I include the industry in a scaled scenario 😈

**Comment by jorisberkhout** [comment]
> I'm also very curious what would happen if I include the industry in a scaled scenario 😈

That seems to work fine.

**Comment by antw** [comment]
For that scenario, the following inputs calculate a default ("start") value of `NaN` – "not a number" – which is typically the result of dividing zero by zero:

* industry_chemicals_aggregated_other_burner_coal_share
* industry_chemicals_aggregated_other_burner_crude_oil_share
* industry_chemicals_aggregated_other_burner_network_gas_share
* industry_chemicals_aggregated_other_burner_wood_pellets_share
* industry_final_demand_for_chemical_aggregated_other_steam_hot_water_share

**Comment by RobTerwel** [comment]
>industry_chemicals_aggregated_other_burner_coal_share
industry_chemicals_aggregated_other_burner_crude_oil_share
industry_chemicals_aggregated_other_burner_network_gas_share
industry_chemicals_aggregated_other_burner_wood_pellets_share
industry_final_demand_for_chemical_aggregated_other_steam_hot_water_share

These sliders should only appear in non-NL datasets. One sec.

**Comment by antw** [comment]
> These sliders should only appear in non-NL datasets. One sec.

Ah, I see. ETEngine calculates the start values for *all* inputs/sliders, regardless of the dataset; it doesn't know which sliders are used by which dataset (that is ETModel's responsibility).

It would be nice if these inputs could handle that gracefully, but alternatively we could do what we do with `NaN`s in gquery results: automatically convert the value to zero.

**Comment by RobTerwel** [comment]
> Ah, I see. ETEngine calculates the start values for all inputs/sliders, regardless of the dataset; it doesn't know which sliders are used by which dataset (that is ETModel's responsibility).

Indeed; I just set these sliders to be dependent on `has_aggregated_chemical_industry`, but that doesn't solve this.

**Comment by antw** [comment]
It's not too pretty, but the start value queries ([such as this one](https://github.com/quintel/etsource/blob/master/gqueries/input_elements/start_value/heat_production_share_from_coal_in_aggregated_chemical_industry.gql)) could be changed to something like this:

```ruby
IF(
  EQUAL(AREA('area_code'), 'nl'),
  0.0,
  (
    V(industry_chemicals_other_burner_coal,output_of_heat_carriers) +
    V(industry_chemicals_fertilizers_burner_coal,output_of_heat_carriers)
  ) / (
    V(industry_useful_demand_for_chemical_other_useable_heat,preset_demand) +
    V(industry_useful_demand_for_chemical_fertilizers_useable_heat,preset_demand)
  )
)
```

**Comment by RobTerwel** [comment]
>It's not too pretty, but the start value queries (such as this one) could be changed to something like this

Yes, that should do the job. I can do this later today.
