### ISSUE TITLE
Translation missing for mekko_of_final_demand_in_industry

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2184]
<img width="644" alt="screen shot 2016-08-11 at 16 16 45" src="https://cloud.githubusercontent.com/assets/4669028/17591581/151570e8-5fdf-11e6-90a2-c73c30d1b1c4.png">

**Comment by RobTerwel** [comment]
I set the chart to be `always_hidden`; this is an old chart that is no longer in use. @jorisberkhout (or perhaps @ChaelKruip ), shall I delete the corresponding `output_elements` and `output_elements_series` on the ETEngine database on staging or would we like to keep these entries?

**Comment by jorisberkhout** [comment]
I am in favour of removing this chart entirely. What do you think, @ChaelKruip ?

**Comment by ChaelKruip** [comment]
I am in favour of removing this chart entirely. What do you think, @ChaelKruip ?

👍 Fine by me!

**Comment by RobTerwel** [comment]
> I am in favour of removing this chart entirely.

This has already been done for a while now, closing.
