### ISSUE TITLE
OVERVIEW: Merging space heating and hot water combi technologies

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2185]
# Problem

Currently, combi-technologies which can do space heating (SH) and hot watert (HW) technologies occur twice in the ETM:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/17664808/f619fbbc-62f6-11e6-9e12-201ca990201a.png)
and again:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/17664826/090d0cc8-62f7-11e6-90a9-901f4e69a2bb.png)

There are several issue with this:
- It is confusing for the user
- It leads to inconsistencies (users can easily set the sliders differently in SH and HW)
- We need to correct for the double counting of investment and O&M costs
- The technologies are exported twice to the Stakeholder Analysis (resulting in more confusion, double counting etc.)
# Proposed solutions
## Front-end

It would be nice if we could somehow merge the SH and HW technologies into a big share-group where the combi-technologies only showing up once:

![20141209_topology_interface_v1_key](https://cloud.githubusercontent.com/assets/1303760/17664799/e2d61b26-62f6-11e6-909f-2f7b9f0fe4e9.png)

There are several technical issues to overcome here as we currently cannot balance two slider groups with overlap (@antw do you see possibilities to make this happen?)
## Back-end

I propose to simplify the ETM by using only one version of each combi technology in the graph. We will make a small energetic error (as the COPs and efficiencies are not equal for SH and HW) but it will simplify the graph and analyses considerably I think and will remove the need for correcting double counting of costs in ETM and ETM-SA.

NOTE: The front-end simplification can also be done keeping the two combi options. 

@antw @jorisberkhout @dennisschoenmakers @AlexanderWirtz @RobTerwel @DorinevanderVlies I'm curious about your thoughts.

**Comment by DorinevanderVlies** [comment]
> There are several issue with this:

> It is confusing for the user
> It leads to inconsistencies (users can easily set the sliders differently in SH and HW)
> We need to correct for the double counting of investment and O&M costs
> The technologies are exported twice to the Stakeholder Analysis (resulting in more confusion, double counting etc.)

I agree

If I understand you correctly you are proposing one slide for "Space heating and hot water". I think that's a good solution.

### Front-end
Currently there is one chart for *Final energy demand for heating in residences* and one for *Final energy demand for hot water in residences*.

I think there are two options: 

- Show both charts when slides are opened
- Add a new chart: *Final energy demand for heating and hot water in residences*.
<p>
 Personally I am in favour of the second option.

**Comment by antw** [comment]
> There are several technical issues to overcome here as we currently cannot balance two slider groups with overlap (@antw do you see possibilities to make this happen?)

I imagine it is possible, but it would be a considerable amount of work. Off the top of my head:

* Inputs have a `share_group` attribute which optionally associates the input with a *single* share group. This must be changed.

* The [front-end slider "balancer" in the ETM](https://github.com/quintel/etmodel/blob/a9ffd2cf095f22d262e814e22dbd3d174015ed38/app/assets/javascripts/lib/models/input_element_balancer.js), and [the auto-balancer in ETEngine](https://github.com/quintel/osmosis) would both require significant changes to permit inputs to be balanced while belonging to multiple groups.

**Comment by marliekeverweij** [comment]
This is done during the heat project 🙂
