### ISSUE TITLE
Add a slider to increase the capacity of P2G

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2191]
Related to #2189 and #2190 , John suggested to add a slider that allows the user to increase the capacity of P2G plants by up to ten times to be able to deal with more excess electricity.

Closely linked to https://github.com/quintel/etmodel/issues/2078.

**Comment by RobTerwel** [comment]
If we add industrial scale P2G units as a technology (as we plan to do when modelling the fertilizer industry in more detail), these sliders might not be necessary.

**Comment by jorisberkhout** [comment]
As discussed with John, we are closing this in favour of the solution proposed in https://github.com/quintel/etmodel/issues/2078.
