### ISSUE TITLE
Some typo's in Biomass C)2 slides

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2195]
I found a few minor typo's and failed translations in the texts:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/17895043/0d42b6ac-694c-11e6-8b0d-4b73b31a896d.png)

**Comment by DorinevanderVlies** [comment]
Thanks for the attentiveness!

Closed by b2bcff8
