### ISSUE TITLE
Error when loading some fuel production charts

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2197]
Natural gas for example:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/17922967/078aae0e-69e2-11e6-919f-5c7000f7a4fe.png)

**Comment by antw** [comment]
Do you have the ID for the scenario in which this occurs? The dashboard resembles a default NL/2050 scenario, but the error is not happening for me, before or after changing the values of the "Alternative fuels" sliders.

**Comment by ChaelKruip** [comment]
I just found out that you can reproduce this by opening the different Fuel production slides in rapid succession. Any fresh NL 2050 scenario should do this.
