### ISSUE TITLE
What to do with the charts 'final demand in industry' and 'heat production in industry'?

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2198]
In splitting the industry in https://github.com/quintel/etsource/pull/1147 we obliterated the old `metal`/`chemical`/`other` distinction and only show in the front-end the 'end-nodes' of those categories. 

This means that the following two bezier charts are currently no longer functional (i.e., queries are not collectively exhaustive or refer to converters which no longer exist):
- final demand in industry
- heat production in industry

I've therefore set these charts to `always_hidden`. Would we like to rewrite the queries behind these charts or just get rid of them altogether? FYI, we already have a FD mekko for the entire industry, but no industrial heat production charts as of yet.

@jorisberkhout @ChaelKruip @AlexanderWirtz , I'm curious about your thoughts.

**Comment by ChaelKruip** [comment]
>  just get rid of them altogether

👍

**Comment by jorisberkhout** [comment]
> just get rid of them altogether

Sounds good to me!

**Comment by AlexanderWirtz** [comment]
👍

**Comment by RobTerwel** [comment]
> just get rid of them altogether

Done, closing.
