### ISSUE TITLE
Expected demand check returns unexpected value

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2199]
In a clean nl scenario there is an expected demand check which fails: the demand of the node `energy_export_oil_products` is 0 PJ, but the `expected_demand` is 1 kJ. However, what is surprising here is that the `expected_demand` itself is not what one would expect. In this case, one would expect a demand of 0 PJ, as the node is the child of an `inversed_flexible` edge which is connected to a node without excess energy. 

This construction (a distribution node connected to production, flexible import, a demand-initialised child and inversed_flexible export) occurs in several parts of the graph, and this hasn't caused any trouble so far.

@antw , could you perhaps look into why the `expected_demand` method returns a non-zero value for this converter?

**Comment by antw** [comment]
1kJ is *tiny*, I'm 99% sure this is just a floating-point rounding error in the Atlas+Refinery calculations, from which the expected demand value comes.

![industry_locally_available_crude_oil_non_energetic_ finished](https://cloud.githubusercontent.com/assets/4383/18090240/a7e521bc-6ebb-11e6-9db0-7430ba44ce83.png)

However, Atlas+Refinery use `Rational` numbers (which support arbitrary precision), so this is not supposed to happen.

I'll keep this open as I'd like to figure out how this is occurring, but I don't think it's anything to worry about.

```
ETSource: 1bc67af
Atlas:    ce45457
Refinery: 58c1138
```

**Comment by RobTerwel** [comment]
After a few ETSource commits this does start to look even more like a rounding error:

![screen shot 2016-08-31 at 17 51 19](https://cloud.githubusercontent.com/assets/14106387/18135868/abd811ce-6fa3-11e6-966a-3e1b7f6071fb.png)

**Comment by ChaelKruip** [comment]
Closing.
