### ISSUE TITLE
Biocoal should not give the same CO2 emissions as coal

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2203]
As can be seen in [this](https://beta-pro.energytransitionmodel.com/scenarios/572355) scenario.

**Comment by ChaelKruip** [comment]
It looks like `industry_chp_ultra_supercritical_coal` is not changing its input when the bio-coal slider is touched.

**Comment by ChaelKruip** [comment]
The central coal heater seems to be suffering from the same problem.

**Comment by jorisberkhout** [comment]
I have compared the converters that are connected to `energy_distribution_torrified_biomass_pellets` (see list below) to the ones whose inputs are updated by the input statement behind the biocoal slider (the ones for which the box is ticked). 
Indeed `industry_chp_ultra_supercritical_coal` is one of converters that is not updated by the biocoal input statement.

Shall I add `industry_chp_ultra_supercritical_coal` to the input statement, @ChaelKruip and @AlexanderWirtz ? Same question for `energy_steel_hisarna_transformation_coal`?

- [ ] `industry_chp_ultra_supercritical_coal`
- [x] `energy_power_ultra_supercritical_coal`
- [x] `energy_power_combined_cycle_ccs_coal`
- [x] `energy_power_ultra_supercritical_oxyfuel_ccs_lignite`
- [x] `energy_power_ultra_supercritical_lignite`
- [x] `energy_power_supercritical_coal`
- [x] `energy_chp_ultra_supercritical_cofiring_coal`
- [ ] `energy_steel_hisarna_transformation_coal`
- [x] `energy_power_combined_cycle_coal`
- [x] `energy_power_ultra_supercritical_ccs_coal`
- [x] `energy_power_ultra_supercritical_cofiring_coal`
- [x] `energy_chp_ultra_supercritical_coal`

**Comment by jorisberkhout** [comment]
While looking into this I also found that the following converters are connected to the `energy_distribution_coal` but **not** to `energy_distribution_torrified_biomass_pellets`. The way I understand it, this means that it is impossible to make these processes greener by running them on torrified biomass pallets. One of these converter is the central coal heater that @ChaelKruip mentioned above.

Should we connect the following converters to the `energy_distribution_torrified_biomass_pellets` and include them in the biocoal input statement, @ChaelKruip and @AlexanderWirtz ?

- [ ] `energy_cokesoven_transformation_coal`
- [ ] `energy_heater_for_heat_network_coal`
- [ ] `energy_steel_blastfurnace_bat_transformation_cokes`
- [ ] `energy_steel_blastfurnace_current_transformation_cokes`

**Comment by ChaelKruip** [comment]
I think yes and yes 👍

**Comment by ChaelKruip** [comment]
Although I think that the _cokes converters might be exceptions right @AlexanderWirtz?

**Comment by jorisberkhout** [comment]
I just discussed this issue with @AlexanderWirtz with the following conclusions:
- `industry_chp_ultra_supercritical_coal` should indeed not respond to the biocoal slider (i.e. things should remain the way it is). Such an industrial CHP has a separate supply chain from the energy industry. If you want to make the industrial CHP's more renewable you can replace them by e.g. gas CHP's and feed them with greengas
- `energy_heater_for_heat_network_coal` should be connected to `energy_distribution_torrified_biomass_pellets` and be included in the input statement behind the biocoal slider
- `energy_steel_hisarna_transformation_coal` has its own slider to make it more renewable (`Biomass in cyclone furnace`). It does not make sense to run any of the other steel ovens on biomass. Making the steel sector more renewable therefore involves switching to cyclone furnaces and using biomass in these furnaces

Do you agree with the above conclusions, @ChaelKruip ? If so, I can make the changes to the ETM (i.e. the changes required for point 2).

**Comment by ChaelKruip** [comment]
> Do you agree with the above conclusions, @ChaelKruip?

Yes 👍
