### ISSUE TITLE
Make it possible to give a subheader name to every slider group within a slide

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2207]
### Background

Right now it's possible to provide a general subheader name for all sliders within a slide, as well as group subheader name which appears above all slider groups. With the recent industry overhaul, besides the 'size' slider we present two groups of sliders on most slides:

- `efficiency improvement`
- `heat production`

with the group subheader name:

- `share`

![screen shot 2016-09-02 at 15 17 32](https://cloud.githubusercontent.com/assets/14106387/18206711/210c3bfc-7128-11e6-9fe6-4263662f4bde.png)

### Problem

This subheader/group implementation in the front end can be seen below (for refineries)

![image](https://cloud.githubusercontent.com/assets/14106387/18206412/e9c4bc06-7126-11e6-8c44-c542b71bc8f5.png)

The problem here, is that the group subheader name is `share` is the name we want for the group `heat production`, but not quite the name we want for the group `efficiency improvement`. That group should receive the subheader name `%/year`. 

### Possible solution

A possible solution is one in which we can specify the group subheader name for each slider group independently. @antw , would this require much effort, and if so, do you see another way in which we could do this?

Including @jorisberkhout

**Comment by jorisberkhout** [comment]
Added to `Deploy September 2016` milestone.

**Comment by antw** [comment]
In the [en_etm.yml](https://github.com/quintel/etmodel/blob/3438fa2dcbb13a78dc101f04503e17e8d533d97d/config/locales/en_etm.yml#L144-L157) and [nl_etm.yml](https://github.com/quintel/etmodel/blob/3438fa2dcbb13a78dc101f04503e17e8d533d97d/config/locales/nl_etm.yml#L144-L158) local files, you may now optionally define a custom label for a slider group by adding a key which matches the name of the slider "interface group" field. For example, to assign a custom label for sliders in the "efficiency" group:

<img width="638" alt="screen shot 2016-09-07 at 10 56 32" src="https://cloud.githubusercontent.com/assets/4383/18307803/e45a3acc-74e9-11e6-8af4-f779fbb9069d.png">

... you would add:

```yml
subheaders:
  efficiency: "%/year"
```

I've [already done this for efficiency](https://github.com/quintel/etmodel/commit/3438fa2dcbb13a78dc101f04503e17e8d533d97d?diff=unified#diff-c4b4ee48207548c8caf90977a85a9c74).

<img width="451" alt="screen shot 2016-09-07 at 11 00 13" src="https://cloud.githubusercontent.com/assets/4383/18307908/4653e44e-74ea-11e6-82bb-3aa17c5ce0f6.png">

If there is no matching translation it will – as before – fall back to using the slide's "Group sub header":

<img width="493" alt="screen shot 2016-09-07 at 11 01 19" src="https://cloud.githubusercontent.com/assets/4383/18307953/782197c8-74ea-11e6-80ea-ba9652894852.png">
