### ISSUE TITLE
New industry features are still lacking some explanatory texts

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#2209]
Explanatory texts are missing for the following:

- *all* new industry charts
- *all* new 'size' sliders
- the p2g for industry slider

**Comment by DorinevanderVlies** [comment]
I have added texts to:

> all new industry charts
> all new 'size' sliders

Still open:

> the p2g for industry slider

**Comment by jorisberkhout** [comment]
> the p2g for industry slider

@AlexanderWirtz kindly added some text to this slider. Closing.
