### ISSUE TITLE
How to convey the effect of P2G for industry on CO2-emissions to the user?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2211]
This is a tricky one, so I'm looking for some help with this.

Assume you have a scenario with a lot of excess electricity. One of the things you can now do with this excess electricity is turn it into hydrogen for industry and use this hydrogen as input for the Haber-Bosch process. This 'renewably generated' hydrogen then replaces the hydrogen that would otherwise be generated by steam-methane-reforming, which produces quite some (non-energetic) CO2.

As John pointed out, it is not very obvious from the ETM that applying P2G for industry is beneficial. The investment costs are high, and there is no effect on the CO2-emissions in the dashboard as these only show energetic CO2-emissions.

I'm wondering if and how we should it more obvious to the user that using P2G for industry is beneficial to your CO2-emissions. Should we somehow include it in the FCE module?

Any thoughts @AlexanderWirtz , @ChaelKruip or @DorinevanderVlies ?

**Comment by AlexanderWirtz** [comment]
This is a bit of a conundrum. The ETM was designed to show energetic effects. This is not one. If we start including charts about things like non-energetic CO2-emissions, we need to also include other non-energetic emissions from cement production etc. We probably don't want to venture in that direction as we then need to start explaining that there is non-energetic energy demand that can cause CO2 emissions and also chemical processes that are not non-energetic demand, but also cause emissions etc etc.

I think the short-term solution needs to be to explain the particular non-energetic natural gas demand on the appropriate slide (Industry - Fertilizer) and to point people's attention to the industry chart that shows non-energetic energy demand, and how the amount of non-energetic natural gas demand decreases. The chart itself should explain that some non-energetic energy demand leads directly to CO2-emissions and other non-energetic energy demand does not.

No matter how you do this, it's complicated and it's a bitch.

**Comment by jorisberkhout** [comment]
Thanks for you input, @AlexanderWirtz .

> No matter how you do this, it's complicated and it's a bitch.

Ok, I'll use that argument to convince John 😉 

Removing the milestone as this is not deploy critical.

**Comment by michieldenhaan** [comment]
This is now fixed: https://github.com/quintel/etengine/pull/1134. This non-energetic CO2 is included, so using P2G for industry reduces emissions
