### ISSUE TITLE
Duration of excess electricity events chart should not be dependent on order of flexibility options

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2217]
## Problem
If, in total, enough flexibility options are installed there should be no excess events, regardless of the order of the flexibility options. This is currently not the case.

## Example

This [scenario](https://beta-pro.energytransitionmodel.com/scenarios/575062) is based on the Urgenda scenario, all flexibility options are maximally used.

If P2G for industry or transport has highest priority there is no excess electricity. So, the P2G capacity is sufficient.

However, if I change the order of priority and put P2P EV or households is put on on top excess events do occur. This seems unrealistic as the P2G still has enough capacity to take care of the excess events that are left after the capacity of P2P is used.

### P2G for industry on top (no excess events)
![image](https://cloud.githubusercontent.com/assets/19907658/18355188/9c343644-75e8-11e6-8ea3-1648618a530d.png)

### P2G for transport on top (no excess events)
![image](https://cloud.githubusercontent.com/assets/19907658/18355211/b86f8854-75e8-11e6-8035-058b9a96e506.png)

### Storage in EV's on top (1199 h excess)
![image](https://cloud.githubusercontent.com/assets/19907658/18355243/d226e7d8-75e8-11e6-9d16-7dd4b8a683e7.png)

### Storage in batteries on top (1271 h excess)
![image](https://cloud.githubusercontent.com/assets/19907658/18355297/f47eeb96-75e8-11e6-845b-ece9a4ca646c.png)

**Comment by jorisberkhout** [comment]
Nice catch @DorinevanderVlies . This is a tricky issue. I did exactly as you did (i.e. open the Urgenda scenario, install all flexibility options and play around with the order). Like you I was expecting no excess electricity to be left.

I did one more thing. I put `Storage in batteries` on top and downloaded the merit order load curves and performed some analysis on these load curves. 
- I looked at the load curve for batteries and noticed that for a few hours the batteries take all excess electricity, then suddenly only very little for one hour after which it start taking all excess electricity for a few more hours. In other words the battery is not fully charged yet when it takes very little excess electricity (below is an excerpt from my analysis)

<img width="90" alt="screen shot 2016-09-13 at 19 04 26" src="https://cloud.githubusercontent.com/assets/4669028/18483583/e9e08834-79e4-11e6-85bf-f813af8b74d3.png">

- I then added all electricity production and subtracted the demand and the flexibility options and counted for how much hours the result is larger than zero (in fact larger then `1e-5` to avoid numerical issues). This resulted in around 900 hours even though there is enough installed flexibility capacity to consume this.
 
It feels like something is not completely right in the merit calculation. Would you have time to look into this, @antw ? Let me know if I did not explain the issue clear enough.
