### ISSUE TITLE
Bio-footprint illustration fro Belgium only takes Flanders into account

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2219]
I am currently creating a dataset for Belgium. On the etmodel side of things I can re-use some of the stuff that we made a long time ago when we still had a model for Belgium.

There is an issue with the maps that we use to display the bio-footprint. As can be seen below, this illustration only takes Flanders into account, where it should take the entire Belgium into account. Could you adjust the maps such that the entire Belgium is coloured grey or blue depending on the bio-footprint in the scenario, @grdw ? You can find the maps [here] (https://github.com/quintel/etmodel/tree/master/app/assets/images/maps).

You can check if it works by checking out the `be_2013` branch on etmodel and etsource. You might need to clear your cache in order to make the model for Belgium visible on your local machine.
 
<img width="91" alt="screen shot 2016-09-08 at 21 50 06" src="https://cloud.githubusercontent.com/assets/4669028/18364428/8ff41d6a-760e-11e6-84bd-7d5faace99dc.png">

**Comment by grdw** [comment]
@dennisschoenmakers do you know where the location of these images are in the Dropbox folder? Or where I can find these images online?

**Comment by dennisschoenmakers** [comment]
> @dennisschoenmakers do you know the location of these images in the Dropbox folder? Or where I can find these images online?

you can find them here: https://github.com/quintel/etmodel/tree/master/app/assets/images/maps. No vector images on Dropbox that I know of.

**Comment by grdw** [comment]
👍 thanks, I'll color the pixels by hand. 

> No vector images on Dropbox that I know of.

Good to know.

**Comment by grdw** [comment]
Can anyone @antw or @dennisschoenmakers suggest me a tool where I could do this with? I currently use gimp but I can't get color the edges correctly. I can color the grey spaces the same type of blue but I can't make the edges a bit darker type of blue (at least not easily). Is there a tool for OSX (preferably open source / freeware) that let's me do it quiet easily.

**Comment by grdw** [comment]
Turns out it was possible with Gimp. 👍 I just didn't really know how until now. Also @jorisberkhout pointed out that the other countries are one shade of blue and one shade of grey. I assumed that - since the borders of the Beglium country had a different shade of blue / grey that these borders would have to be colored aswell. Which was not the case.

**Comment by jorisberkhout** [comment]
Closed by #2245 .
