### ISSUE TITLE
CO2 of oil and derivatives in export query in CO2-Mekko leads to errors

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2224]
In [this commit](https://github.com/quintel/etsource/commit/aa32e4258ab2ecab747a33cb36635209232de380),  the [oil products export node](https://github.com/quintel/etsource/blob/master/nodes/energy/energy_export_oil_products.ad) was created. Now there are two export nodes with crude_oil as input.

This results in problems in [this query](https://github.com/quintel/etsource/blob/master/gqueries/general/co2/primary_co2_of_oil_and_derivatives_in_export.gql#L6-L8) because it expects a value and now gets an array [value_1, value_2].

I quickly tried to fix this with a SUM:
```
IF(
  SUM(V(G(energy_export).select {|node| node.input_slots.detect { |slot| slot.carrier.crude_oil? }}, primary_demand)) > 0.0,
  SUM(V(G(energy_export).select {|node| node.input_slots.detect { |slot| slot.carrier.crude_oil? }}, "crude_oil_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)")),
  0.0
)
```
 But this does not work because the division "demand / primary_demand" is performed for both nodes *before* the summation leading to: SUM([ value_1, NaN] ) = NaN.

@antw I think I need your help to solve this properly.

Another solution direction would be to either:
* create a new carrier: `oil_products` to distinguish from `crude_oil`
* merge the `energy_export_oil_products `node with the energy_export_crude_oil`

@jorisberkhout @antw what do you think?

**Comment by ChaelKruip** [comment]
Perhaps as a short-term solution we can hide this chart?

**Comment by antw** [comment]
```ruby
crude_oil      = G(energy_export).select {|node| node.query.input_of_crude_oil > 0 };
gasoline       = G(energy_export).select {|node| node.query.input_of_gasoline > 0 };
diesel         = G(energy_export).select {|node| node.query.input_of_diesel > 0 };
lpg            = G(energy_export).select {|node| node.query.input_of_lpg > 0 };
kerosene       = G(energy_export).select {|node| node.query.input_of_kerosene > 0 };
heavy_fuel_oil = G(energy_export).select {|node| node.query.input_of_heavy_fuel_oil > 0 };

EACH(
  V(crude_oil, "crude_oil_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)"),
  V(gasoline, "gasoline_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)"),
  V(diesel, "diesel_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)"),
  V(lpg, "lpg_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)"),
  V(kerosene, "kerosene_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)"),
  V(heavy_fuel_oil, "heavy_fuel_oil_input_conversion * primary_co2_emission * (1.0 - demand / primary_demand)"),
)
```
