### ISSUE TITLE
FCE charts should show more info in mouse-over

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2225]
The elements in the chart react to mouse-over (become slightly larger) but no values are shown:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/18434950/939f067a-78f0-11e6-9a64-056eab87b3b4.png)

Curiously the red rectangles do not seem to react to mouse-over!

**Comment by antw** [comment]
The FCE charts use the old charts library (jqPlot); in fact I think they might be the last to still use this library. Therefore, adding tooltips consistent with the other charts might be easier said than done.

How about after the deploy we look at replacing this with a D3 version, and see if that allows us to remove jqPlot from ETModel?

**Comment by jorisberkhout** [comment]
> How about after the deploy we look at replacing this with a D3 version

Sounds like a plan, removing the milestone!

**Comment by marliekeverweij** [comment]
FCE is not used anymore in the ETM and supposed to be deleted (see #2986). So closing this issue :)
