### ISSUE TITLE
FCE sliders should be consistent with time-curves

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2226]
It is weird that you can make a scenario for 2050 where you import all your gas from abroad (because the time-curve dictates this):
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/18435122/a0ab863a-78f1-11e6-9f4a-ff72cf4983c0.png)

 but your FCE sliders still indicate that the gas mix is very Dutch:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/18435087/7351b0ce-78f1-11e6-954c-bad1a370e1a7.png)

**Comment by jorisberkhout** [comment]
Removing the milestone as this is not deploy critical.

Shall we pick this up as part of a broader discussion on how to deal with time curves in the ETM, see https://github.com/quintel/etsource/issues/418 ?

**Comment by marliekeverweij** [comment]
FCE is not used anymore in the ETM and supposed to be deleted (see https://github.com/quintel/etmodel/issues/2986). So closing this issue :)
