### ISSUE TITLE
 Investments for heat and electricity production chart fails to load

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2227]
Gives a 442 currently on beta; my guess - a renamed/missing gquery. 

![screen shot 2016-09-12 at 14 06 07](https://cloud.githubusercontent.com/assets/2676542/18435204/2e1bbda0-78f2-11e6-82f2-53b49a5fefd0.png)

Also after loading one failed chart, I am not able to select another chart.

**Comment by jorisberkhout** [comment]
Closing due to duplicate #2218.
