### ISSUE TITLE
Should we rename the 'Supply >> Hydrogen production' page to 'H2 for transport'?

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2229]
This name doesn't seem to correspond to what the page is about (H2 for transport). Hydrogen is also produced by P2G under 'Electricity balance >> Flexibility >> Conversion to gas'.
Also note #2228 concerning the textual content of these slides/pages.

Let me know if you agree: @dennisschoenmakers @jorisberkhout @ChaelKruip

**Comment by ChaelKruip** [comment]
> Let me know if you agree: 

👍
