### ISSUE TITLE
Display issues with Mekko's

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2231]
The primary demand Mekko has some weird display issues:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/18439071/1c3f9338-7904-11e6-8b7b-1e5d64dd178d.png)
* Small grey squares (related to LNG) appear in the Mekko (we did see this issue before right @antw?)
* Lines are plotted but don't point to labels (this disappears when reloading)
* The "Export and Curtailment" label only displays "Curtailment"

When "zooming" the chart:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/18439195/a1814e56-7904-11e6-9f1f-b6c73f85c8d5.png)
* The legend does not display any colors
* The legend is not space nicely (only column)

**Comment by grdw** [comment]
I always forget to test that "full-screen" button... I'm fixing it as we speak.

**Comment by ChaelKruip** [comment]
> Small grey squares (related to LNG) appear in the Mekko (we did see this issue before right @antw?)

Fixed this myself. I forgot to remove some old series in the database 😊

**Comment by ChaelKruip** [comment]
Now the primary demand Mekko has a weird almost horizontal line:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/18439541/1ec7c45c-7906-11e6-9b2d-71cededb1403.png)

**Comment by ChaelKruip** [comment]
With one Mekko everything seems fine:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/18464960/56d4b54c-7994-11e6-9355-f4ae4ce8c4f2.png)

Adding another one:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/18464974/73540b5a-7994-11e6-9094-a8090f7244e7.png)

**Comment by grdw** [comment]
That's part of the same problem and will be fixed when #2232 will be merged
