### ISSUE TITLE
All the things that can be displayed better in this pop-up

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2233]
![screen shot 2016-09-12 at 17 14 13](https://cloud.githubusercontent.com/assets/2676542/18441198/65a6dda8-790c-11e6-8925-663e6c51408c.png)
- The Y-axis is way to far to the right
- The button text is too small
- There are funny spaces of white between the text and the dropdown-text
- The color between the legend and the chart is not the same
- The link and the share button need to be aligned

**Comment by grdw** [comment]
@jorisberkhout re-assign at will

**Comment by jorisberkhout** [comment]
Assigning @grdw . Not urgent.
