### ISSUE TITLE
Remove the 'button'? On bottom of the chart info pop-up

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2236]
When clicking the question mark icon on a chart there is a weird button-looking thing on the bottom of the pop-up.

![screen shot 2016-09-13 at 11 14 41](https://cloud.githubusercontent.com/assets/2676542/18468252/61742550-79a3-11e6-95e9-9b9685605aad.png)

"Chart-info" looks like a button but it isn't. It's just text dangling on a pop-up which doesn't really serve a purpose (unless somebody, knows the actual purpose?). My suggestion here would be to completely remove it since it doesn't really add anything to the pop-up other than stating the obvious.

**Comment by grdw** [comment]
@jorisberkhout re-assign at will

**Comment by jorisberkhout** [comment]
Assigning @grdw . Not urgent.
