### ISSUE TITLE
Add sliders to change the investment costs in flexibility technologies

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2237]
This is a follow-up of https://github.com/quintel/etmodel/issues/2208.

As noted by @RobTerwel , the sidebar item, slide and sliders are already there. We need to add the ETSource side of things.

**Comment by jorisberkhout** [comment]
Assigning @marliekeverweij .

**Comment by jorisberkhout** [comment]
@marliekeverweij , what is the status of this? I noticed that part of this is on the Beta server, but not all of it.

**Comment by marliekeverweij** [comment]
I have added power-to-kerosene to the costs section. I have also made the sliders work that were already made by Rob but still hided in the admin (household batteries, power-to-heat industry and power-to-gas transport).

But I have not done more! Should cost-sliders for **all** flexibility technologies be made?
(Also text and tooltips should be added still...)
