### ISSUE TITLE
Can we auto-lock charts when adding them?

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2239]
This is a bit of a "I'm a lazy developer" issue. But I catch myself doing the following a lot:
1. add a chart
2. refresh the browser
3. I SHOULD HAVE LOCKED THE CHART
4. NOOOOOOOOOOO

Little too much drama here but it would be cool if the chart would lock itself automatically somehow. This is a really really really nice to have.

**Comment by ChaelKruip** [comment]
>  it would be cool if the chart would lock itself automatically somehow. 

Do you suggest that this 'locking' only applies to when the same page is refreshed? Locking charts automatically would be really annoying in the normal ETM work-flow: I open the model, go to another section, and another.... WOW! I have a lot of charts in my window! 😄

**Comment by grdw** [comment]
> I open the model, go to another section, and another.... WOW! I have a lot of charts in my window!

Switching section does not append a new chart or does it? Or does it append a new one once a chart is locked?

**Comment by ChaelKruip** [comment]
> Switching section does not append a new chart or does it? Or does it append a new one once a chart is locked?

You can answer all these questions by using the [Energy Transition Model](https://pro.energytransitionmodel.com/). It's free! 😜 

More seriously: No, it does not append a new chart indeed but it will not show any other chart either. So, after you lock the first one, that would be the only chart you see.

**Comment by grdw** [comment]
Closing issue as it is no longer relevant
