### ISSUE TITLE
Duplicate chart-name 'Primary energy use'

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2240]
![screen shot 2016-09-13 at 16 56 52](https://cloud.githubusercontent.com/assets/2676542/18478859/18de676c-79d3-11e6-8555-67d60adf7e5c.png)

**Comment by jorisberkhout** [comment]
Assigning @TessColijn .

**Comment by TessColijn** [comment]
@jorisberkhout would "Primary energy allocation by source" be an appropriate title for the following chart:

![image](https://cloud.githubusercontent.com/assets/22587085/19354811/57fe34ac-9168-11e6-9a9d-e052baeab094.png)

**Comment by jorisberkhout** [comment]
Looking at these charts made me realise that there is a discrepancy between the total primary energy use for both charts. I did a quick check and found that this discrepancy is explained completely by the fact that export and curtailment are taken into account differently in the primary energy use bar chart. I see two options to resolve this, but would like to hear @ChaelKruip on this as well as he has been working on https://github.com/quintel/etmodel/issues/2110.

Option 1: Remove the primary energy use bar chart as it is a bit boring and all information shown in it is contained in the primary energy use mekko.
Option 2: Fix the primary energy use bar chart to be in line with the mekko and keep both. In that case I would rename the primary energy mekko to `primary energy use per sector`

**Comment by ChaelKruip** [comment]
> Option 1: Remove the primary energy use bar chart as it is a bit boring and all information shown in it is contained in the primary energy use mekko.

I like this option. We then use the mekko as the default right?

**Comment by TessColijn** [comment]
I just checked on the beta model and neither of the two charts is used as a default on any of the slides. I will remove the bar chart. @jorisberkhout do you still want to rename the mekko?

**Comment by ChaelKruip** [comment]
> I just checked on the beta model and neither of the two charts is used as a default on any of the slides. 

But the bar chart is the default pop-up for the energy use dashboard item. We changed that to be the Mekko on Beta BTW.

**Comment by TessColijn** [comment]
I have hidden the bar chart and Chael has changed the default chart for the Energy Use dashboard to the mekko. @jorisberkhout can we close this issue?

**Comment by jorisberkhout** [comment]
Yes, nice work guys. Closing.
