### ISSUE TITLE
How can there be fewer 'excess events' when demand is reduced?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2243]
1. I build 100.000 offshore wind mills

![image](https://cloud.githubusercontent.com/assets/104830/18479022/b70bb732-79d3-11e6-90bc-c14b78a417e4.png)

2. I reduce energy demand by a) cut population in half, b) demolish all old houses, and reduce new houses to 0.1 million.

![image](https://cloud.githubusercontent.com/assets/104830/18479121/168d4892-79d4-11e6-962e-d144568c12ee.png)

**Comment by ChaelKruip** [comment]
I think the answer to that question is that peaks in the wind profile that earlier where counted as multiple events are now part of a longer single event.

**Comment by jorisberkhout** [comment]
> I think the answer to that question is that peaks in the wind profile that earlier where counted as multiple events are now part of a longer single event.

I fully agree with @ChaelKruip . This is supported by the fact that the dashboard item showing the **total** number of excess hours does increase.

Closing this issue. Re-open if you disagree with the explanation.
