### ISSUE TITLE
'Bookkeeping' of flexibility charts needs to be improved

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2244]
As discussed in https://github.com/quintel/etmodel/issues/2214, the numbers in the flexibility charts do not always add up to the same value. The total value varies by about +/- 5%, which needs to be fixed. Potential causes for this issue are:
- [ ] losses in the HV network
- [ ] ...

**Comment by ChaelKruip** [comment]
Would it be an idea to add the loss on the HV network tot the 'loss' category in the table?
