### ISSUE TITLE
Duration of excess events chart is hard to interpret 

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2246]
After discussions with @dennisschoenmakers I believe we could improve the readability of the chart which currently shows number of events vertically and minimum duration horizontally:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/18503048/25bf757e-7a5b-11e6-9d89-9a3d4164e9f5.png)

The main issue is that the surface area underneath the chart does not have an intuitive interpretation. If you would, for example, dramatically decrease the demand for electricity you can 'merge' 30 separate one hour excess events into one big event of 30 hours (see https://github.com/quintel/etmodel/issues/2243). 

This would result in the leftmost bar on the left shrinking (by 30!) and the rightmost bar growing (by one!). The chart changes qualitatively to this shape:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/18504610/773a96e2-7a63-11e6-8d0b-c5d8982bc4fd.png)

Perhaps it would be more intuitive to plot the _number of hours_ vertically instead of the number of events. 

Also, most people have trouble understanding the cumulative aspect of the bins (i.e., that the first bin also includes the events of the second bin etc.). Perhaps distinct bins (i.e., one hour or shorter, one to two hours, two to three hours, etc.) give a clearer image. (I know that I have argued for the cumulative bins in the past).

Curious about your opinions @jorisberkhout @DorinevanderVlies @dennisschoenmakers @AlexanderWirtz @antw @grdw

**Comment by AlexanderWirtz** [comment]
> Perhaps it would be more intuitive to plot the number of hours vertically instead of the number of events.

I do not see how this would work with binning. How do we bin the events on the x-axis meaningfully?

>Also, most people have trouble understanding the cumulative aspect of the bins (i.e., that the first bin also includes the events of the second bin etc.). Perhaps distinct bins (i.e., one hour or shorter, one to two hours, two to three hours, etc.) give a clearer image.

If we keep the x-axis the same, I agree that distinct binning would be easier. Still, histograms are quite hard for most people to interpret.

**Comment by dennisschoenmakers** [comment]
I think plotting the (sum of the) number of hours vertically rather
than the number of events would be much more informative yes!

I am not so sure about cummulative or not horizontally. Perhaps we
want to try both and see how that works out?

**Comment by DorinevanderVlies** [comment]
Using a non cumulative chart might also work.

Instead of "minimum duration" the x-axis will be "duration".
The x-axis runs from 0 to longest duration with steps of, for example, one hour.
On the y-axis the total events with that duration will be plotted.
