### ISSUE TITLE
Mekko charts III: The Return Of The Overlap - Browser compatability

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2247]
One thing to test: browser compatibility... 

*Chrome/Safari* 😄 
![screen shot 2016-09-14 at 11 40 06](https://cloud.githubusercontent.com/assets/2676542/18507606/54a08e80-7a71-11e6-94a1-4b81f566c576.png)

*Firefox 48.0.1* 😢 
![screen shot 2016-09-14 at 11 41 25](https://cloud.githubusercontent.com/assets/2676542/18507608/54c2a7f4-7a71-11e6-8e7c-2899b70df1d3.png)

~~I think the Firefox thing has to do with [this PR](https://github.com/quintel/etmodel/pull/2168) because I checked out some commits from way back when and it started working again... it's a bit odd.~~

*IE9*
![screen shot 2016-09-14 at 11 48 45](https://cloud.githubusercontent.com/assets/2676542/18507670/9406b824-7a71-11e6-86ff-0084469935ac.png)

Returns a D3 error

*IE11, Edge* 

Are a bit untesteable on a localhost machine due to CORS errors with localhost.

**Comment by jorisberkhout** [comment]
Hmm, this is deploy-critical as the ETM freezes on IE9 when you open a mekko. @grdw is looking into this. Do you have any ideas, @antw ?

**Comment by grdw** [comment]
I managed to fix Firefox problems 👍 

IE9 is up next.

**Comment by grdw** [comment]
I'm close though. The problem is in the `fitHeightToLabels()` method. I'm sort of commenting out lines and adding them back in again to see what causes the `D3` error.

**Comment by antw** [comment]
> IE11, Edge

IE11 and Edge both look fine on my Windows machine.

I don't have IE9 available. I can get it, but probably not soon enough to be any help. 😬

**Comment by antw** [comment]
>  The problem is in the fitHeightToLabels() method.

Perhaps `fitHeightToLabels: ->` needs to be `fitHeightToLabels: =>` (fat arrow) for IE9?

**Comment by grdw** [comment]
No, it's specificly in this [line](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/d3/mekko.coffee#L295) that it breaks ... now I need to figure out the details 😅

**Comment by grdw** [comment]
I see why. Appereantly IE9 doesn't know how to select a `[object SVGSVGElement]`. Which causes an argument error on the side of D3. I think that's what [somebody at D#](https://github.com/d3/d3/issues/851) already found out.

So I guess we would have to this with `setAttribute` (it fixes the problem): 

````javascript
// Instead of...
d3.select(real_svg).style('height', g_height + transform)
// ... we'd use:
real_svg.setAttribute('height', g_height + transform)
````

**Comment by antw** [comment]
> So I guess we would have to this with setAttribute (it fixes the problem):

That's probably better anyway. :+1:

**Comment by grdw** [comment]
![screen shot 2016-09-14 at 12 23 16](https://cloud.githubusercontent.com/assets/2676542/18508811/0dbc0d64-7a76-11e6-9af7-bb2b180de83f.png)

It does suck at wrapping the labels though... but it fits.
