### ISSUE TITLE
IABR scaled scenario has new industry sectors. How does this work?

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2251]
The [IABR 2035 scenario](https://pro.energytransitionmodel.com/scenarios/291793) for north-eastern Groningen has changed quite a bit post-deploy. Admittedly, I hadn't tested in on beta (as I was too lazy to migrate it there from the live server). I probably should have, but decided to open this issue regardless to raise some questions as to what has actually happened.

The image below shows that the IABR scenario now has fertilizer industry. I had foolishly assumed the default for scaled scenario's would be to keep the same industrial subsectors we used to have:
- Steel, aluminium and other metals
- Chemical
- Other industry

rather than give the scaled scenario's all new subsectors. In my particular case, there should be **no (real) refinery, fertilizer or paper industry.** There is food industry and Central ICT (data center), but I don't feel like digging up their actual energy demands for now. 

I have a nagging feeling in the back of my skull that I will need to completely update the industrial energy demand anyway, as the demands have been scaled from a completely different graph. So even keeping only the original industrial subsectors would have caused demand in these (now smaller) subsectors to be smaller in any scaled scenario.

**Questions**
1. Am I correct in assuming the energy demands for the fertilizer industry are simply the result of scaling from the Dutch numbers by the usual factor? This energy demand used to reside in the chemical industry sector, so that has presumably become smaller in the scaled scenario, correct?
2. Where did the energy demand by the refineries use to reside before we split up industry?  
3. How do I exclude the unwanted subsectors?
4. I see a lot of new input statements in the scenario table `user_values` on the database. How have these been generated?

![image](https://cloud.githubusercontent.com/assets/308563/18512365/19d38092-7a89-11e6-8706-a37b470fa8ce.png)

notifying @jorisberkhout @ChaelKruip and hell why not @RobTerwel

**Comment by RobTerwel** [comment]
> 1a: Am I correct in assuming the energy demands for the fertilizer industry are simply the result of scaling from the Dutch numbers by the usual factor? 

Correct. 

>1b: This energy demand used to reside in the chemical industry sector, so that has presumably become smaller in the scaled scenario, correct?

The totals should still be the same. The old sector slider settings were migrated to subsector slider settings, as follows

``
other -> refineries, food, paper
``
``
chemical -> other_chemical, fertilizers
``

E.g., if the old slider setting of the demand growth of the chemical industry was set to 2%/year, that number was converted to a relative size (for a 2050 scenario 1.02^(2050-2013)*100 = 208%) and the `other_chemical` and `fertilizers` size slider were then assigned this value.

> 2: Where did the energy demand by the refineries use to reside before we split up industry?

In the `other` industry.

> 3: How do I exclude the unwanted subsectors?

Set the `adjust_scaling` UD sliders of the respective subsectors to 0, so for instance <a href="https://github.com/quintel/etsource/blob/master/inputs/adjust_scaling/industry/industry_useful_demand_for_chemical_fertilizers_both.ad">this one<a/>.

> 4: I see a lot of new input statements in the scenario table user_values on the database. How have these been generated?

See answer 1b. Because sectors were split, all subsectors received the `user_values` of their parent sectors. Since there are multiple subsectors, there are now multiple `user_values`  as well.

Hope this helps!

**Comment by AlexanderWirtz** [comment]
@RobTerwel thanks for the quick reply. It helps a lot. Some of the more obvious answers I had figured out meanwhile, but it is reassuring to know you gave this some though.

Still, I wonder why dashboard values are so different if the total demands are still the same. the IABR 2035 scenario went from -95.0% CO2 emissions to -98.2% and from 88% renewable to 92%.  I had initially figured this had something to do with industry.

**Comment by RobTerwel** [comment]
> the IABR 2035 scenario went from -95.0% CO2 emissions to -98.2% and from 88% renewable to 92%. I had initially figured this had something to do with industry.

This could also very well have to do with the efficiency of the refinery, which is higher in the new industry than in the old industry. The refinery in an NL-based scenario now has the 'Dutch efficiency' rather than the 'European efficiency', which is quite a bit lower.

**Comment by AlexanderWirtz** [comment]
> This could also very well have to do with the efficiency of the refinery, which is higher in the new industry than in the old industry. 

Meaning the sum of the `Other` industry sector and refinery sector has effectively become smaller and hence the total in the scaled scenario as well? Makes sense.

**Comment by AlexanderWirtz** [comment]
UPDATE:

After comparing the IABR 2035 scenario on the production branch and the old production branch (thanks for that @ChaelKruip) I have concluded that fixing this scenario is not straightforward. 

The reason is that we used to have sliders to set the useful demand growth of `electricity`, `heat`, `oil and oil products (non energetic)`, `network gas (non energetic) `, `other carriers (non energetic)` in the chemical and other industry subsectors. These sliders and corresponding input statements have been replaced by input statements to scale the sectoral energy demand. We all knew this of course.

For tweaking industry in the IABR scenario I explicitly set non-energetic demand for oil products, network gas and other carriers. The reason was that I actually had some decent information on what these demands were. Now I can only scale the other chemical industry sector's total demand and the carriers' relative demands are completely different now.
 
**Conclusion**
For the other chemical and other industry sectors we should (re)create these input statements, so we can tweak carriers' relative demands in the total. This is likely to work in a messy way, since the total sector can also be scaled. That means two differnt input statements affect the demand for the same carrier in the same subsector in the graph.

Please advise and opine @RobTerwel @jorisberkhout and @ChaelKruip

**Comment by AlexanderWirtz** [comment]
@dennisschoenmakers

**Comment by RobTerwel** [comment]
> For tweaking industry in the IABR scenario I explicitly set non-energetic demand for oil products, network gas and other carriers.

This is something we can enable again.

> That means two differnt input statements affect the demand for the same carrier in the same subsector in the graph.

That need not be the case. Perhaps the following is a workable solution:

Replace the `adjust_scaling` inputs that used to set the total demand of the subsector with `adjust_scaling` inputs that set the individual carrier demand for that subsector. 

In this way, we don't have two inputs acting upon the same demand *at the same time* (the `adjust_scaling` input having priority and impacting both present and future, the front-end input only impacting the future *post* `adjust_scaling`). In addition, this would us (QI) to fully tweak energy flows, while we don't overwhelm the user with sliders.

This would be a relatively safe solution for the present of all local scenario's that we have made; however, it is not much more than that. Do you think this would do the job @AlexanderWirtz ?

**Comment by AlexanderWirtz** [comment]
@RobTerwel I like this very much and this was indeed what I was angling for. 

To be more explicit:

1. In the `adjust_scaling` folder we (re)create inputs that set the demand for individual carriers for the relevant subsectors. These are statements that pertain to `both` graphs. These statements **replace** the `both` input statements for the total subsector demand. 
2. This impacts the scenario migration that @antw and @RobTerwel did, as this has introduced the above statements to be replaced. Instead, the 'original' scenario entries for change/year need to be recalculated to absolute change. @RobTerwel I assume you and @antw created some kind of script that can be amended to do this?

I feel insufficiently competent to perform 2. 1 I could do with oversight from @ChaelKruip

**Comment by RobTerwel** [comment]
Point 1: exactly!

Point 2: this is a bit more subtle.

>  @RobTerwel I assume you and @antw created some kind of script that can be amended to do this?

This migration led to an aggregation in the sense that several slider values were compressed into one: the average of the sliders for the demand per carrier within a subsector determined the value of that subsector's demand slider. The original slider values per carrier can therefore not simply be retrieved - that is reverse engineering.

However, since all relevant scenario's (Ameland, GEA, IABR) have been documented, we can use these analyses to retrieve the original slider values for the subsector demand per carrier.

**Comment by AlexanderWirtz** [comment]
@RobTerwel 
> The original slider values per carrier can therefore not simply be retrieved from their average mathematically.

Yes, I understand that. 😄 

> However, since all relevant scenario's (Ameland, GEA, IABR) have been documented, we can use these analyses to retrieve the original slider values for the subsector demand per carrier.

Is it not easier to rely on the fact that we have backed up our scenario's and the original slider values still exist? @antw what is your opinion on what would be easiest. I am a little afraid that the documentation could be flawed or not up to date here and there.

**Comment by ChaelKruip** [comment]
> Is it not easier to rely on the fact that we have backed up our scenario's and the original slider values still exist?

Yes.

**Comment by antw** [comment]
> Is it not easier to rely on the fact that we have backed up our scenario's and the original slider values still exist? @antw what is your opinion on what would be easiest. I am a little afraid that the documentation could be flawed or not up to date here and there.

We have a complete backup of the production database from immediately prior to the recent deploy. It would be quite easy to get the original input values of these scenarios from that backup.

**Comment by antw** [comment]
Here are the original input values IABR scenario mentioned in the first post: **https://gist.github.com/antw/f4a9ca5ad7f67a15fbb8cefce91b0ef8**

**Comment by RobTerwel** [comment]
> Is it not easier to rely on the fact that we have backed up our scenario's and the original slider values still exist?

I was unaware of this, great we have it though! This once more shows the importance of backups. 😉

**Comment by AlexanderWirtz** [comment]
@antw and @RobTerwel I guess that means we can do as I suggested:

### Step 1. Generate the input statements for individual carriers and `both` graphs. 
@RobTerwel does this list cover things in your opinion? 

Need-to-haves non-energetic use:
- [ ] `industry_useful_demand_for_chemical_other_coal_non_energetic_both` (used to be set with 'other carriers' slider)
- [ ] `industry_useful_demand_for_chemical_other_biomass_non_energetic_both` (used to be set with 'other carriers' slider)
- [ ] `industry_useful_demand_for_chemical_other_crude_oil_non_energetic_both`
- [ ] `industry_useful_demand_for_chemical_other_network_gas_non_energetic_both`
- [ ] `industry_useful_demand_for_other_aggregated_industry_nl_coal_non_energetic_both` (used to be set with 'other carriers' slider)
- [ ] `industry_useful_demand_for_other_aggregated_industry_nl_biomass_non_energetic_both` (used to be set with 'other carriers' slider)
- [ ] `industry_useful_demand_for_other_aggregated_industry_nl_crude_oil_non_energetic_both`
- [ ] `industry_useful_demand_for_other_aggregated_industry_nl_network_gas_non_energetic_both`

Need-to-haves (energetic use): --> these are needed for the GEA QI scenarios
- [ ] `industry_useful_demand_for_chemical_other_useable_heat_both`
- [ ] `industry_useful_demand_for_other_aggregated_industry_nl_useable_heat_both`
- [ ] `industry_useful_demand_for_chemical_other_electricity_both`
- [ ] `industry_useful_demand_for_other_aggregated_industry_nl_electricity_both`

Nice-to-haves (energetic use) --> pretty sure these are not needed for GEA, right @RobTerwel?: 
- [ ] `industry_useful_demand_for_chemical_other_crude_oil_both`
- [ ] `industry_useful_demand_for_chemical_other_network_gas_both`
- [ ] `industry_useful_demand_for_other_aggregated_industry_nl_crude_oil_both`
- [ ] `industry_useful_demand_for_other_aggregated_industry_nl_network_gas_both`

We could also create --> pretty sure these are not needed for GEA, right @RobTerwel?:
- [ ] `industry_useful_demand_for_chemical_other_coal_both` --> not needed yet
- [ ] `industry_useful_demand_for_chemical_other_biomass_both` --> not needed yet
- [ ] `industry_useful_demand_for_other_aggregated_industry_nl_coal_both` --> not needed yet
- [ ] `industry_useful_demand_for_other_aggregated_industry_nl_biomass_both` --> not needed yet

Not sure we need: @RobTerwel ?
- [ ] `industry_useful_demand_for_other_aggregated_industry_other_<insert carrier name>_both`? 

### Step 2. Determine the values for the generated input statements
I have copied the old input statements from IABR and the values that are relevant from the file @antw referenced. The values are in %/yr and should be in absolute %-ages. The same applies to the GEA QI scenarios (I still need to look up the exact scenarios to migrate). 

So the formula needed to recalculate the <new_values> from the <old_values>:
`(<old_value>/100+1)^(<future_year> - 2013)*100 =<new_value>`

Copy from IABR:
```
industry_useful_demand_for_chemical_crude_oil_non_energetic_both: -5.0
industry_useful_demand_for_chemical_other_non_energetic_both: -50
industry_useful_demand_for_other_crude_oil_non_energetic_both: -50
industry_useful_demand_for_other_network_gas_non_energetic_both: -50
```

### Step 3. Carry out the migration in whichever way @antw deems best

**Comment by RobTerwel** [comment]
The first and second list in step 1 are correct and complete when it comes to the chemical industry (refineries, fertilizers, other chemical) provided that there are no refineries and fertilizers industry in any of these scenario's (which I believe there aren't).

The inputs included in the third and fourth list we don't need; the *sum* of the energetic use of coal, wood pellets, crude oil and network gas is already determined by the useable heat inputs in the second list. The *relative shares* of the energetic use (and therefore the FD) for these carriers can also be tweaked with the `heat_production` shares, such as <a href="https://github.com/quintel/etsource/blob/master/inputs/adjust_scaling/industry/industry_chemicals_refineries_burner_coal_share_present.ad">this one<a/> for instance. It would therefore be potentially risky to include more inputs which act on the same demand.

Now let's get to the other industry,  which in the Netherlands consists of food, paper and aggregated other (ict is taken from the services energy use and is therefore not included here). We can already set the size of these subsectors, but @AlexanderWirtz would we also like to set the demand per carrier of these subsectors? I don't think this is necessary for GEA at least, as we don't have very detailed data.

What we however do **need** to add are the `heat_production` inputs for the food and paper industry which update the present shares.

 	industry_other_food_burner_coal_share_present
	industry_other_food_burner_crude_oil_share_present
	industry_other_food_burner_network_gas_share_present
	industry_other_food_burner_wood_pellets_share_present
	industry_other_food_heater_electricity_share_present

 	industry_other_paper_burner_coal_share_present
	industry_other_paper_burner_crude_oil_share_present
	industry_other_paper_burner_network_gas_share_present
	industry_other_paper_burner_wood_pellets_share_present
	industry_other_paper_heater_electricity_share_present

In addition, we should perhaps add an input which determines the size of the ICT sector (i.e., its electricity use) in the present ánd future:

	industry_useful_demand_for_other_ict_both

So **bottom line**, the inputs in list 1 and 2 are complete and correct if we don't want to/aren't able to specify detailed demand per carrier for the refineries, fertilizers, food and paper industry, those in list 3 and 4 we should not add whilst we should create the heat production inputs for the food and paper industry as listed above as well as perhaps an ICT size slider.

P.s.: don't we use `wood_pellets` rather than `biomass` in the names we give to these inputs? I'd recommend using `wood_pellets` for consistency.

**Comment by AlexanderWirtz** [comment]
@RobTerwel Thanks for you reply. I have 'striken through' the statements we do not need and have added the other need-to-haves. 

>Now let's get to the other industry, which in the Netherlands consists of food, paper and aggregated other 

As you will notice I have included in the first two lists, the input statements for the `aggregated` industry. The food and paper industry are likely to be very similar everywhere, so I do not expect large local variation from the national average. 

>What we however do need to add are the heat_production inputs for the food and paper industry which update the present shares.

Good to know. Added these to the need-to-have list.

> P.s.: don't we use wood_pellets rather than biomass in the names we give to these inputs? I'd recommend using wood_pellets for consistency.

Of course, my bad. Will update the statements.

**Comment by AlexanderWirtz** [comment]
@antw For the GEA scenario values from before the deploy, I need a backup of `etengine_staging` that is somewhat recent but from before the migration and (obviously) from before the deploy. I had a relevant backup for the IABR scenario, but did not make one in this particular period. 

Question 1: Can you help me with this?
Question 2: I can tell August 11 was a day all these scenario were updated. Is that when you did the migration? I cannot see when @RobTerwel last edited these scenarios (somewhere before Aug 11, though).

The scenario titles and IDs are the following:

- GEA QI Nulmeting 2013/2014 (incl. NL): `507792`
- GEA QI Nulmeting 2013/2014 (excl. NL) V2: `536976`
- GEA QI Beeld 2020 (incl. NL) V4: `512062`
- GEA QI Beeld 2020 (excl. NL) v1: `533133`
- GEA QI Beeld 2023 (incl. NL) V2: `530730`
- GEA QI Beeld 2023 (excl. NL) v2: `533602`
- GEA QI (voor)Beeld GEA 2035 v2: `531167`
- GEA QI (voor)Beeld 2050 V6: `530759`

**Comment by antw** [comment]
> Question 1: Can you help me with this?

**[Here you go!](https://gist.github.com/antw/4e88d72f3e874371c88be644e8380390)**

If you need it, you can find the full database backup on DropBox at `Quintel` → `Development` → `Deploys` → `Misc DB Backups` → `etengine_staging-11-08-2016-09-58-before-chem-split.sql.bz2`

> Question 2: I can tell August 11 was a day all these scenario were updated. Is that when you did the migration? [...] I cannot see when @RobTerwel last edited these scenarios (somewhere before Aug 11, though).

Indeed, 11th August was the migration date for the staging server.

| Scenario | Last modified |
| --- | --- |
| GEA QI Nulmeting 2013/2014 (incl. NL): 507792 | 7th March |
| GEA QI Nulmeting 2013/2014 (excl. NL) V2: 536976 | 1st June |
| GEA QI Beeld 2020 (incl. NL) V4: 512062 | 30th March |
| GEA QI Beeld 2020 (excl. NL) v1: 533133 | 24th May |
| GEA QI Beeld 2023 (incl. NL) V2: 530730 | 18th May |
| GEA QI Beeld 2023 (excl. NL) v2: 533602 | 25th May |
| GEA QI (voor)Beeld GEA 2035 v2: 531167 | 19th May |
| GEA QI (voor)Beeld 2050 V6: 530759 | 18th May |

**Comment by AlexanderWirtz** [comment]
@RobTerwel as I started creating these input statements I found out that 

### Energetic demand
The `industry_useful_demand_for_other_aggregated_industry_nl_both.ad` input statement also contains a lot of energetic use input statements for the various sub-subsectors, other than the `useable_heat` and `electricity` we need for GEA. If we replace this sector-wide input statement, I suppose that implies that we need to create input statements that cover energetic UD for these carriers in the `aggregated_industry` as well?

Do we need these?
- [ ] `industry_useful_demand_for_other_aggregated_industry_nl_electricity_both.ad`
- [ ] `industry_useful_demand_for_other_aggregated_industry_nl_useable_heat_both.ad`
- [ ] `industry_useful_demand_for_other_aggregated_industry_nl_coal_both.ad`
- [ ] `industry_useful_demand_for_other_aggregated_industry_nl_crude_oil_both.ad`
- [ ] `industry_useful_demand_for_other_aggregated_industry_nl_network_gas_both.ad`
- [ ] `industry_useful_demand_for_other_aggregated_industry_nl_wood_pellets_both.ad`

### Non-energetic demand
Only the `other_non_specified` sub-subsector has any input statements that set non-energetic UD for carriers. Can the other sub-subsectors never have any?

**Comment by AlexanderWirtz** [comment]
> Here you go!

Thanks!

**Comment by RobTerwel** [comment]
In creating the subsectors listed in the `aggregated_other` inputs, we did two things:
- not add any burner/heater technologies to these subsectors, as we chose not to model previously unexposed subsectors in detail.
- direct all non-energetic demand  to the `other_non_specified` subsector, as it can not be extracted from the EB to which subsector this non-energetic demand for the **old** `other` industry sector goes, nor is it easy to research these values for the 8 subsectors under discussion. 

Therefore,
>if we replace this sector-wide input statement, I suppose that implies that we need to create input statements that cover energetic UD for these carriers in the aggregated_industry as well?

Yes, that's correct, if we want to tweak those as well. Keep in mind no heating technologies are present in these subsectors though.

>Can the other sub-subsectors never have any?

Indeed the `other_non_specified` subsector is the only subsector within the `aggregated_other` industry which can have non-energetic demand.

**Comment by AlexanderWirtz** [comment]
@jorisberkhout is there any chance you could look at this and create the remaining input statements? I guess you and I need to have a chat on how to go about the migration. @antw has already found all the  old values in the relevant scenarios.

**Comment by ChaelKruip** [comment]
> @jorisberkhout is there any chance you could look at this and create the remaining input statements?

@RobTerwel has done this already in https://github.com/quintel/etsource/commit/c43d2f28abb46a2d835dc09fc20368e5f0258dd7

**Comment by AlexanderWirtz** [comment]
Reopening this until the scenarios in question have been fixed

**Comment by AlexanderWirtz** [comment]
@jorisberkhout I am quite sure this has been fixed/addressed. Can I close this?
