### ISSUE TITLE
Should primary CO2 include distribution losses?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2255]
This is a bit of a philosophical question: "Why would you also take oil spilling into the sea, gas leaking from the pipes and coal dropping from the conveyor belt into account when calculating CO2 emissions (as we currently do)?"

Is this convention?

**Comment by AlexanderWirtz** [comment]
It is not convention (I believe), but just how our CO2 calculation works. IF we decide to change this, and account for CO2 emissions of actual energetic use, we would need to first map out how large the discrepancy is and if we can reproduce official numbers. 

One issue might be that for compiling official usage statistics, losses are not always known precisely and it is simply assumed or reported that everything is used.

**Comment by ChaelKruip** [comment]
Thanks for your answer @AlexanderWirtz! 

> we would need to first map out how large the discrepancy is 

I checked for the Dutch dataset and we currently assume lossless transportation and distribution for the major carriers (gas, coal, oil, biomass). 

Also in the refinery sector, the losses of non-energetic oil are zero. 

Closing this as I don't think this is worth pursuing anytime soon.
