### ISSUE TITLE
Network costs seem to have disappeared from the costs chart in the dashboard

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2256]
As witnessed during presentation with ECN today

**Comment by ChaelKruip** [comment]
For scaled scenario's it seems that the network cost calculation is missing from the chart indeed although some extra (network?) costs are taken into account in the dashboard item itself:
![energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_](https://cloud.githubusercontent.com/assets/1303760/18865860/acc32074-849d-11e6-8d7e-685e728ddd70.png)

**Comment by ChaelKruip** [comment]
@antw could it be that the `use_network_calculations` attribute is set to `false` for scaled scenario's?

**Comment by antw** [comment]
> could it be that the use_network_calculations attribute is set to false for scaled scenario's?

[Yes](https://github.com/quintel/etmodel/blob/9b2b00ae8320d226d33735f100359bc3cdc23484/app/models/api/scaled_area.rb#L6). That was done in order to prevent the "Infrastructure" section from appearing in scaled scenarios (edd5400).

**Comment by ChaelKruip** [comment]
> Yes. That was done in order to prevent the "Infrastructure" section from appearing in scaled scenarios (edd5400).

Makes sense. What is weird though is that the costs for infra are excluded from the chart but not from the dashboard item. When I check the value of the `use_network_calculations` attribute in the sand-box for a scaled scenario, I get `true` which is surprising to me:
![energytransitionmodel](https://cloud.githubusercontent.com/assets/1303760/18911462/83dc6f0e-857d-11e6-9292-5dcb8caf1df6.png)

**Comment by ChaelKruip** [comment]
Co-assigning @antw

**Comment by antw** [comment]
> When I check the value of the use_network_calculations attribute in the sand-box for a scaled scenario, I get true which is surprising to me:

The attribute is disabled in ETModel (the front-end) only.

The intention of edd5400 was to hide the infrastructure sidebar item and "Required additional infrastructure investments" chart – not to turn off `use_network_calculations` for the scenario in ETEngine. This was the simplest way of achieving that since ETModel permits only one area-dependency, and the sidebar item and chart were already set to `use_network_calculations`.

I expect we could also set `use_network_calculations` to false in ETEngine, if that is desirable?

**Comment by ChaelKruip** [comment]
>  I expect we could also set use_network_calculations to false in ETEngine, if that is desirable?

I think it would make sense because the network calculation is not built to work for small regions and the Stakeholder Analysis module typically will override the calculation with more accurate local data.
