### ISSUE TITLE
Maintainability of scaled scenario's needs to be improved

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2259]
Because the scaling of the `present` dataset (as a fraction of the national dataset) is often insufficiently representative of the local situation, elaborate update statements are used to scale both `present` and `future` data.

**Comment by AlexanderWirtz** [comment]
@ChaelKruip this issue needs clarification. @jorisberkhout was chosen to be in charge of creating vision of the future by the way

**Comment by AlexanderWirtz** [comment]
I suggest closing this issue as it is way out of date. Let's create a more current one to address any remaining issues.
