### ISSUE TITLE
WANTED: bar-chart with negative series

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2261]
I'd like to make a chart which show the user how much CO2 emission is reduced between the start- and end-year similar to:
<img width="818" alt="20160804_gasunie_co2_v02_key" src="https://cloud.githubusercontent.com/assets/1303760/18917004/bf4a010a-8596-11e6-8bb1-76ee1cda32e9.png">

Although I think that for the ETM it would be more logical to flip the horizontal and vertical axis (putting the labels below).

@antw @grdw can you give me an indication of the amount of effort this would require from your side?

**Comment by antw** [comment]
I think this would take a couple of days, but I'm not very familiar with the D3 library used for the charts. @grdw probably has a better idea of how much effort this would take.

The existing bar charts are not suitable; the `target_bar` charts have hard-coded Gquery names, and the CO2 charts are special-cased to also include 1990 values. This seems like a good opportunity to add a proper bar chart class, where each sector is it's own [ChartSerie](https://github.com/quintel/etmodel/blob/bd5844eb3d8dc7c8950d031d653fa6a3ef204c5c/app/assets/javascripts/lib/models/chart_serie.coffee) (`output_element_series` in the database).

**Comment by grdw** [comment]
> I think this would take a couple of days,
> This seems like a good opportunity to add a proper bar chart class

I think about 2-3 days including manual testing if this needs to be a new class.
