### ISSUE TITLE
User should be able to choose the base year for the CO2 comparison in the dashboard

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2262]
For national scenario's it is very clear that this need to be 1990, but for local municipalities they rather like to compare it to the present year.

**Comment by ChaelKruip** [comment]
It would be relatively easy to add a dashboard item to the list:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/18948858/0f8c6430-8639-11e6-803b-efca72141c06.png)
and a query of the form:
```
QUERY_FUTURE(total_co2_emissions) / QUERY_PRESENT(total_co2_emissions)
```

**Comment by ChaelKruip** [comment]
If more people like this idea, I can make this happen in little time.

**Comment by dennisschoenmakers** [comment]
:+1:

**Comment by dennisschoenmakers** [comment]
Thanks! :+1:
