### ISSUE TITLE
User should be able to distinguish between local and non-local mobility use

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2263]
Right now a lot of discussion happens on which part of mobility use should be attributed to a particular region, e.g.:
- which part of a ferry service between an island and the mainland should be attributed to the island or the mainland, especially when the a big component is tourism?
- how should car transportation of a region be divided between home areas and working areas?
- should passing through transportation be taken into account?
- etc.

**Comment by ChaelKruip** [comment]
Ok, but does IEA make any distinction like that @jorisberkhout @AlexanderWirtz? If we can't find good data on this, it would not be worth it to make this distinction in the ETM.

**Comment by AlexanderWirtz** [comment]
> Ok, but does IEA make any distinction like that @jorisberkhout @AlexanderWirtz?

Nope, it doesn't. The [Klimaatmonitor](https://klimaatmonitor.databank.nl/) numbers that we often use to tweak local energy demands (down to municipality, not further) does distinguish between fuel use for highway-bound vehicles and the rest. This isn't quite what @dennisschoenmakers is referring to, of course, as a lot of traffic on the A10 in Amsterdam could be local traffic, for example.

I am afraid making this distinction from the data initialization onwards would be highly impractical as the data is simply not available. This is one of the reasons it lead to so much discussion.  

That leaves the option of including a slider and just letting the user decide. I fail to see the value of that, as all it does is reduce transport-related energy demand and CO2 emissions by the factor set by the slider. In exploring the future, users can also do that by themselves and simply declare that "half the energy use and transport-related emissions are not really ours!".

**Comment by AlexanderWirtz** [comment]
I suggest reminding any user who creates/edits a local dataset and good documentation. One reason transport is often left out of local targets and statistics is that this break-down is hard. We include it mostly to show that electrification / hydrogenification of previously fossil-fueled transportation has local impacts.

Shall we close this issue?
