### ISSUE TITLE
"Import + production" and "export + demand" for oil_products are not always the same 

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2267]
In a blank Belgian scenario, excess production of oil products is not exported.

<img width="614" alt="screen shot 2016-09-29 at 17 30 21" src="https://cloud.githubusercontent.com/assets/4669028/18960864/71f2833e-866b-11e6-9da7-b288bb3b4f31.png">

In a blank Dutch scenario with the chemical sector increased to `169%` the shortage of oil products is not imported.

<img width="616" alt="screen shot 2016-09-29 at 17 39 17" src="https://cloud.githubusercontent.com/assets/4669028/18960971/c466579e-866b-11e6-8d5b-fc8f2bc33414.png">

This is most likely caused by the fact that the input of `industry_locally_available_crude_oil_non_energetic_for_chemical` consists of two different carriers.

<img width="1425" alt="screen shot 2016-09-29 at 17 33 16" src="https://cloud.githubusercontent.com/assets/4669028/18961032/f10f78f2-866b-11e6-9e72-cc7c6c16f8d7.png">

**Comment by RobTerwel** [comment]
Previously this did not occur when we converted the `oil_products` to `crude_oil` in the no longer existent node `energy_production_oil_products`, which resulted in one carrier flowing into the `industry_locally_available_crude_oil_non_energetic_for_chemical` node (as opposed to now). 

This should either partially or fully explain the observed absence of import. I'd also recommend looking at the edge types if the double carrier aspect doesn't fully account for this behaviour: the `industry_final_demand_for_chemical_crude_oil_non_energetic` node is meant to fill the unfulfilled demand on the `industry_locally_available_crude_oil_non_energetic_for_chemical` node.

**Comment by ChaelKruip** [comment]
I'm running into some trouble with non-NL datasets here. The weird thing is that the there seems to be a mismatch between the production of heat from the `industry_useful_demand_for_chemical_refineries_useable_heat` node and the input of heat into the `industry_refinery_transformation_crude_oil` node.

Could it be that the same carrier cannot be simultaneously used as input and output of a node @antw?

![industry_refinery_transformation_crude_oil_converter_ad_ _etsource](https://cloud.githubusercontent.com/assets/1303760/19240822/651f75d2-8f0c-11e6-97ac-5b6152ac5bf6.png)

**Comment by antw** [comment]
> Could it be that the same carrier cannot be simultaneously used as input and output of a node @antw?

I highly doubt it.

Comparing the calculation order of NL and UK datasets for the "useful demand" and "transformation" nodes, the order of each node and edge being calculated is identical, and the exact same strategies are used for each one.

Essentially, the error message is complaining that the demand of the "useful demand" node (which appears to be calculated by summing the demands of its input edges) does not match the amount of energy which leaves the node:

![industry_useful_demand_for_chemical_refineries_usea calculable](https://cloud.githubusercontent.com/assets/4383/19244017/48ebe336-8f12-11e6-9328-e81a5c691d5d.png)

I can look into it in more detail in the morning.

**Comment by antw** [comment]
Debug output of related nodes for the UK dataset:

| Step | Action performed |
| :---: | --- |
| 1036 | ![01036](https://cloud.githubusercontent.com/assets/4383/19246476/76bae724-8f1e-11e6-8bd1-78b1c0673cb5.png) |
| 1199 | ![01199](https://cloud.githubusercontent.com/assets/4383/19246477/76bb6078-8f1e-11e6-9358-354feb1d45ed.png) |
| 1208 | ![01208](https://cloud.githubusercontent.com/assets/4383/19246479/76bd741c-8f1e-11e6-9080-3f2fe373aad4.png) |
| 1215 | ![01215](https://cloud.githubusercontent.com/assets/4383/19246478/76bd2534-8f1e-11e6-90da-9095bebaa37e.png) |
| 1247 | ![01247](https://cloud.githubusercontent.com/assets/4383/19246480/76be9658-8f1e-11e6-8e52-171eb5da02e9.png) |
| 1276 | ![01276](https://cloud.githubusercontent.com/assets/4383/19246481/76c6328c-8f1e-11e6-900f-1af1fc65febd.png) |
| 1277 | ![01277](https://cloud.githubusercontent.com/assets/4383/19246483/76d57260-8f1e-11e6-8462-f2e23b8ded2f.png) |
| 1278 | ![01278](https://cloud.githubusercontent.com/assets/4383/19246482/76d534c6-8f1e-11e6-8996-cb95f3f0996b.png) |
| 1362 | ![01362](https://cloud.githubusercontent.com/assets/4383/19246484/76d7bf20-8f1e-11e6-85d4-d0e8d7ecd690.png) |
| 1363 | ![01363](https://cloud.githubusercontent.com/assets/4383/19246485/76d8f4c6-8f1e-11e6-846f-61d59a40b7f8.png) |
| 1372 | ![01372](https://cloud.githubusercontent.com/assets/4383/19246486/76d98b34-8f1e-11e6-8d24-05842d4bc0d6.png) |

**Comment by antw** [comment]
... and again for NL. They're basically the same, except that for NL the output of the useful demand node matches the demand of the outgoing edge (which comes from the transformation node).

| Step | Action taken |
| :---: | --- |
| 1033 | ![01033](https://cloud.githubusercontent.com/assets/4383/19246836/34994a0a-8f20-11e6-8f89-56321390c9c3.png) |
| 1195 | ![01195](https://cloud.githubusercontent.com/assets/4383/19246837/34a978ee-8f20-11e6-89b2-8385fb120b9e.png) |
| 1204 | ![01204](https://cloud.githubusercontent.com/assets/4383/19246838/34b325ce-8f20-11e6-8683-c7bc5fdd1ac9.png) |
| 1211 | ![01211](https://cloud.githubusercontent.com/assets/4383/19246839/34b6d32c-8f20-11e6-9a52-575411f04837.png) |
| 1242 | ![01242](https://cloud.githubusercontent.com/assets/4383/19246842/34c1eaf0-8f20-11e6-9fcd-504be77915d0.png) |
| 1271 | ![01271](https://cloud.githubusercontent.com/assets/4383/19246841/34bcbe04-8f20-11e6-9702-cbcb15e0a002.png) |
| 1272 | ![01272](https://cloud.githubusercontent.com/assets/4383/19246840/34b9ec2e-8f20-11e6-88c6-fdaf36e952e6.png) |
| 1273 | ![01273](https://cloud.githubusercontent.com/assets/4383/19246843/34c33d92-8f20-11e6-96dd-dc65f651180e.png) |
| 1359 | ![01359](https://cloud.githubusercontent.com/assets/4383/19246844/34cc8c8a-8f20-11e6-83f5-d37826973dc3.png) |
| 1360 | ![01360](https://cloud.githubusercontent.com/assets/4383/19246845/34d5744e-8f20-11e6-9a28-e4e645747d22.png) |
| 1369 | ![01369](https://cloud.githubusercontent.com/assets/4383/19246846/34d7ff52-8f20-11e6-9c67-6f441cb69b9c.png) |

**Comment by antw** [comment]
> What I don't understand is that the strategies seem to work from right to left. Shouldn't the demand be set from left to right (demand driven)?

The error comes from Refinery, where calculations are bi-directional. If it knows the demand of a node, the output conversion (efficiency) and the (parent) share of an output edge, it can compute the demand the edge from right-to-left.

I checked out one of the heaters: industry_chemicals_refineries_burner_crude_oil

1. The demand originates in `industry_final_demand_crude_oil`, [which comes from an energy balance query](https://github.com/quintel/etsource/blob/f68983dc161d9b61c9ab396b4213410a63f2337e/nodes/industry/industry_final_demand_crude_oil.final_demand.ad).

2. The demand of the output link to `industry_final_demand_for_chemical_crude_oil` is [set using a SHARE() CSV file](https://github.com/quintel/etsource/blob/f68983dc161d9b61c9ab396b4213410a63f2337e/edges/industry/industry_final_demand_crude_oil-industry_final_demand_for_chemical_crude_oil%40crude_oil.ad#L5).

  ![00118](https://cloud.githubusercontent.com/assets/4383/19263955/bba7caf0-8f96-11e6-9419-da377e149470.png)

3. There is now enough information to set the demand of the node:

  ![00121](https://cloud.githubusercontent.com/assets/4383/19263963/c287c9f6-8f96-11e6-8739-c7f47e25293e.png)

4. Its output links [also have SHARE() values](https://github.com/quintel/etsource/blob/f68983dc161d9b61c9ab396b4213410a63f2337e/edges/industry/industry_final_demand_for_chemical_crude_oil-industry_final_demand_for_chemical_refineries_crude_oil%40crude_oil.ad#L5):

  ![00512](https://cloud.githubusercontent.com/assets/4383/19263979/cf0271c2-8f96-11e6-8a32-3641f53c4ecd.png)

5. ... and now the demand of `industry_final_demand_for_chemical_refineries_crude_oil` may be set:

  ![00515](https://cloud.githubusercontent.com/assets/4383/19264030/035e0008-8f97-11e6-9d3f-ba0e771b328d.png)

6. That node has a single output slot and a single edge, therefore the demand of the output edge and node can be determined:
  
  ![00896](https://cloud.githubusercontent.com/assets/4383/19264057/2805dbd8-8f97-11e6-85e1-389a373b4312.png)
  ![00897](https://cloud.githubusercontent.com/assets/4383/19264063/2cf3eaea-8f97-11e6-9f9c-1f2bf5953ae1.png)
  ![01208](https://cloud.githubusercontent.com/assets/4383/19264064/2d0a6fa4-8f97-11e6-8e41-f975d45ac317.png)

**Comment by antw** [comment]
There is a difference in the calculation order between this branch and master. On this branch the "locally available" node now has only one input slot (crude_oil) and Refinery is able to determine sooner in the calculation what the demand of its inputs are:

![01276](https://cloud.githubusercontent.com/assets/4383/19273345/1b3d7f50-8fc4-11e6-9375-eae382a25001.png)

Refinery knows that the "locally available" node needs to output 150PJ and that the "final demand" input is going to provide none of that. Therefore the full 150PJ must be provided by the transformation node:

![01277](https://cloud.githubusercontent.com/assets/4383/19273396/446a575e-8fc4-11e6-8e39-dca955a79f75.png)

Refinery now knows how much energy must flow between the transformation node and the "locally available" node, *and* it knows the output efficiency of the crude_oil output for the transformation node, therefore it can set its demand:

![01278](https://cloud.githubusercontent.com/assets/4383/19273442/7303ee54-8fc4-11e6-8376-02194dd36802.png)

--

**On the master branch**, the two input slots on the "locally available" node mean it has to wait longer before it has enough information to set the edge between the transformation and "locally available" nodes:

![01278](https://cloud.githubusercontent.com/assets/4383/19273565/dfd5ce6c-8fc4-11e6-94c9-35738b236033.png)
![01368](https://cloud.githubusercontent.com/assets/4383/19273560/dfbd5f80-8fc4-11e6-91fe-e056d7be7aac.png)
![01369](https://cloud.githubusercontent.com/assets/4383/19273563/dfc0b16c-8fc4-11e6-951a-904b20d2f455.png)
![01410](https://cloud.githubusercontent.com/assets/4383/19273562/dfbf4fca-8fc4-11e6-9c38-cb7056926eaa.png)
![01411](https://cloud.githubusercontent.com/assets/4383/19273561/dfbe9274-8fc4-11e6-8815-707bfbaf78ba.png)
![01423](https://cloud.githubusercontent.com/assets/4383/19273564/dfc0b608-8fc4-11e6-9cd6-9dc342c64856.png)
![01424](https://cloud.githubusercontent.com/assets/4383/19273566/dfddd63e-8fc4-11e6-97e5-1ff910cc052a.png)

There's an issue here as well, where the transformation node is oversupplying the "locally available" node.

**Comment by jorisberkhout** [comment]
Thanks for the insights @antw and @ChaelKruip . I have looked into the ETDataset side of things and I get the suspicion that the 'bookkeeping' in the dataset generation is not right. One first observation is that the NL dataset (both 2012 and 2013) is the only dataset where the refineries do not produce enough 'oil products' to feed the chemical industry. Hence crude oil is imported to overcome this deficit and things work fine (that is after the fix by @ChaelKruip ).

In all other dataset, the refineries produce to much 'oil products' for the demand in the chemical industry and you would expect the excess to be exported. This, however, seems to be where the dataset generation process does not calculate shares correctly. I will look into this issue tonight or tomorrow.

**Comment by jorisberkhout** [comment]
I finally found time to have a look at this issue. I found the following / took the following actions:
- The fix by @ChaelKruip (on branch `oil-products`) worked fine for the Netherlands, where the refineries do not make enough "oil products" to fulfil the demand in the petrochemical industry
- In all other countries that we model, the refineries produce **more** than their chemical industries need and the refineries also produce for the export of oil products
- I have pushed a fix for the latter to the `oil-products` branch in which I explicitly set the demand of the `energy_export_oil_products` node
- This fix results in working graph for all datasets
- This fix introduces marginal changes to default scenarios
- The new Urgenda scenario (`Urgenda 2.0 20161005 v8`) does **change** quite radical in terms of **Energy use** (`-62.9%` on Beta vs `-57.3%` locally after the fix) and **Energy import** (`-1.0%` on Beta vs `10.9%` locally after the fix). This is easily explained by the fact that on Beta non-energetic oil is created out of nowhere, which you can see by looking at the refinery sankey

The fix is in https://github.com/quintel/etsource/pull/1170 and I leave it up to @ChaelKruip to review this fix and decide if we merge it.
