### ISSUE TITLE
P2P currently has a sustainability share of 0.0

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2269]
The  `sustainability_share` of the  `households_flexibility_p2p_electricity` converter is currently 0.

This influences the renewability of `households_locally_available_electricity` and also the total renewability of the scenario.

@ChaelKruip and I discussed this, we think a sustainability share of 1 would be realistic as excess electricity is stored usually originates from renewable sources.

@antw how do you think the `sustainability_share` can be adjusted?

**Comment by antw** [comment]
I believe there are two possible solutions:

1. Add a new `sustainability_share` attribute in Atlas so that we might set a custom value [for the converter](https://github.com/quintel/etsource/blob/2b20e080396f55c9b3e47f60c7ac44aad9e04ec4/nodes/households/households_flexibility_p2p_electricity.converter.ad). I don't think this would change `demand_of_sustainable`... is that a problem?

2. Add a new node which connects to the P2P node using a sustainable carrier.

The second option is a bit annoying for adding a new node, but doing that should also result in `demand_of_sustainable` also becoming non-zero.

**Comment by ChaelKruip** [comment]
> I don't think this would change demand_of_sustainable... is that a problem?

I don't think so. I'm leaning towards solution 1.

**Comment by ChaelKruip** [comment]
@antw how much time do you think this would take? It would be nice to pick this up with some priority IMO.

**Comment by antw** [comment]
This is done, and deployed to beta. Looks fine to me, but could you check it out and see if things are as you expected? If so, this issue can then be closed.

**Comment by ChaelKruip** [comment]
Nice work @antw 👍

**Comment by ChaelKruip** [comment]
@DorinevanderVlies can you check if this change has the desired effect on the Urgenda scenario?

**Comment by ChaelKruip** [comment]
@DorinevanderVlies can you check if this change has the desired effect on the Urgenda scenario?

**Comment by DorinevanderVlies** [comment]
Looking at the effect on the Urgenda scenario has raised two questions.

1. Why does the renewability decrease when the amount of household batteries increases?
2. Why does storage in batteries influence the scenario in a different way than storage in electric vehicles? The renewability is not influenced by storage in electric vehicles.

I will try to find the answer to the questions.

### Details
These screenshots clarify the questions.

The energy use of situation B and C should be the same, or at least very similar. The total amount of stored energy is the same and the conversion losses of both household and EV P2P are the same.

The % renewables of scenario B and C should be the same or at least very similar.

A) Dashboard without storage:
![image](https://cloud.githubusercontent.com/assets/19907658/20487455/a20d9df8-b003-11e6-93a0-d9f77f1ee6c0.png)

B) Dashboard with 100% storage in household batteries (29.65 PJ stored in batteries) and no storage in EV
![image](https://cloud.githubusercontent.com/assets/19907658/20487582/36127730-b004-11e6-8890-e54ff945d497.png)

C) Dashboard with 100% storage in electric vehicles (55.63 PJ stored in EV) no storage in batteries
![image](https://cloud.githubusercontent.com/assets/19907658/20487594/467913e0-b004-11e6-97f8-1b87b8d4499f.png)

D) Dashboard with 25% storage in electric vehicles batteries (29.99 PJ stored in EV, so the same as the scenario with 100% storage in batteries) no storage in batteries
![image](https://cloud.githubusercontent.com/assets/19907658/20487617/5ea46fa0-b004-11e6-9de3-342ca86b57d7.png)

**Comment by DorinevanderVlies** [comment]
> 1. Why does the renewability decrease when the amount of household batteries increases?
> 2. Why does storage in batteries influence the scenario in a different way than storage in electric vehicles? The renewability is not influenced by storage in electric vehicles.

This is still the case. I'm have not been able to find out why this occurs

**Comment by ChaelKruip** [comment]
@antw could you have a look at this issue as well?

**Comment by antw** [comment]
> @antw could you have a look at this issue as well?

Already am. :smiley: I suspect that the recursive sustainability share isn't being calculated correctly. I'll get back to you both once I have more info.

**Comment by antw** [comment]
Closed by quintel/etengine@697a5c5.

**Comment by ChaelKruip** [comment]
Great work @antw!

**Comment by DorinevanderVlies** [comment]
nice!
