### ISSUE TITLE
Heat efficiency improvement in fertilizers subsector should not affect the non-energetic input of network gas

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2272]
See title.

**Comment by TessColijn** [comment]
I looked through the input queries and come up with this:

**Comment by TessColijn** [comment]
I have looked through the inputs and found the following:

![image](https://cloud.githubusercontent.com/assets/22587085/19383519/092481a4-9205-11e6-8bd7-b84ff48e3958.png)

@jorisberkhout  are these the correct queries related to the issue?

![image](https://cloud.githubusercontent.com/assets/22587085/19383480/d2c70dde-9204-11e6-9c82-f8c25ba39355.png)

**Comment by jorisberkhout** [comment]
Removing from milestone as this is more complicated to solve than I anticipated.

**Comment by ChaelKruip** [comment]
@jorisberkhout what do you think would be a good way forward for this issue?

**Comment by jorisberkhout** [comment]
See the separate e-mail that I just sent you. Let's discuss that first and then decide how to proceed with this issue.
