### ISSUE TITLE
Modelling Agriculture CHPs

### ISSUE THREAD

**Issue by TessColijn** [quintel/etmodel#2276]
Please find a description of the steps to solve the issues related to agriculture CHPs (https://github.com/quintel/etsource/issues/1174).

The solution discussed will involve 3 changes to the model which all incorporate further questions and issues:
1. Make agriculture CHPs dispatchable
2. Develop a heat demand and supply balance
3. Provide User feedpack

**1. Make agriculture CHPs dispatchable:**
- How will marginal costs be determined for electricity production to enable a fair representation in merit order? https://github.com/quintel/etmodel/issues/2281 

**2. Develop a heat demand and supply balance:**
- How will the heat demand curve be modelled? Heat Demand Curve in Agriculture #2280
- How will different technologies be implemented? https://github.com/quintel/etmodel/issues/2278
- How will shortages be solved? https://github.com/quintel/etmodel/issues/2277 
- What happens in the case of a surplus?https://github.com/quintel/etmodel/issues/2282

**3. User feedback:**
- What information is provided to user about agriculture CHPs and in which form? #2279

**Comment by ChaelKruip** [comment]
> How will marginal costs be determined for electricity production to enable a fair representation in merit order? Please see issue quintel/etsource#236

I think that issue deals primarily with the 'energy' CHPs which typically have a heat contract. As we are talking about agricultural CHPs (which can't sell their heat nor adjust their efficiency for making electricity), the issue of what their marginal costs should in the electricity merit order is a bit more subtle:
* If no heat is needed: marginal costs should include fuel costs for both electricity and heat
* If heat is needed:
  * If cost for running CHP < cost for running backup heater: marginal costs are zero (this never happens)
  * If costs for running CHP > cost for running backup heater: marginal costs are difference between costs for running CHP and running backup heater. This can likely be approximated well by setting the marginal costs to exclude the heat production part (as proposed in quintel/etsource#236).

@AlexanderWirtz does this make sense to you as well?

**Comment by TessColijn** [comment]
@ChaelKruip @AlexanderWirtz @jorisberkhout  Please find here an overview of the issues related to the steps to be taken for agriculture CHPs.

**Comment by michieldenhaan** [comment]
Closing, CHPs are now dispatchable in Merit, marginal costs for steam cycle CHPs have been adjusted. Heat demand calculation is time-resolved
