### ISSUE TITLE
Shortage of Heat in Agriculture sector

### ISSUE THREAD

**Issue by TessColijn** [quintel/etmodel#2277]
How will shortages be solved?

Once CHPs are dispatchable there will be two reasons for a shortage:
1. Electricity price is low and CHPs are too expensive to run. Hence CHPs are available but not active or not running on full capacity. If this is the case the shortage might also arise depending on technology. If woodpellets CHP is too expensive then greenhouses with woodpellets CHP are not heated while gas CHPs might be active and providing excess heat. 
   
   Several questions arise to how this shortage is solved?
   - Can we couple each CHP to the demand of the location of the CHP and thus determine the shortage per location?
   - Do we want shortage to be filled with an automatic response or should this be determined by user input? 
   - Is every CHP coupled with a certain backup? (A gas CHP has a gas-fired heater as backup? and what about a wood-pellets CHP?)
   - Should we take water tanks to buffer heat into consideration?
2. CHPs are profitable and thus running on full capacity but share of heat required to be fulfilled with CHP heat as determined by user input is not met. 
   
   The user will need options to solve this second type of shortage. According to the inputs in the current model these solutions could be in the following forms:
   - User can add more CHPs
   - User can decrease the percentage share of CHPs and replace with other technologies to solve the second type of shortage
   
   Do we want to leave these options to the user? Or should these be automatic responses to the shortages? Also see issue https://github.com/quintel/etmodel/issues/2278 about user input.

**Comment by TessColijn** [comment]
@AlexanderWirtz @jorisberkhout @ChaelKruip do you have some thoughts/ideas about the questions above?

**Comment by AlexanderWirtz** [comment]
@ **1**
> Can we couple each CHP to the demand of the location of the CHP and thus determine the shortage per location?

Not desirable. Data will not be available and making assumptions is too complicated IMO.

> Do we want shortage to be filled with an automatic response or should this be determined by user input?

The ETM cannot deal with imbalance, so something will always have to be done to fill this shortage. We could add a new carrier called `heat_shortage`, or we could just have gas-fired heaters jump in. I prefer the latter option, as this is likely to be closest to the truth. biomass heaters will not be able to start fast enough, so biomass CHPs will have gas-fired heaters for backup as well. 

We could give the user the option of choosing `greengas` or `biogas` for backup heaters, but that seems convoluted, as they can also choose the percentage of `greengas` in `network_gas`.

> Should we take water tanks to buffer heat into consideration?

I vote no, as this makes things so complicated. I wonder if it is really necessary on a large scale.

@ **2**
The above also applies here. The question for both 1 and 2 is: how do we make the user aware that backup heaters are being used instead of CHPs?

**Comment by TessColijn** [comment]
@AlexanderWirtz 

> or we could just have gas-fired heaters jump in

In this case we make an assumption that every greenhouse has a gas boiler that could supply all the heat needed. And we could label these boilers "backup_boilers". And if i understand correctly this is the current scenario in the dutch agriculture sector and would be a realistic assumption. But i am still not sure how these gas-fired boilers would relate to the percentage share of gas-fired boilers that the user has already chosen to use? Wouldn't this mean that the percentage share selected by the user needs to be updated such that CHPs produce less and gas-fired boilers more? Or is it sufficient to keep the initially chosen gas-fired boilers and the backup boiler as separate feedbacks for the user?

> CHPs are profitable and thus running on full capacity but share of heat required to be fulfilled with CHP heat as determined by user input is not met.

I know i gave this as a possible scenario, but are there cases where a greenhouse needs both a CHP and gas boilers at full capacity to meet its heat demand?

**Comment by ChaelKruip** [comment]
> According to the inputs in the current model these solutions could be in the following forms:

The user can also decrease the total heat demand to solve this shortage.

> User can decrease the percentage share of CHPs and replace with other technologies to solve the second type of shortage

Wouldn't it make more sense to give the user sliders for the installed capacity (number of units) for all heating options rather than this complex two-step approach of first setting shares and later number of units (only for CHPs)?

**Comment by ChaelKruip** [comment]
> I know i gave this as a possible scenario, but are there cases where a greenhouse needs both a CHP and gas boilers at full capacity to meet its heat demand?

This would mean that the greenhouse did not dimension its heat production properly. I think that this might occur in reality but is perhaps not very useful to model explicitly.

@AlexanderWirtz I'm curious about your thoughts on this as well!

**Comment by TessColijn** [comment]
@ChaelKruip 

> Wouldn't it make more sense to give the user sliders for the installed capacity (number of units) for all heating options rather than this complex two-step approach of first setting shares and later number of units (only for CHPs)?

Would we then assume that all installed capacities run their FLHs? Doesn't the percentage shares try to match the output of heat to the demand for heat and how would this work if user only choses units? 

Also see issue https://github.com/quintel/etmodel/issues/2278 about distribution of heat between technologies.

**Comment by TessColijn** [comment]
@AlexanderWirtz @jorisberkhout 
From a discussion with Chael we have come to the following conclusions:

1. If we make Agriculture_CHPs dispatchable we have to disregard the fixed FLHs and allow them to be flexible. In that case to determine Energy output: ``E = FLH * Cap/unit * NoU`` number of units need to be determined and this could be in the form of a user input slider as is the case now. This also enables the user to adjust installed capacity for a growing demand. 

2. Furthermore to distinguish between shortages occuring at different locations/ at different technologies, we could add the three different CHPs as percentage shares for the user instead of a total CHP share. This would give way to enable both surpluses for one CHP technology and shortages with other CHP technologies. For example if Percentage share of each CHP technology is determined at 10 % and according to merit order Gas_CHPs can provide 12 % of heat demand, but wood_pellets_CHPs can only provide 8% of energy demand, then user and model can still distinguish between the two and decide that we need 2 % of heat demand from backup gas boilers while we also have 2 % surplus in some greenhouses.

Does this make sense and if so do you agree?

**Comment by TessColijn** [comment]
@ChaelKruip  if we make the agriculture CHPs dispatchable. Wouldn't it also make more sense to relocate the slider for the number of units to the Supply section of the model, together with all the other electricity production?

**Comment by michieldenhaan** [comment]
Closing, CHPs are now dispatchable in Merit, marginal costs for steam cycle CHPs have been adjusted. Heat demand calculation is time-resolved
