### ISSUE TITLE
DIfferent Technologies for Heat in agriculture

### ISSUE THREAD

**Issue by TessColijn** [quintel/etmodel#2278]
How will different technologies be implemented?

Currently user can determine percentage shares of heat produced for each technology:

![image](https://cloud.githubusercontent.com/assets/22587085/19553343/2474c118-96b4-11e6-84ba-baf3df14255d.png)

Furthermore user can also determine number of units of CHPs:

![image](https://cloud.githubusercontent.com/assets/22587085/19553367/489ecb92-96b4-11e6-8c45-51e6c95896f2.png)

If we make CHPs dispatchable we might want to  reconsider what user input we want to have for CHPs. 

Do we need users to determine the number of units of CHPs?
Would it be an option to combine the two inputs pictured above and also give each CHP type a percentage share?

**Comment by TessColijn** [comment]
@AlexanderWirtz linking this to your comments within issue #2277 

Do we need users to determine the number of units of CHPs?
Would it be an option to combine the two inputs pictured above and also give each CHP type a percentage share?

**Comment by TessColijn** [comment]
After further discussions i have come to the following standpoint:

It seems a bit counterintuitive to let user chose percentages to fill the heat demand and only as a second stage determine number of units. In this way the user is enabled to chose a percentage share of heat demand for CHPs that the CHPs might not be able to fulfill and thus the user is confronted with an inevitable shortage which he can solve by adding more units or readjusting the percentage shares.

Shouldn't the question to the user be; How many CHPs of each type do you want in the agriculture sector? (This would also enable choices related to sustainability such as choosing solely biogas CHPs instead of network gas). 

Choosing the number of units, and providing the merit order is on, the user could already get feedback on how much percentage of the full heat demand the CHPs can fulfill, and then make choices about how other technologies could be implemented to ensure the full heat demand is met. If we want to take an approach along these lines we have to consider what happens to the idea of backup boilers? The percentage of the final heat that a CHP can fulfill is also different form the percentage share that the CHP will fulfill based on the electricity merit order (The latter might also vary on an hourly basis). Maybe a distinction between these two will help to decide when backup burner is switched on. 

The percentage of the final heat demand that a CHP can produce is fixed as a CHP can only deliver heat at its location. The percentage share for CHPs is limited by the number of units and the heat demand of one location. Anything produced beyond that will not count towards the useable heat supply. Thus another consideration was to include this limit within the input for percentage shares for the various technologies. But from Chael i understood that this would enable unwanted features where the input from one slider affects the inputs of other sliders.

**Comment by michieldenhaan** [comment]
Closing, no longer relevant with time-resolved heat network implementation
