### ISSUE TITLE
Feedback on agriculture CHPs for user

### ISSUE THREAD

**Issue by TessColijn** [quintel/etmodel#2279]
What information is provided to user about agriculture CHPs and in which form?

**User wants to know:**
- Shortage/Surplus of heat and where this shortage/surplus occurs
- Number of units of each technology installed
- FLH of each technology
- Electricity price

Merit Order can provide:
- Electricity Prices 
- FLHs of the 3 different agriculture CHPs

A heat demand balance could provide:
- Shortage/Surplus of heat

User input:
- Determine number of units of each technology installed

**Comment by michieldenhaan** [comment]
Closing, CHPs are now dispatchable in Merit, marginal costs for steam cycle CHPs have been adjusted. Heat demand calculation is time-resolved
