### ISSUE TITLE
Marginal Costs of Agriculture CHPs

### ISSUE THREAD

**Issue by TessColijn** [quintel/etmodel#2281]
How will marginal costs be determined for electricity production to enable a fair representation in merit order? Please also refer to issue quintel/etsource#236

**Comment by TessColijn** [comment]
From Chael's previous comment:

>How will marginal costs be determined for electricity production to enable a fair representation in merit order? Please see issue quintel/etsource#236
I think that issue deals primarily with the 'energy' CHPs which typically have a heat contract. As we are talking about agricultural CHPs (which can't sell their heat nor adjust their efficiency for making electricity), the issue of what their marginal costs should in the electricity merit order is a bit more subtle:

If no heat is needed: marginal costs should include fuel costs for both electricity and heat
If heat is needed:
If cost for running CHP < cost for running backup heater: marginal costs are zero (this never happens)
If costs for running CHP > cost for running backup heater: marginal costs are difference between costs for running CHP and running backup heater. This can likely be approximated well by setting the marginal costs to exclude the heat production part (as proposed in quintel/etsource#236).
@AlexanderWirtz does this make sense to you as well?

**Comment by TessColijn** [comment]
If we make assumptions about the heat demand per location of CHP, we know how much of the heat produced by a CHP is useable. And this will have to be evaluated per hour. At every hour the inputs used for the production of the useable heat will need to be evaluated and a distinction need to be made.

The equation mention in quintel/etsource#236:

`fuel_used_for_heat = total_fuel_input * (heat_efficiency / (heat_efficiency + electrical_efficiency))`

Should only applied for the fuel inputs for useable heat. And this amount of fuel need for useable heat varies on a hourly basis depending on the heat demand. Is it possible to couple the marginal costs of CHPs to the heat demand of one location?

**Comment by michieldenhaan** [comment]
Closing, CHPs are now dispatchable in Merit, marginal costs for steam cycle CHPs have been adjusted
