### ISSUE TITLE
Surplus in heat balance for agriculture

### ISSUE THREAD

**Issue by TessColijn** [quintel/etmodel#2282]
What happens in the case of a surplus of heat produced by agriculture CHPs?

Is it sufficient to say that heat is lost and just indicate the heat produced as a surplus?
Or would user be encouraged to decrease share of heat produced by other technologies? Can we expect user to make this conclusion himself?

**Comment by ChaelKruip** [comment]
> Is it sufficient to say that heat is lost and just indicate the heat produced as a surplus?

I think that is the least we can do yes.

> Or would user be encouraged to decrease share of heat produced by other technologies?

I don't think so. When there is an imbalance in the electricity production, the user is not warned explicitly either.

**Comment by michieldenhaan** [comment]
Closing, CHPs are now dispatchable in Merit, marginal costs for steam cycle CHPs have been adjusted. Heat demand and supply calculation is now time-resolved
