### ISSUE TITLE
Pop-up chart CO2 could be a lot more interesting.

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2283]
The current pop-up chart for CO2 (when you click the dashboard) is rather _flat_:

![image](https://cloud.githubusercontent.com/assets/104830/19646601/76940abe-99fa-11e6-8f3d-cd06a6f6a025.png)

We already have a more in-dept analysis of the CO2-emissions per sector:

![image](https://cloud.githubusercontent.com/assets/104830/19646612/7f9d9fee-99fa-11e6-85ae-3dc464c49594.png)

The pop-up chart would be a lot more informative when we would integrate the second chart above. I would prefer to keep the three columns rather, then we can keep the red line for the set target.

**Comment by ChaelKruip** [comment]
I am in favour of this 👍 
The three-bar chart is a bit custom, I think @jorisberkhout or @antw know how to do this best. With some help I could also pick this up.

**Comment by jorisberkhout** [comment]
I like the idea of integrating those charts!

**Comment by dennisschoenmakers** [comment]
@ploh could you pick this up?

**Comment by ploh** [comment]
My current implementation draft looks like this (I know that the scaling is off. Will fix it):
![picture3](https://cloud.githubusercontent.com/assets/768025/20428744/f5f0d97e-ad8a-11e6-8fe0-0b2516e1a812.png)

**Comment by ploh** [comment]
@jorisberkhout @dennisschoenmakers I compared the gqueries of the old 3 bar chart and the new (resp. the old 2 bar chart).
The old computes the domestic co2 as `V(G(final_demand_group),primary_co2_emission).sum`
The new does `SUM(V(INTERSECTION(G(final_demand_group),SECTOR(households)), primary_co2_emission))` and stacks that for the 7 sectors shown above.

Is that guaranteed to be equal or could it happen that some of the `final_demand_group` is in none of the 7 sectors?

**Comment by ploh** [comment]
Reopened because of [open question](#issuecomment-261514118)

**Comment by ploh** [comment]
@ChaelKruip Could you please have a look at the (probably very easy) [open question](#issuecomment-261514118) above

**Comment by ChaelKruip** [comment]
> Is that guaranteed to be equal or could it happen that some of the final_demand_group is in none of the 7 sectors?

I think this is guaranteed. You can easily check this yourself by using:
```
TXT_TABLE(G(final_demand_group), key)
```

In the sandbox.
