### ISSUE TITLE
Demand and supply of electricity are not the same in the start year for most datasets

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2285]
As observed in the following chart for a fresh NL scenario.

<img width="610" alt="screen shot 2016-10-25 at 14 49 33" src="https://cloud.githubusercontent.com/assets/4669028/19686663/7edd73d6-9ac2-11e6-8097-51e3b7cf686f.png">

This happens for all datasets except `uk` and `br`, which seems to suggest that something is wrong in the dataset. I'll look into this soon.

**Comment by ChaelKruip** [comment]
This issue seems to be related to the final demand groups. Since https://github.com/quintel/etsource/commit/b66736b917ef389bacf40d8b803345476ae39d27, this seems to be resolved. I don't fully understand how and why though. Closing nevertheless.
