### ISSUE TITLE
Co2 is wrongly formatted in change menu

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2288]
Witnessed in Dutch

**Comment by grdw** [comment]
What is the 'change menu exactly'?

**Comment by dennisschoenmakers** [comment]
> What is the 'change menu exactly'?

![image](https://cloud.githubusercontent.com/assets/104830/19960291/35d65086-a1ac-11e6-9199-19c06445926c.png)

**Comment by dennisschoenmakers** [comment]
Perhaps something @ploh can have a go at?

**Comment by grdw** [comment]
I think so 👍 maybe to get a bit of a feel for ETModel.
