### ISSUE TITLE
New dashboard item: sustainability percentage for the household sector.

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2299]
For Ameland, people want to see in the dashboard that the household sector is (e.g.) 100% sustainable rather than 40% of the *whole* energy system.

We would need to add a dashboard item that can be selected from the [**change menu**](https://cloud.githubusercontent.com/assets/104830/20217645/14f76adc-a821-11e6-8971-40cc57f67962.png).

In the change menu, a third item would be be added under *renewables*:

* Total share of renewable energy
* Total share of renewable electricity
* **Household share of renewable energy**

For your information, @ploh: 
* In the backend, a dashboard item is called a *constraint* :smirk:
* You will reed to write a gquery yourself in ETSource to calculate this, look at the other two ('total share of renewable energy' and 'total share of renewable electricity'). Test it locally, there is also a [**sandbox**](https://beta-engine.energytransitionmodel.com/data/latest/gqueries/test) available.
* Add NL and EN translations, no worries if the Dutch is off, we'll fix it.

**Comment by ploh** [comment]
you wrote "Household share of renewable energy" as title for the new _constraint_. i would rather suggest "Share of renewable energy in the household sector" because otherwise it could mean the share of the renewable energy that is used in households compared to renewable energy in all sectors

**Comment by dennisschoenmakers** [comment]
A gquery that can compute the renewability share **in** the household sector:

```
DIVIDE(V(INTERSECTION(G(final_demand_group),SECTOR(households)),"demand*sustainability_share").sum,V(INTERSECTION(G(final_demand_group),SECTOR(households)),"demand").sum)
```

**Comment by dennisschoenmakers** [comment]
We by the way can easily compute renewability shares **in** other sector by varying the SECTOR(parameter):

```
DIVIDE(V(INTERSECTION(G(final_demand_group),SECTOR(industry)),"demand*sustainability_share").sum,V(INTERSECTION(G(final_demand_group),SECTOR(industry)),"demand").sum)
```

**Comment by ploh** [comment]
@jorisberkhout Comparing your gquery for the new sustainability share in households
https://github.com/quintel/etsource/compare/sustainability_in_households
with the existing sustainability share of total final demand
https://github.com/quintel/etsource/blob/master/gqueries/general/shares/renewability.gql
I have two questions:
1. Should the `USE(energetic)` also occur in the new gquery? In the same way as in the old one or would that be wrong?
2. Should the _ambient heat_ also be respected in the new gquery? And if so, how?

**Comment by ploh** [comment]
Reopened because of [open question](#issuecomment-260925027)

**Comment by ploh** [comment]
@ChaelKruip Could you please have a look at the [open question](#issuecomment-260925027) above

**Comment by ChaelKruip** [comment]
> @ChaelKruip Could you please have a look at the open question above

1. Yes. Non-energetic demand (think of use of oil as a lubricant) is normally excluded from this calculation and will be small in households.
2. Yes. I think we should make one new query to be included in both numerator and denominator (analogous to the national query) which quantify the use of ambient heat in heat pumps in this sector.

The query:
```
- unit = MJ
- query =
    V(
    	households_water_heater_heatpump_ground_water_electricity,
    	households_water_heater_heatpump_air_water_electricity,
    	households_space_heater_heatpump_air_water_electricity,
    	households_space_heater_heatpump_ground_water_electricity,
    	households_space_heater_hybrid_heatpump_air_water_electricity,
        households_water_heater_hybrid_heatpump_air_water_electricity,
    	input_of_ambient_heat
    ).sum
```
