### ISSUE TITLE
Should the slider for wind turbines show installed capacity rather than number of wind turbines?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2303]
As suggested by John, we are often calculating the installed capacities from the slider setting which indicates the number of wind turbines. Why not make the slider display the installed capacity instead?

Alternatively, we could leave the slider the way it is and display the installed capacity to the left of it like we do for the fuel prizes.

What do you think @AlexanderWirtz , @dennisschoenmakers , @ChaelKruip , @antw and @DorinevanderVlies ?

**Comment by DorinevanderVlies** [comment]
I agree that installed capacity is indeed a better slider than number of wind turbines. 

Currently I often find myself calculation from installed capacity back to number of turbines to set the slider.

**Comment by AlexanderWirtz** [comment]
hallelujah! Hopefully we can finally get rid of the odd 'number_of' sliders and just show installed capacity for all large scale power producers, including wind turbines.

**Comment by jorisberkhout** [comment]
> hallelujah! Hopefully we can finally get rid of the odd 'number_of' sliders and just show installed capacity for all large scale power producers, including wind turbines.

Really, I didn't know that you were leaning towards that solution. I'm all in favour!

**Comment by dennisschoenmakers** [comment]
Yes yes yes!!!!

**Comment by antw** [comment]
> Alternatively, we could leave the slider the way it is and display the installed capacity to the left of it like we do for the fuel prizes.

This would require a bit of work, but I like this a lot. If you prefer, we could still use capacity as the base unit and number of units as the label to the left of the slider. Currently those labels work only with inputs whose unit is `%`, but I doubt it would be too hard to make it more flexible.

Neither strike me as *ideal* – I have no idea what 1GW of wind energy means, nor whether 100 wind turbines is a lot – but then I'm not really the target audience for the ETM, so it comes down to whatever our users will find more natural. I have no strong opinion. :smiley:

**Comment by DorinevanderVlies** [comment]
> but then I'm not really the target audience for the ETM

Spoken like a true programmer. :wink:

>Alternatively, we could leave the slider the way it is and display the installed capacity to the left of it like we do for the fuel prizes.

The other way round could be an option as well. Slider for total capacity with conversion to # of units next to it. I'm not hugely in favour of this as it rises the same issues with the slightly arbitrary individual capacity.

**Comment by marliekeverweij** [comment]
Fixed! https://github.com/quintel/etsource/commit/ea912ae2244bca7f9b7423d08fa44697e659854f
