### ISSUE TITLE
%/year appears twice

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2304]
I guess this is not intended, right? Now it says %/year in grey in the group, and also as the unit behind the slider:

![image](https://cloud.githubusercontent.com/assets/104830/20435077/ef93b4a0-adaa-11e6-912a-cef5bd845f8e.png)

**Comment by jorisberkhout** [comment]
I believe this is a result of the discussion in https://github.com/quintel/etmodel/issues/2207, but I agree with @dennisschoenmakers that this should look different. I will look into this.

**Comment by ChaelKruip** [comment]
Fixed by @MartLubben
