### ISSUE TITLE
Three JS and the possible use and inspiration of 3D in ETModel

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2305]
I was sort of overlooking some meetings of other people within Quintel and saw (while walking for tea) that some (or it was just one) of them were presenting a 3D representation of a certain area with 3D windmills and houses. 

I was just looking at [ThreeJS](https://threejs.org/) which uses OpenGL to create interactive 3D objects and animations inside of the browser. I don't know where we might use this for, yet. But I hope this issue might spark the imagination by some of the Quintellers that were actually in that meeting (or weren't in that meeting for that matter). 

Obviously ThreeJS is now mainly used in art, advertisement and games but it might also be useful to us. For example this [Renault car](http://renaultespace.littleworkshop.fr/) is completely created with ThreeJs or this game with a fairly ok looking [planet with a house](http://collinhover.github.io/kaiopua/). It would be cool if you could draw something more real life to visually convince a user. 

Another example of using this library would be for 3D graphs (however useful those may be); an example [here](http://output.jsbin.com/yezoyenise/1). 

Or for fun just [looking at the stars](http://stars.chromeexperiments.com/) 🚀 

----

I've created this issue purely as discussion for another tool we might use. Don't know if we will but it does look rather amazing (just my 2 cents).

**Comment by dennisschoenmakers** [comment]
> Or for fun just looking at the stars 🚀

Cool. This reminds me of a long holiday I once took.

**Comment by AlexanderWirtz** [comment]
unassigning myself

**Comment by ChaelKruip** [comment]
Closing as this is not very actionable.
