### ISSUE TITLE
Where does the 19.8 kWh come from?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2307]
It seems a bit large to me, as the new Tesla Powerwall is 14 kWh.

**Comment by DorinevanderVlies** [comment]
This is indeed a large battery. It was discussed in issue #2189 (part of which is quoted below).

For calculations regaring the battery see: households_flexibility_p2p_electricity.converter.xlsx in ETDataset - Node source analyses - households.

> Note:
20 kWh is a large battery as the average electricity consumption of a household is 10 kWh. Implementing a bigger battery will be unrealistic. If more battery storage has to be implemented I propose to create a new attribute/converter for commercial batteries. Once that attribute/converter has been created I think it would be good to reset the household battery to the more realistic storage volume of 9.6 kWh.

**Comment by jorisberkhout** [comment]
I hope this answers your question, @dennisschoenmakers . Closing this issue. Re-open if you disagree.

**Comment by dennisschoenmakers** [comment]
Thanks

Sent from my iPhone

On 6 Jan 2017, at 16:46, Joris Berkhout <notifications@github.com> wrote:

I hope this answers your question, @dennisschoenmakers
<https://github.com/dennisschoenmakers> . Closing this issue. Re-open if
you disagree.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/quintel/etmodel/issues/2307#issuecomment-270931741>,
or mute
the thread
