### ISSUE TITLE
Scaling of FCE charts cuts off some series

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2316]
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/21422600/aeb708a8-c838-11e6-82a1-a475cd898edb.png)

Related: https://github.com/quintel/etmodel/issues/2225

**Comment by marliekeverweij** [comment]
FCE is not used anymore in the ETM and supposed to be deleted (see #2986). So closing this issue :)
