### ISSUE TITLE
Electricity demand and supply do not match

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2318]
![energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_](https://cloud.githubusercontent.com/assets/1303760/21426334/a7390d04-c84e-11e6-96ba-a6ed6b269923.png)

Observed in [this scenario](https://pro.energytransitionmodel.com/scenarios/308870)

**Comment by DorinevanderVlies** [comment]
is related to #2314

**Comment by ChaelKruip** [comment]
Closing because duplicate
