### ISSUE TITLE
unitialized constant Api::Area::Scaling

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2322]
![screen shot 2017-01-16 at 10 55 37](https://cloud.githubusercontent.com/assets/2676542/21978305/5611699a-dbda-11e6-81c9-92f8e3cb8119.png)

When loading ETModel locally there's a problem with an unknown constant being present in the codebase. This is only fixable when removing the ETModel cookie and refreshing the page. 

@ploh didn't you know how to fix this?

**Comment by ploh** [comment]
Already fixed in quintel/atlas@84c542e3fda389 a couple days ago
