### ISSUE TITLE
Applying (national) scenario slider settings on local scenario's

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2323]
We will soon be having two ways to make local scenario's:

* Currently, local (scaled) scenario's can be constructed with the [scaling interface](https://pro.energytransitionmodel.com/scaled) resulting in a local scenario which takes into account the sliders already set in the parent scenario. This is very useful if you want to see what the implications of a certain national scenario could be on your local situation. 
* The new functionality creates local datasets from national (parent) datasets. Although this has several important advantages, it is unclear yet if/how to apply a set of (national) choices to a scenario based on a local dataset easily

Not very urgent or critical but good to keep in mind IMO

**Comment by ChaelKruip** [comment]
Including @AlexanderWirtz @jorisberkhout @DorinevanderVlies @dennisschoenmakers

**Comment by grdw** [comment]
Is this issue - or question rather - still relevant? If so, how?

**Comment by marliekeverweij** [comment]
I think this tool made by @antw fixes this issue https://github.com/quintel/etm-tools/tree/master/cp-scenario. Right?
