### ISSUE TITLE
Synchronize seeds.rb file with the beta environment database rows

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2326]
The `seeds.rb` file and the staging database should be in synch. I know a lot of people use `bundle exec cap staging db2local` but that doesn't work if your SSH key is not installed on the server. Unfortunately because I have multiple laptops, I have multiple SSH keys. I should probably copy my keys over from my Mac but somehow I feel that someone without 'server access' should also be able to synchronize the database.

**Comment by ChaelKruip** [comment]
@grdw can you please give short descriptions/context of your issues (even if you are the only one assigned). This will help our future selves to solve problems that occurred before.

Is this about the database? Why are these files no longer synchronised?

**Comment by grdw** [comment]
Closing this issue. 👍
