### ISSUE TITLE
How to scale scenarios with a derived dataset.

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2328]
#### Should this really be supported?

As @ChaelKruip stated [here](https://github.com/quintel/etengine/pull/900#discussion_r96601564) it should.

#### I'm trying this out currently and am stumbling against a very big hurdle which I'll explain:

Assume 3 scenarios:

1. A scenario NL with residences = 1.000.000
2. A scenario with a derived dataset Lutjebroek with residences = 1.000
3. A scenario with a derived dataset scaled; presumably a street inside of Lutjebroek with residences = 100

When creating a scenario your `min_value` and `max_value` for an input are set to x. 
For example a `max_value` of an input is set to 20.000. When you look at the scenarios that `max_value` is expected to look like:

1. 20.000
2. 20
3. 0.02

What actually happens is the following

1. 20.000
2. 20
3. 2.000

The scaling factor between scenario 1 and 2 is 1.000, however the scaling factor between 2 and 3 is 10 so the original `max_value` is just divided by 10 and will result in 2.000. This obviously doesn't work and I'm not sure how to solve this without it getting rather hacky. And that brings us back to point number 1, should we really support this.

**Comment by grdw** [comment]
Including @ChaelKruip @antw @ploh

**Comment by grdw** [comment]
I could set the correct `base_value` though when a scaler is created. 🤔

**Comment by ploh** [comment]
I think this would be a useful feature, as Chael already pointed out. But it is definitely not something that is mission-critical for the derived datasets.
So I suggest to put this on hold for now.

**Comment by grdw** [comment]
> So I suggest to put this on hold for now.

But even if we aren't going to support it.  It's either: yes we are going to build it. Or no: we're going to prevent the user from scaling a scenario with a derived dataset. Right now it's possible and it will give you a really buggy scenario.

So what's it going to be 😅

**Comment by ploh** [comment]
> Right now it's possible and it will give you a really buggy scenario.

You are right, of course, that we should not keep it at like that :smirk: 

So, please prevent this for now.

**Comment by grdw** [comment]
We could for example check if a user is using a derived dataset in his or her scenario and disable this button in the front-end:

![screen shot 2017-01-18 at 17 00 00](https://cloud.githubusercontent.com/assets/2676542/22071473/92139820-dd9f-11e6-86fa-1ba508ecc0c6.png)


And redirect to his scenario when he visits the `scaled_path (/scaled)`

**Comment by antw** [comment]
I do think this should be supported. Otherwise it's a very inconsistent user experience to allow scaling of scenarios belonging to one region but not another; it's not obvious why an "nl" scenario can be scaled, but an "ameland" one cannot.

I agree this is not critical, but it would be nice to aim to do this before everything is merged into master and deployed.

> I could set the correct base_value though when a scaler is created. 

Does it work correctly if you do this?

**Comment by ploh** [comment]
Side note: The problem with further scaling of a derived dataset lies probably only in the _input_ handling. The graph and gqueries should be fine.

**Comment by grdw** [comment]
> Does it work correctly if you do this?

Currently: no.

The population slider is freezing up.. 

Before scaling:
![screen shot 2017-01-18 at 17 09 09](https://cloud.githubusercontent.com/assets/2676542/22071884/e07b05d8-dda0-11e6-9921-6bce86c3d270.png)
 
After scaling:
![screen shot 2017-01-18 at 17 10 48](https://cloud.githubusercontent.com/assets/2676542/22071962/14c7876c-dda1-11e6-8033-dc6f313fd6de.png)

This is with the old settings though. If you however alter the `base_value` (I know directly alter the databse row for a scaling) there's no change in behavior.

**Comment by grdw** [comment]
It could be that the wrong `Input` object is cached though - which causes this behavior - because either `scaled` and `derived` both point to the same `Input.cache` object.

**Comment by grdw** [comment]
> I could set the correct base_value though when a scaler is created.

Okay, this is a really bad idea because the population will be incorrectly determined. 

Namely because it will multiply the scaling factor (500 / 7449300) against the `number_of_residences` of the parent scenario: 

![screen shot 2017-01-18 at 17 25 13](https://cloud.githubusercontent.com/assets/2676542/22072587/19e7e91a-dda3-11e6-9691-1dce020256dd.png)

0.2 people does look a bit odd 😆

**Comment by antw** [comment]
> It could be that the wrong Input object is cached though - which causes this behavior - because either scaled and derived scenarios both point to the same Input.cache object.

Could this be because both the derived area and the scenario have a `scaling` setting, and ETModel only uses one of them? Or are the input values being scaled incorrectly in ETEngine?

> We could for example check if a user is using a derived dataset in his or her scenario and disable the 'Scale this graph' button in the front-end.

**Comment by grdw** [comment]
Value for slider `households_number_of_inhabitants`:

```ruby
# Min/max
{:min=>0.0011262520978486833,
:max=>0.004505008391394733,
:default=>0.0022525041956973665 }

# Step
{:step=>1.0e-05}
```

Values for `households_number_of_inhabitants` scaled:

```ruby
{:step=>0.01}

{:min=>0.00011262520978486832, 
 :max=>0.0004505008391394733
:default=> 0.00022525041956973665
```

So as far as I can see the `step` is incorrect. It should be `0.01 * 1.0e-05 = 1.0e-07`.

**Comment by grdw** [comment]
I've corrected the step like this:

```ruby
  def input_step_multiplier
    if scenario && scenario.parent && scenario.parent.area[:derived]
      multiplier * self.class.from_atlas_scaling(scenario.parent.area[:scaling]).multiplier
    else
      multiplier
    end
  end
```

However, this feels really really really hacky. What if I were to scale this scenario again? I'd probably have to check the `scenario.parent.parent` etc. This is going to suck. What I also can't seem to understand is that the `min_value` and `max_value` etc. are correctly scaled. Because if I do this:

```ruby
  def multiplier
    @multiplier ||= (value.to_f / base_value) * input_step_multiplier
  end

  def input_step_multiplier
    if scenario && scenario.parent && scenario.parent.area[:derived]
      self.class.from_atlas_scaling(scenario.parent.area[:scaling]).multiplier
    else
      1.0
    end
  end
```

Everything is destroyed but the `step`.

Also writing specs for this code is nearly impossible because it's so dodgy.

**Comment by antw** [comment]
> This is going to be bad. What I also can't seem to understand is that the min_value and max_value etc. are correctly scaled.

Presumably because inputs tested get their start/min/max values from `_gql` attributes which query the (scaled down) graph. These are not scaled by `value * multiplier`.

Try testing with an input which uses a scaleable `unit` and hard-coded start/min/max values and I expect you'll find that the `step_value` problem is also true of hard-coded start/min/max. For example: [number_of_energy_flexibility_p2g_electricity](https://github.com/quintel/etsource/blob/master/inputs/flexibility/energy/number_of_energy_flexibility_p2g_electricity.ad).

> However, this feels really really really hacky. [...] Also writing specs for this code is a bit hard.

Agreed. The ability to test it thoroughly is essential, and with all these moving pieces I can see that becoming difficult.

**Comment by ploh** [comment]
> > However, this feels really really really hacky. [...] Also writing specs for this code is a bit hard.

> Agreed. The ability to test it thoroughly is essential, and with all these moving pieces I can see that becoming difficult.

So maybe it is now time to rethink the approach of re-using the "scaled-scenario" input range scaling and instead to the "right thing" and improve/repair the automatic setting of input ranges, i.e. set the input range (and possibly the displayed unit) automatically depending on the current value - even if the current value is orders of magnitude different from what you once expected!?

**Comment by grdw** [comment]
> [..] (and possibly the displayed unit) automatically depending on the current value

I'm not sure I understand this. Could you maybe expand it a little?

As far as I know though this partially happens in the front-end of ETModel. To elaborate: each input inside of ETSource doesn't need to correspond to a slider. To create a slider you'll need to create an `InputElement` inside of ETModel. The `InputElement` has a default `unit`. From that `unit` in combination with the value from ETEngine the 'formatting' takes place in the front-end. However, the `min_value`, `max_value` etc. are all scaled inside of ETEngine. 

So maybe you're right though. Those `min_value`, `max_value` properties should not be scaled inside of ETEngine but should be correctly formatted in the front-end? Or I could be misinterpreting what you are saying and I'm dwelling of the topic.. 😅

**Comment by antw** [comment]
> So maybe you're right though. Those min_value, max_value properties should not be scaled inside of ETEngine but should be correctly formatted in the front-end?

They do need to be scaled in ETEngine since it validates that `min_value` <= `user_value` <= `max_value`. And I think it makes no sense for inputs.json for a derived region to return unscaled values for the full-size region; API users would expect the values to be consistent with the size of the region.

I've posted an ETSource issue which might help us get around this problem: quintel/etsource#1213. Feedback would be very welcome. :gift:
