### ISSUE TITLE
Does the amount of gas used by CHP for heat networks include gas use for electricity production?

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2330]
This chart seems to suggest a lot of gas is used by CHPs for the local heat network. alsmost as much as  geothermal heat, even though the slider settings say 70% geothermal and 30% gas CHP:

![image](https://cloud.githubusercontent.com/assets/308563/22148687/d997c6d2-df0f-11e6-8717-f57279b91cfa.png)

This caused me to wonder: is the gas use for electricity production accidentally included?

Assigning @ChaelKruip feel free to reassign.

**Comment by ChaelKruip** [comment]
Yes, incorrectly so I'm afraid 😞 
```
SUM(
  V(CHILDREN(V(households_final_demand_steam_hot_water)),input_of_natural_gas),
  V(CHILDREN(V(households_final_demand_steam_hot_water)),input_of_lng),
  V(CHILDREN(V(households_final_demand_steam_hot_water)),input_of_network_gas),
  V(CHILDREN(V(households_final_demand_steam_hot_water)),input_of_gas_power_fuelmix),
  V(CHILDREN(V(households_final_demand_steam_hot_water)),input_of_compressed_network_gas)      
) / BILLIONS
```
Correcting this would need need some tricky queries though. They would have to become technology dependent and take the output conversions of the CHPs into account:
```
gas_for_heat_from_chp = gas_input * output_of_heat / (output_of_heat + output_of_electricity)
```

**Comment by AlexanderWirtz** [comment]
@ChaelKruip I understand it is tricky, but surely it is not beyond the mighty modellers of the ETM to correctly calculate the amount of gas used for CHP heat production? Does this merit creating a method?

notifying @jorisberkhout @dennisschoenmakers @antw

**Comment by ChaelKruip** [comment]
> ...but surely it is not beyond the mighty modellers of the ETM...

I see what you did there @AlexanderWirtz! Although I'm very susceptible to flattery I think we should not rush into a hacky solution for this. 

> Does this merit creating a method?

@antw do you think that something like:
```
<carrier>_for_heat = <carrier>_input * output_of_heat / (output_of_heat + output_of_electricity || 0)
```
could be incorporated in ETEngine?

**Comment by AlexanderWirtz** [comment]
@antw and @ChaelKruip creating a method would also help us in finally tackling the issue where CHP marginal costs are calculated based on all fuel input, rather than just the fuel input for power production. Granted, that would be the inverse query (or is it obverse?)

**Comment by michieldenhaan** [comment]
Closing, chart doesn't exit anymore ✌️
