### ISSUE TITLE
How to secure that researchers have a smooth workflow?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2331]
There are several aspects to this question:
* What if the local installation of ETE, ETM, Atlas etc. does not work on a researchers computer?
* How to link data-analyses on ETDataset and commits on ETSource?
* How do you ensure that data-commits and functionality-commits are kept separated?

**Comment by ploh** [comment]
> What if the local installation of ETE, ETM, Atlas etc. does not work on a researchers computer?

Alex said that this should not be a problem for the moment. Maybe the "rapid-prototyping" is gonna be needed in the future, but for now it is fine to modify etsource and test locally.

> How to link data-analyses on ETDataset and commits on ETSource?
> How do you ensure that data-commits and functionality-commits are kept separated?

Are those problems not the same for local datasets as for national datasets? How are they handled there? Can it be done in the same way for local datasets?

**Comment by ChaelKruip** [comment]
> Alex said that this should not be a problem for the moment. Maybe the "rapid-prototyping" is gonna be needed in the future, but for now it is fine to modify etsource and test locally.

Sorry for not being clear. @AlexanderWirtz and myself are worried that by relying on 'running the model locally' will introduce a lot of ad-hoc requests for assistance from @antw and @grdw. Although discouraged for many reasons, the rapid prototyping using the database has as a big advantage that you can do it without having a local setup of the ETM universe running properly. In other words: perhaps we should keep looking into ways to quickly set up the ETM as a 'package' on any laptop without any need for technical assistance.

> Are those problems not the same for local datasets as for national datasets? 

Yes.

> How are they handled there? 

By strong discipline amongst researchers (either commit data *or* changes to the machinery) and by the virtue of Excel files that are highly automated to automatically read in and erase all data-fields.

Can it be done in the same way for local datasets?

Yes but that will take time from someone able to create those Excel files like @jorisberkhout who is currently too busy with other things.

**Comment by ploh** [comment]
> Although discouraged for many reasons, the rapid prototyping using the database has as a big advantage that you can do it without having a local setup of the ETM universe running properly. In other words: perhaps we should keep looking into ways to quickly set up the ETM as a 'package' on any laptop without any need for technical assistance.

So, how do we proceed in this matter now? My suggestion: We continue with making the InitializerInputs disjoint from the Inputs, i.e. the former may only be used in derived datasets whereas the latter may only be used in user_values. If we later see that we need some more convenient way for prototyping a new derived dataset, we introduce some mechanism to add initializer inputs to a scenario at runtime, i.e. temporary init. inputs that only belong to one scenario but not the underlying dataset.

**Comment by antw** [comment]
> perhaps we should keep looking into ways to quickly set up the ETM as a 'package' on any laptop without any need for technical assistance.

[This is on our radar](https://github.com/quintel/internal/issues/8). No ETA, but I think we're all quite keen on investigating this further.

**Comment by grdw** [comment]
> will introduce a lot of ad-hoc requests for assistance

> No ETA, but I think we're all quite keen on investigating this further.

Well, last week when the power was out in Amsterdam I already started at 8:00 in the morning. So I took the last hour of the day (my free time) to investigate it a little bit. It's not really done or anything but I read some articles + tutorials how to do this properly for a rails application.

**Comment by grdw** [comment]
This seems more like a discussion that needs to be held on basecamp. Still not 100% happy with Docker - this is mainly due to technical annoyances that keep popping up (I'll spare the details). 

I'll close this issue and revisit the whole containerization debate on Basecamp once time permits.
