### ISSUE TITLE
Why are there still logo's inside the app/assets/images/partners folder when all the images are on amazon?

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2339]
Are they used as a back-up in case Amazon S3 goes down?

**Comment by antw** [comment]
I've no idea. :thinking:

The images are served up by S3 via ETCentral's [Partners API](https://github.com/quintel/etcentral/blob/3fbee998695e55bf7aa061cf048b485eabe2d0fb/app/controllers/partners_controller.rb). There hasn't been a new image added to the ETM directory in more than four years, so perhaps they simply weren't removed when the system changed.

**Comment by grdw** [comment]
> they simply weren't removed when the system changed.

I guess they can be removed than 👍

**Comment by grdw** [comment]
Just figured out they are actually used in the footer of ETmodel, closing this issue.
