### ISSUE TITLE
'Show graph' option does not show on new scenario

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etmodel#2340]
In the settings menu, often the 'Show graph' option is not available. It does appear when you hit refresh.

**Comment by ChaelKruip** [comment]
@BerendSmits why am I assigned to this ticket? Assigned @antw instead.

**Comment by grdw** [comment]
I can't seem to reproduce this in Firefox 51.0.1.

**Steps:**

1. Start a new scenario
2. Check settings
3. See 'Show graph'

I tried signing in and see if that makes a difference but it doesn't. It can be, that while your scenario is still loading, that the Show graph button is not visible yet. But I'm not sure if that's the same thing you're experiencing.
