### ISSUE TITLE
Web-interface to improve and share local datasets

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2342]
This tickets summarises ideas from @dennisschoenmakers and @grdw to make first steps to opening up our local datasets.

# Background

We are creating more and more local datasets (Ameland, Groningen, Drenthe etc.) which live on the ETDataset repository. We will not be able to maintain and create such a dataset for each municipality (390 in our country) or neighbourhood (11000) ourselves. It will be inevitable that third parties are able to create and improve with little help from our side.

One possible 'far future' solution would be a 'Wikipedia'-like interface where many can work on one dataset with version control and peer-review. This will take a big time investment. This ticket explores a first step we could take towards the grand vision described above.

# First step

A very simple web-interface where people can:
* download the latest local datasets (and earlier versions)
* upload a new version of a dataset (with a new name)
* leave a mandatory 'commit message' with each new version about the changes

# Possible solutions 

@grdw has been looking into a 'git'-gem which allows you to link git commands to buttons etc.

# Open questions

* At what stage do we require login and proper account management?
* How do we synchronise our own datasets on ETDataset with the ever evolving ones on this new web-interface? Or should it link directly to ETDataset_public?
* What do we call this thing?

@AlexanderWirtz @antw @jorisberkhout @DorinevanderVlies @BerendSmits I am curious about your ideas and input!

**Comment by grdw** [comment]
> @grdw has been looking into a 'git'-gem which allows you to link git commands to buttons etc.

I'd like to add that this is purely a technical gateway to a solution. It's not really 'the solution'. I can imagine for example; that the structure of the dataset would be fixed and no newly named files can be added for they won't hold any significance (and to prevent people from misusing this application as their personal dropbox).

> [..] download the latest local datasets (and earlier versions)

Would that be a dump of `etsource/datasets/<name-of-dataset>` or would that be a dump of something-etdataset? 

> What do we call this thing?

I now named it `etgit`. Because the thing I'm trying out currently is literally a wrapper for git. But please feel free to name it something else.

> At what stage do we require login and proper account management?
> How do we synchronise our own datasets on ETDataset with the ever evolving ones on this new web-interface? Or should it link directly to ETDataset_public?

Just a quick question though, but wouldn't it be practical if we could build this as a separate module inside of etengine? Or does this really have the potential to become something separate?

**Comment by grdw** [comment]
I'm creating a bit of a larger overview [here](https://gist.github.com/grdw/a2c85e57c2b12110d6c8faa1a68470de). This is work in progress still.

**Comment by antw** [comment]
> Open questions

* How do we allow third-parties to edit datasets when the energy balance is proprietary, licensed to QI, and we are not permitted to redistribute it?

> We are creating more and more local datasets (Ameland, Groningen, Drenthe etc.) which live on the ETDataset repository. [...] One possible 'far future' solution would be a 'Wikipedia'-like interface where many can work on one dataset with version control and peer-review. 

Are these "full" datasets with a complete analysis (like NL, DE, etc)? Is it suggested that third-parties should be able to edit any of the XLS files in ETDataset and see the changes reflected in their custom region in ETEngine? To put it another way: at what point in the flow between `ETDataset → ETSource → Atlas/Refinery → (Optional: Local dataset) → ETEngine` will the user make their edits? 

> What do we call this thing?

Ambitious? 😀

**Comment by ChaelKruip** [comment]
> Are these "full" datasets with a complete analysis (like NL, DE, etc)? Is it suggested that third-parties should be able to edit any of the XLS files in ETDataset and see the changes reflected in their custom region in ETEngine? To put it another way: at what point in the flow between ETDataset → ETSource → Atlas/Refinery → (Optional: Local dataset) → ETEngine will the user make their edits?

This is for local (derived) datasets only. The user edits numbers in an Excel (the ETDataset point of the flow). For now, the rest of the work-flow is not altered.

> Ambitious? 😀
🤣

**Comment by grdw** [comment]
> The user edits numbers in an Excel (the ETDataset point of the flow). For now, the rest of the work-flow is not altered.

Just to be clear, this is a *single* xls file? If so, than I managed to create a supersimple dummy app that version controls a single xls upload through papertrail 👍  However, you can't really do that much with it 😆

**Comment by grdw** [comment]
I'll call the project [etcabinet](https://github.com/quintel/etcabinet) for now.

**Comment by ChaelKruip** [comment]
> Just to be clear, this is a single xls file?

One xls file *per* region. So Ameland.xls, Drenthe.xls, Paddepoel.xls etc.

> I'll call the project etcabinet for now.

Not that big of a deal but I think 'ETCabinet' is not a very sexy name. What about "ETPortal", or "ETLocal"?

**Comment by ChaelKruip** [comment]
Closing this as it has been superseded by a Trello board.
