### ISSUE TITLE
Possibility to link to a pop-up chart in a text

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2358]
I would like to be able to open a chart in a pop-up window from a link in text.

Specifically, I think it would be great to show the CO2-Sankey to users which click a link in the text of the current dashboard pop-up chart:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/23853789/842b98ba-07ee-11e7-8795-3d978ba0208a.png)

**Comment by ChaelKruip** [comment]
Is this difficult you think @antw?

**Comment by antw** [comment]
This is now available on beta. [The commit](https://github.com/quintel/etmodel/commit/3944995c8101948304453e7eaee33e02d5da3caf) contains some instructions, and I added an example to the *English* text for the CO<sub>2</sub> dashboard item:

```html
This chart shows the CO<sub>2</sub> emissions that result from the inland final
consumption of energy. If you have chosen to use Fuel Chain Emissions, these values
will also include other greenhouse gases.

Also see the <a
  href="#" class="open_chart"
  data-chart-key="co2_sankey"
>sankey chart of CO<sub>2</sub> emissions</a>.
```

**Comment by ChaelKruip** [comment]
Nice!
