### ISSUE TITLE
Overview of problems and questions regarding EV's (partly in local datasets)

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2360]
There are some problems with and questions regarding electric vehicles. 
Some of them are already mentioned in previous issues. As they are related I made this issue to bundle them.

I can solve number 4. For the others I think I need the expertise of @grdw or @antw.

- [x] 1. number_of_cars in a local dataset should not be defined by transport_useful_demand_car_kms
Related issue: https://github.com/quintel/etsource/issues/1253
- [x] 2. Number_of_units per vehicle type are incorrectly used
- [x] 3. Number_of_units per vehicle type are probably incorrectly defined
- [x] 4. electric_cars_additional_costs.gql should not be defined by initial_investment of transport_car_using_hydrogen

---
### 1 number_of_cars in a local dataset should not be defined by transport_useful_demand_car_kms
Related issue: #1253
For local dataset the number of cars is currently defined by `transport_useful_demand_car_kms`. This overwrites the area attribute `number_of_cars` which is set in the .ad-file.

@grdw has already pushed a commit which deletes the extra lines.
https://github.com/quintel/etsource/pull/1254/commits/01be6112be7d6975339f68a566b8a94ba42a80d6
I think the commit can be merged.

---
### 2 Number_of_units per vehicle type are incorrectly used
This is also discussed in:
https://github.com/quintel/etsource/issues/1223#issuecomment-277316959 
and (partly) fixed by
https://github.com/quintel/etsource/commit/92db5e85b3a01067d95a9b244c5319fa004afff2 

In local datasets I notice that, the even when EV's have a share of 0%, energy can be stored in EV's:
@antw, can it be that in merit `number_of_units` is still used instead of a query based on number of cars and shares?  

![image](https://cloud.githubusercontent.com/assets/19907658/24037449/227caaec-0afe-11e7-8eec-e1e90adf3f16.png)

---
### 3 Number_of_units per vehicle type are probably incorrectly defined
In issue https://github.com/quintel/etsource/issues/1223 is was discussed that gqueries should be independent of `number_of_units` for cars. This was fixed with https://github.com/quintel/etsource/commit/92db5e85b3a01067d95a9b244c5319fa004afff2. When I follow this reasoning it seems unnecessary to define `number_of_units` for cars at all. 

Proposal:
- Remove `number_of_units` from all car shares [like for EV's](
https://github.com/quintel/etsource/blob/ea7cc5af9be787f76df760b01f32744e77b8f561/inputs/demand/transport/transport_car/transport_car_using_electricity_share.ad). Or at least define the `number_of_units` for all car technologies based on `number_of_cars` multiplied with corresponding shares. 
- Remove the update of `number_of_units` from [transport_useful_demand_car_kms.ad](https://github.com/quintel/etsource/blob/ea7cc5af9be787f76df760b01f32744e77b8f561/inputs/demand/transport/transport_car/transport_useful_demand_car_kms.ad)? 

---
### 4 electric_cars_additional_costs.gql should not be defined by initial_investment of transport_car_using_hydrogen

This is the case for [electric_cars_additional_costs.gql](https://github.com/quintel/etsource/blob/9e497c279596ab1f2157180b675e6e0759fdb95b/gqueries/output_elements/output_series/vertical_stacked_bar_170_investment_electric_cars/electric_cars_additional_costs.gql).
@antw, do you agree this should be changed? 

---
Notifying @ChaelKruip @grdw @BerendSmits

**Comment by antw** [comment]
> 2 Number_of_units per vehicle type are incorrectly used
>
> can it be that in merit number_of_units is still used instead of a query based on number of cars and shares?

I can't actually reproduce this myself: I added an excess of wind energy, removed all EVs, but set EV availability (for storage) to 100%. All the excess was curtailed, with none stored in EVs. Any chance you have a scenario where I can explore this? Your explanation *does* make sense though: if the `number_of_units` were non-zero, Merit might think there were EVs available for storing energy.

> 4 electric_cars_additional_costs.gql should not be defined by initial_investment of transport_car_using_hydrogen
>
> This is the case for electric_cars_additional_costs.gql.
> @antw, do you agree this should be changed?

That seems like a mistake and should probably be changed.

> 1 number_of_cars in a local dataset should not be defined by transport_useful_demand_car_kms
> 3 Number_of_units per vehicle type are probably incorrectly defined

I think @ploh [was correct](https://github.com/quintel/etsource/issues/1223#issuecomment-277337344): we should add a custom node type for vehicles so that we can correctly calculate the number of units, without resorting to doing it as part of an input or query. This is not difficult.

I think it would be nice to explore if we could do this without an `AREA` attribute, by setting `number_of_units` in a "transport_cars" converter which would be inserted between the "transport_useful_demand_car_kms" node and the individual technologies. It has always felt slightly wrong to me to define a number of units in the area file... @ChaelKruip @DorinevanderVlies Do you have any thoughts on this?

**Comment by DorinevanderVlies** [comment]
> Any chance you have a scenario where I can explore this? 

https://beta-pro.energytransitionmodel.com/scenarios/651391

> That seems like a mistake and should probably be changed.

Will do

> I think it would be nice to explore if we could do this without an AREA attribute, by setting number_of_units in a "transport_cars" converter which would be inserted between the "transport_useful_demand_car_kms" node and the individual technologies.

My first thoughts are that this seems a neat solution.

**Comment by ChaelKruip** [comment]
> I think @ploh was correct: we should add a custom node type for vehicles so that we can correctly calculate the number of units, without resorting to doing it as part of an input or query. This is not difficult.

I like this as well. 👍 

> It has always felt slightly wrong to me to define a number of units in the area file...

Do you feel differently about `number_of_cars` than `number_of_residences` for instance?

**Comment by antw** [comment]
> Do you feel differently about number_of_cars than number_of_residences for instance?

That's a good point, but I think the two are different. To my knowledge, we don't explicitly model "household" nodes – rather the two types of household are separated by purpose ('new houses demand for cooling", "old houses demand for heating", etc) – so it seems to make sense that it would remain an area attribute.

If we had a `transport_cars` node it might make it easier to compute the number of electric cars, gasoline cars, etc, while retaining the ability to [set demand ("car kms")](https://github.com/quintel/etsource/blob/ea7cc5af9be787f76df760b01f32744e77b8f561/inputs/demand/transport/transport_car/transport_useful_demand_car_kms.ad#L3) separately. In fact, I don't think we *need* a new node since `transport_useful_demand_car_kms` already does this; we might prefer to rename that node and set the `number_of_units` attribute there.

```ruby
# Replaces "transport_useful_demand_car_kms" input:
EACH(
  UPDATE(V(transport_cars), preset_demand, USER_INPUT()),
  UPDATE(V(transport_cars), number_of_units, USER_INPUT())
  # No need to set number of units for separate car types; happens automatically
  # once a new converter class is added.
)

# Update the total number of kilometres driven, does not add more cars.
UPDATE(V(transport_cars), preset_demand, USER_INPUT())

# Change the number of cars without changing the number of kilometres driven.
UPDATE(V(transport_cars), number_of_units, USER_INPUT())
```

**Comment by ChaelKruip** [comment]
> # No need to set number of units for separate car types; happens automatically
>  # once a new converter class is added.

Do you mean that the left-to-right share of car type determines how the number_of_units of the different types of cars is derived from the `transport_cars` node?

Sounds like a good plan!

**Comment by DorinevanderVlies** [comment]
> If we had a transport_cars node it might make it easier to compute the number of electric cars, gasoline cars, etc, while retaining the ability to set demand ("car kms") separately. In fact, I don't think we need a new node since transport_useful_demand_car_kms already does this; we might prefer to rename that node and set the number_of_units attribute there.

I like this approach!
Would it include another slider for number of cars (to set number of units)? Of would this number of units be part of the dataset?

@antw, can you implement this?

**Comment by DorinevanderVlies** [comment]
As mentioned in https://github.com/quintel/etmodel/issues/2390#issuecomment-302349657 in order to calculate the extra investment costs correctly `number_of_units` for trucks needs to be modelled the same way as `number_of_units` for cars

**Comment by DorinevanderVlies** [comment]
> If we had a transport_cars node it might make it easier to compute the number of electric cars, gasoline cars, etc, while retaining the ability to set demand ("car kms") separately. In fact, I don't think we need a new node since transport_useful_demand_car_kms already does this; we might prefer to rename that node and set the number_of_units attribute there.

@antw am I right in assuming your proposal would enable the following?
@antw would this effect the current local datasets?
@antw would this effect the method of creating local datasets?

**A data analysis which has output:**
- Number of cars
- Total useful demand of cars (kilometers)
- Shares

This output is used to set the current graph

**For first implementation we can just allow adjustment of:**
- Total useful demand of cars (kilometers)
- Shares

In this case I would say number of cars is scaled according to the change of total useful demand of cars

**Later on adding a slider to adjust** 
- Number of cars (this can be used to simulate self-driving scenario's)

And all three of these can be adjusted separately.
I think we can wait with this enhancement before until after the deploy.

**Comment by antw** [comment]
[My proposed solution above](https://github.com/quintel/etmodel/issues/2360#issuecomment-288194206) has been implemented and pull requests have been created (but are waiting on a little more testing before merging).

* ETSource: https://github.com/quintel/etsource/pull/1283
* ETEngine: https://github.com/quintel/etengine/pull/926

> Would it include another slider for number of cars (to set number of units)?

This is indeed possible. The ETSource pull request still uses the single "demand" slider to set both demand (kms driven) and the number of cars simultaneously. However, it would certainly be possible to use two sliders to set demand and number of cars separately.

> would this effect the current local datasets?

I still need to test this, but I expect the impact on existing local datasets – if any – to be minimal. The datasets currently define a `number_of_units` attribute in the area file and it is scaled to the size of the region. This value is used to initialize the nodes in ETEngine, therefore I think no changes will be necessary.

I'll get back to you on this ASAP.

> would this effect the method of creating local datasets?

I do not believe so. I will check this after testing the existing datasets.

**Comment by DorinevanderVlies** [comment]
Closing this issue 

In discussion with @jorisberkhout and @ChaelKruip it was decided not (yet) to implement a number of cars slider. In the future we can reconsider implementing this slider. In that case we have to keep in mind (among other things):

- How to prevent impossible sider settings like too little cars for the total demand (in kms)
- Do we have to implement a flexible demand curve which changes according to the car to kms ratio?
