### ISSUE TITLE
Legend for CO2 of biomass chart is not visible in report

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2363]
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/24252496/e57b7d28-0fdd-11e7-9fb2-9520844f2ee9.png)

**Comment by antw** [comment]
This does not appear to be the case for me. It's curious that your chart does not have a breakdown of sectors; it suggests that your DB is old and lacking the latest chart settings. You might want to try grabbing a fresh DB dump from staging.

<img width="653" alt="screen shot 2017-03-28 at 14 14 54" src="https://cloud.githubusercontent.com/assets/4383/24406787/f8e31600-13c0-11e7-957b-3053b20e2629.png">

**Comment by antw** [comment]
I beg your pardon, I was looking at the wrong chart. Nonetheless, the legend does now display on the biomass CO2 chart for me:

<img width="653" alt="screen shot 2017-03-28 at 14 22 54" src="https://cloud.githubusercontent.com/assets/4383/24407163/20125b22-13c2-11e7-8067-51c395e54ed1.png">
