### ISSUE TITLE
Rounding does not work as expected in report

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2366]
I'm using 
```
{{ future.total_net_energy_import | round: 1 | autoscale: 'MJ'}}
```
And expect to have only one figure behind the decimal but instead I get two:

![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/24554155/e2555cae-162c-11e7-9090-4b676f79bd39.png)

**Comment by antw** [comment]
This is because the query returns a value in MJ (e.g. 1343332946570.8057). `round: 1` rounds this to "1343332946570.8" then `autoscale` converts it to EJ ("1.34 EJ"). I'll see what I can do to give you more control over number formatting.

In the interim you can do this:

```
{{ future.total_net_energy_import | divided_by: 1000000000000 | round: 1 | autoscale: 'EJ' }}
```
