### ISSUE TITLE
Maximum amount of solar PV plants

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etmodel#2367]
I think the maximum amount of solar PV plants that can be built is too low. For instance: in the NL 2013 dataset (in the ad file), land_available_for_solar = 18475.714 
The land use of a solar PV plant is 0.113 km2, so you should be able to build 163,496 plants. However, when you set the slider all the way tot the right, it only goes to 5,817. Still quite a lot, but shouldn't you be able to utilise the full potential?

**Comment by AlexanderWirtz** [comment]
@BerendSmits please enlighten me. 

- Where is this parameter currently set and how was it determined?
- What do you suggest we do to fix this?

Your argument sounds convincing enough, but I wonder if there was some reason for using the other maximum number.

**Comment by jorisberkhout** [comment]
Well spotted, @BerendSmits . I can answer @AlexanderWirtz' first question for you. In https://github.com/quintel/etsource/commit/e992463e3c51489594407bf8f853d479385d8d99#diff-fadc5ee5840b4efbacbb15285feac51f, the maximum value of this slider was made dependent on a query that takes, amongst others, the total electricity production into account. Simply changing that query to something that takes the `land_available_for_solar` into account should fix this. Would you like to give it a try, @BerendSmits ? Let me know if you need help.

**Comment by BerendSmits** [comment]
Thanks @jorisberkhout! I had no idea where max slider values were set..
I've changed it to using the full land available in the branch: https://github.com/quintel/etsource/tree/solar_max_value

The land available for solar is equal to the areable land for the NL dataset (and for a few other datasets as well I think), so the max amount changed quite a bit, from 5,800 to 138,000 solar plants. Setting the slider with your mouse is a bit rough now, the least I could build at a time was one thousand. 

What do you think @jorisberkhout @AlexanderWirtz? Keep it the old way (max is set at matching the total base year electricity production) or change it to using the total available land?

**Comment by AlexanderWirtz** [comment]
new way, i.e. total available land!

**Comment by jorisberkhout** [comment]
I like the new way better too!

The branch [`solar_max_value`](https://github.com/quintel/etsource/tree/solar_max_value) contains a commit (https://github.com/quintel/etsource/commit/2e1ff945ab4a6e703cb9b3e58e82d457e9981f6c) that I guess does not belong there. If you could fix this, @BerendSmits , I can review and merge the resulting pull request.

**Comment by jorisberkhout** [comment]
Closed by https://github.com/quintel/etsource/pull/1269/commits/5d340cbdbc6cdfc89005bf14ad9950538e7fdd71.
