### ISSUE TITLE
Hide legend items if associated series is zero

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2373]
Now users are often confused to see a color in the legend which does not appear in the chart.

**Comment by grdw** [comment]
This is only the case for perticular charts *not* for all charts. I know that the d3 merit chart [has this  feature](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/d3/merit_order_hourly_supply.coffee#L43-L49) already.

**Comment by grdw** [comment]
This is a bit of an ongoing process. Passively monitoring the issues that appear - will extend existing charts when really needed. Closing this issue.
