### ISSUE TITLE
Energy imports pop-up looks weird

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2378]
When clicking on the `Energy imports` dashboard item on the Beta, this is what I get. This does not happen on the Live server. Assigning @grdw as I think this is a technical issue. If not, re-assign at will.

<img width="742" alt="screen shot 2017-04-10 at 14 46 07" src="https://cloud.githubusercontent.com/assets/4669028/24862364/9e3239e8-1dfc-11e7-90d2-163de076277b.png">

**Comment by grdw** [comment]
In which browser was this?

**Chrome Version 57.0.2987.133 (64-bit)**

![screen shot 2017-04-24 at 14 36 11](https://cloud.githubusercontent.com/assets/2676542/25337260/73de529e-28fb-11e7-9fc9-aab38dc1797b.png)

**Firefox 53.0 (64-bits)  (I know the screenshot is localhost but it's not any different from beta)**

![screen shot 2017-04-24 at 14 36 18](https://cloud.githubusercontent.com/assets/2676542/25337261/73e235c6-28fb-11e7-9d42-64590069bd9b.png)

**Version 10.1 (12603.1.30.0.34)**

![screen shot 2017-04-24 at 14 36 41](https://cloud.githubusercontent.com/assets/2676542/25337259/73dc5066-28fb-11e7-9e25-acb0109e1ef3.png)

**Comment by antw** [comment]
This was closed by 3e8a9ec.
