### ISSUE TITLE
Costs of dashboard item differs from sum of costs table

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2384]
I suppose the query of the table is incomplete. I'll check this soon.

### Example
In the [Urgenda 2.0 -scenario](https://pro.energytransitionmodel.com/scenarios/311918) the dashboard shows 49.6 bln/year, the 45.44 bln/year.

![image](https://cloud.githubusercontent.com/assets/19907658/25521433/ca2d225e-2bff-11e7-9c4e-92757f31b805.png)

Notifying @antw @jorisberkhout

**Comment by ChaelKruip** [comment]
I think I fixen this earlier (on beta?) by adding cost of flexibility.

**Comment by DorinevanderVlies** [comment]
> I think I fixen this earlier (on beta?) by adding cost of flexibility.

Thanks! I didn't check beta. It is indeed fixed on beta.
