### ISSUE TITLE
Data for loose parts of the dynamic demand curve for EV profile

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2385]
I'm currently trying to fetch the data for the EV profile. 

The query that belongs to this is `gqueries/general/merit/merit_ev_demand.gql` in ETsource. However I also need 3 other queries for the lose parts. Now I know that I can get the ev profile values by doing:

````ruby
scope.graph.area.electric_vehicle_profile_1 # 2, 3
````

.. in the sandbox. However, I have no idea how to turn this into a profile? Can I just assume that that value is repeated all throughout 8760 points?

**Comment by antw** [comment]
@ChaelKruip and I discussed this briefly yesterday, and for the moment we think it best to proceed without the individual parts of the curve (part 1, 2, 3 for EVs, insulated vs. non-insulated for space heating). Showing the total EV demand curve, old and new space heating, and hot water curves is enough.

**Comment by grdw** [comment]
![screen shot 2017-05-05 at 13 44 50](https://cloud.githubusercontent.com/assets/2676542/25744242/07d20644-3199-11e7-91ae-1d79e6e814f1.png)


Quick preview.

Few things:

1. I don't know how to let the EV be shown. Even if I put the EV technology slider up to 100% it doesn't work and I'm a bit out of options? Should there be sliders for those ev constants?
2. The "rest-area" (the now empty white space in between the total demand curve and the stacked chart), should that be solved be a GQL statement or should we keep it like this - as an empty space?

Note to self:

- [ ] Toggle the series

**Comment by grdw** [comment]
Including @ChaelKruip @jorisberkhout @antw

**Comment by antw** [comment]
> Even if I put the EV technology slider up to 100% it doesn't work and I'm a bit out of options?

You're right, the curve is full of zeros. I renamed some Merit groups recently; perhaps I mis-spelled something. I'll look into it.

**Comment by antw** [comment]
> Even if I put the EV technology slider up to 100% it doesn't work and I'm a bit out of options?

Please pull the latest ETEngine branch; the EV curves had a different name than expected. When no curves can be found, it falls back to the old behaviour.

> The "rest-area" (the now empty white space in between the total demand curve and the stacked chart)

I think it would be nice to fill this in – with a light colour – as if it was another series: "Other demand".

**Comment by grdw** [comment]
![screen shot 2017-05-08 at 14 43 15](https://cloud.githubusercontent.com/assets/2676542/25804580/b2e23472-33fc-11e7-8cbe-fb4e54e163e6.png)
![screen shot 2017-05-08 at 14 43 19](https://cloud.githubusercontent.com/assets/2676542/25804581/b2e49c80-33fc-11e7-8d0b-c84e11bf10dc.png)

I have the most annoying of D3 / JS bugs. Namely that for one random series in the chart can't toggle off or on. Google doesn't give me anything, neither does the D3 docuemntation. I tried implementing the chart as a whole differently (with the `exit().remove()` strategy instead of redrawing the whole chart but that gives a tremendous amount of other problems which I won't go into detail with). 

So I'm stuck. What to do? @ChaelKruip Is it really needed that you can toggle off areas? What's the actual purpose of this feature? Maybe it should only be possible to toggle off the total demand or not the total demand?

**Comment by grdw** [comment]
Moved to issue https://github.com/quintel/etmodel/issues/2386

**Comment by ChaelKruip** [comment]
> Maybe it should only be possible to toggle off the total demand or not the total demand?

I think that is sufficient for now.
