### ISSUE TITLE
Toggle doesn't work for chart

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2386]
![screen shot 2017-05-08 at 14 43 15](https://cloud.githubusercontent.com/assets/2676542/25804580/b2e23472-33fc-11e7-8cbe-fb4e54e163e6.png)
![screen shot 2017-05-08 at 14 43 19](https://cloud.githubusercontent.com/assets/2676542/25804581/b2e49c80-33fc-11e7-8d0b-c84e11bf10dc.png)

I have the most annoying of D3 / JS bugs. Namely that for one random series in the chart can't toggle off or on. Google doesn't give me anything, neither does the D3 docuemntation. I tried implementing the chart as a whole differently (with the `exit().remove()` strategy instead of redrawing the whole chart but that gives a tremendous amount of other problems which I won't go into detail with). 

So I'm stuck. What to do? @ChaelKruip Is it really needed that you can toggle off areas? What's the actual purpose of this feature? Maybe it should only be possible to toggle off the total demand or not the total demand?

**Comment by grdw** [comment]
Some more information: the data is actually correct, the stacking is correct, d3 only displays the data completely the wrong way.

**Comment by grdw** [comment]
Possible fixes:

- [ ] Bump D3 library and actually fix the drawing (takes lots and lots of time) 
- [ ] Ignore the toggling (takes no time at all)
- [ ] Partial toggling (takes a bit more time)
- [ ] Actually fix the bug (takes a lot of time)

**Comment by ChaelKruip** [comment]
> Maybe it should only be possible to toggle off the total demand or not the total demand?

👍  fine for now.

**Comment by grdw** [comment]
Fixed by only toggling the demand curve. Actually it would be great if we can upgrade the D3 version as described here: https://github.com/quintel/etmodel/issues/2387

Closing this
