### ISSUE TITLE
Chart should change when switching to other parts of the ETM when second chart is locked

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2389]
As noticed by @AlexanderWirtz (and checked by me)

To reproduce: 

1. add second chart
2. lock *second* chart
3. navigate to other slide

Expected behaviour: the (unlocked) chart on the left should change to the default chart for the slide you navigate to.

Observed behaviour: the (unlocked) chart is not replaced (as if it was locked)

![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/25946571/05d882a2-364c-11e7-93f7-9f83301a0055.png)

**Comment by AlexanderWirtz** [comment]
I also noticed (only on beta!) that if an additional chart is locked, some dashboard charts no longer load:

![image](https://cloud.githubusercontent.com/assets/308563/26058743/8062d4ba-397f-11e7-85e7-f47847bafcea.png)

Notice how both `Chart view` and `Table view` buttons appear. Clicking them produces this error in the console:
![image](https://cloud.githubusercontent.com/assets/308563/26058789/b3f8e864-397f-11e7-8c13-46b04e600471.png)

**Comment by antw** [comment]
@ChaelKruip @AlexanderWirtz Thanks for the reports. Both work fine in production so I would guess this is my fault and related to changes I made during the scenario report project. I'll try to look into this within the next day or two.

**Comment by antw** [comment]
Fixed by 27992a7.
