### ISSUE TITLE
Add additional costs for trucks using hydrogen and electricity

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2390]
Currently no additional costs are calculated for trucks using electricity.

Scenario's like the Urgenda-scenario have up to 75% electric trucks and we will soon implement trucks using hydrogen in ETModel. I think this is a good improvement to also add costs for trucks using electricity and hydrogen.

Notifying @jorisberkhout

**Comment by DorinevanderVlies** [comment]
I see three options to implement the costs for electric/hydrogen trucks:
1. Same costs as defined for electric cars
2. Specific costs for trucks
3. Don't implement them

I'm in favour of option 2. This will require an extra slider and queries to implement these costs in charts/dashboard items.

@ChaelKruip what's your opinion about this?

**Comment by ChaelKruip** [comment]
@DorinevanderVlies do you mean the 'extra investment'? I agree that this would require an extra slider.

**Comment by DorinevanderVlies** [comment]
> @DorinevanderVlies do you mean the 'extra investment'? I agree that this would require an extra slider.

I do indeed

**Comment by ChaelKruip** [comment]
> I do indeed

Do we have a reliable `number_of_units` for trucks? I think that this is still an issue with electric cars as well and before we solve that I don't think it is feasible to add a similar slider for trucks.

**Comment by DorinevanderVlies** [comment]
> Do we have a reliable number_of_units for trucks? 

[CBS](http://statline.cbs.nl/Statweb/publication/?VW=T&DM=SLNL&PA=82044NED&D1=5-6&D2=0&D3=a&HD=151014-1243&HDR=G2&STB=G1,T&CHARTTYPE=1) gives pretty accurate data on this

**Comment by DorinevanderVlies** [comment]
Closing after discussion with
@jorisberkhout and @ChaelKruip 

As long as batteries of electric trucks are not used for flexibility purposes additional costs should not be taken into account
