### ISSUE TITLE
Chart doesn't go full screen when other chart is locked

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2392]
Steps to reproduce:

1. Load a random chart
2. Lock that chart
3. Add a chart
4. Full screen the chart you just added

Nothing:

![screen shot 2017-05-11 at 16 00 33](https://cloud.githubusercontent.com/assets/2676542/25953219/fd29bfa6-3662-11e7-955c-07e6c4f8ef0f.png)

**Comment by antw** [comment]
> Steps to reproduce:
> 
> 1. Load a random chart
> 2. Add a chart
> 3. Full screen the chart you just added

Just so I'm clear...

0. Start a new scenario.
1. Change the default chart to something else
2. Add a second chart
3. Zoom/full-screen the second chart.

Is that correct? I ask only because with those steps the full-screen chart opens just fine for me.

**Comment by ChaelKruip** [comment]
Not sure but didn't locking one of the charts have to do with it @grdw?

In Chrome I had some issues

**Comment by grdw** [comment]
I forgot that. Yes, it had to do with locking the chart. Updated the steps in the original comment so:

> 1. Load a random chart
> 2. Lock that chart
> 3. Add a chart
> 4. Full screen the chart you just added
