### ISSUE TITLE
Fertiliser chart should show hydrogen if P2G for industry is used

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2397]
I think I replaced all natural gas for fertilisers with hydrogen by building a lot of wind and P2H for industry. The chart does not show the hydrogen (but shows reduced use of natural gas):
![energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_](https://cloud.githubusercontent.com/assets/1303760/26059090/bfe89c22-3980-11e7-8d61-280185d4bcc8.png)

**Comment by jorisberkhout** [comment]
Let's make this part of the upcoming deploy.

**Comment by jorisberkhout** [comment]
Closed by https://github.com/quintel/etsource/pull/1406, https://github.com/quintel/etmodel/pull/2520 and corresponding database changes.
