### ISSUE TITLE
Network cost calculation results in lower investments after dynamic curve implementation

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2400]
The reason that the network costs are (significantly) lower after we improved the modelling of electricity load by modelling the shape of the electricity profile for space heaters, water heaters and EV is that *the old method used simultaneousness multipliers larger than unity*.

This overview shows which values were used:
![screenshot_18_05_2017__14_00](https://cloud.githubusercontent.com/assets/1303760/26201324/b91fb624-3bd2-11e7-92fb-df1b67c429c5.png)

**Comment by ChaelKruip** [comment]
Including @AlexanderWirtz @DorinevanderVlies

**Comment by DorinevanderVlies** [comment]
Just to check. The new costs are the correct costs?

**Comment by ChaelKruip** [comment]
I don't know... @jorisberkhout might know

**Comment by jorisberkhout** [comment]
This issue has been superseded by the new network calculation in which we no longer need the simultaneousness parameters. Also we are checking the results of the new calculation with various grid operators, so I suggest to close this issue as it is more useful to test our calculation with their results.
