### ISSUE TITLE
Merit order chart renders prior to ETEngine response

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2401]
When going to quickly(?) for the `batteries in households` slider, the interface hangs:

### console

![image](https://cloud.githubusercontent.com/assets/104830/26307729/56014c02-3ef6-11e7-8391-9af81f20ea60.png)

@ChaelKruip remembered you, @antw already fixed this? But we couldn't find the old issue, so might be redundant.

**Comment by antw** [comment]
> @ChaelKruip remembered you, @antw already fixed this? But we couldn't find the old issue, so might be redundant.

#2356 is what you're thinking of. I do believe this has been fixed, but as I'm intending to do [some work on chart loading](https://github.com/quintel/etmodel/issues/2389) in the next day or two, I will keep this open to remind me to double-check.

**Comment by dennisschoenmakers** [comment]
Thanks @antw closing this in favor of #2356

**Comment by antw** [comment]
Reopening because I've encountered this several times today on beta.

**Comment by antw** [comment]
> I've encountered this several times today on beta.

... and now I can't reproduce it. I was also using production on the same day I (supposedly) encountered it on beta; perhaps I got my tabs mixed up. 😖 

I'll close this; please reopen if it occurs again.
