### ISSUE TITLE
The user should be able to choose the imbalance price for electricity

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2405]
If there are no more dispatchable plants left in the merit order calculation, the model imports electricity and assumes a price of 140 EUR/MWh. I remember this price being based on historic values or something like that or a multiplier of the most expensive plant. 

This is not very transparent to the user and I think we should turn this into a slider of some sort.

Happy to hear your ideas!

**Comment by DorinevanderVlies** [comment]
> This is not very transparent to the user 

Agreed

> Happy to hear your ideas!

How about:
-  an extra sidebar item "Electricity import" in the costs tab
- the slider sets an absolute value for the costs of imported electricity
- a chart (bar) shows for both present and future (average or max) costs of nationally produced and imported electricity. The future costs are set using a slider, default is present costs. The costs of nationally produced electricity can be used as inspiration for the slider setting (do the costs of electricity increase or decrease?)
_do we have information regarding present costs of imported electricity?_

**Comment by ChaelKruip** [comment]
> * an extra sidebar item "Electricity import" in the costs tab
> * the slider sets an absolute value for the costs of imported electricity
> * a chart (bar) shows for both present and future (average or max) costs of nationally produced and imported electricity. The future costs are set using a slider, default is present costs. The costs of nationally produced electricity can be used as inspiration for the slider setting (do the costs of electricity increase or decrease?)
do we have information regarding present costs of imported electricity?

I like it!

Perhaps we can show an extra line in this chart?
<img width="619" alt="energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_" src="https://user-images.githubusercontent.com/1303760/26976410-fc422b6e-4d23-11e7-9dff-f2ff6bb5341d.png">

Also, I now realise that I made a mistake in my description of the issue. We assume a price for import but we also assume another price when even import is depleted.

@antw isn't it something like this:
* If most expensive dispatchable plant is running, assume some price A
* If more electricity is needed than the most expensive dispatchable plant can provide, assume another price B?

**Comment by antw** [comment]
> * If most expensive dispatchable plant is running, assume some price A
> * If more electricity is needed than the most expensive dispatchable plant can provide, assume another price B?

Correct. The price is the most expensive plant which is running. If demand exceeds supply, the price is [the most expensive plant × 7.22](https://github.com/quintel/merit/issues/66#issuecomment-12317794).
