### ISSUE TITLE
Missing information on Demand Response sliders?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2408]
On all three sliders in the [demand response slide](https://beta-pro.energytransitionmodel.com/scenario/flexibility/electricity_storage/demand-response) there's just an empty grey box when you click the `i`:

![image](https://user-images.githubusercontent.com/104830/26884396-faefa0e6-4b9f-11e7-9955-26aa7448752f.png)

**Comment by dennisschoenmakers** [comment]
It would be interesting to see what the underlying/assumed profiles are for the different sliders.

**Comment by ChaelKruip** [comment]
Done.
