### ISSUE TITLE
Put Berenschot in column of partners that financially support the ETM

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2411]

**Comment by dennisschoenmakers** [comment]
Left columns here: ![image](https://user-images.githubusercontent.com/104830/27123349-dcb80a34-50ed-11e7-88cd-50cab5a212b2.png)

**Comment by dennisschoenmakers** [comment]
PR that will fix this: quintel/etcentral#157

**Comment by dennisschoenmakers** [comment]
Fixed and deployed to staging and production.
