### ISSUE TITLE
In a dataset the sum of old and new residences can differ from total number of residences

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2412]
Currently it is possible to define a dataset in which `number_of_old_residences` and `number_of_old_residences` do not add up to n`number_of_old_residences`.

A fix could be to define 2 out of 3 and let the graph calculate the third.
For example
`number_of_residences=100` 
`number_of_old_residences=30`
From which is calculated
`number_of_new_residences=70`

including @jorisberkhout, @BerendSmits, @antw, @grdw

**Comment by ChaelKruip** [comment]
Could this be enforced in the dataset analyses @DorinevanderVlies ?

**Comment by grdw** [comment]
> Could this be enforced in the dataset analyses @DorinevanderVlies ?

That's one step. I think it would also be practical to validate this with a spec in ETsource.

**Comment by DorinevanderVlies** [comment]
> Could this be enforced in the dataset analyses @DorinevanderVlies ?

In both the national dataset and the local dataset this is currently enforced by setting total residences and a share of old residences.

So I think this issue can be closed unless we want to 

> validate this with a spec in ETsource.
@grdw can you do that?

**Comment by grdw** [comment]
> @grdw can you do that?

Sure! 👍 No problem.

**Comment by grdw** [comment]
My validation is working exactly as it should, in fact. It directly finds an error:

```spec
expected that :drenthe would be valid
"Number of old residences (160970.0) and number of new residences (50953.0) don't add up to the total number of residences (211902.0)."
```

**Comment by DorinevanderVlies** [comment]
> My validation is working exactly as it should, in fact. It directly finds an error:

nice catch

If fix this in:

https://github.com/quintel/etdataset/pull/732/commits/30f0f0adf50033bd113faed39c9e8425642d723c
and
https://github.com/quintel/etsource/pull/1397/commits/7cddc7d06bfd1d16b89106ac0281fb6952cd3453

**Comment by DorinevanderVlies** [comment]
Closing
