### ISSUE TITLE
IE9: Can't load a new scenario

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2415]
Starting a new scenario responds as though Etengine is offline. 

Debug info:

```
ApiGateway.update error [object arguments]
```

---

Starting an existing scenario responds partially (sliders load, charts don't show).

**Comment by grdw** [comment]
Starting a new scenario responds as though Etengine is offline. Starting an existing scenario responds partially.

**Comment by antw** [comment]
Deploy was ongoing. You probably caught it in the minute or two while the maintenance page wasn't up.

Seems fine now.

**Comment by grdw** [comment]
I'm still seeing the same error on the console on the `beta-pro` server though.  I'm using IE9 (Windows 7) in VirtualBox.

**Comment by grdw** [comment]
![screen shot 2017-06-19 at 16 12 35](https://user-images.githubusercontent.com/2676542/27289411-2486ee3c-550a-11e7-8923-1d8bd5e22849.png)

**Comment by antw** [comment]
[It's this Airbrake error](https://quintel.airbrake.io/projects/32209/groups/1976140994971507083?tab=notice-detail). Seems to only affect IE<=9.

**Comment by grdw** [comment]
Okay, I managed to squash this bug only to find lots of others 😢 . I'll create tickets for those bugs and hold those off  until further notice. I do not know how many IE9 users we have for the ETM but if it's worthwhile I'll try and fix them as soon as possible. 

Including @ChaelKruip
