### ISSUE TITLE
IE9: display problems

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2418]
Bugs are visible after applying the fix from issues/#2415 

![screen shot 2017-06-19 at 16 46 49](https://user-images.githubusercontent.com/2676542/27290960-1371a01a-550f-11e7-845f-0ff4c29f9972.png)

The main problems are:

- the constraints aren't visible
- the charts don't load (only the texts, axis and legends). 

---

My guess would be that this is due to unsupported javascript syntax (methods like `filter`, `find`, `map` etc.). I would need to check this though. However the IE9 console doesn't give any debug lines suggesting that this is the case.

**Comment by antw** [comment]
> However the IE9 console doesn't give any debug lines suggesting that this is the case.

You can emulate IE9 with IE11: Open "F12 Developer Tools" -> Emulation tab -> Document mode: 9

In this case, it seems IE9 is sending requests to ETEngine without asking for any Gqueries!

```js
{
  "scenario":{
    "id":687721,
    "title":"API",
    "area_code":"nl",
    "start_year":2013,
    // ...
  },
  "gqueries":{}  // <- !!
}
```

**Comment by antw** [comment]
Swapping `to_json` for `to_hash` in ApiProxyController fixes the problem. Next problem: Support for `to_hash` is going to be removed in Rails 5.1. 😆

**Comment by antw** [comment]
I think we can do:

```ruby
params.permit!.to_h.except('controller', 'action', 'url', 'format')
```

This seems to do the trick and doesn't trigger any deprecation warnings.

**Comment by grdw** [comment]
Looks good to me 👍
