### ISSUE TITLE
Semantics: a local dataset is not a country

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2420]
![screen shot 2017-06-20 at 11 12 28](https://user-images.githubusercontent.com/2676542/27325658-6c656702-55a9-11e7-8acd-565f9799390c.png)

Select country is wrong in this situation. It should probably say "select region". 

The same issue is on the regions pages:

![screen shot 2017-06-20 at 11 13 37](https://user-images.githubusercontent.com/2676542/27325703-8e723906-55a9-11e7-87c3-3ed71c7c6db9.png)

And while somebody's at it, fix the translations 👍

**Comment by grdw** [comment]
@ChaelKruip re-assign at will

**Comment by ChaelKruip** [comment]
> Select country is wrong in this situation. It should probably say "select region".

Assigning @DorinevanderVlies
