### ISSUE TITLE
Dataset Netherland does not load on beta

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2423]
The dataset "Netherlands" and other country datasets do not load properly on the beta server. This includes scenario's based on this dataset.

Local dataset seem fine.

![image](https://user-images.githubusercontent.com/19907658/27544283-f7993ba4-5a8c-11e7-8468-112f1f701145.png)

Does this have to do with https://github.com/quintel/etengine/commit/f33465116d789c886ee0ffc3af7b40953ffac7e0?

**Comment by antw** [comment]
Well-spotted, thanks; that was my bad. :blush:
