### ISSUE TITLE
Short term solution for selecting a (sub)region for a scenario

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2426]
![screen shot 2017-07-03 at 13 38 26](https://user-images.githubusercontent.com/2676542/27791356-e8bd360e-5ff4-11e7-8813-19e36771970f.png)

The current interface for selecting a region in the ETModel interface is becoming messy.  That’s the reason to rethink this and find a new implementation. 

We have to keep in the back of our heads that this implementation will *not* be suitable for 15.000+ datasets but stating that we are far far away from that happening, this will have to do in the mean time.

**I have two basic ideas:**

The first idea is adding a select box and splitting the regions from the countries:
![idea_1_netherlands](https://user-images.githubusercontent.com/2676542/27791859-5a949f0e-5ff7-11e7-8f14-2ae17a7f75f7.png)

So when Netherlands is selected, you'd have another select box with regions from The Netherlands. If however anther country is selected like Poland, there are no other regions to pick from:

![idea_1_poland](https://user-images.githubusercontent.com/2676542/27791857-5a91f416-5ff7-11e7-989b-8a2d7c61c3e6.png)

*Upsides:*
- Clear division of regions and countries

*Downsides:*
- A user needs to perform an extra step to create a scenario for a local region.

---

Another approach to this problem might be a 'hierarchy':
![idea_2_hierarchy_selection](https://user-images.githubusercontent.com/2676542/27791858-5a937304-5ff7-11e7-93a3-7e26743bfaef.png)

*Upsides:*
- Somewhat clear division of regions and countries

*Downsides:*
- It won't look pretty, stating that in the current HTML-spec it's not possible to create a hierarchy in an option list. However, there are probably customizations available online which can make it look nicer than the default html select box implementation.

**Comment by antw** [comment]
> The current interface for selecting a region in the ETModel interface **is becoming messy**. That’s the reason to rethink this and find a new implementation.

Could we go back a step and consider in what way it is messy? I agree that it doesn't look very pretty, but how would you describe the problem with the current option list? Too many entries? Not clear why there are three different sections? ...

**Comment by grdw** [comment]
> but how would you describe the problem with the current option list?

> Too many entries? Not clear why there are three different sections?

Well those two things definitely. Also it's now pretty unclear that the third section of regions are all regions within The Netherlands. For an outsider it might not be immediately clear that that's the case.

**Comment by antw** [comment]
[Using optgroups](https://jsfiddle.net/55q89ffo/) would kind of solve those issues – except for there still being too many entries – and would be really simple to implement. I think it's also easier for visitors to *not* show them a separate "Region" list.

<img width="236" alt="screen shot 2017-07-03 at 14 30 07" src="https://user-images.githubusercontent.com/4383/27794958-28810868-5ffc-11e7-9b8b-5dd0609527b7.png">

If having too many entries is a problem, then this won't work (and I think the second idea – "hierarchy" – is probably therefore also a no-go).

I don't have a strong opinion to be honest, do you have a preference?

**Comment by grdw** [comment]
> I think it's also easier for visitors to not show them a separate "Region" list.

Yes.

I think the `optgroup` solution might actually work for the time being. Also since the only supported regions are the one's from The Netherlands this will hold. When the list becomes larger than >100 items this idea might need to be revisited.
