### ISSUE TITLE
Costs of insulation should be an explicit category in the cost chart

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2429]
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://user-images.githubusercontent.com/1303760/27918129-4fe62388-626e-11e7-82ca-0374088efcaf.png)

**Comment by marliekeverweij** [comment]
A new issue has been made https://github.com/quintel/etmodel/issues/3025
