### ISSUE TITLE
Oil does not show up in import/export chart

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2430]
In the report:
![energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_](https://user-images.githubusercontent.com/1303760/27957630-9395cabe-631f-11e7-9d94-3cd43df0853d.png)

On beta:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://user-images.githubusercontent.com/1303760/27957666-bb3f619c-631f-11e7-8f82-1a2cf9863162.png)

**Comment by antw** [comment]
Is your first screenshot from your local copy? Perhaps your database is out of date and doesn't have that series?

It certainly shows up on beta for me:

| ETM interface | Report | 
| :---: | :---: |
| ![screen shot 2017-07-07 at 14 22 52](https://user-images.githubusercontent.com/4383/27959558-d5a37014-631f-11e7-8b7e-427f1490d282.png) | ![screen shot 2017-07-07 at 14 22 58](https://user-images.githubusercontent.com/4383/27959562-da76b114-631f-11e7-8225-eed633fe2021.png) |

**Comment by ChaelKruip** [comment]
🤦‍♂️ 
😊
