### ISSUE TITLE
How do we advertise the fact that you can create a ScenarioReport?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2432]
Currently, the cool new feature of the scenario report is hidden from sight from the user.

I think we can tackle this in two ways:

1. We 'explain' to people the new features, e.g. with a pop-up/walk through.
2. We make the button more prone, so, people being people and being curious, they inevitably press it, and there you go.

I personally do not like option 1 so much.

### Option 2

![image](https://user-images.githubusercontent.com/104830/28056233-73e27f1e-661c-11e7-89cc-fe19ddc0a964.png)

### With a little extra

We could also add a call out, that appears after a set time, or when the user has moved a set number of sliders.

![image](https://user-images.githubusercontent.com/104830/28056606-b2cb002e-661d-11e7-868e-7cf28d6f2724.png)

Anyways, consider this the start of a discussion. Like to hear your thoughts @ChaelKruip, @antw and @grdw.

**Comment by ChaelKruip** [comment]
> Anyways, consider this the start of a discussion. Like to hear your thoughts @ChaelKruip and @antw.

Personally, I don't like pop-ups. I click them away and hardly ever read them. Shiny buttons, however, attract my curiosity and make me want to push them. Without further ado I will share my preference for option 2!

**Comment by grdw** [comment]
> Personally, I don't like pop-ups. I click them away and hardly ever read them

Was just about to say this. I don't like them at all, click them away. 

![idea](https://user-images.githubusercontent.com/2676542/28057687-096801fe-6621-11e7-9ba7-9f6eb8762594.png)

Can we turn that round red button to a square blue'ish button and move it to the left. I mean, that's where most of the clicking happens anyway. Whenever you change some slider you could light it up a little maybe? At the left side it will be picked up faster, at least according to [eye-tracking studies](http://www.parachutedigitalmarketing.com.au/wp-content/uploads/2011/12/google-search-results-eye-tracking-heat-map.gif) (the typical F-shape). 

You could make it even more prominent by moving it between "Targets" and the header?

**Comment by antw** [comment]
> Can we turn that round red button to a square blue'ish button and move it to the left. [...] You could make it even more prominent by moving it between "Targets" and the header?

Agreed that it should be on the left. I'm not sure the report itself it _so_ useful as to be the top-most item in the sidebar. I expect that people might want to view the report after they've set up their scenario.

I think my personal preference might be for it to be a normal sidebar item / slide:

<img width="687" alt="screen shot 2017-07-11 at 11 30 52" src="https://user-images.githubusercontent.com/4383/28064397-6ded2888-662c-11e7-9503-497285ad6883.png">

**Comment by ChaelKruip** [comment]
> I think my personal preference might be for it to be a normal sidebar item / slide:

I like that as well. 

Perhaps we could draw some attention to it by making it 'glow' or add a 'call out' whenever a user has touched > 10 sliders or so. "Hey, you have spend quite some effort making a detailed scenario... would you like to get more feedback/an analysis/a report?"

**Comment by michieldenhaan** [comment]
Closing, we now have a shiny pop-up
