### ISSUE TITLE
OVERVIEW: Network cost calculation improvements

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2434]
# Background

The network impact/cost calculation has been implemented a long time ago and many things have happened that reduce its consistency and accuracy. A short summary:

## Initial implementation
* Based on rules of thumb from TenneT and Alliander for the spare capacity on different parts of the network:
  * HV network
  * HV-MV trafo
  * MV transport network
  * MV distribution network
  * MV-LV trafo
  * LV network
* Rules of thumb for the costs of extending capacity of the network components
* For each technology the following has been determined:
  * simultaneousness factors for winter day, winter evening, summer day, summer evening
  * peak_load_in_mw method that multiplies the maximum (electric) capacity with the number of units. This is a **worst case** calculation

## Adjustment to match expectations of DSO/TSO
The simultaneousness factors have been adjusted in order to reproduce expected increases in costs for the various technologies. This resulted in simult-values being larger than 1.0

## Improvement of the modelling of spare capacity
* The single-value spare capacity figures have been replaced with arrays which describe the spare capacity as a function of capacity
* The simult factors have not been updated in this project keeping 'adjustments' in place which are not necessarily compatible with the new spare capacity description

## Dynamic demand curve
The technologies who's loads are now explicitly modelled have been removed from the initial worst case calculation methods. Their impact is now derived from the load profile itself (still for the four times in the year though). This introduces another inconsistency: some technologies are treated in a worst case manner, others more realistically.

# Suggestions for improvement
### Current situation

We currently have data about the distribution of spare capacity as a function of bins (which include 5% of the capacity each):
![20170713_distributions_v01](https://user-images.githubusercontent.com/1303760/28164253-e029c0a2-67ce-11e7-8322-33106c242954.png)
Where MV transport, MV distribution and MV-LV trafo have the same distribution (middle one).

In other words, the value in bin 'i' tells you 

"*which fraction of the capacity is still free for the 'i'-th part of the total capacity*".  

Each bin represents 5% of the network capacity of a particular component/voltage level, say MV-LV trafo's. 
So, if the first bin has a value of 0.2 it means that for the most heavily loaded 5% of the total MV-LV trafo capacity, only 20% of the capacity is free.

@jorisberkhout is this a correct description?

In order to make these distributions physical, you need to multiply (the vertical axis) by the total capacity of the network components: `network_capacity_available_in_mw + network_capacity_used_in_mw`.

|component|network_capacity_available_in_mw|network_capacity_used_in_mw|
|---|---|---|
|HV|1600.0| 0.0|
|HV-MV trafo|21340.0|16490.0|
|MV transport network|30301.7|20619.5|
|MV distribution network|42000.0|30000.0|
|MV-LV trafo|6771.411882|4402.535118|
|LV network|74803.2|23376.0|

### Possible improvements
* We now specify both `network_capacity_available_in_mw` and `network_capacity_used_in_mw` but simply add them in the [ETEngine method](https://github.com/quintel/etengine/blob/master/app/models/qernel/converter_api/network.rb#L40-L43). I have the feeling we should either use one number or use the two numbers in a more meaningful way (if the data supports it). @jorisberkhout do you know if these numbers are reliable? I have a feeling that some are more reliable than others because there seems to be some inconsistency between the available fractions found by using the `network_capacity_available_in_mw` and those from looking at the distributions:
![20170713_distributions_v01](https://user-images.githubusercontent.com/1303760/28166939-1c7516aa-67da-11e7-97a5-6563cfd92264.png)

* Could we find a HV network distribution and is that useful @jorisberkhout?

### Possible improvements

**Comment by ChaelKruip** [comment]
Also see https://github.com/quintel/etsource/pull/1293#issuecomment-314054130

**Comment by jorisberkhout** [comment]
This issue is solved by the implementation of the new network calculation, so closing.
