### ISSUE TITLE
Several `final_demand_group` converters not shown in Final energy demand mekko

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2435]
I noticed that the following nodes are in the `final_demand_group` converter group, but are not shown in the _Final energy demand_ mekko:

- `energy_power_sector_own_use_electricity`
- `energy_cokesoven_consumption_coal_gas`
- `energy_export_coal_gas`
- `energy_heat_network_unused_steam_hot_water`

This explains the difference between the total of the mekko and the sum of the demands of all nodes in the `final_demand_group` group.

**Comment by ChaelKruip** [comment]
Fixed by adding the energy sector to the mekko:
<img width="643" alt="energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_" src="https://user-images.githubusercontent.com/1303760/28082649-59f7eb46-6673-11e7-9018-0c45f30b5487.png">
