### ISSUE TITLE
Network calculation: discrepancy between distributions and node attributes

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2436]
There seems to be inconsistencies between the fraction of the total capacity represented by the node attribute `network_capacity_available_in_mw` and the fraction of available capacity as described by the distributions shown below:
![20170713_distributions_v01](https://user-images.githubusercontent.com/1303760/28167278-5881c71e-67db-11e7-98b8-ef465ee25ec5.png)

The discrepancy is largest for the HV-MV trafo (22 percent points):

![20170713_distributions_v01](https://user-images.githubusercontent.com/1303760/28166994-47a552d6-67da-11e7-9ec3-ad943e358800.png)

**Comment by jorisberkhout** [comment]
Closing as these distributions and the parameters mentioned are no longer required in the new network calculation.
