### ISSUE TITLE
P2H in chemical industry

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2438]
Would this be a viable place for a P2H node @antw?

![https___beta-engine_energytransitionmodel_com_data_698278_layout](https://user-images.githubusercontent.com/1303760/28325925-86a46b8a-6bdf-11e7-98df-839c478cdf04.png)

Or should we do something similar to households?

![https___beta-engine_energytransitionmodel_com_data_698278_layout](https://user-images.githubusercontent.com/1303760/28325995-b7d350ae-6bdf-11e7-9375-b624cc34a351.png)

**Comment by antw** [comment]
> Would this be a viable place for a P2H node?

Correct me if I'm wrong, but I *think* we need a new node inserted between the left-most useful demand node and the existing producers. Then P2H can be connected to the left-most node with a `dependent` link, and the other new node with a `flexible`; the flexible will "fill-in" for whatever energy isn't provided by P2H.

```
               <--  Crude oil
Useful demand  <--  Coal
               <--  ...
```

... becomes ...

```
             (flexible)                         <--  Crude oil
                 <--  Useful demand before P2H  <--  Coal
Useful demand                                   <--  ...
                 <--  P2H
             (dependent)
```

![screen shot 2017-07-19 at 16 26 15](https://user-images.githubusercontent.com/4383/28375355-2d571594-6c9f-11e7-8c8b-7a9185882c3f.png)

**Comment by ChaelKruip** [comment]
I think you are right @antw 

CC: @DorinevanderVlies

**Comment by DorinevanderVlies** [comment]
I agree, I propose to implement the following:

![image](https://user-images.githubusercontent.com/19907658/28618157-aa3814be-7203-11e7-91e5-f2730fb30016.png)

**Comment by DorinevanderVlies** [comment]
Just discussed this with @ChaelKruip and made a correction to my proposal (see below)

@antw do you mean _after_ p2h for the node to which the technologies are attached?

![image](https://user-images.githubusercontent.com/19907658/28619035-efb2781a-7206-11e7-9b33-7c6efc6bf133.png)

**Comment by antw** [comment]
> @antw do you mean after p2h for the node to which the technologies are attached?

Yes, the diagram has the naming correct; I did indeed mean "after". :smiley:

**Comment by ChaelKruip** [comment]
Closing as this has been done.
