### ISSUE TITLE
Option to record slider settings relative to base year values for featured scenario's

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2439]
When loading Urgenda (100% renewable) it now shows no slider changes...

**Comment by DorinevanderVlies** [comment]
This seems to be the case for all saved scenario's. Only the sliders that have been changed since opening a scenario are shown in the report.

IMO it would be more informative to show all sliders that differ from the original dataset.

**Comment by DorinevanderVlies** [comment]
I still think this issue is relevant. When sharing a scenario it is usefull if the viewer can see which sliders have been set. Currently this is not possible since on the the sliders which have been set after opening the scenario are shown in the report.
