### ISSUE TITLE
Scenario's with no power plants have empty charts in the scenario report

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2441]
In some local scenario's and perhaps extreme national scenario's there are no power plants present. ([example](https://beta-pro.energytransitionmodel.com/scenarios/700023))

In the scenario report this results in empty charts in the "Profitability of power plants" and, as there are no plants with marginal costs, the "Merit order and fuel prices" sections. 

### Proposal
If no plants with marginal costs are present:

- replace chart and text from "The marginal costs and installed capacity of power generation for your scenario is shown in the chart below." by "_Your scenario does not contain power plants with marginal costs >0 EUR/MWh_",
- replace chart profitability of power plants and text "In your scenario, 100% of powerplants is not profitable. This means that they are not earning back their investment costs (orange in table below) or are not even earning their OPEX (operational expenditure) back (red). " by _"Your scenario does not contain power plants"_

### Merit order and fuel prices
![image](https://user-images.githubusercontent.com/19907658/28454503-cfadc204-6dfb-11e7-975d-aa0aed688bec.png)

### Profitability of power plants
![image](https://user-images.githubusercontent.com/19907658/28454523-e2271e94-6dfb-11e7-8cb5-034fce6d0a5b.png)

**Comment by MartLubben** [comment]
After the translation is done, this will not be an issue anymore.
