### ISSUE TITLE
Hiding/showing goals/targets section doesn't work properly

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2442]
The target section does not seem to show up now (even if targets have been set) ...

**Comment by antw** [comment]
Well, no. [You can't use GQL in the report template](https://github.com/quintel/etmodel/commit/1b4cb779f531686705eec26ab8be5bac1fc962c8#diff-5eb4a1aefa7cfcb6068d5656b265b8beR289). This needs to be in a Gquery.

**Comment by ChaelKruip** [comment]
> Well, no. You can't use GQL in the report template. This needs to be in a Gquery.

I was too overwhelmed by all the magic that I didn't realise this 👍
