### ISSUE TITLE
Link to queries available through API points to current page

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2444]
Looking at [our API page](https://energytransitionmodel.com/api#area_data), the link 
![energy_transition_model](https://user-images.githubusercontent.com/1303760/28767516-4ffbd8a8-75d4-11e7-835e-3b578ab23b03.png) points to the current page.

**Comment by grdw** [comment]
Where does this link actually need to point to? To [here](https://github.com/quintel/etsource/tree/master/gqueries)?

**Comment by ChaelKruip** [comment]
Perhaps @antw has other ideas but that would be my guess. It would be even better if we had an overview page with a list of queries. Something like
[here](https://beta-engine.energytransitionmodel.com/data/latest/converters) but with some explanations (I realise that last thing is a lot of work)
