### ISSUE TITLE
[OVERVIEW ISSUE] implementation of international aviation

### ISSUE THREAD

**Issue by karimelbana** [quintel/etmodel#2445]
As discussed in #2146, we want to include the international aviation in ETM model. This issue is a proposal for the changes to the front end and I would like to hear you opinions @AlexanderWirtz @ChaelKruip @BerendSmits @DorinevanderVlies @jorisberkhout 

### Objectives
- to give the user of the ETM insight in the energy demand of international aviation
- to give the user of the ETM insight in the CO2 emissions caused by international aviation
- to make it possible to later include synthetic Kerosene in the model

### Overview of changes to the front end
- [ ] Include International aviation slider under *Mobility growth* slide in *Transportation* sidebar item in *Demand* tab

![international aviation slider under mobility growth slide in transportation sidebar item in demand tab](https://user-images.githubusercontent.com/29379411/28829214-528d446c-76d3-11e7-9ca7-2cef83e6e939.png)

- [ ] Include International aviation slide in *Transport fuels* sidebar item in *Supply* tab
- [ ] Include 3 sliders under International aviation slide in *Transport fuels* sidebar item in *Supply* tab for Gasoline, Kerosene and Bio-ethanol

![international aviation slide with 3 sliders in transport fuels sidebar item in supply tab](https://user-images.githubusercontent.com/29379411/28829281-7e9bf5ee-76d3-11e7-9906-2a0373b4403a.png)

- [ ] Include a separate graph for CO2 emissions caused by international aviation ( needs discussion with @AlexanderWirtz  @ChaelKruip  @jorisberkhout )

### Overview of changes to the graph
- TBD with @jorisberkhout, results of this discussion will be added to this issue

**Comment by BerendSmits** [comment]
Looks good! I like the idea of adding this nationally ignored but rather large demand. I'm not sure if it is in the scope of the project right now, but are you guys thinking about adding marine bunkers as well? They should probably be managed much in the same way as aviation fuels (and are four times as large as aviation..)

**Comment by jorisberkhout** [comment]
Everything described is on the Beta server, so closing!
