### ISSUE TITLE
The Final energy demand for heating and hot water in residences currently only shows "heat"

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2451]
After merging the dynamic-heat changes to beta the final energy demand for heating an hot water in residences only shows "heat", even if a mix of technologies is used.

![image](https://user-images.githubusercontent.com/19907658/29623450-b46fdc44-8826-11e7-86c6-78886f92963b.png)

notifying @ChaelKruip

**Comment by antw** [comment]
Good catch; looks like I missed some queries.

This is ultimately down to the insertion of "aggregator" nodes between the heat producer and useful  demand nodes (used to fix deficits). It caused all sorts of problems like this. 😞
