### ISSUE TITLE
Chart on beta server does not display edges

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2452]
Image from: [this scenario](https://beta-engine.energytransitionmodel.com/data/714160/layout)

![image](https://user-images.githubusercontent.com/19907658/29655647-06de4818-88b2-11e7-9e2c-8b90e901f851.png)

notifying @ChaelKruip

**Comment by DorinevanderVlies** [comment]
Besides the edges some nodes are missing as well.
Nodes related to space and water heating technologies are currently not displayed in the graph

**Comment by antw** [comment]
I haven't yet positioned the new heating nodes, could that be the reason for this?

**Comment by DorinevanderVlies** [comment]
If it's just the positioning I think that should not be the cause.
ETEngine just puts them on top of each other

**Comment by grdw** [comment]
I patched the problem locally like this:

```diff
diff --git a/app/assets/javascripts/graphviz.coffee b/app/assets/javascripts/graphviz.coffee
index 4d480dc..535a995 100644
--- a/app/assets/javascripts/graphviz.coffee
+++ b/app/assets/javascripts/graphviz.coffee
@@ -318,7 +318,7 @@ class @Converter

   getSectorUseShortcut: ->
     sector_shortcut = @sector.charAt(0).toUpperCase()
-    use_shortcut = @use.charAt(0).toUpperCase()
+    use_shortcut = (@use || '').charAt(0).toUpperCase()

     shortcut = sector_shortcut
     if use_shortcut != 'U'
```

**Comment by antw** [comment]
Thanks @grdw; the new nodes don't have a `use` attribute assigned so it makes sense why your change fixes this.

The new household heat nodes should probably be "energetic". @DorinevanderVlies I'll send a pull request your way shortly.

**Comment by BerendSmits** [comment]
Nice work guys, thanks for the fix:thumbsup:
