### ISSUE TITLE
Slider max of buffer and cut-off COP not as set in input-file

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2453]
The input files seem to set the min, max and start-value of the sliders correctly. However, the front-end displays a different max.

### Input files

[Input - Buffer size water heating](https://github.com/quintel/etsource/blob/master/inputs/flexibility/households/households_flexibility_water_heating_buffer_size.ad)
[Input - Cut-off HHP space heating](https://github.com/quintel/etsource/blob/master/inputs/flexibility/households/households_flexibility_space_heating_cop_cutoff.ad)

### Screenshots
![image](https://user-images.githubusercontent.com/19907658/29656555-13649a62-88b5-11e7-83ca-d0269a0c7d9a.png)

**The query of the start-value outputs the correct value**

![image](https://user-images.githubusercontent.com/19907658/29656534-047dce9c-88b5-11e7-998e-cb14b040d38c.png)

notifying @ChaelKruip

**Comment by DorinevanderVlies** [comment]
Addition:
For The Netherlands this problem does not occur.

It seems to be cause by automatic scaling of the max value of sliders in local datasets.
For different datasets the max value differs.

**Noorderplantsoenbuurt:**
![image](https://user-images.githubusercontent.com/19907658/29657160-17745870-88b7-11e7-9636-6b25ed06224d.png)

**Friesland:**
![image](https://user-images.githubusercontent.com/19907658/29657143-02e3bd4c-88b7-11e7-8561-8120f111a01f.png)

**Comment by antw** [comment]
CoP being scaled makes sense since `#` is a scaled unit. I can add a new unit for those and opt it out of scaling. The same is true of buffer volumes; these are the only two sliders which use `kWh`, so it should be safe to not scale that unit.
