### ISSUE TITLE
Final demand for gas for HHP is increased after COP(T) implementation, this is unexpected 

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2454]
COP used to be 3 for HW and 4.5 for SH.

The new COP(T) is generally lower so I would expect the gas use to increase after these implementations.

I made two scenario's, both with 100% HHP for SH and HW, one one [Beta](https://beta-pro.energytransitionmodel.com/scenarios/714174) and one on [Live](https://pro.energytransitionmodel.com/scenarios/333662).

I notice that in the final demand chart the gas use for housholds is higher on live than on beta. This is the opposite from what I expected.

@antw do you think this is a query issue, similar to https://github.com/quintel/etmodel/issues/2451?

notifying @ChaelKruip 

###Screenshots

**Beta**
![image](https://user-images.githubusercontent.com/19907658/29659441-93751610-88be-11e7-8978-03f7e881acc4.png)

**Live**
![image](https://user-images.githubusercontent.com/19907658/29659438-8d4faa52-88be-11e7-8b71-9604181a166d.png)

**Comment by antw** [comment]
I'll look into this shortly, but this might be correct behaviour. If demand in any given hour can be satisfied entirely by the electric component, then the gas component will not be used; perhaps that's what's happening here?

**Comment by DorinevanderVlies** [comment]
A I see, that's interesting.

I was thinking about ETM-SA behaviour. But it might indeed be that the HHP is using it's elektric part more than was assumed before

**Comment by antw** [comment]
> If demand in any given hour can be satisfied entirely by the electric component, then the gas component will not be used

This does appear to be the case. I created an NL scenario using 100% HHPs for space and water heating. For water heating, the minimum output capacity of the electric components is *always* higher than the maximum hourly demand for heat:

* **Water heating**
  Maximum hourly demand: 10,848 kWh
  Minimum electric HHP capacity: 11,674 kW

* **Space heating**
  Maximum hourly demand: 85,982 kWh
  Minimum electric HHP capacity: 18,599 kW

For space heating, the peak demand *is* higher than the electric component capacity although this is very rare; the average demand is 9,930 kWh (half the capacity of the heat pump) while the median is only 2,578 kW.

I'm still double-checking the actual gas load. It *seems* too low, but I suspect that the buffer is (at least partly) responsible for that.

**Comment by DorinevanderVlies** [comment]
I don't really understand why you state

> Water heating
Maximum hourly demand: 10,848 kWh
Minimum electric HHP capacity: 11,674 kW

On basecamp I read the following:

> For reference, here are the computed min and max COPs of the heat pumps using the 1987 temperature curve:
> Space heating heat pumps (and HHP electrical component)
> Min 1.92875 (at -15°C), Max 5.8225 (at 29.4°C)
> 
> Hot water heat heat pumps (and HHP electrical component)
> Min 1.2107 (at -15°C), Max 3.1242 (at 29.4°C)

With this I would say the minimum electric HHP capacity is much lower: 
1.2 (COP) * 1.2 (input capcity HP) = 1.44 kW

Even at maximum COP 3.1 the electric part of the HHP only delivers 3.1 * 1.2 = 3.72 kWh

With this it is surprising that the gas for hot water is 0 when HHP's are used:

![image](https://user-images.githubusercontent.com/19907658/29703186-c7fe3eb4-8974-11e7-9031-a24b6fa582a7.png)

**Comment by ChaelKruip** [comment]
> Minimum electric HHP capacity: 11,674 kW

> 1.2 (COP) * 1.2 (input capcity HP) = 1.44 kW

Could the input capacity be a factor 10 too high in the model?

**Comment by antw** [comment]
> With this I would say the minimum electric HHP capacity is much lower:

Sorry, I meant **MW** and **MWh**, not kW and kWh. The numbers are for the whole country, not per-heat pump.


1.294498 (kW) × 1.2107 (COP) × 7449298 (number of residences) = 11674 MW

**Comment by ChaelKruip** [comment]
> The numbers are for the whole country, not per-heat pump.

😆 If it's the same for you @antw can we perhaps use 'per heat pump' units? That's what @DorinevanderVlies and myself have more feeling for those 😄

**Comment by antw** [comment]
Sure, will do. I was taking those numbers directly out of the ETEngine graph, which represents the whole country.

**Comment by ChaelKruip** [comment]
@DorinevanderVlies what are the actions on this currently?

**Comment by DorinevanderVlies** [comment]
Closing this issue as it is too general.
Will open more detailed issues when relevant
