### ISSUE TITLE
There should be no decifits for HHPs in the start scenario with 100% HHPs

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2457]
<img width="1118" alt="cursor_and_energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_" src="https://user-images.githubusercontent.com/1303760/29704219-2c5e6d62-8979-11e7-975b-8d6cafadb37b.png">

Even if the capacity of the electric part of the HHP is insufficient, the gas-part should be able to save the game right @antw @DorinevanderVlies?

**Comment by antw** [comment]
Was fixed by quintel/etengine@fb00b15.
