### ISSUE TITLE
2013 additional infrastructure investments in table not 0 in 2013

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2458]
For an empty scenario the **additional** infrastructure investment in the table is not 0 for 2013

![image](https://user-images.githubusercontent.com/19907658/29716287-11bfb830-89ab-11e7-9290-63d4253b690b.png)

**Comment by ChaelKruip** [comment]
@antw can you please have a look?

**Comment by antw** [comment]
I'm not too familiar with the Gqueries used to calculate these costs, but this seemed to become an issue when we added the explicitly-modelled electric technologies (the dynamic electricity curve project).

I think the problem [is this line](https://github.com/quintel/etsource/blob/c9efbe253ecbcf2490b2b0e8558e95096a975b67/gqueries/modules/network/network_impact_calculations/hv_mv_trafo/network_hv_mv_trafo_peak_load_sd.gql#L10) and similar lines in other peak load queries. The load of these technologies should perhaps be wrapped in a `QUERY_DELTA` like the other values.

**Without a `QUERY_DELTA`** that query returns the following:

* Present: 49 869.86
* Future: 49 889.94

**[With a `QUERY_DELTA`](https://gist.github.com/antw/3b0323f69b804e7ba1673447d6cee769)**:

* Present: 0.0
* Future: 20.08

**Comment by ChaelKruip** [comment]
Assigning @DorinevanderVlies to take a look at this as part of https://github.com/quintel/mechanical_turk/issues/97

**Comment by DorinevanderVlies** [comment]
This issue (with this description) is fixed by https://github.com/quintel/etsource/commit/9ce203b63f090a834c9b8d84ec3265356e485798.

However there are two more issues which I will adress separately
- Initial investment costs very different on beta and on live
- with default settings additional investment costs are non-zero on beta
