### ISSUE TITLE
Additional infrastructure investment chart differs from table 

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2459]
Additional infrastructure investment chart shows **additional** investments.
The table shows something different. I would expect the chart to show the same data as the table. This issue is related to https://github.com/quintel/etmodel/issues/2458 and might be solved by solving that issue.

### screenshots
![image](https://user-images.githubusercontent.com/19907658/29716227-dcdb746a-89aa-11e7-818b-028864b78906.png)

![image](https://user-images.githubusercontent.com/19907658/29716236-e6b8886a-89aa-11e7-9483-730341ba20c3.png)

@ChaelKruip please reassign when appropriate

**Comment by ChaelKruip** [comment]
Assigning @antw. I can look into the GQL side of things if needed.

**Comment by antw** [comment]
The table shows the actual values returned by the Gqueries, while the chart shows the *difference* between the future and present. It has apparently always been this way.

If you wanted the chart to show the actual Gquery value (for the future), editing each series and assigning it to the "future" group should do the trick.

![screen shot 2017-09-06 at 15 46 56](https://user-images.githubusercontent.com/4383/30118379-cc1d0a5c-931a-11e7-83a3-12de3adf6ef7.png)

---

![screen shot 2017-09-06 at 15 47 51](https://user-images.githubusercontent.com/4383/30118386-cf69ee14-931a-11e7-8dae-6936057ceebb.png)

![screen shot 2017-09-06 at 15 47 56](https://user-images.githubusercontent.com/4383/30118387-cf860a72-931a-11e7-8539-308da61a9f05.png)

**Comment by DorinevanderVlies** [comment]
> The table shows the actual values returned by the Gqueries, while the chart shows the difference between the future and present. It has apparently always been this way.

I think it will be most clear if the chart and the table show the same values.

I propose to show the **delta** for both. I'll implement this.

However, this wil **not** fix https://github.com/quintel/etmodel/issues/2458.
