### ISSUE TITLE
Additional infrastructure investment chart shows very high amounts on beta

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2460]
Slightly related to https://github.com/quintel/etmodel/issues/2459, but a different issue.

The 2013 investment costs are very different high on beta.
In for example the Urgenda-scenario this leads to big differences between beta and live. The additional investments for this scenario are very small on beta.

I think this might be related to the dynamic heat changes. @antw what do you think?

### Screenshots of Urgenda-scenario on beta and live
**Beta**
![image](https://user-images.githubusercontent.com/19907658/29717904-3b9f24d2-89b1-11e7-9f77-d352057c3039.png)

**Live**
![image](https://user-images.githubusercontent.com/19907658/29717896-33c2962c-89b1-11e7-971b-15157bcf2178.png)

notifying @ChaelKruip

**Comment by antw** [comment]
[(Probably) related Basecamp task](https://3.basecamp.com/3797409/buckets/4288526/todos/601928006).

**Comment by DorinevanderVlies** [comment]
@antw, any idea whether this is indeed causing this very high 2013-investments?

**Comment by antw** [comment]
Haven't had the chance to look yet, sorry.

**Comment by antw** [comment]
Now on beta:

![screen shot 2017-09-18 at 18 03 28](https://user-images.githubusercontent.com/4383/30554221-b3a35c4e-9c9b-11e7-9137-37eeab77d0e4.png)

**Comment by DorinevanderVlies** [comment]
Nice fix @antw!

Does this fix only influence the network costs? Or are there more changes to the existing scenario's due to this fix?

**Comment by antw** [comment]
> Does this fix only influence the network costs?

I believe so yes.
