### ISSUE TITLE
What does the Coefficient of Performance attribute of HHP's display 

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2461]
The screenshot below show that for the space heating part of the HHP the coefficient of performance is 2.72 in present an 2.17 in the future.

- What does this attribute mean?
- How is it calculated? My guess was input share/ambient heat. However 63.2/18.01=3.5

![image](https://user-images.githubusercontent.com/19907658/29770180-00736cd0-8bee-11e7-9d6f-122f9ff02a70.png)

**Comment by antw** [comment]
In this case, ETEngine calculates COP as `1 / (1 - share_of_ambient_heat)`. I don't think it makes any sense in the context of the HHP: 

https://github.com/quintel/etengine/blob/1447a70a9774c5cc04e6307fb05e0674137746a6/app/models/qernel/converter_api/capacity_production.rb#L55-L60

**Comment by ChaelKruip** [comment]
> n this case, ETEngine calculates COP as 1 / (1 - share_of_ambient_heat). I don't think it makes any sense in the context of the HHP:

This is the definition:
```
COP = input_of_electricity / output_of_heat
```
but that is only valid at times when the heat pump is working.

BTW: The above simplifies as follows:
```
COP = output_of_heat / input_of_electricity
    = (input_of_electricity + input_of_ambient_heat) / input_of_electricity
    = 1 / (1 - input_of_ambient_heat)
```
when you set `input_of_electricity + input_of_ambient_heat = 1`.

**Comment by antw** [comment]
> This is the definition: [...]

What I mean is that ETE does not respect that the HHP has more than two carriers as inputs; this has always been the case. The COP calculation makes sense if the gas and electric components were separate nodes (as on normal electric heat pumps), but not when the HHP is modelled as a single node.

For what it's worth, there isn't a single reference to the `coefficient_of_performance` attribute in ETSource.

**Comment by DorinevanderVlies** [comment]
>For what it's worth, there isn't a single reference to the coefficient_of_performance attribute in ETSource.

I think this average COP when the electric part of the HHP is working is an interesting value to display. Especially when the threshold is set in a scenario.

The following equation also holds and will for HHP give the average COP for the HP-part:
```
COP = (input_of_electricity + input_ambient) / input_of_electricity
```
Because:
```
HHP:
output.useable_heat.ambient_heat = 1
output.useable_heat.electricity = 1
electric and ground HP:
output.useable_heat = 1.0
```
---
On the other hand like @antw says:
>For what it's worth, there isn't a single reference to the coefficient_of_performance attribute in ETSource.

So we can also not change the equation. In that case I would propose not to display Coefficient of performance in the converter summary of HHP's.

**Comment by DorinevanderVlies** [comment]
> For what it's worth, there isn't a single reference to the coefficient_of_performance attribute in ETSource.


closing as no priority at all
