### ISSUE TITLE
Final energy demand of heating and hot water residences still contains electricity and ambient heat when threshold COP= 6

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2462]
In a scenario for the Netherlands with 100% HHP and threshold Cop 6 for both SH and HW the dynamic demand curve shows no electricity for SH and HW.

However the final energy charts do show electricity and ambient heat for SH and HW.
This demand is also shown in the nodes on ETEngine

Below an overview of input shares for the SH HHP node for various COP-thresholds and a screenshot of the final energy charts.

notifying @ChaelKruip 

![image](https://user-images.githubusercontent.com/19907658/29773538-3760c71e-8bfe-11e7-97c6-146c05706524.png)

![image](https://user-images.githubusercontent.com/19907658/29773630-9d3a3bb0-8bfe-11e7-9cb5-5b7a5f5e994a.png)

**Comment by antw** [comment]
This morning's change allowing the HHP gas component to fill the buffer seems to be responsible. I have reverted the change and will revisit that behaviour soon.

![screen shot 2017-08-28 at 13 46 44](https://user-images.githubusercontent.com/4383/29773894-5c3ae026-8bf7-11e7-9165-66a57fe90fd4.png)
