### ISSUE TITLE
HHP should not be able to use more than 1.2 kW of electricity

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2463]
In a 100% HHP-scenario with threshold COP for water on 6, during the coldest week of the year I assume the electric part of the HHP is mostly running at full power to provide space heating.

Number of residences 7500000 * input capacity HHP 1.3 kW ~ 9,700 MW. This corresponds to demand the chart I'm seeing for this situation:

![image](https://user-images.githubusercontent.com/19907658/29774688-ad57e958-8c02-11e7-9723-2032c30bd2a7.png)

When I lower the threshold COP for hot water to 1 I expect the total electric demand of the HHP to stay the same. Because the HHP was already running at maximal capacity part of the capacity will now be used to refill the water buffer. So I will expect less input power for space heating and more input power for water heating.

However the total demand for HHP increases to above 15,000 MW which is higher than 1.3 kW per household. 15.000 MW/ 7500000 = 2 kW

![image](https://user-images.githubusercontent.com/19907658/29774908-8bde6418-8c03-11e7-9f08-63c4b7713cdd.png)
 
notifying @ChaelKruip

**Comment by ChaelKruip** [comment]
Nice catch @DorinevanderVlies!

**Comment by antw** [comment]
Sorry, this was an oversight on my part; these aren't set up to prioritise hot water over space heating, but are instead two separate producers each with their own capacities. I'll fix this.
