### ISSUE TITLE
When trying to load an existing scenario on beta, I get an error message

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2465]
I get this error message, regardless of whether I use the 'Settings >> Load scenario' option or try and load a preset scenario from the home page. 

'Settings >> Load scenario'
![image](https://user-images.githubusercontent.com/308563/29914229-0c00a4d6-8e38-11e7-84e1-db72b3c73d49.png)

Home page >> Start and existing scenario:
![image](https://user-images.githubusercontent.com/308563/29914139-ba31ea20-8e37-11e7-9f2f-a39371c899f2.png)

**Comment by AlexanderWirtz** [comment]
Aha, I can in fact load scenarios using incognito mode. Seems like an issue with cookies or sth

**Comment by grdw** [comment]
This is really odd behavior. Also Airbrake or the logs aren't raising the error which makes it even weirder. @antw would you recognize what this *could* be purely by looking at it?

**Comment by AlexanderWirtz** [comment]
I assume it is something to do with Browsing data, but before I start clearing everything, it may be interesting to figure out what this could be.

**Comment by antw** [comment]
There doesn't seem to be anything in the log either. I'm a bit stumped by this; the only the that occurred to me is something like #2322, however that would surely affect everyone and I can load that scenario (423882) just fine.

**Comment by antw** [comment]
I'm not sure what log file I was looking at before (😊). This appears to be the error:

```
F, [2017-08-31T10:33:43.896932 #15849] FATAL -- : [531f9a86-974b-48dd-b2eb-ded406e57286] NoMethodError (undefined method `analysis_year' for nil:NilClass):
F, [2017-08-31T10:33:43.896946 #15849] FATAL -- : [531f9a86-974b-48dd-b2eb-ded406e57286]
F, [2017-08-31T10:33:43.896959 #15849] FATAL -- : [531f9a86-974b-48dd-b2eb-ded406e57286] app/models/setting.rb:97:in `start_year'
[531f9a86-974b-48dd-b2eb-ded406e57286] app/models/setting.rb:153:in `public_send'
[531f9a86-974b-48dd-b2eb-ded406e57286] app/models/setting.rb:153:in `block in to_hash'
[531f9a86-974b-48dd-b2eb-ded406e57286] app/models/setting.rb:152:in `each'
[531f9a86-974b-48dd-b2eb-ded406e57286] app/models/setting.rb:152:in `each_with_object'
[531f9a86-974b-48dd-b2eb-ded406e57286] app/models/setting.rb:152:in `to_hash'
[531f9a86-974b-48dd-b2eb-ded406e57286] config/initializers/andand.rb:59:in `me'
I, [2017-08-31T10:33:43.897395 #15849]  INFO -- : [531f9a86-974b-48dd-b2eb-ded406e57286] Processing by ErrorsController#show as HTML
```

Perhaps @AlexanderWirtz previous scenario was for a dataset which has been removed? (Barendrecht)

**Comment by AlexanderWirtz** [comment]
Not the first time something like this happens to me. @dennisschoenmakers seems to have understood what was going on then. I cleared all my Browsing data and that fixed it.

**Comment by AlexanderWirtz** [comment]
Update:
Clearing past 4 weeks browsing data does NOT resolve this. Screenshot was taken after removing browsing data, but same check-boxes checked to show which data I cleared.

![image](https://user-images.githubusercontent.com/308563/29959995-306b2072-8efa-11e7-94de-72352c2c01c4.png)

**Comment by AlexanderWirtz** [comment]
> Perhaps @AlexanderWirtz's previous scenario was for a dataset which has been removed? (Barendrecht)

This could well be the case, actually. How can I cleanse my digital self from this stain from my past?

**Comment by antw** [comment]
@AlexanderWirtz I deployed a possible fix. Can you try it again and see if you're able to get any further?

I'm not too hopeful... clearing your cookies will have separated you from your old scenario; if it *was* a deleted region causing this, removing your cookies should have fixed it.

**Comment by AlexanderWirtz** [comment]
Yes! Whatever you did, it is now fixed. Thanks a lot!
