### ISSUE TITLE
Heat demand and production chart shows charging of buffers, even though buffer size = 0

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2467]
[This scenario](https://beta-pro.energytransitionmodel.com/scenarios/719385) has 100% electric heat pumps voor both space and water heating, the buffer size is set to 0 kWh.

The heat demand and production chart still shows charging of the buffers. This shouldn't be the case.

![image](https://user-images.githubusercontent.com/19907658/30014826-9a3322b0-914e-11e7-9620-7901915525e7.png)

notifying @ChaelKruip

**Comment by antw** [comment]
This is not buffering, but is demand being time-shifted (deferred) into the future when the space heating producers have insufficient capacity to meet demand.

I intend for a future improvement to the chart to show this differently, which should avoid confusion with buffering.

**Comment by DorinevanderVlies** [comment]
thanks for the info!
