### ISSUE TITLE
"Converted to heat for industry" should be added to the use of flexibility options per hour chart

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2468]
Conversion to heat for industry is currenlty not shown in the "use of flexibility options per household" chart.

![image](https://user-images.githubusercontent.com/19907658/30025770-4d774c18-917a-11e7-807c-5177f08e812d.png)

![image](https://user-images.githubusercontent.com/19907658/30025762-3e9ccaba-917a-11e7-8807-11404229c0f7.png)

notifying @ChaelKruip and @antw

**Comment by DorinevanderVlies** [comment]
Analogue to the way flexibility p2g is implemented in this chart I would like to add a series with the following gquery:

Name: industry_flexibility_p2g_electricity
Query: MERIT_LOAD_CURVES(:flexibility_p2h_electricity)

However this query does not work (yet). @antw, can you help me with this? Does anything have to be changed in merit?

**Comment by antw** [comment]
```ruby
MERIT_LOAD_CURVES(:households_flexibility_p2h_electricity)
MERIT_LOAD_CURVES(:industry_chemicals_other_flexibility_p2h_electricity)
MERIT_LOAD_CURVES(:industry_chemicals_refineries_flexibility_p2h_electricity)
MERIT_LOAD_CURVES(:industry_other_food_flexibility_p2h_electricity)
MERIT_LOAD_CURVES(:industry_other_paper_flexibility_p2h_electricity)
```

If you want the four industry series' to be combined as one (I'd recommend this as it will reduce the amount of data which must be sent between ETEngine and ETModel) then I'll need to make some additional changes to ETEngine.

**Comment by DorinevanderVlies** [comment]
I implemented this change: https://github.com/quintel/etsource/pull/1336/commits/b4d90c5632ea659b97d9de7293c8e9e7157ff57c. The query sums the four arrays, so the combined series is shown in the chart.

Will that do as well? Or would combining the series on ETEngine be cleaner?

**Comment by ChaelKruip** [comment]
> Or would combining the series on ETEngine be cleaner?

It would likely improve performance.

**Comment by ChaelKruip** [comment]
I have merged https://github.com/quintel/etsource/pull/1336 so it all works. If @antw has created a summed series, we can easily change the query to refer to that.
