### ISSUE TITLE
HP ground should not have a temperature dependent COP

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2469]
The COP of both the HP ground for water and for space should not be dependent on ambient temperature.

The standard division among ambient_heat and electricity applies at all time:
`- input.ambient_heat = 0.791666666666667`
`- input.electricity = 0.208333333333333`

notifying @ChaelKruip

**Comment by antw** [comment]
Removing...

```
- fever.efficiency_balanced_with = ambient_heat
- fever.efficiency_based_on = electricity
```

... from the relevant node files should fix this.

**Comment by DorinevanderVlies** [comment]
Will do, will also remove 
`- fever.base_cop = 3.25`
`- fever.cop_per_degree = 0.0875`
