### ISSUE TITLE
with default settings additional investment costs are non-zero on beta

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2481]
The delta between the total investment costs is non-zero (16 mln) for an empty scenario on beta.

@antw, can this be because we use a different calculation method for the present and the future year?

![image](https://user-images.githubusercontent.com/19907658/30220183-bf79bc82-94be-11e7-9f55-ce5059df8c52.png)

notifying @ChaelKruip

**Comment by antw** [comment]
> @antw, can this be because we use a different calculation method for the present and the future year?

Almost certainly. However, I wouldn't trust the *exact* numbers right now since the detection of peak loads is obviously incorrect. I'll get my fix for that finished soon and then we can see what the costs look like with the correct electricity curves.

**Comment by DorinevanderVlies** [comment]
The current status of this issue is that the required additional investments in infrastructure have become a lot smaller, but they are not zero:

![image](https://user-images.githubusercontent.com/19907658/30659470-2bc9ad6a-9e3e-11e7-8209-f2486a08f73a.png)

I suppose that we are not going to get rid of this difference completely due to the changes implemented in the dynamic heat project. IMO the difference is small enough to close this issue. 

@ChaelKruip do you agree?

**Comment by ChaelKruip** [comment]
I agree. The extra investment costs are due to the fact that we dynamically model electricity in the future year but not for the present. Right @antw? 

Closing!

**Comment by antw** [comment]
> we dynamically model electricity in the future year but not for the present. Right @antw?

Correct. In fact I can be more specific, since I investigated this before the changes were pushed. The investment costs for the future are different mostly because the air heat pump efficiency varies with air temperature.

**Comment by DorinevanderVlies** [comment]
thanks!
