### ISSUE TITLE
Increasing P2H in a scenario with excess electricity should result in lower CO2 and higher renewables share

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2487]
Issue https://github.com/quintel/etmodel/issues/2477 did indeed fix the "connection" between households_useful_demand_for_hot_water_for_houses_with_p2h and 
 households_flexibility_p2h_electricity.

However, the failed mechanical turk test which brought this bug to light still fails.

Increasing the P2H on live results in less energy use, lower CO2 emissions, less and higher share of renewables.
Increasing the P2H on Beta results in less energy use, equal CO2 emission and equal share of renewables.
I would say Live gets it right.

I'll dive into this. @antw and @ChaelKruip do you have ideas on the causes of this difference between beta and live?

---
### Screenshots
**Excess electricity without P2H (left Beta, right Live)**
![image](https://user-images.githubusercontent.com/19907658/30363605-27e3fb16-9861-11e7-8dae-6e01858da493.png)

**Excess electricity with P2H (left Beta, right Live)**
![image](https://user-images.githubusercontent.com/19907658/30363636-41dfeb92-9861-11e7-984c-c37e707cdb5a.png)

---
### Mechanical turk test
This issues originates from Mechanical Turk failure:
rspec ./spec/flexibility/flexibility_spec.rb:123 # Flexibility P2H In a scenario increasing the number of P2H units should decrease CO2 emissions

Scenario is made with excess electricity (10,000 turbines inland).
Increasing P2H electric boiler to 20% share should decrease CO2

In the Use of excess electricity chart this results in a decrease in excess electricity, but not in an increase of converted to heat for households.

**Comment by antw** [comment]
> I'll dive into this.

No need; I'm pretty sure I know what the problem is. I'll push a fix today.

**Comment by DorinevanderVlies** [comment]
> No need; I'm pretty sure I know what the problem is. I'll push a fix today.

Sounds good :smiley:

**Comment by antw** [comment]
Pushed a fix, but it's curently incomplete. It is still a problem that if you add P2H other hot water technologies will begin to show a deficit, since they're not accounting for heat demand which is being satisfied by P2H. Fixing that *should* be easy, but it's ETEngine we're talking about so of course it's anything but... 😣

I'll update this again once I have a fix for the deficits.

**Comment by antw** [comment]
A fix is now in place. The heat chart will still show a deficit when using P2H (quintel/etengine#948) but I'm reasonably confident that there is no _actual_ deficit in the graph. I will resolve this soon.
