### ISSUE TITLE
number_of_buildings attribute is not updated when slide `number_of_buildings` is set

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2488]
When setting the slider `number_of_buildings` the demands change accordingly.
However, the attribute `number_of_buildings` does not change. This results in wrong insulation costs for buildings. 

![image](https://user-images.githubusercontent.com/19907658/30534822-2458e968-9c60-11e7-8fd9-3a13dd7c1a19.png)
![image](https://user-images.githubusercontent.com/19907658/30534843-39a91bda-9c60-11e7-9b92-3ee0473b8323.png)

Work in progress
notifying @ChaelKruip

**Comment by ChaelKruip** [comment]
This also happens on PRODUCTION
