### ISSUE TITLE
Don't show the empty series the legend of the heat deficit chart 

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2489]
During the wrap-up of the dynamic heat project we discussed that the legend of the dynamic heat chart is currently very elaborate. 

@antw is it possible to just show the non-empty series in the legend?

![image](https://user-images.githubusercontent.com/19907658/30631088-60706d52-9de3-11e7-843c-34e2af842872.png)

notifying @jorisberkhout @AlexanderWirtz @grdw @ChaelKruip @MichielDenHaan @BerendSmits

**Comment by AlexanderWirtz** [comment]
In fact, there are a few more charts that qualify for this.

**Comment by DorinevanderVlies** [comment]
> In fact, there are a few more charts that qualify for this.

Good point, I'll make an inventarisation

**Comment by DorinevanderVlies** [comment]
The heat deficit chart has by far the most legend items (25)

Other charts with many legend items are:
![image](https://user-images.githubusercontent.com/19907658/30649964-faea8294-9e21-11e7-92f8-eee24a3a71c5.png)

**Comment by AlexanderWirtz** [comment]
> Other charts with many legend items are:

I think GitHub needs an `applaud` button like Basecamp has!

**Comment by grdw** [comment]
> @antw is it possible to just show the non-empty series in the legend?

Can I answer with yes! :) I think [this functionality](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/d3/merit_order_hourly_supply.coffee#L38-L44) already exists within other charts.

**Comment by grdw** [comment]
What is seen as a significant value for these charts? 

I now picked that a value larger than 10e-6 might actually still be 'somewhat' useful to show in a legend. Anything lower than that is not shown in the legend. 

Should this be done for any type of chart? The https://github.com/quintel/etmodel/pull/2492 will only apply to 'vertically stacked bar charts'.

**Comment by DorinevanderVlies** [comment]
>The fix at #2492

Nice!

> I now picked that a value larger than 10e-6 might actually still be 'somewhat' useful to show in a legend. Anything lower than that is not shown in the legend.

I think 10e-6 is fine

> Should this be done for any type of chart?

Would be awesome

**Comment by grdw** [comment]
> Would be awesome

I'm going to investigate how long that is going to take me 🤔 moment please.

**Comment by grdw** [comment]
These are all the types:

- [ ] bezier
- [ ] time_curve
- [ ] mekko
- [ ] vertical_stacked_bar
- [ ] line
- [ ] waterfall
- [ ] horizontal_stacked_bar
- [ ] grouped_vertical_bar
- [ ] block
- [ ] co2_emissions_biomass
- [ ] html_table
- [ ] scatter
- [ ] sankey
- [ ] refinery
- [ ] target_bar
- [ ] d3
- [ ] storage
- [ ] import_export_cwe
- [ ] import_export_flows
- [ ] import_export_renewables
- [ ] import_export_capacity
- [ ] dynamic_demand_curve
- [ ] heat_demand_and_production

**Comment by grdw** [comment]
I propose the following, we merge the fix at #2492 , the other chart types will have to wait, until there's a valid reason to also apply fixes for those.

**Comment by DorinevanderVlies** [comment]
Result from a short discussion with @grdw:
We're also going to tackle "bezier" charts.

That will fix most of the charts with too long legends.

**Comment by grdw** [comment]
Closing this, as is it fixed with https://github.com/quintel/etmodel/pull/2492

**Comment by DorinevanderVlies** [comment]
Nice work @grdw
