### ISSUE TITLE
Should we run hourly calculations for present?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2497]
Following up on the discussion in https://github.com/quintel/etmodel/issues/2481, we are currently in the position where we run Merit and Fever for the future year, but the present is still 'non-dynamic'.

As a result, there are differences (delta's) in the outcomes of the model which are not related to slider settings of the user. I think we should try to minimise these as much as possible.

The only two reasons I currently see for not running Fever for the present:
* Performance (how bad would the penalty be @antw?)
* Import/export of electricity in the present year currently is representative for what actually happened in the start-year. If we would run Merit (without improving our modelling of electricity import/export), import would disappear from the start-year and you would begin with an 'unrepresentative' dataset.

@DorinevanderVlies @jorisberkhout @AlexanderWirtz @BerendSmits @MichielDenHaan I'm curious about your opinions on this.

**Comment by DorinevanderVlies** [comment]
When it comes to heat pump behaviour and electricity load I think it would be an improvement if start-year and end year are equal when no sliders are set as long as this does not introduce other inconsistencies.

Something we should also consider is the impact on the analysis for making a new dataset. When all behaviour is fixed calculation from final to useful demand is straightforward. However, when technologies have dynamic behaviour in the start-year this might (in the worst case) become an iterative process.

---
> Performance 

Running the start year would only have to happen once as it is not influenced by slider settings. Perhaps that reduces the "penalty"

> Import/export of electricity in the present year currently is representative for what actually happened in the start-year....()

Is it just the import and export? Or would hourly calculation for the start-year also influence the behaviour of the whole supply side? Or can we go round this by not enabling merit for the start-year?

**Comment by ChaelKruip** [comment]
> However, when technologies have dynamic behaviour in the start-year this might (in the worst case) become an iterative process.

Good point! I did not consider that.

> Running the start year would only have to happen once as it is not influenced by slider settings. Perhaps that reduces the "penalty"

Good point as well.

> Or would hourly calculation for the start-year also influence the behaviour of the whole supply side? 

Yes. 

> Or can we go round this by not enabling merit for the start-year?

Yes. But I'm not sure if you can run Fever without running Merit 😟  @antw what do you think?

**Comment by antw** [comment]
> Performance (how bad would the penalty be @antw?)

On my laptop:

* Today (Time-resolved loads on future graph only): **1.6s-1.8s**
* Time resolved loads on future and present graphs: **2.7s-2.9s**

A large part of ETEngine's response time is due to time-resolved loads; both in calculating Merit and Fever (heat), and the need to compute the graph a second time (requiring the dataset to be cloned again, which is expensive in both CPU time and memory [which has to be garbage collected]).

> Running the start year would only have to happen once as it is not influenced by slider settings. Perhaps that reduces the "penalty"

Sadly this is not so. As long as we can have `both` and `present` inputs, the present graph is *not* immutable and needs to be calculated each time.

**Comment by DorinevanderVlies** [comment]
> Sadly this is not so. As long as we can have both and present inputs, the present graph is not immutable and needs to be calculated each time.

Do we need to keep those? My first thought is that we used the present and both statements to initialize local datasets when we didn't have initializer inputs and that they are not used anymore.

**Comment by grdw** [comment]
> ... That we used the present and both statements to initialize local datasets

Well yes. But they are *also* in the regular inputs:

```
# Update period 'both'
inputs/area/areable_land.ad
inputs/area/buildings_roof_surface_available_for_pv.ad
inputs/area/co2_emission_1990.ad
inputs/area/coast_line.ad
inputs/area/land_available_for_solar.ad
inputs/area/number_of_buildings_both.ad
inputs/area/number_of_inhabitants.ad
inputs/area/number_of_new_residences.ad
inputs/area/number_of_old_residences.ad
inputs/area/number_of_residences.ad
inputs/area/offshore_suitable_for_wind.ad
inputs/area/onshore_suitable_for_wind.ad
inputs/area/residences_roof_surface_available_for_pv.ad
inputs/misc/settings_enable_merit_order.ad
inputs/modules/employment/employment_fraction_production.ad
inputs/modules/employment/employment_economic_multiplier.ad
inputs/modules/employment/employment_local_fraction.ad
inputs/targets/policy_cost_electricity_cost.ad
inputs/targets/policy_cost_total_energy_cost.ad
inputs/targets/policy_sustainability_co2_emissions.ad
inputs/targets/policy_sustainability_renewable_percentage.ad
```

```
# Update period present
inputs/area/number_of_buildings_present.ad
inputs/area/number_of_inhabitants_present.ad
inputs/c02_biomass/climate_relevant_co2_biomass_gas_present.ad
inputs/c02_biomass/climate_relevant_co2_biomass_liquid_present.ad
inputs/c02_biomass/climate_relevant_co2_biomass_solid_present.ad
```

**Comment by BerendSmits** [comment]
> Do we need to keep those? My first thought is that we used the present and both statements to initialize local datasets when we didn't have initializer inputs and that they are not used anymore.

It's true these are not used in our current methods for making datasets, they are however used by quite a lot of old 'datasets' (living as scenario's). 

For instance:

- IABR 
- GEA 
- Ameland
- Next Electric
- Zuid-Holland

The nice thing to do would be to make datasets in the proper new manor for each of these areas, but that would take some time.

**Comment by BerendSmits** [comment]
> they are also in the regular inputs:

I think the area ones are not attached to sliders, but have the same function as adjust scaling ones. As for employment, targets and co2_biomass, I don't think you need to rerun ETEngine for those. 

But this is a lot of 'thinking' on my part, would you agree (or know a trick to find out) @grwd?

**Comment by MichielDenHaan** [comment]
> Import/export of electricity in the present year currently is representative for what actually happened in the start-year. If we would run Merit (without improving our modelling of electricity import/export), import would disappear from the start-year and you would begin with an 'unrepresentative' dataset.

That would be a pity, I think its an interesting statistic for end users

**Comment by ChaelKruip** [comment]
> Is it just the import and export? Or would hourly calculation for the start-year also influence the behaviour of the whole supply side? Or can we go round this by not enabling merit for the start-year?

> That would be a pity, I think its an interesting statistic for end users

This is a tricky conundrum... 

If we dynamically calculate the present year (and 'freeze the result) by running Fever and Merit, there are no delta's expected between the present and the future results of the ETM with the exception of import/export of primary carriers as a result of time-curves. This will likely result in present-year results that are different from those obtained with the dataset analysis (which assumes different full-load-hours than Merit calculates).

If we don't dynamically calculate the present year, we are stuck with the current situation where there are going to be increasingly big differences between the present ad future year results *solely* because we use a different calculation method. This obfuscates the outcomes of the ETM and makes it difficult to interpret results.

Perhaps in the future it will be possible to construct a dataset (with ETLocal?!) for the ETM that is very close to the actual present-year statistics (also for the Supply side) but works dynamically? 
My feeling is that this would require us to model import and export of electricity based on a price curve for foreign electricity...

**Comment by DorinevanderVlies** [comment]
> Perhaps in the future it will be possible to construct a dataset (with ETLocal?!) for the ETM that is very close to the actual present-year statistics (also for the Supply side) but works dynamically?
My feeling is that this would require us to model import and export of electricity based on a price curve for foreign electricity...

Sounds like a nice aim
