### ISSUE TITLE
Should we add losses of all export to primary demand?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2498]
As an extension of https://github.com/quintel/etmodel/issues/2486, I was wondering if we shouldn't add all losses (primary_demand - demand) of the export nodes related to refinery products as well to the primary demand dashboard...

My first guess would be 'yes' as these (transformation) losses are accounted for by the producing country right?

**Comment by AlexanderWirtz** [comment]
They should be accounted for by the producing country, indeed. Perhaps the extended energy balance provides some clues as to the nature of these losses.

**Comment by ChaelKruip** [comment]
> Perhaps the extended energy balance provides some clues as to the nature of these losses.

@DorinevanderVlies @MichielDenHaan @jorisberkhout do you know this?
