### ISSUE TITLE
Error when loading batches of scenarios

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2500]
```
F, [2017-10-05T15:31:58.176149 #24338] FATAL -- : [aca49b5c-fca6-42a4-a264-b5f3036971e1]
F, [2017-10-05T15:31:58.176838 #24338] FATAL -- : [aca49b5c-fca6-42a4-a264-b5f3036971e1] NoMethodError (undefined method `map' for #<HTTParty::Response:0x007fa03d2292e8>):
F, [2017-10-05T15:31:58.176939 #24338] FATAL -- : [aca49b5c-fca6-42a4-a264-b5f3036971e1]
F, [2017-10-05T15:31:58.177029 #24338] FATAL -- : [aca49b5c-fca6-42a4-a264-b5f3036971e1] app/models/api/scenario.rb:20:in `batch_load'
[aca49b5c-fca6-42a4-a264-b5f3036971e1] app/models/saved_scenario.rb:24:in `batch_load'
[aca49b5c-fca6-42a4-a264-b5f3036971e1] app/controllers/scenarios_controller.rb:34:in `index'
```

Airbrake doesn't notify this btw.

**Comment by antw** [comment]
What error is ETEngine returning?

[I expect this one](https://quintel.airbrake.io/projects/35333/groups/2054418262143293958?tab=overview): Could not find a dataset with the key "barendrecht"

> Airbrake doesn't notify this btw.

[Here's the ETModel Airbrake notification](https://quintel.airbrake.io/projects/32209/groups/2009305847743453930?tab=overview).

**Comment by grdw** [comment]
Aha, it's ETEngine that's receiving the error not ETModel. Was looking into the wrong project on Airbrake

**Comment by grdw** [comment]
Related: https://github.com/quintel/etengine/issues/951

**Comment by grdw** [comment]
@ChaelKruip should we remove the 9 Barendrecht scenarios or? I don't know if they're actually used in any way?

![screen shot 2017-10-05 at 17 29 55](https://user-images.githubusercontent.com/2676542/31235879-ddf0ec5a-a9f2-11e7-9479-889797d8d96b.png)

**Comment by ChaelKruip** [comment]
> @ChaelKruip should we remove the 9 Barendrecht scenarios or? I don't know if they're actually used in any way?

I think this is a question for @AlexanderWirtz and @DorinevanderVlies (I have no idea)

**Comment by DorinevanderVlies** [comment]
I do not use them

**Comment by grdw** [comment]
I take that as a 'yes'. I'll export the 'scenarios' table first and then I'll delete them. If you feel you need them anytime soon, come ask me 👍

**Comment by grdw** [comment]
Closing
