### ISSUE TITLE
Centralized district heating slider is 0% even though local dataset sets it to 99.7%

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2504]
In the .yml I set:

```yaml
  :"buildings_chp_engine_biogas-buildings_final_demand_steam_hot_water@steam_hot_water": 0.0029
  :"buildings_collective_chp_network_gas-buildings_final_demand_steam_hot_water@steam_hot_water": 0
  :"buildings_collective_chp_wood_pellets-buildings_final_demand_steam_hot_water@steam_hot_water": 0
  :"buildings_collective_geothermal-buildings_final_demand_steam_hot_water@steam_hot_water": 0
  :"buildings_heat_network_connection_steam_hot_water-buildings_final_demand_steam_hot_water@steam_hot_water": 0.9971
```
Biogas chp is correctly set to 0.3% but centralized heating district is 0 (see screenshot). Setting biomass, gas, geothermal to non-zero values works fine.
![screen shot 2017-10-10 at 11 07 14](https://user-images.githubusercontent.com/32056448/31378356-46e82ec4-adab-11e7-9541-23c0cab14ad7.png)

Workaround:
 
```yaml
  :"buildings_chp_engine_biogas-buildings_final_demand_steam_hot_water@steam_hot_water": 0.0029
  :"buildings_collective_chp_network_gas-buildings_final_demand_steam_hot_water@steam_hot_water": 0
  :"buildings_collective_chp_wood_pellets-buildings_final_demand_steam_hot_water@steam_hot_water": 0
  :"buildings_collective_geothermal-buildings_final_demand_steam_hot_water@steam_hot_water": 0
  #:"buildings_heat_network_connection_steam_hot_water-buildings_final_demand_steam_hot_water@steam_hot_water": 0.9971
```

![screen shot 2017-10-10 at 10 57 47](https://user-images.githubusercontent.com/32056448/31378031-4f83c076-adaa-11e7-8222-81e7f54bca9b.png)

**Comment by ChaelKruip** [comment]
On which branch are you working @MichielDenHaan?

**Comment by grdw** [comment]
I actually made this issue together with @MichielDenHaan so all is fine actually 👍 this is a bug. It's either ETModel which can't balance the sliders or it's something in the initializers. What is odd, is that I can remember something similar was happening with the `initializer inputs` (specify all but 1 of a share group).

**Comment by grdw** [comment]
![screen shot 2017-10-10 at 14 16 26](https://user-images.githubusercontent.com/2676542/31386011-9e5a63c4-adc5-11e7-82ac-ffb1982ddeb1.png)

The `buildings_heat_network_connection_steam_hot_water-buildings_final_demand_steam_hot_water@steam_hot_water` edge is a 'flexible' edge. Which I think exists as a share which share value are determined like I specified in the above comment:

> Specify all but 1 of a share group (so `1 - 'the sum of the rest of the shares in that share group'`)

By actually explicitly specifying this share the whole things breaks.

Please correct me if I'm wrong @antw

**Comment by grdw** [comment]
Now the real questions:

1. How do we deal with this in the Excel?
2. Should they be explicitly in the yml?
3. Are there any other 'flex' shares which are set, which are causing similar issues?

**Comment by ChaelKruip** [comment]
> How do we deal with this in the Excel?

I don't understand why it is relevant how we deal with this in Excel 😟 . This is behaviour which is happening in ETEngine right?

> Should they be explicitly set in the graph values yml?

It would be nice for completeness IMO but not essential. 

> Are there any other 'flex' shares which are set, which are causing similar issues?

* Households space heating:
![cursor_and_energytransitionmodel](https://user-images.githubusercontent.com/1303760/31391619-5bf0d9de-add7-11e7-81d7-39a4704cb971.png)

* Households hot water:
![cursor_and_energytransitionmodel](https://user-images.githubusercontent.com/1303760/31391668-7b4ab836-add7-11e7-9970-11555f1765f7.png)

* Households cooking
* Buildings heating
* Possibly others

What confuses me is that for instance this share group (cars) in transport does not have a flexible share:
![cursor_and_energytransitionmodel](https://user-images.githubusercontent.com/1303760/31391801-d74647f4-add7-11e7-922a-572e8b554b93.png)

@antw can we remove all flexible links in share groups and would this solve the above issue?

**Comment by antw** [comment]
> can we remove all flexible links in share groups and would this solve the above issue?

There would almost certainly be some queries to be updated, but I guess so.

However I don't like that as a solution to this problem, because it will happen again someday that someone tries to specify a share for a flexible edge with initializer methods.

I think it should be the responsibility of the initializer method to check the type of the edge and do the correct thing (i.e., in this case, ignore the value and do not set a share).

With that said, I do not understand why the custom share for the flexible edge is ignored and instead results in 0.0. Either ETE should respect the share set, or ignore it and calculate the share dynamically. Either way, it should result in 99%. How does it end up as 0%?

**Comment by grdw** [comment]
--

In response to @ChaelKruip :

> I don't understand why it is relevant how we deal with this in Excel 😟 . This is behaviour which is happening in ETEngine right?

> It would be nice for completeness IMO but not essential.

Yes, but @MichielDenHaan now copy pastes the end-result of that Excel into the Yaml, so it's the source - kind of. And I'm more thinking about the 'documentation' of that number. It could be left out of the Yaml (as the workaround suggests). 

--

In response to @antw :

> I think it should be the responsibility of the initializer method to check the type of the edge and do the correct thing (i.e., in this case ignore the value and do not set a share?).

That, or write a new validator that will raise an error whenever somebody whitelists a flexible share. 

> How does it end up as 0%?

I was hoping you could tell me 😅 but it's clearly a bug than. Could it be related to merit in someway? Or let me ask a more basic question first: what is the purpose of a flexible share?

**Comment by MichielDenHaan** [comment]
This does not seem to be an issue for all flexible shares. I just tested for households hot water by setting: 
```yaml  :"households_water_heater_coal_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0
  :"households_water_heater_combined_network_gas_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0.848889120002718
  :"households_water_heater_crude_oil_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0
  :"households_water_heater_district_heating_steam_hot_water_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0
  :"households_water_heater_fuel_cell_chp_network_gas_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0
  :"households_water_heater_heatpump_air_water_electricity_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0.0176397866914411
  :"households_water_heater_heatpump_ground_water_electricity_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0.0749336638103457
  :"households_water_heater_hybrid_heatpump_air_water_electricity_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0
  :"households_water_heater_micro_chp_network_gas_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat":  0
  :"households_water_heater_network_gas_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0.0334983128299795
  :"households_water_heater_resistive_electricity_aggregator-households_useful_demand_for_hot_water_after_solar_heater_and_p2h@useable_heat": 0.0250391166655157
```
Result:
![screen shot 2017-10-10 at 17 17 50](https://user-images.githubusercontent.com/32056448/31394587-f6e195f8-adde-11e7-91aa-8ee69ea22ebb.png)
According to @ChaelKruip's post, the gas water heater share is flexible. However, the share is correct (3.3%) even though it is explicitly set in the .yml.

**Comment by grdw** [comment]
So perhaps it's just this (`buildings_heat_network_connection_steam_hot_water-buildings_final_demand_steam_hot_water@steam_hot_water`) single share for some reason 🤔

**Comment by MichielDenHaan** [comment]
When I set:
`:"households_heat_network_connection_steam_hot_water-households_final_demand_steam_hot_water@steam_hot_water": 1` it breaks down as well (all shares are 0)
