### ISSUE TITLE
Final demand for space heating sky high for nl2015 dataset future

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2505]
A first version of the nl2015 dataset has been committed to the `nl_2015_update` branch on ETSource.

Most of it is working fine. However...
The final demand for space heating is very high for the future. The useful demand is constant (as it should be).
Final demand for hot water is fine.

Me and @ChaelKruip had a look. We noticed that:
- Space heater deficits are really high for the future
- The tiny demand that is left (which is not deficit) results in very high final demand

@antw do you have an idea why this is and how to fix it?

### Screenshots

![image](https://user-images.githubusercontent.com/19907658/31394756-62f56724-addf-11e7-912a-52d5f1e59cdb.png)

![image](https://user-images.githubusercontent.com/19907658/31394767-6cdc9b9a-addf-11e7-8312-05849432728e.png)

![image](https://user-images.githubusercontent.com/19907658/31394998-fa3e30d4-addf-11e7-9465-ae6b27c4ccca.png)

![image](https://user-images.githubusercontent.com/19907658/31395026-11157e7a-ade0-11e7-9d9d-5ebcc857e902.png)

Note: the dataset nl2015 is not available from the front end. I made an empty scenario with this dataset by creating an empty scenario in the nl dataset and changing the area in ETEngine.

Notifying @ChaelKruip

**Comment by antw** [comment]
The heat profiles (`insulated_household.csv` and `non_insulated_household.csv`) are supposed to sum to 1/3600.

Currently:

* `heat/default/insulated_household.csv`: 3838.3
* `heat/default/non_insulated_household.csv`: 12089.1

**Comment by DorinevanderVlies** [comment]
Thanks!!! I'll fix this

**Comment by DorinevanderVlies** [comment]
:tada:

![image](https://user-images.githubusercontent.com/19907658/31398365-01a72598-ade9-11e7-8bcf-71b07974170d.png)
