### ISSUE TITLE
Axes of chart does not accomodate present values

### ISSUE THREAD

**Issue by MichielDenHaan** [quintel/etmodel#2506]
![screen shot 2017-10-11 at 13 59 12](https://user-images.githubusercontent.com/32056448/31439515-b156228e-ae8c-11e7-806c-da8923ff675a.png)

This happens locally for my machine...

**Comment by MichielDenHaan** [comment]
This is caused by the fact that there is -0.2 PJ other heat in the Groningen/Ten Boer industry (for some reason I haven't figured out yet)
![screen shot 2017-10-17 at 10 03 07](https://user-images.githubusercontent.com/32056448/31653431-e01d5a98-b322-11e7-88be-c2681be6811c.png)

**Comment by ChaelKruip** [comment]
> This is caused by the fact that there is -0.2 PJ other heat in the Groningen/Ten Boer industry.

Hm, negative energy is the worst!

**Comment by MichielDenHaan** [comment]
This wasn't just a Groningen/Ten Boer issue. The chart query didn't take into account all industry sectors, which could result in a negative number (see below for an 'extreme' national scenario in which heat is also negative). This is fixed by this commit: https://github.com/quintel/etsource/commit/44c75b665f145c748dba4e9ccd9e5eb892a1e969.
![negativeheat](https://user-images.githubusercontent.com/32056448/31710272-c86a07d4-b3f4-11e7-814c-685598248919.png)

**Comment by ChaelKruip** [comment]
Congratulations on closing your first issue @MichielDenHaan! 🎉
