### ISSUE TITLE
Should seasonal storage be incorporated in the ETM?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2507]
Storing energy for long periods (weeks to months) is becoming a hot topic in the debate. I think we should start thinking about incorporating it in the ETM.

Some fundamental questions:
* Which carriers can be used to store energy long term? Which conversions are needed?
* Which technologies can be used?
* Where are these technologies located? At the end-user, in the distribution network, at the production site?

I'm curious about your ideas and insights!

**Comment by AlexanderWirtz** [comment]
Seasonal storage should be included where it makes sense in my opinion.
Here are my 2cts:

- Seasonal storage of hydrogen is in scope of the Gasunie hydrogen project in 2018
- Seasonal storage of natural (or green) gas should be fairly easy if we can pull off hydrogen
- Seasonal storage of heat is feasible and should be included at some point. I hear lots of talk about a project in Denmark where solar heat (in large scale facilites) is produced and stored, to be used in fall and winter. 
- Seasonal storage of electricity is not feasible and a waste of resources

The first three cases may provide some insight into the other questions:

**Gas storage**
Storing gases like hydrogen or natural gas is technically quite easy and just requires some underground cavity. Al that is needed is a connection to a high-pressure network and some pumps. In the province of Groningen, Gasunie is doing some first experiments with hydrogen storage (converted from solar PV electrolysis). I do not know how the graph / ETM would handle it, though. The easiest implementation would be to always store/buffer hydrogen made from excess electricity, but in the hydrogen project I would like to treat hydrogen like a proper carrier. This means users should get to decide how they want to make their hydrogen and much they want to store.

**Heat storage**  
Heat storage is another matter: it requires special heat storage units that are not necessarily connected to every heat source. Just like the case in Denmark, the storage would have to be built for a specific amount/source of heat. This is harder to implement in the ETM (both front end and back end. 

The Danish case would necessitate adding 'solar heat parks' with their own storage. These can then supply the central heat network. 

Storing heat from other (smaller) sources is also possible: thermal storage in combination with heat pumps is actually a form of seasonal heat storage. This has been implemented in a rough way at present (a very high COP, but no actual storage). I wonder if in this case the temperature of the heat storage needs to be monitored or if it can be done in a similar way to the way buffers are modelled now.

**Comment by ChaelKruip** [comment]
> This means users should get to decide how they want to make their hydrogen and much they want to store.

I think it would weird to ask the user *how much* (volume) they want to store. The net storage should be zero over the year (roughly). The capacity (kW) of storage is more useful IMO but perhaps that is what you meant @AlexanderWirtz?

In that case, the logic could be that you store all hydrogen that you don't use instantaneously and store the remainder (if your capacity allows). If you produce more that you can use or store in an hour, the excess is exported. If your buffer has left-over hydrogen at the end of the year you also export that. Makes sense?

> I wonder if in this case the temperature of the heat storage needs to be monitored or if it can be done in a similar way to the way buffers are modelled now.

I am afraid that we would have to start modelling temperature because it depends on the type and volume of the storage medium how a certain amount of deposited energy translates to temperature which is the quantity that the COP reacts to.

**Comment by michieldenhaan** [comment]
At a workshop I attended yesterday there was a lot of discussion about 'ecovat', for example combined with large scale solar thermal (https://www.ecovat.eu/).

**Comment by marliekeverweij** [comment]
Whoop whoop!

![Screen Shot 2020-01-02 at 10 29 07](https://user-images.githubusercontent.com/32833996/71660264-ba9e7c80-2d4a-11ea-9ead-39dfd49f5e78.png)
