### ISSUE TITLE
Minor improvement: showing key of the slider on hover

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2510]
I was helping out @nairnamratha and found out that people need to know what the key of a slider is. Ofcourse this information is only useful to Quintellers (maybe not? - correct me if I'm wrong) but I thought - since it's such a minor change - that it would be easy to show the key when you hover (for some time) on a slider:

**Like:**

![img](http://g.recordit.co/Fu8eohy9iC.gif)

Now people open up a developer console to check what the key is 😨 which looks a bit shabby.

Considering it such a minor thing I commited here (on a separate branch): https://github.com/quintel/etmodel/commit/11f0023e6dea5968cd5dda4e028dd67117e8c67f

Including @ChaelKruip @jorisberkhout @antw

**Comment by ChaelKruip** [comment]
I am not in favour of this as the unknowing user might just hover over a slider and see some cryptic information that means nothing to them...

**Comment by grdw** [comment]
> I am not in favour of this as the unknowing user might just hover over a slider and see some cryptic information that means nothing to them...

Yes, that was what I was thinking 👍. Maybe we could only enable it in development environments?

**Comment by ChaelKruip** [comment]
> Maybe we could only enable it in development environments?

Yes. That's an idea. The way I use this is by copying the key from the console to look up the input in my text-editor. Having a mouse-over bubble doesn't give you convenient copy-paste capabilities though. If this is a development environment thing anyways, would it be more useful to make it a clickable link that opens the input in ETEngine where you can view it?

**Comment by grdw** [comment]
> would it be more useful to make it a clickable link that opens the input in ETEngine where you can view it?

Hmmm 🤔 I would then rather put it in the information box:

![screen shot 2017-10-16 at 15 17 03](https://user-images.githubusercontent.com/2676542/31613994-1ad83610-b285-11e7-8ccf-b07f0fec7ed3.png)

And make that link only 'viewable' when:

a) A person is signed in
b) is an admin of ETModel

**Comment by antw** [comment]
1. Sign in to your ETModel (admin) account.
2. Go back to your scenario.
3. Open the JS console, then move the slider.
4. The slider key and value will be shown.

**Comment by grdw** [comment]
> Sign in to your ETModel (admin) account.
> [..]
> Open the JS console, then move the slider.

This is something I tried but it didn't work at @nairnamratha laptop.... let me see. Ah! so you need to actually be signed in for this to work 😄 . I still don't really like the idea of opening a JS console for this... but I'll close this for now. If I come up with something smarter then I'll open another issue. Thanks!
