### ISSUE TITLE
Add wacc and lifetime to datadummp

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2511]
Our client who is using the datadump would like wacc and technical lifetime to be added to the datadump.
@antw is that possible?

Notifying @ChaelKruip and @jorisberkhout

**Comment by antw** [comment]
> [...] would like wacc and technical lifetime to be added to the datadump.

Which datadump CSV? A new one?

**Comment by ChaelKruip** [comment]
> Which datadump CSV? A new one?

Electricity and heat production (and cost)
