### ISSUE TITLE
Add flexibility technologies to datadump

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2512]
Currently `households_flexibility_p2p_electricity` is not shown in the datadump whilst `households_flexibility_p2h_electricity` is shown in the datadump.

Relevant technologies (as far as I have found them)
- `industry_flexibility_p2g_electricity`
- `households_flexibility_p2p_electricity`
- `energy_flexibility_p2g_electricity`

@jorisberkhout , what would be a good approach to add the flexibility technologies to the datadump?
- Add the group `flexibility` to the datadump. 
- Add the relevant nodes to a group which is currently already represented in the datadump

**Comment by jorisberkhout** [comment]
They need to be added to the `application_group` group. I must have missed them when creating that group.

**Comment by DorinevanderVlies** [comment]
Thanks! I'll add those nodes

**Comment by DorinevanderVlies** [comment]
All nodes which belong to the `electricity_production`, `heat_production` and `cost_other` are part of the "production_parameters"-export.

For further reference the relevant lines:
[https://github.com/quintel/etengine/blob/master/app/controllers/api/v3/scenarios_controller.rb#L198-208](https://github.com/quintel/etengine/blob/master/app/controllers/api/v3/scenarios_controller.rb#L198-208)
[https://github.com/quintel/etengine/blob/master/app/controllers/api/v3/scenarios_controller.rb#L198-L208](https://github.com/quintel/etengine/blob/master/app/controllers/api/v3/scenarios_controller.rb#L198-L208)
