### ISSUE TITLE
Add link to HP demand response slide from space heating technologies slide

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2525]
It would be cool if the text above the different space heating technologies shows a link to the Demand response - Heat pumps slide to draw some more attention to that new cool feature.

<img width="448" alt="screen shot 2017-11-01 at 11 47 33" src="https://user-images.githubusercontent.com/4669028/32271521-8f4f8184-befa-11e7-9ec3-22a9c302f908.png">

**Comment by DorinevanderVlies** [comment]
Great idea, I'll implement this

**Comment by DorinevanderVlies** [comment]
![image](https://user-images.githubusercontent.com/19907658/32507550-081c6fea-c3e8-11e7-9119-16322e2fe161.png)
