### ISSUE TITLE
Add link to HP demand response slide from hot water technologies slide

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2526]
It would be cool if the text above the different hot water technologies shows a link to the Demand response - Heat pumps slide to draw some more attention to that new cool feature.

<img width="450" alt="screen shot 2017-11-01 at 11 47 46" src="https://user-images.githubusercontent.com/4669028/32271546-b77877ba-befa-11e7-9d57-61bee1f2ca92.png">

**Comment by DorinevanderVlies** [comment]
![image](https://user-images.githubusercontent.com/19907658/32507582-1b5831f2-c3e8-11e7-87cf-9b0884c7ed50.png)
