### ISSUE TITLE
Should we add heat delivered by P2H in industry to the respective final demand charts?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2527]
I've created a scenario with a lot of excess electricity and converted most of it to heat in industry, but haven't done anything about the industrial sectors themselves. This leads to the changes in the final demand of the sector shown below. Although the calculation is entirely correct, the chart feels counterintuitive. So the question is if we should show the electricity used for P2H like we do for P2G in the fertilizers industry. The only problem with doing this is that this electricity is not considered final demand (I guess).

How do you feel about this, @AlexanderWirtz , @ChaelKruip , @DorinevanderVlies and @MichielDenHaan ?

<img width="609" alt="screen shot 2017-11-01 at 11 51 32" src="https://user-images.githubusercontent.com/4669028/32271724-8332af42-befb-11e7-8a24-027121f08757.png">

**Comment by DorinevanderVlies** [comment]
> The only problem with doing this is that this electricity is not considered final demand (I guess).

That is indeed why we did not add the electricity used for P2H to this chart.

Although it can also be argued that the electricity does reach the industries and is used there, so in some way it can be considered as final demand.

**Comment by AlexanderWirtz** [comment]
If the electricity is used to create heat, how is that not final demand? Or is this heat fed into a heat network? The chart seems to show both a decrease in gas use (which would imply final demand) and in heat use (which is itself final demand, but the electricity used to produce it is not. 

My point is that electric heaters in homes are final demand, so why is this not the case in industry. Sorry, I know I am not up to speed with how this works in the industry sector, so maybe this is a really stupid question.

**Comment by DorinevanderVlies** [comment]
> My point is that electric heaters in homes are final demand, so why is this not the case in industry. Sorry, I know I am not up to speed with how this works in the industry sector, so maybe this is a really stupid question.

A similar issue runs for electric heaters in households that are powered with excess electricity options: https://github.com/quintel/etmodel/issues/2528. They are currently not counted as final demand. Is that correct @ChaelKruip ?

I remember @ChaelKruip and me had a discussion about this chart and that we decided that energy used by P2H technologies should not be shown in this chart as it is not final demand. @ChaelKruip do you remember why we decided this is not final demand?

**Comment by ChaelKruip** [comment]
> @ChaelKruip do you remember why we decided this is not final demand?

I think there were several reasons (some of which already mentioned above):
- We don't show electricity for P2H in households (but we could I suppose)
- I don't know if the heat for Industry will be made 'inside the sector' so if we should count the heat or the electricity used to create the heat as final demand
- Technically, it is a bit tricky because the P2H nodes have no electricity demand (that is all taken care of inside Merit):
![energytransitionmodel](https://user-images.githubusercontent.com/1303760/33216266-6eaf6dd6-d133-11e7-8b92-e5e226ec459b.png).
@antw is it difficult/desirable to add the input carrier and demand for P2H, P2P and P2G nodes?

**Comment by michieldenhaan** [comment]
This issue was brought up by one of our clients. My gut feeling would be to show the electricity as final demand. We should do this as well then for P2H in households, P2P etc. Notifying @AlexanderWirtz, @ChaelKruip, @marliekeverweij. 

>is it difficult/desirable to add the input carrier and demand for P2H, P2P and P2G nodes?

I think this has been fixed already, all flexibility options are now connected to the ``energy_production_excess_electricity`` node. So it should be relatively straightforward to include use of excess electricity in the industry demand charts.

**Comment by marliekeverweij** [comment]
I think it's a good idea to show the excess electricity used for P2H as final demand. However, I think we should then be consistent in all final demand charts, so for example also show electricity used for P2H in the final demand mekko. As the final demand mekko shows all energy in the final-demand-nodes it will be kind of ugly to separately add P2H-electricity.

**Comment by ChaelKruip** [comment]
> My gut feeling would be to show the electricity as final demand. We should do this as well then for P2H in households, P2P etc. Notifying @AlexanderWirtz, @ChaelKruip, @marliekeverweij.

Do we count hydrogen produced by dedicated offshore wind to be primary? I would suggest to be consistent with the choice made there... So, if we do, count the heat as primary carrier (and also final carrier).

**Comment by michieldenhaan** [comment]
No electricity is primary for dedicated wind/solar PV

**Comment by ChaelKruip** [comment]
> No electricity is primary for dedicated wind/solar PV 

I think we should count the electricity as final then. @AlexanderWirtz probably has a more authoritative opinion on this though...

**Comment by AlexanderWirtz** [comment]
> I think we should count the electricity as final then. @AlexanderWirtz probably has a more authoritative opinion on this though...

I am not sure it is more authoritative. I am just too stupid to see how this is not plain old final demand. Of course, the heat might be generated by the energy sector (some kind of joint venture who owns the heater for P2H) and brought to industrial clients, but it seems more likely that plants invest in electric heaters. In that case, it is final demand in my book.

**Comment by marliekeverweij** [comment]
Closing this as we have a new one :0 https://github.com/quintel/etsource/issues/2494
