### ISSUE TITLE
Can't find 'annual infrastructure costs' chart 

### ISSUE THREAD

**Issue by nairnamratha** [quintel/etmodel#2530]
The chart info for _Required additional infrastructure investments_ (found in section Infrastructure Costs) says that there is a possibility to switch to another chart which displays annual infrastructure costs.
![screen shot 2017-11-01 at 16 40 53](https://user-images.githubusercontent.com/32448293/32283109-c704e19a-bf23-11e7-800e-387c69eed348.png)

The missing chart is supposed to show the change in magnitude of the infrastructure costs.  

I am not sure whether the missing chart is supposed to represent what the current chart is already showing or whether it's something different but missing from the current list of charts.

**Comment by jorisberkhout** [comment]
@nairnamratha , could you please assign someone to look into an issue? You can do that on the top right of the issue page.

Regarding the issue itself, the chart you're looking for is only available for The Netherlands and not for other countries as we do not support a network calculation for these countries. The chart is called `Required additional infrastructure investments` and can be found under the `Costs` section of the chart selector.

I agree that the chart info is misleading. I'll leave this issue open and will assign it to you to pick up when we start working on the improvement of the network calculation.

**Comment by nairnamratha** [comment]
Noted! @jorisberkhout 

Thanks!

**Comment by MartLubben** [comment]
ok removed. As you wished @jorisberkhout
