### ISSUE TITLE
Adding slider history feature

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2532]
At a workshop on Tuesday a few participants said they missed the following features in the front end:

- see the last X changes made to a scenario

- quickly save/bookmark a certain 'stage' (i.e. all changes up to a certain point) to which the user can easily go back.

The motivation behind this was that they wanted to try out different routes for 'finetuning' a scenario and quickly go back to a stage they were happy with if things didn't work out as they wanted them to. 

I like this idea, as it provides a nice overview of all the changes the user made. Another thing I noticed was that people tend to forget in which tab they made a certain change. E.g. they change the car share to 100% electric, decide that they want to add some hydrogen cars 10 minutes later but can't remember which tab to go to. This can be solved by making the change history 'clickable', i.e. by clicking on the 100% electric change you automatically jump to the right tab.

Any thoughts @ChaelKruip @AlexanderWirtz @DorinevanderVlies @antw @grdw ?

**Comment by ChaelKruip** [comment]
> Any thoughts @ChaelKruip @AlexanderWirtz @DorinevanderVlies @antw @grdw ?

I like it a lot! We would have to come up with a nice way to visualise the history-of-clicks though and think of a place in the ETM where to put this...
