### ISSUE TITLE
Zeeland and Baarland and the dataset selector

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2541]
<img width="228" alt="screen shot 2017-11-15 at 15 04 42" src="https://user-images.githubusercontent.com/2676542/32839922-54d81dc8-ca16-11e7-9472-9b758eb2f6d8.png">

See above screenshot. "Zeeland" and "Baarland" are both datasets which are used for 'demo'-ing and aren't up-to-par with Quintel standard so to speak. Should we move them to another sector or specify behind the title that it regards a 'demo' dataset?

**Comment by AlexanderWirtz** [comment]
@grdw It looks like we really need a solution to sort datasets better than the one we have now. @jorisberkhout and @ChaelKruip do you agree?

**Comment by grdw** [comment]
> [..] to sort datasets better

It was brought to my attention again last sprint meeting of ETLocal. I however don't see it as 'that terrible', yet. It's not nice, but it's not horrible. I'll draw up some ideas though and post them on basecamp to see what sticks and what doesn't.

**Comment by grdw** [comment]
Closing this as it's discussed on Basecamp and solved as a searchable select box.
