### ISSUE TITLE
Add kerosene demand to transport chart similar to hydrogen demand for cars

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2552]
Due to the recent changes, the transport chart shows only the remaining kerosene demand after P2L. In line with the hydrogen demand for cars, I would like it to show the full kerosene demand and add a separate chart to show how this kerosene is produced.

**Comment by marliekeverweij** [comment]
Do you mean this chart? :
![screen shot 2017-11-21 at 13 34 58](https://user-images.githubusercontent.com/32833996/33072692-cf0c4584-cec0-11e7-857c-2ea756bb10a7.png)

We have deleted this chart when we were adding public transport. But I think the problem will also occur with the new transport charts we have added. So I will leave this issue open!

**Comment by jorisberkhout** [comment]
Thanks for the clarification @marliekeverweij . I just wanted to make sure that the production of synthetic kerosene reduces the kerosene demand, as it was doing in the now deleted transport chart. I think you are correctly implementing this in the new international transportation chart, so will close this issue.
