### ISSUE TITLE
Add chart to show how kerosene is produced

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2553]
Something similar to the hydrogen production chart would be great

<img width="613" alt="screen shot 2017-11-17 at 11 33 27" src="https://user-images.githubusercontent.com/4669028/32943033-276c5f72-cb8b-11e7-9c03-8ec18625be5b.png">

**Comment by marliekeverweij** [comment]
So I have now created this chart:
![screen shot 2017-11-21 at 10 21 01](https://user-images.githubusercontent.com/32833996/33064407-d97e24e4-cea5-11e7-876e-47f9bd444fa3.png)
This shows what is happening in the distribution nodes of kerosene and bio-kerosene.

But this was not what your intention was with this graph! Shall I also make one (or replace this one) with the final demands of biokerosene, fossil kerosene and synthetic kerosene? And then without the import/export?

**Comment by marliekeverweij** [comment]
I have created the two extra gqueries (for bio-kerosene and fossil kerosene) that are necessary for the new chart on the 'chart209'- branch. I am a bit hesitant to merge it with beta, since it would probably mess up with the charts of public transport. So I thought I could better add these gqueries when public transport is merged!

**Comment by marliekeverweij** [comment]
I have a question for @jorisberkhout :

When more synthetic kerosene is produced than the kerosene demand, that the excess of synthetic kerosene is exported. Shall I show this in the chart? That I distinguish between synthetic kerosene that is used nationally and synthetic kerosene that is exported?

**Comment by marliekeverweij** [comment]
Okay, Joris and I discussed to replace the previous chart with a new chart #200 showing the shares of bio-kerosene, fossil kerosene and synthetic kerosene!
