### ISSUE TITLE
Should we revise/update 'Employment' in preparation of Energieakkoord 2.0? 

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2555]
According to @MichielDenHaan the difference between the 'Nationale Energie Verkenning' (NEV) and the ETM is huge. The ETM calculates 50.000 jobs while the NEV calculated 150.000 for a comparable scenario. 

Next to this it would be very interesting in the class of jobs could be show, like higher educated jobs, middle, and low. 

@AlexanderWirtz is this valuable enough to invest time in?

**Comment by ChaelKruip** [comment]
> The ETM calculates 50.000 jobs while the NEV calculated 150.000 for a comparable scenario.

Only a factor three! 😆 

What did you use for 'economic multiplier'? (That is a setting for the secondary, tertiary etc. effect of job creation.) And what does PBL do?

On a related note: I am not sure how useful the employment module of the ETM is as it is very limited in scope (no industrial jobs etc.). I would be open to removing it entirely.

**Comment by AlexanderWirtz** [comment]
I am kind of in favor of removing it. The only one who likes it is John. We could ask his arguments against removing it. It feels not quantitative enough to me.

**Comment by MichielDenHaan** [comment]
Creating 15.000 additional jobs is often named as one of the four 'cornerstones' of the SER Energieakkoord (alongside % renewability and 2 energy saving goals). So if we want to get involved in the new Energieakkoord, it might be a nice feature to have. On the other hand, if the calculation diverges a lot from other estimates like the NEV it can also be seen as a weakness (and cast doubts on other results).

**Comment by marliekeverweij** [comment]
As we want to get rid of the employment module in the ETM, I've have just hidden the employment sidebar item, slide and chart on PRO and BETA. This is not a structural solution! Because I didn't remove any of the calculations. But it is one step in the right direction :)

**Comment by ChaelKruip** [comment]
>  On the other hand, if the calculation diverges a lot from other estimates like the NEV it can also be seen as a weakness (and cast doubts on other results).

This is likely and also my main concern

**Comment by AlexanderWirtz** [comment]
>>On the other hand, if the calculation diverges a lot from other estimates like the NEV it can also be seen as a weakness (and cast doubts on other results).

Let's be clear: these calculations are nonsense. I lost a discussion with John whether or not it would make sense to include them. I would like them gone. :-)

**Comment by michieldenhaan** [comment]
Closing, we no longer support this
