### ISSUE TITLE
Add CO2-allocation sliders to synthetic kerosene

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2556]
From the meeting yesterday with all clients involved in the synthetic kerosene project the idea arose to create sliders to allocate the CO2-profits to either the industry or the aviation. Ewald Breunesse from Shell proposed to make the default setting 50/50. I propose to put the sliders underneath the carbon sources for synthetic kerosene. What do you think, @jorisberkhout ?

![screen shot 2017-11-21 at 11 13 27](https://user-images.githubusercontent.com/32833996/33066956-09aa24cc-cead-11e7-8ba9-f80843150b3b.png)

**Comment by jorisberkhout** [comment]
> What do you think, @jorisberkhout ?

I agree that this is best place for now. Let's see how to deal with these type of sliders when we add more!

**Comment by marliekeverweij** [comment]
The sliders are implemented and they work!!
