### ISSUE TITLE
Add costs-sliders for PtL (and also PtG and PtH?)

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2557]
From the meeting from yesterday the idea arose to make a cost-slider for PtL. Shall we put it here: 

![screen shot 2017-11-21 at 11 26 33](https://user-images.githubusercontent.com/32833996/33067670-281faa2e-ceaf-11e7-9d0a-7f6febf06c49.png)
 
We can make a separate slide with the name 'Synthetic fuel' and also place hydrogen there. (And when were are going to add methanol it can also be placed here)

**Comment by jorisberkhout** [comment]
I would prefer to create a new sidebar item under the `Costs` tab called `Flexibility`. This sidebar item could then contain a slide for synthetic kerosene production, where the cost slider for PtL can be placed (BTW this slider should influence the _investment_ costs of the Ptl plant, the costs of the kerosene produced will also (and mainly) depend on the costs of the electricity needed to produce the synthetic kerosene).

Once there exists a separate sidebar item for the costs of flexibility options, this would be a nice place to add costs sliders for other flexibility options (see also https://github.com/quintel/etmodel/issues/2237).

**Comment by marliekeverweij** [comment]
Done!

![screen shot 2017-11-24 at 11 45 43](https://user-images.githubusercontent.com/32833996/33207199-16f375ae-d10d-11e7-807b-5ba543d628e7.png)
