### ISSUE TITLE
Same label for output_element_serie but shows up two times in legend of chart

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2558]
For the CO2 emissions chart (#46) I have added the CO2 emissions of bunkers in 1990 and also for the present and future. These are the series of this chart: 

![screen shot 2017-11-21 at 13 52 20](https://user-images.githubusercontent.com/32833996/33073578-9ed290a0-cec3-11e7-924c-805376f11552.png)

I have given the CO2 emissions of bunkers in 1990 and also for the present/future the same label `groups.bunkers`, because I wanted to show 'international transport' only once in the legend. However, it shows up 2x:

![screen shot 2017-11-21 at 13 50 15](https://user-images.githubusercontent.com/32833996/33073644-d24fadbe-cec3-11e7-90b5-159a28bd07e4.png)

Is it possible to show it only 1x?

**Comment by ChaelKruip** [comment]
> Is it possible to show it only 1x?

You mean the duplication of "International transport" in the legend?

I think this is the result of you adding it for both 1990 and for the future. Alternatively, you could add the 1990 value directly to the total (grey) bar. This would be consistent with how we show the other sectors now.

**Comment by marliekeverweij** [comment]
> You mean the duplication of "International transport" in the legend?

Yes

> Alternatively, you could add the 1990 value directly to the total (grey) bar. This would be consistent with how we show the other sectors now.

Yes that would be consistent. However, I think it is better to keep international transport apart from the rest of the emissions of 1990, since it is never included in the statistics. What do you think, @jorisberkhout ? 

I can also change it back to how it was with a separate legend 'CO2 emissions international transport 1990': 

![screen shot 2017-11-21 at 16 28 22](https://user-images.githubusercontent.com/32833996/33080732-15fdd878-ced9-11e7-9fb4-e80e37828eb5.png)

**Comment by marliekeverweij** [comment]
I have discussed with Chael that I am going to give the CO2 emissions international transport 1990 another colour to make the distinction.
