### ISSUE TITLE
Change legends of all charts

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2562]
As discussed during the last public-transport-pressure-cooker-meeting the order of the legend items should change for all charts. Now it is like this:
![screen shot 2017-11-22 at 17 30 30](https://user-images.githubusercontent.com/32833996/33139449-98bcee1e-cfad-11e7-8846-fafc635b658f.png)
There are two things that need to be changed:

1.  Now the legend items are ordered from left to right, which makes it not clear for the user. It would be better if they would be ordered from top to bottom. 

2. Also it would be more intuitive to place the lowest item in the chart (the output_element_serie with position 1) also as the lowest item in the legend. 

Would it be possible to make these changes, @antw and @grdw ?

**Comment by grdw** [comment]
<img width="580" alt="screen shot 2017-11-23 at 08 29 59" src="https://user-images.githubusercontent.com/2676542/33162211-8dc57b9a-d028-11e7-88d6-19d8a1130106.png">

This is it reversed, L &rarr; R. 

Moving the direction from top to bottom does require some more changes. Give me a moment though.

**Comment by grdw** [comment]
<img width="624" alt="screen shot 2017-11-23 at 09 49 09" src="https://user-images.githubusercontent.com/2676542/33165593-b057b376-d037-11e7-8c53-6fa9f23f39f3.png">

This is it from Up &rarr; Down (reversed).

**Comment by marliekeverweij** [comment]
Nice! I like it.
