### ISSUE TITLE
Hide the sub-sidebar items when user is not in transport section

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2563]
Now that public transport is also merged into beta, there are three sub-sidebar items in the sidebar shown when 'Demand' is opened. It would be really nice to hide the sub-sidebar-items when transport is not used! 

@antw & @grdw , could you help us out?

**Comment by grdw** [comment]
How can you tell if transport is not used?

**Comment by marliekeverweij** [comment]
> How can you tell if transport is not used?

Okay, sorry that was a bad explanation. I mean that the sub-sidebaritems should hide when the user is not in the transport-section. For example now the three sub-sidebaritems should hide, when the user is in the households-section:

![screen shot 2017-11-23 at 09 18 42](https://user-images.githubusercontent.com/32833996/33163565-6cb4839a-d02f-11e7-85a2-f1c0be208e60.png)

**Comment by marliekeverweij** [comment]
How is it actually going with this issue? I am looking forward to the moment when this works :smile:
