### ISSUE TITLE
NL-translations of transport are in English

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2568]
Some transport-translations in "nl" are in English

- Sidebar
- Slides
- Sliders
- Legends

![image](https://user-images.githubusercontent.com/19907658/33185120-c6ae7cce-d080-11e7-8e70-496763bbf5f6.png)

notifying @AlexanderWirtz because he noticed this as well

**Comment by marliekeverweij** [comment]
Yes I have only included the english translations, I will work on that today!

**Comment by marliekeverweij** [comment]
Mart is going to fix this issue!

**Comment by marliekeverweij** [comment]
@MartLubben, also the names of the charts need to be translated in Dutch

**Comment by marliekeverweij** [comment]
All translations are included :)
