### ISSUE TITLE
Clicking on international transport sidebar item should not redirect to households

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2574]
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://user-images.githubusercontent.com/1303760/33216571-a559265a-d134-11e7-95fa-dc6f8d1c7030.png)

As seen on BETA

**Comment by marliekeverweij** [comment]
This is fixed right? At least it hasn't happened to me.
