### ISSUE TITLE
Technology shares of motorcycles of migrated scenario's do not add to 100%

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2577]
For example for scenario 593967:

![image](https://user-images.githubusercontent.com/19907658/33274950-c7b4413a-d391-11e7-83b9-2e3f972c93dd.png)

Suggestion:
Make `electric motorcycles` equal to `electric cars` and `gasoline motorcycles` equal to `1-(electric cars)`

notifying @ChaelKruip

**Comment by grdw** [comment]
I think something went wrong in the migration. I'll take a look! 👍
