### ISSUE TITLE
Add this icon for Costs: Flexibility 

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2586]
![flexibility](https://user-images.githubusercontent.com/33415156/33323898-2e305d60-d44e-11e7-96b9-3dc40360a239.png)

**Comment by grdw** [comment]
What do you think about this icon for Flexibility @antw  @ChaelKruip @AlexanderWirtz?

**Comment by antw** [comment]
Who created it / what's the license?

The idea seems fine, but I expect it's going to look thin and out-of-place when scaled down to fit the sidebar (18x18px max).

**Comment by grdw** [comment]
> Who created it / what's the license?

@MartLubben's very own super-special-licence, since he created it himself. 😅

**Comment by michieldenhaan** [comment]
![flexibility](https://user-images.githubusercontent.com/32056448/33365832-c48af93c-d4e9-11e7-815c-5355db0e711e.jpg)

**Comment by MartLubben** [comment]
![image](https://user-images.githubusercontent.com/33415156/33425300-9bf949a8-d5be-11e7-8d99-118ba3075914.png)

**Comment by MartLubben** [comment]
The new one is a bit thicker when scaled down. @antw Does this help? Or should I look for something else?

**Comment by MartLubben** [comment]
@antw I like it. The last one is better. Who's super-special-license is it now? :)

**Comment by MartLubben** [comment]
@antw Flexibility is also added in the costs section. It should get the same icon. At this moment Costs > Flexibility feels naked and lonely, see:

![screen shot 2017-12-01 at 13 28 40](https://user-images.githubusercontent.com/33415156/33482976-d8d42342-d69b-11e7-886d-3c22c7d001ed.png)

**Comment by MartLubben** [comment]
Hey @antw 

Could you add the flexibility icon to the costs? Also I have just finished the imported electricity. This also needs an icon. I have created a first idea. 

![screen shot 2018-02-21 at 11 33 30](https://user-images.githubusercontent.com/33415156/36475502-2aa9fd14-16fb-11e8-8ea4-91f257ecfd1b.png)

![icon imported electricity](https://user-images.githubusercontent.com/33415156/36475818-385cd9e4-16fc-11e8-9a5e-0c5819104fb4.png)

**Comment by antw** [comment]
How's this?

![screen shot 2018-02-21 at 14 01 49](https://user-images.githubusercontent.com/4383/36484025-d533d598-170f-11e8-95b4-e54c262c7d99.png)

**Comment by MartLubben** [comment]
This is also a nice snd FREE one: https://www.flaticon.com/free-icon/login-button_16036

**Comment by MartLubben** [comment]
@antw What do you think. You've got the best feeling for this ;-)

**Comment by MartLubben** [comment]
@antw I am happy. It looks great. Thanks  :)
