### ISSUE TITLE
Shall we add number of units for trucks?

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2590]
I client contacted me because he is confused that in his scenario various types of trucks are present, but number_of_units are just given for electric trucks. 

I had a look and found that for all car technologies and for electric trucks number of units are supplied in datasets and scenario's.

In fact just the number of units for electric cars are relevant because that is used for this gquery: https://github.com/quintel/etsource/blob/master/gqueries/output_elements/output_series/vertical_stacked_bar_170_investment_electric_cars/electric_cars_additional_costs.gql.

For clarity I think we should either give number of units for all transport technologies or just for the ones that are relevant. 

### Proposal:
Just define number of units for electric cars (and cars in total in order to calculate electric cars).

@ChaelKruip what do you think?
@antw is that a big change?

**Comment by antw** [comment]
> but number_of_units are just given for electric trucks

Where is this found?

I know that we specify [number of units for cars](https://github.com/quintel/etsource/blob/0d44e16fbc004d2baf22d6e9c81f1cc76034990d/nodes/transport/transport_useful_demand_cars.demand.ad#L8) and then ETEngine is able to figure out the number of units for each individual type of car by [assigning those nodes to the `inheritable_nou` group](https://github.com/quintel/etsource/blob/0d44e16fbc004d2baf22d6e9c81f1cc76034990d/nodes/transport/transport_car_using_electricity.converter.ad#L5). I don't see any harm in doing the same with trucks – or any other type of transport for which which have the necessary data.

**Comment by ChaelKruip** [comment]
> For clarity I think we should either give number of units for all transport technologies or just for the ones that are relevant.

I agree. This is probably (hastily) copied from electric vehicles and never removed by me.

**Comment by DorinevanderVlies** [comment]
As `number_of_units` is more difficult to say for trucks (trucks and vans etc) than it is for cars **and** it is not used for anything I propose to remove anything to do with `number_of_units` for trucks.

@antw I do not see inheritable_nou group for [transport_truck_using_electricity](https://github.com/quintel/etsource/blob/0d44e16fbc004d2baf22d6e9c81f1cc76034990d/nodes/transport/transport_truck_using_electricity.converter.ad). How can we remove `number_of_units` for trucks?
