### ISSUE TITLE
Fuel prices

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2593]
The fuel price sliders currently allow users to set the % change of prices. The resulting absolute prices are displayed on the left side of the slider:
![fuelprices1](https://user-images.githubusercontent.com/32056448/33607738-590bde82-d9c2-11e7-801f-4362682c285b.png)

When updating the ETM base prices, scenario's that explicitly set prices are affected (simply because a 50% increase of a 10 euro base price is not the same as a 50% increase of 12 euro base price). 

To (partly)* avoid this in the future, we could swap absolute and relative prices, i.e. let the user set an absolute price and display the % change left of the slider. In my opinion, this is also more intuitive (a 10 euro ETS price or 100 dollar oil price speaks to mind, a % change less so), though that's probably a matter of taste.

What's your opinion on this @AlexanderWirtz , @jorisberkhout , @ChaelKruip , @DorinevanderVlies , @MartLubben , @marliekeverweij, @antw  ?

/* Partly because oil and coal prices are in dollars. When we update the euro dollar exchange rate, a migration is still needed to ensure that existing scenario's are not affected.

**Comment by marliekeverweij** [comment]
I agree that absolute-price-sliders are more intuitive than the current percentage-sliders, I would go for that. 

Furthermore, doubt if it is necessary to show the percentage change in price on the left side of the slider. What is the added value?

**Comment by ChaelKruip** [comment]
Although I agree that absolute price is more intuitive for most people I can also imagine a user (me for instance) thinking: 

"I don't know exactly what oil will do in the future (or what it currently costs) but I think it will be twice as expensive in the future."

If this is the way they think about the fuel prices, it makes sense to use % sliders and refrain from migrating scenario's *even if we update prices*. 

Playing the 👿 's advocate a bit but I think we should keep in mind that most people don't think in absolute but rather relative prices...

**Comment by michieldenhaan** [comment]
True, except that the prices users set are not relative to the dataset year but relative to the moment Quintel did a price update (which makes it extra confusing). That is, if you set a 50% price increase, it is not a 50% increase compared to 2015 prices but compared to the prices as they were at the moment Quintel updated them. So it only makes sense to think that 'it will be twice as expensive in the future' if you know the origin of your base prices (which means opening ETDataset..)

**Comment by DorinevanderVlies** [comment]
> Although I agree that absolute price is more intuitive for most people I can also imagine a user (me for instance) thinking:

I agree with this. However, IMO the arguments @michieldenhaan make convince me to change to absolute values

**Comment by AlexanderWirtz** [comment]
I agree with @michieldenhaan 's proposal.

**Comment by jorisberkhout** [comment]
I like @michieldenhaan 's proposal a lot!

**Comment by jorisberkhout** [comment]
BTW, I assigned @michieldenhaan as this issue had no assignee.

**Comment by michieldenhaan** [comment]
Closing, this is implemented by https://github.com/quintel/etsource/pull/1509
