### ISSUE TITLE
Legend order of chart #188 CO2 biomass

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2594]
I find the legend order of chart #188 (co2 biomass) a little funny, it looks a bit random (see figure below). @DorinevanderVlies , am I right that you have created this chart? Maybe you know why it's like this?

![screen shot 2017-12-05 at 13 53 41](https://user-images.githubusercontent.com/32833996/33608440-cd22821a-d9c4-11e7-9cbd-a0c36eeb7192.png)

![screen shot 2017-12-05 at 13 54 02](https://user-images.githubusercontent.com/32833996/33608444-cefb4928-d9c4-11e7-895c-77f7a39c9415.png)

**Comment by ChaelKruip** [comment]
Perhaps we should hide all zero/small series *and* their legends?

**Comment by DorinevanderVlies** [comment]
I think me and @jorisberkhout crated this chart together.

It becomes more clear when there is a significant amount of biomass in a scenario **and** the CO2 for biomass sliders are set:

![image](https://user-images.githubusercontent.com/19907658/33721403-37350efe-db67-11e7-880c-ed01a6c3ec58.png)

> Perhaps we should hide all zero/small series and their legends?
Great idea, maybe @grdw can help with this

**Comment by jorisberkhout** [comment]
Please have a look at https://github.com/quintel/etmodel/issues/2596 before making any changes to this chart.
