### ISSUE TITLE
Add 1990 column to `CO2 of international transportation` chart 

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2595]
This can be easily done by adding a `is 1990` series in the admin section. The result should look something like this, but nicer.

<img width="615" alt="screen shot 2017-12-05 at 16 18 53" src="https://user-images.githubusercontent.com/4669028/33614615-21855680-d9d8-11e7-973a-8571eabee4f4.png">

**Comment by marliekeverweij** [comment]
This issue is still relevant right? Then I will fix it tomorrow or the day after

**Comment by marliekeverweij** [comment]
Okay done!

![screen shot 2017-12-20 at 15 12 52](https://user-images.githubusercontent.com/32833996/34211077-48ab34fc-e598-11e7-8c20-b356b1f70cad.png)
