### ISSUE TITLE
Sustainability_share of industry_flexibility_p2g_electricity

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2597]
At the moment I am modelling a new hydrogen plant for the production of power-to-kerosene. I am using most attribute-values from the node `industry_flexibility_p2g_electricity` for this new node. In `industry_flexibility_p2g_electricity` I see a sustainability_share of 0.0. This surprises me since this hydrogen is produced from excess electricity. Hydrogen for transport which is produced in `energy_flexibility_p2g_electricity` does have a sustainability_share of 1.0. 

Shall I also take a sustainability_share of 1.0 for `bunkers_flexibility_p2g_electricity` and change the sustainability_share of `industry_flexibility_p2g_electricity` to 1.0?

Since I have read the following previous discussions (https://github.com/quintel/etmodel/issues/2403 , https://github.com/quintel/etsource/pull/1278 , https://github.com/quintel/etmodel/issues/2269 ), I will include @DorinevanderVlies and @ChaelKruip in this issue.

**Comment by ChaelKruip** [comment]
> Shall I also take a sustainability_share of 1.0 for bunkers_flexibility_p2g_electricity and change the sustainability_share of industry_flexibility_p2g_electricity to 1.0?

I think so yes. @DorinevanderVlies do you agree?

**Comment by DorinevanderVlies** [comment]
Yes I agree!

**Comment by marliekeverweij** [comment]
Okay we will do that, thanks for answering so quickly :)
