### ISSUE TITLE
Exces of imported electricity in yearly view and not in weekly view

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2600]
In [this scenario ](https://beta-pro.energytransitionmodel.com/scenarios/772630) the whole year of electricity production differs from a weekly view. The yearly view shows excess of imported electricity. This exces is also shown in the primary energy use chart.

@antw do you know why there is a difference between the weekly and the yearly view?
Is it correct that imported electricity is exported? This seems contradictory to me.

notifying @michieldenhaan 

### Screenshots
![image](https://user-images.githubusercontent.com/19907658/33996035-294ecb12-e0e0-11e7-9bdc-e6e080bbd5c6.png)

![image](https://user-images.githubusercontent.com/19907658/33996046-391fcd48-e0e0-11e7-855d-9701434cc8bc.png)

![image](https://user-images.githubusercontent.com/19907658/33999742-9abee1dc-e0eb-11e7-849d-dc6415af1cac.png)

**Comment by antw** [comment]
The weekly view is accurate. The annual view downsamples the hourly data to show the average energy produced by each producer throughout the day and then stacks them on top of one another. This creates the (misleading) impression that electricity is being imported during periods when demand is being met.

**Comment by DorinevanderVlies** [comment]
Thanks @antw!
Can you also explain why the primary energy use chart shows an export of imported electricity?

**Comment by ChaelKruip** [comment]
> Can you also explain why the primary energy use chart shows an export of imported electricity?

I think that at moments of excess electricity, the year-averaged electricity mix is exported. This may include imported electricity. Import and export do not coincide.

Closing. Re-open if this doesn't answer your question.

**Comment by antw** [comment]
> I think that at moments of excess electricity, the year-averaged electricity mix is exported.

Exactly right. This wasn't a problem in the past since ETEngine would never calculate that there would be import *and* export present in the same scenario. As import is now handled by Merit, it is possible to have both.

Since Merit only permits importing to meet demand (it never imports more than is needed), there might be a case for hardcoding the value in this query to always return zero.

```
- query = 0.0
```

**Comment by ChaelKruip** [comment]
> As import is now handled by Merit, it is possible to have both.

But not in the same hour right? 

> Since Merit only permits importing to meet demand (it never imports more than is needed), there might be a case for hardcoding the value in this query to always return zero.

I don't understand this @antw...  The current behaviour is expected right? Namely:
* If there is excess (which is not converted and stored), electricity is exported (with the current national mix)
* If there is not enough production capacity, electricity is imported with the current national mix
* Over the year, these two effects don't have to cancel out so they can show up in the chart

**Comment by antw** [comment]
> But not in the same hour right?

Correct.

> The current behaviour is expected right?

Yes, ETEngine is behaving correctly in that it only deals with the *total* supply and demand for electricity during the entire year; it doesn't know about the complexities of Merit. For example, in this simplified graph ...

![1 graph](https://user-images.githubusercontent.com/4383/34258188-c39f4902-e654-11e7-9e51-489a843b85e5.png)

... ETEngine will tell you that if import is 20% of the total energy input (100PJ) and export is 10% of the output, that 2PJ of energy which was imported is then exported:

![2 flows](https://user-images.githubusercontent.com/4383/34258191-c7b6fb7a-e654-11e7-8f17-d684d9bd784b.png)

However this is not really true when you consider what Merit is doing; it will never import electricity when there is a surplus of local production. What is *really* happening is this:

![3 corrected](https://user-images.githubusercontent.com/4383/34258193-ca520514-e654-11e7-934f-97d2a945363d.png)

I think this also shows the issue to be more complicated than I first thought. Tt's likely not good enough to hard-code the "export of import" query to be zero; we'd also have to increase the other queries to compensate.

**Comment by DorinevanderVlies** [comment]
> ... ETEngine will tell you that if import is 20% of the total energy input (100PJ) and export is 10% of the output, that 2PJ of energy which was imported is then exported:

I get that part. However, I don't really understand the following figure. Why is local production 78+8=96 PJ?

![image](https://user-images.githubusercontent.com/19907658/34481302-af1429ec-efb1-11e7-8268-f469d718b18f.png)

> I think that at moments of excess electricity, the year-averaged electricity mix is exported.
Would it be possible it import the year-averaged electricity mix excluding export?

**Comment by ChaelKruip** [comment]
> I get that part. However, I don't really understand the following figure. Why is local production 78+8=96 PJ?

I think @antw meant to write "72 PJ" instead of "78 PJ" for the amount of local production that goes to local consumption.
