### ISSUE TITLE
Should Power-to-Kerosene work for non NL scenario's?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2609]
For Belgium (with lost of wind and P2K) for instance, the charts show no production:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://user-images.githubusercontent.com/1303760/34208881-58aeddfc-e590-11e7-9710-240e8098dae4.png)

**Comment by marliekeverweij** [comment]
Yes it should and it does my belgium scenario:

![screen shot 2017-12-20 at 14 22 24](https://user-images.githubusercontent.com/32833996/34209128-3e06e94e-e591-11e7-9f36-eb93d5b075aa.png)

I see you have not built any power-to-kerosene units, maybe that is the problem?

**Comment by ChaelKruip** [comment]
> I see you have not built any power-to-kerosene units, maybe that is the problem?

😊  Closing.
