### ISSUE TITLE
Ordering charts

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2612]
I sometimes have a hard time finding the right chart. They are now ordered in certain categories (Overview, Supply, Demand etc.). Are they furthermore ordered within the categories? Would it be an idea to also order them alphabetically within the categories? Or are there better ideas? 

![screen shot 2017-12-20 at 14 26 32](https://user-images.githubusercontent.com/32833996/34209308-e3c4511e-e591-11e7-992f-79703d146d98.png)

(I just assigned a few people to give there opinion and @grdw)

**Comment by michieldenhaan** [comment]
Sorting them alphabetically is a good idea. Maybe we can also change the category order (overview, then demand, then supply, then merit). And a search function would be nice.
How do you people feel about removing the preview pictures and replace the 3 column interface by a simple, compact list?

**Comment by nairnamratha** [comment]
Also like the sorting alphabetically idea and changing the 3 column interface. But the preview thumbnails should stay in my opinion ( since they show the type of chart, without adding any extra text to the title).

**Comment by AlexanderWirtz** [comment]
I use the 'Add a chart' fucntionality a lot in workshops. I disagree with the order @michieldenhaan suggests. 

In practice we mostly end up using the Overview, Merit order and Flexibility and Costs charts in workshops. Sometimes Supply and basically never anything from Demand. One reason for this is that is is virtually impossible to find the right demand chart visually (same/similar thumbnail and long winding titles), but also because most of them aren't all that interesting.

I like sorting alphabetically within category, but this shouldn't lead to different orders when using English or Dutch. I thinks this is currently the case and always means I look for charts longer than necessary as I expect them to be at a certain place in the list.

**Comment by grdw** [comment]
> Are they furthermore ordered within the categories? 

I guess, no.

> Would it be an idea to also order them alphabetically within the categories? 

I think that would be nice. It would cause the charts to sort the same for beta and production (I think those two are now, not ordered in the same fashion, at least for the demand category they aren't). 

I do know that there's already a `sub_group` column to split the groups into sub groups - which I implemented some time ago:

<img width="931" alt="screen shot 2017-12-20 at 16 11 55" src="https://user-images.githubusercontent.com/2676542/34213788-8c0c9742-e5a0-11e7-8e71-6705941abbdf.png">

It still has a nasty bug though 😟 but it might be useful. 

Related: https://github.com/quintel/etmodel/issues/1923

**Comment by MartLubben** [comment]
I was also quite lost the first times when I was looking for a graph. For me the images helped a lot, so I am not pro a list. (maybe an option to choose between list and images, but this should not make it more complicated.)

My proposal: 
1. ONLY use the 10 most used charts in 'Overview', so less experienced users can easily find some interesting charts. At this moment 'Overview' includes 27 charts. 
2. The rest could stay the same, however a revision of the names could be an option, or an addition of numbers. I do not have a strong opinion about this part.

**Comment by marliekeverweij** [comment]
Just found this issue again and it is Friday afternoon 🙂  
I like Marts idea of only showing around 10 most used charts in 'Overview' and put the rest in other categories. But which ones are the most used? Please check below the charts that you use most! I hope this works like this, otherwise just post your favourite charts in a comment. Also charts from other categories can be added to 'Overview'!
- [ ] Primary energy use 
- [ ] Sankey diagram of future energy flows
- [ ] Sankey diagram of present energy flows
- [ ] CO2 emissions of electricity production 
- [ ] Supply and demand of the central heat network
- [ ] Detailed final energy demand in the industry 
- [ ] Detailed energetic final energy demand in the industry 
- [ ] CO2 emissions biomass 
- [ ] CO2 emissions of international transportation 
- [ ] CO/CO2 available and used for power-to-kerosene 
- [ ] CO2 emissions 
- [ ] Present energy imports 
- [ ] Renewability of final demand
- [ ] Realization of the electricity demand
- [ ] Primary energy use 
- [ ] Future energy imports 
- [ ] Security of supply 
- [ ] Renewable electricity 
- [ ] Final energy demand
- [ ] Primary CO2 emissions of final demand 
- [ ] Primary demand of biogenic energy carriers 
- [ ] Bio-footprint of primary demand 
- [ ] Net flow of refinery products 
- [ ] Sankey diagram of energetic on-the-spot CO2 emissions 
- [ ] Relative CO2 emissions of primary energy use 
- [ ] Relative primary use of coal, oil and gas 


Maybe an extra category for CO2-charts named 'CO2 emissions' is a good idea, below the 'Overview' category. What do you think? 

I also thought of making subgroups (Gerard's suggestion) within the demand section (for industry, transport, agriculture etc), I just checked and that works fine.

>I like sorting alphabetically within category, but this shouldn't lead to different orders when using English or Dutch. I thinks this is currently the case and always means I look for charts longer than necessary as I expect them to be at a certain place in the list.

It seems that the order is not changing anymore between English and Dutch, just checked 🙂   
And I think sorting alphabetically is not needed anymore when the number of charts within a category is less.

**Comment by ChaelKruip** [comment]
@grdw can you use Analytics to track which charts are actually picked most by people using the ETM? This way we could use actual user statistics to guide us in this issue.

**Comment by DorinevanderVlies** [comment]
> @grdw can you use Analytics to track which charts are actually picked most by people using the ETM?

**Comment by DorinevanderVlies** [comment]
@grdw can you use Analytics to track which charts are actually picked most by people using the ETM?

@grdw I assume your "thumbs up" means that this is possible, nice! 

I added the "primary demand mekko" and the "electricity production" chart to the ticks. 

We could also include some charts to which we want to draw attention to the "overview". For example CO<sub>2</sub>-emissions of international transport or the dynamic demand curve.

**Comment by marliekeverweij** [comment]
Maybe this issue would also be nice to fix before the deploy next week! Does anybody have time to tackle this?! (I do not...)

**Comment by MartLubben** [comment]
Another quick fix option is to not change the overview, but add an extra group on top with: 'Most used',

This should include the 10 most used according to analytics. @grdw Is this easy to get? Do you already have it? And does this contain enough data or is it just too little to represent the 'average' ETM user?

**Comment by grdw** [comment]
> This should include the 10 most used according to analytics. @grdw Is this easy to get? 

Yes, in time...

> Do you already have it? 

No, unfortunately not.  The only way you can easily say something - as of right now - about the 10 most used charts, is by asking everybody within Quintel what the most used charts are. Which actually might be representative as we are probably the most active user-group. Google analytics is not yet in the ETM, this still needs to be finished.

**Comment by grdw** [comment]
Related: #2653

**Comment by grdw** [comment]
Just going to update here: It's now possible to see which charts are being used by going to Google Analytics -> (Pro) Energy transition model -> Behavior -> Top Events -> 2. chart -> 1. added. 

This list only contains data for one month of user analytics (for 264 users) which might not be that conclusive. I'd suggest to hold this off for a couple of months when there's something relevant to show. Also the more I think about it, the more I actually wouldn't want to order the charts by 'most used' (as that can fluctuate on a monthly basis).

---
Just to sum up:

**Features I'm hearing:**

- Add a search box
- Make it possible to sort the charts on: alphabet, by group name, 
- Make it possible to shed some extra light on perticular charts.
- Maybe it would be nice to filter the charts by chart type?

**What we could do is something like:**

![screen shot 2018-04-04 at 11 06 34](https://user-images.githubusercontent.com/2676542/38298695-5f12a42a-37f8-11e8-8b8c-467b2dc4be12.png)

Where we have 4 featured charts and below would be the rest of the charts. The 4 featured charts can be 'most used' or recently added charts - whatever we'd like to be put there.

**Comment by jorisberkhout** [comment]
Moved to 'Deploy June 2018' milestone.

**Comment by marliekeverweij** [comment]
This afternoon I have been sorting the charts in the chart list on beta. These charts are now selected for 'Overview' (other charts are moved to other sections): 
 
![screen shot 2018-06-27 at 16 14 37](https://user-images.githubusercontent.com/32833996/41979962-9c358038-7a25-11e8-84e4-4e7d72a7219d.png)

The other sections have been organised by adding sub-categories (which could be done in the admin). These sub-categories are based on the sidebar categories in the ETM, for example 'Demand' is now split into the different sectors:

![screen shot 2018-06-27 at 16 21 06](https://user-images.githubusercontent.com/32833996/41980183-28d2488c-7a26-11e8-8a0e-42f8f208e9c1.png)

And I was thinking of some other improvements:
1. I think it would be better if the charts within a section are sorted alphabetically; is everybody okay with that?
2. Could the order of the categories within a section be changed @antw ? For example for 'Demand' I would like the sectors to be in the same order as they are in the sidebar and for 'Supply' I would also like that the categories to follow the order in the sidebar
3. Adding dutch translations for the sub-categories; where can I do that @antw ? I can only find where to add translations for the sections.
4. I think it would also be good to add a search function to this list. Is this possible and how much work would this be @antw?

Feel free to change the location of a chart again if you do not agree with the current structure :)

**Comment by marliekeverweij** [comment]
> Adding dutch translations for the sub-categories; where can I do that @antw ? I can only find where to add translations for the sections.

@Michiel found out where to adjust these translations, so this is done!

**Comment by antw** [comment]
> Could the order of the categories within a section be changed @antw ?

The order is hard-coded and is not so easy to change if you don't know the Ruby language. [I've ordered the sub-groups as requested](https://github.com/quintel/etmodel/commit/d6864d39f7b6d2e38be81b3aae758133bb78443a).

> I think it would also be good to add a search function to this list. Is this possible and how much work would this be @antw?

Yes, I'd love to have this too. It'll probably cost us a couple of days to do it properly.

**Comment by marliekeverweij** [comment]
I will close this issue and create a new one for the search-function and a new one for sorting the charts alphabetically
