### ISSUE TITLE
Idea: include option for 'Dunkelflaute' similar to the 'Cold snap' option

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2613]
I have often been told that the electricity system needs to be robust enough to provide security of supply even during a so-called _Dunkelflaute_. This German term describes a once-in-so-many-years event in which there is little sunshine an no wind in a country or area (of Europe). 

I think the ETM can be improved by including an option for this, just like the current option for 'Cold snap' included at the behest of Gasunie. Of course, the cold snap and _Dunkelflaute_ are likely to be related, and therefore not independent, but the extent to which they are I leave to be researched. 

To be researched:
- Just what happens during a _Dunkelflaute_ to wind and solar curves, or even temperature curves?
- Does a _Dunkelflaute_ significantly impact the average temperature in a year in a predictable way?
- How often does such an event occur and how long does it last?
- etc..

Notifying @ChaelKruip @jorisberkhout @michieldenhaan @MartLubben @DorinevanderVlies

**Comment by AlexanderWirtz** [comment]
I happen to know that Ecofys and CIEP have published on this topic or have expertise in this matter

**Comment by michieldenhaan** [comment]
Closing, this is now supported! https://github.com/quintel/etmodel/commit/f72e9edd9663ff7b756afec0bb126f09a6ae2ca1
