### ISSUE TITLE
Could we incorporate car sharing into the ETM?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2616]
I think it would be interesting to add a slider for the amount of sharing of (autonomous) EV will happen in the future. 

@jorisberkhout @DorinevanderVlies @michieldenhaan @marliekeverweij @MartLubben I am curious about your thoughts!

**Comment by DorinevanderVlies** [comment]
I agree that it is important to take (the share of) autonomous vehicles into account in scenario's. However, there are a lot of different thoughts about the effects of autonomous vehicles.
- How much will the number of cars decrease?
- How will this affect the steel section?
- How will this affect the total passenger kms of cars (and other applications)?

Do you have any ideas of what this slider should do?

IMO the ETM can already model the possible effects of autonomous vehicles pretty well without a specific slider. Maybe we can add some information for users on which sliders to set when they want to model their vision on autonomous vehicles.

**Comment by ChaelKruip** [comment]
> there are a lot of different thoughts about the effects of autonomous vehicles

The effects that @DorinevanderVlies mentions are second order and therefore the responsibility of the user IMO. Right now, you can also use public transport instead of cars but leave the steel industry and refinery as is for instance...

In the same category:

* How will this affect the amount of storage capacity available for flexibility that we attribute to EV?

The question I am more worried about is the following:

* How will this affect the charging profiles? These will likely change beyond what we can model with the current profiles...

> Do you have any ideas of what this slider should do?

* Change the number of person_kms per unit
* Change the full_load_hours (with possible impact on O&M costs and technical_lifetime?)

**Comment by jorisberkhout** [comment]
I like the idea of adding a slider for car sharing as this is often debated as a solution (including in our own Industry report). I agree with @ChaelKruip on what the slider should and that it is up to the user to worry about the secondary effects on the steel and industry sector.

I would be happy to discuss the effects on charging profiles and flexibility available.

**Comment by marliekeverweij** [comment]
I also think this would be a really nice added feature! And I think that it is possible to find data about the impact of car-sharing on the technical performance and O&M costs of EV.
