### ISSUE TITLE
Hide sector/subsector if demand is 0 PJ

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2618]
The final demand charts currently show all sectors/subsectors regardless whether these sectors have an energy demand (see picture e.g. international transport, refineries, fertilizers). This makes the charts harder to read. Is it possible to hide these sectors? (Another option would be to sort the chart sectors from large to small so 0 PJ sectors are all on the right)
![0pjchart](https://user-images.githubusercontent.com/32056448/34299060-35628afa-e721-11e7-99d2-3fe0220f8816.png)

**Comment by marliekeverweij** [comment]
This falls into the same category as issue #2588

**Comment by grdw** [comment]
> so maybe both issues can be fixed at the same time 

Unfortunately, no. These are two separate issues due to the two different types of charts.

**Comment by antw** [comment]
@grdw has created a pull request (#2623), but I'm not entirely sure I agree with the premise of this issue (or #2588). There *is* value in showing that something is zero; that it makes no contribution – positive or negative – to the outcome of the scenario. When it is hidden, it's not clear whether the value is zero or if it is an explicit choice (it may be non-zero but we've decided to hide the series anyway).

We've already done this for a couple of charts, but I think we should seek more feedback before continuing down this path.

*Side-note: In the past we would only hide a series when the thing it represented was not modelled in the region (for example, series for buildings would be hidden when `has_buildings` is false).*

---

Including @jorisberkhout @ChaelKruip @DorinevanderVlies.

**Comment by ChaelKruip** [comment]
> We've already done this for a couple of charts, but I think we should seek more feedback before continuing down this path.

I agree! 

For the Mekko's I think it is not a good idea to hide subsectors except those that are explicitly not modelled/available in the region as @antw mentions in his side-note.

**Comment by michieldenhaan** [comment]
How about option 2: sort the sectors from large to small so the zeroes are all at the right of the chart?

**Comment by marliekeverweij** [comment]
> How about option 2: sort the sectors from large to small so the zeroes are all at the right of the chart?

I like this idea! Then still all sectors are shown, but in an organised way

**Comment by grdw** [comment]
> How about option 2: sort the sectors from large to small so the zeroes are all at the right of the chart?

You'd still *see* all the zeros. So I think sorting is nice, but it's a different issue. Can we for clearification purposes, close this issue and create a new one about mekko-sorting?

**Comment by grdw** [comment]
Actually there already is one: https://github.com/quintel/etmodel/issues/2223
