### ISSUE TITLE
Local datasets have a # of units minimum of 1 even when area available is 0

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2619]
See picture below (coastal wind). When coast line (or any other land availability property) is set to 0, it is still possible to build 1 power plant unit.

![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://user-images.githubusercontent.com/32056448/34299200-f5e716c4-e721-11e7-8c09-9e8b21388625.png)

**Comment by grdw** [comment]
This has to do with the [max_value_gql](https://github.com/quintel/etsource/blob/master/inputs/supply/number_of/number_of_energy_power_wind_turbine_coastal.ad#L7) property of the input

**Comment by michieldenhaan** [comment]
Is there a reason for this? I would say the minimum should be 0. 
Notifying @ChaelKruip

**Comment by grdw** [comment]
I would suggest to hide this slider if the coast line is 0.

**Comment by ChaelKruip** [comment]
> Is there a reason for this? I would say the minimum should be 0.

Everything has a reason @michieldenhaan! Perhaps we use the number of windturbines in the denominator of a fraction?

**Comment by grdw** [comment]
Is this still relevant? I just created a dataset with the area of 'Reitdiep' and saw that the sliders start at 0 and move up to 1.

![screen shot 2018-03-01 at 14 50 53](https://user-images.githubusercontent.com/2676542/36847896-f78e4820-1d5f-11e8-973e-099b9bd4ce13.png)
![screen shot 2018-03-01 at 14 50 56](https://user-images.githubusercontent.com/2676542/36847897-f7aa22a2-1d5f-11e8-8733-e14565fe98e2.png)

Is that the correct behavior or should the sliders in question still be hidden?

**Comment by michieldenhaan** [comment]
Still relevant, would be nice if you can hide the onshore coast slider if coast_line = 0

**Comment by grdw** [comment]
> [..] would be nice if you can hide the onshore coast slider if coast_line = 0

Just to be clear: it only has to affect *onshore*, not offshore?

**Comment by grdw** [comment]
I'm a bit at unease about how to solve this properly. I see multiple routes

### 1. Adding a `visibility_gql` attribute to `Input` in `Atlas`

This way you can add an attribute per input as such:

```ruby
- query =
    EACH(
      UPDATE(V(energy_power_wind_turbine_inland), number_of_units, USER_INPUT()),
      UPDATE(L(energy_power_wind_turbine_inland), preset_demand_by_electricity_production, V(energy_power_wind_turbine_inland, production_based_on_number_of_units))
    )
- priority = 0
- max_value_gql = present:MAX(1.0,DIVIDE(AREA(onshore_suitable_for_wind),V(energy_power_wind_turbine_inland,land_use_per_unit)))
- min_value = 0.0
- start_value_gql = present:V(energy_power_wind_turbine_inland,number_of_units)
- step_value = 0.1
- unit = #
- update_period = future

# NEW
- visibility_gql = AREA(coast_line) > 0
```

ETModel has to figure out the rest.

---

#### 2. Use a separate Gquery in the front-end of ETModel

Add a `visibility_gquery` column to the `input_elements` table. This `visibility_gquery` value will point to a `.gql` file with contentst as such:

```ruby
- query = AREA(coast_line) > 0
```

@antw may I know your thoughts on these possibilites, what would you suggest?

**Comment by antw** [comment]
> what would you suggest?

1. In the dataset, set `has_coastline = false`.
2. For the slider, in ETModel add an area dependency on `has_coastline`:
  ![screen shot 2018-03-02 at 10 29 25](https://user-images.githubusercontent.com/4383/36895265-3dd5d054-1e06-11e8-8fdc-e48644bfef08.png)

This dependency is already in place for the coastal and offshore turbines – so I don't think this needs to be changed – it's just that no-one has ever set `has_coastline` to false.

You may need to clear ETModel's cache for it to see that the dataset `has_coastline` has become false.

**Comment by grdw** [comment]
I added the switch, thanks @antw ! That's way easier 👍 

@michieldenhaan can I leave it up to you to figure out which local dataset have a coastline and which doesn't?

**Comment by michieldenhaan** [comment]
yup, thanks guys
