### ISSUE TITLE
Fuel Prices - Percentage change cannot be displayed on the slider's LHS

### ISSUE THREAD

**Issue by nairnamratha** [quintel/etmodel#2622]
As part of the fuel price update issue  [#2593](https://github.com/quintel/etmodel/issues/2593) , the left-hand side of the sliders should show the percentage change between the original cost of the fuel and user-defined cost of the fuel (as a result of the slider changes made by the user).

This, however, seems to require in-depth changes to be made to the the ET Engine, as the unit is preset as %. Here’s a [note](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/views/input_element_view.js#L499-L503) made by @antw  regarding this.

**Comment by MartLubben** [comment]
@nairnamratha can this be closed?
