### ISSUE TITLE
How do nodes get their full load hours assigned?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2632]
The full load hours for `households_solar_pv_solar_radiation` for instance are listed in the [central_producers.csv](https://github.com/quintel/etsource/blob/master/datasets/nl/central_producers.csv#L36) which is part of every dataset.

For some nodes, their full_load_hours are taken from this CSV file by [a query in the node.ad file](https://github.com/quintel/etsource/blob/master/nodes/households/households_collective_chp_biogas.central_producer.ad#L43).

Such a query is absent for `households_solar_pv_solar_radiation` and full_load_hours are not hard-coded in the node.ad file either.

How do the nodes which don't have a `full_load_hours = ...` statement get their full_load_hours?

**Comment by ChaelKruip** [comment]
Including @DorinevanderVlies @michieldenhaan

**Comment by antw** [comment]
> Such a query is absent for households_solar_pv_solar_radiation and full_load_hours are not hard-coded in the node.ad file either.

That node is a central producer. [The queries for central producers are implicit](https://github.com/quintel/atlas/blob/85f7746e988df1eff00f4c15db32a48291082dda/lib/atlas/node/central_producer.rb#L8-L11).

With the benefit of hindsight, I'm not sure how to feel about the implicit queries for these nodes. The goal was to simplify things (set the node as a central producer and just add the values to the CSV; no need to write the queries yourself) but perhaps it makes the mechanics of Atlas+ETSource *more* confusing to not be able to see the query when reading the node file?

**Comment by ChaelKruip** [comment]
> With the benefit of hindsight, I'm not sure how to feel about the implicit queries for these nodes. The goal was to simplify things (set the node as a central producer and just add the values to the CSV; no need to write the queries yourself) but perhaps it makes the mechanics of Atlas+ETSource more confusing to not be able to see the query when reading the node file?

At least for me, this is indeed confusing. I would be happier with explicit queries for all producers. Is that as easy as reverting a commit @antw ?

**Comment by ChaelKruip** [comment]
> Would it still have meaning for "central_producer" to be in the node filename after adding the queries, or should we remove that as well?

I'm not sure to be honest... 

Perhaps @jorisberkhout can give additional insights/opinions here? It might become relevant for the network calculation project to re-evaluate the status of the producers as the households solar PV for instance might become a read de-central producer!
