### ISSUE TITLE
New technologies for public transport and kerosene should be added to scenario report

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2651]
Assigning @marliekeverweij , I am happy to help you to get started!

notifying @ChaelKruip

**Comment by DorinevanderVlies** [comment]
co-assigning @martlubben.

This can be changed and tested on your local machine

Relevant folders:
https://github.com/quintel/etmodel/tree/master/config/reports
https://github.com/quintel/etsource/tree/master/gqueries/modules/scenario_report 

Some previous issues regarding the scenario report:
https://github.com/quintel/etmodel/issues/2495
and this search:
https://github.com/quintel/etmodel/issues?utf8=%E2%9C%93&q=is%3Aissue+scenario+report

**Comment by marliekeverweij** [comment]
I can do this next week 🙂

**Comment by MartLubben** [comment]
I will play with it today and will co-do it next week with you @marliekeverweij

**Comment by marliekeverweij** [comment]
We actually found out that the scenario report does not have to be adjusted because of the changes in public transport and kerosene 😉  the new sector 'international transport' is already displayed in all relevant charts.

So I will close this issue 🙂
