### ISSUE TITLE
Hidden unit names

### ISSUE THREAD

**Issue by nairnamratha** [quintel/etmodel#2652]
Units for the sliders under Fuel Prices are currently hidden by the tool tips icon.

![screen shot 2018-01-25 at 16 13 18](https://user-images.githubusercontent.com/32448293/35395504-d2fbc2a2-01ea-11e8-891b-0815a251e03f.png)

Can we move the tool tips more to the right so that the entire unit is visible?

**Comment by antw** [comment]
IMO it makes more sense to set the step value for these sliders to `1` instead of `0.01` since the decimal places don't convey much useful information. That will also conveniently fit into the available space:

![screen shot 2018-01-25 at 16 01 01](https://user-images.githubusercontent.com/4383/35398121-1ababb0e-01e9-11e8-8ea7-2432fcb6c7ed.png)

**Comment by nairnamratha** [comment]
@michieldenhaan pointed out that reducing the number of significant figures could affect the total cost results on the dashboard. 

I just checked this out and it does make a significant difference to the costs, especially as the fuel prices increase. The ETengine takes the number of significant figures shown in the UI into account in related calculations. 

So it would be good to keep those significant figures as they are, to avoid changes to related calculations like total costs on the dashboard.

**Comment by ChaelKruip** [comment]
> I just checked this out and it does make a significant difference to the costs

What does 'significant' mean here? 1%? 10%?

> So it would be good to keep those significant figures as they are, to avoid changes to related calculations like total costs on the dashboard.

I disagree. I think that fuel prices are very uncertain and any changes due to rounding are fake accuracy anyways.

**Comment by nairnamratha** [comment]
Thanks a lot for pointing this out.  My bad here!

(I went back and checked again, and realised that I had previously checked this on my local server where I didn't take some unrelated changes into consideration.)
 
Anyway, it's right that reducing the sig. figs doesn't affect the final costs. So, I will change the step value to 1 for these sliders, hence no other changes are required .
