### ISSUE TITLE
Improving renewable electricity chart 

### ISSUE THREAD

**Issue by nairnamratha** [quintel/etmodel#2659]
I think that this chart, "Renewable electricity", which currently only shows the percentage share of renewable electricity available could do with some improvements:

![screen shot 2018-02-05 at 16 12 13](https://user-images.githubusercontent.com/32448293/35812038-378f611c-0a90-11e8-86f9-f15ed1011874.png)

We could possibly paint a clearer and bigger picture if we could add more info to the chart, for example:

- Percentage share of specific renewable electricity sources which add up to  the cumulative share of renewable electricity (i.e. 5% solar, 10% wind etc.)

Other ideas welcome!

**Comment by michieldenhaan** [comment]
> Percentage share of specific renewable electricity sources which add up to the cumulative share of renewable electricity (i.e. 5% solar, 10% wind etc.)

Very good idea!

**Comment by nairnamratha** [comment]
Done!
