### ISSUE TITLE
Sanegeest does not appear in the partners while it's clearly in the partners.json

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2660]
Here is [Sanegeest](https://beta.energytransitionmodel.com/partners.json) (at the bottom). However I don't see it appear on the beta et-model. 🤔 

I cleared the cache and restarted puma but it didn't quiet work... 

@antw do you know what might be the cause?

**Comment by antw** [comment]
[Closed with an updated config](https://github.com/quintel/ansible/commit/ce52dcd29810ca3f332cdfcd745adf040f702578).
