### ISSUE TITLE
Flex-order should be first slide

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2662]
Now you get this less useful slide:
![image](https://user-images.githubusercontent.com/1303760/36299276-8c1323e4-12fc-11e8-9faa-e0c383ec804d.png)

**Comment by marliekeverweij** [comment]
Okay! Shall I delete the first slide and integrate the text of both slides into one slide (the flex-order slide)?

**Comment by ChaelKruip** [comment]
> Okay! Shall I delete the first slide and integrate the text of both slides into one slide (the flex-order slide)?

I think that would be great!

**Comment by marliekeverweij** [comment]
I have changed the flexibility slides, this is the result:

![screen shot 2018-02-26 at 11 54 27](https://user-images.githubusercontent.com/32833996/36666738-d59d7da6-1aeb-11e8-9543-c48bfd0e4396.png)

One question: which chart do we want to be displayed on the right? In the text I now explain the table that is currently shown. But personally I like this one:

![screen shot 2018-02-26 at 11 58 15](https://user-images.githubusercontent.com/32833996/36666900-5ab38152-1aec-11e8-82b5-437a01683998.png)

Or we could do 'Duration of excess electricity events', that was connected to the first slide. What do you prefer @ChaelKruip ?

**Comment by ChaelKruip** [comment]
> I have changed the flexibility slides, this is the result:

I like it but I also think there is (way) too much text now. If you have a small screen, you need to scroll down to reach the 'merit order'. Perhaps we can reduce this text? I can help 😄 

> But personally I like this one:

me too!

**Comment by marliekeverweij** [comment]
I have deleted some text! Maybe more can be deleted, but I could not figure out which part

![screen shot 2018-03-01 at 14 11 09](https://user-images.githubusercontent.com/32833996/36846307-72d876e6-1d5a-11e8-85a5-dfd1a2ea9265.png)

**Comment by ChaelKruip** [comment]
> I have deleted some text! Maybe more can be deleted, but I could not figure out which part

Thanks! I removed one more sentence and am closing this now.
