### ISSUE TITLE
Only show non-zero producers in time-resolved electricity production chart

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2663]
Now the legend is too cluttered:
![image](https://user-images.githubusercontent.com/1303760/36299869-3aee5e4a-12ff-11e8-859b-71f82d6f9261.png)

**Comment by jorisberkhout** [comment]
Moved to 'Deploy June 2018' milestone.

**Comment by antw** [comment]
This is already the case. [Only series with one or more hours of non-zero production are shown](https://github.com/quintel/etmodel/blob/438e14b9acde93455eda0aecead8a7b1c3576f11/app/assets/javascripts/d3/merit_order_hourly_supply.coffee#L31).
