### ISSUE TITLE
Downloadlink of industry report is broken

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2667]
The link to [https://quintel.com/publications/industry](https://quintel.com/publications/industry) still works, however pressing the download button which redirects to [https://quintel.com/publications/industry/download](https://quintel.com/publications/industry/download) gives:

![image](https://user-images.githubusercontent.com/19907658/36529856-df043702-17b9-11e8-86ac-dfcfe03ae310.png)

**Comment by grdw** [comment]
Fixed it with https://github.com/quintel/quintel.com/commit/5246e8f2e6aa630e7ecf5cd44e718c82c282cd55
