### ISSUE TITLE
Micro-CHP can only be up to 55% while all other technologies can be 100%

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2668]
Is this what we desire?
If so, shouldn't we mention the why in the '?' ?

![screen shot 2018-02-23 at 09 36 50](https://user-images.githubusercontent.com/33415156/36590742-f8cc6138-188f-11e8-98f0-d53d448b4029.png)

**Comment by AlexanderWirtz** [comment]
This is something I need time to look at. Removing milestone.

**Comment by michieldenhaan** [comment]
Closing, the micro-CHP has been removed in the recent heat overhaul
