### ISSUE TITLE
Order technologies space heating/hot water not the same

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2672]
![heatingwatertechs](https://user-images.githubusercontent.com/32056448/36606135-0a9b970c-18c3-11e8-8c31-e8faec56f59f.png)

**Comment by MartLubben** [comment]
Now ordered alphabetically. 
OK?

![screen shot 2018-02-26 at 09 41 31](https://user-images.githubusercontent.com/33415156/36660666-46d70838-1ad9-11e8-83aa-8a893651e6dc.png)
![screen shot 2018-02-26 at 09 41 38](https://user-images.githubusercontent.com/33415156/36660667-46f0140e-1ad9-11e8-9c03-ea640804ee7c.png)
