### ISSUE TITLE
Translations seem to be missing on LIVE

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2673]
![image](https://user-images.githubusercontent.com/1303760/36632768-13b2face-198b-11e8-8af7-9bfc8e96cb83.png)

**Comment by grdw** [comment]
They aren't gone on https://beta-pro.energytransitionmodel.com. This is already solved  with https://github.com/quintel/etmodel/commit/29e9d0457b53329c358e64466445e282d05f3515

**Comment by grdw** [comment]
https://pro.energytransitionmodel.com/scenario/demand/transport/truck-technology it got deployed to production.
