### ISSUE TITLE
Wrong translation used for hydrogen production in flex chart

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2675]
![image](https://user-images.githubusercontent.com/1303760/36633051-e3fa7cfe-198e-11e8-85c6-1651f46087c2.png)

**Comment by marliekeverweij** [comment]
Done! 
I have also updated other legend names to more understandable ones:
- converted to gas > converted to **hydrogen**
- converted to heat > converted to heat **for households**
- stored in batteries > stored in **household** batteries

![flexibility legend](https://user-images.githubusercontent.com/32833996/36661550-d4369430-1adb-11e8-93ed-55b30bf596a3.jpg)
