### ISSUE TITLE
Every central heater should have a slider in the front-end

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2682]
There are seven heaters:
![image](https://user-images.githubusercontent.com/1303760/36727577-10e5394e-1bbe-11e8-8da3-bf34365d2b54.png)
But only 5 have a slider:
![image](https://user-images.githubusercontent.com/1303760/36727620-3c5f8e12-1bbe-11e8-876a-351121128158.png)

As far as I can see there is a slider for:
* Coal
* Oil
* Waste
* Gas
* Biomass (in renewable heat section)

For lignite, I think the slider should be country dependent (NL does not have lignite, but DE does). For geothermal I think there should be a new slider.

Including @jorisberkhout @AlexanderWirtz

**Comment by ChaelKruip** [comment]
> For geothermal I think there should be a new slider.

@michieldenhaan @AlexanderWirtz @jorisberkhout @MartLubben do you agree? 

This would help with some of the recent Gelderland scenario's as well...

**Comment by ChaelKruip** [comment]
Assigning @MartLubben

**Comment by MartLubben** [comment]
Done and closed
