### ISSUE TITLE
Coal CHP should not be displayed in heat mekko as central heater

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2683]
I removed all coal heater but still see heat from coal:
![image](https://user-images.githubusercontent.com/1303760/36727974-713b089a-1bbf-11e8-883d-af0af9493c4d.png)
Either the label or the query is wrong...

**Comment by marliekeverweij** [comment]
I think I found the problem! 
In the queries of this mekko the coal chps and heaters are switched:

![issue_2683](https://user-images.githubusercontent.com/32833996/36845615-c2af0750-1d57-11e8-9753-f069b8ec09d6.jpg)

Do you agree?

Btw: both the lignite chps and heaters are switched off by default, so indeed the other issue (#2682) could wait until after the deploy!

**Comment by ChaelKruip** [comment]
> Do you agree? Then I will switch them back.

Great catch! Yes please switch them back 😄

**Comment by ChaelKruip** [comment]
@marliekeverweij please also check that the queries themselves refer to the correct nodes as well. Thanks!

**Comment by marliekeverweij** [comment]
> please also check that the queries themselves refer to the correct nodes as well. 

Done. And I checked if it works locally and it does; now the queries correspond to the correct energy flows.
