### ISSUE TITLE
Final demand of international aviation in mekko is incorrectly calculated

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2684]
I am making screenshots for in my presentation tomorrow and now I bump into an issue! The final demand of international aviation seems to be doubled in the final demand mekko:

![screen shot 2018-02-27 at 15 44 57](https://user-images.githubusercontent.com/32833996/36735185-d77e8e68-1bd5-11e8-981d-0e62855d5cf6.png)

The final demand is 158 PJ and not 0.32 EJ!

Somehow the kerosene demand is doubled! Maybe this has to do with our solution of the separate node for international aviation and international navigation where the demand is imported for the IEA dataset. However, for international shipping the final demand is not doubled...

The query for this chart is:
```# Final demand of the 'oil_and_derivatives' carrier group

- unit = PJ
- query =
    SUM(
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :bunkers"
          ),
          crude_oil?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :bunkers"
          ),
          gasoline?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :bunkers"
          ),
          diesel?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :bunkers"
          ),
          lpg?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :bunkers"
          ),
          kerosene?
        ),
        value
      ),
      V(
        FILTER(
          FILTER(
            LG(final_demand),"sector == :bunkers"
          ),
          heavy_fuel_oil?
        ),
        value
      )
    ) / BILLIONS
```

![screen shot 2018-02-27 at 15 54 18](https://user-images.githubusercontent.com/32833996/36735704-0ec60864-1bd7-11e8-951b-4a9110d4258c.png)

**Comment by grdw** [comment]
I just did this - out of curiosity: 

```ruby
FILTER(LG(final_demand), "sector == :bunkers")
```

Which returned:

```ruby
[
  <Qernel::Link "bunkers_aviation_mixer_kerosene-(kerosene) -- s --> (kerosene)-bunkers_final_demand_for_aviation_kerosene">,
  <Qernel::Link "bunkers_aviation_mixer_kerosene-(kerosene) -- f --> (kerosene)-bunkers_final_demand_for_aviation_bio_kerosene">,
  <Qernel::Link "bunkers_ship_using_lng-(lng) -- s --> (lng)-bunkers_final_demand_for_shipping_lng">,
  <Qernel::Link "bunkers_ship_using_heavy_fuel_oil-(heavy_fuel_oil) -- s --> (heavy_fuel_oil)-bunkers_final_demand_for_shipping_heavy_fuel_oil">
]
```

Which makes me think that `lpg?`, `gasoline?` and `diesel?` don't return any graph edges.

**Comment by ChaelKruip** [comment]
> Which makes me think that lpg?, gasoline? and diesel? don't return any graph edges.

True.

> PS: Can't the whole thing above be rewritten as:

Yes 😄

**Comment by marliekeverweij** [comment]
Apparently this issue has already been fixed, because it is not there anymore. But I ran into a new one:

![screen shot 2018-06-20 at 09 35 34](https://user-images.githubusercontent.com/32833996/41644088-6c34c24e-746d-11e8-853d-e186b46cea09.png)
 
Bio-kerosene is not displayed in the final demand mekko, instead kerosene is shown. I found out that an edge had a wrong name with kerosene in it instead of bio-kerosene. I am fixing that now

**Comment by marliekeverweij** [comment]
This is a bit more complex than thought. Discussed with @ChaelKruip that we will fix this after the deploy. 

Part of the fix is on this branch: https://github.com/quintel/etsource/tree/bio-kerosene-fix

**Comment by marliekeverweij** [comment]
> But I ran into a new one:

To fix this issue properly I wanted to change the carrier of this edge to bio-kerosene (because the final demand chart gets the demands from these edges):
![screen shot 2018-06-29 at 09 43 09](https://user-images.githubusercontent.com/32833996/42080073-ba089e12-7b81-11e8-88b5-eec8d61d4a5a.png)
I thought that would be an easy fix, however changing the carrier of this edge gives me the following error:

![screen shot 2018-06-29 at 09 47 38](https://user-images.githubusercontent.com/32833996/42079991-85f41c5a-7b81-11e8-889d-0d746fa68878.png)

Apparently there is more to do than that! Do you maybe know what is going on @antw?

(There is also a more ugly fix by changing the query of the final demand mekko, but then the query would not be consistent wit all other queries for that mekko.)

**Comment by marliekeverweij** [comment]
@michieldenhaan just explained me where the error comes from @antw!

I am closing this issue (because it was initially another issue) and created a new one https://github.com/quintel/etmodel/issues/2835 .
