### ISSUE TITLE
IE10 (Windows), Safari 5.1 (Windows) - Layout of local vs global spans full width of the screen

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2687]
What it looks like on Windows - IE10, Windows - Safari 5.1:

![screen shot 2018-03-01 at 13 20 23](https://user-images.githubusercontent.com/2676542/36844522-6526a844-1d53-11e8-9805-77cd49820317.png)

What it looks like on Firefox:

![screen shot 2018-03-01 at 13 21 28](https://user-images.githubusercontent.com/2676542/36844564-86d0b908-1d53-11e8-865d-d2b30366cb3f.png)

**Comment by antw** [comment]
Closed by f5da2815a
