### ISSUE TITLE
Merit Order Capacities Chart doesn't scale properly

### ISSUE THREAD

**Issue by nairnamratha** [quintel/etmodel#2693]
The chart doesn't scale properly when there are no oil and diesel plants present. As shown below
![screen shot 2018-03-05 at 16 40 05](https://user-images.githubusercontent.com/32448293/36984067-4334b9e4-2094-11e8-8101-3464c3fc9103.png)
However, when oil-fired power plants /diesel generators are added, then the chart works fine:
![screen shot 2018-03-05 at 16 39 52](https://user-images.githubusercontent.com/32448293/36984072-46d3dfd0-2094-11e8-9599-88d786b88c6b.png)

**Comment by grdw** [comment]
Seems a little odd to this within the February deploy. Will pick this up, but if it's not of high priority I'm going to do this tomorrow.
