### ISSUE TITLE
Chart: Supply and demand of the central heat network. The sum of the table is always 0.

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2696]
@antw Can I fix this myself? 

![screen shot 2018-03-05 at 17 37 17](https://user-images.githubusercontent.com/33415156/37021514-1db7a4b0-2120-11e8-8691-9254b000e380.png)

**Comment by jorisberkhout** [comment]
Moved to 'Deploy June 2018' milestone.

**Comment by antw** [comment]
This doesn't seem to be actionable at the moment, so I'll remove the milestone.

**Comment by marliekeverweij** [comment]
Apparently already fixed 🙂
![Screen Shot 2019-04-08 at 16 47 34](https://user-images.githubusercontent.com/32833996/55733403-0f140600-5a1e-11e9-9a20-e8f74e0e2cfe.png)
