### ISSUE TITLE
CO2 emissions BETA vs LIVE are different; what is the reason for that?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2698]
The CO2 emissions in the dashboard of BETA vs LIVE differ: 
- BETA = + 9.9%
- LIVE = + 8.7%

![beta_co2](https://user-images.githubusercontent.com/32833996/37038722-daaf51a0-2155-11e8-9d2b-246504611e87.jpg)

![live_co2](https://user-images.githubusercontent.com/32833996/37038753-f1b1bd20-2155-11e8-921b-821351232617.jpg)

@michieldenhaan suggested that it could be the import of biogenic waste that has co2_per_mj factor of 0.0835255319148936 on BETA. But I cannot figure out if that is the total issue!

**Comment by ChaelKruip** [comment]
> But I cannot figure out if that is the total issue! 

Perhaps the "Primary CO2 Mekko chart" in table view can give you some insight?

**Comment by michieldenhaan** [comment]
I was referring to: https://github.com/quintel/etsource/commit/6c6b55cbefbcb5099a7caa09adf208f0563c43d5. I.e. the carrier ``non_biogenic waste`` has a non-zero ``co2_conversion_per_mj`` on beta.
This results in 1.8197 MT extra CO2 in 2015.

**Comment by marliekeverweij** [comment]
This difference is only in the electricity and hot water consumption. @michieldenhaan says this has to do with the factor for the import of biogenic waste. 

![beta_primary_co2](https://user-images.githubusercontent.com/32833996/37040473-3871ac94-215a-11e8-9db0-573e121375ea.jpg)

![live_primary_co2](https://user-images.githubusercontent.com/32833996/37040477-3a0d9892-215a-11e8-9701-5bc3ac63650d.jpg)

**Comment by ChaelKruip** [comment]
> I.e. the carrier non_biogenic waste has a non-zero co2_conversion_per_mj on beta.

Making a scenario on BETA and LIVE without non_biogenic waste should give you the same result! Can you show that this is the case @marliekeverweij @michieldenhaan?

**Comment by marliekeverweij** [comment]
Yes this is the case! There is only a minor difference of 0.00326 MT

![live](https://user-images.githubusercontent.com/32833996/37043139-3260cb9a-2160-11e8-8c02-63ea12a9de54.jpg)
![beta](https://user-images.githubusercontent.com/32833996/37043140-32613788-2160-11e8-9cd0-ab20ab7e166f.jpg)

**Comment by ChaelKruip** [comment]
> Yes this is the case! There is only a minor difference of 0.00326 MT

Great work! Closing this.
