### ISSUE TITLE
Saved scenario list should exclude scenarios for nonexistent datasets

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2699]
![image](https://user-images.githubusercontent.com/19907658/37041794-5090b04c-215d-11e8-91c7-e6d8682e33f2.png)

**Comment by DorinevanderVlies** [comment]
@antw and @grdw please re-assign if appropriate. 
Can this be an effect of recent imports or is something else going on?

**Comment by DorinevanderVlies** [comment]
notifying @michieldenhaan

**Comment by antw** [comment]
This is because `rivierenland` was renamed to `om_rivierenland`. I have updated the affected scenarios to fix the immediate problem, but will leave this issue open because it's not right for a deleted dataset to be able break this page.
