### ISSUE TITLE
Slide texts are missing for both flexibility cost slides

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2700]
![screen shot 2018-03-07 at 10 55 34](https://user-images.githubusercontent.com/4669028/37085770-32fd9d12-21f6-11e8-818c-b35b547e2953.png)

**Comment by jorisberkhout** [comment]
And so are the tooltips.

![screen shot 2018-03-07 at 10 57 18](https://user-images.githubusercontent.com/4669028/37085831-5b4c4250-21f6-11e8-80fb-9b0cf26733d8.png)

**Comment by jorisberkhout** [comment]
Assigning @marliekeverweij . Reassign at will.

**Comment by marliekeverweij** [comment]
![screen shot 2018-06-19 at 12 30 06](https://user-images.githubusercontent.com/32833996/41592335-8b087bb8-73bc-11e8-96b4-22378b28d30f.png)
