### ISSUE TITLE
Not possible to create an account with two "." behind "@" of e-mailadres

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2704]
A user tried to create an account with the e-mailadres with the following syntax: xx.xx@yy.yy.com. However he received the message that the e-mailadres is not valid.

My assumption is that the double "." behind the "@" gives an error. 

Notifying @grdw and @ChaelKruip

**Comment by antw** [comment]
I can register an account with `xx.xx@yy.yy.com` as the e-mail address without any problem. Is there any chance you know the exact message that was shown?

**Comment by DorinevanderVlies** [comment]
Closing as it turns out to be false alarm by this user.
