### ISSUE TITLE
How do we deal with the circularity of electricity use for carbon capture?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2705]
@marliekeverweij and I had the following question: 

Power-to-kerosene uses excess electricity. The amount of carbon needed, therefore depends on the amount of excess.
At the same time, extracting carbon uses electricity:

![image](https://user-images.githubusercontent.com/1303760/37083309-6bb9f45e-21ef-11e8-9467-56ff4813ce1a.png)

This extra electricity demand could (severely?) reduce the excess used in step 1. Is this a problem @antw @jorisberkhout?

**Comment by antw** [comment]
> This extra electricity demand could (severely?) reduce the excess used in step 1. Is this a problem?

Isn't this just a conversion? The amount of "excess" electricity wouldn't change, what would change is how it is used. For example, if 40% of the excess is used to extract carbon and 60% to convert to kerosene:

```
<-- "loss" (C extraction) [0.4] --  +-----+
                                    | P2L |  <- excess electricity [1.0]
             <-- kerosene [0.6] --  +-----+
```

**Comment by ChaelKruip** [comment]
> The amount of "excess" electricity wouldn't change, what would change is how it is used. 

I thought that the `bunkers_flexibility_p2g_electricity` node would receive X PJ of electricity and would produce Y PJ of hydrogen. To make kerosene from that hydrogen, an additional amount of electricity is needed to produce the needed carbon_monoxide. @antw are you telling me that the excess is partially re-allocated to also cover the production of the carbon_monoxide? That would be a very nice solution indeed!

**Comment by antw** [comment]
> are you telling me that the excess is partially re-allocated to also cover the production of the carbon_monoxide? That would be a very nice solution indeed!

No, I'm misunderstanding the graph. 😇

I see the problem now: producing more hydrogen for conversion to kerosene also increases demand on the electricity network. Merit does not (and probably cannot) know about this increased demand. Merit and the ETEngine graph therefore become inconsistent.

I'm not sure how we can solve this. The obvious answer is to siphon off some of the P2G electricity for use in the kerosene and CO nodes. but I expect that is really tricky due to the losses and conversions in those nodes.

**Comment by jorisberkhout** [comment]
Adding to the milestone for the upcoming CCS project.

**Comment by michieldenhaan** [comment]
No longer relevant with: https://github.com/quintel/etengine/pull/1134
