### ISSUE TITLE
Domestic planes use no energy for local datasets 

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2706]
When testing for the deploy I found this bug: the energy demand for passenger transport goes to 0 when all passenger transport is by domestic plane. This only happens for local datasets.
![image](https://user-images.githubusercontent.com/308563/37096234-4d18b688-2218-11e8-9889-e436d17cf1d5.png)

The cause is the fact that the slider group for Domestic aviation technology does not add up to 100% or even initialize to anything:
![image](https://user-images.githubusercontent.com/308563/37096256-5be7e936-2218-11e8-8450-d92d037a2055.png)

Setting these sliders gets the energy use for passenger transport back up from 0:
![image](https://user-images.githubusercontent.com/308563/37096319-96b42b24-2218-11e8-80b9-5d0077a99561.png)

**Comment by michieldenhaan** [comment]
Nice catch! Probably because all air plane carriers are zero in 2015:
![energytransitionmodel httpsengine energytransitionmodel com 2018-03-07 15-34-46](https://user-images.githubusercontent.com/32056448/37098074-4279e54e-221d-11e8-8414-c05f6cf19758.png)

Not sure what's the proper way to fix this tho.. @antw, @grdw any ideas?

**Comment by antw** [comment]
> Not sure what's the proper way to fix this tho.. @antw, @grdw any ideas?

The common practice – when not providing default shares for the edges in ETSource – is to set one of them to `type=flexible` instead of `type=share`. That way, when all the other edges have a share of 0% the flexible edge will automatically be 100%.

**Comment by michieldenhaan** [comment]
Thanks! See: https://github.com/quintel/etsource/pull/1597
![energy transition model - your free independent comprehensive fact-based scenario builder httpetmodel test 2018-03-07 16-50-05](https://user-images.githubusercontent.com/32056448/37102211-a2306dbe-2227-11e8-8acd-dba587f4a2e5.png)
