### ISSUE TITLE
Inconsistency: the new HT heat pump for heat networks has no network impact for HH sector.

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2708]
The new heat pump for district heating in HH and Buildings is a welcome improvement. What is inconsistent though, is that it has no impact on the shape of the dynamic electricity demand curve, whereas the other electric heat pumps in households do.

I suppose this means we need to add timecurves for the heat demand on the district heating network?

![image](https://user-images.githubusercontent.com/308563/37114941-099cd4ac-224a-11e8-80d0-c5f007bf97fd.png)

This is not urgent, but still an issue I would like to point out to @michieldenhaan @DorinevanderVlies and @ChaelKruip. I suppose this is also relevant to the network calculation, @jorisberkhout and @MartLubben 

Reassign as you see fit

**Comment by MartLubben** [comment]
Checked it with @ChaelKruip, and we can close it. 

![screen shot 2018-06-25 at 12 07 07](https://user-images.githubusercontent.com/33415156/41844376-50df3c20-7870-11e8-8c30-c22d2593dce9.png)
![screen shot 2018-06-25 at 12 06 22](https://user-images.githubusercontent.com/33415156/41844378-5101742a-7870-11e8-962d-c1ba7089ac12.png)
