### ISSUE TITLE
Final demand households per utility chart has illogical order of series - fix please

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2709]
This chart is a huge improvement, but I do not much like the fact that there does not seem to be any logic to the order in which the applications are shown:
![image](https://user-images.githubusercontent.com/308563/37115333-236a9c9c-224b-11e8-9daf-23d194d04caa.png)

The order is not alphabetical, nor is it increasing or decreasing share of final demand in 2015, nor is it a sensible grouping of different kinds of final demand, like heating, hot water, cooling, cooking, appliances and lighting or something like that.

To me, this makes the chart look a bit ugly. ANY order would improve it IMO. Perhaps share of final demand in 2015 is best? 
What do you think @ChaelKruip and @MartLubben?   

Reassign as you see fit.

**Comment by AlexanderWirtz** [comment]
Also while we are fixing this chart, please rename the English version:

Final demand households per utility —> Final demand households per application

'Utility' often means something like the electricity and gas company in English and is therefore confusing in this context.

**Comment by MartLubben** [comment]
@AlexanderWirtz I agree. 

Some possibilities:
Alphabetic 1:
![screen shot 2018-03-08 at 09 15 12](https://user-images.githubusercontent.com/33415156/37140234-4e04298a-22b1-11e8-836a-9fd492b8cea3.png)

Alphabetic 2:
![screen shot 2018-03-08 at 09 17 39](https://user-images.githubusercontent.com/33415156/37140334-a1fa7c42-22b1-11e8-8fbd-1be9fbbe2c97.png)

Size:
![screen shot 2018-03-08 at 09 20 17](https://user-images.githubusercontent.com/33415156/37140452-092db0c8-22b2-11e8-9bdb-98f70d5fe32a.png)

I am most convenient with the last one. It directly shows the most relevant targets for energy reduction.

**Comment by ChaelKruip** [comment]
> I am most convenient with the last one. It directly shows the most relevant targets for energy reduction.

Aesthetically speaking, I think the last one should be reversed with the largest series on the bottom. Perhaps I am alone in this but I'd like to voice my (strong) preference for that option.

**Comment by MartLubben** [comment]
@AlexanderWirtz I have changed the names and the keys to application: https://github.com/quintel/etmodel/pull/2711/commits/2145501bccbc80e4a47fe85d5b027d41f2cbb2f9 

@ChaelKruip I do not have a strong opinion about the aesthetic difference, but as a birthday present you can choose :).

![screen shot 2018-03-08 at 09 48 40](https://user-images.githubusercontent.com/33415156/37141621-ec7631e0-22b5-11e8-81e5-fa0ef37cb528.png)

Is everyone agreeing?

**Comment by AlexanderWirtz** [comment]
I like the same version @ChaelKruip likes! Thanks Mart!
