### ISSUE TITLE
Scaling a scenario does not work on beta

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2713]
Scaling is currently not working for both a national and a local dataset

@antw please reassign if appropriate
notifying @grdw and @ChaelKruip

**Comment by antw** [comment]
Working fine here. I tried scaling a blank NL scenario, a saved scenario, and a local dataset scenario
 (Gelderland) and all three worked as expected. 😳

Could you give it another go and note down each step you take? (which dataset used, end year, the scaling values chosen)

---

**1. NL scenario:**

![screen shot 2018-03-08 at 14 05 24](https://user-images.githubusercontent.com/4383/37155128-fa35d2d0-22d9-11e8-839c-5c9692901a0b.png)

**2. Scaling screen:**

![screen shot 2018-03-08 at 14 05 36](https://user-images.githubusercontent.com/4383/37155155-0c0ab0de-22da-11e8-81bb-3189e67b2809.png)

**3. Scaled scenario:**

![screen shot 2018-03-08 at 14 05 48](https://user-images.githubusercontent.com/4383/37155165-12307bec-22da-11e8-8980-e080ca22afe9.png)

**Comment by DorinevanderVlies** [comment]
The error occurs right after clicking "scale this scenario". I attached a screen recording of me trying to scale a scenario on the beta server.
[Issue scaling copy.zip](https://github.com/quintel/etmodel/files/1793440/Issue.scaling.copy.zip)

**Comment by grdw** [comment]
I'm also unable to reproducte this. Does it have to do with '[dronten](https://quintel.airbrake.io/projects/35333/groups/2164621577744833512?tab=overview)'?

**Comment by antw** [comment]
This should be fixed by 0e98e17. @DorinevanderVlies when you have time can you confirm that this is the case?

**Comment by DorinevanderVlies** [comment]
Fixed indeed! Thanks @antw
