### ISSUE TITLE
Number of units capped in local datasets

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2717]
The max value of a lot of power plant sliders is capped to very low numbers in local datasets. As a result, virtually all local datasets with a big plant have a higher number of units than the slider allows for. E.g. Rotterdam (actual number of units is 2.375):
![energy transition model - your free independent comprehensive fact-based scenario builder httpetmodel test 2018-03-09 17-30-20](https://user-images.githubusercontent.com/32056448/37218040-94ebd776-23bf-11e8-8c64-15a502e8e799.png)

This seems to have something to do with the max value being dependent on total production.
Is it possible to make the max number of units for local datasets equal to their parent dataset maximum (except for the ones depending on area attributes such as wind and solar)? Tried to add `#` to `` UNSCALEABLE_INPUT_UNITS`` in the Engine but that didn't work.

**Comment by michieldenhaan** [comment]
Set the 'minimum maximum' to 5 now for all power plants (except solar/wind). This should be enough for local situations. See: https://github.com/quintel/etmodel/issues/2717.

**Comment by michieldenhaan** [comment]
Reopening because the slider caps are still a constraint for some scenario's (in flexibility for example).
Currently a lot of slider maximums depend on the present value of ``Q(total_electricity_produced)``. Since mainly local datasets barely have any electricity production in the present, the maximum is often too low. Shall I change this to ``DIVIDE(Q(total_electricity_consumed)``?

Notifying @ChaelKruip

**Comment by ChaelKruip** [comment]
> Shall I change this to DIVIDE(Q(total_electricity_consumed)?

I like that!
