### ISSUE TITLE
Final demand households chart translation missing in LIVE

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2719]
Hey @antw, 

In the live a translation is missing. It is ok in the beta-. It is solved with this pull request. https://github.com/quintel/etmodel/pull/2711

Probably it happened when you've deployed the new front-end, but without the updated ETModel. 

![screen shot 2018-03-13 at 09 03 14](https://user-images.githubusercontent.com/33415156/37329271-6e116b3a-269d-11e8-80de-bbad2f5bdb7f.png)

**Comment by antw** [comment]
Thanks! Fixed on the production branch.
