### ISSUE TITLE
Legend of mekko charts

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2724]
For the hydrogen project I have created a mekko showing the demand and supply of the hydrogen network: 
![screen shot 2018-03-14 at 12 22 44](https://user-images.githubusercontent.com/32833996/37399798-2231f0cc-2783-11e8-949f-da03014d4d7c.png)

Recently we had changed the order of the legend items for charts in #2562 . Now the legend items go from L → R and from top → bottom.  

![screen shot 2018-03-14 at 12 25 33](https://user-images.githubusercontent.com/32833996/37399989-a94315fa-2783-11e8-8836-b4f567dd9e3d.png)

However, I see that this is not completely done for mekkos yet (only for vertical stacked bars and beziers I think). For mekkos L → R is done, but not top → bottom.

@grdw , could you maybe also change the order of the legend items for mekkos the same way as you did for the other charts? And I would also prefer if there are two columns with items and not three columns.

**Comment by grdw** [comment]
![screen shot 2018-04-04 at 10 31 44](https://user-images.githubusercontent.com/2676542/38296998-63e5ea3e-37f3-11e8-87dc-3f85ea9b5a09.png)

Including @jorisberkhout in the abscence of @marliekeverweij  - This is what it's going to look like when there's no Hydrogen? I don't know what is not there 'energy-wise' so the translation might need some adjustments. 

Also - this can only be applied to **all** mekko charts. So therefor - mekko's that can become empty need a translation for when it does become empty.

**Comment by michieldenhaan** [comment]
Looks good! Maybe change the text to 'There is no hydrogen supply and/or demand in this scenario'

**Comment by grdw** [comment]
https://github.com/quintel/etmodel/pull/2757 would it be okay if I let you - @michieldenhaan - take care of this? 👍

**Comment by AlexanderWirtz** [comment]
@grdw is @marliekeverweij 's orignial question clear?

**Comment by grdw** [comment]
> is @marliekeverweij 's original question clear?

You mean the one about the actual ordering? I think so yes, and I also know I'm confusing this issue with another 😕 https://github.com/quintel/etmodel/issues/2744

**Comment by grdw** [comment]
Back to the original issue:

> could you maybe also change the order of the legend items for mekkos the same way as you did for the other charts? And I would also prefer if there are two columns with items and not three columns.

I think the closest I am able to get - while keeping the original drawing of the legend items in tact - is like this:

![screen shot 2018-04-06 at 09 50 51](https://user-images.githubusercontent.com/2676542/38409008-04fa3780-3980-11e8-8cd2-8829a38838e0.png)

What do you think @marliekeverweij (or @jorisberkhout in this case or @AlexanderWirtz or somebody else with an opinion?)

**Comment by grdw** [comment]
Fixed by https://github.com/quintel/etmodel/pull/2757
