### ISSUE TITLE
Scenario report print as PDF - missing icons

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2727]
![screen shot 2018-03-15 at 16 09 03](https://user-images.githubusercontent.com/2676542/37471979-3f7c9b58-286b-11e8-80d1-7dc1af6171e1.png)

When I save the scenario report as a PDF, all the icons are missing from the PDF. Not the charts though. My first guess - knowing PDF rendering - would be that the images miss the full url (instead of a relative one) a bit in the same line as a mailer.

**Comment by antw** [comment]
How was this being converted to PDF? The PDF download is currently disabled, so I'm guessing based on the missing background color for the header that this was something like "Print → Save as PDF" in something *other* than Chrome or Safari?

Webkit browsers get `-webkit-print-color-adjust: exact` to ensure that backgrounds (images and colours) are printed, but other browsers don't have an equivalent. I suppose we could replace most of the background images with [`<img alt="" />`](https://www.w3.org/WAI/tutorials/images/decorative/) tags instead.

**Comment by grdw** [comment]
This is in the most recent version of Firefox. And indeed, I hit the print button and do a "Print as PDF". I think Chrome actually is doing this correctly, just like Safari - so maybe this is a Firefox-only issue.
