### ISSUE TITLE
Remove oil-fired and coal-fired heaters from paper industry

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2728]
As we are now adding H2 burners to many industrial subsectors, @AlexanderWirtz and I saw that some sectors have many heaters and we think some can be deleted. For example the oil-fired and coal-fired heaters from the paper industry (and maybe also from the food industry?):

![screen shot 2018-03-16 at 14 00 12](https://user-images.githubusercontent.com/32833996/37521884-77f946b8-2922-11e8-8c08-49314e99c819.png)

What do you think @Joris?

**Comment by AlexanderWirtz** [comment]
The same goes for the food sector, IMO

**Comment by ChaelKruip** [comment]
> The same goes for the food sector, IMO

Check: is there oil/coal use in these sectors in other countries? Sometimes you need a node to accommodate an energy flow which is non-existent in NL.

**Comment by AlexanderWirtz** [comment]
Good idea to check this. I checked several other countries and alas, demand for certain types of coal and oil derivatives are non-zero in Belgium, Germany and some others. They are VERY small, but non-zero. 

In this case, perhaps we could come up with a different ordering logic for the sliders?

Such as: 
- burners in order of direct CO2 emissions
- electric heaters and heat pumps
- CHPs
