### ISSUE TITLE
Factsheet supply total doesn't add up

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2729]
The total of chart 2 is larger than the sum of its parts (37,437 vs. 40,147):
![energietransitiemodel - je eigen onafhankelijke volledige en op feiten gebaseerde energiescenario httpsbeta-pro energytr 2018-03-19 11-24-43 1](https://user-images.githubusercontent.com/32056448/37590320-341efe40-2b68-11e8-8081-98b461f598dc.png)

**Comment by antw** [comment]
Looks like the chart is missing a `factsheet_supply_heat_from_electricity` series which is part of the `factsheet_total_supply` query. Should this be added?

**Comment by ChaelKruip** [comment]
> Looks like the chart is missing a factsheet_supply_heat_from_electricity series which is part of the factsheet_total_supply query. Should this be added?

I think @michieldenhaan removed it on purpose but *forgot to remove it from the total query*. I expected the total to be generated automatic looking at [these lines](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/factsheet/charts.js#L58-L62).

I am in the train now, @antw could you remove the electricity query from the total query please?

**Comment by antw** [comment]
> I am in the train now, @antw could you remove the electricity query from the total query please?

Done.
