### ISSUE TITLE
Year selector is broken

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2734]
![image](https://user-images.githubusercontent.com/1303760/37645499-5481dd82-2c27-11e8-85fe-be8667c8bf9b.png)

**Comment by MartLubben** [comment]
Yes I found the same only Chrome, with Firefox it is normal.

**Comment by grdw** [comment]
That's odd. 🤔 

![screen shot 2018-03-21 at 10 26 01](https://user-images.githubusercontent.com/2676542/37702262-49f91378-2cf2-11e8-8961-2e06d609d0fa.png)

I actually got this working.

This is on Chrome Version 65.0.3325.162 (Official Build) (64-bit)

Which version do you use?

**Comment by ChaelKruip** [comment]
> I actually got this working.

I cannot reproduce this. Closing.

**Comment by MartLubben** [comment]
I still have the issue: Chrome: Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by MartLubben** [comment]
It is on the beta- and I updated Chrome: Version 65.0.3325.181 (Official Build) (64-bit), however it is still looking the same.

**Comment by MartLubben** [comment]
![screen shot 2018-03-21 at 11 20 17](https://user-images.githubusercontent.com/33415156/37704705-df5771d8-2cf9-11e8-86a5-d80c20b4b1c2.png)

**Comment by grdw** [comment]
Could you show me the output of your console? So if you go to `Developer Tools -> Console` in your browser.

**Comment by MartLubben** [comment]
![screen shot 2018-03-21 at 15 46 40](https://user-images.githubusercontent.com/33415156/37716555-15e3a940-2d1f-11e8-842b-101d19948c98.png)

**Comment by grdw** [comment]
Reproduced by John. Still not sure how this can come about. Even going back as far to Safari 8.1 in Browserstack doesn't give the same result. 

If somebody knows how exactly to reproduce this, I'd like to hear it.

**Comment by grdw** [comment]
![screen shot 2018-04-16 at 09 27 38](https://user-images.githubusercontent.com/2676542/38795402-6c87b4c4-4158-11e8-9400-0494f0ca9d46.png)

_Google Chrome is up to date
Version 65.0.3325.181 (Official Build) (64-bit)_

I have the same version - but it looks completely different (this is also https://beta-pro.energytransitionmodel.com/). 

@ChaelKruip could you try and do a "Cmd + Shift + R" at `beta` and see if it looks any different?

**Comment by grdw** [comment]
Not sure if my fix works. Can somebody confirm that it might? @ChaelKruip yours is broken on `beta`?  This feels a bit like trying to hit a blind target. 😿

**Comment by jorisberkhout** [comment]
I did see this on Live yesterday. Couldn't reproduce it or catch any error messages because as soon as I hit `cmd` + `r` it appeared normal again.

**Comment by ChaelKruip** [comment]
>  @ChaelKruip yours is broken on beta? 

It seems fine at the moment. Closing this until it re-surfaces.

**Comment by grdw** [comment]
I know that @MartLubben is still having issues with it. Can you confirm?

**Comment by MartLubben** [comment]
Si 

![screen shot 2018-04-23 at 09 41 00](https://user-images.githubusercontent.com/33415156/39112987-7b2754c6-46da-11e8-84b3-226cf342f37b.png)

**Comment by grdw** [comment]
I've managed to fix it with https://github.com/quintel/etmodel/commit/80a1181186bed67b7152e7335311e82e2e1432b1 though. Just confirmed it @MartLubben 's computer.

**Comment by grdw** [comment]
I'm currently moving these 2 commits to production.
