### ISSUE TITLE
Create alert when hydrogen mekko cannot be shown

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2744]
When you open a new scenario no hydrogen is used or produced and therefore the hydrogen mekko looks like this:
![schermafbeelding 2018-03-23 om 20 42 02](https://user-images.githubusercontent.com/32833996/37850362-1f035828-2edb-11e8-9fb9-b18d4a9a6d22.png)

@ChaelKruip and I thought of the idea to show an alert here saying something like: 
_To view this information hydrogen needs to be produced or used somewhere in the model_

Just like now is done when the merit is not enabled:

![schermafbeelding 2018-03-23 om 20 42 43](https://user-images.githubusercontent.com/32833996/37850439-63b31576-2edb-11e8-884e-07e52847e5bf.png)

**Comment by ChaelKruip** [comment]
@antw is this much work?

**Comment by antw** [comment]
Something like this is supported already in the "excess events" chart when there are no excess events.

![screen shot 2018-03-29 at 14 15 53](https://user-images.githubusercontent.com/4383/38090833-b7f482bc-335b-11e8-8034-2ed42aaa97e6.png)

@grdw is probably in a better position to know how hard this is, but I can investigate as time  permits.

The only thing I'd add is that there are many charts which might benefit and I'm opposed to enabling it for only one or two charts or *types* of chart; it should be generic and supported on all of them. For example:

![screen shot 2018-03-29 at 14 14 45](https://user-images.githubusercontent.com/4383/38090975-121908da-335c-11e8-81ec-640e8ee8aa38.png)

**Comment by grdw** [comment]
Every chart has the ability to overwrite the `D3ChartView`, `is_empty` method which should be filled with logic (which will have to return a boolean value) - also it needs a translation. That's all. If everything is correct it should render a message displaying that it's empty.  😄
