### ISSUE TITLE
Merit-alert is shown even when merit is enabled

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2745]
Today @ChaelKruip and I were working in my local model and some merit tables/charts showed this message, even when the merit was enabled! I do not know if this only is an issue in a local model and not on BETA.....

![schermafbeelding 2018-03-23 om 20 42 43](https://user-images.githubusercontent.com/32833996/37850547-d2da8cfe-2edb-11e8-8868-381540910945.png)

**Comment by antw** [comment]
Reopening because I still experience this.

**Comment by ChaelKruip** [comment]
Could this be related @antw ?

![image](https://user-images.githubusercontent.com/1303760/46069527-02177f80-c17c-11e8-93d7-e9e9fd3c4baf.png)

**Comment by antw** [comment]
> Opening the model quickly at a time-resolved chart freezes the dashboard.

Was this either immediately after refreshing the page, or by following a link directly to the hydrogen slides? If so, it's possible that the two are related.

**Comment by ChaelKruip** [comment]
> Was this either immediately after refreshing the page, or by following a link directly to the hydrogen slides? If so, it's possible that the two are related.

By following a link directly to the hydrogen slides

**Comment by antw** [comment]
This has been fixed for D3 v6 charts. The v2 charts are still affected, but they'll be converted to v6 over time.
