### ISSUE TITLE
Profitability chart for dashboard item pop-up looks very ugly

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2750]
![image](https://user-images.githubusercontent.com/1303760/38076608-6a7fb8d2-3336-11e8-98ba-92f843fd3424.png)

**Comment by antw** [comment]
Are you able to reproduce this consistently? Although I don't see how this could affect anything, does it persist after providing a translation for the hydrogen turbine? Does it happen with a default scenario?

If it's still broken could you provide details of the branches, scenario, and browser being used?

It looks normal to me locally and on beta:

<img width="1100" alt="screen shot 2018-03-29 at 09 54 32" src="https://user-images.githubusercontent.com/4383/38079628-4d786440-3337-11e8-897e-abca3989310e.png">

**Comment by ChaelKruip** [comment]
On beta this still doesn't look ideal:
![image](https://user-images.githubusercontent.com/1303760/38864426-feb0f03a-423a-11e8-9359-762719129993.png)
