### ISSUE TITLE
Is it intended behaviour that the COP slider for HHPs for Hot Water affects the final demand for Space Heating?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2751]
COP = 1:
![image](https://user-images.githubusercontent.com/1303760/38079321-e704e6ea-333e-11e8-977d-4134cedd1a40.png)
 COP = 6:
![image](https://user-images.githubusercontent.com/1303760/38079340-f2dc3c2a-333e-11e8-9082-b3abdfafd0f6.png)

**Comment by ChaelKruip** [comment]
The effect is not big but you can see that the gas-use for the HHP in the left chart (space heating) decreases. I have not spent any time investigating further yet...

**Comment by antw** [comment]
This doesn't make intuitive sense to me, but the HHP isn't a very intuitive heat producer. The capacity of the HHP is shared between space heating and hot water, and space heating demands can also be deferred until later in the day. I think the most likely explanation is that the electrical component is being used to produce hot water, and space heating demands are therefore more frequently satisfied by gas.

I can debug this in more detail but it will take time. :smile:

**Comment by ChaelKruip** [comment]
> I think the most likely explanation is that the electrical component is being used to produce hot water, and space heating demands are therefore more frequently satisfied by gas.

I forgot about that! This seems to be what is going on indeed. Thanks. Closing for now.
