### ISSUE TITLE
Layout zoomed out CO2 factsheet

### ISSUE THREAD

**Issue by grdw** [quintel/etmodel#2755]
![screen shot 2018-04-03 at 10 17 46](https://user-images.githubusercontent.com/2676542/38237740-4aeed34a-3728-11e8-8417-f999f2ca75cd.png)

When zooming out the CO<sub>2</sub> factsheet in the browser, the layout will get distorted.

**Comment by jorisberkhout** [comment]
Removing my assignment as my technical skills are not up to this challenge. I am of course available for discussion.
