### ISSUE TITLE
CO2-Sankey seems broken for HH, perhaps also other sectors

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2760]
The CO2-Sankey does not agree with the CO2 emissions in an NL starting situation.

These are the CO2 emissions for a starting situation in the NL (2030):

![image](https://user-images.githubusercontent.com/308563/38358078-9b76d8b0-38c4-11e8-8c9d-d18576760a43.png)

Clicking through to the CO2 Sankey, we see almost no natural gas use and very low direct emissions in HH and buildings. that seems counterintuitive to me. I have a feeling this is due to groupings having changed. 

![image](https://user-images.githubusercontent.com/308563/38358112-b31b6ca6-38c4-11e8-8032-06c4d9ff88c0.png)

Re-assign as you see fit

**Comment by ChaelKruip** [comment]
Assigning @MartLubben to sharpen his GQL skills. Let me know if you run into problems!

**Comment by marliekeverweij** [comment]
Shall I pick this up as Mart is busy? Or is this not urgent at the moment?

**Comment by ChaelKruip** [comment]
> Shall I pick this up as Mart is busy? Or is this not urgent at the moment?

I think this would be nice to pick up in conjunction with

https://github.com/quintel/etmodel/issues/2795

I think the urgency is not very high but it would be great if this can happen somewhere in the next weeks depending on your time.

**Comment by MartLubben** [comment]
Hey all,
I found some queries which erroneously return '0' in the Sankey like: Q(households_gas_for_space_heating_in_co2_sankey) and Q(households_gas_for_hot_water_in_co2_sankey). 

This Sankey needs quite some revision and I am afraid that it will not be finished before the deploy.  Also, when we take the time to revision it, we could do it good. At this moment the Sankey is built for on the spot CO2 and the stacked bar shows the primary CO2 of a sector. It would be good if our CO2-factsheet, the stacked bar and the Sankey are consequent. 

I propose that we hide the Sankey now and then redesign it to be consequent with the CO2-factsheet and the stacked bar. The main questions are: 

1. What is the added value of the sankey next to the other overviews? 
2. What level of detail would we like to show in the Sankey?

**Comment by michieldenhaan** [comment]
Fixed in recent CCUS project
