### ISSUE TITLE
Hydrogen turbines slider gives NaN

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2763]
![image](https://user-images.githubusercontent.com/1303760/38468137-38bb7868-3b42-11e8-989f-807120ae78d1.png)

**Comment by ChaelKruip** [comment]
I think I found the issue. The FLHs for the hydrogen turbines are zero for the present year. 

The slider max is determined by:
```
present:MAX(1.0,PRODUCT(DIVIDE(Q(total_electricity_produced),V(energy_power_turbine_hydrogen,typical_electricity_production_per_unit)),2))
```

As the `typical_electricity_production_per_unit` method uses the  FLHs, this query returns NaN. 

@michieldenhaan will correct this tomorrow!

**Comment by michieldenhaan** [comment]
Fixed: https://github.com/quintel/etsource/pull/1663
