### ISSUE TITLE
Negative loads on networks not displayed correctly in charts

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2771]
On branch `new_network_calculation`. Net loads can be negative when there is more volatile production than demand. This is not displayed correctly in the new load charts.

![screen shot 2018-04-16 at 14 26 06](https://user-images.githubusercontent.com/4669028/38810798-201152d2-4188-11e8-9ddb-a64ca6b4546d.png)

**Comment by grdw** [comment]
Also few minor points:

- The space above the maximum of this chart is quiet big.
- `MW` is hiding under the ticks of the y-axis.

**Comment by antw** [comment]
![screen shot 2018-04-16 at 15 48 21](https://user-images.githubusercontent.com/4383/38816277-a13c1e64-418d-11e8-9f1b-7cb18caf14a8.png)

**Comment by antw** [comment]
Reopening because I also need to add this feature to the dynamic demand chart.
