### ISSUE TITLE
Include network costs for wind offshore and interconnector capacity in network table

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2772]
![screen shot 2018-04-16 at 15 53 39](https://user-images.githubusercontent.com/4669028/38813113-6e17113c-418e-11e8-92be-6b85ecbefeb2.png)

**Comment by marliekeverweij** [comment]
Do we still want this? Is this something I can do?

**Comment by jorisberkhout** [comment]
These two entries have been added to this table in the mean time, so this issue can be closed. The translations are still missing though, see https://github.com/quintel/etmodel/issues/2785. Could you pick up that issue if you have time, @marliekeverweij ? Closing the current issue.
