### ISSUE TITLE
Excess supply from wind turbines does not show up on HV network charts

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2773]
I have included a ridiculous amount of offshore wind turbines in my scenario which results in a excess electricity. This excess electricity should translate in excess load on the HV network which in turn, will partly be exported. Let's discuss how to go forward with this.

![screen shot 2018-04-16 at 16 23 36](https://user-images.githubusercontent.com/4669028/38814783-a5eef8aa-4192-11e8-9eb2-62bdd50d6139.png)

**Comment by antw** [comment]
![screen shot 2018-04-16 at 17 10 37](https://user-images.githubusercontent.com/4383/38821675-1c446b42-4199-11e8-8a6b-c648ddcb5745.png)
