### ISSUE TITLE
slider decimal places in local datasets

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2781]
In local datasets, some sliders have more decimal places than in country datasets / the step value specified in ETModel. This can be confusing: in the screenshot below the number of units of biogas CHPs can be interpreted as 31 thousand rather than 31.

![screen shot 2018-04-20 at 11 26 21](https://user-images.githubusercontent.com/32056448/39043652-418edaf2-448e-11e8-83a2-bc4abe7847ff.png)

In some cases this messes up the layout (the '2' of 'H2' is hidden behind the question mark):
![slack - quintel 2018-04-20 11-31-06](https://user-images.githubusercontent.com/32056448/39043700-61cb19ac-448e-11e8-8b7c-5d79b449c510.png)

**Comment by grdw** [comment]
How would you like to see this work? My suggestion would be is to leave it to an input itself to determine how the max and min's are rounded. If we take for example [this input](https://github.com/quintel/etsource/blob/master/inputs/demand/households/households_demand/households_useful_demand_lighting.ad), I'd think that the rounding might work as:

```ruby
- query =
    UPDATE(
      V(households_useful_demand_light), preset_demand, USER_INPUT()
    )
- priority = 0
- max_value = 5.0
- min_value = -5.0
- start_value = 0.0
- step_value = 0.1
- unit = %
- update_period = future
- update_type = %y
#####
- round = 2
#####
```

However, if it will *always* be just simply 2 digits behind the dot I'd like to know, as it will make the solution to this problem far more easy.

**Comment by michieldenhaan** [comment]
We already specify in ETModel how many decimal places we want to show. For local datasets, however, this setting is not respected. I don't think it's necessary to add an extra attribute, this issue would be solved if the sliders in local datasets display the same number of decimals as national datasets.
