### ISSUE TITLE
Table 223 (Electricity network capacity and peaks) needs translations

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2785]

**Comment by marliekeverweij** [comment]
I have added the translations for this table with help of @antw ; this is what is now on beta:

![screen shot 2018-05-29 at 16 42 27](https://user-images.githubusercontent.com/32833996/40666178-632e1f84-635f-11e8-8025-464815826559.png)

![screen shot 2018-05-29 at 16 42 16](https://user-images.githubusercontent.com/32833996/40666181-6536c6fa-635f-11e8-8fe4-68f458423f8d.png)
