### ISSUE TITLE
Coal plants cofiring biomass are not shown in plant-profitability-table

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2793]
I saw that the 'pulverized coal with co-firing' is not shown in the plant-profitability-table in the dashboard when it is installed. Is that on purpose or is it a bug?

![screen shot 2018-05-25 at 11 54 29](https://user-images.githubusercontent.com/32833996/40538606-779c7f7e-6012-11e8-82e1-e53cf0dc79ed.png)

It is included in the plant_profitability_table_view.coffee in ETModel:

![screen shot 2018-05-25 at 11 56 22](https://user-images.githubusercontent.com/32833996/40538707-b2681f00-6012-11e8-84d3-451dbdc563e7.png)

The same goes for the 'co-firing coal plant for district heat (CHP)'

**Comment by jorisberkhout** [comment]
Good question @marliekeverweij . I don't know the answer. Maybe @AlexanderWirtz can help?

**Comment by michieldenhaan** [comment]
It's because ``energy_power_ultra_supercritical_cofiring_coal.central_producer.ad`` wasn't in the ``merit_order_converters_for_dashboard`` group. Fixed that now
