### ISSUE TITLE
2016 datasets showing 2015 in ETmodel

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2794]
I've added datasets for Rotterdam and (a week ago) Friesland, both with ``analysis_year = 2016``. For some reason the charts in ETmodel show 2015 as the starting year.
Quering ``AREA(analysis_year)`` returns 2016. In addition, other 2016 datasets I've made earlier (e.g. Haarlemmermeer, all the Brabantse Delta datasets) do show 2016 in the charts..

![2015](https://user-images.githubusercontent.com/32056448/40550318-16adc254-603a-11e8-8014-b0f807ddbb2f.png)

**Comment by antw** [comment]
Fixed by clearing the ETEngine and ETModel caches.
