### ISSUE TITLE
Add entries and queries for peak demand on interconnector to table 223

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2800]
They are currently empty.

![screen shot 2018-06-01 at 17 26 16](https://user-images.githubusercontent.com/4669028/40848972-fcc6df4c-65c0-11e8-9a7e-60acffd759e7.png)

**Comment by MartLubben** [comment]
Done!

https://github.com/quintel/etmodel/pull/2809/commits/3d347d353bcf8d36e0b7586062287b44a4fb5049

https://github.com/quintel/etsource/pull/1739/commits/2dd8527ce0fbf12b83ed464e58360c92dbb0dbc7

![screen shot 2018-06-15 at 14 26 16](https://user-images.githubusercontent.com/33415156/41467806-1aa0065a-70a8-11e8-932e-17494128afab.png)
