### ISSUE TITLE
Should we keep the `Usage of networks` slider?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2801]
This slider was implemented as a quick fix. I think we can remove it.

https://beta-pro.energytransitionmodel.com/scenario/costs/infrastructure/usage-of-networks

**Comment by jorisberkhout** [comment]
I have heard no objections, so let's remove this. Assigning @MartLubben .

**Comment by MartLubben** [comment]
Fixing it with https://github.com/quintel/etsource/pull/1740 
Waiting for pull request to be accepted, then removing the slider in the front-end.

**Comment by MartLubben** [comment]
Fixing it with quintel/etsource#1740 and removed
