### ISSUE TITLE
CO2-factsheet does not load properly on Internet Explorer

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2802]
During a workshop the CO2-factsheet did not load properly on Internet Explorer

Notifying @jorisberkhout

**Comment by antw** [comment]
Can't reproduce this myself. I've tested the factsheet with a couple of regions in IE10 and it loaded correctly. We don't support anything older than Internet Explorer 10 (which is already 5 years old).

If this happens again we would need to know:

* Which version of Internet Explorer is being used?
* Which operating system is being used?
* For which region is the factsheet being displayed?

The first two can be answered by visiting https://www.whatismybrowser.com/ and a link to the information can be copied:

![screen shot 2018-06-18 at 12 43 34](https://user-images.githubusercontent.com/4383/41534130-4efc94d2-72f5-11e8-97fd-1b348525d3ff.png)
