### ISSUE TITLE
Consistency of FLHs and peak capacity should be enforced

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2803]
The ETM is becoming more and more the ECTM, the Energy & Capacity Transition Model. Now that we show hourly load curves on infrastructure and for electricity and heat production, the quality of our profiles is much more visible then ever before.

Sorry, I'm going to sound a bit 'didactic' below but that is mostly to keep my own thinking straight. Also, please correct me where I am unclear or incorrect.

## Background

Energy and total installed capacity (P) are related by full load hours (FLH) by the following formula:
```
Energy [MWh] = P [MW] * FLH [hours]
```
The profiles carry information about all three:
![image](https://user-images.githubusercontent.com/1303760/40965490-230b92d4-68ae-11e8-9a9c-f86fe22faaef.png)
The hight of the profile is the instantaneous load (which, realistically/physically cannot exceed the installed capacity 'P'). The surface area under the profile represents the total (annual) Energy. 

### Special case: technologies that reach their max capacity

In the case of some technologies, the simultaneousness of their operation is very high. Think of heat pumps on a very cold day or wind turbines in a very windy hour. In such cases, the highest peak(s) in their profile will coincide with their total installed capacity P (as is the case for the profile shown above).

In this case, you know that the profile tells you which fraction of the installed capacity is running in every our. Dividing the profile through the total installed capacity (P) sets the peak(s) to 1:
![image](https://user-images.githubusercontent.com/1303760/40966723-8eca05b6-68b1-11e8-81ac-1c5dd0ddd8c9.png)
Now, the resulting profile is a direct representation of the 'capacity factor'. Adding up all values in this profile (integrating) gives you the full load hours (FLH). 

In other words: if you know that the peak(s) coincide with the installed capacity, the profile has an **intrinsic** number of FLHs.

NOTE: for most profiles you cannot do this as their related technologies might never perform at the installed capacity as an ensemble! Their profile will typically look like this:
![image](https://user-images.githubusercontent.com/1303760/40966971-32ef8eae-68b2-11e8-8e56-392ccd3daa31.png)

We need additional information (about simultaneousness) in order to find the 'intrinsic' FLHs for such profiles.

## The issue

We do regular updates of the energy data (FLH, installed capacities) but don't update the profiles accordingly. This may result in discrepancies.

### Case 1: peaks larger than installed capacity

We know something is wrong if there are peaks that exceed the (physical limit) of the installed capacity:
![image](https://user-images.githubusercontent.com/1303760/40967141-9d9d6a1e-68b2-11e8-87eb-7f7018b1b6ab.png)

This likely points to a problem with either the FLHs from the data-analysis (too high) or the shape of the profile (to peaked).

NOTE: The ETM currently does not check for this eventuality right @antw ?

### Case 1: peaks lower than installed capacity

![image](https://user-images.githubusercontent.com/1303760/40967257-e8f25f10-68b2-11e8-82c4-6ed778ed7f7e.png)

Here it is not obvious if this profile is correctly representing the behaviour of the technologies. As mentioned above, we would need additional information about simultaneousness of the technologies to asses the intrinsic FLHs of the profile and compare them to the datasets FLHs.

## Possible solutions

* Add checks in ETSource/Atlas/ETEngine? to see if Case 1 occurs
* Make the generation of profile a more integral part of the dataset analysis

Including @jorisberkhout @AlexanderWirtz @DorinevanderVlies @michieldenhaan @MartLubben @marliekeverweij

**Comment by jorisberkhout** [comment]
https://github.com/quintel/etsource/issues/912 addresses this very same issue, but only for must-run CHP's. I will close that issue, but it is worth having a look at the comments in that issue.
