### ISSUE TITLE
How to store (and scale) load profiles?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2804]
## Background 

See also https://github.com/quintel/etmodel/issues/2803

Currently, we store hourly load profiles scaled to have a total sum of 1/3600. The reason for this is that when you multiply them (every datapoint that is) with the total energy demand/production of the corresponding node in MJ, the height of the profile correctly reflects the load in MW. 

This works because the surface area under the profile represents the total annual energy in MWh and it holds that 1 MWh = 3600 MJ. 

In the context of the new FLH-sliders for solar PV and wind, it is desirable to store wind and solar profiles in a different format: normalised to the interval (0,1) where the highest peak(s) are equal to 1. This helps to linearly interpolate between profiles without having to pre-scale the baseline profiles.

## Possible approaches

1. Keep storing all profiles in the current format (sum = 1/3600)
2. Store all profiles in (0,1) format
3. Use a mixed approach: use (0,1) format for profiles that need to be interpolated, the old/current "1/3600 format" for all other profiles

### Option 1

Pro's:
* No work to change current methods and profiles

Con's: 
* For the interpolation curves (three types of wind, one solar), an extra scaling operation is needed every time the user touches the FLHs sliders. This has a negative impact on performance (8760 extra operations per profile)

### Option 2

Pro's
* Interpolation can be done without extra operation

Con's
* We need to migrate all profiles to the new format
* We need a somewhat different method for scaling all profiles to the correct energy/height. 
Currently we do this: Multiply each point of the curve (sum=1/3600) with the demand/production in MJ:
```
factor = MJ
```
What we need to do in the new situation: Multiply each point of the curve by demand/production in MJ **divided by 3600 * intrinsic_FLHs_of_profile**:
```
factor = MJ / (3600 * intrinsic_FLHs_of_profile)
```

This operation is not more complex or computationally demanding because each of the 8760 points still needs to be multiplied only once. The multiplication factor has a new component, however: the intrinsic_FLHs_of_profile.
Luckily, the intrinsic_FLHs_of_profile can be pre-computed for each profiles (it simply is the sum of the profile in (0,1) format).

### Option 3

Pro's:
* Current profiles can stay the same and the method for scaling them as well

Con's: 
* For the wind and solar PV profiles, we still need to take the steps described in 'Options 2'
* We need to maintain two types of storage and scaling with possible fallout and confusion

**Comment by ChaelKruip** [comment]
@antw @jorisberkhout do you have preference for one of the above options? Or other ideas?

**Comment by ChaelKruip** [comment]
I have a preference for option 2 BTW but you might have suspected that already 😉

**Comment by ChaelKruip** [comment]
Including @DorinevanderVlies @michieldenhaan @AlexanderWirtz @marliekeverweij @MartLubben

**Comment by antw** [comment]
> I have a preference for option 2

Me too. I'll mean more work in ETEngine (to precompute the FLH of each curve), but I like that it'll keep all the curves in a consistent format.

**Comment by AlexanderWirtz** [comment]
Option 2 is my favorite

**Comment by antw** [comment]
As we all seem to be on the same page, I'll get to work on the ETEngine changes needed to support this.

@ChaelKruip Provided we're not changing the *shape* of any profiles, I expect I can also write a script to renormalise all of the profiles in ETSource.

> Yes, perhaps this can be done every ETSource import (that is the only time that profiles might change)?

Indeed. The Merit library already caches profiles in production; I'll move that feature out of Merit into ETEngine so that we can also precompute and cache any metadata for the curve (for now, the intrinsic FLH).

**Comment by ChaelKruip** [comment]
> @ChaelKruip Provided we're not changing the shape of any profiles, I expect I can also write a script to renormalise all of the profiles in ETSource.

That would be nice. We're not planning to change the shape of the profiles. At least not right now.

> Indeed. The Merit library already caches profiles in production; I'll move that feature out of Merit into ETEngine so that we can also precompute and cache any metadata for the curve (for now, the intrinsic FLH).

👍

**Comment by ChaelKruip** [comment]
Closing this.
