### ISSUE TITLE
Let's remove the "under construction" warning from the network charts

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2806]
I think it is time to remove the "under construction" warning from the network charts
@antw how can I do that?
@jorisberkhout do you agree?

![image](https://user-images.githubusercontent.com/19907658/41355006-b4499746-6f20-11e8-87f6-f593a1f80e96.png)

**Comment by jorisberkhout** [comment]
You can do this through the admin interface of ETModel.

I would suggest to wait until we have done the deploy testing, which I will start doing now. Do have any objections to removing the warning by next Tuesday the latest @DorinevanderVlies ?

**Comment by DorinevanderVlies** [comment]
Ok, I'll put it on my todo-list for Tuesday

**Comment by marliekeverweij** [comment]
Rob wants to use some of these charts for in a presentation. These charts are now tested, right? So he could use them?

**Comment by jorisberkhout** [comment]
I have removed all 'Under construction' banners. Closing.
