### ISSUE TITLE
CO2-emissions of imported electricity should be dataset dependent

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2817]
### Current situation:
The carrier [imported electricity](https://github.com/quintel/etsource/blob/master/carriers/imported_electricity.ad#L4) has as attribute co2_conversion_per_mj =  0.1463888889

This carrier is dataset independent:
The sliders ([present](https://github.com/quintel/etsource/blob/master/inputs/flexibility/import_export/co2_emissions_of_imported_electricity_present.ad#lL7
) and [future](https://github.com/quintel/etsource/blob/master/inputs/flexibility/import_export/co2_emissions_of_imported_electricity_future.ad#lL7
)) define the start value of CO2-emissions of imported electricity based on the carrier.

However, the datasets also define `co2_emissions_of_imported_electricity_g_per_kwh` in the .ad files. This is currently not used and should be removed

### Fix for deploy
Make sure that ETSource - input, ETSource - datasets, ETSource carrier and ETDataset - carrier are all consistent

Suggestions:
- Remove `co2_emissions_of_imported_electricity_g_per_kwh` from .ad files

### Possible improvements:
Make the `imported electricity carrier` dataset dependent.
A similar apprach to the FCE analysis might work.

**Comment by MartLubben** [comment]
Removed attribute: https://github.com/quintel/etsource/commit/ca042c8caf56b566f3079f69d25c0c7889145205

Still open is the solution.

**Comment by michieldenhaan** [comment]
New issue: https://github.com/quintel/etsource/issues/1766
