### ISSUE TITLE
CCS slider should reduce the amount of CO/CO2 available for synthetic kerosene production

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2821]
**With no CCS**

![screen shot 2018-06-19 at 17 13 46](https://user-images.githubusercontent.com/4669028/41606601-547cf7ea-73e4-11e8-9fb1-710a74f62114.png)

**With CCS**

![screen shot 2018-06-19 at 17 13 57](https://user-images.githubusercontent.com/4669028/41606636-6d9508a8-73e4-11e8-834e-f6afdeba1824.png)

I tried fixing this myself by including the `INPUT_VALUE(industry_ccs_in_industry)` in the query that set the values for available CO/CO2, but realised that it is more complicated than this. Assigning @marliekeverweij .

**Comment by marliekeverweij** [comment]
I assume this should also be done before the deploy?

**Comment by ChaelKruip** [comment]
This is a temporary feature which is very obscure and used by at most three people. Not critical for the deploy. This will be properly fixed in the ccs project

**Comment by michieldenhaan** [comment]
Closed with: https://github.com/quintel/etengine/pull/1134
