### ISSUE TITLE
Power-to-heat is not displayed in the use of excess electricity chart

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2822]
When testing the flexibility options I found this issue:

![screen shot 2018-06-20 at 10 47 07](https://user-images.githubusercontent.com/32833996/41647715-5522ecc0-7477-11e8-9dfc-9b83b38c69d4.png)

**Comment by jorisberkhout** [comment]
Closed by quintel/etsource#1752 .
