### ISSUE TITLE
Import should be a participant in the merit order

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2826]
Using as 'marginal cost' the price of imported electricity. 

Currently, import is the 'last resort' option if not enough local production capacity is available. It would be much more realistic if import would occur based on cost/price instead. 

@antw can you make an estimate of how difficult/time consuming this change would be?

**Comment by antw** [comment]
This has been pushed:

* **ETEngine**: [`import-price` branch](https://github.com/quintel/etengine/tree/import-price)
* **ETSource**: [`import-price` branch](https://github.com/quintel/etsource/tree/import-price)
* **ETModel**: [`import-price` branch](https://github.com/quintel/etmodel/tree/import-price)

I added "Imported electricity" to the merit order table just to ensure that it was working correctly, but have not added it to any other table or chart. There may be others which need to be updated such as "Merit order capacities and marginal costs"; if not, I'll submit pull requests for the three branches.

![screen shot 2018-06-25 at 15 20 12](https://user-images.githubusercontent.com/4383/41859078-48d9d79c-7893-11e8-9128-c9bd82894865.png)

**Comment by ChaelKruip** [comment]
Great work @antw !

> There may be others which need to be updated such as "Merit order capacities and marginal costs"

That is the only one that I can think of really. No problem to add that later IMO.

**Comment by MartLubben** [comment]
I believe that this is fixed.
