### ISSUE TITLE
Should the load on the HV-net increase when excess electricity from offshore wind is converted into hydrogen?

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2829]
Due to the volatile peaks the network calculation module builds ~81,5 GW HV-net in the [National Steering scenario of NvdT 2017](https://beta-pro.energytransitionmodel.com/scenarios/873455), while CE Delft calculates ~11.6 GW max peak. 10GW difference can be explained by the fact that in NvdT some solar parks and wind turbines are connected to the MV-net. 

My question: How realistic are our assumptions that the whole HV-net is increased in capacity while in reality the hydrogen converters are probably close to the wind offshore?

This issue could explain the significant yearly cost difference of the electricity net between the NvdT scenario by CE Delft (8.9 billion) and the ETM (14.2 billion). 

Some supporting charts and a link to the scenario: https://beta-pro.energytransitionmodel.com/scenarios/873455 

![screen shot 2018-06-26 at 11 58 58](https://user-images.githubusercontent.com/33415156/41904704-60162158-7939-11e8-98a8-bf0ac1cc34a7.png)

![screen shot 2018-06-26 at 11 59 10](https://user-images.githubusercontent.com/33415156/41904692-57272ab0-7939-11e8-83b5-d76aa6b42a67.png)

**Comment by AlexanderWirtz** [comment]
@MartLubben this issue is not really actionable, is it? You have a point of course, but what do you suggest we do? Localizing electrolysers at landing sites for offshore wind or near wind- or solar parks would make a lot of sense, but I think turning that idea into a change to the network calculation is not trivial and would have to be taken up together with the TSOs and DSOs.

**Comment by MartLubben** [comment]
@AlexanderWirtz I wanted to document and share this issue with you and @jorisberkhout, because it is quite relevant. 

A possible solution is that we could add a slider which sets the % of local electrolysers. The amount of local electrolysers * their capacity could be reduced from the wind offshore peaks. I am not sure about the fallout. Maybe @antw or @ChaelKruip see some red flags.
