### ISSUE TITLE
Add scenarios for Brabant to Featured scenario list

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2833]
Victor, the customer of the Brabant project, asked us if we could add the two scenario's that we create with him to the list of featured scenario's. Specifically, he would like to add these two scenario's:
- https://pro.energytransitionmodel.com/scenarios/364762
- https://pro.energytransitionmodel.com/scenarios/368636

This would be the first time that we add a 'local' scenario to the featured scenario list, which I quite like as it supports our efforts to apply the ETM on a more local level. How do you feel about this, @AlexanderWirtz , @ChaelKruip , @antw , @DorinevanderVlies , @michieldenhaan , @MartLubben and @marliekeverweij ?

**Comment by MartLubben** [comment]
Great scenario's, so I do not see any problems. :)

**Comment by MartLubben** [comment]
@jorisberkhout I am adding them to the presets. Two relevant follow-up points:

1. How are we going to order the presets, now we have a regional scenario I have started a [basecamp discussion] (https://3.basecamp.com/3797409/buckets/6935869/messages/1160690485)

2. The [variation scenario] (https://pro.energytransitionmodel.com/scenarios/368636) has no description. @DorinevanderVlies and @jorisberkhout: What are the main deviations to the basis scenario?

**Comment by jorisberkhout** [comment]
Thanks @MartLubben ! Regarding your points:

1. I will respond to the Basecamp discussion
2. Good point. The variation scenario differs in only one aspect from the base scenario being that we assigned a share of wind offshore to the region, reducing the amount of onshore wind and solar PV plants needed.

I can supply the description for the second scenario. Could you send me the name of the ETSource branch that you will create / have created these preset scenarios on? I will then add the description there.

**Comment by MartLubben** [comment]
> Could you send me the name of the ETSource branch that you will create / have created these preset scenarios on?

ETSource branch: brabant_to_presets

**Comment by jorisberkhout** [comment]
@MartLubben , what is the status of this issue?

**Comment by MartLubben** [comment]
They are ready on the branch 'brabant_to_presets'. However I was waiting for a conclusion on the [ordering issue](https://3.basecamp.com/3797409/buckets/6935869/message_boards/961550622). 

They could be pushed to beta and then to LIVE. Without a conclusion they will first become a featured scenario.

**Comment by MartLubben** [comment]
Done and closed
