### ISSUE TITLE
Urgenda preset needs an update

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2834]
Now that imported electricity is a 'full-fledged' participant in the merit order (see https://github.com/quintel/etengine/pull/1020), the Urgenda scenario (on beta) no longer meets its CO2 and renewability goals. This is because imported electricity is now one of the cheapest options in the merit order, pushing green gas turbines to the right:

![energy transition model - your free independent comprehensive fact-based scenario builder httpsbeta-pro energytransiti 2018-06-28 14-51-02](https://user-images.githubusercontent.com/32056448/42035215-b3590ace-7ae2-11e8-8fde-5675108171ec.png)

**Comment by MartLubben** [comment]
Possible solution is to put the import price on 121, see image. 

If the CO2 of imported electricity is lowered to 0, then it stil doesn't reach the renewability goal of >97%. When the interconnectivity is lowered, then it gets to much black out hours: ~170h/year. 

![screen shot 2018-06-29 at 13 44 05](https://user-images.githubusercontent.com/33415156/42090645-86630810-7ba2-11e8-9dff-3854f5cd4f03.png)

**Comment by MartLubben** [comment]
> How can this be? Is this a bug @MartLubben?

@ChaelKruip: As far as I know the renewability is based on the own production. For example, a region with 100% import of renewable electricity still has a renewability % of 0. Thus, import of renewables is not part of renewability in the dashboard.

I do not think it is a bug, but more a bookkeeping choice.

**Comment by ChaelKruip** [comment]
> I do not think it is a bug, but more a bookkeeping choice.

It's not a choice I have been consulted in and also not one that I agree with. The whole point of being able to choose the "CO2 of imported electricity" is to be able to de-couple the assumptions of the sustainability/climate impact of imported electricity from the local production park. It seems inconsistent to only apply this to CO2 but not to renewability.

@jorisberkhout @AlexanderWirtz are you aware of this choice? Curious about your opinions as well!

**Comment by MartLubben** [comment]
I am referring to [this basecamp discussion](https://3.basecamp.com/3797409/buckets/4288548/messages/780384582#__recording_787431555) in December. It is mentioned, although in hindsight it could be more explicit.

**Comment by DorinevanderVlies** [comment]
Closed with: https://github.com/quintel/etsource/pull/1835
