### ISSUE TITLE
Should the chart list have a search function?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2837]
As discussed in the [previous issue](https://github.com/quintel/etmodel/issues/2612) we thought that it would be nice to add a search-function to the chart list. Maybe in the upperright corner?

![screen shot 2018-06-29 at 14 04 46](https://user-images.githubusercontent.com/32833996/42091439-a6ef03a6-7ba5-11e8-81e7-59f97d11c915.png)

Let me know your opinions! @jorisberkhout @AlexanderWirtz @ChaelKruip @DorinevanderVlies @antw @MartLubben @michieldenhaan

**Comment by DorinevanderVlies** [comment]
Sounds like a good idea, I'm currently using "command+F" to search. A dedicated search-function would be nice!

**Comment by antw** [comment]
Coming after the flex charts are merged. 😮 

![Kapture 2020-12-08 at 12 33 42](https://user-images.githubusercontent.com/4383/101484495-a1864e80-3951-11eb-895f-ec9c46becebd.gif)
