### ISSUE TITLE
International transport final demand goes to zero when using synthetic kerosene

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2839]
Without synthetic kerosene production:

![energietransitiemodel - je eigen onafhankelijke volledige en op feiten gebaseerde energiescenario httpsbeta-pro energytr 2018-06-29 14-52-06 1](https://user-images.githubusercontent.com/32056448/42093353-573a98d2-7bac-11e8-9a40-4fd201ce7958.png)

With synthetic kerosene production:

![energietransitiemodel - je eigen onafhankelijke volledige en op feiten gebaseerde energiescenario httpsbeta-pro energytr 2018-06-29 14-52-20](https://user-images.githubusercontent.com/32056448/42093318-3132a7c4-7bac-11e8-8565-860fe4ddcdae.png)

Table view shows demand is zero for all carriers

**Comment by marliekeverweij** [comment]
Good catch :) I have added the `final_demand` group to the following edges and now the queries work:

`bunkers_final_demand_electricity-bunkers_kerosene_production_p2l@electricity
bunkers_final_demand_electricity-bunkers_p2l_direct_air_capture@electricity
bunkers_final_demand_electricity-bunkers_p2l_point_source_co@electricity
bunkers_final_demand_electricity-bunkers_p2l_point_source_co2@electricity
bunkers_final_demand_network_gas-bunkers_p2l_burner_network_gas@network_gas`

![screen shot 2018-06-29 at 15 26 22](https://user-images.githubusercontent.com/32833996/42094945-8591cba6-7bb1-11e8-9cb4-f6bf2fad695d.png)
