### ISSUE TITLE
Should energietransitiemodel.nl redirect to energytransitionmodel.com?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2844]
When browsing to http://energietransitiemodel.nl, I get redirected to https://energytransitionmodel.com. Given that most of our users are Dutch, I would prefer to not redirect to the English URL and leave the user on http://energietransitiemodel.nl

How do you feel about this, @AlexanderWirtz , @ChaelKruip , @ antw, @michieldenhaan and @MartLubben ? And how difficult would it be to change this, @antw ?

Also, https://energietransitiemodel.nl/ gives a certificate error. Can this be fixed easily, @antw ?

**Comment by AlexanderWirtz** [comment]
I like the Dutch URL. Is it possible to detect whether someone is visiting the page from a non-Dutch IP-address and redirect them to the .com site only in that case??

**Comment by antw** [comment]
I'm trying to remember why we standardised only on using the .com domain, but I'm coming up blank. It might be related to [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing), which restricts requesting resources across different domains (e.g. ETModel on .nl, ETEngine on .com, avoided by them both being on sub-domains of *.energytransitionmodel.com). I'm sure we can set this up so it's not a problem.

There's some other stuff which will need to be done on the servers first, so while I don't think this is difficult, it will take a little time.

> Is it possible to detect whether someone is visiting the page from a non-Dutch IP-address and redirect them to the .com site only in that case?

We can indeed do this. :+1:
