### ISSUE TITLE
Should CHP eletricity production follow the same profile as the heating demand?

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2860]
In a scenario with 100% heat network supplied by CHP's the electricity production does not  follow the same profile as the heat demand. There is a distinct production peak in the beginning of November which is not present in the heat demand curve.

![image](https://user-images.githubusercontent.com/19907658/45172113-a143f980-b204-11e8-9f66-206e4d992fb6.png)

![image](https://user-images.githubusercontent.com/19907658/45172165-d2242e80-b204-11e8-825b-20a043acec11.png)

@antw do you know why this is the case? 
Are the CHP's for the heat network controlled by Heat or in another way?

Not sure if this is a bug or something we are aware of, so using the "Question" label for now. 

Including @ChaelKruip

**Comment by ChaelKruip** [comment]
> In a scenario with 100% heat network supplied by CHP's the electricity production does not follow the same profile as the heat demand.

I'm afraid that we use CHP profiles which are not consistent with the temperature profiles of this year. The CHP profiles are based on a 'degree hour' approach where you take the difference between the thermostat temperature and the outdoor temperature per hour as a proxy for the heating demand. We probably haven't updated these profiles when we updated the rest of the dataset...

**Comment by DorinevanderVlies** [comment]
As the profiles for heating are flexible (depend on insulation level), just adding the right profile to CHP's will be an improvement, but not the solution for this issue.

Adding CHP's to fever will (I think) solve this issue

Adding all space heating related technologies to fever is part of the to be started "heat improvement" project. I added this milestone.

**Comment by marliekeverweij** [comment]
@DorinevanderVlies do you maybe know what the status of this issue is? I think that the CHP-profile hasn't changed during the profiles-project. 

I actually think it's not strange that the profile doesn't follow the household heat demand profile, as CHPs are not individual technologies.

**Comment by DorinevanderVlies** [comment]
This issue is already partly solved.

In the curves project we defined curves for:
* [Households space heating collective](https://github.com/quintel/etdataset/tree/master/curves/demand/households/space_heating_collective)
* [Buildings space heating collective](https://github.com/quintel/etdataset/tree/master/curves/demand/buildings/space_heating)

These curves are not related to insulation, but to respectively G1A and G2A. 

To be solved: not all collective heating nodes have the right merit_group assigned. Example: 
https://github.com/quintel/etsource/blob/512c64b5db24e2ae65805d9623e3a40d5ae64059/nodes/households/households_collective_chp_biogas.central_producer.ad#L9

See: https://github.com/quintel/etsource/pull/2054
