### ISSUE TITLE
When a dataset has no new residences it should be possible to set the slider households_number_of_new_houses

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2862]
Currently it is not possible to set the slider `households_number_of_new_houses` when a dataset has no new residences. A quick fix is to manually set new residences to a small value: https://github.com/quintel/etsource/pull/1801. 

@ChaelKruip do you think this issue should be picked up with urgency, or can it be part of the Gasunie warmte (heat) improvements?

notifying @ChaelKruip and @michieldenhaan

**Comment by antw** [comment]
I've opened an ETEngine issue to discuss possible workarounds for this: https://github.com/quintel/etengine/issues/1025.

**Comment by ChaelKruip** [comment]
> @ChaelKruip do you think this issue should be picked up with urgency, or can it be part of the Gasunie warmte (heat) improvements?

I made it part of the Heat improvement milestone.

**Comment by antw** [comment]
ETEngine will now prevent division by zero when using `DIVIDE`. This issue can be fixed by changing the input to use `DIVIDE`:

**No:** `a / b`
**Yes:** `DIVIDE(a, b)`

**Comment by marliekeverweij** [comment]
We are picking up this issue in the heat project, so I think it is a good suggestion to leave it for now 🙂

**Comment by DorinevanderVlies** [comment]
Closing this issue

**Comment by antw** [comment]
> I tried the above, but that doesn't seem to solve the issue completely.

It's been a while since I looked into this, but I seem to recall that the divide-by-zero occurs on one of the earlier lines.

**Comment by DorinevanderVlies** [comment]
> It's been a while since I looked into this, but I seem to recall that the divide-by-zero occurs on one of the earlier lines.

Thanks @antw 
I'm not sure. This change did enable me to set new households for a dataset without new households in the present.

I can be that the issue I'm now seeing (the demand does not increase when new houses are built) originates in the earlier lines. 

Taking into account that there this will be solved in the heat improvement project I still think it is not necessary to solve this now.

**Comment by antw** [comment]
> I'm not sure. This change did enable me to set new households for a dataset without new households in the present.

Yeah sorry... I edited my post, but too late for you to see it before replying. I re-read your earlier comment and realised you said the division by zero *was* fixed, but that demand remains at zero. There's [a task on Basecamp](https://3.basecamp.com/3797409/buckets/9242423/todos/1403043093) related to fixing that.
