### ISSUE TITLE
How to deal with multiple dataset versions of the same region?

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2865]
Recently we've added quite a few new dataset versions of areas already present in the ETM (e.g. Flevoland, Noorderplantsoen, Stichtse Vecht). Since these new versions are typically quite different from the old ones, I've kept both versions for now to avoid messing up existing scenario's (as discussed with @DorinevanderVlies and @jorisberkhout). The old datasets are hidden in the front-end. I think we should avoid having multiple dataset versions, especially if one version is considered to be an improvement of another.

One way to deal with this is the following:

- Hide 'old' datasets in ETModel (with ``- enabled.etmodel = false``) as soon as a better version becomes available. This means that non-Quintel users can no longer create new scenarios of old datasets.
- Delete old datasets every now and then when we think it's safe (e.g. go through the list of old datasets before every deploy)
- Migrate the ``area`` of 'deleted dataset' scenarios to new dataset ``area`` to prevent scenarios from breaking down completely

Curious to hear anyone's thoughts on this!
Notifying @ChaelKruip, @antw, @AlexanderWirtz

**Comment by ChaelKruip** [comment]
> One way to deal with this is the following

I like it! 👍
