### ISSUE TITLE
Overview issue: clean up other industry

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2871]
With https://github.com/quintel/etsource/pull/1822 the 'other industry' sector in ETModel is now the same for all datasets. Previously, some datasets had one slide for all 'other industry' sectors combined (``has_aggregated_other_industry = true``) while other datasets had three slides (one for food, paper, and one for the 'other' 'other industry' sectors, ``has_detailed_other_industry = true``).

This means we can clean up the following code:

- [x] Remove area attributes ``has_aggregated_other_industry`` and ``has_detailed_other_industry`` + references to these attributes in ETEngine, ETModel, ETSource

- [x] Remove all queries ending with ``_in_aggregated_other_industry_other_energetic`` and ``_in_aggregated_other_industry_other_non_energetic``.

- [x] Remove charts using above queries from database. These charts can no longer be accessed through ETModel. 

- [ ] Remove ``_nl`` suffix from all ``in_aggregated_other_industry_nl`` queries. These queries are no longer used exclusively for NL. Migrate the charts using these queries. Find/replace all occurrences of these queries.

- [x] Remove ``aggregated_other_industry_other`` group, rename ``aggregated_other_industry_nl`` group to ``aggregated_other_industry``. Find/replace all occurrences. 

- [x] Remove slide from database that was used for `other_industry_other`: `demand_industry_aggregated_other_other` and `demand_industry_other`. 

- [x] Rename slide `demand_industry_aggregated_other_nl` and `demand_industry_nl`

Feel free to edit/comment on this issue in case I forgot something.

Notifying @ChaelKruip, @antw, @marliekeverweij, @jorisberkhout

**Comment by marliekeverweij** [comment]
Good overview, thanks!

I have added one more thing: 
- [ ] Remove slide from database that was used for `other_industry_other`: `demand_industry_aggregated_other_other`(and rename `demand_industry_aggregated_other_nl`)
