### ISSUE TITLE
"Load scenario" gives error on Beta

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2874]
![image](https://user-images.githubusercontent.com/19907658/46093717-5b9d9f80-c1b8-11e8-82db-07a3920bf4ca.png)

**Comment by antw** [comment]
Which scenario(s)?

I'm guessing it's one whose region is "u10", [which no longer exists](https://github.com/quintel/etsource/commit/89788c40d1be46fb7c24cbee3b786045a079d92a#diff-a6530558856d3869a0931837ef0f6c29). Could those scenarios be transferred to a different dataset or is there no equivalent to "u10"?

I appreciate that the error message is worse than useless and could stand to be improved. 😞

**Comment by DorinevanderVlies** [comment]
Yes, I had an U10-scenario on my account. Deleting it solved the issue.
