### ISSUE TITLE
Danish dataset has higher FLH for solar than the Netherlands (or Germany)

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2890]
The Danish ETM shows this: 1141 FLH
![image](https://user-images.githubusercontent.com/308563/46725831-4bd48f80-cc7d-11e8-91ad-3009060e89d1.png)

The Dutch one this: 867
![image](https://user-images.githubusercontent.com/308563/46725902-77f01080-cc7d-11e8-8db9-f5e442c7f6b0.png)

I know we are farther south than Denmark and almost as windy, so I would expect the Netherlands to be roughly just as sunny or sunnier. Is this a bug or did something go wrong with the solar profile scaling?

The German dataset shows 1012 LFH:
![image](https://user-images.githubusercontent.com/308563/46726089-de752e80-cc7d-11e8-8f89-0467b21168d0.png)

The Dutch FLH are a scaled number as they take into account the ~15% system losses in PV systems. In reality there are about ~1000 full sun hours 

notifying @jorisberkhout

**Comment by antw** [comment]
Saying nothing about whether the numbers themselves are *accurate*, the calculation of FLH is correct:

```ruby
V(
  energy_power_solar_pv_solar_radiation,
  "demand / (input_capacity * number_of_units * 3600)"
)
```

DE: 1012
DK: 1140
NL: 867

**Comment by ChaelKruip** [comment]
This is not a bug IMO. The FLHs follow directly from the profiles and are indeed a bit counter intuitive. If this is an issue, it is a data quality one. 

Removing deploy milestone and bug label.

**Comment by AlexanderWirtz** [comment]
> If this is an issue, it is a data quality one.

I imagine it is an issue of understanding how FLH for countries are researched and then implemented in the datasets after we added the FLH sliders. Agree that it is not deploy-critical, but it is clearly incorrect. We seem to lack a good label for that (despite the fact that there are plenty to choose from).

**Comment by MartLubben** [comment]
This are the numbers directly from the Energinet Analysis Assumptions. 

![screen shot 2018-10-10 at 12 31 36](https://user-images.githubusercontent.com/33415156/46730515-a8897780-cc88-11e8-945b-8f24e36a09d0.png)

**Comment by AlexanderWirtz** [comment]
It is clear to me, that the way to implement FLH in the dataset is not transparent enough. @MartLubben let's pick this up after deploy.
