### ISSUE TITLE
Default costs for imported electricity are too low, IMO

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2891]
In all cases and all countries, the future electricity production is completely dominated by imports, as opposed to the present one. This suggests that 35 €/MWh is too low. I suggest moving it to at least 55 or 60 €/MWh (based on no research whatsoever).

I also suggest we limit the default availability of import and export interconnection to 50 or 75%

notifying @DorinevanderVlies @michieldenhaan @marliekeverweij and @jorisberkhout

**Comment by AlexanderWirtz** [comment]
This can probably wait until after deploy.

**Comment by ChaelKruip** [comment]
> I suggest moving it to at least 55 or 60 €/MWh (based on no research whatsoever).

> I also suggest we limit the default availability of import and export interconnection to 50 or 75%

Fine by me. @MartLubben can you make this happen today?

**Comment by ChaelKruip** [comment]
> This can probably wait until after deploy.

Sounds good. Removing deploy milestone.
