### ISSUE TITLE
Non-energetic demand in other industry should scale with industry size slider

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2893]
I increased the size of the other industry to 300% resulting in all carrier demands to increase by a factor of 3 except for the non-energetic demand that stays the same (see below). I think these non-energetic demands should scale with the relative size of the industry as well.

![screenshot 2018-10-11 at 10 56 24](https://user-images.githubusercontent.com/4669028/46792776-6887ca80-cd44-11e8-9eff-89a8bf9ffe2e.png)

**Comment by marliekeverweij** [comment]
Yes that is true! I'll fix it.
