### ISSUE TITLE
New, blank scenario for Germany shows different target lines for CO2 emissions

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2894]
I opened a new, blank scenario for Germany and did not set any targets for the CO2 emissions. To my surprise the CO2 emissions chart shows a target line. Even more interesting, the very same CO2 emissions chart shows different targets in different places of the model.

**Next to the Carbon capture and storage (CCS) slide (~0.8 GT)**
![screenshot 2018-10-11 at 11 06 49](https://user-images.githubusercontent.com/4669028/46793584-64f54300-cd46-11e8-8af9-6363008c9e5a.png)

**If I click on the CO2 emissions dashboard item (~0.65 GT)**
![screenshot 2018-10-11 at 11 12 07](https://user-images.githubusercontent.com/4669028/46793642-89e9b600-cd46-11e8-8938-0fcbf32435cf.png)

**In the table view of both charts (0 GT)**
![screenshot 2018-10-11 at 11 13 02](https://user-images.githubusercontent.com/4669028/46793809-d503c900-cd46-11e8-9c81-a0421749c3b5.png)

**Comment by ChaelKruip** [comment]
Well spotted! I have no clue how this is possible 😕 

@antw do you know how to even investigate this?
