### ISSUE TITLE
Proposal for restructuring flexibility sidebar item

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2896]
In [this discussion on Basecamp](https://3.basecamp.com/3797409/buckets/9225876/todos/1318485035) we thought of renaming the 'Electricity balance' tab to 'Flexibility' since this fits better in the energy transition narrative. When renaming this tab the names within the tab also need to change (since Flexibility is used there already) and I had some ideas of restructuring the sidebar items within the tab:

1. Renaming 'Flexibility' sidebar item to 'Excess electricity', because it is only about usage of excess electricity and not about using excess heat.
2. Taking 'Demand response' out of the 'Excess electricity' sidebar item since it not about excess electricity production, but a separate item.
3. Moving the information in the last four slides of import/export to the documentation because it contains a lot of very detailed text and it has no sliders.

-----------

Here a visualisation of the ideas, let me know what you think! @antw @ChaelKruip @jorisberkhout @DorinevanderVlies @michieldenhaan @MartLubben :

![screen shot 2018-10-16 at 17 00 07](https://user-images.githubusercontent.com/32833996/47026506-e8a79900-d165-11e8-93e5-801843c7f62d.png)

![screen shot 2018-10-16 at 17 00 17](https://user-images.githubusercontent.com/32833996/47026511-eb09f300-d165-11e8-9e9c-3e1196db3cb5.png)

![screen shot 2018-10-16 at 17 00 24](https://user-images.githubusercontent.com/32833996/47026528-f1986a80-d165-11e8-812f-cb25f85fa7c7.png)

Let me know what you think!

**Comment by ChaelKruip** [comment]
I like it a lot!

One extra thought: perhaps we should consider moving the Merit Order section to the Cost section? This has more to do with prices and marginal costs than flexibility IMO. 

Curious about your thoughts @AlexanderWirtz @DorinevanderVlies @jorisberkhout @michieldenhaan @MartLubben @marliekeverweij

**Comment by marliekeverweij** [comment]
Okay, we are going realise the above proposal as part of the time-resolved chart project. Including this:
> moving the Merit Order section to the Cost section

Please let us know when you have suggestions!

**Comment by marliekeverweij** [comment]
Now on beta :) we only need an icon for the demand response sidebar item, when you have inspiration....
