### ISSUE TITLE
Rename 'dynamic demand curve' to 'electricity demand per hour' ? 

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2897]
I think the name 'dynamic demand curve' does not really fit this chart, 'electricity demand per hour' would be better. Just like 'electricity production per hour'. What do you think @ChaelKruip ?

![screen shot 2018-10-18 at 17 04 27](https://user-images.githubusercontent.com/32833996/47164321-20dee100-d2f8-11e8-8873-5055bd7a75e5.png)

**Comment by ChaelKruip** [comment]
I agree!
