### ISSUE TITLE
The maximum value of the wind turbine & solar parks sliders should be set to the total area of a region

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2912]
@MartLubben, @michieldenhaan and I just had a discussion about the maximum value of the wind turbine and solar parks sliders. Currently the max values are based on a potential that can be set in the AREA-file with the attributes `land_available_for_solar` and `onshore_suitable_for_wind`. 

The disadvantage of this is that it prompts a lot of discussion while generating a dataset, especially when the dataset is generated together with a municipality. Another disadvantage is that it is a hassle to update it every time when the potential changes.

We propose to cap the sliders to the **total area of the region**. Then the discussion about available land will be postponed to the moment when the scenario is made and that would be better. Now the subject is discussed several times.

What do you think? @jorisberkhout, @DorinevanderVlies, @AlexanderWirtz, @ChaelKruip & @antw 

We also thought about capping the sliders on the available arable land, but in that case there is a chance that it is too limited; for example for cities like Amsterdam that have space for wind/solar in the harbour.

**Comment by DorinevanderVlies** [comment]
> We propose to cap the sliders to the total area of the region. 

:+1:

**Comment by AlexanderWirtz** [comment]
I am not necessarily opposed, but in my opinion it just postpones the inevitable discussion to a later moment. It will also allow users who are not aware to set an amount of production capacity that is physically not possible. That seems at odds with our intention of the ETM.

**Comment by DorinevanderVlies** [comment]
> That seems at odds with our intention of the ETM.

I'm not sure I agree with that.
The ETM allows many irrelastic settings (demolishing all houses, electric heat pumps in non-insulated houses, using loads of green gas, etc)

The difficulty about setting restrictions to settings is that opinions about these restrictions vary a lot. So when in doubt I would go a high max slider setting.

**Comment by ChaelKruip** [comment]
> So when in doubt I would go a high max slider setting.

I agree. The total area is a nice objective upper limit: if you demolish everything and only build wind turbines, this is what you can do.

**Comment by ChaelKruip** [comment]
> Currently the max values are based on a potential that can be set in the AREA-file with the attributes

How is this potential determined?

**Comment by michieldenhaan** [comment]
For some areas this is a researched number (e.g. from a GIS study from one of our partners). For most areas it is set equal to ``arable_land`` (which sometimes leads to problems as some areas have almost no arable land). I've had multiple requests tho to override specific researched numbers as they were deemed too 'limiting' in scenario sessions.

**Comment by ChaelKruip** [comment]
I say we change the potential to the total area. It's clear and well-defined and easy to research.

@marliekeverweij can you make this happen?

**Comment by marliekeverweij** [comment]
Yes I can!

**Comment by marliekeverweij** [comment]
@michieldenhaan and I just had a short chat about this issue and thought that it would not be safe to do this before the mini-deploy today, because we would like to test it first! 

Our proposal would be to delete the area-attributes `land_available_for_solar` and `onshore_suitable_for_wind` and add one area-attribute `total_area` on which the slider max is based. This would mean that the slider would always allow enough wind turbines / solar parks, no more discussions when creating datasets!  🎉 For national datasets it will then be possible to place an unrealistic high number of wind turbines / solar parks, but users can do more stupid stuff as Dorine mentioned above:
> The ETM allows many unrealistic settings (demolishing all houses, electric heat pumps in non-insulated houses, using loads of green gas, etc)

How to fix this issue:

- [ ] Delete area-attributes `land_available_for_solar` and `onshore_suitable_for_wind` and add area-attribute `total_area`
- [ ] Find data for all regional datasets (2 hr)
- [ ] Update ETLocal: remove `land_available_for_solar` and `onshore_suitable_for_wind` and add `total_area` (1 hr)
- [ ] Update all regional datasets (1 hr)
- [ ] Find data for all national datasets (0.5 hr)
- [ ] Update area analysis on ETDataset and update all country datasets (1 hr)
- [ ] Update input statements for `number_of_energy_power_wind_turbine_inland` and `number_of_energy_power_solar_pv_solar_radiation` (0.5 hr)
- [ ] Check for fall-out! {1.5 hr)

So this would cost about a day for one person!

Maybe we could integrate it in an upcoming development project, @ChaelKruip ?

**Comment by ChaelKruip** [comment]
> Maybe we could integrate it in an upcoming development project, @ChaelKruip ?

Yes. We are trying to make a project happen where the focus is to make the ETM more suitable for local energy transition.

**Comment by MartLubben** [comment]
I have an other opinion. For wind turbines I agree that the most logical input is a unit. For solar parks the discussion is more about the area or MW of the park. The current unit of 20 MW and 20-30 hectares creates a lot of confusion and extra preparation for a session. Would people agree to change it to MW input, just like we do in the hydrogen sector?

**Comment by marliekeverweij** [comment]
> I have an other opinion. For wind turbines I agree that the most logical input is a unit. For solar parks the discussion is more about the area or MW of the park. The current unit of 20 MW and 20-30 hectares creates a lot of confusion and extra preparation for a session. Would people agree to change it to MW input, just like we do in the hydrogen sector?

I will create a new issue for this, as your proposal is about the _unit_ of the slider and this issue is about the _max value_ of the slide.
