### ISSUE TITLE
The CO2-emissions compared to start year should be 0.0% in empty scenario

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2921]
Due to the calculation per hour of import of electricity for the future year we have sometimes more imported electricity in the future year than in the start year.  
![screen shot 2019-01-02 at 11 08 44](https://user-images.githubusercontent.com/33415156/50587653-0b04a500-0e7f-11e9-8880-f14dfb6c8e88.png)

This can result in quite a large increase in CO2 in the start year without a user touching any slider. 
![screen shot 2019-01-02 at 11 08 29](https://user-images.githubusercontent.com/33415156/50587678-21aafc00-0e7f-11e9-80fc-c626e52b09c1.png)

This can be quite confusing. Could it be an option to add the volume of calculated import in the (empty) future to the start year? We also have import now, and with the ETM we have quite a good guess how big it is. 

@ChaelKruip @antw @jorisberkhout @AlexanderWirtz @michieldenhaan @marliekeverweij  I am curious what you think.

**Comment by ChaelKruip** [comment]
I agree with @AlexanderWirtz that this is currently not feasible. Closing.

**Comment by MartLubben** [comment]
>Not an option, I’m afraid. The actual imports come from ETDataset and the
Extended Energy Balance. The higher imports in the future are a result of
the way imports are handled by merit (a fixed, low price) as opposed to
real market circumstances.

@AlexanderWirtz For regional scenarios with only wind and sun, we do not have the influence of merit in real life. Do we? Also we don't have the energy balance of a region. We need to do an estimate. In this case and in many other regional scenario's it is possible to do a better estimate than the sum of the yearly volumes. 

@ChaelKruip I still feel that this issue is not closed. Maybe we don't have a solution yet, but it is very relevant for workshops that in the starting situation nothing (major) is changed. Maybe wait for @michieldenhaan to come back.
