### ISSUE TITLE
Factsheet should be fixed 

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2933]
Currently the factsheet doesn't work on BETA and should be fixed before the deploy:

![screen shot 2019-01-30 at 16 45 07](https://user-images.githubusercontent.com/32833996/51993104-807b8980-24ae-11e9-8d48-351c02d2ac14.png)

**Comment by michieldenhaan** [comment]
To add to this, our new imported heat node should be added to the 'waste heat' category on the factsheet
