### ISSUE TITLE
Chart 172, 173 and 99 about flex options do not load

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2934]
![screen shot 2019-01-31 at 12 20 24](https://user-images.githubusercontent.com/33415156/52051180-0e10b500-2553-11e9-9eda-50035c1ab54d.png)

{"errors":["Gquery households_space_heater_micro_chp_network_gas does not exist","Gquery households_water_heater_fuel_cell_chp_network_gas does not exist","Gquery households_water_heater_micro_chp_network_gas does not exist"]}

**Comment by marliekeverweij** [comment]
Working again :)
