### ISSUE TITLE
ETFlex and Mobile game should be updated before deploy

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2936]
Because of the changes during the heat project ETFlex and the mobile game should be updated. At the moment they will most probably not work... I think this should be done before the deploy! Right @ChaelKruip ?

(I posted the issue here, because then we can use the Milestone ;) )

**Comment by ChaelKruip** [comment]
> I think this should be done before the deploy! Right @ChaelKruip ?

Yes! Can you try to fix thisn @marliekeverweij  and let me know if you run into troubles or questions?

**Comment by ChaelKruip** [comment]
We have decided to discontinue support for ETFlex and I suggest to link the local versus global interface instead. This is currently of limited use to the average user but it might also help us to focus on making that part of the ETM (support for local energy transition) more top-of-mind).

@antw can you put a very simple: "Sorry, the energy game is no longer supported." page where ETFlex used to be?

**Comment by ChaelKruip** [comment]
> @antw can you put a very simple: "Sorry, the energy game is no longer supported." page where ETFlex used to be?

@AlexanderWirtz is working on a new image for ETCentral that communicates that ETFlex is discontinued. He will push his changes to a pull-request. This makes this page unnecessary for now.

Closing this issue.
