### ISSUE TITLE
Food, paper and ICT sectors should be shown on BETA

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2938]
Somehow the food, paper and ICT sectors are hidden on BETA, even though they are not `_always_hidden` in de admin-section.

**BETA:**
![screen shot 2019-01-31 at 17 25 43](https://user-images.githubusercontent.com/32833996/52068602-42996680-257d-11e9-9755-2d82203ce71e.png)

**LIVE:**
![screen shot 2019-01-31 at 17 25 33](https://user-images.githubusercontent.com/32833996/52068622-504eec00-257d-11e9-88e3-aa6f557d3ade.png)

**Comment by antw** [comment]
I've pushed a small fix for the admin section. The slides are dependent on an attribute `has_detailed_other_industry` [which was recently removed](https://github.com/quintel/etmodel/commit/d36f9341cfd9173b4e97fb7a533b621b5ce76d06#diff-f8737ffcf0d1a40db31e52e65222b993). The admin section was showing that the slide was not dependent on anything when in fact it really was.

The fix means the invalid dependency will be shown to you, allowing it to be changed:

![screen shot 2019-02-01 at 11 05 07](https://user-images.githubusercontent.com/4383/52119532-42e34180-2611-11e9-9c7d-9879d2ab2acf.png)

There are four items in the ETM which are still dependent on this old attribute, and therefore will never be shown:

* Slide: Demand → Industry → Central ICT ([slide 211](https://beta-pro.energytransitionmodel.com/admin/slides/211/edit))
* Chart: Final energy demand in the paper industry ([chart 181](https://beta-pro.energytransitionmodel.com/admin/output_elements/181))
* Chart: Final energy demand in the food industry ([chart 183](https://beta-pro.energytransitionmodel.com/admin/output_elements/183))
* Chart: Final electricity demand in the central ICT industry ([chart 189](https://beta-pro.energytransitionmodel.com/admin/output_elements/189))

I haven't changed any of them myself, as I'm unclear if they should be given a new dependency or made always-visible.

**Comment by marliekeverweij** [comment]
Thanks for implementing the small fix to be able to see the errors! I have removed the dependency form the ETM items, so the paper, food and ICT sectors will be visible for all datasets now.
