### ISSUE TITLE
Over Morgen factsheet does not show future inhabitants or number of dwellings

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2939]
Erwin Lindeijer of Almere pointed this out to us. The number quoted above are for the present. This is a bit confusing

![image](https://user-images.githubusercontent.com/308563/52126611-138ffd00-2630-11e9-8710-41b3aa9cdb82.png)

**Comment by ChaelKruip** [comment]
@redekok can you replace the queries to match the future instead of the present?

**Comment by michieldenhaan** [comment]
See https://github.com/quintel/etmodel/pull/2951
