### ISSUE TITLE
Final demand freight transport should be the same in chart #208 and chart #201

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2944]
Currently they are different:

![image001](https://user-images.githubusercontent.com/32833996/52268064-d8950e80-293a-11e9-9b94-a3baba25a54c.png)

![image004](https://user-images.githubusercontent.com/32833996/52268068-d9c63b80-293a-11e9-817b-d35b025d6fb2.png)

**Comment by marliekeverweij** [comment]
The difference is due to the non-energetic oil demand that is included in the total demand of freight transport (because it's in the `freight_transport`-group), but not in the chart with different freight transport technologies:

![screen shot 2019-02-05 at 15 10 52](https://user-images.githubusercontent.com/32833996/52278926-882ca980-2958-11e9-8750-9be6f39c8890.png)

Shall I include non-energetic oil use in chart #208 ? It is not really a transport technology, but I think it is good to include all energy

Notifying @AlexanderWirtz @ChaelKruip @michieldenhaan

**Comment by AlexanderWirtz** [comment]
Ideally, we would show non-energetic demand as a separate series. Don't know how much work that is. 

Thanks for fixing!

**Comment by AlexanderWirtz** [comment]
Also, it is a bit strange that ALL non-energetic demand is included in the freight group. I suppose we have no good way of splitting this between passenger and freight transport, other that proportionally according to energetic demand of fossil energetic demand. That is ultimately best done in the dataset generation (ETDataset) and therefore a bit laborious. What do you think @marliekeverweij and @ChaelKruip ?

**Comment by michieldenhaan** [comment]
I would prefer to include it as a separate series as well

**Comment by marliekeverweij** [comment]
> Also, it is a bit strange that ALL non-energetic demand is included in the freight group. I suppose we have no good way of splitting this between passenger and freight transport, other that proportionally according to energetic demand of fossil energetic demand. That is ultimately best done in the dataset generation (ETDataset) and therefore a bit laborious.

I totally agree with that, but I think that it is too laborious for now. I think I'll add all non-energetic demand as a separate series to freight_transport for now, do you agree @ChaelKruip ?

**Comment by ChaelKruip** [comment]
> I think I'll add all non-energetic demand as a separate series to freight_transport for now, do you agree @ChaelKruip ?

👍
