### ISSUE TITLE
Shall we combine chart #65 and #56 to one chart?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2945]
Since he have combined the sliders for hot water and space heating in households, I think it would be good to also combine the charts of "Final energy demand for heating in residences" (#56) and 'Final energy demand for hot water in residences' (#65) to one chart by adding up the demands of each carrier. This can easily be fixed.

What do you think @MartLubben, @AlexanderWirtz, @redekok, @jorisberkhout, @ChaelKruip, @antw  and @michieldenhaan ?

![screen shot 2019-02-05 at 16 51 35](https://user-images.githubusercontent.com/32833996/52285286-5b7f8e80-2966-11e9-80f6-a28dde110f14.png)

**Comment by redekok** [comment]
That would make sense after having combined the sliders for space heating & hot water, I guess! Is there any use case in which the user would like to check out the difference in demands per carrier for space heating and hot water (since the distribution of demands for each carrier is apparently different for space heating and hot water)?

**Comment by ChaelKruip** [comment]
> s there any use case in which the user would like to check out the difference in demands per carrier for space heating and hot wate

Yes I think so but we could do that in the same chart anyways! I am all for merging the two!

**Comment by AlexanderWirtz** [comment]
Good idea!

**Comment by marliekeverweij** [comment]
I have combined the charts and kept the series for heat and hot water separately, it now looks like this:

![screen shot 2019-02-06 at 16 05 30](https://user-images.githubusercontent.com/32833996/52350514-0fe1e900-2a29-11e9-9d2d-5a820821913d.png)
