### ISSUE TITLE
The Over Morgen Factsheet of any random scenario does not work on Beta

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2946]
https://beta-pro.energytransitionmodel.com/scenarios/1002117/factsheet

shows me:
![image](https://user-images.githubusercontent.com/308563/52335109-d3e75d80-2a01-11e9-8378-4f27910bf963.png)

etc
re-assign as you see fit

**Comment by michieldenhaan** [comment]
@marliekeverweij is on it! (https://github.com/quintel/etmodel/issues/2933)

**Comment by AlexanderWirtz** [comment]
my bad!
