### ISSUE TITLE
Hydrogen production from excess electricity nog working on beta

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2947]
I tried creating a scenario on Beta for Drenthe where H2 is created from excess electricity, but no hydrogen was made. Then I checked the difference between Net voor de Toekomst scenarios on Live and Beta. One big difference is that no hydrogen is produced from excess electricity. Methinks this is a bug:

**Live**
![image](https://user-images.githubusercontent.com/308563/52342104-bbcd0980-2a14-11e9-8e55-29237ef5ef87.png)

**Beta**
![image](https://user-images.githubusercontent.com/308563/52342121-ca1b2580-2a14-11e9-871c-929e7fd09a0a.png)

Re-assign at will

**Comment by AlexanderWirtz** [comment]
Same settings for order of what to do with excesses.

**Comment by AlexanderWirtz** [comment]
the scenario is 'National steering'

**Comment by marliekeverweij** [comment]
Very strange! I took a short look into it, but do not understand where this comes from. The slider works: more P2G units are build, but no hydrogen is produced with those P2G units. Maybe it has something to do with the interaction between the merit-order and the new hydrogen-calculation. I am assigning @antw
