### ISSUE TITLE
Saving a scenario sometimes doesn't work as it should

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2953]
I just had some troubles saving a scenario. This is what I did:
1. I opened an already saved scenario on beta (f.e. 1003393)
2. Changed the flexibility order 
3. Click `Save scenario`, added a name and description
4. Opened the scenario again from the list that appeared and then only the flexibility order adjustment was saved and not the settings of scenario 1003393....

However, I cannot reproduce this bug 😉

**Comment by antw** [comment]
> However, I cannot reproduce this bug 😉

Me neither. 😀 

If it happens again, I think it would be useful to have the IDs of both scenarios.

**Comment by marliekeverweij** [comment]
Closing this issue as I cannot reproduce it ;)
