### ISSUE TITLE
Number of excess hours returns zero even when it is not zero

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2957]
For the National NvdT scenario I was testing the scenario report, when it struck me it reports **0** hours of excess, even if the chart shows a lot of H2 production from excess electricity. ETmodel shows this:
![image](https://user-images.githubusercontent.com/308563/52487882-e65ac600-2bbe-11e9-972d-0d457af61b7b.png)

This seems incompatible, so there is probably something wrong with the query. This is the case on the Beta and the Live server by the way.

Re-assign as needed. notifying @MartLubben

**Comment by AlexanderWirtz** [comment]
I tested a hypothesis, which turned out to be correct. If I set the number of P2G elektrolyzers to `0`, I see the following. This means the definition of excess events is incorrect iMO. I still think this is a bug, not a feature. 

![image](https://user-images.githubusercontent.com/308563/52488035-494c5d00-2bbf-11e9-820a-ea366193b662.png)

**Comment by AlexanderWirtz** [comment]
From the scenario report:

![image](https://user-images.githubusercontent.com/308563/52488308-d2639400-2bbf-11e9-80b5-73bd61bdf128.png)

**Comment by antw** [comment]
This is because electricity consumed by a flexible is not considered to be an excess. I don't think I'm qualified to say whether or not this is a correct definition of "excess", so I'll leave that discussion to others.

The query that calculates excess events can be easily adjusted to ignore flexible technologies; currently it ignores export and curtailment:

```diff
 V(
   GRAPH(),
   total_number_of_excess_events([
+    :energy_flexibility_pumped_storage_electricity,
+    :households_flexibility_p2p_electricity,
+    :transport_car_flexibility_p2p_electricity,
+    :power_to_heat_industry,
+    :households_flexibility_p2h_electricity,
+    :bunkers_flexibility_p2g_electricity,
+    :energy_hydrogen_flexibility_p2g_electricity,
     :energy_export_electricity,
     :energy_flexibility_curtailment_electricity
   ])
 )
```

---

Notifying @ChaelKruip

**Comment by ChaelKruip** [comment]
> I don't think I'm qualified to say whether or not this is a correct definition of "excess", so I'll leave that discussion to others.

I think about excess as whatever electricity remains after *mandatory demand* has been subtracted:
```
excess = production - mandatory_demand
```

where `mandatory_demand` is all demand of technologies that are not flexible (or export/curtailment). So, excess is the electricity which is left for storage, conversion, export and curtailment. If I understand the graph methods dealing with excess correctly, adding the flex-options to the query should solve this issue indeed! 😄 

Is this also how you think about it @antw ?

**Comment by ChaelKruip** [comment]
With the suggestions by @antw my local machine shows this:
![image](https://user-images.githubusercontent.com/1303760/52573462-81031100-2e1a-11e9-95bf-053deb35bb1a.png)
