### ISSUE TITLE
Heat cost correction should be removed

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#2961]
Now that we've merged the heating and hot water options in ETModel, I think we can get rid of the ``dashboard_total_cost_correction`` in the cost calculation. Instead of using a cost correction I think we can simply stop charging costs for hot water technologies (except for technologies that cannot produce both space heating and hot water).

Note that a correction is still required to avoid double counting of heating and cooling technologies.

**Comment by ChaelKruip** [comment]
> I think we can simply stop charging costs for hot water technologies

We might be able to simplify the correction but it is not wrong at the moment. Seems not worth the trouble for now. Closing this.

**Comment by michieldenhaan** [comment]
That's why I didn't add the deploy milestone. I think this issue is worth keeping open so someone can take this up when time permits. @redekok and I already encountered some fallout from this cost correction when adding the H2 HHP last week.

**Comment by ChaelKruip** [comment]
> I think this issue is worth keeping open so someone can take this up when time permits.

👍
