### ISSUE TITLE
Buildings heat network costs should be updated 

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2962]
Last week I received input from Greenvis about new heat network costs / capacity in buildings. This should be updated on BETA!

**Comment by ChaelKruip** [comment]
@marliekeverweij can we do this next week (after the deploy) and push a mini-deploy of these values and updated biomass values to both BETA and PRODUCTION?

**Comment by marliekeverweij** [comment]
Yes good idea!
