### ISSUE TITLE
Insulation sliders households and buildings should have correct tooltip-description

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2963]
Currently the insulation slider for households don't have any write up and buildings still has the outdated one.

![screen shot 2019-02-11 at 15 34 12](https://user-images.githubusercontent.com/32833996/52569894-83616d00-2e12-11e9-8353-13ccd47dac84.png)

![screen shot 2019-02-11 at 15 34 04](https://user-images.githubusercontent.com/32833996/52569901-85c3c700-2e12-11e9-891d-4bfa79f70a24.png)

**Comment by ChaelKruip** [comment]
@redekok could you fix this today please?

**Comment by redekok** [comment]
@ChaelKruip Yes, I'm on it!

**Comment by redekok** [comment]
@marliekeverweij or @ChaelKruip, I've written some texts for the tooltip descriptions. Let me know if those are good enough!

**Comment by marliekeverweij** [comment]
Yes! Thanks @redekok
