### ISSUE TITLE
English reports refer to old queries

### ISSUE THREAD

**Issue by antw** [quintel/etmodel#2965]
The Dutch-language reports have been updated, but both the main and regional English-language reports still refer to old queries.

* https://beta-pro.energytransitionmodel.com/scenario/reports/main?locale=en
* https://beta-pro.energytransitionmodel.com/scenario/reports/regional?locale=en

**Comment by MartLubben** [comment]
@antw I sent you a pull request to fix it: https://github.com/quintel/etmodel/pull/2967

It removes the outdate text which refers to the queries. A good translation of the new Dutch scenario report to the English one is still WIP.
