### ISSUE TITLE
Remove Supply>Renewable electricity>Biomass plants slide

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#2968]
This slide (Supply>Renewable electricity>Biomass plants slide) seems to be redundant, since there is a new sidebar item for Biomass in BETA. I think I'm not authorized to delete the slide in the admin of ETModel. @antw, could you remove the slide?

![screenshot 2019-02-12 at 17 30 44](https://user-images.githubusercontent.com/5946498/52651776-153da880-2eed-11e9-8ecb-94e3e12dfcc8.png)

**Comment by antw** [comment]
> could you remove the slide?

Done.
