### ISSUE TITLE
Difference in CO2-emissions in dashboard (PRO vs. BETA)

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#2969]
In the Nederlands (present - 2050) scenario, there is a difference in the CO2-emission KPI in the dashboard:

![screenshot 2019-02-12 at 18 07 19](https://user-images.githubusercontent.com/5946498/52654124-a44cbf80-2ef1-11e9-819b-60c6ef742bf0.png)

![screenshot 2019-02-12 at 18 09 29](https://user-images.githubusercontent.com/5946498/52654130-a6af1980-2ef1-11e9-9eb7-5d8dc6b70e47.png)

When I checked the CO2-emission chart for biomass, there seemed to be a difference of a few Mton as well between BETA and PRO:

![screenshot 2019-02-12 at 17 58 58](https://user-images.githubusercontent.com/5946498/52654248-e4ac3d80-2ef1-11e9-8b96-beec6d7d620c.png)

![screenshot 2019-02-12 at 17 55 50](https://user-images.githubusercontent.com/5946498/52654254-e70e9780-2ef1-11e9-9684-4730c26e6ca0.png)

I'm not sure if this is the only thing that causes the difference in the dashboard KPI for CO2-emissions.
 @marliekeverweij, do you have any thoughts on this? I'll check the CO2-emissions for some other scenarios as well to see if there are any differences in emissions between PRO and BETA.

**Comment by michieldenhaan** [comment]
As discussed, this is because we corrected the double counting of coal gas in Industry. See: https://github.com/quintel/etdataset/issues/621
