### ISSUE TITLE
"Under construction" biomass charts on BETA 

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#2970]
These biomass charts do still have the label "UNDER CONSTRUCTION" on BETA. @marliekeverweij, are these still under construction? If so, what is necessary to make those ready for the deploy? If not (i.e., the charts are ready to be shown on PRO after the deploy), should we remove the "UNDER CONSTRUCTION" label in the ETModel admin?

![screenshot 2019-02-12 at 18 20 49](https://user-images.githubusercontent.com/5946498/52655004-7ec0b580-2ef3-11e9-9762-a719ab0156d4.png)
![screenshot 2019-02-12 at 18 20 58](https://user-images.githubusercontent.com/5946498/52655013-81bba600-2ef3-11e9-9ec7-e30dcfa52682.png)
![screenshot 2019-02-12 at 18 21 09](https://user-images.githubusercontent.com/5946498/52655015-82ecd300-2ef3-11e9-8ce2-bb3d455991b5.png)

**Comment by marliekeverweij** [comment]
The labels have been added this week because we haven't implemented the biomass data yet. Therefore, users should know that the data behind this chart is outdated. I will implement the data next week and will then remove the labels!
