### ISSUE TITLE
Max setting of slider CO2 of imported heat is too low.

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2972]
See below the proposed 36 kg/GJ of a gas power plant, while the slider 21 kg/GJ

![screen shot 2019-02-13 at 12 43 53](https://user-images.githubusercontent.com/33415156/52709502-31912200-2f8d-11e9-816e-366d66433ba4.png)

**Comment by marliekeverweij** [comment]
Somehow the max slider value is scaled for the dataset you're looking into. I cannot find where this is defined, could you maybe help me out @antw ?

**Comment by antw** [comment]
> I cannot find where this is defined, could you maybe help me out @antw ?

Unscaleable units are now defined in ETSource: [config/unscaleable_units.yml](https://github.com/quintel/etsource/blob/master/config/unscaleable_units.yml)

**Comment by michieldenhaan** [comment]
I tried this but the value doesn't change. Am I doing something wrong?


![etmodel test - energy transition model - your free independent comprehensive fact-based scenario builder 2019-02-14 09-16-35](https://user-images.githubusercontent.com/32056448/52773053-5c857f80-303a-11e9-8be2-d0f2915c569d.png)

**Comment by antw** [comment]
[The input unit is `kg`](https://github.com/quintel/etsource/blob/4f47c6eb5acd645ea9f4b3b8929cb1bbded4c392/inputs/supply/heat/co2_emissions_of_imported_heat.ad). I think it should be `kg/MJ`. This might also be true for hydrogen, [here](https://github.com/quintel/etsource/blob/4f47c6eb5acd645ea9f4b3b8929cb1bbded4c392/inputs/supply/hydrogen/imported_hydrogen_co2/co2_emissions_of_imported_hydrogen_present.ad) and [here](https://github.com/quintel/etsource/blob/4f47c6eb5acd645ea9f4b3b8929cb1bbded4c392/inputs/supply/hydrogen/imported_hydrogen_co2/co2_emissions_of_imported_hydrogen_future.ad).

(I can't help but notice that heat and H2 are inconsistent, with the former using per-Joule and the latter using per-watt-hour, while imported electricity uses `gCO2/KWh` 🤔).

**Comment by michieldenhaan** [comment]
Thanks! I agree that the use of different units is not so nice. The thing is that most people tend to use GJs when talking about heat, kWh/MWh for electricity and kg or MWh for H2..
I'm happy to change the units tho if someone has a strong opinion on this.
