### ISSUE TITLE
Bio-footprint calculation for greengas doesn't seem to work as expected

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#2978]
When changing the share of green gas in the gas network, the bio-footprint is expected to increase. This is indeed the case for PRO:

![screenshot 2019-02-14 at 12 08 19](https://user-images.githubusercontent.com/5946498/52784273-d3c80d00-3054-11e9-8d80-44e6c1e2fb9a.png)
![screenshot 2019-02-14 at 12 09 52](https://user-images.githubusercontent.com/5946498/52784277-d6c2fd80-3054-11e9-84a5-1b10e4f7d499.png)

However, the bio-footprint (in the dashboard) doesn't increase when changing the shares for BETA:

![screenshot 2019-02-14 at 12 10 08](https://user-images.githubusercontent.com/5946498/52784288-eb9f9100-3054-11e9-9eaf-b7dda446d90f.png)
![screenshot 2019-02-14 at 12 10 21](https://user-images.githubusercontent.com/5946498/52784290-ee9a8180-3054-11e9-87ee-95f9c7f1914d.png)

At the production branch, the key `typical_production_per_km2` is still included in the `greengas.ad` file, whereas it has been removed for beta. It should calculate the value recursively but this doesn't seem to be the case.

@antw Do you have any thoughts on this?

**Comment by antw** [comment]
The [area footprint calculation](https://github.com/quintel/etengine/blob/4a4591092223ca09cf3d3e9c1a4a10b9c63d6bd4/app/models/qernel/graph_api.rb#L55-L65) is pretty simple. It looks for the `bio_footprint_calculation` node group, and for each of its output it looks at the `typical_production_per_km2` of each carrier.

@marliekeverweij @ChaelKruip Is it possible that new nodes added for the biomass project should have been added to the group, or that new carriers may be missing a `typical_production_per_km2` value?

**Comment by ChaelKruip** [comment]
> @marliekeverweij @ChaelKruip Is it possible that new nodes added for the biomass project should have been added to the group, or that new carriers may be missing a `typical_production_per_km2` value?

We are on it!

**Comment by redekok** [comment]
The edge between `energy_import_greengas` and `foreign_energy_upgrade_biogas` was of type `constant` instead of `share`. Updating the edge type to `share` seems to have fixed the issue.
