### ISSUE TITLE
Pro starting page preset scenarios could be more clearly demarcated as scenarios

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2980]
To quote my wife: 
"How will people know those are all individual scenarios, on first glance it looks like a solid block of text"

She was referring to this: 
![image](https://user-images.githubusercontent.com/308563/52844191-5065f480-3104-11e9-8cda-e237282d144b.png)

Perhaps each preset scenario title could have a bullet or even a subtle button-like frame around it? Just to make it appear less like a block of text and more like three separate lists.

**Comment by antw** [comment]
Two ideas come to mind:

1. Add an arrow after each scenario title, as with many of the other links on the page:

![screen shot 2019-03-07 at 15 28 17](https://user-images.githubusercontent.com/4383/53967790-c3ec9780-40ed-11e9-89f2-191f7af9f763.png)

2. Make the links the same blue colour as the other links. I'm not a fan of this as I think they distract a lot of attention from other parts of the page.

![screen shot 2019-03-07 at 15 27 59](https://user-images.githubusercontent.com/4383/53967826-d797fe00-40ed-11e9-8512-a17a3f58bcef.png)

Happy to entertain any other ideas.

**Comment by redekok** [comment]
How about changing the arrows from your first idea into **>>** icons that we use for the **Continue >>** and **Start >>** buttons?
