### ISSUE TITLE
We should remove the fuel chain emission section from the ETM

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2986]
During the biomass project we had to update the FCE module, because we had added new bio-carriers (sugar beets, wheat, rapeseed etc). We experienced that updating the FCE section takes quite some effort and we are not even sure if the data matches the data used there. Also the FCE is based on 2012 data, so should be updated in general I think, when we want to keep it. 

But, do we want to keep the FCE module in the ETM?

When you have an opinion about this issue, let me know! @antw , @MartLubben , @redekok , @michieldenhaan , @AlexanderWirtz , @ChaelKruip , @jorisberkhout 

Link to FCE: https://pro.energytransitionmodel.com/scenario/supply/fce/fce-settings

**Comment by AlexanderWirtz** [comment]
I am OK with removing it, but might I propose a compromise?

We COULD always consider removing the FCE bits unrelated to combustion of a fuel. That way we could still use the fact that Eastern European coal and Indonesian coal emit different amounts of CO2/GJ of energy output. 

Just putting it out there.

**Comment by ChaelKruip** [comment]
> But, do we want to keep the FCE module in the ETM?

I never use it but I can see its usefulness to make a point that emission factors can depend on origin of a carrier. I would suggest to replace the module with sliders to set the CO2/MJ for relevant carriers (similar to what @AlexanderWirtz suggests I now see)

**Comment by marliekeverweij** [comment]
In https://github.com/quintel/etsource/issues/1766 @ChaelKruip said:
> @marliekeverweij in light of recent discussions on (partially) removing/replacing the FCE module of the ETM I wonder if we should extend the FCE functionality. Perhaps we could seize this opportunity to simplify/replace the FCE sliders and calculations which are not used by many (I think) and are prone to breaking and maintenance (I know)?

Yes, good point! 

The current .yml-files in [datasets/??/fce](https://github.com/quintel/etsource/tree/master/datasets/nl/fce) actually include more than only the fuel-chain-emissions. Besides the fuel-chain-emissions, it also includes:
1. `co2_conversion_per_mj`, which are used for setting CO2 emissions of carriers also when the FCE is not enabled
2. `start_value` or shares, f.e. the shares of feedstock for bio-ethanol or the countries of origin for coal

I think we would surely like to keep the above two features! Because in that case we can set the shares and adjust the `co2_conversion_per_mj` per dataset. Then we would keep the things that @ChaelKruip and @AlexanderWirtz mention above!

My proposal would be to:

- remove the FCE-module side bar item from the front-end
- remove the fuel-chain-emissions from the .yml-files (but keep the `start_value` and `co2_conversion_per_mj`)
- rename [datasets/??/fce](https://github.com/quintel/etsource/tree/master/datasets/nl/fce) to `co2_carriers` (or something in that direction)

Maybe we could:
- add sliders to the front-end in which users could set the country of origin of their coal/oil, which influences the `co2_conversion_per_mj` ? 
**OR** 
- add sliders that allow users to set the CO2/MJ of the fuel directly (just like imported_heat and imported_electricity)

**Comment by ChaelKruip** [comment]
> add sliders that allow users to set the CO2/MJ of the fuel directly (just like imported_heat and imported_electricity)

That has my strong preference.
