### ISSUE TITLE
Deploy-updates should be shown on PRO

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2988]
I can only see the banner with the deploy-updates in my local model and not on BETA/PRO. Shouldn't it be shown there?

![screen shot 2019-02-28 at 16 38 28](https://user-images.githubusercontent.com/32833996/53578182-6ef1d400-3b77-11e9-881d-78ea7ca306d2.png)

**Comment by antw** [comment]
Thanks for the heads-up; I've turned it back on.
