### ISSUE TITLE
Change solar parks slider unit to MW instead of number of units

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2992]
@MartLubben proposes the following in this issue https://github.com/quintel/etmodel/issues/2912#issuecomment-468609784 : 

For solar parks the discussion is more about the area or MW of the park. The current unit of 20 MW and 20-30 hectares creates a lot of confusion and extra preparation for a session. Would people agree to change it to MW input, just like we do in the hydrogen sector?

**Comment by ChaelKruip** [comment]
If this is not too time consuming (two hours?) I would be greatly in favour of doing this soon!

**Comment by marliekeverweij** [comment]
Okay! I just assigned @redekok , reassign somebody else at will :)
