### ISSUE TITLE
Antwerp would like CO2 reference year to be 2005 instead of 1990

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2993]
Apparently 1990 is not the universal reference year for CO2 emissions that we thought it was. In some countries 2005 is more commonly used. Belgium is one of those. 

A 'simple' way to fix that would be to have the CO2 chart label the left-most column with whatever reference year the dataset provides. 

![test](https://user-images.githubusercontent.com/308563/53745297-0ff5cd00-3e9f-11e9-871b-f676d623c019.png)

Is it possible to have the label for 1990 be country-specific? Is this desirable, do we need to change many labels, etc?

This is not a major request, but if this is easy to fix, then why not do so?

Curious wat you think @ChaelKruip @marliekeverweij @antw

**Comment by michieldenhaan** [comment]
@redekok and I encountered this in Gent as well

**Comment by marliekeverweij** [comment]
Currently the 1990 CO2 emissions are added to the left-most column by ticking the `is 1990` in the admin-section (see screenshot below).

![screen shot 2019-03-04 at 17 16 07](https://user-images.githubusercontent.com/32833996/53746365-51877780-3ea1-11e9-8206-1da13afd6626.png)

Maybe we could:
- add a tick box for `is 2005`?
or 
- make the tick box more general: f.e. `is reference year`. And then add an area-attribute (f.e. `- reference_year = `) with which you can set the reference year for the dataset (for Dutch datasets we can set it on 1990 by default).

I actually think it's not very easy to fix, but @antw can better decide that I think!

Btw: the label of the output element series (f.e. '1990 CO2 emissions of international transport') does not have to include the reference year per se I think. We can also delete 1990 from the text above the chart. Then we do not have to make those country-specific. 
Only underneath the vertical stacked bar it is needed that the right reference year is stated!

**Comment by AlexanderWirtz** [comment]
> Btw: the label of the output element series (f.e. '1990 CO2 emissions of international transport') does not have to include the reference year per se I think. We can also delete 1990 from the text above the chart. Then we do not have to make those country-specific.
Only underneath the vertical stacked bar it is needed that the right reference year is stated!

Indeed, in most text you can refer to the 'reference year'. I do know there are 3 `area` .ad files that refer to `co2_emission_1990...`, like: `co2_emission_1990.ad`
```
- query = UPDATE(AREA(), co2_emission_1990, USER_INPUT())
- priority = 2
- update_period = both
```

**Comment by antw** [comment]
I think @marliekeverweij is correct to suggest making it more generic to call it a "reference year" (or similar) and define the year in the area/dataset file.

Currently "1990" is hard-coded in quite a number of places, particularly some of the ETMs charts, but also the reports, ETEngine, Atlas, and ETSource. I expect replacing it properly will be a small project of it's own.

**Comment by marliekeverweij** [comment]
Sorry for responding a month later to this issue.... Let's keep is as it is for now then, since we do not have budget to replace '1990' with a more general year. We have communicated to Antwerp that we will use 2005 emissions for the Antwerp dataset instead of 1990 emissions and that the 1990 label will stay the same. It will probably give some confusion, but so be it. 

Notifying @MartLubben: as this may be relevant during your workshop in Antwerp this week.
