### ISSUE TITLE
The geothermal slider should be capped at a more reasonable maximum

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2996]
At this moment te slider `number_of_energy_heater_for_heat_network_geothermal` is capped at 18704, which results in 2100 PJ of geothermal heat, while a recent studie shows a max in NL around 230 PJ source: https://www.ebn.nl/wp-content/uploads/2018/05/20180529-Masterplan-Aardwarmte-in-Nederland.pdf 

This 230 PJ can be capped with to max amount of 2047 geothermal units. 

@ChaelKruip what do you think?

**Comment by marliekeverweij** [comment]
Do we want to do something with this issue? @MartLubben I assigned you, if you want to reassign someone else, just do it ;) 

The slider is capped with the following statement:
`- max_value_gql = present:MAX(5.0,PRODUCT(DIVIDE(Q(total_electricity_consumed),V(energy_power_geothermal,typical_electricity_production_per_unit)),V(energy_power_geothermal, electricity_output_capacity)))`

Indeed quite a lot! You can supply 5x the regional electricity consumption

**Comment by michieldenhaan** [comment]
> Indeed quite a lot! You can supply 5x the regional electricity consumption

The first operator is a ``MAX``, not ``PRODUCT``. So you can supply 1x the present electricity consumption or 5 MW, whichever is higher. 

@MartLubben is referring to the heater btw, not the geothermal power plant. The max for that slider is:
``present:MAX(5.0,PRODUCT(DIVIDE(SUM(V(G(heat_production),output_of_heat_carriers)),V(energy_heater_for_heat_network_geothermal,typical_heat_production_per_unit)),2.0,V(energy_heater_for_heat_network_geothermal,heat_output_capacity)))``
So 2x the present total heat production (both individual heat and collective heat, which is around 1 EJ for NL). That's a lot. I think we have to be careful tho not to limit the slider max too much, as this affects all regions in the ETM. Maybe we can remove the multiplication by 2, such that geothermal can supply 100% of current heat demand? Still a lot but for some regions that might be possible.
