### ISSUE TITLE
After scaling a scenario the 'Import/Export' sidebar item is lost

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2997]
When a scenario is scaled with the scaling tool in the ETM front-end, it results in not showing the import/export sidebar item.

**Comment by MartLubben** [comment]
![screen shot 2019-03-07 at 15 31 24](https://user-images.githubusercontent.com/33415156/53963706-19c13f80-40ee-11e9-8cb5-acb27797edda.png)

**Comment by antw** [comment]
This appears to be as intended:

![screen shot 2019-03-07 at 14 56 32](https://user-images.githubusercontent.com/4383/53965596-69e9d300-40e9-11e9-88ed-c67525f0e45f.png)

The name is now a little misleading. `is_national_scenario` is any scenario *not* scaled using the old scaling feature.

**Comment by MartLubben** [comment]
Thanks! Sorry for blaming you to create bugs ;-).
