### ISSUE TITLE
Should we decrease the number of series in the heat network mekko?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2999]
@michieldenhaan and I were discussing last week that the heat network overview mekko is actually too detailed. When opening a new scenario for the NL, the following heaters are shown:

![Screen Shot 2019-03-11 at 14 34 49](https://user-images.githubusercontent.com/32833996/54127962-438aa700-440b-11e9-9b46-6f61bbc5d8ad.png)

Since we want to focus less on the different heat networks modelled in the ETM (households, buildings, agricultural, industrial, 'central'), we want to propose to narrow the series down to only the type of heater and not the location. So for example:

- Geothermal
- Gas CHP
- Biomass CHP
- etc.

What do you think? @MartLubben, @redekok, @ChaelKruip, @AlexanderWirtz, @jorisberkhout

**Comment by michieldenhaan** [comment]
One other option is to group the different heaters/CHPs by carrier, e.g. showing one series for 'gas heaters' rather than 6+ series for all the different gas CHPs

**Comment by ChaelKruip** [comment]
I agree with the observation that this is a busy chart and simplification would be nice. On the other hand, what I like about the abundance of series is that you know where to go to in the model to remove a type of heater. With the re-arrangement of the sliders in the last heat project this argument is less strong...

**Comment by redekok** [comment]
In my opinion an interactive chart would be cool! That you start off with a simplified chart in (which some of the series are grouped) and that, by clicking on one of the blocks, it breaks down into multiple series. Not sure if that is possible, though?
