### ISSUE TITLE
Combined cycle hydrogen power plant should be added to hydrogen demand chart

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3008]
It seems that the series for the new combined cycle hydrogen power plant is missing in the hydrogen demand chart: 

![Screen Shot 2019-04-01 at 12 29 31](https://user-images.githubusercontent.com/32833996/55321390-d3a39580-5479-11e9-9c78-2a29d9151f2e.png)

![Screen Shot 2019-04-01 at 12 27 22](https://user-images.githubusercontent.com/32833996/55321370-c4244c80-5479-11e9-87d0-c036f3671d6f.png)

And it seems like a translation is missing:

![Screen Shot 2019-04-01 at 12 27 35](https://user-images.githubusercontent.com/32833996/55321456-fa61cc00-5479-11e9-961f-5a860e999f87.png)

Reassign at will :)

**Comment by redekok** [comment]
> It seems that the series for the new combined cycle hydrogen power plant is missing in the hydrogen demand chart

I've merged the series for the hydrogen turbine and the new combined cycle hydrogen plant; both are included in the electricity production series:

```
- unit = PJ
- query =
    DIVIDE(
        SUM(
            V(LINK(energy_power_turbine_hydrogen,energy_distribution_hydrogen_after_transport), demand),
            V(LINK(energy_power_combined_cycle_hydrogen,energy_distribution_hydrogen_after_transport), demand)
        ),
        BILLIONS
    )
```


> And it seems like a translation is missing

I've just created a [PR](https://github.com/quintel/etmodel/issues/3008) to add the missing translations. Thanks for noticing and notifying!
