### ISSUE TITLE
Buttons above additional charts are not loaded for etmodel in Dutch 

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#3011]
I understand this is a recurring issue. I have not looked up the closed issue, though. 

On Live, this is what an additional chart looks like when I view it in Dutch: 
![image](https://user-images.githubusercontent.com/308563/55481421-a8a87580-5622-11e9-8e73-2590a869c3a6.png)

Reloading the page doesn't solve this.

When I switch to English and reload the chart, the buttons above the extra chart do appear:
![image](https://user-images.githubusercontent.com/308563/55481651-253b5400-5623-11e9-8e25-78b6f39fcbf3.png)

**Comment by redekok** [comment]
The previous [issue on this topic](https://github.com/quintel/etmodel/issues/2955
) was solved by https://github.com/quintel/etmodel/commit/e9bdad7a47fc7f7bceadca5d675813e99c63a332 but apparently the issue is still occurring..

**Comment by antw** [comment]
I've changed up the styles again; it should be fine now. 🤞
