### ISSUE TITLE
Shall we narrow down the number of sidebar items in the Costs-section?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3016]
Currently the 'Costs'-section has 14 categories:

![Screen Shot 2019-04-08 at 17 15 20](https://user-images.githubusercontent.com/32833996/55735905-8ea3d400-5a22-11e9-9785-ac7154726cde.png)

Shall we narrow it down by creating new sidebar items and nesting current categories inside them?

For example, we could create the following sidebar items:
- 'Power plants' : which could include 'Combustion plants' and 'Nuclear plants'
- 'Renewable electricity': which could include 'Wind tubrines', 'Solar power', 'Geothermal' and 'Hydro electric'

Let me know what you think and if you have better suggestions! @AlexanderWirtz, @antw  , @ChaelKruip , @DorinevanderVlies , @jorisberkhout , @redekok , @MartLubben , @michieldenhaan

**Comment by DorinevanderVlies** [comment]
I like this plan!

Furthermore I think we can remove the slide "merit order positions" as it has overlap with the slide "Merit order price" in "Results" --> "Data export"
