### ISSUE TITLE
The chart overview_costs_of_electricity_production does not load

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3020]
On live and on beta

![image](https://user-images.githubusercontent.com/19907658/55858633-7e9a0a80-5b70-11e9-9e4f-3407ea3c25a3.png)

This issue might be connected with the implementation of the H2 CCGT plant
notifying @martlubben

**Comment by DorinevanderVlies** [comment]
It seems that this charts does not use gqueries from ETSource, but output from merit.
We (@marliekeverweij, @redekok and me) suspect the H2 CCGT plant links (for investement and/or costs) are not yet correctly in place. 

@antw, can you have a look at this?

**Comment by michieldenhaan** [comment]
The 'short content` field was empty for the Hydrogen CCGT.

![pro energytransitionmodel com - EnergyTransitionModel 2019-04-10 10-38-11](https://user-images.githubusercontent.com/32056448/55864422-c32ba300-5b7c-11e9-95fa-ac45821b4ee7.png)
