### ISSUE TITLE
The primary demand mekko should not show used surplus electricity as exported or curtailed

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3022]
In the Groningen-Drenthe scenario: https://beta-pro.energytransitionmodel.com/scenarios/1051292 the mekko primary demand shows 270 PJ of electricity which is exported or curtailed. This is in contrast with the flexibility chart which shows 90PJ losses and 140 PJ hydrogen production. 

![Screen Shot 2019-04-17 at 14 31 37](https://user-images.githubusercontent.com/33415156/56287817-a283c000-611d-11e9-9dcc-9bfb5e30fb28.png)

**Comment by marliekeverweij** [comment]
Closing this issue as this issue now exists: https://github.com/quintel/etsource/issues/2025
