### ISSUE TITLE
Some max values of sliders are limiting scenario making in Groningen-Drenthe

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3023]
Some sliders have a max value lower than we would like to explore:

- Wind offshore, now 6264 units and should be 7500 units
- PtHydrogen. no 13000 MW, but should be 20 000 MW

**Comment by marliekeverweij** [comment]
@MartLubben is this issue still relevant for the project?

**Comment by MartLubben** [comment]
@marliekeverweij the sliders are set via the engine, so not for the results, but yes when you want to play with it.
