### ISSUE TITLE
Change the housing type sliders to % instead of # of units

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3024]
During the heat project we had chosen to make # of units sliders for the different housing types.

![Screen Shot 2019-04-18 at 12 17 57](https://user-images.githubusercontent.com/32833996/56354468-12ed1880-61d4-11e9-8a9c-8504821ff6f4.png)

If I remember correctly, the reason for this was partly to reduce the number of sliders, because when we would implement % sliders also a total number of houses slider should be added.

However, actually it's more intuitive to have % sliders. @MartLubben experienced during workshops that most regions know the future plans for the total number of houses, but not for each individual housing type. So now users should evenly divide the expected growth of houses among the different housing types, which is quite cumbersome.

So my proposal would be to change it to this:

![Screen Shot 2019-04-18 at 12 26 57](https://user-images.githubusercontent.com/32833996/56355142-dc180200-61d5-11e9-977d-abf5e6c91945.png)

Let me know your opinion @AlexanderWirtz @antw @jorisberkhout @MartLubben @redekok  @michieldenhaan @ChaelKruip @DorinevanderVlies

**Comment by marliekeverweij** [comment]
To fix this issue the following things have to be done:

- [ ] add input statement for new slider: `households_total_number_of_houses`
- [ ] housing type sliders have to be adjusted to % instead of # (and maybe renamed?)
- [ ] fix translations
- [ ] migration has to take place for these adjusted & new sliders! @redekok or @michieldenhaan do you have time to assist with that?

**Comment by redekok** [comment]
> migration has to take place for these adjusted & new sliders! @redekok or @michieldenhaan do you have time to assist with that?

I would have time next week to help with the migration!
