### ISSUE TITLE
Costs of insulation should be an explicit category in the cost chart

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3025]
Now the insulation costs are nested under 'heat production & network', shall we create a separate series for them? 

![Screen Shot 2019-04-18 at 13 36 49](https://user-images.githubusercontent.com/32833996/56358521-218cfd00-61df-11e9-96e8-c850cdb8b578.png)

@AlexanderWirtz @antw @jorisberkhout @MartLubben @redekok  @michieldenhaan @ChaelKruip @DorinevanderVlies

**Comment by AlexanderWirtz** [comment]
👍

**Comment by DorinevanderVlies** [comment]
Yes! And add them to the investment table
