### ISSUE TITLE
Electricity demand should not decrease in a scenario with heat network using collective heat pump

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3026]
In [this scenario](https://pro.energytransitionmodel.com/scenarios/414230) with all households on a heatnetwork supplied by a collective heat pump the total electricity demand is lower than in the present situation. 

![image](https://user-images.githubusercontent.com/19907658/56379800-ddb2eb80-6210-11e9-9300-b9185afc02b2.png)

This is unintuitive and I assume wrong.

Notifying @marliekeverweij

**Comment by marliekeverweij** [comment]
Interesting issue. I had a look a the graph and I saw two more electricity consuming nodes that are not final demand:

- `energy_cokesoven_consumption_coal_gas`
- `energy_compressor_network_gas`

Maybe we could adjust the query in such a way that it takes the total yearly demand of electricity from the merit order? Not sure how yeat
