### ISSUE TITLE
We should move the 'save scenario'-button to a more prominent place!

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3039]
@MartLubben mentioned this week that one time during a session he accidentally clicked on 'reset scenario' instead of 'save scenario', which is kind of unpractical when you just finished a scenario....

![Screen Shot 2019-05-24 at 16 53 59](https://user-images.githubusercontent.com/32833996/58337017-2760a880-7e45-11e9-984d-95a4c335cb84.png)

Thinking about this; as we want to give more attention to saving a scenario, we should mabye move the 'save scenario' button to another place!

My preference would go to underneath the Results-tab! In line with the our workflow 😎
@AlexanderWirtz , @ChaelKruip , @redekok , @DorinevanderVlies @michieldenhaan @MartLubben @michieldenhaan

**Comment by MartLubben** [comment]
>is kind of unpractical when you just finished a scenario....
I couldn't agree more. 

Fortunately, is was a very easy scenario which I could reproduce :p.

**Comment by redekok** [comment]
I agree to emphasize the "save" functionality! 

> My preference would go to underneath the Results-tab!

As a new tab? Or as a sidebar item under Results?

**Comment by marliekeverweij** [comment]
> As a new tab? Or as a sidebar item under Results?

As a new tab. Then the tabs exactly correspond with our workflow!

![Screen Shot 2019-05-27 at 09 23 18](https://user-images.githubusercontent.com/32833996/58402845-83a01400-8061-11e9-8bc0-b6d8806c56d9.png)

**Comment by marliekeverweij** [comment]
Oh I have a better idea: the new tab 'Save scenario' does not directly have to link you to the 'save scenario' page. We could also do it like this: write a good text for users about how to save a scenario and how to share your scenario with others and create a button that links to the 'save scenario' page. I think it's good for users to know what the impact of the 'save scenario'-button is **before they leave the scenario**. What do you think?

![Screen Shot 2019-05-27 at 09 23 18](https://user-images.githubusercontent.com/32833996/58462697-ab12e180-8132-11e9-8334-876daa8df794.png)

**Comment by MartLubben** [comment]
>What do you think?

Very good idea!!

**Comment by marliekeverweij** [comment]
I think that it is achievable to create this new button before the deploy on July 10th, therefore I have added the deploy-milestone to this issue. Please let me know when I am wrong!

**Comment by marliekeverweij** [comment]
I do not see this new 'SAVE'-button on BETA yet and I am really looking forward to it! 🙂

@antw @sfp-kemp, what's the status of this issue? Will it be possible to put it on BETA before the feature-freeze?

**Comment by antw** [comment]
> what's the status of this issue? Will it be possible to put it on BETA before the feature-freeze?

@sfp-kemp is not working this week. I'm unsure about rushing out this button... what should it do? "Save scenario" or "Save scenario as"?

> @MartLubben mentioned this week that one time during a session he accidentally clicked on 'reset scenario' instead of 'save scenario',

We should add an "Are you sure?" prompt when clicking "Reset". I wonder how many people ever use it? Does anyone know?

**Comment by DorinevanderVlies** [comment]
> I do not see this new 'SAVE'-button on BETA yet and I am really looking forward to it! 🙂

For me it is only visible when work in a scenario I previously saved in the normal way and opened through load scenario.

> We should add an "Are you sure?" prompt when clicking "Reset". I wonder how many people ever use it? Does anyone know?

Sounds good. I use it every now and then, particularly in discussions/workshops.

**Comment by marliekeverweij** [comment]
> For me it is only visible when work in a scenario I previously saved in the normal way and opened through load scenario.

Ah that's it! The functionality for "Save scenario" has already been implemented next to "Save scenario as", but the button has not yet been moved to a more prominent place. And the "Save scenario" button is now only visible in a previously saved scenario: 

![Screen Shot 2019-07-02 at 15 25 26](https://user-images.githubusercontent.com/32833996/60516765-b1225200-9cde-11e9-9dda-834917147e34.png)

But I'll leave this issue open, because I think that moving the button to a more prominent place is still a good idea :)

**Comment by marliekeverweij** [comment]
It would actually be great to move the save buttons before the deploy, so actually today 😉. Yesterday @redekok and I talked about it and thought that it should not be too difficult. But actually it is @sfp-kemp 's work, so would be nice if he could also do this last part! He'll only be there again next week.

The difficulty I see with implementing the 'SAVE'-button and 'SAVE AS'-button to this new place, is that the 'SAVE'-button should only show up when the scenario has already been saved before. 
How much work do you think this will be @antw?

This would be the idea (copied the image I used before), except then we would have the two 'SAVE'-buttons next to each other:

![58462697-ab12e180-8132-11e9-8334-876daa8df794](https://user-images.githubusercontent.com/32833996/60644438-687dac80-9e36-11e9-8d57-44b09a0f3cc9.png)

**Comment by marliekeverweij** [comment]
Just talked with @ChaelKruip about this issue and decided that it would be okay to move the buttons on Monday when @sfp-kemp is back. Do you also think so @antw ?

**Comment by sfp-kemp** [comment]
It took me a little more effort then expected to figure this out. I'm afraid I might not be able to finish and test this in time for the deploy.

**Comment by marliekeverweij** [comment]
We decided to not rush this replacement of the 'SAVE'-button and 'SAVE AS'-button through and fix this after the deploy. Removing the milestone

**Comment by sfp-kemp** [comment]
https://github.com/sfp-kemp/etmodel/tree/new_save_button_location

**Comment by marliekeverweij** [comment]
What is the status of this issue @sfp-kemp? Do we still want to move the save scenario button to the location on the image below or not?

![58462697-ab12e180-8132-11e9-8334-876daa8df794](https://user-images.githubusercontent.com/32833996/65425495-63654380-de0e-11e9-9263-ec9c6c3a2233.png)

**Comment by sfp-kemp** [comment]
Working on this!

**Comment by antw** [comment]
Closed by #3470
