### ISSUE TITLE
It should be possible to use non-energetic hydrogen in the chemical industry

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3040]
As @AlexanderWirtz and @MartLubben mentioned: it should be possible to replace non-energetic oil/gas/coal/biomass and use non-energetic hydrogen in chemical_other industry. This would lead to five extra sliders, because non-energetic oil/gas/coal/biomass  are already included in the chemical other industry at the moment. Mockup:

![Screen Shot 2019-05-27 at 16 13 42](https://user-images.githubusercontent.com/32833996/58425602-7a7f6900-809a-11e9-8e60-c871d6cd779c.png)

We have two ways to implement this: 
1. We could use the same kind of input statements as we've used for the energetic other industry sliders (https://github.com/quintel/etsource/blob/master/inputs/demand/industry/industry_aggregated_other_industry_coal_share.ad). 
For example: for `industry_chemicals_other_non_energetic_coal_share` would then look like this:
```
- query =
    total_demand_chemical_other_industry_non_energetic = Q(final_demand_of_chemical_other_industry_non_energetic);
    
    EACH(
      UPDATE(V(industry_useful_demand_for_chemical_other_coal_non_energetic), preset_demand, (USER_INPUT() / 100.0) * total_demand_chemical_other_industry_non_energetic * BILLIONS)
    )
``` 
Option 1 seems a little cumbersome, but the conventional method of adjusting the node-shares with %-sliders cannot directly be applied here. This is the case since there isn't a total useful demand non-energetic node for chemical 
other industry in the graph:
![Screen Shot 2019-05-27 at 16 13 29](https://user-images.githubusercontent.com/32833996/58425702-ca5e3000-809a-11e9-9477-5db66442c274.png)

2. But the node `industry_useful_demand_for_chemical_other_non_energetic` could also be added. This is not done anywhere else in the graph: that the _total_ non-energetic demand for a sector comes together in one non-energetic useful_demand node.

I do not have a strong opinion for one of these options! Let me know your opinion @ChaelKruip, @michieldenhaan, @jorisberkhout, @AlexanderWirtz, @antw (+ anybody else who has an opinion about this :) )

**Comment by marliekeverweij** [comment]
Just discussed with @ChaelKruip: we want to go for option 2!

**Comment by AlexanderWirtz** [comment]
I am not sure option 2 always makes sense, but maybe I am overcomplicating. 

Not all non-energetic demand can be replaced by each carrier equally (hence the need for the molecules project). How to replace Methane and hydrogen is quite easy to find out, as most non-energetic CH4 demand is to make H2 + CO.  We also know a bit about how biomass is used to make H2 + CO (we have a gasification node). This makes estimating how much biomass (energetically) replaces how much CH4 or methane easy too.

Non-energetic oil demand is another thing though: oil is split into lots of fractions. All of them can be synthesized from H2 + CO, but I am not sure the always requires the same amount of H2. The longer the hydrocarbon chain, the fewer H-atoms per C-atom is needed.

I don't want to get ahead of myself and start a mini-molecules project. My suggestion for now would be to make CH4, biomass and H2 interchangable but leave oil demand out of it.

Notifying @ChaelKruip @michieldenhaan @redekok @marliekeverweij

**Comment by AlexanderWirtz** [comment]
After discussing this with @ChaelKruip we agreed that most non-energetic oil demand will actually be naphta and that it is possible to determine quite accurately how many PJ of H2 replace 1 PJ of naphta. 

I agree with the option 2 approach therefore. 

Note that the replacement is not necessarily 1:1, right?

**Comment by marliekeverweij** [comment]
> Note that the replacement is not necessarily 1:1, right?

I was actually thinking about replacing all carriers 1:1. I did not take into account the exact pathway from one carrier to another to be honest. I think this is indeed complicated, since you do not know exactly which part of the non-energetic fuel is needed (for H2 is obvious, but for oil less obvious).

Mabye we could do it 1:1 now and model it more realistic during the molecules-project?
