### ISSUE TITLE
Readability of the investment table should be improved

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3041]
I just opened the investment table and saw this :)

![Screen Shot 2019-05-28 at 17 02 29](https://user-images.githubusercontent.com/32833996/58488917-8a667e00-816a-11e9-8ed6-69b817f3fd54.png)

Before fixing it, this is maybe the right time to ask ourselves the questions:

- Do we want to keep the investment table? It is now a super long unclear list with numbers. 

- If we want to keep it: how could we improve it? Which numbers are really relevant? How could we organise it better?

Please let me know your opinion :) 

@AlexanderWirtz @ChaelKruip @jorisberkhout @redekok @MartLubben @DorinevanderVlies @michieldenhaan

**Comment by ChaelKruip** [comment]
This table is useful if you want to know which investments your scenario implies. To make it less long, we could investigate how to hide rows for which nothing has changed perhaps?

**Comment by michieldenhaan** [comment]
Maybe we can improve the translations/labels of the table somehow. Currently the translations are linked to the slider translations. For industry this means that 'gas heater' appears 8 times or so in table (one time for each subsector)

**Comment by marliekeverweij** [comment]
When somebody is going to update the investment table, could s/he also add the following greengas production technologies:
- energy_biogas_fermentation_wet_biomass
- energy_greengas_gasification_wet_biomass
- energy_greengas_gasification_dry_biomass

**Comment by marliekeverweij** [comment]
Would anybody like to pick up this issue before the deploy? :)

**Comment by marliekeverweij** [comment]
I have assigned @michieldenhaan ! Reassign when needed

**Comment by redekok** [comment]
> This table is useful if you want to know which investments your scenario implies. To make it less long, we could investigate how to hide rows for which nothing has changed perhaps?

@antw Would this be possible?

**Comment by antw** [comment]
> > To make it less long, we could investigate how to hide rows for which nothing has changed perhaps?
> 
> @antw Would this be possible?

Sure. A day or two to create a custom [table view](https://github.com/quintel/etmodel/blob/e02151751028a200fce7f5460ce5799c3d31bc9e/app/assets/javascripts/lib/views/html_table_chart_view.coffee) would be needed.

**Comment by redekok** [comment]
> > > To make it less long, we could investigate how to hide rows for which nothing has changed perhaps?
> >
> > @antw Would this be possible?
>
> Sure. A day or two to create a custom table view would be needed.

@ChaelKruip What are your thoughts on this?

**Comment by ChaelKruip** [comment]
> @ChaelKruip What are your thoughts on this?

I like the idea to hide rows that show no info but I would like to be able to keep the total overview as well. Even the investments that are already present in the start-year can be interesting.

Also, I think this is low priority compared to actual bugs present in the model.

**Comment by redekok** [comment]
> Also, I think this is low priority compared to actual bugs present in the model.

I agree! Closing this again.
