### ISSUE TITLE
CO2-footprint does not load on beta

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3043]
![image](https://user-images.githubusercontent.com/19907658/58940105-f05d9180-8778-11e9-8461-2cd51ef3f69f.png)

**Comment by ChaelKruip** [comment]
I cannot reproduce this. How did you get to this screen @DorinevanderVlies ?

**Comment by redekok** [comment]
I cannot reproduce this. How did you get to this screen @DorinevanderVlies ?

> I can, though. Maybe it's another caching problem?

**Comment by ChaelKruip** [comment]
> I can, though.

What are the steps?

**Comment by redekok** [comment]
Clicking on "Show region CO2 footprint" / "Bekijk CO2-voetafdruk":

![201906_screenshot](https://user-images.githubusercontent.com/5946498/58943196-88f71000-877f-11e9-91ed-f8ccc1025cb4.png)

**Comment by michieldenhaan** [comment]
I get the following (more informative) error on my local machine:
![etmodel test - NoMethodError at regionsbe 2019-06-05 12-28-19](https://user-images.githubusercontent.com/32056448/58949810-9c10dc80-878d-11e9-9664-7d172b9f4460.png)

Maybe related to https://github.com/quintel/etengine/commit/3b6972b163fc469c0362e2e7b1e4e79bda8d81ee @antw ?

**Comment by antw** [comment]
> Maybe related to quintel/etengine@3b6972b @antw ?

Good catch! I've fixed this in ETEngine.
