### ISSUE TITLE
Dashboard bio-footprint shows geo_id for non-countries

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3047]
For scenario's that are created for regions other than countries, the dashboard bio-footprint item shows the entire geo_id behind the value. Could it be the case that the ETM doesn't recognize anymore whether the scenario has been created for a country or another region? The settings menu also seems to be broken but I'm not sure why.

![image](https://user-images.githubusercontent.com/5946498/58962988-a0002700-87ac-11e9-906c-94b224c85b79.png)

![201906_screenshot](https://user-images.githubusercontent.com/5946498/58962664-f4ef6d80-87ab-11e9-90c5-5d0348d70eb8.png)

**Comment by antw** [comment]
Fixed by quintel/etengine@1aadb87. You'll need to start a new scenario for the bug to disappear, but after you do so everything should be fine.
