### ISSUE TITLE
Are the onshore wind and solar park slider settings unclear for users?

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3052]
Based on https://github.com/quintel/etmodel/issues/2912, the maximum slider values for onshore wind turbines and solar parks were set to the total land area for that specific region (https://github.com/quintel/etsource/pull/2003).

Accidentally (I think, at least), the input statement for onshore wind turbines ([`capacity_of_energy_power_wind_turbine_inland.ad`](https://github.com/quintel/etsource/blob/master/inputs/supply/renewable_electricity/wind_turbines/capacity_of_energy_power_wind_turbine_inland.ad#L14)) uses `AREA(onshore_suitable_for_wind)` again instead of `AREA(total_land_area)`, since https://github.com/quintel/etsource/pull/2010/. @DorinevanderVlies: was this a conscious choice?

Furthermore, a few of our users have been confused by our new approach for the maximum value of these sliders. For instance, in a NvdT scenario it is either not very clear for the user that the slider has actually been set or the user might think that this value is the slider minimum (instead of 0 MW). 

![20190613_screenshot](https://user-images.githubusercontent.com/5946498/59441915-95bbd980-8df9-11e9-80ae-e26d5fd2851e.png)

I'm not sure yet if we should do something about this? @AlexanderWirtz @jorisberkhout @ChaelKruip @DorinevanderVlies @MartLubben @michieldenhaan @marliekeverweij  What are your thought on this?

**Comment by DorinevanderVlies** [comment]
> @DorinevanderVlies: was this a conscious choice?

No, I think I used `AREA(onshore_suitable_for_wind)`  because I  used [`capacity_of_energy_power_wind_turbine_offshore.ad`](https://github.com/quintel/etsource/blob/ea912ae2244bca7f9b7423d08fa44697e659854f/inputs/supply/renewable_electricity/wind_turbines/capacity_of_energy_power_wind_turbine_offshore.ad) as basis for the sider max query.

> Furthermore, a few of our users have been confused by our new approach for the maximum value of these sliders. 

Would it be an idea to use `AREA(onshore_suitable_for_wind)` (or similar for other wind techs) and widen the setting of that parameter to a theoretical maximum. So users are not limited by the slider max, but reasonable use of wind is visible in the slider bar.

**Comment by redekok** [comment]
> widen the setting of that parameter to a theoretical maximum

What would you consider a theoretical maximum here? The total land area minus the area where residences, utility, highways, etc. are located? Do you think we'd be able to (fairly) easily collect this data for all our datasets?

**Comment by marliekeverweij** [comment]
> What would you consider a theoretical maximum here? The total land area minus the area where residences, utility, highways, etc. are located? Or would you take more restrictions into account, e.g. "at least 200 m from the built environment"?

Are we then not going back to where we came from: the areable land? 😉 When we would do that then we can only set a few wind turbines for urbanized municipalities and that was not desirable.

**Comment by redekok** [comment]
> Are we then not going back to where we came from: the areable land? 😉 When we would do that then we can only set a few wind turbines for urbanized municipalities and that was not desirable.

Yes, that was exactly my thought. However, I'm not sure if there would be some kind of midway? Since the current situation is not 100% desirable either, I guess..
