### ISSUE TITLE
Offshore wind curve nl 2015 incomplete (results in zero's for significant periods)

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3055]
![image](https://user-images.githubusercontent.com/19907658/59606655-fb69d780-9111-11e9-94ad-8475b13ae33f.png)

**Comment by marliekeverweij** [comment]
This issue is not relevant anymore as we have used different sources to generate this curve: Solar Radiation Data for PV (SoDa) and Ecofys data for wind.
