### ISSUE TITLE
Offshore wind curve for nl 2016 shows significant increase over the year

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3058]
This curve is based on measured data.
For NL the installed capacity probably increased during 2016.

![image](https://user-images.githubusercontent.com/19907658/59606919-8ea30d00-9112-11e9-9969-8ad854355bd8.png)

**Comment by ChaelKruip** [comment]
@DorinevanderVlies, I'm unclear about this issue:
- Is there a problem? If so, what is it?
- What kind of action is required? In other words: when can we close this ticket again?

**Comment by DorinevanderVlies** [comment]
> Is there a problem? If so, what is it?

Problem: curve is unrealistic. The peaks in December are nearly twice as high as in January. 

> What kind of action is required? In other words: when can we close this ticket again?

Can be fixed by:

- Correcting the curve for the change in installed capacity
- Using a different data source which shows no big fluctuations during the year.
