### ISSUE TITLE
We should show the scenario title in an opened scenario

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3060]
(Stealing the idea of @MartLubben )

Currently when you open a saved scenario, you can only see the country and end year for which the scenario is made:
![Screen Shot 2019-06-17 at 16 55 43](https://user-images.githubusercontent.com/32833996/59614307-cadd6a00-9120-11e9-8e92-9d50741afca7.png)

This is quite confusing when you have opened multiple scenarios for the same country and end year! Therefore, it would be great to also show the title of the scenario in the ETM.

Maybe we can add the scenario title to the same locations as where the country and end year are now located:
![Screen Shot 2019-06-17 at 17 07 21](https://user-images.githubusercontent.com/32833996/59615953-c49cbd00-9123-11e9-9834-e25382df9e60.png)
(I've also moved the 'Information'-drop-down-menu to the right, because I think 'Settings' is more important!)

What do you think? And do you have other/better suggestions for where to put the scenario title? @antw @ChaelKruip @michieldenhaan @AlexanderWirtz @jorisberkhout @redekok @DorinevanderVlies @sfp-kemp @MartLubben

**Comment by sfp-kemp** [comment]
Ik pak 'm op!

**Comment by marliekeverweij** [comment]
I think that it is achievable to add the scenario title to the ETM before the deploy on July 10th, therefore I have added the deploy-milestone to this issue. Please let me know when I am wrong!

**Comment by marliekeverweij** [comment]
Will it be possible to deploy this to BETA before the feature freeze on Friday?

**Comment by antw** [comment]
Probably, but I'm not so keen on cramming it into the options section in the header. However, I don't currently have any better ideas.

**Comment by marliekeverweij** [comment]
> Probably, but I'm not so keen on cramming it into the options section in the header

I agree with that, there are better places to think of.

But, I think adding the scenario title is already a huge improvement for the current users!! Is it an idea to deploy this idea to LIVE for now and think about relocating the scenario title to a better place after the deploy? Shall I open a new issue for that?

**Comment by antw** [comment]
I just realised that Steven already sent a pull request for this feature. It needs a few changes before merging and I'm unlikely to be able to get to them today; if I can do so tomorrow I will, otherwise it might have to wait.
