### ISSUE TITLE
Feedback form does not work

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#3067]
As pointed out by an external user. You can fill out the following form, but nothing happens when you hit the OK button. This happens both on BETA and LIVE.

You can find this form through the information menu ('Information -> Feedback' or 'Informatie -> Reacties').

![Screenshot 2019-07-02 at 11 03 18](https://user-images.githubusercontent.com/4669028/60499651-3430b180-9cb9-11e9-9025-138906bbd1fc.png)

**Comment by michieldenhaan** [comment]
That's a feature

**Comment by redekok** [comment]
I'm not really sure how to fix this but I guess @antw does? 

While checking out some of the scripts related to the feedback form, I found out that the feedback messages are still redirected to John en Dennis (besides our general info@energytransitionmodel.com): https://github.com/quintel/etmodel/blob/master/app/models/notifier.rb#L4

We might want to change this. :) Whose mail addresses should we use? Or would it be enough to only redirect the feedback messages to the info mail address (which probably redirects the messages to a specific Quinteller)?

**Comment by jorisberkhout** [comment]
Well spotted, @redekok ! I suggest that we forward the feedback mails to info@quintel.com. Various colleagues including myself keep an eye on that mailbox (or, in fact, the mailbox of post@quintel.com to which info@quintel.com is an alias).
