### ISSUE TITLE
Bio dashboard item shows area name for derived datasets when opening saved scenario

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3073]
When opening a saved scenario for a local dataset the biomass dashboard item looks like this:

![beta-pro energytransitionmodel com - Energietransitiemodel - Je eigen onafhankelijke, volledige en op feiten gebaseerde energie… 2019-07-04 09-30-17](https://user-images.githubusercontent.com/32056448/60647661-746d6c80-9e3e-11e9-8c6e-574973038b9f.png)

Issue related to: https://github.com/quintel/etmodel/issues/3047

Edit: To clarify, when opening a new scenario everything's fine but when opening a saved scenario (even a recently saved one) the bug still appears

**Comment by marliekeverweij** [comment]
Good one! I think this should be fixed before the deploy, so I added it to the milestone. Do you have time to fix this @antw ? Or shall we ask @sfp-kemp ?
