### ISSUE TITLE
The chart "Properties of combined heat and power (CHP) plants" does not load (both on beta and on live)

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3076]
When I open the chart `Properties of combined heat and power (CHP) plants` on the Beta or on the Live server the chart freezes at "loading".

![image](https://user-images.githubusercontent.com/19907658/60717080-43b23380-9f21-11e9-90b2-5d66de04eff1.png)

**Comment by michieldenhaan** [comment]
Nice catch, it's still referring to the micro chp/fuel cell queries which have been removed during the recent heat project

![beta-pro energytransitionmodel com - Energietransitiemodel - Je eigen onafhankelijke, volledige en op feiten gebaseerde energie… 2019-07-05 13-24-31](https://user-images.githubusercontent.com/32056448/60719544-4ebc9200-9f28-11e9-9180-3cffd7478223.png)
