### ISSUE TITLE
Imported electricity curve does not recognize BOM

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3080]
Excel's default file encoding for CSV is UTF-8 with BOM. Uploading a CSV to the ETM gives the following error:

![beta-pro energytransitionmodel com - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario build… 2019-07-08 10-24-22](https://user-images.githubusercontent.com/32056448/60794676-92064300-a16a-11e9-860e-dac6a4da86af.png)

When changing the encoding to plain UTF-8 (no BOM) the error disappears. As most of our users will probably create price curve CSVs using Excel, is it possible to skip over the byte order mark when validating the curve?

**Comment by antw** [comment]
@michieldenhaan I don't have a copy of Excel; would you mind sending me the offending file?

**Comment by michieldenhaan** [comment]
Thanks @antw, you're the BOM 🎉
