### ISSUE TITLE
MYC: use should be able to select all his/her own scenario's

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3081]
When I open the MYC-starting interface the option "Start a new session" shows me an incomplete list of scenarios.

- Not all recent scenarios are present in the list
- It seems that only national scenario's are shown
- Local vs Global does show me a complete list of my scenarios

Screenshot of scenarios I can choose from:
![image](https://user-images.githubusercontent.com/19907658/60797066-e7445380-a16e-11e9-85ea-214485adb869.png)

The local vs. Global starting page does show me all scenarios I created:
![image](https://user-images.githubusercontent.com/19907658/60796902-992f5000-a16e-11e9-87b8-095471d20141.png)

**Comment by antw** [comment]
It shows Netherlands/2050 scenarios only.

* We don't show other regions at this time because MYC doesn't auto-scale values in the charts. This means that particularly small regions will likely format numbers in a way which isn't useful to the user. I'm happy to experiment with this further, because it may not be an issue in practice.

* We don't show scenarios with an end year other than 2050 because we need to create scenarios for 2040 and earlier; this currently isn't possible if the scenario is for an earlier date. This too can likely be resolved eventually.

**Comment by ChaelKruip** [comment]
> We don't show other regions at this time because MYC doesn't auto-scale values in the charts. 

This feature will likely be used on the municipality level a lot. We might get some requests about this soon. Including @redekok

**Comment by redekok** [comment]
> This feature will likely be used on the municipality level a lot.

Indeed, which is why I think it would be a good idea to experiment with auto-scaling the values in the charts, if time permits. How much time would it cost you to fix this?

**Comment by antw** [comment]
I've enabled the ability to create an MYC session using a 2050 scenario from *any* region. The smallest dataset we have (GM0748_bergen_op_zoom) results in charts/values which are not quite as useful as we might like, but it is useable:

![Screen Shot 2019-07-08 at 15 26 51](https://user-images.githubusercontent.com/4383/60818095-dc041e80-a194-11e9-8c9a-771d31cbb264.png)

Doing some ETModel-style unit scaling (e.g. converting MT to kT) would improve things.

**Comment by redekok** [comment]
Looks good! :)

> Doing some ETModel-style unit scaling (e.g. converting MT to kT) would improve things.

That would be great! Do you think you could make this ETModel-style unit scaling work before the deploy?

**Comment by antw** [comment]
> Do you think you could make this ETModel-style unit scaling work before the deploy?

Likely not, but MYC is a separate application which means we can implement this after the deploy without any consequences for the rest of the ETM.
