### ISSUE TITLE
Cooling curve for households and buildings should be specific so seasonal fluctuations are represented

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3082]
Cooling in winter is bigger than cooling in the summer.
![Screenshot 2019-07-08 at 11 00 24](https://user-images.githubusercontent.com/33415156/60797531-b6b0e980-a16f-11e9-93c0-7d7eac18d18c.png)

Both in households and buildings this issue occurs

I increased the cooling demand to 10%/year to make it more visible in the chart

**Comment by DorinevanderVlies** [comment]
The cooling curve is E1A for households and E3A for buildings. 

See this text for explanations: https://github.com/quintel/etdataset/tree/master/curves/demand/households/cooling

**Comment by MartLubben** [comment]
@DorinevanderVlies I think I do understand the reasoning. However I am not sure if I understand the choice. 

A major power of the ETM is the agenda setting of yet unseen or underestimated energy flows  which could change towards the future. With this perspective I would rather accept the risk of overestimating cooling peaks, than use the E1A and E3A profiles which are also wrong.  

Using the E1A and E3A profiles for cooling could be statistically more right for the present, but will not create a better estimation for future scenarios with high cooling demand. The old way has the risk of over estimation. In my opinion this is not always bad.

**Comment by MartLubben** [comment]
@DorinevanderVlies After the team meeting a lot is clear. I propose to not close this issue, but remove the milestone. What do you think?

**Comment by DorinevanderVlies** [comment]
I added the milestone NL2017 update
