### ISSUE TITLE
Climate slider and cold winter sometimes create an error 

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3083]
When increasing the temperature in blanc NL 2050 scenario and toggle the cold winter, the ETM returns the following error in Inspect> Network> repsonse 

![Screenshot 2019-07-08 at 11 22 47](https://user-images.githubusercontent.com/33415156/60799084-be25c200-a172-11e9-9fe2-802bdd480334.png)

The interesting thing is that is does not occur every time

**Comment by michieldenhaan** [comment]
I think this has been fixed now, probably related to https://github.com/quintel/etmodel/issues/3079. I don't get the error when following the steps above.
