### ISSUE TITLE
The non-energetic sliders in the chemical industry do not have tooltips yet

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3084]
![image](https://user-images.githubusercontent.com/5946498/60800541-adc31680-a175-11e9-997a-30e437e78a2a.png)

**Comment by michieldenhaan** [comment]
Fixed!

"The chemical industry traditionally uses crude oil as the main carbon feedstock for the production of basic chemicals (such as methanol and ethylene). In the future this oil may be replaced with other sources, like biomass or hydrogen. These sliders allow you to change the future feedstock mix. What will be the share of CARRIER feedstock in the chemical industry of the future?"
