### ISSUE TITLE
(Total) cost unaffected by hourly import price curve

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3086]
The cost of imported electricity in the (yearly) charts/dashboard item is unaffected by the import price curve. Costs are determined by the cost slider, regardless of which import price curve is used.

Blank scenario, import price set by slider (35 eur/MWh):

![beta-pro energytransitionmodel com - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario build… 2019-07-08 12-30-09](https://user-images.githubusercontent.com/32056448/60803822-5ffddc80-a17c-11e9-98f5-82941249a20f.png)

Uploading curve with 10 eur/MWh average, no effect on dashboard/cost chart even though import price is lower:

![beta-pro energytransitionmodel com - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario build… 2019-07-08 12-30-22](https://user-images.githubusercontent.com/32056448/60803876-7c9a1480-a17c-11e9-8484-15c4687ad446.png)

Resetting curve, changing slider to 10 eur/MWh, dashboard/cost chart do change now:
![beta-pro energytransitionmodel com - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario build… 2019-07-08 12-30-38](https://user-images.githubusercontent.com/32056448/60803921-95a2c580-a17c-11e9-91c5-c9e5c76c157b.png)

Reuploading curve (10 eur/MWh). Curve is the same as in 2nd screenshot but now costs are lower because slider has been lowered in 3rd screenshot.
![beta-pro energytransitionmodel com - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario build… 2019-07-08 12-30-48](https://user-images.githubusercontent.com/32056448/60804039-e0244200-a17c-11e9-819e-c855fbd8fdd2.png)

**Comment by antw** [comment]
I'm guessing the queries use the `cost_per_mj` attribute for imported_electricity to calculate the total costs, so this is an oversight on my part. I guess we can set an updated value after the merit order has run which should fix this.

I'll investigate.
