### ISSUE TITLE
The sankey 'future energy flows' should not show export of coal

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3087]
The cause is coal gas in the steel industry. Which is not exported in reality but burned. 

![Screenshot 2019-07-08 at 16 38 55](https://user-images.githubusercontent.com/33415156/60819220-808b5e00-a19f-11e9-8e1f-d0d89c5d131c.png)

**Comment by michieldenhaan** [comment]
Closed in recent steel update: https://github.com/quintel/etsource/pull/2576
