### ISSUE TITLE
Local vs. Global: user should not be directed to admin-section after log-in

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3088]
When you're not logged in yet, Local vs. Global directs you to the log-in page. After logging in you are directed to the admin-section, but it would be better to go to Local vs. Global!
**1.**
![Screen Shot 2019-07-09 at 09 21 59](https://user-images.githubusercontent.com/32833996/60867612-97779200-a22b-11e9-8c52-42b04e125649.png)
**2.**
![Screen Shot 2019-07-09 at 09 22 13](https://user-images.githubusercontent.com/32833996/60867617-99d9ec00-a22b-11e9-94fd-d637a6eb714a.png)
**3.**
![Screen Shot 2019-07-09 at 09 22 20](https://user-images.githubusercontent.com/32833996/60867621-9c3c4600-a22b-11e9-84e8-8a55a41e0a4e.png)

**Comment by antw** [comment]
This is because you're an admin user. Non-admins will be redirected back to the previous page.

I do think we should change this and add an "Admin" button somewhere in the ETM header, but I'm not sure if it needs to be done for this deploy. If I get time, I'll take care of it.

**Comment by antw** [comment]
Closed by 383c2ad8a130a7bc8891570a706f2cf19e7b0eb9.

A link to the admin section has been added to the settings menu instead. Non-admins won't see it.

![Screen Shot 2019-07-09 at 13 02 59](https://user-images.githubusercontent.com/4383/60886459-fc41e500-a249-11e9-92c9-edae34031ec9.png)
