### ISSUE TITLE
Tooltips of supply sliders should be revised

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3090]
Most supply sliders still have the following text in the tooltip: 
![Screen Shot 2019-07-09 at 09 45 17](https://user-images.githubusercontent.com/32833996/60869555-7ca71c80-a22f-11e9-8deb-02384ce08f4d.png)

**Comment by DorinevanderVlies** [comment]
Changed content of all capacity related sliders. Example:

![image](https://user-images.githubusercontent.com/19907658/60881675-78d2c480-a246-11e9-8e66-3032ebd7df42.png)
