### ISSUE TITLE
The electricity infrastructure costs slider do not have tooltips

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3091]
![Screen Shot 2019-07-09 at 10 11 56](https://user-images.githubusercontent.com/32833996/60871175-83835e80-a232-11e9-8ded-a2b42e7bdff6.png)

**Comment by michieldenhaan** [comment]
Fixed!

"These sliders allow you to change the future (average) grid expansion costs for each voltage level. The default settings for the Netherlands are based on the current average expansion costs as reported in the study 'Grid for the Future', CE Delft (2017)."
