### ISSUE TITLE
Factsheet should link to load saved scenario

### ISSUE THREAD

**Issue by sfp-kemp** [quintel/etmodel#3104]
Instead of load scenario

**Comment by antw** [comment]
I'm not sure about this myself.

Saved scenarios are currently not completely private (you can view them by editing the URL) nor can they be deleted, but both of these could change in the future. Factsheets are commonly printed out and distributed, so it's important that the link is available.

The scenario link (/scenarios/12345) is a permalink that should never stop working

**Comment by sfp-kemp** [comment]
I agree that links like "/scenarios/12345" should keep on working! The change I'm proposing is one to the href in the factsheet, not to the controller handling the scenario route. 

The reason for this proposition is that some confusion could arise if several factsheets about the same region circulate within an organization. Its hard to differentiate between them and to me there is no clear way to add distinguishing data the current route scheme. 

The current link always points to a scenario with the name API: 
![Screenshot 2019-07-16 at 10 08 43](https://user-images.githubusercontent.com/51709773/61278440-83480d80-a7b4-11e9-8108-1548a45ca93f.png)

I'm not sure if I introduced this behavior or if it has always been like this but I think linking to the following page would be better. 

![Screenshot 2019-07-16 at 10 30 21](https://user-images.githubusercontent.com/51709773/61278600-c4402200-a7b4-11e9-9e2d-dd41ba108c1e.png)
The best thing is that all the routing for the following page already exists so we "just" have to change the href. 

I'm still trying to figure out a solution for your concerns about future features on the saved_scenarios.
