### ISSUE TITLE
Add link to factsheet to "show saved_scenario" page

### ISSUE THREAD

**Issue by sfp-kemp** [quintel/etmodel#3107]
At the moment user's cant create factsheets from saved_scenarios.

the pages with the following path: [/saved_scenarios/:id](https://beta-pro.energytransitionmodel.com/saved_scenarios/4369) should provide a link to https://beta-pro.energytransitionmodel.com/scenarios/:id.

**Comment by michieldenhaan** [comment]
Closing, fixed in https://github.com/quintel/etmodel/pull/3108
