### ISSUE TITLE
Interconnector capacity of local datasets should have local capacity after resetting slider

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3114]
As explained in [this issue](https://github.com/quintel/etsource/issues/1757): the interconnector capacity for local datasets uses the NL value in the start year instead of the local scaled value. When you set a certain value for the interconnector capacity and then reset the slider, the scaled value is used on LIVE.

However, this is not the case currently on BETA: when you reset the slider the national interconnector capacity is used again.

1. **Opening local dataset (in this case Rotterdam) -> interconnector capacity 5.85 GW (national value)**
![Screen Shot 2019-08-19 at 14 40 35](https://user-images.githubusercontent.com/32833996/63266805-06b3bd80-c291-11e9-98e4-97737097977a.png)

2. **Setting interconnector capacity to certain value**
![Screen Shot 2019-08-19 at 14 49 34](https://user-images.githubusercontent.com/32833996/63266628-a15fcc80-c290-11e9-8840-6b1fab7e1737.png)

3. **Resetting the slider -> interconnector capacity is again 5.85 MW (national value)**
![Screen Shot 2019-08-19 at 14 49 21](https://user-images.githubusercontent.com/32833996/63266664-b4729c80-c290-11e9-9bf6-bae3b94c15d5.png)

Notifying @ChaelKruip

**Comment by ChaelKruip** [comment]
Good catch @marliekeverweij! 

Just to be clear: the expected/correct behaviour is that it resets to the scaled NL value?

**Comment by marliekeverweij** [comment]
Yes!

**Comment by antw** [comment]
This is because of quintel/etmodel@8a7ed72, which was a fix for #3110. The reset button now removes the input setting from the scenario, returning it to it's default state. It used to send the start value, which in the case of the interconnector is _not_ the same as the default value.

Fixing quintel/etsource#1757 will probably fix this.
