### ISSUE TITLE
Add chart which shows final demand and/or primary demand per energy carrier 

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3115]
@DorinevanderVlies added this to-do to BC two months ago:

Input from client: it is currently difficult to get a quick overview of total final/primary demand per carrier.

Users (including me) often manually sum numbers from the final demand mekko or move their cursor over the Sankey diagram (which only shows primary demand).

**Comment by ChaelKruip** [comment]
Can you pick this up @marliekeverweij ? I think this is very useful!
