### ISSUE TITLE
Links in scenario descriptions are broken

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3119]
In many scenario descriptions we use link with the following format:

`<a href="URL">description</a>`

Both on Live and on Beta they are currently in text: `<a href=“URL”>description` [Example](https://pro.energytransitionmodel.com/scenarios/341741%22%3ENoorderplantsoenbuurt%20Variatie%203):
 
![image](https://user-images.githubusercontent.com/19907658/63750956-c49d0400-c8ae-11e9-9230-9eb7afb3a701.png)

@antw do you know how this can be fixed?

**Comment by antw** [comment]
Links became disallowed when I updated the Markdown parser a month ago. The reason being that we can't guarantee the safety of external sites, and someone could use a link from a scenario description to send someone to a bogus login page to steal their email address and password.

However, clearly links to the ETM are safe, so I've relaxed the restriction to allow these.

Some of our presets contain links to external sites, mostly to netbeheernederland.nl (Net voor de Teokomst presets and newscenter.philips.com (energy productivity presets). For the time being, the links will be replaced with just the text inside the link. We could allow external links in preset descriptions (but not scenarios), but this would require a couple of changes to ETModel and ETEngine; I'm not sure if this is worth doing?

**Comment by DorinevanderVlies** [comment]
> However, clearly links to the ETM are safe, so I've relaxed the restriction to allow these.

Thanks!

> I'm not sure if this is worth doing?

I'm fine with this solution

**Comment by DorinevanderVlies** [comment]
> We could allow external links in preset descriptions (but not scenarios), but this would require a couple of changes to ETModel and ETEngine; I'm not sure if this is worth doing?

I have some second thoughts about this. Last week we added the "klimaatakkoord" scenario's to the presets. This preset contains external links which now look very unprofessional.

I expect that we will be adding some more presets in the coming month and that they will start to play a more important role (for example when we implement the context-scenario feature).

So, it would be nice to be able to add a working link to a preset description.

**Comment by marliekeverweij** [comment]
Is this issue still relevant and should it be picked up before the deploy? @DorinevanderVlies @antw

**Comment by DorinevanderVlies** [comment]
Not urgent for the deploy. I'll add it to the longlist of development projects
