### ISSUE TITLE
Resetting slider for saved scenario resets energy flows to blank scenario

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3121]
When resetting a slider in a saved scenario the slider value changes back correctly but the energy flows no longer match up with the slider setting. It looks like the energy flows are reset to/correspond with the slider value of a blank scenario even though the slider itself displays the saved scenario value.

E.g. Net voor de Toekomst Nationaal green gas slide

_Original scenario situation_: 63.3% green gas in network according to scenario
![beta-pro energytransitionmodel com - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario build… 2019-09-02 15-44-40](https://user-images.githubusercontent.com/32056448/64118824-bd876180-cd98-11e9-9b22-716e3e46f47e.png)

Changing green gas to 100%
![beta-pro energytransitionmodel com - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario build… 2019-09-02 15-44-51](https://user-images.githubusercontent.com/32056448/64118840-c5df9c80-cd98-11e9-82d0-cb7140341679.png)

Reset slider. Slider value is same before and after reset (63.3%) but as the chart shows the energy flows are not the same as in the original situation. In fact the energy flows are equal to a blank NL2015 scenario with little to no greengas.
![beta-pro energytransitionmodel com - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario build… 2019-09-02 15-45-04](https://user-images.githubusercontent.com/32056448/64118852-cc6e1400-cd98-11e9-8e84-722818850791.png)

**Comment by antw** [comment]
This will be related to the fix for #3110. I can likely resolve this in ETEngine.
