### ISSUE TITLE
Unit €/MWh should be entirely visible on chart axis

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3123]
Currently only `€/M` is visible instead of `€/MWh` in chart 244: Production costs and price of green gas:
![Screen Shot 2019-09-03 at 15 41 37](https://user-images.githubusercontent.com/32833996/64178428-c132eb00-ce61-11e9-9128-53357224fe56.png)

**Comment by antw** [comment]
Fixed in 4c1d995.
