### ISSUE TITLE
Primary energy demand mekko should be updated with new biomass carriers

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3127]
Now the primary energy demand mekko does not load! Because the queries still refer to old biomass carriers like:
- corn
- manure
- woody biomass
- wood

**Comment by marliekeverweij** [comment]
Would anybody like to pick up this issue before the deploy? :)

**Comment by redekok** [comment]
I can fix this!

**Comment by marliekeverweij** [comment]
This is done right? :)

**Comment by redekok** [comment]
Yes it is, closing this!
