### ISSUE TITLE
Plant profitability table seems broken on beta and Live

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#3129]
I was looking at this table on the Live server and came across this: 
![image](https://user-images.githubusercontent.com/308563/65450346-31b7a100-de3d-11e9-8024-301a1cf47a2d.png)

There is some kind of problem with the calculation of the availability percentage and the profitability. At the same time the dashboard value itself seems fine. Same problem on Beta.

notifying @ChaelKruip 

re-assign as needed

**Comment by michieldenhaan** [comment]
@antw Do you have time to take a look at this? I would like to use this table next week for a workshop. I looked into it but couldn't quite figure out what's going wrong.
