### ISSUE TITLE
PICO iframe doesn't load

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3130]
The PICO iframe doesn't load anymore due to changes in the init json:
![image](https://user-images.githubusercontent.com/5946498/65490348-47fd4580-dead-11e9-8f9d-22b9ea18f1e5.png)
The minimap (https://pico.geodan.nl/pico/minimap/map_windmodule.html) now i) allows you to select a municipality, province or RES region, ii) change the default / start values of restrictions, and iii) read the restriction values when closing the iframe (in order to be able to reopen the iframe a second time with the same restrictions as before).

@sfp-kemp are you able to fix this?

**Comment by sfp-kemp** [comment]
@redekok volgens mij werkt dit nu goed!
