### ISSUE TITLE
Update list of preset scenario's

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3131]
The current list of preset scenario's is outdated.

I propose to remove the scenario's with a red number:
![image](https://user-images.githubusercontent.com/19907658/65509751-7857da80-ded3-11e9-9daf-c0d9927e6564.png)

Curious about your ideas @marliekeverweij @MartLubben @michieldenhaan @redekok @ChaelKruip @jorisberkhout @AlexanderWirtz

**Comment by AlexanderWirtz** [comment]
I am even wondering if we should continue #5. Perhaps you and Joris have already discussed this with Marjan Minnesma? 
In my opinion that scenario needs a fundamental rethink.

**Comment by DorinevanderVlies** [comment]
> I am even wondering if we should continue #5. Perhaps you and Joris have already discussed this with Marjan Minnesma? In my opinion that scenario needs a fundamental rethink.

Good point. We raised this issue last week. Fact is that this scenario is still being used by Urgenda. Therefor I propose to keep it in the presets and at the same time try to get going with a fundamental rethink.

**Comment by MartLubben** [comment]
We still use the example of the Energieakkoord (2023) in lectures, just to show how the costs of carriers affects the total costs of the energy system. I know it is outdated, however can't we make a library where users (including ourselves) can find these scenario's. I think it is still valuable to explore older scenario's. .

**Comment by DorinevanderVlies** [comment]
Closing this issue after a short discussion with @MartLubben .
The old preset scenario's are still available (and can be used for presentations), but they are no longer displayed on the front page
