### ISSUE TITLE
Technology spec viewer should be available for flex technologies

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#3135]
![image](https://user-images.githubusercontent.com/1303760/65770224-ee5b7c00-e135-11e9-9235-e868d45a78cf.png)
opens an empty pop-up:
![image](https://user-images.githubusercontent.com/1303760/65770258-00d5b580-e136-11e9-9d67-05bebe4ab03d.png)

**Comment by antw** [comment]
The node(s) need to be have one of the following `presentation_group`s:

* `biomass`
* `carbon_capturing`
* `chps`
* `electricity_production`
* `heat_pumps`
* `hydrogen_production`
* `p2g`
* `p2h`
* `p2kerosene`
* `traditional_heat`

If none of these are satisfactory, see ETEngine's [`Api::V3::ConvertrerPresenterData`](https://github.com/quintel/etengine/blob/master/app/models/api/v3/converter_presenter_data.rb).

**Comment by ChaelKruip** [comment]
@antw thanks for the clear explanation.

I think we should add a new p2p presenter group which shows some new items:
* the charging capacity (input) in MW
* the storage volume in MWh
* the round-trip efficiency in % (this one is tricky as it consists of an input efficiency and an output efficiency in the ETM)

@noracato could you try your hand on adding this new presenter group and adding the P2P technologies to this group?
* household batteries
* OPAC
* large scale batteries
