### ISSUE TITLE
Scenario report still refers to old queries 

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3136]
The scenario report still refers to old biomass primary demand queries, such as `primary_demand_of_corn_in_bunkers` and `primary_demand_of_wood_in_agriculture`. This is the case for the following carriers: corn, manure, dry biomass and wood.

**Comment by marliekeverweij** [comment]
Assigning @MartLubben , re-assign when you want to :)

**Comment by MartLubben** [comment]
@redekok I guess this is solved with: https://github.com/quintel/etmodel/pull/3144?

Could we close it?
