### ISSUE TITLE
The hourly electricity demand curve of small datasets shows white areass

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3138]
For small dataset the hourly electricity demand curve shows white areas.
For larger datasets (province / countries) the curve looks fine.

Example De Bilt:

![image](https://user-images.githubusercontent.com/19907658/65973143-19faa100-e46b-11e9-9d8a-e5e32fabee1d.png)

Example Meijerijstad:
![image](https://user-images.githubusercontent.com/19907658/65973334-73fb6680-e46b-11e9-98cb-2b1ea54cf459.png)

@antw do you know how this issue originates?
My guess is that rounding of values might play a role

notifying @MartLubben

**Comment by redekok** [comment]
I think it relates to https://github.com/quintel/etsource/issues/1944.

(That issue should have been written for ETModel instead of ETSource.)

**Comment by DorinevanderVlies** [comment]
Closing this as it is a duplicate. Thanks @redekok
