### ISSUE TITLE
PICO-ETM interaction: regional datasets should not use all of NL for potential

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3141]
For a region the PICO map takes the whole of The Netherlands into account.
I would expect that just the potential of my region is shown and imported in my scenario.

**Example for De Bilt**
![image](https://user-images.githubusercontent.com/19907658/66191620-121b4680-e68f-11e9-895e-1341a0e24924.png)

**Comment by redekok** [comment]
@sfp-kemp Is this a bug in our code or in the PICO library?

**Comment by marliekeverweij** [comment]
Is this issue deploy critical or not?

**Comment by redekok** [comment]
IMO this is deploy critical. @sfp-kemp what are your thoughts on this?

**Comment by marliekeverweij** [comment]
Steven and I have temporarily removed the PICO-link from BETA. We'll put the link back when this issue is fixed. Then we can still deploy today :)

**Comment by redekok** [comment]
Meaning that the ETM-PICO interaction won't be available on our LIVE-server before the next deploy, right?

**Comment by marliekeverweij** [comment]
I think we could cherry-pick the fix + add link again (when the bug is at our side) or simply add the link again (when the bug is in the PICO library). So then we do not have to wait for the next deploy. What do you think?

**Comment by redekok** [comment]
Sounds good to me!

**Comment by sfp-kemp** [comment]
Fixed
