### ISSUE TITLE
PICO-ETM interaction: this feature should also be available when language is set to English

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3142]
Currently this feature is only available when language is set to Dutch.
I understood from @redekok that this is done intentionally because the language of PICO is Dutch.

However, I reckon some of the Dutch users use ETM with language set to English. It would be a pity if they miss this nice feature!

I therefor propose to enable this feature when language is set to English. We can add a warning that the feature itself is in Dutch. For example like this:

![image](https://user-images.githubusercontent.com/19907658/66192968-e6e62680-e691-11e9-8a27-5b00bd13f473.png)

**Comment by redekok** [comment]
> However, I reckon some of the Dutch users use ETM with language set to English. It would be a pity if they miss this nice feature!

I agree, I'm in favour of your suggestion!

**Comment by DorinevanderVlies** [comment]
Closing this issue.

I implemented the change shown above. Please re-open or open a new issue when you disagree.
