### ISSUE TITLE
Should we remove the biofootprint chart from the scenario report?

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3143]
The biofootprint chart has been hidden on BETA since the previous biomass project. Should we also remove it from the scenario report?

![image](https://user-images.githubusercontent.com/5946498/66200905-582dd580-e6a2-11e9-9939-7478e1720f6c.png)

@marliekeverweij, @MartLubben, what are your thoughts on this?

**Comment by marliekeverweij** [comment]
Yes, I agree that it should be removed from the report!
