### ISSUE TITLE
Investment table translations should be more intelligible

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3147]
The translations of the investment table are currently linked to the slider translations. Because of this, it is not always clear which row in the table refers to which converter. E.g. we have multiple 'coal heaters' in the industry section but it is not clear which one refers to which industrial subsector. We can solve this by adding custom translations for the ambiguous entries.

![localhost - Energietransitiemodel - Je eigen onafhankelijke, volledige en op feiten gebaseerde energiescenario  2019-10-07 09-48-25(1)](https://user-images.githubusercontent.com/32056448/66293786-b992b600-e8e7-11e9-99df-deb5ce138b2b.png)

NOTE: To update the investment table, use the script! https://github.com/quintel/modeling_experiments/blob/master/query_generation/investment_table.py

**Comment by redekok** [comment]
@marliekeverweij: I'm afraid I won't be able to fix this before the deploy. Is that ok with you?
