### ISSUE TITLE
Excess electricity chart does not display losses of underground pumped storage 

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3150]
![pro energytransitionmodel com - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario builder  2019-10-09 17-35-13](https://user-images.githubusercontent.com/32056448/66496820-c9fb8a00-eabb-11e9-8762-362d2d47b23b.png)

**Comment by marliekeverweij** [comment]
Closed with https://github.com/quintel/etsource/commit/1b48892e23dae9ef208ff726ec1ce3fb5807a27a
