### ISSUE TITLE
Create a Dutch translation for 'Network gas' in chart picker

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#3160]
It says Network gas, now in the Dutch version.
![image](https://user-images.githubusercontent.com/308563/68655860-13af1880-0531-11ea-9062-b2f9a743a437.png)

**Comment by michieldenhaan** [comment]
Closed via https://github.com/quintel/etmodel/commit/e39cadd99554fb9df4b550ef5b11fab76306e5b2
