### ISSUE TITLE
Description of weather years makes it hard to distinguish 1987 and 1997

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#3161]
Both in essence say it was quite cold and there was little wind generation. I am being unfair, as the FLH and average temperature paint a different picture, but perhaps we could try to be a little more clear as to what makes these 3 weather years so different.

**Comment by marliekeverweij** [comment]
I have updated the descriptions for 1997 and 1987: https://beta-pro.energytransitionmodel.com/scenario/flexibility/flexibility_weather/extreme-weather-conditions
