### ISSUE TITLE
It would be great if the profiles used for weather data were exportable

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#3162]
I love the weather conditions feature. Love it. I do find myself wondering what data is behind it. It would be great if users could download the weather data to a CSV, so they can plot it. I am thinking:
- temperature curves
- wind onshore, coastal and offshore curves
- solar PV curves (and later solar thermal)

Alternatively, these files could be placed in the documentation section of this feature (which I haven't been able to find).

**Comment by AlexanderWirtz** [comment]
Aha, the documentation is here: https://github.com/quintel/etdataset/blob/weather_years/curves/supply/wind/script/weather_years/README.md

**Comment by redekok** [comment]
The CSV is actually already present in the datasets on ETSource; it's called [weather_properties.csv](https://github.com/quintel/etsource/blob/master/datasets/nl/curves/weather/1987/weather_properties.csv). I agree that we should refer to these files in the documentation.

**Comment by marliekeverweij** [comment]
>  It would indeed also be cool if there would be a download link to these weather properties.

Actually the production profiles of wind and solar can already be downloaded in the data dump: Results > Data export > Merit order price > Load curves. Shall we refer to this data dump in the [climate documentation on GitHub](https://github.com/quintel/documentation/blob/master/general/climate.md) when we'll update it? Only the temperature profile cannot be downloaded, but we can refer to KNMI for that I would say.

**Comment by AlexanderWirtz** [comment]
> Actually the production profiles of wind and solar can already be downloaded in the data dump: Results > Data export > Merit order price > Load curves. Shall we refer to this data dump in the climate documentation on GitHub when we'll update it? 

Good to know. I don't think people can find it there without help. A link from the documentation section or even a mention on the page itself would help. Also, should the normalized profiles, rather than only the production curves be downloadable too?

**Comment by marliekeverweij** [comment]
> Also, should the normalized profiles, rather than only the production curves be downloadable too?

I think that that's not needed. People interested in these profiles could do that themselves I think :)

**Comment by marliekeverweij** [comment]
Okay to close this issue?
