### ISSUE TITLE
The weather conditions page should contain a link to Documentation on GitHub for weather years

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#3163]
At present it only links to the Climate slider. The weather curves are at least as interesting. Also see: #3162

**Comment by DorinevanderVlies** [comment]
Link to documentation can be added after this pull request is merged https://github.com/quintel/documentation/pull/48

**Comment by DorinevanderVlies** [comment]
![image](https://user-images.githubusercontent.com/19907658/68843821-0cbb0e00-06c9-11ea-9390-f90ea47a132d.png)

![image](https://user-images.githubusercontent.com/19907658/68843841-147ab280-06c9-11ea-8731-4287decedb44.png)
