### ISSUE TITLE
The P2H sliders for industry have rather limited maximum ranges, so they don't do much

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#3164]
I have used the National Net voor de Toekomst scenario and changed the flex merit order to favor P2H for industry, but almost nothing happens. I noticed that I cannot increase the sliders beyond what they have already been set to. See screenshot below: 

![image](https://user-images.githubusercontent.com/308563/68659408-84593380-0537-11ea-9a67-2350825e88c8.png)

The slider range should be much larger (equal to the installed capacity of wind offshore, or even total wind capacity?).

Also, I realised after some playing around that users will not necessarily understand that in scenarios with a lot of baseload electric boilers/heaters in the Refinery, Chemical, Paper and Food sub-sections, there is almost no impact for power-2-heat. This should be clarified. 

Finally, I think that P2H for industry should link back to the Flexibility section and vice versa. I will create a separate issue for these improvements.

**Comment by DorinevanderVlies** [comment]
> The slider range should be much larger (equal to the installed capacity of wind offshore, or even total wind capacity?).

I do not agree with that. It does not make sense to put a lot of P2H in a small sector. The heat cannot be used. The [slider max of P2H](https://github.com/quintel/etsource/blob/master/inputs/flexibility/industry/capacity_of_industry_chemicals_other_flexibility_p2h_electricity.ad#L18) is set so the P2H can deliver the max demand of that sector

>Also, I realised after some playing around that users will not necessarily understand that in scenarios with a lot of baseload electric boilers/heaters in the Refinery, Chemical, Paper and Food sub-sections, there is almost no impact for power-2-heat. This should be clarified.

P2H does not compete with electric technologies. So P2H in combination with a large share of electric boilers does not have a lot of effect. I think this makes sense, but I agree that it needs to be clarified.

**Comment by AlexanderWirtz** [comment]
> I do not agree with that. It does not make sense to put a lot of P2H in a small sector. The heat cannot be used. The slider max of P2H is set so the P2H can deliver the max demand of that sector

You are right, I had not looked at this properly. I suppose I am disappointed by how much of a difference it makes. The right point of this feature is rather that it makes users investigate the difference between gas and hydrogen-fired heaters with or without P2H, which is significant if not spectacular. 

Also, the impact on gas demand (and power networks) for power production for baseload electric heaters  versus P2H is interesting to investigate, but I am afraid users will never realize this if we do not point it out. (#3165 )

**Comment by DorinevanderVlies** [comment]
I agree, closing this issue as the improvements identified here are part of the new issue #3165.

**Comment by AlexanderWirtz** [comment]
Just one more gasp: when I increase the size of a sub-sector, I still cannot increase the installed capacity of P2H in that subsector. It remains the same. So if a scenario originally shrinks a subsector, the slider will have very limited range. Is that something we can address?

**Comment by michieldenhaan** [comment]
The slider max is based on the sub sector size in the present. This means that the current slider max is only limiting when the user chooses to supply a large amount of heat demand with gas and/or hydrogen burners and also chooses to increase the sub sector size.

I think we can increase the slider max (e.g. to 2 times the current max) but there's a risk that much more P2H will be installed than necessary. If total heat demand is 100 MWh per year and 20% of this is supplied by H2/gas burners, then the maximum amount of P2H that can be useful is 100 * 0.2 / 8760

**Comment by AlexanderWirtz** [comment]
> The slider max is based on the sub sector size in the present. This means that the current slider max is only limiting when the user chooses to supply a large amount of heat demand with gas and/or hydrogen burners and also chooses to increase the sub sector size.

Yes, after posting my message I realized this was the case. I see there are no easy fixes here. It comes down to the question of whether we think it is a problem that users might install way too much capacity. We allow the same for elektrolyzers. The 'solution' there is that users can see their FLHs. Is that an option here?

**Comment by michieldenhaan** [comment]
The FLHs can be found in the flex table for P2H as well but I think the current final demand chart is a better default chart for the slide. We can add a warning in the tooltip that users have to be careful and look in the P2H table?

![beta-pro energytransitionmodel com - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario build… 2019-11-13 12-55-30](https://user-images.githubusercontent.com/32056448/68761689-e63b9b00-0614-11ea-9195-5d0d54289202.png)

**Comment by AlexanderWirtz** [comment]
> We can add a warning in the tooltip that users have to be careful and look in the P2H table?

Good idea regardless. That leaves the question of how we maximize the slider. I wouldn't mind more than 100% of the subsector size in the present. 200% seems like a reasonable alternative. It is something that can also be addressed post-deploy, I suppose, so I do not think it is deploy-critical.

**Comment by marliekeverweij** [comment]
> 200% seems like a reasonable alternative. 

Good idea, let's do it!
