### ISSUE TITLE
User experience of P2H in industry should be improved

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#3165]
As noted in #3164, it would be good to make the P2H in industry more intuitive to users. 

It may be confusing to users that the Flexibility >> Excess electricity >> Conversion page has nothing on Power-to-heat in industry. I would re-introduce the slide for P2H in industry and add links to the various industrial subsectors with the message that users can set installed capacity there. Similarly, it would be good to link back to this Flex >> Excess electricity >> Conversion page from the various industrial subsectors. Since the Flexibility merit order does require users to choose the order in which surpluses should be used, they have to go to the Flex section anyway to make use of P2H in industry. 

The description in the industrial subsectors might be improved by mentioning that P2H only lowers the energy demand of hydrogen and network gas-fired heaters.

**Comment by marliekeverweij** [comment]
![Screen Shot 2019-11-13 at 15 50 29](https://user-images.githubusercontent.com/32833996/68774536-8d2c3100-062d-11ea-9177-5f7d35c203e0.png)
![Screen Shot 2019-11-13 at 15 52 27](https://user-images.githubusercontent.com/32833996/68774586-9d441080-062d-11ea-81b3-9f99959fcfb5.png)
