### ISSUE TITLE
Weather years: the front end should explain that the same flh and curve is used for inland and coastl wind

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3166]
We should make it a bit more clear that for weather years we use the same flh and curve for coastal and inland wind.

For example by adding flh coastal to the weather year description.

**Comment by marliekeverweij** [comment]
I have added the flh for coastal wind to the descriptions: https://beta-pro.energytransitionmodel.com/scenario/flexibility/flexibility_weather/extreme-weather-conditions
