### ISSUE TITLE
Technical specs should work for underground pumped hydro storage and large-scale batteries

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3171]
![Screen Shot 2019-11-18 at 09 34 13](https://user-images.githubusercontent.com/32833996/69036668-aabf1900-09e6-11ea-9104-c6dead7556f7.png)
![Screen Shot 2019-11-18 at 09 35 20](https://user-images.githubusercontent.com/32833996/69036726-c2969d00-09e6-11ea-9253-0b9ba546e174.png)

**Comment by redekok** [comment]
This relates to this issue, I think: https://github.com/quintel/etmodel/issues/3135
