### ISSUE TITLE
Capacity label causes wrapping with some flexibility options

### ISSUE THREAD

**Issue by antw** [quintel/etmodel#3180]
![Screenshot 2019-11-29 at 17 17 16](https://user-images.githubusercontent.com/4383/69883460-3466c480-12cc-11ea-9d3f-1506c7cbd9fb.png)

Perhaps we can place the capacity label on the left, below the name of the flexibility option? It lengthens the list when there are lots of options, but appears less busy to my eye.

![Screenshot 2019-11-29 at 17 19 57](https://user-images.githubusercontent.com/4383/69883529-7c85e700-12cc-11ea-9e5d-a779f3acf151.png)

**Comment by noracato** [comment]
Good catch! Your solution looks clear and nice. I'll pick this one up.
