### ISSUE TITLE
The heat deficit chart is not very informative

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3195]
The heat deficit chart is supposed to show whether supply of the heat network is sufficient to meet demand. However, it's not possible to have a deficit on the heat network (a back-up heater will always ensure that no deficit occurs). In other words, I'm not sure what the purpose of this chart is. Unless anyone could explain its purpose, I would propose to remove it.

![image](https://user-images.githubusercontent.com/5946498/71242594-94bab600-230e-11ea-93d3-6efbed47e19c.png)

Notifying @antw @ChaelKruip @AlexanderWirtz @jorisberkhout @DorinevanderVlies @michieldenhaan @marliekeverweij @MartLubben @noracato @sfp-kemp

**Comment by DorinevanderVlies** [comment]
It doesn't (shoudn't) only show deficits in the heat network but in all heat demand.

For example if you install HP's without insulation deficits might occur. 
However, with our curves, the size of HP's and the demand of NL2015 deficits rarely occur. Only when the heat demand increases significantly and HP's are installed without insulation.

So, not the most informative chart...

![image](https://user-images.githubusercontent.com/19907658/71243533-d64c6080-2310-11ea-814f-76cd761e0a4b.png)

**Comment by redekok** [comment]
Thanks @DorinevanderVlies!

> So, not the most informative chart...

Does this mean you're in favor of removing it? Or would you want to keep the chart?

**Comment by DorinevanderVlies** [comment]
Not sure yet... 
I like the chart in theory, but the way it works out is not very informative. I think mainly because we do not take into account that water of 40 oC does not heat a badly insulated house properly. So, patly this chart is a reminder for me that we can improve that point.

Furthermore, this chart was an explicit wish of Gasunie.

All in all I lean towards keeping it.

**Comment by redekok** [comment]
Good point! In that case, I'll rename this issue.

**Comment by marliekeverweij** [comment]
A side-effect of smoothing heat demand profiles is that no heat deficits occur anymore (I concluded this after installing a air source heat pump in all houses and not insulating)

I would propose to remove this chart, together with the heat pump buffers (https://github.com/quintel/etmodel/issues/3325) I will discuss this with Gasunie as we have added these features with them

**Comment by ChaelKruip** [comment]
> I would propose to remove this chart, together with the heat pump buffers (#3325) I will discuss this with Gasunie as we have added these features with them

I agree! Good proposal :)

**Comment by marliekeverweij** [comment]
Haven't had the time to discuss the removal of this chart with Gasunie before this deploy. Will add this issue to the next deploy milestone #procrastination

**Comment by marliekeverweij** [comment]
Gasunie has agreed that we could remove this chart! @mabijkerk could you maybe pick this up this week?

Removing this section includes removing:
- the chart / output element (ETModel); the key of the chart is `heat_deficit` and it can be found in this document https://github.com/quintel/etmodel/blob/master/config/interface/output_elements/demand_households.yml
- the translations: chart title and legend entries (ETModel)
- the gqueries for the chart (ETSource); these can be found https://github.com/quintel/etsource/tree/master/gqueries/output_elements/output_series/vertical_stacked_bar_195_heat_deficits

**Comment by noracato** [comment]
- And removing the charts `output_element_series` from ETModel https://github.com/quintel/etmodel/blob/master/config/interface/output_element_series/heat_deficit.yml

**Comment by mabijkerk** [comment]
@marliekeverweij I added commits to the pull requests for "remove-heat-pump-buffers" branches in ETModel and ETSource.
