### ISSUE TITLE
It should be possible to choose the order of groups in the chart list

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3203]
Charts can be given a 'Group' and a 'Sub group' in the database, which sorts the charts into different groups in the chart list:
![Screen Shot 2020-01-02 at 14 47 08](https://user-images.githubusercontent.com/32833996/71669984-cef47080-2d6e-11ea-9dc8-0526f111d9ce.png)

It is unclear to me how the order of these groups is determined (not alphabetically for example). Is it be possible to choose the order of these groups somewhere? That would be nice!
![Screen Shot 2020-01-02 at 14 43 55](https://user-images.githubusercontent.com/32833996/71669949-acfaee00-2d6e-11ea-9ec3-a9d5cfda9b1e.png)

**Comment by antw** [comment]
I agree it would be nice to do this in the admin section. For now it can be done [by changing the order of group keys here](https://github.com/quintel/etmodel/blob/79aaba5046a777b6e0af17ab3264e13167cfb80f/app/models/output_element.rb#L24-L41).

**Comment by marliekeverweij** [comment]
I think I just wanted to know how to adjust the order and now I know. Good enough to change the order of group keys like this :)
