### ISSUE TITLE
The combination tool should work for the present

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3204]
The combination tool is broken. We did not notice this during the deploy testing. @marliekeverweij and @ChaelKruip. It could be useful to add the testing of the combination tool to the deploy testing and/or test it with the Mechanical Turk.

@noracato Could you find out what is exactly going wrong? 

![Screenshot 2020-01-03 at 13 20 21](https://user-images.githubusercontent.com/33415156/71723180-fa896080-2e2b-11ea-8549-b0d4ca7d1793.png)

**Comment by redekok** [comment]
> It could be useful to add the testing of the combination tool to the deploy testing and/or test it with the Mechanical Turk.

Same for other modules such as the transition path charts! :)

**Comment by marliekeverweij** [comment]
Do we want to have this fixed before the next deploy? 

If we do not think that this issue has priority, than we should maybe temporarily take it offline

Notifying @antw
