### ISSUE TITLE
Lack of available choices limits outcomes at scenario end year.

### ISSUE THREAD

**Issue by solonlost** [quintel/etmodel#3206]
The inability to select technologies for certain branches of the model has a tendency to influence the possible outcomes. With a scenario ending in 2100 or even 2050 in many cases there should be a possibility for more freedom in selecting technologies per branch.

A number of examples.
1. It isn't possible to select hydrogen as a fuel for maritime transport. This skews outcomes significantly and is also unrealistic as H2 tankers will be run from tank boil off, just as LNG tankers currently are. When the transport of H2 is done by H2, that's a significant proportion of maritime transport capacity, and the current model is unrealistic in its assumption that that would be done by fuel oil.
2. Limited study shows that LH2 is a viable fuel for air transport. On the scale of a scenario  ending in 2100 particularly, not being able to select H2 as a fuel option also skews outcomes.
3. A future economy with a large scale presence of cryogenic liquid (LH2) would be very inefficient if it doesn't leverage that cryogenic fluid for superconducting. That in turn means a lot less waste heat on a system level, this too ought to be in the model as its likely to significantly impact long term outcomes.

I realize that it's not possible to foresee in every eventuality, but I feel that the most major potential technologies that are currently being explored should be worked out to a greater extent than they currently are, especially where it would very significantly impact a scenario's outcome. Being able to migrate sea and air travel to H2 would make a vast difference to outcomes and the inability to select it potentially has political consequences if decisions are based on scenario outcomes.

**Comment by marliekeverweij** [comment]
Thanks for this issue and examples, @solonlost . It would indeed be a good idea to give the user more choices by adding more technologies to the transport sector. We will add your ideas to our improvements-backlog!
