### ISSUE TITLE
Effect of changes is often unclear, would be good to know what a change is affecting.

### ISSUE THREAD

**Issue by solonlost** [quintel/etmodel#3207]
When you make a change on a slider, it would be very helpful to have a live display of the effects of that change, preferably clickable. At the moment a slider change often leads to an effect in a sub menu somewhere which can often be hard to find, particularly as relationships between things are often not explicitly displayed.

Some soft of facility that demonstrates what is being affected, ideally in a clickable form to be able to navigate quickly to whatever is being affected, would be very helpful.

**Comment by marliekeverweij** [comment]
Very good idea, this would be very helpful for users. We could maybe list all important values that change when updating a slider. It would be even better when a short explanation would be added to this list, explaining why this happens. We will add this idea to our improvements-backlog.
