### ISSUE TITLE
Weather years: ideas for improvements / additions

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3209]
During the wrap-up of this project we had some good ideas for improvement:

- Add an average weather year
- Add weather year with warm winter
- Show FLH of weather year next to disabled FLH slider
- Change the location of this feature: it could be placed closer to the results-section because it is actually a sensitivity analysis to test the robustness of your scenario
- Communicate the impact of changing weather years better:
  - We could add an table showing several KPI's, like:
    - storage size of gas
    - impact on electricity network costs
  - We could add a dashboard item with a relevant weather year KPI

**Comment by ChaelKruip** [comment]
@marliekeverweij @noracato can you make these into ideas for our BaseCamp project?

**Comment by marliekeverweij** [comment]
> @marliekeverweij @noracato can you make these into ideas for our BaseCamp project?

I actually think that only number 3 ("Show FLH of weather year next to disabled FLH slider") is interesting for Basecamp because this requires software development. The other improvements do not require software development, but research and extra charts/ tables

**Comment by ChaelKruip** [comment]
> The other improvements do not require software development, but research and extra charts/ tables

In the project Ideas BC project we also collect non-software development projects for when there is filler time between projects. But Github is also fine indeed.

My concern is more with the fact that nobody is assigned to this issue which usually means it will be forgotten :)

**Comment by marliekeverweij** [comment]
> In the project Ideas BC project we also collect non-software development projects for when there is filler time between projects. But Github is also fine indeed.

Okay good to know

> My concern is more with the fact that nobody is assigned to this issue which usually means it will be forgotten :)

Okay I will assign myself ;)
