### ISSUE TITLE
Scenario report not loading on LIVE

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#3211]
I get this error message for the scenario report for various scenarios.

![Screenshot 2020-01-08 at 16 51 40](https://user-images.githubusercontent.com/4669028/71993436-65c1a100-3237-11ea-9152-dd9eedde1eaa.png)

**Comment by marliekeverweij** [comment]
The scenario report does load when I am browsing in a private window........

![Screen Shot 2020-01-08 at 17 05 02](https://user-images.githubusercontent.com/32833996/71994463-11b7bc00-3239-11ea-8f36-6e9213273eff.png)

**Comment by antw** [comment]
Doesn't look like this is related to the recent changes to the CO2 sheet. I can't find the original "co2_sheet_non_energy_emissions_industry" query file in the Git history ([referenced in non_energetic_co2_emissions_percentage](https://github.com/quintel/etsource/blob/ad8a2bec22dd8bcbba9163ddf82d0837051d9dcd/gqueries/modules/scenario_report/regional_report/non_energetic_co2_emissions_percentage.gql#L10)), and I don't know enough about these queries to be able to fix this myself.

[co2_sheet_non_energy_emissions_industry_energy.gql](https://github.com/quintel/etsource/blob/master/gqueries/modules/co2_sheet/industry_and_energy/co2_sheet_non_energy_emissions_industry_energy.gql) looks similar to the other emissions queries used.

**Comment by jorisberkhout** [comment]
> The scenario report does load when I am browsing in a private window in Firefox........

Same in Chrome in a private window. Could it be some caching issue, @antw ?

**Comment by antw** [comment]
> Same in Chrome in a private window.

Any chance the private window opens in English? The query which triggers this – energetic_co2_emissions_percentage – is for some reason only used in the NL reports.

Nonetheless it's not a caching issue: the "co2_sheet_non_energy_emissions_industry" query is missing.

**Comment by jorisberkhout** [comment]
> Any chance the private window opens in English?

Correct. Does anyone have a clue what can trigger this error? @marliekeverweij , @DorinevanderVlies maybe?

**Comment by marliekeverweij** [comment]
I'll check it out :)
