### ISSUE TITLE
Collective solar thermal should be added to the Overmorgen Energysheet/factsheet

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3213]
At this moment solar thermal is only connected in the factsheet to individual heating. 
![Screenshot 2020-01-14 at 10 31 40](https://user-images.githubusercontent.com/33415156/72331844-2b358980-36b9-11ea-973a-0290adb9abb6.png)

**Comment by marliekeverweij** [comment]
Fixed with https://github.com/quintel/etmodel/pull/3447#event-3607505073 and https://github.com/quintel/etsource/pull/2327#event-3607460392
