### ISSUE TITLE
Missing merit queries on BETA

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3214]
BETA returned some errors:
![image](https://user-images.githubusercontent.com/5946498/72335273-ff1d0700-36be-11ea-8f32-466bd4a786ec.png)

I think these queries (`merit_households_space_heating_demand` and `mv_buildings_space_heating_load_curve`) were removed in this commit https://github.com/quintel/etsource/commit/3c52f35e63daf5f8110f18c69b72b62f45044515, which was authored by @michieldenhaan and committed by @antw. Do you guys know what's going on here?

**Comment by antw** [comment]
Looking at the commit, I think the old queries have been replaced by a new one: [mv_energy_heat_load_curve](https://github.com/quintel/etsource/blob/36a90553068bef45be4e46241ca6efacb8855219/gqueries/general/merit/mv/mv_energy_heat_load_curve.gql). If that's the case, then we can just update the affected chart.

**Comment by michieldenhaan** [comment]
Yes that's correct. I wrote a migration for it (https://github.com/quintel/etmodel/blob/master/db/migrate/20191210103848_fix_mv_demand_curve_chart.rb) but it looks like the old queries are still used in some other queries. I'll fix this!
