### ISSUE TITLE
Would it be informing to add percentage bars to supply sidebar items?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3215]
Currently we have percentage bars for the different demand sectors: 
![Screen Shot 2020-01-14 at 11 32 09](https://user-images.githubusercontent.com/32833996/72336921-f548d300-36c1-11ea-9374-3043f567713b.png)

We could also add percentage bars to the supply sectors with the shares of each category **in final demand:** 
![Screen Shot 2020-01-14 at 11 32 23](https://user-images.githubusercontent.com/32833996/72337013-17425580-36c2-11ea-9ab1-8d6328b5d655.png)

For example for the Netherlands it would be:

- Electricity 18%
- Renewable electricity 2%
- District heating 8%
- Transport fuels 21%
- Biomass 2%
- Fuel production (we could rename to "fossil fuel production") 49%

I think its interesting! As it directly shows the share of each category. We currently only have the final demand mekko showing these numbers and this chart can not easily be found and understood.

![Screen Shot 2020-01-14 at 11 50 19](https://user-images.githubusercontent.com/32833996/72338095-0eeb1a00-36c4-11ea-8376-8726657baab9.png)

However, these percentages do need some explanation and are not directly understandable (as the demand percentage are). Also the categories do not exactly match the final demand categories (geothermal and solar thermal are missing, I've now added these to district heating).

What do you think? @AlexanderWirtz @jorisberkhout @ChaelKruip @antw @MartLubben @michieldenhaan @noracato @redekok @sfp-kemp @DorinevanderVlies

**Comment by redekok** [comment]
I like it!

**Comment by DorinevanderVlies** [comment]
I generally like the idea. 

But with the numbers and categories above it mainly confuses me. Some questions that pop into my mind:
But it does raise some questions, for example:

- What is the category Electricity (2%), import? In what category does fossil fossil electricity fall?
- How do we count overproduction of electricity?
- Where do we count direct use of fossil fuels eg Condensing combi boiler)? (is that fuel production? Not with the current content of that item)
- How do we deal with double counting - for example biomass used for renewable electricity
- Is this based on final demand, primary demand or a mix?

**Comment by ChaelKruip** [comment]
I like the idea but also agree with the points @DorinevanderVlies raises!

**Comment by MartLubben** [comment]
I really like the idea! Agree with the points of @DorinevanderVlies. Although we could think of something.  

Option 1: We could show the % supply to the final demand.

> - What is the category Electricity (2%), import? In what category does fossil fossil electricity fall?
**Fossil electricity is then part of Electricity.**
> - How do we count overproduction of electricity?
**Not included,  because it is not supplied to the final demand**
> - Where do we count direct use of fossil fuels eg Condensing combi boiler)? (is that fuel production? Not with the current content of that item)
**This is part of Fossil fuel production**
> - How do we deal with double counting - for example biomass used for renewable electricity
**Part of electricity and not of biomass**
> - Is this based on final demand, primary demand or a mix?
**In this case final demand**

Option 2: We could show the % supply to the primary demand. 

> - What is the category Electricity (2%), import? In what category does fossil fossil electricity fall?
**Electricity only shows import. Fossil electricity is part of Fossil fuel production.**
> - How do we count overproduction of electricity?
**Not included, because it is not a primary demand**
> - Where do we count direct use of fossil fuels eg Condensing combi boiler)? (is that fuel production? Not with the current content of that item)
**This is part of Fossil fuel production**
> - How do we deal with double counting - for example biomass used for renewable electricity
**Part of biomass and not of renewable electricity. Solar and wind will be part of renewable electricity**
> - Is this based on final demand, primary demand or a mix?
**In this case primary demand**

Another idea is to add a switch between final and primary %

**Comment by marliekeverweij** [comment]
Yes good points! @DorinevanderVlies 

To start with the first question (because it also answers others)
> Is this based on final demand, primary demand or a mix?

It is based on final demand

> - How do we count overproduction of electricity?
> - Where do we count direct use of fossil fuels eg Condensing combi boiler)? (is that fuel production? Not with the current content of that item)
> - How do we deal with double counting - for example biomass used for renewable electricity

Same as final demand

> What is the category Electricity (2%), import? In what category does fossil fossil electricity fall?

I mixed up the percentages: 18% is Electricity and 2% is Renewable Electricity ;)

**Comment by DorinevanderVlies** [comment]
Thanks for the explanation.

A big difference IMO is that the percentages shown at the demand side can be changed directly at that sidebar item. Changing the split of supply is more complex. For example, if you want to reduce direct use of fossil fuels you either have to make changes to the demand side or got to "biomass". The section "Fuel production" only shows. And the electricity mix depends on curves and costs as well as on installed capacity.

I am still not convinced that the sidebar is the place to put this information. Would it be an idea to not only technically test this feature, but to ask some users to test it as well?
