### ISSUE TITLE
Explanation costs calculation should be added to costs-dashboard item

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3222]
Currently are costs calculation is not explained in the dashboard. I think we should add that we use the greenfield approach etc. etc. and explain the different categories more. We can add a link to our GitHub about our costs calculations: https://github.com/quintel/documentation/blob/master/general/cost_calculations.md (and maybe check if this page is still up to date). Anybody interested in doing this? :)

![Screen Shot 2020-01-24 at 10 30 35](https://user-images.githubusercontent.com/32833996/73058815-b9b5c200-3e94-11ea-983e-30f8844472c1.png)

**Comment by marliekeverweij** [comment]
Let's direct to the updated costs documentation here! https://docs.energytransitionmodel.com/main/cost-main-principles
Adding this to the deploy milestone
@michieldenhaan

**Comment by michieldenhaan** [comment]
done!
