### ISSUE TITLE
Sum of electricity loads for households_final_demand_for_space_heating_electricity is not equal to demand in graph

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3223]
A client pointed out that in his scenario on PRO (606418) the sum of the electricity loads (in the loads.csv data export) differed from the demand in the graph for `households_final_demand_for_space_heating_electricity`. 

The sum of the loads is 14942121.1 MWh = ~53.79 PJ, whereas the demand is 54.08 PJ according to the graph:
![image](https://user-images.githubusercontent.com/5946498/73446250-b4f18200-435c-11ea-9165-e775d2c406a8.png)

This difference of 0.3 PJ seems a bit much to be just the result of rounding, doesn't it? @antw would you have any idea what could cause this difference?

Also notifying @ChaelKruip @michieldenhaan @marliekeverweij

**Comment by antw** [comment]
I just took a quick look, and it appears to be specific to the hybrid heat pumps (gas and electricity). None of the other electric heating technologies cause this effect.

I will look into this further.

**Comment by antw** [comment]
So far I cannot say why this is happening: the hybrid heat pumps are rather (too) complicated, and it's proving hard to track down where this error is occurring. There is clearly some link to the dynamic output efficiency of the HHP:

```
- output.useable_heat.ambient_heat = 1
- output.useable_heat.electricity = 1
- output.useable_heat.hydrogen = 1.12825
```

Essentially, these lines say that when the hydrogen component is used, every one unit of hydrogen should result in 1.12825 units of useable heat. If we get rid of that, the problem goes away and the electricity demand and curve match up exactly:

```
- output.useable_heat = 1
```

This might suffice as temporary fix, but it obviously isn't a solution to the problem.
