### ISSUE TITLE
Small mismatch between total electricity supply and demand due to CHPs and HHPs

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3227]
There's a small mismatch between total electricity demand and supply in the graph. For a NL2015 blank scenario on BETA the difference is about 8 TJ on a total demand of 427 PJ (0.002%). This mismatch completely disappears when:
1) All CHPs are turned off
2) All HHPs are turned off

When increasing HHP share to 100% and supplying most electricity with CHPs, the mismatch increases to about 370 TJ (0.08% of a total demand of 482 PJ).

Note that a tiny mismatch is also present on PRO atm. Turning off all CHPs and all HHPs does not completely resolve the issue there.

Discussed with @antw. Demand and supply in Merit match almost perfectly, so the issue is caused by _something_ in the graph. The HHP issue could be related to: https://github.com/quintel/etmodel/issues/3223

Notifying @ChaelKruip.

![localhost - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario builder  2020-02-12 17-52-06(1)](https://user-images.githubusercontent.com/32056448/74358096-2996d880-4dc1-11ea-8902-235b267d5c51.png)

![localhost - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario builder  2020-02-12 17-55-50(1)](https://user-images.githubusercontent.com/32056448/74358100-2d2a5f80-4dc1-11ea-9e2a-56c15aff364d.png)

**Comment by ChaelKruip** [comment]
Good catch @michieldenhaan! @marliekeverweij shall we add this to the next deploy milestone?
