### ISSUE TITLE
When you save a saved scenario the description should not disappear

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3234]
At this moment the scenario description disappears when you save a saved scenario. 

**Scenario description:**
![image](https://user-images.githubusercontent.com/33415156/75144903-481d9d80-56f8-11ea-87c3-816090f05957.png)

**Comment by marliekeverweij** [comment]
I think this should be fixed before the deploy. @noracato is it that possible?

**Comment by noracato** [comment]
I can try. I think the proper way to fix this would be moving the description from the scenarios in etengine to the saved scenarios in etmodel. This would also allow us to more easily create an 'edit description' button in the future. But I'm not sure I can make that (including testing) before the feature freeze on Tuesday.
However, I can try to create a hotfix like we have for keeping the title. @marliekeverweij what do you think about that?

**Comment by noracato** [comment]
Temporarily fixed 😸

**Comment by marliekeverweij** [comment]
Removing milestone as this issue is temporarily fixed :)

**Comment by sfp-kemp** [comment]
@noracato I think this issue is permanently solved. It could be nice for sure but I think this shouldn't be an open issue. Do you agree?

**Comment by noracato** [comment]
Yes!
