### ISSUE TITLE
The waste heat for ICT is 3x higher than the Berenschot paper

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3247]
The Berenschot paper (https://www.berenschot.nl/actueel/2018/november/410-kton-co2-besparing/ ) states a waste heat of 6 PJ and 100% use of waste heat in the ETM of ICT is 18 PJ. The difference is due to the fact that in the ETM ICT is more than datacenters

https://github.com/quintel/documentation/blob/master/general/residual_heat_industry.md

**Comment by marliekeverweij** [comment]
Good point Mart!

> The difference is due to the fact that in the ETM ICT is more than datacenters

You're right.

Currently residual heat potential is calculated based on the electricity demand of the ICT sector and the share of energy that can be recovered as residual heat from datacenters (77% of electricity demand of datacenters). However, we should indeed take into account the share of datacenters in the ICT sector!

There are two ways to fix this in my opinion:

1. We could split the ICT sector in 'datacenters' and the 'rest' in the graph.
2. We could use the calculated residual heat potential that Berenschot calculated in 2018: 6.3 PJ as a basis. This is a technical and economical potential; they took into account the proximity to heat demand and the gas price. We could use this to calculated the potential residual heat share from ICT in the graph.

Note: there's a big difference in the electricity demand for central ICT in NL2015 (from RVO) which is **23.5 PJ** and the electricity demand of Informatie en communicatie (SBI J) on Klimaatmonitor which is **12.4 PJ** in 2015.
![Screen Shot 2020-03-03 at 10 40 54](https://user-images.githubusercontent.com/32833996/75762766-8429b180-5d3b-11ea-8bc4-b79e49397477.png)
![energiegebruik_dienstensector](https://user-images.githubusercontent.com/32833996/75762103-732c7080-5d3a-11ea-8e6c-489faa3715a6.png)

**Comment by michieldenhaan** [comment]
> Note: there's a big difference in the electricity demand for central ICT in NL2015 (from RVO) which is 23.5 PJ and the electricity demand of Informatie en communicatie (SBI J) on Klimaatmonitor which is 12.4 PJ in 2015.

It looks like the data used for the 2015 dataset is old, RVO now also reports a demand close to 12.4 PJ:

![energiecijfers databank nl - Jive - ICT  PJ  - Nederland - Mozilla Firefox 2020-03-03 13-35-50](https://user-images.githubusercontent.com/32056448/75776304-0aea8880-5d54-11ea-81b3-3f93509ccf99.png)

**Comment by marliekeverweij** [comment]
@michieldenhaan and I just looked into this issue and concluded that it's more a data issue than a potential residual heat share issue. The percentage we are using now (77%) is correct for electricity demand of datacenters.

What should happen is:

- [ ] Update electricity demand ICT for NL2015 23.5 PJ -> 13.0 PJ. This will have huge scenario impacts, so should be carefully done!
- [ ] Electricity demand ICT should be split into electricity demand for data centers and 'other'. This share should be calculated based on a good data source (that we currently do not have) and the share should be dataset-dependent. Somehow the electricity demand of datacenters is not correctly reported: many datacenters have been built, but the electricity demand of ICT is not increasing the last couple of years (see Klimaatmonitor and RVO data in previous posts)
- [ ] A disclaimer should be added to the data center residual heat slider that user should use the slider carefully. We have to do this before this deploy: I will add it to the text changes on BC.

I will remove the deploy milestone from this issue and add the NL2017 update milestone
