### ISSUE TITLE
Slider setting for H2-fired heater for refineries got lost in NvdT-scenario's

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3248]
In all NvdT-scenario's on beta (post migration) the H2-fired heater for refineries is set to 0. This results in slider group <100% and too little final H2-demand for this sector.

Example for "[nationaal](https://beta-pro.energytransitionmodel.com/scenarios/1276133) (H2-fired burner should be 100%)" 

BETA
![image](https://user-images.githubusercontent.com/19907658/75567884-8b5a7200-5a52-11ea-9140-70c364f19705.png)

PRODUCTION
![image](https://user-images.githubusercontent.com/19907658/75568050-de342980-5a52-11ea-937a-b4853c48074f.png)

Both in the [BETA](https://engine.energytransitionmodel.com/inspect/737904/scenarios/606415/edit) and the [PRODUCTION](https://pro.energytransitionmodel.com/scenarios/606415) database there is no slider setting for `industry_chemicals_refineries_burner_hydrogen_share`:

However opening [scenario Nationaal](https://pro.energytransitionmodel.com/scenarios/606415) on PRODUCTION shows 100% H2-fired burners.

I am not sure how a correct setting is shown on PRODUCTION even though no slider is set.
My guess is that this slider got lost somewhere in the Berenschot-process...

Links to scenario's
Regionale sturing
https://pro.energytransitionmodel.com/scenarios/606411
Nationale sturing
https://pro.energytransitionmodel.com/scenarios/606415
Europese CO2-sturing
https://pro.energytransitionmodel.com/scenarios/606418
Internationale sturing
https://pro.energytransitionmodel.com/scenarios/606388

**Comment by marliekeverweij** [comment]
> My guess is that this slider got lost somewhere in the Berenschot-process...

I also think that this is the case. Do you agree @noracato / @michieldenhaan ?

**Comment by michieldenhaan** [comment]
I'm not sure how that would explain that the slider group does sum up to 100% on PRO but not on BETA. And it would be quite worrisome tbh if slider settings get lost.

One fix would be to make the H2 burner flexible, this ensures that the energy flows add up nicely:

![beta-engine energytransitionmodel com - EnergyTransitionModel - Mozilla Firefox 2020-03-02 11-33-52(1)](https://user-images.githubusercontent.com/32056448/75668718-0e114600-5c7a-11ea-83e5-f29f98a5bd42.png)

![localhost - EnergyTransitionModel - Mozilla Firefox 2020-03-02 11-33-24(1)](https://user-images.githubusercontent.com/32056448/75668728-110c3680-5c7a-11ea-8cad-e415032902d9.png)

However on my local machine the slider group still does not sum up to 100%:
![localhost - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario builder  - Mozilla Firefox 2020-03-02 11-37-21](https://user-images.githubusercontent.com/32056448/75668828-326d2280-5c7a-11ea-96fa-0f0304b2ca4a.png)

Do you know why this is @antw?
Relevant scenario on BETA: https://beta-pro.energytransitionmodel.com/scenarios/1276133

**Comment by DorinevanderVlies** [comment]
> I'm not sure how that would explain that the slider group does sum up to 100% on PRO but not on BETA. And it would be quite worrisome tbh if slider settings get lost.

In the Berenschot-scenario's on PRO there is no input for that slider. So the inputs do not add to 100%. I am confused why on PRO the H2-fired burner gets a setting at all. I would expect that on pro the group wouldn't add to 100% (as happens on Beta).

**Comment by antw** [comment]
> Do you know why this is @antw?

All the sliders have a user value of 0.0, except for industry_chemicals_refineries_burner_hydrogen_share which doesn't have a user value, but whose default is also 0.0.

> I am not sure how a correct setting is shown on PRODUCTION even though no slider is set.

This is not immediately obvious to me either. However what we're seeing on *beta* doesn't appear to be a bug: the default H2 share is 0% and if no input updates that share then it will stay at 0%.

**Comment by marliekeverweij** [comment]
FYI I have just added the line `industry_chemicals_refineries_burner_hydrogen_share: 100.0` to all migrated iNET scenarios on BETA, because I am going to share them with the customers.

**Comment by antw** [comment]
@DorinevanderVlies I'm curious if you know how the beta scenario was created? It's only a few days old. Is is possible it was created by copy/pasting the user values from the production server to beta?

Scenario records in the database have two fields which store input values:

* `user_values` – these are input values set explicitly by a user (e.g. with a slider, or a value set with the API).
* `balanced_values` – these are input values set automatically by ETEngine to ensure share groups sum to 100%.

I only checked the "Regionale sturing" scenario on production, but it has six "balanced" values:

```
households_heater_coal_share: 0.0
households_heater_crude_oil_share: 0.0
buildings_space_heater_coal_share: 0.0
transport_freight_train_using_coal_share: 0.0
industry_chemicals_refineries_burner_hydrogen_share: 100.0
households_collective_chp_biogas_share: 0.0
```

If input values were copy/pasted from the "edit scenario" page on ETEngine, these values won't have been included. I will add a "balanced_values" field to the page in case this happens again in the future.

**Comment by DorinevanderVlies** [comment]
> @DorinevanderVlies I'm curious if you know how the beta scenario was created? It's only a few days old. Is is possible it was created by copy/pasting the user values from the production server to beta?

I copied the user values from the migration Nora made of scenario's on Pro.
These scenario's were originally made using the API.

For now it was a quick fix to be able to test a bit quicker than locally and to be able to share the migrated scenario's before the deploy.

> If input values were copy/pasted from the "edit scenario" page on ETEngine, these values won't have been included. I will add a "balanced_values" field to the page in case this happens again in the future.

II think that is what happened. I do not think this will happen often as we do not regularly copy slider settings from a scenario made by an API. What do you think @marliekeverweij ?

**Comment by marliekeverweij** [comment]
Good to know the origin of this issue @antw! 

> I will add a "balanced_values" field to the page in case this happens again in the future.

Good idea, is this a lot of work? Otherwise we can leave it and keep this in mind when copying slider settings from a scenario made by an API

**Comment by marliekeverweij** [comment]
Not deploy critical, since it only happens when copying slider setting from a scenario

**Comment by marliekeverweij** [comment]
Closing as issue is not relevant anymore
