### ISSUE TITLE
Slide for datadump of hourly loads should have appropriate title

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#3259]
"Merit Order Price" does not cover the essence IMO:

![image](https://user-images.githubusercontent.com/1303760/75765665-22b81180-5d40-11ea-986c-6429a082aaa6.png)

**Comment by marliekeverweij** [comment]
Yes true. I think 'Electricity demand, supply and price' is more consistent with the datadump for network gas and hydrogen. Do you agree? I'll move this issue to the BC to-do where text changes are being collected.
