### ISSUE TITLE
energy_heat_dumped_steam_hot_water should be part of applications data-dump

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#3260]
It is currently not included leading to differences between the sum of the final demand in the CSV file and the GQuery `SUM(V(G(final_demand_group),demand))`

**Comment by ChaelKruip** [comment]
Same goes for `industry_final_demand_hydrogen_non_energetic`

**Comment by redekok** [comment]
For my understanding, should `SUM(V(G(application_group),final_demand))` result in the same output value as `SUM(V(G(final_demand_group),demand))`?

Maybe we could add a spec to check this in the future?

**Comment by ChaelKruip** [comment]
> For my understanding, should SUM(V(G(application_group),final_demand)) result in the same output value as SUM(V(G(final_demand_group),demand))?

It seems to be the idea behind the data dump to be complete in that sense yes.

**Comment by ChaelKruip** [comment]
> Maybe we could add a spec to check this in the future?

Good idea!
