### ISSUE TITLE
merit.order datadump should have more descriptive name and text on slide needs rewrite

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#3261]
The data-dump contains hourly load curves for electricity production and consumption.
Perhaps `electricity.load` is a better name?

![image](https://user-images.githubusercontent.com/1303760/75862777-bb619680-5dff-11ea-85f3-0f9f8b673f4b.png)

I think the text above should be rewritten slightly:
"load curves for all power plants" is no proper description of what is in the file.

"hourly load curves for all electricity production and consumption"

**Comment by marliekeverweij** [comment]
Closed with https://github.com/quintel/etmodel/pull/3263
