### ISSUE TITLE
Flex technologies should be added to electricity and heat producers data dump

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#3262]
![image](https://user-images.githubusercontent.com/1303760/75863768-4ee79700-5e01-11ea-8a10-d9f2da8a4450.png)

Not sure if all new heat network features are included as well

**Comment by marliekeverweij** [comment]
I think this is nice and probably easy to pick up for next deploy. @antw / @noracato how could I add new technologies to this download? I had a quick look and I thought adding the missing flex nodes to the `application_group` could do the trick, but that doesn't work ;)
> Not sure if all new heat network features are included as well
Yes, the heat network technologies are added already

**Comment by noracato** [comment]
You can add a new converter to [this list](https://github.com/quintel/etengine/blob/7f6f8eb2ea043f957a3ebd101e5b2ccf0f78c918/app/models/api/v3/production_parameters_presenter.rb#L42) It will pop up as a new row in the download. In the `converter row` below that you can adjust the queries/columns for each row. The column titles go [here](https://github.com/quintel/etengine/blob/7f6f8eb2ea043f957a3ebd101e5b2ccf0f78c918/app/models/api/v3/production_parameters_presenter.rb#L21). Hope this helps!
