### ISSUE TITLE
The pumped (hydro) storage slider disappears sometimes for a UK scenario (LIVE)

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3269]
For a UK scenario (LIVE), the slider to set the capacity of pumped storage sometimes disappears. Not sure what causes the slider to disappear though..

![image](https://user-images.githubusercontent.com/5946498/76088921-260a0200-5fb9-11ea-996f-bc7109c09222.png)
vs. 
![image](https://user-images.githubusercontent.com/5946498/76089183-813bf480-5fb9-11ea-9abb-e49dc7f471b9.png)

@antw / @noracato Would you have any idea what's going on here?

**Comment by antw** [comment]
@noracato @sfp-kemp Would you mind looking into this? It seems like the area dependencies on input elements (maybe other YModels?) might not be working as expected.

I loaded an NL scenario on production and the "Reservoirs" slider *was* shown alongside "OPAC", even though "Reservoirs" is dependent on "has_mountains". "has_mountains" is false for NL. "OPAC" has no dependency and seems to be correctly shown always.

Then I loaded a UK scenario, which showed both "Reservoirs" and "OPAC" sliders as expected, then loaded NL again and "Reservoirs" disappeared. It doesn't seem to be predictable, but refreshing the page causes the slider to sometimes appear and sometimes not.

**Comment by antw** [comment]
Should be fixed by #3277. Thanks @noracato!
