### ISSUE TITLE
Chart hourly heat production for district heating freezes when "merit" is turned off

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3275]
The `hourly heat demand for district heating` and the `hourly heat production for district heating` charts of [this saved scenario](https://pro.energytransitionmodel.com/saved_scenarios/8847) does not load properly.

![image](https://user-images.githubusercontent.com/19907658/76639139-e78ebd00-654d-11ea-8df1-17cc6a8b4868.png)

I do not have this problem for fresh/self-made scenario's. Could this be caused by migration?

notifying @MartLubben as I think I have heard you describe this issue as well.

**Comment by marliekeverweij** [comment]
Weird...

How is this scenario made? Is it migrated? 

In the engine I see a lot of old heat network slider settings that are not used anymore. Therefore I suppose that old slider settings are copied from somewhere, could that be?

![Screen Shot 2020-03-13 at 17 22 46](https://user-images.githubusercontent.com/32833996/76640138-b3b49700-654f-11ea-91be-e7b777ddd268.png)

**Comment by DorinevanderVlies** [comment]
this is the Over Morgen scenario for Gelderland. 

Judging by the above I reckon they might have opened an old (not properly saved) scenario and saved it recently. So it is now a protected scenario which has missed some migrations...

**Comment by marliekeverweij** [comment]
> Judging by the above I reckon they might have opened an old (not properly saved) scenario and saved it recently. 

Could be... What happens to scenarios that have not been saved properly before a deploy? Will they be deleted or get a disclaimer that they can't open it anymore? Including @noracato @antw @michieldenhaan

**Comment by noracato** [comment]
> What happens to scenarios that have not been saved properly before a deploy?

Most migrations only go over the protected scenarios. So nothing happens to the ordinary scenario, it user values stay the same. 

> Will they be deleted or get a disclaimer that they can't open it anymore?

If scenarios are older than 180 days, a warning will be shown on trying to open them.

**Comment by antw** [comment]
The source scenario is 722652, which was created in mid-February and is protected. It was last updated mid-afternoon on 3rd March in the ~30 minute window in which scenarios were being updated by the csv-update-scenarios tool following the deploy (but prior to the website reopening to the public).

Does the CSV that was used still exist? It might be worth checking that the values for this scenario were valid: ETEngine will have rejected the change if the inputs were invalid.

**Comment by DorinevanderVlies** [comment]
> The source scenario is 722652, which was created in mid-February and is protected.

My guess is that scenario 722652 was based on an older (~1.5 year old) scenario.

> Does the CSV that was used still exist? It might be worth checking that the values for this scenario were valid: ETEngine will have rejected the change if the inputs were invalid.

I'll ask the owner of this scenario about the above.

**Comment by michieldenhaan** [comment]
It looks like the migration did run but the old keys were not removed. One thing to note is that this scenario has the merit order disabled, when turning on merit the charts do load. However when trying to load the charts first breaks the front-end, instead of showing a 'there's no data for this chart' message

**Comment by michieldenhaan** [comment]
To add to this: it looks like the old heat keys are present in a lot (maybe all) protected scenarios. @noracato Did the migration script remove the old heat keys?

**Comment by DorinevanderVlies** [comment]
> To add to this: it looks like the old heat keys are present in a lot (maybe all) protected scenarios. @noracato Did the migration script remove the old heat keys?

I opened a new issue for this: https://github.com/quintel/etmodel/issues/3279

**Comment by DorinevanderVlies** [comment]
>  One thing to note is that this scenario has the merit order disabled, when turning on merit the charts do load. However when trying to load the charts first (before switching merit on) the front-end breaks, instead of showing a 'there's no data for this chart' message

Clear, I changed the issue title

**Comment by antw** [comment]
> I'll ask the owner of this scenario about the above.

Sorry I wasn't clear: I was asking about the CSV which we used to migrate scenarios in February. Since @michieldenhaan confirmed the scenario was migrated there's no need to look into this further.

It seems that "Requires merit order" (on the "edit chart" page) was not set for these charts. I've done so, however they're still broken so I'll have to look into it further next week.

**Comment by marliekeverweij** [comment]
@antw , do you think this issue is deploy-critical?
