### ISSUE TITLE
The area dependency is buggy for the oil- and coal-fired heater in households

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3276]
The inputs for oil- and coal-fired heaters in households should be hidden in the front-end for a NL scenario due to the area dependency `has_coal_oil_for_heating_built_environment` which is false for this area. However, this is not always the case, as can be seen in the screenshot below. Presumably this has got something to do with our new ymodel?

![image](https://user-images.githubusercontent.com/5946498/76746071-310e2080-6777-11ea-9f89-5bf25feeb1f9.png)

**Comment by michieldenhaan** [comment]
I think this is the same issue as https://github.com/quintel/etmodel/issues/3269, i.e. the area dependency not being processed properly.

For me they don't show up in a blank NL scenario, but maybe they do show up after touching some sliders/refreshing just like the pumped hydro slider?

**Comment by noracato** [comment]
> where should we make these inputs hidden again? Here?

Yes, just fill in the `dependent_on` attribute. You can find a list of options for this attribute [here](https://github.com/quintel/etmodel/blob/master/app/models/api/area.rb)

**Comment by redekok** [comment]
> I think this is the same issue as #3269, i.e. the area dependency not being processed properly.

Yes, I guess this is indeed the case, since the inputs are dependent on `has_coal_oil_for_heating_built_environment` which is false for the Netherlands.

**Comment by noracato** [comment]
Looking into this right now. I don't think it's the dependecies that are buggy, but something with the Current.setting (it randomly starts switching areas)

**Comment by noracato** [comment]
This is probably fixed by #3277. @redekok did this issue come up after you changed areas?

**Comment by redekok** [comment]
> @redekok did this issue come up after you changed areas?
This could be the case but I actually don't remember it very well.. I did start some scenario's for the UK lately, for which `has_coal_oil_for_heating_built_environment = true`.

**Comment by noracato** [comment]
> This could be the case but I actually don't remember it very well

No problem 😄  I'll close the issue for now, because it's most probably fixed. If it does pop up again, please feel free to reopen the issue and we'll investigate!
