### ISSUE TITLE
Old heat keys are still present in a lot (maybe all) protected scenario's

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3279]
It looks like the old heat keys are present in a lot (maybe all) protected scenarios. @noracato Did the migration script remove the old heat keys?

![image](https://user-images.githubusercontent.com/19907658/76941311-1618e900-68fc-11ea-83c9-bdf5043e8c09.png)

Also mentioned in:
https://github.com/quintel/etmodel/issues/3275

notifying @michieldenhaan @marliekeverweij

**Comment by noracato** [comment]
No, the 'migration' I did just set the values for the newly introduced sliders. We can write a mirgation to get rid of these old user values for protected scenarios

**Comment by marliekeverweij** [comment]
@noracato is it possible to do this before next deploy? I think it would be nice to clean this up :)

**Comment by noracato** [comment]
@marliekeverweij ofcourse! Do you have a list maybe of all keys that we don't use anymore?

**Comment by marliekeverweij** [comment]
Here is the list of keys that can be deleted 
Right @michieldenhaan?

buildings_chp_engine_biogas_share
buildings_collective_burner_hydrogen_share
buildings_collective_burner_network_gas_share
buildings_collective_chp_wood_pellets_share
buildings_collective_geothermal_share
buildings_collective_heatpump_water_water_electricity_share
capacity_of_agriculture_chp_engine_biogas
capacity_of_agriculture_chp_engine_network_gas
capacity_of_agriculture_chp_supercritical_wood_pellets
capacity_of_energy_chp_engine_biogas
capacity_of_energy_heater_for_heat_network_coal
capacity_of_energy_heater_for_heat_network_geothermal
capacity_of_energy_heater_for_heat_network_lignite
capacity_of_energy_heater_for_heat_network_network_gas
capacity_of_energy_heater_for_heat_network_oil
capacity_of_energy_heater_for_heat_network_waste_mix
capacity_of_energy_heater_for_heat_network_wood_pellets
households_collective_burner_hydrogen_share
households_collective_burner_network_gas_share
households_collective_chp_biogas_share
households_collective_chp_network_gas_share
households_collective_chp_wood_pellets_share
households_collective_geothermal_share
households_collective_heatpump_water_water_electricity_share
households_flexibility_p2h_electricity_market_penetration
investment_costs_earth_geothermal_electricity
investment_costs_heat_network_buildings
investment_costs_heat_network_households
om_costs_earth_geothermal_electricity
om_costs_heat_network_buildings
om_costs_heat_network_households

[Old_new_keys.xlsx](https://github.com/quintel/etmodel/files/4376176/Old_new_keys.xlsx)

**Comment by michieldenhaan** [comment]
Yes!

**Comment by noracato** [comment]
Closed by quintel/etengine@f08ee66a56176d81f08f9f2f0121ff4785011665
