### ISSUE TITLE
The behaviour of the households and buildings curtailment sliders is not as expected

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3282]
The behaviour of the households and buildings curtailment sliders is not as I expected:

1. When not touching any slider, there is no curtailment:
![image](https://user-images.githubusercontent.com/5946498/77293947-a6cc3c00-6ce3-11ea-97ce-ed9ba89e17c8.png)

2. When setting the curtailment of households solar pv to 100%, it is indeed curtailed:
![image](https://user-images.githubusercontent.com/5946498/77294094-e5fa8d00-6ce3-11ea-8661-64170636c8c9.png)

3. But when setting the slider back to 0%, all production from households solar pv is still curtailed. The dashboard KPIs actually do change (e.g. the % renewables increases again when there is no curtailment).
![image](https://user-images.githubusercontent.com/5946498/77294128-f6126c80-6ce3-11ea-9ee4-88b4f08e8661.png)

The buildings solar pv slider has some strange behaviour as well but the solar pv plants slider seems to be working fine.

Not sure if this is a modelling or development bug so I assigned both @noracato and @marliekeverweij .

**Comment by noracato** [comment]
I think this is the yearly chart code again. I've discovered bugs similar to this before when working on the chart. I'll go check it out!
