### ISSUE TITLE
Effect of curtailment sliders remains when slider is returned to 0%

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3284]
I opened a [scenario](
https://beta-pro.energytransitionmodel.com/saved_scenarios/4474) in which I installed PV on roofs of households and buildings and PV plants.

And changed curtailment of the three options too 100% and back again.
Below some observations. Some seem to be bugs in the charts, others recommendations for user friendliness.

- When I set and reset curtailment of households the chart still shows curtailment of households, even though slider is back to 0 (bug?)

The same happens with the other two sliders.

![image](https://user-images.githubusercontent.com/19907658/77309336-c1f77580-6cfc-11ea-8f88-c5dace4c2ebf.png)

- When I curtail PV plants, the order or the series changes, which is confusing (recommendations for user friendlines)

I would expect the light green part of the chart to turn light blue. This might happen, but it is difficult to see because the order of the series seems to change (light blue part is on top of the chart)
![image](https://user-images.githubusercontent.com/19907658/77309685-6083d680-6cfd-11ea-9376-c2ed38a34dba.png)

![image](https://user-images.githubusercontent.com/19907658/77309261-9eccc600-6cfc-11ea-8f09-584908044207.png)

**Comment by ChaelKruip** [comment]
Duplicate of https://github.com/quintel/etmodel/issues/3282

**Comment by DorinevanderVlies** [comment]
Closing this issue, the first part is a duplicate. I am not sure about the second part anymore. If a user sets 100% curtailment it is intuitive if the position of the series stays the same. But on the other hand it is more intuitive to see all curtailment on top of the production chart. The second point outweighs the first in my opinion.
