### ISSUE TITLE
Is the Merit profile dump (over)complete?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#3285]
The following heat producing flex options are included twice (once with .input and once with .output):

'industry_chemicals_other_flexibility_p2h_hydrogen_electricity.output',
'industry_chemicals_other_flexibility_p2h_network_gas_electricity.output',
'industry_chemicals_refineries_flexibility_p2h_hydrogen_electricity.output',
'industry_chemicals_refineries_flexibility_p2h_network_gas_electricity.output',
'industry_other_food_flexibility_p2h_hydrogen_electricity.output',
'industry_other_food_flexibility_p2h_network_gas_electricity.output',
'industry_other_paper_flexibility_p2h_hydrogen_electricity.output',
'industry_other_paper_flexibility_p2h_network_gas_electricity.output'

I would expect the output variety not to be included as the output deals with heat.

Another question is related to the import/export of electricity:

'energy_export_electricity.output', and 'energy_export_electricity.input', are both included but 
'energy_interconnector_imported_electricity.output' is the only reference to import. 

Is there some kind of double-counting here?

**Comment by antw** [comment]
Flexibility technologies have both input and output curves, even in cases where it doesn't make sense (P2H, P2G). This can probably be improved when it comes to the CSV dump.

> 'energy_export_electricity.output', and 'energy_export_electricity.input', are both included but
'energy_interconnector_imported_electricity.output' is the only reference to import.

Export is a flexibility option ([flex/curtailment](https://github.com/quintel/etsource/blob/9ef286c9bd3d20d58aaec796973c0103aa326bec/nodes/energy/energy_export_electricity.ad#L6-L7)). Import is a producer ([producer/dispatchable](https://github.com/quintel/etsource/blob/9ef286c9bd3d20d58aaec796973c0103aa326bec/nodes/energy/energy_interconnector_imported_electricity.converter.ad#L6-L7)).

**Comment by ChaelKruip** [comment]
Thanks @antw. Closing this!
