### ISSUE TITLE
Weather years should be shown on PRO for Dutch datasets

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3286]
One of our clients found out that the weather years functionality doesn't show on PRO for all Dutch datasets. 

![Screen Shot 2020-03-23 at 15 44 53](https://user-images.githubusercontent.com/32833996/77328816-5ffb3800-6d1d-11ea-9e24-282c10faaa49.png)

@noracato and I had a look into this issue and found that:

- weather curves input element is dependent on the area dependency `has_weather_curves`: https://github.com/quintel/etmodel/blob/production/config/ymodel/input_elements.yml#L13328

- for example the Dutch dataset includes `- has_weather_curves = true`: https://github.com/quintel/etsource/blob/master/datasets/nl/nl.full.ad#L10

So nothing seems to be going wrong there!

On BETA the weather years is shown! So we thought that it had something to this commit of @noracato fixed it: https://github.com/quintel/etmodel/commit/5b94772f5d8e9fe574070665c94dd42ddec0c35a

@antw , shall we cherry-pick this to PRO? Then this client can use the weather years again and doesn't have to wait for the deploy.

Notifying @ChaelKruip

**Comment by noracato** [comment]
> On BETA the weather years is shown! So we thought that it had something to this commit of @noracato fixed it: 5b94772

However, the above issue did not specifically occur after switching datasets (on which my fix was based). So I'm not 100% sure this commit will fix the issue.

**Comment by antw** [comment]
> @antw , shall we cherry-pick this to PRO? Then this client can use the weather years again and doesn't have to wait for the deploy.

I've done so. I can't reproduce the issue myself, so hopefully that's fixed it.

**Comment by marliekeverweij** [comment]
Yes it's fixed, thanks! 

The client said that the weather years were shown when forcing an update (CTRL + F5), so I think it had something to do with the caching, right? So then this commit (https://github.com/quintel/etmodel/commit/5b94772f5d8e9fe574070665c94dd42ddec0c35a) has fixed it?

Notifying @jorisberkhout as he is really into caching problems ;)
