### ISSUE TITLE
Setting a low cut-off COP for hot water gives an error in an

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3287]
The annual chart of "Demand curve of hybrid heat pump for space heating" returns an error when hot water is supplied by electricity.

Setting COP of HHP hot water to 1 or other low value returns the following error when the annual display of the chart is open.

![image](https://user-images.githubusercontent.com/19907658/77339781-98eed900-6d2c-11ea-9f85-c3d5f86bfc6d.png)

**Comment by marliekeverweij** [comment]
@antw, I am not sure how this could happen. I've tested different threshold COP setting for hot water and any value below 1.7 returns this error. I suppose the error is triggered when the network gas profile only returns zeros. Could you maybe have a look at this issue?
