### ISSUE TITLE
Hourly charts - shall we make 'whole year' the default setting?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3291]
Currently the hourly charts first show the first week of January:
![Screen Shot 2020-03-24 at 14 15 16](https://user-images.githubusercontent.com/32833996/77429578-2d634500-6dda-11ea-952f-4bda372b7ed2.png)

I actually always immediately go to 'whole year':
![Screen Shot 2020-03-24 at 14 15 24](https://user-images.githubusercontent.com/32833996/77429630-410eab80-6dda-11ea-8c25-f9ea2a240723.png)

Shall we make 'whole year' the default setting?

**Comment by marliekeverweij** [comment]
@antw this has been fixed on BETA right? So shall we close it or do you first want to merge it with PRO as well?

**Comment by antw** [comment]
> do you first want to merge it with PRO as well?

It's extremely low-impact and unlikely to break anything, but unless it's important to be on production now, I'll wait until the next scheduled deploy.
