### ISSUE TITLE
Some old menu items have reappeared on BETA

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3307]
See screenshots below.

![tabs](https://user-images.githubusercontent.com/32056448/78896994-c0a2a880-7a71-11ea-9d7d-adc934d1a8bd.png)

![shortname](https://user-images.githubusercontent.com/32056448/78896999-c1d3d580-7a71-11ea-9cf3-46a6cdb3f09d.png)

**Comment by noracato** [comment]
All the dependencies of the sidebar items seem to have dissapeared. I'll look into where that happend and will restore them.
