### ISSUE TITLE
The datadump of scenario input values includes old input keys

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3328]
The input values export of a saved scenario (by typing `.csv` behind the url in the browser) seems to include some old input keys, such as `buildings_ventilation_rate` and `buildings_waste_heat_recovery`.

@noracato, do you know how this export works? Could it be based on some hard-coded (outdated) list of inputs? And do you know if the values are rounded to a certain number of decimals?

![image](https://user-images.githubusercontent.com/5946498/80085036-01152280-8558-11ea-8a6d-4ede2473d569.png)

**Comment by noracato** [comment]
The export works by selecting **all** InputElements (sliders), printing their name and associated user value (if there is one). My guess is that there are some sliders still present in the interface files, that have been outdated or hidden. There also is no check for area dependencies etc, the datadump just simply prints **all** sliders.

**Comment by redekok** [comment]
I see, thanks. Where are all InputElements selected? Because `buildings_ventilation_rate` and `buildings_waste_heat_recovery` seem not to be present on ETSource or ETModel anymore?

**Comment by noracato** [comment]
[This](https://github.com/quintel/etmodel/blob/master/app/views/saved_scenarios/show.csv.erb) is where the selection takes place. On `production` the keys you mention are still present in the interface ymls.

**Comment by redekok** [comment]
All right, so if I understand correctly, this issue will be partly fixed by the next deploy? Since the old keys I mentioned are not in [this list](https://github.com/quintel/etmodel/tree/master/config/interface/input_elements) on BETA?

It might also be nice to consider relevant dependencies and omitting the inputs that are not relevant for the current scenario. Not very urgent, just a nice-to-have! :)

**Comment by noracato** [comment]
> All right, so if I understand correctly, this issue will be partly fixed by the next deploy? Since the old keys I mentioned are not in this list on BETA?

If that's the case, yes! 

> It might also be nice to consider relevant dependencies and omitting the inputs that are not relevant for the current scenario. 

Fully agree, would be strange to see a slider popping up in your datadump that you don't remember seeing in the ETM. Would only take a quick minute to fix 😄
