### ISSUE TITLE
iNET questions the impact of EV charging on network load - is this correct?

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#3330]
Yesterday we demonstrated this scenario: 
https://pro.energytransitionmodel.com/saved_scenarios/9131

There were some doubts about the limited impact of EV charging on network loads. This is what this scenario shows (I changed the profile to 100% Smart Elaad, but the profiles make little difference):
![image](https://user-images.githubusercontent.com/308563/80105460-ed2de880-8578-11ea-9e65-c99f2fed616f.png)

It looks like the peaks are roughly 2 GW. This seems low.

Their reasoning was as follows: 

1. EV power demand is 48.17 PJ = ~13.4 TWh. Cars charging 24/7 would then give load of: 14.4 TWh/8760h = ~1.5 GW. 
2. Of course, cars don't charge 24/7, so the load must be concentrated in hours when many charge together.

Now, I am not convinced this conclusion is correct. I think we have a chance to show how transparent the ETM is about this by verifying the result and sharing this with iNET.

I suggest we:

1. Verify that the annual power demand is roughly correct.
2. Change the profile setting to 100% Smart Elaad (to simplify things). 
3. Dump the resulting charging curve and plot it.
4. Establish the peak load impact of charging EV's
5. Look at the profile-documentation for explanation of behavior and see if the network impact is as expected
6. Feel free to use the correspondence with Maarten if that helps. 
6. Write up the results and share with me and @ChaelKruip. We will share with iNET

**Comment by marliekeverweij** [comment]
We have compared the peak demand for EVs (in [this scenario](https://pro.energytransitionmodel.com/saved_scenarios/9131)) with reference values of Stedin and Enexis. Conclusions first:
- The peaks of all ETM EV profiles are low compared to the reference values of Stedin and Enexis
- 100% slim laden has the lowest peaks in this scenario (3.3 GW), then regulier laden (3.6 GW), then overal laden (3.7 GW), then snel laden (4.0 GW) and thuis laden has the highest peaks (4.1 GW)
- The ETM does not update the number of cars if users change the modal split or the total number of passenger kilometers. I will create an issue for that as it impacts the flexibility and cost calculation.

Below you can see the table that we have sent to iNET (sorry in Dutch!). FYI: we have calculated the future number of cars in this table ourselves based on the slider settings in the scenario (the modal split and number of passenger kilometers have been updated).

II3050   Regional Sturing 100% slim laden | Piek per auto   o.b.v. scenario Regulier 2050 | Referentiewaarden   Steden & Enexis
-- | -- | --
elektriciteitsverbruik   EVs [PJ] | 48.17 |  
elektriciteitsverbruik   EVs [TWh] | 13.38 |  
vraagpiek EV   slim laden [GW] | 3.30 |  
vraagpiek EV   thuis laden [GW] | 4.05 |  
aantal BEVs   [miljoen auto's] | 5.8 |  
verbruik per   auto [kWh/BEV] | 2316 |  
piek per auto   slim laden [kW/BEV] | 0.60 | 0.85 - 1.0
piek per auto   thuis laden [kW/BEV] | 0.70 | 0.85 - 1.0

**Comment by ChaelKruip** [comment]
I am still left with some questions to be honest:
* Are our profiles not peaked enough?
* Do we underestimate the demand for people kms?
* Do we overestimate the number of BEV?

Should we look into the assumptions that underly the system operator values?
