### ISSUE TITLE
Chart list should load again

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3340]
At the moment the chart list does not load on BETA when clicking on 'see more charts':

![Screenshot 2020-05-04 at 16 03 48](https://user-images.githubusercontent.com/32833996/80975000-d5c8e800-8e21-11ea-8dcb-232e570a1659.png)

**Comment by noracato** [comment]
After a quick look: all OutputElements are interpreted as hidden (although they have attribute `hidden: false`), that's why they don't show. I'll go and try to correct it!

**Comment by noracato** [comment]
Closed by #3338
