### ISSUE TITLE
There seems to be a shift in the profiles used for the LV and MV net

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3353]
Does it make sense that the peaks on the LV net occur a couple of months later (or sooner) on the MV (and HV) net? It seems as if the profile has shifted between the different voltage levels. Could anybody explain this to me? Or is it a bug?

Notifying @antw @ChaelKruip @michieldenhaan @marliekeverweij @DorinevanderVlies (and anybody else who is interested 😄) 

![image](https://user-images.githubusercontent.com/5946498/82824403-8cf8d200-9ea9-11ea-9697-28d2f9a5b0ee.png)

**Comment by marliekeverweij** [comment]
Interesting! I think it's a bug and I am guessing that it has something to do with the heat calculation starting the 1st of April.....

**Comment by ChaelKruip** [comment]
> Interesting! I think it's a bug and I am guessing that it has something to do with the heat calculation starting the 1st of April.....

That would also be my guess!

**Comment by antw** [comment]
It's the "residual" curve which isn't rotated. We build that curve by accessing the merit order directly; the merit order knows nothing about curves being rotated. I'm not sure how to *cleanly* fix this. I'll give it some thought.

**Comment by marliekeverweij** [comment]
I think we should fix this before the deploy, so I have added the deploy milestone
