### ISSUE TITLE
FCE is currently disabled. Shall we remove links, documentation and code or re-active it?

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3357]
The link to the fuel chain emission sector does not work.
https://beta-pro.energytransitionmodel.com/scenario/supply/fce/coal
It directs to user to the supply electricity section.

Have any changes been made to this sector recently? @marliekeverweij @antw ?

**Comment by antw** [comment]
The FCE sidebar items has been set to `dependent_on: _always_hidden`; it is effectively disabled. Therefore the ETM redirects you to the first slide in the supply section.

The links in Supply → Fuel production should probably be taken out, and if FCE is being removed permanently, it might be best to delete the sidebar item, slides, and sliders from the interface YAML files.

**Comment by DorinevanderVlies** [comment]
> The links in Supply → Fuel production should probably be taken out, and if FCE is being removed permanently, it might be best to delete the sidebar item, slides, and sliders from the interface YAML files.

I agree!
I opened this issue because we received a questions about this from a user.

If FCE is not active anymore we should remove references and documentation and (preferably) also code and information.

Renaming this issue to make a decision about this

**Comment by DorinevanderVlies** [comment]
Notifying
@jorisberkhout @AlexanderWirtz @michieldenhaan @MartLubben @noracato @redekok @ChaelKruip

**Comment by antw** [comment]
Related issue: https://github.com/quintel/etmodel/issues/2986

**Comment by michieldenhaan** [comment]
Closed: https://github.com/quintel/etmodel/pull/3475
