### ISSUE TITLE
Is our default price for import/export of electricity is too high? (leading to much more export than the energy balance actually shows)

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3366]
When opening a new NL scenario, there is a blank space between the 'Total electricity demand' line and the series underneath. While comparing the chart with LIVE, I found out that the Agriculture electricity demand is missing. However on LIVE agriculture is a relatively small compared to the other series, so maybe more is missing?

![Screenshot 2020-06-08 at 11 30 32](https://user-images.githubusercontent.com/32833996/84015349-feda1c80-a97b-11ea-89f4-430604063ec9.png)
![Screenshot 2020-06-08 at 11 31 08](https://user-images.githubusercontent.com/32833996/84015354-013c7680-a97c-11ea-874f-44bba12fb47e.png)

**Comment by ChaelKruip** [comment]
I think @antw has pointed out that export now makes up a lot of the (hidden) demand. Perhaps we should include export explicitly? Or only show the 'domestic demand' as a red line here? I think we had this discussion on BC already as I'm having a strong deja-vu!

**Comment by ChaelKruip** [comment]
On a related note: Perhaps our default price for import/export of electricity is too high (leading to much more export than the energy balance actually shows. 

@marliekeverweij can you set up a meeting with @AlexanderWirtz and myself to remedy this?

**Comment by marliekeverweij** [comment]
> I think @antw has pointed out that export now makes up a lot of the (hidden) demand

Yes, you're right, that's it! Because of the update interconnection modelling dispatchable plants can now produce solely for export and that's the case now on beta (117.8 PJ extra electricity demand because of export):
![Screenshot 2020-06-08 at 11 46 45](https://user-images.githubusercontent.com/32833996/84016838-27631600-a97e-11ea-8f27-8dffc69c9aa6.png)
![Screenshot 2020-06-08 at 11 47 21](https://user-images.githubusercontent.com/32833996/84016850-2d58f700-a97e-11ea-90e3-160860573ebc.png)

I'll rename this issue and create a separate issue for the missing series for agriculture 

>  Perhaps we should include export explicitly? Or only show the 'domestic demand' as a red line here? I think we had this discussion on BC already as I'm having a strong deja-vu!

In [this basecamp todo](https://3.basecamp.com/3797409/buckets/16762656/todos/2697732644#__recording_2701640445) we decided to included export demand to the demand line. So indeed export should be added as a series to this chart. Let us know when you think different about this (but please read the BC todo first, where you can find the reasoning for this choice ;) )

> On a related note: Perhaps our default price for import/export of electricity is too high (leading to much more export than the energy balance actually shows. @marliekeverweij can you set up a meeting with @AlexanderWirtz and myself to remedy this?

Yes!
