### ISSUE TITLE
Should there be heat buffers modeled for power-to-heat / hybrid heat boilers in industry?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3368]
While fixing this issue https://github.com/quintel/etengine/issues/1118 we were wondering: in reality, are there heat buffers installed for power-to-heat / hybrid heat boilers in industry? If yes, how large should these buffers be? This is something we should investigate in the future. Currently a small heat buffer of 50 MWh is modeled for each power-to-heat boiler in industry and that's not really based on source data.

Notifying @antw @ChaelKruip @AlexanderWirtz

**Comment by AlexanderWirtz** [comment]
I am not expert, but why SHOULD there be a heat buffer? Is there a technical reason?

**Comment by ChaelKruip** [comment]
>  I am not expert, but why SHOULD there be a heat buffer? Is there a technical reason?

The main reason I can think of is the capacity mismatch between heat demand and excess electricity. If you have a LOT of excess in one hour, but only a bit of demand it might be nice to convert the whole peak of excess and spread the resulting heat out over a longer period of demand.

**Comment by marliekeverweij** [comment]
This issue is something we want to research together with a client in the future. Questions: how should power-to-heat in industry ideally be modeled in the ETM? With or without heat buffers? What size and capacity should these buffers have?

Therefore removing deploy milestone
