### ISSUE TITLE
Can we mark the Polish dataset as 'Demo version' or remove it altogether?

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#3370]
In order to support a private Polish initiative similar to a National Energy Agreement to explore ways in which 'Just Transition Fund' money earmarked in the EU's Green Deal might be best spent transforming the Polish energy system, it is worth labeling our outdate Polish dataset differently. 

The current Polish dataset version is very old and out of date, but this is not obvious to people who are not familiar with the ETM. I think there are two solutions. Either we:

1. remove/hide the dataset altogether - a bit drastic perhaps
2. clearly mark it as 'out of date' or a 'demo version' or something like that.

@ChaelKruip and @marliekeverweij this would ideally be part of the deploy. Re-assign as needed.

**Comment by marliekeverweij** [comment]
Cool!!

I would not remove / hide it, as it's cool to show that we've already made the dataset in the past. Maybe we could show the dataset year in brackets behind the country? Or maybe with a nice layout / in grey for example? 

![Screenshot 2020-06-09 at 09 32 08](https://user-images.githubusercontent.com/32833996/84119026-1c6abd00-aa34-11ea-9c06-44ceffa37160.png)

However, we should do that for all countries then I would say. Actually for all other datasets as well, that's maybe not desired. 

So then I would go for option 2 'out of data'! With or without the date behind?
![Screenshot 2020-06-09 at 09 36 57](https://user-images.githubusercontent.com/32833996/84119578-db26dd00-aa34-11ea-83c5-f6bea788f4ac.png)

**Comment by ChaelKruip** [comment]
> clearly mark it as 'out of data' or a 'demo version' or something like that.

I agree that we should make clear that this is not up-to-standard indeed!

**Comment by AlexanderWirtz** [comment]
Sorry, my typ-o: should be 'Out-of-date'

**Comment by ChaelKruip** [comment]
Just an idea: perhaps we can add a system to show the 'quality' of a dataset. Poland is currently a one-star dataset but The Netherlands is a three-star dataset. 

It might help clients to decide whether they want to upgrade their dataset to a higher standard if we give the stars more meaning:

For country datasets:
- One star: National data combined with Dutch assumptions
- Two stars: Added realism in installed capacities of power plants, weather profiles
- Three stars: All country dependent data has been researched including capacity of electricity network, insulation values, modality splits and market shares of technologies

For local datasets a similar system might apply
