### ISSUE TITLE
Remove gql search from admin section?

### ISSUE THREAD

**Issue by noracato** [quintel/etmodel#3372]
I just found out the gql search function on the admin page is broken on beta. As we now have all the queries for output elements (etc) written down in the interface yamls, and can find them with a simple cmd+F, I'm not sure we need this search functionality anymore. Or do we have some big users?

My question is: fix the gql search or remove it?

Notifying @ChaelKruip @michieldenhaan @redekok  @antw @marliekeverweij @MartLubben

**Comment by michieldenhaan** [comment]
I'm fine with removing it (I've never used it). Maybe others have?

**Comment by antw** [comment]
Agree with @michieldenhaan. Now that everything is defined in YAML, `git grep` would seem to be just as good for this purpose.

**Comment by MartLubben** [comment]
I have used it, but I will adapt to the new situation. :)

**Comment by redekok** [comment]
Fine for me as well!
