### ISSUE TITLE
Incorrect interconnector capacity for derived datasets

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3385]
![image](https://user-images.githubusercontent.com/33415156/84400322-2b9f6580-ac02-11ea-8f87-cabc7b067c69.png)

Example Blaricum

**Comment by MartLubben** [comment]
The same is true for all other regions I checked, for example Holland Rijnland:
![image](https://user-images.githubusercontent.com/33415156/84401500-a1580100-ac03-11ea-8576-153d14cb3c9d.png)

**Comment by MartLubben** [comment]
It has to do with the interconnection: 
![image](https://user-images.githubusercontent.com/33415156/84401730-e714c980-ac03-11ea-9057-746132a556c4.png)

**Comment by marliekeverweij** [comment]
Good catch @MartLubben !

I think it has something to do with this query[interconnection_net_capacity_delta_present_future](https://github.com/quintel/etsource/blob/master/gqueries/modules/network_calculation/interconnection_net/capacity/interconnection_net_capacity_delta_present_future.gql)

QUERY_FUTURE(interconnection_net_capacity_future) returns the Dutch interconnector capacity for local datasets and QUERY_PRESENT(interconnection_net_capacity_present) returns the local interconnector capacity. So the capacity delta becomes huge! Not sure what goes wrong here though

**Comment by michieldenhaan** [comment]
Ideally these costs should be 0 I think for derived datasets. As the electricity they 'import' simply comes from the HV grid (for which we already charge costs)

**Comment by marliekeverweij** [comment]
@michieldenhaan and I just had a chat about this issue and agreed that there's indeed something going wrong with the queries I noted in my previous post. @antw do you maybe have time to find out what's going wrong? I will assign you this issue 

For GM0153_gouda this is what the queries return:
![Screenshot 2020-06-12 at 11 30 20](https://user-images.githubusercontent.com/32833996/84488357-57712880-aca0-11ea-977a-66bdab9a8a1c.png)
![Screenshot 2020-06-12 at 11 31 28](https://user-images.githubusercontent.com/32833996/84488382-63f58100-aca0-11ea-9861-083ac67196b2.png)

**Comment by antw** [comment]
Pretty sure this is https://github.com/quintel/etsource/issues/1757 again. I'll try to fix this once-and-for-all today.
