### ISSUE TITLE
Documentation link on hydrogen production slide should work again

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3387]
Maybe we should check all documentation links :) Reassign somebody else if you want to!

Clicking on this documentation link: 
![Screenshot 2020-06-11 at 17 23 47](https://user-images.githubusercontent.com/32833996/84405492-7d4aee80-ac08-11ea-8b69-af07638b312b.png)
Gives this error:
![Screenshot 2020-06-11 at 17 24 24](https://user-images.githubusercontent.com/32833996/84405554-95227280-ac08-11ea-9039-2633550b08d5.png)

**Comment by michieldenhaan** [comment]
Is this PRO? 🙈

**Comment by noracato** [comment]
@michieldenhaan, yes I guess it's pro. It looks like the links have already been fixed by a5997d60b48b6d6e2f0fc5116484fa5ceabf80d6 on beta in april but have not been picked to pro yet! I'm closing this issue!

**Comment by marliekeverweij** [comment]
OMG! 😅
