### ISSUE TITLE
Scenario selector should show selected scenario's after navigating away and back

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#3391]
Initial selection is made:
![image](https://user-images.githubusercontent.com/1303760/84494634-28f84b00-acaa-11ea-90d3-9d0876dabe54.png)
Looking at the result:
![image](https://user-images.githubusercontent.com/1303760/84494681-39102a80-acaa-11ea-9179-de49bbeb803f.png)
Navigating back (it should be nice to have a link/button to return to the selection menu):
![image](https://user-images.githubusercontent.com/1303760/84494763-5644f900-acaa-11ea-8303-5a97fe39de1c.png)
Selecting a new set (you would think!):
![image](https://user-images.githubusercontent.com/1303760/84494803-678e0580-acaa-11ea-9e9d-f3d3c71ab984.png)
Oops! Previous selection was still active:
![image](https://user-images.githubusercontent.com/1303760/84494848-7d032f80-acaa-11ea-862a-87d05ffc0c93.png)

**Comment by antw** [comment]
This used to work fine, and still works in Firefox. My guess is something has changed in Chrome such that the (hidden) checkboxes aren't immediately re-ticked when the page reloads?

I just delayed the check slightly, and this seems to do the trick.
