### ISSUE TITLE
Investment table should show all translations for heaters in industry

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3394]
At the moment the investment table is missing translations for most heaters in industry

![Screenshot 2020-06-12 at 14 16 15](https://user-images.githubusercontent.com/32833996/84501879-96f73f00-acb7-11ea-8eaa-89a171f22aeb.png)

**Comment by noracato** [comment]
On [this branch](https://github.com/quintel/etmodel/tree/fix-investment-table-translations) I added two [new translation files](https://github.com/quintel/etmodel/blob/fix-investment-table-translations/config/locales/interface/input_elements/en_investment_table.yml) with all the missing titles. Right now they're all translated as `GAS`. I think it might be quicker if somebody else than me looks up/remembers the right translations, as I'm not up to date on naming conventions.
