### ISSUE TITLE
Missing translation Required additional infrastructure investments

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3396]
![Hoe werkt het Energietransitiemodel - Welkom! - Energietransitiemodel - beta-pro energytransitionmodel com 2020-06-12 17-47-51](https://user-images.githubusercontent.com/32056448/84521191-f3b52280-acd4-11ea-8342-2dd241e3b398.png)

**Comment by marliekeverweij** [comment]
Assigning @antw  , as I cannot find out why the translation is not showing up. The total series are not shown in the [additional_infrastructure_investments.yml](https://github.com/quintel/etmodel/blob/master/config/interface/output_element_series/additional_infrastructure_investments.yml), so it's probably a custom chart
