### ISSUE TITLE
Scenario reports displays number of excess hours incorrectly

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#3399]
The following scenario reports display the number of excess hours incorrectly (see screenshot as an example):
- Dutch national (twice, under _Elektriciteitsoverschotten_ and _Onbenut potentieel_)
- English national (under _Unused potential_)
- Dutch regional (under _B2. Flexibiliteit_)

![Screenshot 2020-06-15 at 11 36 34](https://user-images.githubusercontent.com/4669028/84643939-c350cc80-aefe-11ea-9e79-8609e2a51279.png)

**Comment by marliekeverweij** [comment]
This is a strange issue as it does not always show up like in you screenshot and there seems to be nothing going wrong in the scenario report code. It uses this query [dashboard_total_number_of_excess_events](https://github.com/quintel/etsource/blob/master/gqueries/output_elements/dashboard/dashboard_total_number_of_excess_events.gql)

**Comment by antw** [comment]
Fixed by https://github.com/quintel/etsource/commit/40557c2fe6aa53abd2bb604205778a57e6b0501a.
