### ISSUE TITLE
Dutch national scenario report has error message

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#3402]
See screenshot
![Screenshot 2020-06-15 at 11 38 54](https://user-images.githubusercontent.com/4669028/84645027-4888b100-af00-11ea-97ab-970c0f896ae9.png)

**Comment by marliekeverweij** [comment]
I do not see anything wrong in the code: https://github.com/quintel/etmodel/blob/master/config/reports/main.nl.liquid#L514-L518 
@noracato could you maybe have a look at this?

**Comment by noracato** [comment]
The query that seems to create the error (`dashboard_total_costs` ) seems to always return 0 for the `present`:

<img width="971" alt="Screenshot 2020-06-15 at 16 28 09" src="https://user-images.githubusercontent.com/14875123/84669538-4127ce80-af25-11ea-97ce-756f9a69fd76.png">

Maybe you can just remove the sentence for now?

**Comment by marliekeverweij** [comment]
We will remove this sentence from the report :)

**Comment by antw** [comment]
> We will remove this sentence from the report

No need to remove the sentence. I've fixed the JavaScript error.
