### ISSUE TITLE
Series in hourly electricity charts should be consistent when exporting and curtailing excess electricity

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3410]
I am looking at this preset scenario: [Net voor de Toekomst - Regie Nationaal](https://pro.energytransitionmodel.com/scenarios/369650) and I found that the series in the hourly electricity charts are not consistent when exporting and curtailing excess electricity.

For the start situation (having touched no sliders), the volume/shape of excess electricity (above the demand line) is consistent among the three hourly electricity charts:

![Screenshot 2020-06-17 at 11 08 40](https://user-images.githubusercontent.com/32833996/84879389-70f0e680-b08b-11ea-8731-2175d84dcc02.png)

However, if I put all flexibility technologies to zero and only export & curtail excess electricity, the excess electricity peaks are different for each hourly chart:

![Screenshot 2020-06-17 at 11 13 58](https://user-images.githubusercontent.com/32833996/84879862-11470b00-b08c-11ea-85ca-cfd8c0c632d7.png)

BTW: the new interconnector-feature is switched off in both situations, so only excess electricity can be exported. 

The electricity production chart is showing all electricity produced per hour and thus shows the correct excess electricity peaks (this charts also doesn't change in the above two situations). I am not sure what's going on with the other two charts, but see a few interesting things:
- Curtailment is not included in the 'Electricity demand per hour' chart. I think it should be part of the 'Flexibility' series
- Curtailment in the 'Use of flexibility options per hour' chart is shown on top and underneath the demand line. It should be shown on top! When that's fixed, then the excess electricity peaks will be the same for the hourly flexibility options and hourly electricity production chart.
- Export is shown differently in the 'Electricity demand per hour' chart and the 'Use of flexibility options per hour' chart. There seems to be more export in the demand chart than the flexibility chart. These two export-queries should be checked.

I saw another issue with the hourly demand line. I thought export was now included in the 'Total electricity demand'-line. However, in the hourly demand chart export is shown on top of the demand line when the interconnector-toggle is switched off and export is shown underneath the demand line when the interconnector-toggle is swithed on. I could create a separate issue for this, but I think it's related to the rest:
![Screenshot 2020-06-17 at 11 32 02](https://user-images.githubusercontent.com/32833996/84881563-566c3c80-b08e-11ea-8f2e-ebd46ef366fc.png)
![Screenshot 2020-06-17 at 11 32 12](https://user-images.githubusercontent.com/32833996/84881582-5c621d80-b08e-11ea-9b06-3c73f4b8e09a.png)

@antw , I am assigning you this issue. But if more people have an idea how to fix this, please comment below.

**Comment by ChaelKruip** [comment]
Good catch @marliekeverweij!

**Comment by antw** [comment]
I fixed the problem with the flexibility chart.

> I saw another issue with the hourly demand line.

This is unrelated to the flex chart. I've created a new issue with more background: #3411.

**Comment by marliekeverweij** [comment]
Thanks for the quick fix!
