### ISSUE TITLE
Inconsistent treatment of export's contribution to total demand

### ISSUE THREAD

**Issue by antw** [quintel/etmodel#3411]
When export is disallowed from consuming energy from dispatchables, it is treated as a flexibility option, and therefore does not contribute to the total electricity demand. However, when it is allowed to use dispatchable, it is classed as a User, and therefore *does* contribute to total demand.

| Dispatchables disallowed | Dispatchables allowed |
| --- | --- |
| ![](https://user-images.githubusercontent.com/32833996/84881563-566c3c80-b08e-11ea-8f2e-ebd46ef366fc.png) | ![](https://user-images.githubusercontent.com/32833996/84881582-5c621d80-b08e-11ea-9b06-3c73f4b8e09a.png) |

Though it makes perfect sense considering the implementation, this behaviour is inconsistent from a user perspective. This was [already discussed on Basecamp](https://3.basecamp.com/3797409/buckets/16762656/todos/2697732644) and the decision was that export should be included as part of total demand. @ChaelKruip @marliekeverweij Do you think this is still true even when export is only provided excess electricity? Doing so has been complicated by the addition of the dispatchable toggle.

---

Originally reported by @marliekeverweij in quintel/etmodel#3410.

**Comment by marliekeverweij** [comment]
>Though it makes perfect sense considering the implementation, this behaviour is inconsistent from a user perspective.

Yes it indeed makes perfect sense considering the implementation!

> Do you think this is still true even when export is only provided excess electricity? Doing so has been complicated by the addition of the dispatchable toggle.

Good question...

I think we should distinguish two types of export and create two series:

1. export of excess electricity (not included in demand line, part of 'Flexibility' series)
2. export of electricity from dispatchables (included in demand line)

However, I do not know how doable it is to make this distinction!

**Comment by marliekeverweij** [comment]
Okay too bad! It's maybe also a bit hard to explain why there are two types of export and why one has been added to the demand line and the other hasn't. So we should make a choice!

> Do you think this is still true even when export is only provided excess electricity? Doing so has been complicated by the addition of the dispatchable toggle.

I think this is not true anymore. When export is only provided excess electricity then it should not be added to the demand line. The electricity demand line would then show all the production peaks by wind and solar and that's confusing.

Therefore my choice would be to not include export in the electricity demand line. We could make this choice clear by renaming the demand line from 'Total electricity demand' to 'Total electricity demand (domestic)', just as in the yearly chart:
![Screenshot 2020-06-25 at 15 10 28](https://user-images.githubusercontent.com/32833996/85726113-117f8000-b6f6-11ea-9d8f-7a2179777656.png)

What do you think @ChaelKruip @antw @AlexanderWirtz and everybody else?

**Comment by marliekeverweij** [comment]
If we decide to not include export in the demand line, then we should delete the export series from the electricity demand per hour chart I think to avoid confusion.

**Comment by antw** [comment]
> @antw how difficult would it be / how much time would it take to separate these two types?

I can't say at this stage, but can investigate when time permits.

**Comment by ChaelKruip** [comment]
> Annoying though it might be (😛 ), it would be possible to keep track of the two loads separately, but I can't think of any way to expose that through the graph: the node has just one electricity_input_curve.

Would it help to split the node up into two nodes?

**Comment by antw** [comment]
> Would it help to split the node up into two nodes?

Yes and no. It solves the problem of where to place the different curves, and provides the means to easily see how much energy is from excess and how much is from demand. I like that. However, I expect this will complicate the merit order by either needing ETEngine to know about both nodes, or by Merit having two separate participants with a shared capacity (not supported at the moment).

I expect it would also complicate the graph structure – we'd need two new nodes per interconnector – and it's not clear to me yet how this would be calculated when the merit order is disabled, or in Refinery (is [the default load](https://github.com/quintel/etsource/blob/ef71d5f249583fb1023134f22af30afcd24a52c3/nodes/energy/energy_interconnector_1_imported_electricity.converter.ad#L23) from excess, or from demand?).
