### ISSUE TITLE
Missing translation in RES dataset (LIVE)

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3412]
![image](https://user-images.githubusercontent.com/33415156/85005534-3a819d00-b159-11ea-8c9a-be4afab78348.png)

**Comment by MartLubben** [comment]
It is the only RES region with a missing translation. It does not seem to be a wider spread issue.

**Comment by redekok** [comment]
Oh I think this is my bad! I will adjust the translations in ETModel
