### ISSUE TITLE
It should be possible to download a chart as an image

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3420]
A client had the idea to make it possible to download ETM charts as an image. I think this is a great idea. It's better than making screen shots (like we're doing at the moment), since the resolution will always be good! We could add a download-button to the top bar of charts. However, this bar is already quite full for some charts, because of the annual/hourly-toggle.

![Screenshot 2020-06-25 at 14 17 33](https://user-images.githubusercontent.com/32833996/85718316-ae3e1f80-b6ee-11ea-9129-5730e78e610c.png)

Extra idea: we could give two download options in a dropdown-menu:

1. As an image (JPEB/PNG?)
2. Download table as CSV (for charts that also have a table)

See CBS download button as example:
![Screenshot 2020-06-25 at 14 22 00](https://user-images.githubusercontent.com/32833996/85718918-43d9af00-b6ef-11ea-97b8-2dd228de5bab.png)

Curious what everybody thinks of this! @antw @noracato @jorisberkhout @AlexanderWirtz @ChaelKruip @redekok @MartLubben @DorinevanderVlies @michieldenhaan

**Comment by DorinevanderVlies** [comment]
I really like this idea!

It will also solve the issue of alignment in presentations.

**Comment by MartLubben** [comment]
What a great idea!

**Comment by redekok** [comment]
Btw, I think this relates to https://github.com/quintel/etmodel/issues/2005. In my opinion it would also be nice to download other tables, such as the investment table, as CSVs.

**Comment by marliekeverweij** [comment]
Okay more than half of our team likes the idea, so I will add it to the backlog and change the title!

**Comment by noracato** [comment]
Done in #3521
