### ISSUE TITLE
Chart "Heat and electricity sources in industry" should be updated

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3449]
One of our clients was interested to know the total heat demand of all industrial sectors, so the sum of all useful heat demand nodes in industry. We have a chart that should be able to show this. However, it's not correct anymore since this year's heat network update: now the industrial CHPs follow the electricity merit order in the future year, so can produce more electricity than in the present year; more electricity than needed in industry. This excess electricity (and excess heat?) is shown in this chart, but should not be.

I will take the chart offline and we can fix it for next deploy.

This is how the chart looks for a fresh NL scenario:
![Screenshot 2020-08-05 at 13 35 47](https://user-images.githubusercontent.com/32833996/89408428-a7102580-d720-11ea-8ddd-ec41c7466c52.png)

Notifying @jorisberkhout

**Comment by ChaelKruip** [comment]
> One of our clients was interested to know the total heat demand of all industrial sectors, so the sum of all useful heat demand nodes in industry.

This is a different question than answered by the chart (even after it's 'fixed') IMO. Perhaps we should replace the out-dated chart with one that actually shows the requested demands?

**Comment by michieldenhaan** [comment]
> However, it's not correct anymore since this year's heat network update

This behaviour was already present before the heat network update. AFAIK it has been possible for a long while to produce more heat and/or electricity with industrial CHPs than there is industry demand. In that sense the chart is working as intended, but I can imagine that a chart showing useful heat demands is more informative as @ChaelKruip suggests.

**Comment by marliekeverweij** [comment]
Closing this issue. Chart works as intended and has been hidden already.
