### ISSUE TITLE
It should be clear for users which data is used in their dataset

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3454]
Currently it is for users of the ETM not clear where the data for the starting year comes from. As a deliverable for the update of the Province and municipalities of Gelderland we will describe the proces of dataset generation. Part of this will be a **general introduction to local dataset generation**. It would be good to give this a place somewhere on the website (https://pro.energytransitionmodel.com/). 

I am curious what you think @ChaelKruip, @antw and @noracato . Reactions of other Q's are welcome as well. I have described some options below, but probably you will have more ideas. 

**Option 1: A link to the common documentation, where also the general dataset creation is described**

![image](https://user-images.githubusercontent.com/33415156/90009712-de418200-dc9e-11ea-92df-550ef46c2875.png)

**Option 2: A data tab in the Sidebar**
This data tab can be used to describe and add links to:

1. Dataset creation and ETLocal
2. Node and carrier source analyses
3. A datadump of the sliders where you can add your own documentation to your assumptions. 
4. Ref to the datadump of scenario outcomes.

![image](https://user-images.githubusercontent.com/33415156/90009907-37111a80-dc9f-11ea-9f69-0d0252e6c3aa.png)

**Option. 3:**
?

**Comment by antw** [comment]
> Option 1: A link to the common documentation, where also the general dataset creation is described

The documentation site does seem like the perfect place for this. It's well-suited to writing larger bodies of text, providing example images, etc. Depending on the intended audience, the docs could either go in "For Users" (if you want to describe generally how we have created existing datasets) or "For Contributors" (if you want to describe how people/QIs can create their own datasets).

**Comment by ChaelKruip** [comment]
> The documentation site does seem like the perfect place for this. It's well-suited to writing larger bodies of text, providing example images, etc. Depending on the intended audience, the docs could either go in "For Users" (if you want to describe generally how we have created existing datasets) or "For Contributors" (if you want to describe how people/QIs can create their own datasets).

I agree. 
Additionally, I think many users are interested in 'where the assumptions and data underlying the ETM come from' but are unable to quickly find that information. 
The route: link in the options menu -> documentation -> data seems a bit indirect.

> Option 2: A data tab in the Sidebar

Although I feel that "Data" is a bit of a dissonant with the other sidebar items, I like the accessibility of this suggestion. Perhaps we can make it "Documentation" and make "Data and Assumptions" a very eye-catching part of it?

**Comment by noracato** [comment]
I think I like option 1 the most; to point users to our documentation website.

However, if you'd like to have the documentation more visible in the sidebar, I propose to add it under 'Overview'. Either as a second sidebaritem, or as a slide in 'Introduction'. Our documentation also provides pages for learning to work with the ETM, so it won't be too out of place there.

As a second sidebaritem it will look something like this (not sure Backgrounds is the appropiate title):

![Screenshot 2020-08-17 at 16 54 10](https://user-images.githubusercontent.com/14875123/90410171-51396700-e0aa-11ea-820e-a253f68fcbbe.png)

**Comment by ChaelKruip** [comment]
> As a second sidebaritem it will look something like this (not sure Backgrounds is the appropiate title):

I really like this option as well. I would simply call it "Documentation" and make the "Data" and "Assumptions" sections very easy to find.

**Comment by michieldenhaan** [comment]
Nice one @noracato!

Would be awesome if we could link to the ETLocal dashboard directly from the ETM. There we have all of the (region specific) data in one place already and the data history feature typically gives a good grasp of where the data comes from.

So the workflow would be:
1. Open ETM for Amsterdam
2. Click on Documentation sidebar
3. Go to 'Data' section/slide
4. Click on the Amsterdam-specific ETLocal link that shows you directly this (without having to look for the region on the map):

![ETLocal - beta-local energytransitionmodel com 2020-08-17 17-09-50](https://user-images.githubusercontent.com/32056448/90412045-e63d5f80-e0ac-11ea-8b8b-f06ab9b73e0b.png)

**Comment by noracato** [comment]
> Click on the Amsterdam-specific ETLocal link that shows you directly this (without having to look for the region on the map):

That would be awesome! But I have to dissapoint you on that one - there's currently (to my knowledge) no way to link to an etlocal dataset like that. We need to do some work on etlocal to make that possible.
