### ISSUE TITLE
Heating groups should always add up to 100%

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#3456]
![image](https://user-images.githubusercontent.com/1303760/91317723-af58ff00-e7ba-11ea-819d-a336a5e679c7.png)

As pointed out by a client. This happens in a random local dataset (Achtkarspelen) but possibly more generally. Could well be that something is awry in the level of the input statements.

**Comment by antw** [comment]
This isn't the case (for me) using a blank Achtkarspelen scenario.

![Screenshot 2020-08-26 at 15 58 55](https://user-images.githubusercontent.com/4383/91320113-12479780-e7b5-11ea-9e1b-89a514ceebdb.png)

Is this for a specific scenario? Is there a known way to reproduce it?

**Comment by ChaelKruip** [comment]
> Is this for a specific scenario? Is there a known way to reproduce it?

I fiddled with some of the sliders and it happened when dragging sliders to zero and having the rest compensate (inadequately). Sorry for not mentioning this initially 😬

**Comment by marliekeverweij** [comment]
I cannot reproduce this issue. @ChaelKruip can you? And do you have a scenario link? :)

**Comment by ChaelKruip** [comment]
I cannot reproduce this anymore either. Closing!
