### ISSUE TITLE
We could make full load hours of solar PV and wind onshore region specific.

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3461]
It is possible to add region specific full load hours of solar and wind to the datasets for municipalities, RES-regions and Provinces.

**How are the region specific full load hours calculated?** 
We simply divide the production by the capacity of the Klimaatmonitor. 

**Benefits**
- The ETM will show the right production and capacity. At this moment only the right production is showed and **not** the right capacity.
- The ETM shows insights into the current full load hours.

**Overview regional full load hours**
![image (1)](https://user-images.githubusercontent.com/33415156/93181598-ed519f00-f738-11ea-876d-0f6bfe15d39d.png)
![image](https://user-images.githubusercontent.com/33415156/93181614-f0e52600-f738-11ea-9ec6-6f8de194b159.png)
Some outliers like Goes, Gouda, Borssele and Cranendonck are due to rounding of the Klimaatmonitor and the effect of newly added capacity which get half the full load hours.

**Disadvantages**
- The full load hours will always be lower then expected if new capacity has been added in the previous year. Lower full load hours are caused by the fact that the new added capacity gets half the full load hours in the calculated production by CBS and the Klimaatmonitor. 
- Scenarios can change if the datasets are updated. 

**Questions/Challenges**:
- Do we need regional specific profiles if we have regional specific full load hours? @DorinevanderVlies 
- What is the effect on existing scenario's if the full load hours in the dataset are changed? Are migrations needed or is a normal effect of a dataset update?

Curious what you all think @DorinevanderVlies @AlexanderWirtz, @ChaelKruip, @jorisberkhout 
and @michieldenhaan.

**Comment by AlexanderWirtz** [comment]
I am confused. So this is already possible. What is this issue about? The method for calculating FLH?

**Comment by MartLubben** [comment]
It could be an enhancement to add region specific full load hours. It is technically possible, but at the moment all Dutch regions have 1920 FLH wind onshore and 876 FLH for solar PV.

**Comment by michieldenhaan** [comment]
> The full load hours will always be lower then expected if new capacity has been added in the previous year. Lower full load hours are caused by the fact that the new added capacity gets half the full load hours in the calculated production by CBS and the Klimaatmonitor.

If this is the case then I wouldn't be in favour of doing this, as this would mean that the 'present' full load hours in the ETM are not representative for the future for many municipalities. The user can of course change this in the weather section but that's quite an advanced part of the model we don't want to bother our regular users with.

**Comment by MartLubben** [comment]
> If this is the case then I wouldn't be in favour of doing this, as this would mean that the 'present' full load hours in the ETM are not representative for the future for many municipalities. The user can of course change this in the weather section but that's quite an advanced part of the model we don't want to bother our regular users with.

I agree, this insight made me change my mind on this topic. Let's close it.
