### ISSUE TITLE
Costs of Coal CCS are always zero in "Total cost of electricity production" chart 

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3466]
Even when Coal CCS is producing electricity, the costs of power production in the chart is zero:

![Screenshot 2020-10-08 at 15 40 59](https://user-images.githubusercontent.com/32833996/95467065-51a10080-097d-11eb-9ae5-803c736d1bd1.png)

Also there seems to be a tipping point in for Pulverised coal when adjusting the coal prices:
![Screenshot 2020-10-08 at 15 59 15](https://user-images.githubusercontent.com/32833996/95468874-3afba900-097f-11eb-8e20-6bd2d4fb5fb2.png)

![Screenshot 2020-10-08 at 15 59 07](https://user-images.githubusercontent.com/32833996/95468885-3f27c680-097f-11eb-85b2-43dc42d12cc9.png)

Not sure if this is a feature or a bug ;) 

Notifying @ChaelKruip 

Scenario: https://pro.energytransitionmodel.com/saved_scenarios/9550

**Comment by michieldenhaan** [comment]
I'm not sure if I understand what you mean. Pulverised coal CCS capacity is 0 MW in the screenshot, isn't that why the pulverised cost of power production is zero? It does look like the chart is missing a coal IGCC CCS series tho.

Regarding the tipping point: I think that's just merit at play. When coal becomes more expensive, it swaps places with import (purple in chart below). The result is that the capacity factor drops from 12% to _almost_ 0%. That means that the coal plant only produces electricity for a few hours per year. The total production cost per MWh for the electricity will be very large in that case, as the full investment costs are divided by very few MWhs.

![image](https://user-images.githubusercontent.com/32056448/95470523-2fa97d00-0981-11eb-9c45-2fcfe43ade5f.png)

**Comment by ChaelKruip** [comment]
> as the full investment costs are divided by very few MWhs.

Marginal costs should be *variable cost* / production. It should, therefore, be independent of full load hours.

**Comment by michieldenhaan** [comment]
I was talking about the chart below, which shows total production costs rather than marginal production costs.

![image](https://user-images.githubusercontent.com/32056448/95474559-887b1480-0985-11eb-8096-811299ead2a9.png)

**Comment by ChaelKruip** [comment]
> I was talking about the chart below, which shows total production costs rather than marginal production costs.

🤦 

Sorry, yes you are right. I was confused: thinking this chart shows marginal costs. False alarm! Sorry for that. Closing this issue.
