### ISSUE TITLE
Flexibilty chart missing gquery 'bunkers_flexibility_p2g_electricity_capacity'

### ISSUE THREAD

**Issue by noracato** [quintel/etmodel#3478]
On BETA etengine returns the following error when opening the Flexibility options chart.
![Screenshot 2020-11-10 at 09 53 08](https://user-images.githubusercontent.com/14875123/98651655-d2676980-233a-11eb-90ab-007e70812893.png)
This was on a fresh NL scenario with only increased wind power (6640 MW onshore coast, 252600 MW onshore inland)

**Comment by marliekeverweij** [comment]
Wow! Time record for issue closing goes to @michieldenhaan !

**Comment by michieldenhaan** [comment]
![fast](https://user-images.githubusercontent.com/32056448/98656526-0e053200-2341-11eb-8217-7cdbeb527792.gif)
