### ISSUE TITLE
Scenarios not loading on beta in IE11

### ISSUE THREAD

**Issue by noracato** [quintel/etmodel#3483]
Right now it's not possible to load any scenario on beta in IE11 (from Windows 10 pro). Problem seems to be in the `header.js`, IE11 reports that `forEach is not supported for this object`

https://github.com/quintel/etmodel/blob/673365da5af2b54f5010cca7399660dc6003c536/app/assets/javascripts/header.js#L69

On pro scenarios load with no problem.

**Comment by antw** [comment]
Fixed by 1abc9539.
