### ISSUE TITLE
Renewable percentage calculation is broken on BETA

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#3490]
For a generic NL 2050 scenario it gives a renewable percentage of 230%:
![image](https://user-images.githubusercontent.com/1303760/98921871-12148980-24d2-11eb-83d7-1100f896e2d6.png)

And the chart seems fishy as well:
![image](https://user-images.githubusercontent.com/1303760/98921792-fad59c00-24d1-11eb-9bed-2e7444f76678.png)

**Comment by antw** [comment]
This is due to [a change I made in ETEngine](https://github.com/quintel/etengine/commit/dc6b33d8710b8b123bd15c37096b3c339dc3bb64) yesterday. I'll revert it and try to come up with an alternative.

**Comment by antw** [comment]
This was indeed due to the "fix" for incorrect shares on the fertilizer CCUS input. I reverted that commit and came up with an alternative which should not have any such side-effects. 😬
