### ISSUE TITLE
Should we explain why CO2 is yet captured in the fertilizer industry sector?

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3491]
Would it be an idea to explain to the user why (for some datasets) some CO2 is captured yet in the fertilizer industry sector? 

![image](https://user-images.githubusercontent.com/5946498/98932886-3a0ae980-24e0-11eb-980f-35173e4672ba.png)

**Comment by michieldenhaan** [comment]
This varies per region (NL is the only dataset with a positive start value), but I'll add a reference to ETDataset in the tool tip.

**Comment by redekok** [comment]
In addition, I noticed that Zuid-Holland has a different share than the Netherlands.

![image](https://user-images.githubusercontent.com/5946498/98940288-0ed9c780-24eb-11eb-8223-cc1759df39bc.png)
