### ISSUE TITLE
II3050 European CO2 governance has different import/export balance

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#3493]
Pro:
![image](https://user-images.githubusercontent.com/1303760/98934561-94a54500-24e2-11eb-9918-4d150f8e6dfd.png)

Beta:
![image](https://user-images.githubusercontent.com/1303760/98934582-a0910700-24e2-11eb-82ba-5bca2cd0f5b4.png)

Especially natural gas seems to be replaced by hydrogen. Makes me wonder if we are looking a the same scenario...

A clue: natural gas seems to show the largest differences:
![image](https://user-images.githubusercontent.com/1303760/98934985-2319c680-24e3-11eb-9ba4-a98795fa1f93.png)

**Comment by antw** [comment]
I've updated the beta scenarios with the input values generated by the CCS migrations:

![Screenshot 2020-11-12 at 12 40 18](https://user-images.githubusercontent.com/4383/98941301-44c77d80-24e4-11eb-95a7-33a822a49e4d.png)
