### ISSUE TITLE
ESDL file not importing correctly

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#3494]
I have downloaded the following ESDL file from the ESDL Map Editor and tried importing it, but I get the following error message

![Screenshot 2020-11-12 at 13 51 25](https://user-images.githubusercontent.com/4669028/98942401-38482280-24ee-11eb-8f2a-84f632f87971.png)

![Screenshot 2020-11-12 at 13 46 32](https://user-images.githubusercontent.com/4669028/98942058-be179e00-24ed-11eb-99ee-7802657d8d15.png)

**Comment by jorisberkhout** [comment]
It's probably due to the file size of that specific ESDL file, others do get imported properly (🎉 ).

**Comment by antw** [comment]
@jorisberkhout How big is the file?

**Comment by redekok** [comment]
@jorisberkhout And how old is this file? I'm guessing it's an outdated (and inefficient) ESDL file. I checked the file size of a more recent ESDL file for the Gooi & Vechtstreek which was around 3 MB.

@antw The max size is currently 10 MB, isn't it? We could raise this somewhat. Not sure if that would have any other effect than the app taking longer to process large files?

**Comment by redekok** [comment]
@antw @noracato Is this issue still relevant or can we close it?

**Comment by antw** [comment]
> can we close it?

I think so. The file size limit for ETModel was increased to 10 MB to match the etm-esdl site (previously it was lower) and ESDL files I've seen are significantly smaller than that. I expect this issue is unlikely to happen again, but if ESDL files _do_ commonly grow larger than 10 MB we can increase the limit further.
