### ISSUE TITLE
The slider for methanol production is disabled for some local datasets 

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3496]
The slider for methanol production is disabled for some local datasets. Not sure if that's intentional? 

The slider seems to be disabled when there's no chemical industry. Hence, it would make sense to disable the input, unless you could also produce methanol for other processes (or export)?

![image](https://user-images.githubusercontent.com/5946498/98944310-2156ff80-24f1-11eb-91e1-81f83fb3ea9b.png)

**Comment by redekok** [comment]
Relates to https://github.com/quintel/etmodel/issues/3497

**Comment by michieldenhaan** [comment]
Fixed, see: https://github.com/quintel/etmodel/issues/3497
