### ISSUE TITLE
Some sliders regarding CCUS seem to be stuck for municipality datasets

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#3497]
I have tested this for Beverwijk (😄 ) and Bergeijk and found that the following sliders are stuck at zero:
- Direct Air Capture (DAC)
- Synthetic methanol (for Bergeijk, this slider is disabled judging from it colour)
- Other use of CO2

Is this intended behaviour @michieldenhaan ?

**Comment by michieldenhaan** [comment]
Fixed! For methanol this was a bug, for DAC and other use the slider max is based on 1990 emissions but for Beverwijk this is too small relative to the slider unit (mega tonne). I've set a minimum of 2 Mton for these sliders now.
