### ISSUE TITLE
Some chart data labels have lots of decimals

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3498]
Nitpicking but could we introduce some max for the number of decimals?

(Btw, I guess it's not deploy critical so didn't add it to the deploy milestone.)

![image](https://user-images.githubusercontent.com/5946498/98946163-d2f73000-24f3-11eb-9bfb-98143d3c6263.png)

**Comment by antw** [comment]
I haven't had any luck reproducing this. Tooltip values for the stacked bar chart are *already* limited to [a maximum precision of 2 decimal places](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/models/quantity.coffee#L168); I cannot explain the screenshot.

If it happens again, can you save the scenario and post the link?

**Comment by redekok** [comment]
Sure, let's close this issue for now.
