### ISSUE TITLE
Uploading a faulty EDSL file should result in more informative message

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#3503]
![image](https://user-images.githubusercontent.com/1303760/98958248-63d50800-2502-11eb-876c-d59f0208b70b.png)

This seems to work fine but if an EDSL file is unable to load, error messaging is not very useful: it just tells you that is cannot be loaded.

Could we add information about:
* Why it failed to load
* What you can do to fix it
* Where to learn more about writing proper/working EDSL and troubleshooting
* ...

**Comment by redekok** [comment]
Good point! This is indeed one of the points of improvement we identified. Not a priority for now though.
