### ISSUE TITLE
Scenario titles of saved scenarios and presets should also be shown in the scenario-bar

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3504]
When I open multiple preset scenarios I sometimes get confused which scenario is which since the title of the preset scenario (f.e. II3050 - European CO2 governance) is not shown in the scenario bar. I think this would be a nice improvement!

Additionally, scenario titles of saved scenarios created by other people do not show up in the scenario bar. I think this would also be nice :) When you then save the scenario yourself you can change that title if you want.

What do you think @noracato  and @antw?

**Comment by Geoneer** [comment]
Put this also in the report title. Now the report title is default value:

![image](https://user-images.githubusercontent.com/218929/99798399-42db6b00-2b31-11eb-93c8-55dff1dc25bd.png)

I'm using the ETM for every RES-region in the Netherlands. So I use the scenario-name, and want to use this name also in the Title of the report.

**Comment by antw** [comment]
I agree with all the above.

We only show the title for your *own* saved scenarios; this is why you don't get a title when opening a featured scenario, or a saved scenario belonging to someone else. I agree this is not ideal, but I didn't get time to adjust it before the 2020.11 release.

**Comment by marliekeverweij** [comment]
@antw I would really like it when this would be done :) I use the featured scenarios often and get confused which one I've opened. Are there more people that would like this? @quintel/core

**Comment by marliekeverweij** [comment]
Great that we can ow see titles of featured scenarios in the scenario navigation bar!

@antw, I think it would also be an improvement to show the titles of saved scenarios created by others in the navigation bar! I just had to open several saved scenarios from others and didn't know which one was which

**Comment by marliekeverweij** [comment]
> If you're loading based on an ETEngine scenario rather than a saved scenario in ETModel (for example) then you will not get a scenario title. That's because the scenario title is not stored in ETModel; scenario titles in ETEngine are deprecated and likely to be removed in the future.

Okay! Yes, I was opening scenarios created through our API, so that's why.
