### ISSUE TITLE
Data-input-field input next to the slider.

### ISSUE THREAD

**Issue by Geoneer** [quintel/etmodel#3505]
As I'm a user of the ETM a lot nowadays, I want to fill in a number of a value items. Now I can't get the value exact the value I want it to be, due to the behavior of the sliders. 

Is it an option to build in a data-input-field next to the slider?

**Comment by noracato** [comment]
Hi @Geoneer,

If I understand your question correctly: we already have a similar feature. When you click the value next to the slider, an input field opens up where you can put the exact value you want (see image below).



![Screenshot 2020-11-20 at 13 06 34](https://user-images.githubusercontent.com/14875123/99798461-5f77a300-2b31-11eb-9784-9b6fa2599e69.png)


Is this already an answer to your question, or did you mean something else, or something more specific? Let me know!

**Comment by Geoneer** [comment]
aha. yes! wish I've seen this before. This helps a lot to define the scenario's to adjust properly. Thanks!

**Comment by Geoneer** [comment]
![image](https://user-images.githubusercontent.com/218929/99820141-a6c15c00-2b50-11eb-97e2-02778f0cbdf5.png)
