### ISSUE TITLE
bug in the [Specificaties warmte- en elektriciteitsproductie]

### ISSUE THREAD

**Issue by Geoneer** [quintel/etmodel#3506]
Output:
![image](https://user-images.githubusercontent.com/218929/99797747-1ecb5a00-2b30-11eb-9eea-cf7fd7c8f826.png)

Input:
![image](https://user-images.githubusercontent.com/218929/99798065-a0bb8300-2b30-11eb-84ce-45acdbea915c.png)

1. I get a value for the amount of gas what is used. 
2. I did not use gas at all
3. I'm setting up a 100% nuclear scenario, without using gas.
4. I'm getting an amount of gas used in warming up houses. 
5. Why?

**Comment by redekok** [comment]
I tried to reproduce this issue but haven't succeeded yet. Is this a scenario for the Netherlands?

When I start a new scenario for the Netherlands, and copy your slider settings for the heating technology mix of households, I get the following (hydrogen, ambient heat and electricity, but no gas):

![image](https://user-images.githubusercontent.com/5946498/99799420-e9743b80-2b32-11eb-9cd1-62c43a7697a6.png)

![image](https://user-images.githubusercontent.com/5946498/99799684-58ea2b00-2b33-11eb-9ebd-936c79b2889c.png)

Very curious if you could describe which steps I should take to reproduce this issue!

**Comment by Geoneer** [comment]
Thanks for the reply! 

It's not a bug. I think it had to do with my local cache in my browser... or whatever. 

I do get similar graph like yours now =>

![image](https://user-images.githubusercontent.com/218929/99817018-ac1ca780-2b4c-11eb-90a2-5c4f05afbe46.png)
