### ISSUE TITLE
Default text in report, independent on the settings... why is this text added in the report?

### ISSUE THREAD

**Issue by Geoneer** [quintel/etmodel#3507]
![image](https://user-images.githubusercontent.com/218929/99818265-4a5d3d00-2b4e-11eb-99b5-ca3c701e16fc.png)

**Comment by Geoneer** [comment]
I mean the whole point 6. Actieagenda part in the report. Not only the blue sentence.

**Comment by ChaelKruip** [comment]
The numbers in the text (-3.5, -7.2 etc.) are dependent on your scenario setting. Or, they should be...

It looks like in your scenario you have fewer solar parks and windturbines compared to the start situation.

Hope this helps!

**Comment by Geoneer** [comment]
Hello @ChaelKruip 

Indeed, I do have fewer solar parks and windturbines. I will 'clean' NL with 100% Nuclear power in my scenario. So the default text inside the report is something you should configure in the report template.....
