### ISSUE TITLE
Total demand/production line in hourly charts disappear when clicked

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3510]
When I click on the total demand or total production line in the legend of hourly graphs, this line disappears from both the legend and the hourly graph itself. There is no clear way to retrieve this line, other than refreshing the page or refreshing the graph.

This example shows the hourly graph for hydrogen production:
![Screenshot 2020-11-25 at 10 44 46](https://user-images.githubusercontent.com/67338510/100210412-3ed19380-2f0b-11eb-8d82-68e8fca33218.png)

When I click on "Hydrogen demand" in the legend, the line disappears:
![Screenshot 2020-11-25 at 10 48 42](https://user-images.githubusercontent.com/67338510/100210915-ccad7e80-2f0b-11eb-9bab-7a566b9390db.png)

This seems like a bug to me. However, if the option to delete the line is a feature, then it could perhaps be made easier to retrieve the line as well.

**Comment by antw** [comment]
It is a bug. I believe there was a desire to be able to toggle the total demand line by flagging it as "not visible". At some point we've changed the legend to only show series which *are* visible, and this has resulted in the legend item disappearing.

I might be able to rectify this during the (ongoing) flexibility charts projects.
