### ISSUE TITLE
Add possibility to delete/archive scenarios

### ISSUE THREAD

**Issue by Geoneer** [quintel/etmodel#3523]
1. I do make a lot of scenario's. Also with version's of them. So my dashboard and all scenario's got a little diffused and cluttered. 

2. Is it possible to delete a scenario? (or more at once...). 

3. If so, how? 

4. If not, is this an option to build in?

**Comment by ChaelKruip** [comment]
> Is it possible to delete a scenario? (or more at once...).

Currently not unfortunately.

> If not, is this an option to build in?

Yes. We have been considering an 'archive you scenario' option to clean up your scenario overview. This will take at least a couple of days of work and, therefore, requires some budget to be carried out.
