### ISSUE TITLE
Aantallen windturbines in verslag komen niet overeen met 't energie-overzicht

### ISSUE THREAD

**Issue by Geoneer** [quintel/etmodel#3524]
Kijk eens naar de onderstaande afbeeldingen. Verslag klopt niet met de energie-mix. 

scenario: https://pro.energytransitionmodel.com/scenarios/798817/energy_mix

![image](https://user-images.githubusercontent.com/218929/103478315-17050380-4dc6-11eb-96e9-b05560cefe80.png)
![image](https://user-images.githubusercontent.com/218929/103478322-284e1000-4dc6-11eb-8d44-f9c8ee608c57.png)

**Comment by noracato** [comment]
Hi @Geoneer 

Voor de Energiemix bestaat een schuifje voor de capaciteit van een windturbine (zie onderstaand plaatje). Dit schuifje staat in jouw scenario zo te zien op 4,3 MW, wat verschilt van de standaard 3 MW die we in het rapport aanhouden.

124 windmolens van 4,3 MW komt (met wat afrondingsverschillen) ongeveer overeen met 177 windmolens van 3 MW

![Screenshot 2021-01-04 at 09 28 12](https://user-images.githubusercontent.com/14875123/103515870-cc3fc600-4e6f-11eb-8f1e-00e431017169.png)
