### ISSUE TITLE
Embedded Youtube video not loading

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3526]
In the Dutch version of the ETM the info for one of the sliders has an embedded youtube video. See either Vraag > Gebouwen > Ruimteverwarming > Gaswarmtepomp in the Dutch ETM or buildings_space_heater_heatpump_air_water_network_gas_share in the nl_demand_buildings.yml file.

Due to an error in loading the video the model only shows a large whitespace (see screenshot below).

@antw first of all, do you know if this error can be fixed?
@ChaelKruip do you think this video should stay in the model at all? I'm in doubt, because the video is 10 years old and I have not yet come across any other embedded youtube videos.

Screenshot of the whitespace and the error:

<img width="1916" alt="Screenshot 2021-01-04 at 11 57 36" src="https://user-images.githubusercontent.com/67338510/103528329-0ca93f00-4e84-11eb-9fef-3d1b93ad3d8d.png">

The error shown in the screenshot:
> Mixed Content: The page at 'https://pro.energytransitionmodel.com/scenario/demand/buildings/space-heating' was loaded over HTTPS, but requested an insecure plugin resource 'http://www.youtube.com/embed/L2EA69MTNU4?fs=1&hl=en_US&rel=0'. This request has been blocked; the content must be served over HTTPS.

**Comment by ChaelKruip** [comment]
> @ChaelKruip do you think this video should stay in the model at all? I'm in doubt, because the video is 10 years old and I have not yet come across any other embedded youtube videos.

Let's remove it!
