### ISSUE TITLE
NaN values for table view of "Hourly production of solar PV" chart

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3531]
The "Hourly production of solar PV" chart has the option to switch to a table view. I would expect the table to display the cumulative production of the different types of solar power over the year in PJ. However, the table gives NaN values in MW:
 
<img width="623" alt="Screenshot 2021-01-06 at 13 57 50" src="https://user-images.githubusercontent.com/67338510/103770973-32227e00-5027-11eb-9af0-d07978117503.png">

For a few of the other hourly charts that I have checked the table view is not enabled at all. I can therefore imagine that this feature is supposed to be disabled for this chart as well. My question therefore is whether the table view can be fixed for this chart, or whether it is supposed to be disabled.

FYI: the table shown above is from the II3050 National governance scenario. This error also occurs in other scenarios.

**Comment by antw** [comment]
I think it's a mistake that the table view is enabled for this chart. Hourly charts usually do not have a table because we don't have a consistent way of summarising their data.

**Comment by mabijkerk** [comment]
Is the summarisation something that can potentially be solved or is it just inherently not possible? In my view enabling the table view for the hourly charts would be an enhancement to the model, so if it can potentially be solved we could add it as a separate issue labeled 'Enhancement'.

**Comment by antw** [comment]
Summarising in a table is certainly possible, but we'd need to decide (perhaps on a chart-by-chart basis) what the table should summarise. Total annual value for each series? Total monthly values? Peak values? Mean values?

Summing the value of each series and showing an annual total is probably good enough for many charts, but may not be the best way to represent the data for others.
