### ISSUE TITLE
Allow users to export their scenario as .esdl when started from .esdl

### ISSUE THREAD

**Issue by noracato** [quintel/etmodel#3535]
Next to starting a scenario based on an .esdl file, users should also be allowed to export their scenario as ESDL. 

# How it works

We'd like to start this functionality out quite simple: only when a user started their scenario with an .esdl file, they are allowed to export the file again. The file the user started with is sent to the `etm-esdl` app, which adjusts the file according to the changes in the scenario, and sends it back to the ETM. 

To achieve sending the correct .esdl file to the etm-esdl app we could either:

-  Have the user browse their Mondaine Drive/computer again for the source file. We would need to have a flag set somewhere that indicates that the scenario did start from ESDL
- Save the Mondaine Drive path to the used file. (Possibly on SavedScenario - but then the scenario should be immediately saved and named upon creation. But to me it also feels strange to save the path on the ETE scenario.)
- Save the .esdl file as a ScenarioAttachment

Here are the pros and cons I could think of for these options

|  | Pros | Cons  |
| --- |---| ---|
| Have the user reselect the file | - Easy to implement (basically the same as import) | - Not very user friendly: users have to remember what exact file and which version of it they used to start the scenario with |
| Save the Mondaine Drive path     | - We can export without the user having to perform a second action (like in the option above)  |  - Error prone </br> - The file may have changed location on the Mondaine Drive, or the user may have lost access. </br> - The contents of the file may have changed drastically - so that the file does not represent the scenario corrctly anymore </br> - For computer-uploaded esdls we would still have to fall back on option one  |
| Save the file as ScenarioAttachment | - The file you are exporting is always the exact one you started with </br> - No second action of the user is required (as above) </br> - Instinctively feels the sanest of all three </br> - We can later add the option to download the source esdl again |  - ESDL files can be large </br> - The ESDL language is still evolving: if you started your scenario from an old version of ESDL, exporting with this file as a basis can become impossible </br> - We would be saving a lot of files that may never be used: when you start from ESDL you don't neccesarily want to export it as well |

# Ideas on what this may look like

The export functionality could be located under 'Actions' in the scenario menu.

![export_action](https://user-images.githubusercontent.com/14875123/104901512-c4a71380-597d-11eb-802c-878bdd38ff4d.png)

## Option 1: a box
Similar to 'Save scenario (as..)' a box pops up asking the user whether to export the esdl file to their computer or to their Mondaine Drive. If the user picks the second option they end up on the 'choose location' part where they can export the scenario.

<div style='display: flex; justify-content: space-between'>
<img src=https://user-images.githubusercontent.com/14875123/104901660-f7510c00-597d-11eb-85f8-fdb6ea9eb345.png width=390px></img>
<img src=https://user-images.githubusercontent.com/14875123/104901815-29fb0480-597e-11eb-95e8-b6e9fca4d2a9.png width=390px></img>
</div>

## Option 2: a seperate export page
However, if the connection to the ESDLSuite is needed with the box open, how would we handle a login and subsequent redirect? Can we reopen the box? Or should this feature just not be presented in a box?

If we would go with a more global export page, we can also add other export formats there later on (such as our _unfindable_ csv export). However, as the reset and save options in the scenario-nav actions menu do not lead you to a seperate page, this idea might collide with that user flow.

<div style='display: flex; justify-content: space-between'>
<img src=https://user-images.githubusercontent.com/14875123/105483545-48c50800-5caa-11eb-9aab-306a6faeaef1.png width=390px></img>
<img src=https://user-images.githubusercontent.com/14875123/105483551-4bbff880-5caa-11eb-8840-a0877945249e.png width=390px></img>
</div>

---

Overal, I think I'm leaning most towards having the files as ScenarioAttachments, but I'm not fully convinced. Same goes for the looks option 2. @antw would you mind taking a look at these plans?

**Comment by noracato** [comment]
I thought about some pros and cons for the three options of how to send the correct esdl file to the etm-esdl app to adjust.

|  | Pros | Cons  |
| --- |---| ---|
| Reselect the file | - Easy to implement (basically the same as import) | - Not very user friendly: users have to remember what exact file and which version of it they used to start the scenario with |
| Save the Mondaine Drive path     | - We can export without the user having to perform a second action (like in the option above)  |  - Error prone </br> - The file may have changed location on the Mondaine Drive, or the user may have lost access. </br> - The contents of the file may have changed drastically - so that the file does not represent the scenario corrctly anymore </br> - For computer-uploaded esdls we would still have to fall back on option one  |
| Save the file as ScenarioAttachment | - The file you are exporting is always the exact one you started with </br> - No second action of the user is required (as above) </br> - Instinctively feels the sanest of all three </br> - We can later add the option to download the source esdl again |  - ESDL files can be large </br> - The ESDL language is still evolving: if you started your scenario from an old version of ESDL, exporting with this file as a basis can become impossible </br> - We would be saving a lot of files that may never be used: when you start from ESDL you don't neccesarily want to export it as well |

**Comment by antw** [comment]
Nice write-up @noracato.

> Next to starting a scenario based on an .esdl file, users should also be allowed to export their scenario as ESDL.

Before expressing an opinion, I must admit to not understanding how having a copy of the original ESDL file helps us export the current scenario as ESDL. Will this file not be stale as soon as the visitor changes a value in their scenario?

Is the etm-esdl app using the original file as a template for generating a new ESDL file? If so, is there any way it could generate a new ESDL file using the scenario values, without the original file?

**Comment by noracato** [comment]
> Is the etm-esdl app using the original file as a template for generating a new ESDL file? 

Yes, that's the case. The ESDL language is for instance used by another app called the MapEditor, where you can place objects like wind turbines on the map. That app saves the coordinate placement of the turbines in the outputted ESDL. So, if you want to makes changes to that ESDL with the ETM, and then export it as ESDL again, you don't want those placement markers of the wind turbines to have vanished.

We can generate a new ESDL file of course, but a lot of the original information will not be in there as it is not within the ETM's scope.

**Comment by antw** [comment]
> Overall, I think I'm leaning most towards having the files as ScenarioAttachments, but I'm not fully convinced.

I think I agree. I don't *love* the idea of storing ESDL files in ETEngine just for the (rare?) case that someone wants to export again, but the user experience would be nicer. If file size becomes a problem – and we don't need to load or parse the ESDL files themselves in ETEngine – we could run them through bzip before storing, but I don't think this is totally necessary.

The only concern I have is: could ESDL files contain data that the uploader would *not* want to share with the rest of the world? If so, I'm not sure whether this is a good option. Since anyone can send a request to ETEngine, this would allow me to see the contents of your private file by exporting your scenario as ESDL. Requiring access to the Mondaine Drive (or requiring the visitor to upload their file again) would avoid this.

If privacy isn't an issue, I agree with your preference to use ScenarioAttachment.

> Ideas on what this may look like *[..]* Same goes [preferring] the looks option 2.

I have no strong preference. I like option 1 more for not having to send the user to a new page – and thus disrupt their workflow – but I think option 2 is better for now:

* It avoids the authentication issues you mentioned.
* One less thing on the main ETM page means one less thing that has to be in version 1 of the front-end refresh.

**Comment by noracato** [comment]
> I don't love the idea of storing ESDL files in ETEngine just for the (rare?) case that someone wants to export again

That was also the main reason I wasn't fully conviced of the ScenarioAttachment option. But then again, how many people will start a scenario from ESDL in the first place who aren't already using ESDL a lot...
Also, we might be using ESDL in another upcoming project, and I think having the files as ScenarioAttachments there could be very useful.

> If privacy isn't an issue, I agree with your preference to use ScenarioAttachment.

Thanks for bringing this up, it honestly didn't cross my mind. I talked to @redekok about it, and she is fine with us storing the files like that.

> but I think option 2 is better for now

Solid arguments!

Thanks for thinking with me on this issue!
