### ISSUE TITLE
Allow visitors to provide feedback on the current page

### ISSUE THREAD

**Issue by antw** [quintel/etmodel#3536]
Inspired (heavily) by Stripe, we'd like a feedback feature added to the ETM header. This will allow visitors to provide quick feedback about the page they have loaded and is the first step to collecting more data to aid the renewal of our front-end.

My intention is for feedback to be sent to a Basecamp project where we'll be able to discuss it and perhaps reply to the sender. We'll include some basic information about the page the visitor was using, which charts are loaded, and a link to the scenario in case they're reporting a problem.

It currently looks like this:

![Screenshot 2021-01-11 at 11 59 34](https://user-images.githubusercontent.com/4383/104179929-80a79200-5404-11eb-9bbb-f814f1380c57.png)

To say this looks like Stripe's version is an understatement:

![Screenshot 2020-12-04 at 15 04 34 15 16 26](https://user-images.githubusercontent.com/4383/104180027-961cbc00-5404-11eb-8e42-7a0989f06806.png)

I would like to think they wouldn't mind, but we might need to differentiate ours a little more.

**Comment by marliekeverweij** [comment]
Wow this is a great idea!!! I am curious what kind of feedback we will receive! It makes us more approachable for users and we can get in contact with them more :)

**Comment by noracato** [comment]
Closed with #3554
