### ISSUE TITLE
It should be possible to download the source analyses for several CCS technologies

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3549]
When you click on the "Download source analysis (Excel .xlsx)" button, you get an error message for the CCS technologies below:
- Industry + CCS
- Direct Air Capture
- Synthetic Methanol
- Transport technologies

Could this be because we're referring to nodes in the molecules-graph?
![Screenshot 2021-01-19 at 16 46 35](https://user-images.githubusercontent.com/32833996/105057865-f0a5c000-5a75-11eb-98fc-f3561d9a7954.png)

![Screenshot 2021-01-19 at 16 39 58](https://user-images.githubusercontent.com/32833996/105057737-cf44d400-5a75-11eb-992c-09d5785f7c5b.png)

Notifying @michieldenhaan

**Comment by noracato** [comment]
The url from where the Excel file should be accessible is set [in this yml file](https://github.com/quintel/etmodel/blob/213da5bd75bb8e7a7279852d3e50e463d052dd52/config/nodes_download_source.yml#L87) All urls in there correctly point to `etdataset-public`, but it looks like `etdataset-public` isn't even with `etdataset`. Making them even again will fix this issue :) 

FYI: You can automatically fetch all the correct urls to the node Excel files with the rake task `fetch_nodes_download_source`, they'll end up in that config yml.

**Comment by antw** [comment]
To add to what @noracato has said, I think [I broke some of the links](https://github.com/quintel/etmodel/commit/10bb8d9a8ac208d02a270e4ac024ce5d7223e77a) when we added the molecule graph. Links to molecule nodes should not have had "energy/" added to their path.

**Comment by noracato** [comment]
Makes more sense @antw, the published state of `etdataset-public` looks alright
