### ISSUE TITLE
Why is it not possible to download source analyses for green gas technologies?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3550]
Related to https://github.com/quintel/etmodel/issues/3549, but the difference is that there's no download-button shown for the green gas producing technologies. I was wondering why this is the case.

![Screenshot 2021-01-19 at 16 50 08](https://user-images.githubusercontent.com/32833996/105058366-6e69cb80-5a76-11eb-8594-0c2b04c14d5f.png)

**Comment by antw** [comment]
The node key and download link need to be added to [config/nodes_download_source.yml](https://github.com/quintel/etmodel/blob/master/config/nodes_download_source.yml).
