### ISSUE TITLE
Inconsistent display of transport specifications should be structured

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3553]
The transport section of etmodel is inconsistent in its display of technical and financial properties, especially compared to other parts of the model. A detailed description of this inconsistency is given below. 

For example the slider descriptions for car technologies are linked to Github:
<img width="460" alt="Screenshot 2021-01-20 at 10 49 08" src="https://user-images.githubusercontent.com/67338510/105157308-22b63100-5b0d-11eb-9167-653232a97a2a.png">

At the same time, the slider descriptions for train technologies do have technical and financial properties, but only have a download .xls button and no further attributes:

<img width="460" alt="Screenshot 2021-01-20 at 10 51 58" src="https://user-images.githubusercontent.com/67338510/105157690-86d8f500-5b0d-11eb-81c6-cc57ac559dc0.png">

Compare this to the following complete overview, which is more commonly applied throughout the model:

<img width="460" alt="Screenshot 2021-01-20 at 10 52 46" src="https://user-images.githubusercontent.com/67338510/105157816-a40dc380-5b0d-11eb-8bcd-d22669849942.png">

I propose to structure the technical and financial properties for the transport sliders in such a way that it matches the final overview shown above. In that way it will be consistent with the rest of the model. What do you think @marliekeverweij?

**Comment by marliekeverweij** [comment]
Great idea! It would be a great improvement if we would also show those specs
