### ISSUE TITLE
Order of sections in node properties table should be updated

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3569]
At the moment the Other section is on top, but it would be a nice improvement when we would have the following fixed order:
- Technical
- Costs
- Other

![Screenshot 2021-01-26 at 13 33 09](https://user-images.githubusercontent.com/32833996/105845583-4bda3400-5fdb-11eb-8321-5e1784b88945.png)

**Comment by antw** [comment]
Sorry. [I fixed this yesterday](https://github.com/quintel/etmodel/commit/cda3d1ee9464f3935e0cd6c92f889e82dc55d366) then [immediately broke it again](https://github.com/quintel/etmodel/commit/597dc71bddeaa632c44402876157436cbf7d17df).
