### ISSUE TITLE
Price from scenario feature no longer shown on interconnector upload form

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3571]
BETA:
![Interconnector 2 - Import and export of electricity - Energy Transition Model - beta-pro energytransitionmodel com 2021-01-26 15-49-58](https://user-images.githubusercontent.com/32056448/105860856-52be7200-5fee-11eb-8ead-ce8d1352c2c3.png)

PRO:
![Interconnector 2 - Import and export of electricity - Energy Transition Model - pro energytransitionmodel com 2021-01-26 15-50-17](https://user-images.githubusercontent.com/32056448/105860843-4f2aeb00-5fee-11eb-807f-0ab481ffcdd3.png)

**Comment by antw** [comment]
Are you signed in?

![Screenshot 2021-01-26 at 16 32 11](https://user-images.githubusercontent.com/4383/105874071-17bf3d00-5ff4-11eb-8ace-cafe7b0b6b02.png)

It is only an option when using the "Interconnector" slides, and not the new curve upload feature, but expect that can be changed.

**Comment by michieldenhaan** [comment]
Yes I am logged in. Here's the steps to reproduce:

1. Start new scenario -> Go to import/export slide -> the select scenario form is visible
2. Go to curve upload slide -> Upload a curve for a random category, e.g. buildings heating
3. Now go back to import/export slide -> the select scenario form has disappeared
