### ISSUE TITLE
Featured scenarios should not "loose" their electricity price curve

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3577]
I checked two featured scenarios (II3050 Regional & International) and both scenarios do not have an electricity price curve for interconnector 1 on BETA anymore. I guess that this is not intentional

![Screenshot 2021-01-28 at 15 03 56](https://user-images.githubusercontent.com/32833996/106149111-28012480-617a-11eb-8e8d-8decd527d691.png)

**Comment by antw** [comment]
Fortunately we've got pretty good tests and curves *are* copied when cloning a scenario.

Turns out when I created these scenarios on beta I missed the custom curves and didn't upload them. I've rectified this and attached the curve to all four scenarios.
