### ISSUE TITLE
Do we want to have text underneath the chart in the PNG download?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3579]
I think it would be an nice improvement if the scenario title was added to the PNG download. Maybe below the chart:
_Scenario: ......
Created with the Energy Transition Model
energytransitionmodel.com_

Also, we could add the scenario id/name to name of the PNG (next to the chart name)

![Imbalance ( residual load ) per month](https://user-images.githubusercontent.com/32833996/106151769-fd649b00-617c-11eb-8c1f-f356c5658409.png)

**Comment by ChaelKruip** [comment]
To be honest, I think I would rather have no text on the PNG image. If I would want to include it in a report (and I think this is the use-case we are considering) I don't want any watermarks or other unnecessary clutter.

**Comment by marliekeverweij** [comment]
Good point, I agree! Then I think it's a good idea to add the scenario id or name to the PNG name, so we can tell which PNG download belongs to which scenario :)

**Comment by antw** [comment]
@marliekeverweij The scenario title is already shown when you've opened one of your own saved scenarios:

![Total supply and demand per month](https://user-images.githubusercontent.com/4383/106156070-02275000-6179-11eb-866a-ce7e5dc9c0d3.png)

@ChaelKruip's point is pretty fair though. I imagined the texts being useful for when people wanted to download an image and share it with others: in that case the title is important for context, and crediting the ETM is tiny (but nice) PR boost. I can definitely see how these texts would *not* be useful if you want to place the image straight into a report.

We could always turn the download button into a dropdown and give the visitor the choice between text and no text, but if 95% of people want the image with no text then that would be a wasted effort. Any thoughts?

**Comment by marliekeverweij** [comment]
> The scenario title is already shown when you've opened one of your own saved scenarios:

Great!

I actually think that's 95% of the people do not want to have the text underneath their chart, so giving them the choice is only making it more complex I would say.

**Comment by ChaelKruip** [comment]
> I actually think that's 95% of the people do not want to have the text underneath their chart, so giving them the choice is only making it more complex I would say.

My feeling as well. I would even remove the "Scenario created with the .... " text underneath from the current PNG.
