### ISSUE TITLE
Show n. a. for blackout hours in dashboard when merit is off

### ISSUE THREAD

**Issue by noracato** [quintel/etmodel#3593]
When merit is off, blackout hours can not be calculated properly, see #2858. Instead of adjusting our calcultions, we can also choose to make this a merit-only feature. To further attend users to the unavailability of some features when merit is off, we can _grey out_ or show 'n. a.' (not avaliable) at the blackout hours dashboard item.

For instance:

_Plain n.a._
<img width="384" alt="Screenshot 2021-02-02 at 16 35 18" src="https://user-images.githubusercontent.com/14875123/106623543-04245100-6575-11eb-8e6f-d8d0b91a7890.png">

_Greyed out n.a._
<img width="384" alt="Screenshot 2021-02-02 at 16 37 10" src="https://user-images.githubusercontent.com/14875123/106623548-05ee1480-6575-11eb-9505-3b5124563d4f.png">

**Comment by ChaelKruip** [comment]
I like the greyed out version!
