### ISSUE TITLE
Add 'merit was off' disclaimer to the scenario report

### ISSUE THREAD

**Issue by noracato** [quintel/etmodel#3594]
We discussed adding a disclaimer to the scenario report (and possibly other downloads as well) when merit is off. This disclaimer would include which things were not taken into account in the results, and which results might not be useful anymore because of that.

@ChaelKruip, @AlexanderWirtz I can set up support for this disclaimer, can one of you provide the contents?

**Comment by ChaelKruip** [comment]
> @ChaelKruip, @AlexanderWirtz I can set up support for this disclaimer, can one of you provide the contents?

Yes!
