### ISSUE TITLE
Grey out sections or slides that depend on merit, like we do with charts

### ISSUE THREAD

**Issue by noracato** [quintel/etmodel#3595]
Another idea of communicating the disadvantages of turning merit off, is to show users what features have become unavailable to them. Like we show a message on the charts when merit is turned of, we can also do this for slides, sliders or even whole sidebar items. 

Items would include most items in the flexibility section.

We could:

### 1. Just disable inputs on the affected slides

I imagine something like we do to the sliders in the Weather section, but maybe an extra explanation in the tooltip:

<img width="467" alt="Screenshot 2021-02-02 at 17 22 13" src="https://user-images.githubusercontent.com/14875123/106629671-5bc5bb00-657b-11eb-8469-5312dba03974.png">

### 2. Disable slides
Make some slides impossible to open, something like this:

<img width="467" alt="Screenshot 2021-02-02 at 17 32 59" src="https://user-images.githubusercontent.com/14875123/106631120-bad7ff80-657c-11eb-8492-b5f9f8a935aa.png">

### 3. Disable sidebar items
We could also add a disabled tag here to disable opening a sidebar item:

<img width="214" alt="Screenshot 2021-02-02 at 17 35 32" src="https://user-images.githubusercontent.com/14875123/106631448-13a79800-657d-11eb-9678-1d079f12cf4a.png">

What do you think, and which interface items would be contenders for being disabled?

**Comment by ChaelKruip** [comment]
> What do you think?

I like the idea of disabling complete slides and sidebar items. I feel we should inform the user about WHY this has happened though. Perhaps we can also add a "?" to the "disabled" notification?

>  Which interface items would be contenders for being disabled?

**Sliders**
* Power-to-heat boiler for gas and H2 heaters (Demand > Industry > Refineries)
* Power-to-heat boiler for gas and H2 heaters (Demand > Industry > Chemicals)
* Power-to-heat boiler for gas and H2 heaters (Demand > Industry > Food)
* Power-to-heat boiler for gas and H2 heaters (Demand > Industry > Paper)
* Seasonal storage (Costs > Heat)
* 

**Slides**
* ![image](https://user-images.githubusercontent.com/1303760/106749513-e57e9280-6626-11eb-8546-63c74a51a371.png)
I think the whole district heating relies on time-resolved calculations. @michieldenhaan @antw do we have fall-back options for dispatchable heat sources for district heating if time-resolved calculations are being turned off? (Supply > District heating > ...)
* (Seasonal) storage of heat (Supply > District heating > Storage)
* Flexibility (Costs)
* CCUS (Costs)? @michieldenhaan please advise

**Sidebar items**
* Carbon capture, utilisation and storage? @michieldenhaan please weigh in...
* Excess Electricity (Flexibility)
* Net load (Flexibility)
* Import/Export (Flexibility)
* Weather conditions (Flexibility)
* Security of supply (Flexibility)
* Modify profiles (Flexibility)
* Merit Order (Costs)

**Tabs**
* Flexibility as a whole should be disabled I think!

This is not an exhaustive list I think but it gives a first idea of the extent of time-resolved dependency.
