### ISSUE TITLE
Initial investment in technical specs table should not include CCS investment

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3602]
The initial investment in the technical specs table currently also includes CCS investment costs.
The table uses `total_investment_over_lifetime` which consists of `total_initial_investment + decommissioning_costs`. However, `total_initial_investment` includes `initial_investment + ccs_investment + cost_of_installing + storage_costs`.

This is my 100% bad as I suggested using `total_investment_over_lifetime`. What we want (I think) is to show `initial_investment` + `cost_of_installing` + `decommissioning_costs` as 'initial investment', since we already show `ccs_investment` separately in the table:

![image](https://user-images.githubusercontent.com/32056448/106915782-b7707f80-6706-11eb-83ba-f66c9a7a0dc7.png)

**Comment by marliekeverweij** [comment]
https://github.com/quintel/etengine/commit/1fc161ba5f06657376caec2de362b0e7bc60046d
