### ISSUE TITLE
Price curve upload and modify profiles not loading on PRO

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3603]
Interconnector 1:
![image](https://user-images.githubusercontent.com/32056448/107026213-aed18500-67aa-11eb-81a1-1226f0da8c1a.png)

Interconnector 2:
![image](https://user-images.githubusercontent.com/32056448/107026334-d6285200-67aa-11eb-8f0c-611775ed3355.png)

Modify profiles:
![image](https://user-images.githubusercontent.com/32056448/107026373-e6403180-67aa-11eb-8fdf-66a6596ffc4d.png)

**Comment by antw** [comment]
I'm struggling to reproduce this. It's hopefully related to #3604, but in that issue I didn't get any "Loading..." message for the curve upload.

* Is there a JavaScript error in the browser console?
* Does this occur every time you view these pages, or just intermittently?
* Does it occur only when you load the pages directly, when  you start on another slide and move to these slides, or both?
* Are you signed in?
* Could you link the scenario, if you still have it open?
* Is it specific to one scenario, or does it still occur when starting a new scenario?

**Comment by michieldenhaan** [comment]
I got a report from a client with the same issue. My console showed the following JS error (see screenshot). But I have difficulties reproducing it myself now as well. Asked around and it seems to work fine for multiple people now. Maybe a caching thing?

![image](https://user-images.githubusercontent.com/32056448/107037778-daa93680-67bb-11eb-99e2-2d32c0e29079.png)

**Comment by antw** [comment]
Perfect, thanks. That *is* the same issue as #3604 after all, which should now be fixed.

I'm confused why you see a "Loading..." message when I see nothing; I'm going to continue to investigate a little longer just to satisfy my own curiosity, but I'm fairly confident that error is fixed.

I'll close this, but please reopen it if you get any further reports.
