### ISSUE TITLE
Electricity interconnectors slide not loading on BETA

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3604]
![image](https://user-images.githubusercontent.com/32056448/107026531-1e477480-67ab-11eb-8ed6-b6dd75b6afd3.png)

~~On PRO it does seem to work~~ Nvm, happens on PRO as well, but not all the time?

**Comment by antw** [comment]
I've pushed a fix; I think it occurs only when not signed in. Can you confirm that it now works as expected for you?

**Comment by michieldenhaan** [comment]
I think so, thanks!
