### ISSUE TITLE
Biomass plants slide is outdated

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3611]
The biomass plants slide in the renewable electricity section is outdated:
![image](https://user-images.githubusercontent.com/32056448/107787181-0c3b7800-6d4f-11eb-8ec9-160de613bd62.png)

I think the slide should explain:

- That this is about both electricity production and heat production
- That you set the installed _electrical_ capacity of plants
- That the heat from these CHPs is supplied to the district heating network
- The slider '?' should also make clear that you set electrical capacity.

**Comment by marliekeverweij** [comment]
Adding this to the March deploy milestone. Do you have time to take care of this @Charlottevm ?

**Comment by Charlottevm** [comment]
Yes! I can pick this up this week!
