### ISSUE TITLE
Add a short survey

### ISSUE THREAD

**Issue by antw** [quintel/etmodel#3612]
As part of the UX improvement project, we'd like to add a short, *optional* survey which ETM visitors may fill out. There are four or five questions we'd like to ask in order to get a better idea of who uses the ETM, and for what purpose.

The proposal is for a small pop-up to appear in the lower-right of the screen asking the first question. Perhaps something like "Please rate your experience with energy transition" on a scale of 1-5:

![IMG_36266FB528ED-1](https://user-images.githubusercontent.com/4383/108064244-4ad57900-7054-11eb-9fba-3dcf4839d4d9.jpeg)

* If the visitor answers the question, we store the response in the database and show the next question.
* At any time, they can close the pop-up and not be bothered by it again.

The exact inputs for the survey are not yet known and will depend on the questions created by @Charlottevm. It's likely some will be "choose a value", for example, from 1 to 5, while others may be multiple choice. I think we should shy away from text inputs since I suspect (albeit without evidence) that people are less willing to answer these.

The admin section should have a way of viewing the responses, or perhaps just the ability to export them all as a CSV.

@ChaelKruip I'd like to propose this for the next dev sprint. It will hopefully take only a couple of days, and we might be able to sneak it in before the feature freeze.

**Comment by ChaelKruip** [comment]
> @ChaelKruip I'd like to propose this for the next dev sprint. It will hopefully take only a couple of days, and we might be able to sneak it in before the feature freeze.

Fine by me!
