### ISSUE TITLE
Add flex technology installed capacities chart to front-end including slide and text

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3617]
![108211692-4c26a480-712d-11eb-99e5-c974cec17233](https://user-images.githubusercontent.com/32833996/108212967-cefc2f00-712e-11eb-9778-1002c0dfa440.png)

This chart shows the flexibility need in capacities as lines: these are the yearly minimum and maximum values of the residual load curves. Additionally, this chart shows how much capacity of flex technologies is installed. This comparison allows users to receive feedback on whether they have sufficient capacity for their surpluses and shortages. 

We need to find a good location for this chart in the front-end!

@mabijkerk and I discussed two options:
1. We could add it underneath the "The need for flexibility: capacity"-slide: 
![Screenshot 2021-02-17 at 14 48 52](https://user-images.githubusercontent.com/32833996/108213490-61043780-712f-11eb-94af-717cc3140a05.png)
2. We could divide the "Flexibility -> Overview" section into two separate sections, just like the "Excess electricity" section. Then we could place the first four charts underneath "Need for flexibility" and this chart underneath "Deployment of flexiblity".
![Screenshot 2021-02-17 at 14 50 46](https://user-images.githubusercontent.com/32833996/108213614-86914100-712f-11eb-8fb8-728fdc707380.png)

What would you prefer @ChaelKruip @antw @michieldenhaan @AlexanderWirtz and other @quintel/core ?

**Comment by AlexanderWirtz** [comment]
I think this is option 1: add this chart in a 'Installed flexibility capacities' slide.

**Comment by marliekeverweij** [comment]
Are there more opinions about the location of this new chart or is this it? Please share them here :)
