### ISSUE TITLE
Hydrogen production sliders should clearly state whether they affect input or output capacity

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3619]
The sliders for hydrogen production technologies currently do not clearly show whether they set the installed hydrogen output capacity or the input capacity of the energy source used to produce the hydrogen. This can lead to confusion about what the actual **hydrogen** production capacity in a certain scenario is (see for example issue #3618).

For other technologies it is clearly stated which type of capacity is meant, for example:
<img width="300" alt="Screenshot 2021-02-18 at 10 46 58" src="https://user-images.githubusercontent.com/67338510/108338515-a29bed80-71d6-11eb-8114-7dbb921c5a00.png">  <img width="300" alt="Screenshot 2021-02-18 at 10 47 34" src="https://user-images.githubusercontent.com/67338510/108338589-b8111780-71d6-11eb-8f86-ac5330a94725.png">

For hydrogen this is currently not the case, for example:
<img width="300" alt="Screenshot 2021-02-18 at 10 49 43" src="https://user-images.githubusercontent.com/67338510/108338864-04f4ee00-71d7-11eb-8c36-c30d0d7c1e9e.png"> <img width="300" alt="Screenshot 2021-02-18 at 10 50 01" src="https://user-images.githubusercontent.com/67338510/108338908-10481980-71d7-11eb-9d81-959c1dd22d5b.png">

I propose to add a similar pointer for the hydrogen sliders to indicate whether input or output capacity is meant.

A quick scan through the model shows me that this is not consistently applied for other technologies either. For example, biomass plants also do not show whether input or output capacity is meant. In some cases it could be considered evident whether input or output capacity is meant. @michieldenhaan do you think these pointers should be added for other technologies as well?

**Comment by michieldenhaan** [comment]
Yes! Preferably every MW slider should indicate whether it is input or output capacity.

**Comment by marliekeverweij** [comment]
Adding this to the March Deploy milestone. Do you have time to take care of this @mabijkerk ?
