### ISSUE TITLE
Rake task to fetch download node source analyses does not seem to be working

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3620]
The "Download source data" button is missing in ETModel for a number of input sliders that do have "Technical and financial properties" and a corresponding node source analysis in ETDataset.

Some examples are:

- `energy_heat_solar_thermal`
- `energy_heat_burner_wood_pellets`
- `energy_heat_burner_hydrogen`

Because I do not know the complete set of missing node source analyses links, I tried to use the rake task that should add the missing links automatically. However, when I use `rake fetch_nodes_download_source` in etmodel, nothing seems to change. Is this an issue related to the rake file itself, and if so, can it be fixed?

**Comment by marliekeverweij** [comment]
Good point! I think this is the same as this issue, right @noracato? https://github.com/quintel/etmodel/issues/3552
Would be nice if this would be picked up before the March deploy!

**Comment by mabijkerk** [comment]
I did not check whether an issue already existed, #3552 is indeed about the same thing. Thanks checking @marliekeverweij.
