### ISSUE TITLE
Group sub headers should be changeable for each group

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3622]
It is currently possible to specify both a general sub header and a group sub header. See for example the slide`Passenger transport - Applications`, where both the "%/year" growth and the "share" of each transport mode is shown:
<img width="469" alt="Screenshot 2021-02-19 at 11 02 25" src="https://user-images.githubusercontent.com/67338510/108489541-f58ea700-72a1-11eb-806f-dbc963b0c9d9.png">

For some slides it is desirable to specify a different sub header for each group. See for example the slide `Excess electricity - Storage`, where the first group `Low voltage network` should show "share", but the other two groups should show "electricity input".
<img width="460" alt="Screenshot 2021-02-19 at 11 05 17" src="https://user-images.githubusercontent.com/67338510/108489858-5c13c500-72a2-11eb-806f-f92c62c97da0.png">

Currently it does not seem possible to specify different sub headers for each group, is this something that can be added @antw? Another example of where this is an issue is the slide `District heating - Heat sources`, where all the sliders are referred to as "heat output" even though some quite clearly set a share.

**Comment by antw** [comment]
This is possible, but I admit it's really not obvious how to do it.

The slide needs to have a `group_sub_header` attribute. Doing this for the storage slide (and removing `general_sub_header`) looks like so:

![Screenshot 2021-02-19 at 14 39 52](https://user-images.githubusercontent.com/4383/108518365-5f1dae00-72c0-11eb-84c3-e27051907bcf.png)

The sub-headers currently don't look so good when the text is more than one word, as in this case. You may then customise the labels for each group [by adding translations to the "subheaders" collection](https://github.com/quintel/etmodel/blob/7d12ed30bc05e62f67517cba5ec29d784b99ca59/config/locales/en_etm.yml#L140-L162). These should match the `interface_group` of the sliders.

For example, [the interface groups of the storage sliders are "lv_network", "mv_network", and "hv_network"](https://github.com/quintel/etmodel/blob/7d12ed30bc05e62f67517cba5ec29d784b99ca59/config/interface/input_elements/flexibility_flexibility_power_storage.yml). Adding translations for those sub-headers...

```yaml
lv_network: "share"
mv_network: "capacity"
hv_network: "capacity"
```

... results in:

![Screenshot 2021-02-19 at 14 37 57](https://user-images.githubusercontent.com/4383/108518764-d9e6c900-72c0-11eb-85d1-fd4ffcd341a2.png)

**Comment by mabijkerk** [comment]
> These should match the `interface_group` of the sliders.
The way I understand it now, is that the interface_group 'overrules' the subheader group, is that correct? In this case it no longer matters what input is given to the `group_sub_header` because the translations for the interface_group will be used.

**Comment by antw** [comment]
> The way I understand it now, is that the interface_group 'overrules' the subheader group, is that correct?

Exactly. It first looks for a translation matching the `interface_group`, and if none was found it falls back to the translation for `group_sub_header`.
