### ISSUE TITLE
Unused heat in industry should be included in CO2 / primary demand calculation

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3627]
`industry_unused_local_production_steam_hot_water` is not in the `final_demand_group` nor in the `co2_emissions_primary` group. As a result, the primary energy used and CO2 emitted to produce this heat are not included in the primary demand calculation and the co2 calculation.

For residential heat networks, we decided to add `energy_heat_dumped_steam_hot_water` to the final demand group (of the energy sector) to avoid this problem.

@AlexanderWirtz @ChaelKruip @marliekeverweij  shall we do the same for `industry_unused_local_production_steam_hot_water`? 

If so, we probably also have to add another category ('unused heat'?) to this chart?
![image](https://user-images.githubusercontent.com/32056448/108744711-8c759080-753a-11eb-99ab-f5ee1ffb719f.png)

And this one:
![image](https://user-images.githubusercontent.com/32056448/108876753-d88a0900-75fe-11eb-8656-d2706722b0c0.png)

**Comment by ChaelKruip** [comment]
> @AlexanderWirtz @ChaelKruip @marliekeverweij shall we do the same for industry_unused_local_production_steam_hot_water?

I am in favour of this and the resulting addition of a category to the Mekko!

**Comment by marliekeverweij** [comment]
Me too!

**Comment by AlexanderWirtz** [comment]
me three
