### ISSUE TITLE
Scenario report: axis unit of chart does not fully load for some charts

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3640]
Dutch regional report:
<img width="763" alt="Screenshot 2021-02-22 at 17 20 01" src="https://user-images.githubusercontent.com/32833996/109020794-932b1180-76ba-11eb-9af5-2ad1bbec5bb7.png">

**Comment by noracato** [comment]
I cannot reproduce this in a regional scenario report on either Chrome, Firefox or Safari.

**Comment by noracato** [comment]
It seems to happen with all units of over 100! I'll go check!

**Comment by noracato** [comment]
We could do two things here:

1. Make the legend font smaller in the report:
<img width="772" alt="Screenshot 2021-02-24 at 16 46 54" src="https://user-images.githubusercontent.com/14875123/109027011-a4771c80-76c0-11eb-82c1-988c6da2dbd5.png">

2. Alter the chart code to leave more room for the legend:
<img width="754" alt="Screenshot 2021-02-24 at 16 49 47" src="https://user-images.githubusercontent.com/14875123/109027048-accf5780-76c0-11eb-8cb4-fe7db51057be.png">

**Comment by marliekeverweij** [comment]
I am in favour of option 1 :)

**Comment by antw** [comment]
Option 2 for me. The font size used for the report charts is already smaller than that used for the report text. I think making it smaller still is too much.

It's unfortunate that we hard-code the size of these axes, rather than figuring out how much space they need when the chart (re-)renders. Something to keep in mind for the refresh.

**Comment by marliekeverweij** [comment]
> Option 2 for me. The font size used for the report charts is already smaller than that used for the report text. I think making it smaller still is too much.

Also fine for me! Could you make this happen @noracato ? :)
