### ISSUE TITLE
Opening a chart from the dashboard should not make the chart unavailable in the chart menu

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3642]
When a chart is opened from the dashboard and consequently closed again, the chart is unavailable for selection in the chart menu.

For example when I click on the dashboard item "Renewables" the chart "Renewability of final demand" opens. When I then close the chart and go to "See more charts" or to the "Change chart" button in the chart that is already on display in the front-end, "Renewability of final demand" is unavailable for selection.

<img width="700" alt="Screenshot 2021-02-25 at 15 02 40" src="https://user-images.githubusercontent.com/67338510/109164274-840b9880-777a-11eb-842c-af2fa89b36da.png">

I suppose that once you close a chart from the dashboard, is still 'open' somewhere in the background. Can this be fixed?

**Comment by marliekeverweij** [comment]
@antw I think it is important to pick this issue up before tomorrow's deploy. Is that possible

**Comment by antw** [comment]
I'll see what can be done.
