### ISSUE TITLE
Users should be able to select the dpi for the png of the chart download 

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3643]
As far as I can tell, the dpi for png files of charts downloaded from the model is currently automatically set at 72.
See the screenshot for a sample chart below:

<img width="400" alt="Screenshot 2021-02-25 at 15 28 00" src="https://user-images.githubusercontent.com/67338510/109167489-182b2f00-777e-11eb-9dd7-6c406565f970.png">

In some cases it might be preferable to have a higher dpi, mainly when physically printing charts.
For printing an _effective_ dpi of 300 is usually preferred. Though the _effective_ dpi on the page of course also depends on the original image size and the size on the page, a standard dpi of 72 still seems a bit low.

One solution is to increase our standard dpi, but the downside of this solution is that this means that all the downloaded charts will have larger file size. Another solution is to open add a pop-up window that allows the user to choose the dpi when "Save chart as an image is clicked". Finally, if we don't think that our user will need higher resolution downloads (for example because we think that our charts will only be used online), then we don't have to do anything.

What do you think @marliekeverweij and @redekok?

**Comment by marliekeverweij** [comment]
I have no strong opinion on this :) I think the most frequent use case for chart downloads is for a report or PowerPoint presentation (and not printing) and I am not sure what dpi is required for that

**Comment by redekok** [comment]
I would be in favour of having the possibility to download 300 dpi charts. I agree that 72 dpi is a bit low, especially when these charts are used for high-resolution slides or reports (presented on a large screen).

**Comment by antw** [comment]
72 comes from the standard DPI of a monitor, and [html2canvas does not support custom DPI settings](https://github.com/niklasvh/html2canvas/pull/1087#issuecomment-349580211). I think all we can do is set a larger _scale_, increasing the dimensions of the image, but not the DPI.

**Comment by rwieruch** [comment]
https://github.com/shutterstock/changeDPI worked for me.

**Comment by eventx-zack** [comment]
> https://github.com/shutterstock/changeDPI worked for me.

hello! i am facing the similar issue, could u pls attach demo code to show how to use the lib u mentioned? thanks!
