### ISSUE TITLE
CO2 footprint present & future: specific sector should be shown when hovering over

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3659]
The CO2 footprint lives on two locations:

1. When clicking ['Show region CO2 footprint'](https://pro.energytransitionmodel.com/regions/nl) on the landing page
2. In the [Results section](https://pro.energytransitionmodel.com/scenario/data/data_visuals/co2-footprint)

I just noticed that on the 2nd CO2 footprint the hover over functionality does not work in a very specific case 🤓: when the non-energetic GHG are hidden (I did not even know this was a possibility until today!)
![Screenshot 2021-03-12 at 15 03 40](https://user-images.githubusercontent.com/32833996/110950440-23688800-8344-11eb-93fe-33cbdc28bfc8.png)

**Comment by michieldenhaan** [comment]
> when the non-energetic GHG are hidden

This option has been removed
