### ISSUE TITLE
Electricity price rises when installing large amounts of wind / solar capacity

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3664]
As client pointed out that when installing large amounts of wind / solar, that the electricity price rises. This is not the expected behavior: you would expect that there will be more hours with 0 euro / MWh electricity price resulting in a drop in the electricity price. See screenshots below:
[**100 GW offshore: E-price is on average ~€33/MWh**](https://beta-pro.energytransitionmodel.com/saved_scenarios/4834) (start year: 29.5 EUR/MWh)
![image(14)](https://user-images.githubusercontent.com/32833996/111310394-4f924a80-865d-11eb-936a-a512df478671.png)
![image(13)](https://user-images.githubusercontent.com/32833996/111310309-3d181100-865d-11eb-9116-e6e9adfbb579.png)

Characteristics of this scenario:

- no electricity is imported
- large amounts of electricity are exported
- "Use dispatchables for exported electricity?" toggle is OFF

When we switch the toggle to ON, then the electricity price drops to 11 EUR/MWh

@AlexanderWirtz and I have a hypothesis: when the toggle is OFF, could it be that during hours when electricity is exported that the interconnector price (35euro/MWh) sets the electricity price? This should not be the case, only when electricity is imported. 

The reason why we think this is that the electricity price is often 35 EUR/MWh in the scenario above with no electricity import and the gas CCGT being the most expensive plant running (32.68 EUR/MWh).

Would be great if you could have a look into this @antw

**Comment by AlexanderWirtz** [comment]
Since this scenario also curtails _huge_ amounts of offshore wind power, the hours when power is exported are also hours when even more power is curtailed. It would make sense for those hours to have a power price of €0/MWh, instead of €35/MWh, which is the power price of the interconnector.
 This is the scenario: https://beta-pro.energytransitionmodel.com/saved_scenarios/4834

**Comment by antw** [comment]
A fix is enroute to beta.

![Electricity price per hour 1410106 (1)](https://user-images.githubusercontent.com/4383/111318051-9a5f9280-865c-11eb-9614-30feaf5168f2.png)
![Electricity price per hour 1410106 (2)](https://user-images.githubusercontent.com/4383/111318055-9b90bf80-865c-11eb-91c0-a68fba36a86d.png)

> @AlexanderWirtz and I have a hypothesis: when the toggle is OFF, could it be that during hours when electricity is exported that the interconnector price (35euro/MWh) sets the electricity price?

Correct! Merit considered any participant with non-zero load as a candidate for setting the electricity price. Electricity interconnectors when exporting have *negative* load, and could therefore be wrongly used to set the price.

**Comment by marliekeverweij** [comment]
Great @antw !!
