### ISSUE TITLE
Final energy demand for heating in agriculture chart does not correctly update future values display

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3666]
The chart `Final energy demand for agriculture` does not update its future values correctly when you hover above the chart. When I open a blank scenario for the Netherlands for example, the heating demand for district heating is set at 39.5% which results in 41.12 PJ. When I set the slider to 100.0%, the visualised heating demand for district heating increases, but the value for the future year that is displayed when you hover above chart does not:

<img width="500" alt="Screenshot 2021-03-16 at 21 08 50" src="https://user-images.githubusercontent.com/67338510/111373109-d108cd80-869b-11eb-9615-9ee30866fa50.png">

This is the case even though the heating demand for district heating in the corresponding table view increases to 106.5 PJ.
The value for natural gas is not updated either:

<img width="500" alt="Screenshot 2021-03-16 at 21 15 55" src="https://user-images.githubusercontent.com/67338510/111373943-cf8bd500-869c-11eb-89d3-5b0d2a1e11b7.png">

The value for oil is updated, but not correctly since it goes to 14.8 PJ while the value should be 0 PJ:
<img width="500" alt="Screenshot 2021-03-16 at 21 17 08" src="https://user-images.githubusercontent.com/67338510/111374077-f944fc00-869c-11eb-914d-8464f8abb3c2.png">

Finally, the other categories are updated properly to 0 PJ. @michieldenhaan do you have an idea of how this can be fixed?

**Comment by michieldenhaan** [comment]
I think this is a bug with the chart label as the underlying queries seem to be correct. The table view does show the correct numbers. @noracato @antw Do you have time to look into this?
