### ISSUE TITLE
Primary demand of solar thermal and imported heat are missing from primary demand mekko

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3668]
Solar thermal nodes are in the `primary_energy_demand` group but do not show up in the primary demand mekko.
As a result, total primary demand from final demand + export in the graph is higher than shown by the mekko.

Also, imported heat is missing.

Re-assign at will

**Comment by marliekeverweij** [comment]
Good point! I think geothermal & ambient is also missing in the primary demand mekko right? 

Idea: it would be nice to have the same categories in the primary demand mekko and left side of the sankey diagram:
![Screenshot 2021-03-23 at 09 17 25](https://user-images.githubusercontent.com/32833996/112114648-967dc400-8bb8-11eb-9c7f-acc6a29d3072.png)

Question: did we already create a MT test to check if the primary demand in the mekko matches the primary demand in the sankey? I think this would be a nice one. We could also test if the final demand in the sankey (excl. losses and feedstock) matches the final demand in the final demand mekko.

**Comment by michieldenhaan** [comment]
>  I think geothermal & ambient is also missing in the primary demand mekko right?
Geothermal and ambient aren't in the `primary_energy_demand` group

**Comment by marliekeverweij** [comment]
> Geothermal and ambient aren't in the primary_energy_demand group

Alright. Do we want to add them or is this the way it should be?

I am assigning @mabijkerk for this issue. Do you have time for this before the deploy? I could support you when you have questions

**Comment by michieldenhaan** [comment]
>  Do we want to add them or is this the way it should be?

There is a separate issue about this: https://github.com/quintel/etmodel/issues/3641. Definitely a topic to look into some more when time permits but probably not feasible before next deploy.

**Comment by marliekeverweij** [comment]
> There is a separate issue about this: #3641. Definitely a topic to look into some more when time permits but probably not feasible before next deploy.

Thanks for mentioning this issue here. Would be nice to also pick this up. What would be your time estimate for adding geothermal + ambient to the primary energy demand? 1,5 day? We could add it to the milestone of the deploy in May

**Comment by michieldenhaan** [comment]
For the technical work that seems about right. I think the main thing is deciding _whether_ we want to do this. The issue contains a quite lengthy discussion about this (which I haven't read fully).

**Comment by ChaelKruip** [comment]
> I think the main thing is deciding whether we want to do this.

I agree. Who wants to prepare a short meeting to make this decision with a couple of us?

**Comment by mabijkerk** [comment]
I'm picking up this issue and will look into #3641 after closing this one. If necessary I will prepare a meeting.
