### ISSUE TITLE
The option to download slider settings as a CSV file should be removed

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#3670]
I think we made a mistake in adding this feature in the first place. Although I understand the wish of our clients to see all slider settings in table form, this feature suggests a work-flow that I think we should not encourage.

Having the option to download slider settings in CSV format steers the user into a direction where they would like to change one or two values in this CSV and *upload* it into the ETM in order to create a new scenario or change the current scenario.

As mentioned by @antw in the past, we should be cautious supporting a CSV upload for slider settings:
1. Maintenance: We already have a GUI (ETModel) and the API. Adding a third interface implies that we need to maintain
2. Errors, tests, support: if people are going to use this frequently, we need to make sure that they get proper feedback when an error occurs (e.g., misspelling a key, using an illegal value etc.)
3. Balancing: we should make sure that groups still balance

It is my feeling that the kind of power user that needs to make many scenario's would be better off using the API and we should focus our efforts on making that experience as streamlined as possible. 

Unless any objections from @quintel/core I would like to remove this feature.

**Comment by michieldenhaan** [comment]
I would prefer to keep it actually. Two use cases I know some of our clients use it for:

- For scenario documentation. Some users download the CSV and import it into Excel to write up a scenario documentation per slider. The CSV provides a nice overview of all slider settings per section in the model.
- To find the ETM input keys behind each slider. If you want to set a slider via the API, you need to know its key. This information is not very easy to find atm (unless you are an admin or tech-savvy person). I.e. you have navigate through the interface files on ETModel Github to find these keys, which are spread across multiple files and also contain a lot of info/attributes most users are not directly interested in. The CSV provides a clear and complete overview of the slider key, units and corresponding section/slide in the front-end.

I agree that we shouldn't _extend_ the current feature to also allow uploading but afaik we don't have satisfactory alternatives for the above use cases.

**Comment by noracato** [comment]
You make good points, but I think we can solve them in another way than have a hidden .csv download we're hesitant to develop any further. For instance:

> To find the ETM input keys behind each slider. 

To me this sounds like something we should add to our (API) documentation. A nice table of which interface-sliders map to which keys.

> Some users download the CSV [..] to write up a scenario documentation 

IMO we can also help users with documenting their choices in an other way. For example by allowing them to write small comments under sliders in the ETM interface. Could be something to think about for the front-end refresh.

**Comment by redekok** [comment]
> To me this sounds like something we should add to our (API) documentation. A nice table of which interface-sliders map to which keys.

Out of scope, but let's also add a list of "most relevant" gqueries to the API documentation!

**Comment by redekok** [comment]
Another question: is there a way to get input values using the API? If not, that would also be a reason to keep this option (for me, at least).

**Comment by ChaelKruip** [comment]
I like the discussion and many of the points raised above! So, perhaps we should not remove this option but improve it and clearly state its purpose to the user. 

@noracato can you create sub-issues for the ideas and tasks as you see fit? I'll close this one now.
