### ISSUE TITLE
The introductory paragraph about industrial heat network sources seems to state misleading modelling assumptions

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3677]
The introductory paragraph about heat sources for the industrial heat networks states that in case of a deficit, large-scale heat and residual heat sources can be used to deliver the heat. This doesn't seem to be the case though. It seems as if a backup gas heater is always used for deficits. @michieldenhaan is this indeed the case? If so, we should update the paragraph I think?

![image](https://user-images.githubusercontent.com/5946498/113168863-561be700-9245-11eb-905f-45e6cbc7af8a.png)

**Comment by michieldenhaan** [comment]
Yes this is super old. All heat sources that can supply to industrial heat networks are listed on the slide. If the installed capacity does not suffice, a gas back-up switches on automatically.

@Charlottevm Do you have time to fix this?

**Comment by Charlottevm** [comment]
Will do next week if that is ok :)

**Comment by marliekeverweij** [comment]
If possible, I would prefer to have fixed it this week as the improvement can then be deployed next week :) Let me know. If not, we can find somebody else
