### ISSUE TITLE
Add link to ETM Dataset Manager to front-end including text

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3681]
We want to create a direct link / button from a dataset in the ETM to a dataset in the ETM Dataset Manager. This way users can check out the source data of that specific dataset. In https://github.com/quintel/etmodel/issues/3680 the data-specific link is created. This issue is about the location of the link in the ETM and the text supporting it.

**Location**
@noracato and I propose to add the link as a new sidebar-item underneath the 'Overview'-tab in the ETM. This would look something like this:

![Link ETM to ETM Database Regions](https://user-images.githubusercontent.com/32833996/113398699-4f08ec00-939f-11eb-8bf9-48415e621c0e.png)

What do you think of this location @quintel/core ? Let us know when you have other ideas.

**Country datasets**
Something we have to think of is what you see here when you have opened a country dataset. Country datasets are not yet included in the ETM Dataset Manager, so not button should be shown then. There are a few options:

1. Only show this 'Source data' sidebar item for datasets on the ETM Dataset Manager
2. Always show the 'Source data' sidebar item and write a general story for country datasets about the generation process of country datasets (Energy Balances, etc)
3. Always show the 'Source data' sidebar item, write a general story for country datasets and link the users to the source analyses on GitHub (this is an Excel jungle though!)

I prefer option 2. If you have an opinion about this, let us know!

**Comment by mabijkerk** [comment]
I think that adding it to the "Overview" tab would not fit entirely within the current process that a user goes through when opening the model. The users start with the Introduction to the model, which invites them to balance Supply and Demand. To then add this relatively advanced feature (in my opinion) to the "Overview" tab, seems to disrupt the user experience.

Currently most of our data is located at Results > Data export, so perhaps that would be a better location for the link to the Dataset manager?

**Comment by MartLubben** [comment]
I do think that showing source data fits the best at overview. Before someone starts they would like to see where the data comes from. It is input data and not result data, thus I would not show it at the end. 

I prefer option 2, although I do have a remark. A general story (very short) about the main data sources voor countries and regions would be very helpful. The ETM Dataset Manager probably shows a of detail, but not the simple overall story:

**Data sources:**
- Countries: Energy balance (IEA)
- Dutch regions: Klimaatmonitor, Emissieregistratie and CBS.
- Belgian regions: Burgemeestersconvenant, VITO

Also for the Dutch regions we have a word document describing the dataset process. It would be nice to have a link to this document too.

**Comment by noracato** [comment]
> Currently most of our data is located at Results > Data export

True, but this is mostly data that is unique to your scenario; the results. In my opinion viewing the source data is not part of a result, it's what you are starting with. So for me it would not fit under that tab (or we would have to change the name).

Maybe we could name this new sidebar item 'Backgrounds' / 'Achtergronden' instead of 'Source Data' and also include a slide and link to our documentation there? Then it might become something like: if you want to learn more and go deeper, check this out.

**Comment by antw** [comment]
I'm opposed to adding it under "Overview" and also believe it belongs in the "Results" section. I think we should rename "Results" to "Results and data".

@mabijkerk has already covered my reasoning for disliking adding it to "Overview". Users – especially new users – will view the intro, then proceed to the next page. The next page should be something which will capture their attention and introduce the features of the model, *not* send them off-site.

**Comment by AlexanderWirtz** [comment]
I agree with @mabijkerk and @antw

**Comment by ChaelKruip** [comment]
> I agree with @mabijkerk and @antw

Me too

**Comment by marliekeverweij** [comment]
Thanks for all your input! 

@mabijkerk & @antw you have convinced me. I think it's indeed better to included it in the "Results & data" section. I do think it's important to create a link from the "Introduction" section to the source data section, so users can find it.
