### ISSUE TITLE
Concentrated solar power should be included in hourly production of solar PV chart

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3682]
The chart "Hourly production of solar PV" offers the selection between Solar PV (stacked), Buildings, Households and Solar PV plants:

<img width="550" alt="Screenshot 2021-04-02 at 10 50 51" src="https://user-images.githubusercontent.com/67338510/113399922-4ca79180-93a1-11eb-92e8-8bc8fd5a8503.png">

I would expect that concentrated solar power plants are included in the "Solar PV plants" category. The underlying query `energy_power_solar_pv_electricity_output_curve` however shows that this is not the case:

<img width="550" alt="Screenshot 2021-04-02 at 10 53 59" src="https://user-images.githubusercontent.com/67338510/113400211-bb84ea80-93a1-11eb-9086-545d3785ed37.png">

I think that concentrated solar power should be included in this chart, either as part of "Solar PV plants" or as a separate category. What do you think @marliekeverweij and @michieldenhaan?

**Comment by michieldenhaan** [comment]
I think the reason it's excluded in this chart is because CSP is a form of solar thermal, not PV. We could of course generalise the chart to show all solar power production, but given that CSP plays a relatively minor role in the ETM I would prefer to focus on other issues.

**Comment by mabijkerk** [comment]
> I think the reason it's excluded in this chart is because CSP is a form of solar thermal, not PV.

Solid argument, I implicitly assumed the chart showed solar production, even though it says production of solar PV in the name.
