### ISSUE TITLE
Output of P2H should not go to nearly zero when sector grows

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3693]
I made a scenario based on II3050 - European.
With some sectors set to zero and no other flex apart from P2H.

I am confused by the behaviour of P2H when the chemicals sector grows.

Three examples:

1. Sector size of Chemicals 200%, 100% H2 heaters and P2H at maximum --> the behaviour of P2H is as I expect it to be. [link](https://pro.energytransitionmodel.com/saved_scenarios/10626)
2. Sector size of Chemicals 210%, 100% H2 heaters and P2H at maximum --> the behaviour of P2H is **not** as I expect it to be. P2H boilers are hardly operated. [link](https://pro.energytransitionmodel.com/saved_scenarios/10625) 
3. Sector size of Chemicals 210%, 80% H2 heaters, 20% electric boilers and P2H at maximum --> the behaviour of P2H is **not** as I expect it to be. P2H boilers are hardly operated. [link
](https://pro.energytransitionmodel.com/saved_scenarios/10624)
### Screenshots
1. 
![image](https://user-images.githubusercontent.com/19907658/114688507-0a713f00-9d15-11eb-8744-3506e5f82e48.png)
2. 
![image](https://user-images.githubusercontent.com/19907658/114688530-0fce8980-9d15-11eb-8809-ad37ce8d9eb0.png)
3. 
![image](https://user-images.githubusercontent.com/19907658/114688464-01806d80-9d15-11eb-8074-ca33ddac8178.png)

Assigning @marliekeverweij please re-assign / relable when appropriate

**Comment by marliekeverweij** [comment]
Interesting issue, good catch.

There seems to be a tipping point between [Size = 208%](https://pro.energytransitionmodel.com/scenario/demand/industry/energy-demand-in-the-industry) and [Size = 209%](https://pro.energytransitionmodel.com/scenario/demand/industry/chemicals).

@antw do you have time to look into this issue?
