### ISSUE TITLE
Make it possible to add links to external websites to scenario description of featured scenarios

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3695]
I would be nice when it is possible to add links to external websites to the scenario descriptions of featured scenarios. At the moment it's only possible to add links to our own websites. I just featured the Northern Ireland scenarios and I wanted to reference to their governmental page with all related documents, but that was not possible.

**Comment by antw** [comment]
This was requested in the past and it wasn't possible due to us not having a way to tell when it is safe to allow people to link off-site, and when it isn't.

Now that we have featured scenarios we could allow external links for those only, while continuing to disallow them for all other scenarios.

**Comment by marliekeverweij** [comment]
It would be nice to pick this up before the deploy (this / next week). The scenario descriptions of the Northern Ireland scenarios would be significantly improved with the links to their websites and reports.
