### ISSUE TITLE
Add NL translation to "Present" in the ETM landing page

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3703]
In the Dutch ETM landing page the word "Present - xx" is not translated in the dropdown box where the user can select the future year that should be modelled (see screenshot below). A suitable Dutch translation would be "Heden".

<img width="675" alt="Screenshot 2021-04-22 at 13 49 27" src="https://user-images.githubusercontent.com/67338510/115709489-90befe00-a371-11eb-97eb-86134b174d50.png">

The reason for this is that the word "Present" is hardcoded into `app/assets/javascripts/intro.coffee`. Since the present year cannot be selected by a user, I would propose to move it from the dropdown box, to the left. This way the dropdown box would only show the future year and the NL locales for "Present" could be added to the model. Do you think that this would be possible @antw?

A very quick sketch of what I mean with moving "Present" from the dropdown:
<img width="667" alt="Screenshot 2021-04-22 at 13 53 17" src="https://user-images.githubusercontent.com/67338510/115710313-7cc7cc00-a372-11eb-89f7-3b645dd5e268.png">

**Comment by antw** [comment]
TBH I kinda like that the "Present" is inside the drop-down, if only because it provides a more consistent look to the form. However, I don't have a strong opinion.

Clearly "Present" should not be a hard-coded string, and this should be changed.

**Comment by mabijkerk** [comment]
I have no strong preference for leaving it in or moving it out of the drop-down. My main issue was that it would be good to add a translation and I thought that it might not be possible without moving it out of the drop-down.
