### ISSUE TITLE
Adjust workflow image: "Results" -> "Results & data"

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3705]
Today we have merged the link to the Dataset Manager, including a rename of the tab "Results" to "Results & data". 

![Screenshot 2021-04-28 at 16 32 27](https://user-images.githubusercontent.com/32833996/116421656-548f1000-a83f-11eb-9b64-49060f20e02b.png)

This means that we have to adjust the workflow images... We have two of them, one on the landing page and one in the flexibility section:
![Screenshot 2021-04-28 at 16 34 35](https://user-images.githubusercontent.com/32833996/116422011-a0da5000-a83f-11eb-8779-0dec3af439a6.png)
![Screenshot 2021-04-28 at 16 32 15](https://user-images.githubusercontent.com/32833996/116421620-4d680200-a83f-11eb-8c7d-5b7bc591753f.png)

**Comment by michieldenhaan** [comment]
Do we also want to include the new Emissions section in some way?

**Comment by Charlottevm** [comment]
Good point, we can add it to the 'make assumptions about flexibility, costs
and emissions?'

**Comment by Charlottevm** [comment]
Good point, we can add it to the 'make assumptions about flexibility, costs
and emissions?'

**Comment by Charlottevm** [comment]
<img width="1095" alt="afbeelding" src="https://user-images.githubusercontent.com/74194356/119625944-0142ba00-be0b-11eb-9835-19ffa9326bc0.png">
like so?

**Comment by marliekeverweij** [comment]
Yes I like it!
