### ISSUE TITLE
Change text on landing page of ETM Pro version

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#3708]
![Screenshot 2021-04-29 at 17 09 17](https://user-images.githubusercontent.com/4669028/116574171-c03fae80-a90d-11eb-82f6-6b13c8b24bee.png)

I would change the first line to 'Een nieuw scenario kan je starten door één van de beschikbare gebieden te kiezen' as 'regio's' for me means RES-regio's. I would also change 'meest gedetailleerde regio' to 'meest gedetailleerde gebied'.

The same goes for the English text. I would change 'choose one of our modelled regions' to 'choose one of the available areas'. And 'region' to 'area'.

**Comment by marliekeverweij** [comment]
Good idea! I would indeed change 'regio's' in Dutch to 'gebieden'. In English I would keep 'region', as I find 'area' a little vague and the term RES-regions is not used by English users.

@jorisberkhout I think this is the place to also add something like:
Is the region you are interested in not in the list? Please contact us to see what is needed to add your region to the ETM.

What do you think?

**Comment by jorisberkhout** [comment]
> What do you think?
Excellent idea!

**Comment by marliekeverweij** [comment]
@jorisberkhout and I want to change the text the text below. We want to remove the "Not sure what to choose?"-part as people visiting this website probably know what there doing here and know in which area they're interested:

_To start a new scenario, choose one of the available regions and a year in the future. The ETM is available on different geographical levels. Is the region you are interested in not in the list? Please [contact us](https://energytransitionmodel.com/contact) for support._

**Comment by jorisberkhout** [comment]
LGTM!
