### ISSUE TITLE
Remove "Fuel production"-section and add sliders for future production of fossil fuels

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3715]
As part of the ETM simplification we want to remove the fuel production section in the ETM. This section includes the yearly inland production curves for different fossil fuels (in the back end these curves are called `time_curves`). 

![Screenshot 2021-05-03 at 16 55 37](https://user-images.githubusercontent.com/32833996/116894709-a914ff80-ac32-11eb-9e35-a47c9bc5fd65.png)

Instead of these curves we want to add sliders with which the user can set the future inland production of each fossil fuel, this is necessary for the graph to determine how much of the fuel should be imported / exported. We should add sliders for:
- coal
- lignite
- natural gas
- mineral oil
- uranium

My proposal for the location of these sliders would be in the "Electricity"-section as in this section fossil fuel power plants are located (btw: we could use the same chart "Future energy imports" as now in the Fuel production-section)
![Screenshot 2021-05-03 at 16 52 40](https://user-images.githubusercontent.com/32833996/116894367-41f74b00-ac32-11eb-9c17-0bf8fa36a743.png)

We could also keep the sidebar item "Fuel production", but this feels too prominent for these not very important sliders.

What do you think of this proposed location @quintel/core?

**Comment by ChaelKruip** [comment]
> We could also keep the sidebar item "Fuel production", but this feels too prominent for these not very important sliders.

I would be in favour of keeping the sidebar item. In my opinions these sliders are quite important. If the user does not set them, the situation will be as it currently is. For NL this would imply production of natural gas for instance, which we know is not correct as it will be phased out in the near future.

**Comment by marliekeverweij** [comment]
Thanks for your reaction! We actually concluded the same yesterday (but didn't give an update in this issue), so we will keep the fuel production sidebar item.
