### ISSUE TITLE
Add dataset to featured scenario list

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3716]
Until recently we mostly included NL scenarios in our featured scenario list. Since a few weeks we have also included scenarios for Northern Ireland. To clearly distinguish between the countries, we have added the country name to the scenario title. It would be nice to automatically include the dataset name in the list :) Now you see the dataset name twice on the scenario page:
![Screenshot 2021-05-03 at 17 32 15](https://user-images.githubusercontent.com/32833996/116897410-82a49380-ac35-11eb-944c-5b1087cae909.png)

![Screenshot 2021-05-03 at 17 21 03](https://user-images.githubusercontent.com/32833996/116897324-6acd0f80-ac35-11eb-85f3-093bbf4c928f.png)

**Comment by antw** [comment]
I've done this locally, but would be grateful for feedback. Here's what it looks like if we add the dataset name and end year to the list:

![Screenshot 2021-05-10 at 16 18 32](https://user-images.githubusercontent.com/4383/117682831-6364b380-b1ab-11eb-9b1d-a4cb9ecadbbf.png)

It's *fine*.

However I got to thinking: why do we have to put all national scenarios together? Why not separate categories for the Netherlands and Northern Ireland?

![Screenshot 2021-05-10 at 16 14 59](https://user-images.githubusercontent.com/4383/117682958-80998200-b1ab-11eb-8a1b-47f5ed3e41ae.png)

I think this looks clearer, to be honest. The *categories* show which dataset the scenarios belong to, and you don't need to move your eyes to the right.

That leads me to this:

![Screenshot 2021-05-10 at 16 15 47](https://user-images.githubusercontent.com/4383/117683063-97d86f80-b1ab-11eb-9892-e631bdbe3636.png)

I think this is the best of both worlds: we don't clutter up the list with redundant dataset names, *and* the I think it's easier to find the scenario you want; scenarios for NL and NI aren't mixed together.

@marliekeverweij What do you think?

**Comment by marliekeverweij** [comment]
> I think this is the best of both worlds: we don't clutter up the list with redundant dataset names, and the I think it's easier to find the scenario you want; scenarios for NL and NI aren't mixed together.

I agree, good idea! Less = more
