### ISSUE TITLE
Misleading "initial investment" label in technical properties table

### ISSUE THREAD

**Issue by antw** [quintel/etmodel#3727]
A visitor to the ETM recently sent a message expressing confusion why after reducing solar PV investment costs by -100% the technical properties table still shows 500k initial investment.

You may reproduce this yourself by visiting Costs → Solar power → Investment, setting the Solar panels slider to -100%, then viewing the technical properties.

![Screenshot 2021-05-18 at 12 56 26](https://user-images.githubusercontent.com/4383/118646953-b7d5e780-b7d8-11eb-82f3-87a0e817f8f9.png)

This happens because what we are calling "Initial investment" is actually `total_investment_over_lifetime_per(:mw)`. There are a number of other places where we are mislabelling *total* investment as *initial* investment.

Total investment is defined as:

* total_investment_over_lifetime
  * total_initial_investment
    * initial_investment
    * ccs_investment
    * cost_of_installing
    * storage_costs
  * decommissioning_costs

The 500k costs come from `cost_of_installing`; this *is* communicated in the description of the investment slider but is not obvious in the table itself.

There are two solutions:

1. Relabel the row as "Investment over lifetime"
2. Remove the initial investment row, and replace it with five rows – one for each contributor in total investment. This would be clearer to users, but risks the table becoming outdated if we change how total investment is calculated (if we add another contributor, we must remember to also update this table).

I'm happy to take care of this (but would need some assistance with Dutch translations).

@marliekeverweij @michieldenhaan: Since you both had some involvement in updating this table recently, I'd appreciate your feedback. Including @ChaelKruip.

**Comment by michieldenhaan** [comment]
I don't have a very strong preference but I can imagine that option 1 is the easiest and probably good enough. Option 2 makes the table a lot larger with attributes that are only relevant for a handful of nodes (many nodes don't have decommissioning, ccs_investment, storage, installing etc.).

If we are to update our cost calculation, we should investigate whether we can remove some of the above attributes (installing and decommissioning could maybe be included in 'initial investment'?) and also add a data export that clearly communicates all costs with all relevant details.

**Comment by marliekeverweij** [comment]
I am in favour of option 1 as I prefer to keep the table simple

**Comment by antw** [comment]
Thanks to you both, I'll get this done.

How would you feel about an optional toggle-able description of attributes in the table?

![Screenshot 2021-05-18 at 16 44 34](https://user-images.githubusercontent.com/4383/118682513-6e959000-b7f8-11eb-90dc-69c74ba68a0a.png)
![Screenshot 2021-05-18 at 16 44 42](https://user-images.githubusercontent.com/4383/118682524-71908080-b7f8-11eb-974c-d92d5d8d8f7e.png)

**Comment by michieldenhaan** [comment]
Nice! I like it
