### ISSUE TITLE
Final energy demand per sector [%] scales to 1% instead of 100%

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3733]
The 'Final energy demand per sector [%]' chart scales to 1% instead of to 100%. See screenshot below for a blank NL scenario:

<img width="637" alt="Screenshot 2021-05-28 at 16 06 23" src="https://user-images.githubusercontent.com/67338510/119996281-d99c4f00-bfce-11eb-8c61-89bbf8fca0a5.png">

The underlying queries are set as factors. The input should be adjusted so that they are recognised properly as percentages, which can be achieved by multiplying them with 100 - which is also done for similar charts, such as the renewability of final demand or renewable electricity.

**Comment by mabijkerk** [comment]
The queries used in the 'Final energy demand per sector [%]' chart are also used as input for the percentage bars of the demand sidebar items.
Multiplying the queries with 100 therefore has the effect that the percentage bars of the demand sidebar items would be 100 times too large - even though the chart would be fixed.

The updated chart:
<img width="500" alt="Screenshot 2021-05-28 at 17 17 05" src="https://user-images.githubusercontent.com/67338510/120005841-8b8c4900-bfd8-11eb-9553-67fbceba898f.png">

The resulting sidebar:
<img width="217" alt="Screenshot 2021-05-28 at 17 17 32" src="https://user-images.githubusercontent.com/67338510/120005877-99da6500-bfd8-11eb-8c21-fb1df2617a8a.png">

@antw would it be difficult for you to have the sidebar percentage bars register the input value as 100 times lower? If this is too much effort, I can simply create separate queries for this chart and not change anything else.

**Comment by antw** [comment]
If this is already on a branch, I think you can change that here:

https://github.com/quintel/etmodel/blob/a600c0fa1fb068a6f6bf0ea85038c6db3f36d40a/app/assets/javascripts/lib/views/sidebar_view.coffee#L76

```diff
-      percentage = Math.round(result * 100)
+      percentage = Math.round(result)
```
