### ISSUE TITLE
CO2 emissions of electricity production chart should include hydrogen

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3740]
The chart `CO2 emissions of electricity production`, includes coal, lignite, oil, natural gas and waste (see screenshot below). However, emissions can also arise from electricity produced from hydrogen. These emissions are currently not displayed in the chart and should be added.

<img width="500" alt="Screenshot 2021-06-07 at 16 23 29" src="https://user-images.githubusercontent.com/67338510/121033700-b468c700-c7ac-11eb-93a8-8e3027cff29f.png">

**Comment by ChaelKruip** [comment]
> However, emissions can also arise from electricity produced from hydrogen.

Is that the case for grey hydrogen only?

**Comment by mabijkerk** [comment]
As far as I know, blue hydrogen also has associated emissions, since not all emissions can be captured with CCS.

**Comment by mabijkerk** [comment]
It is somewhat more complicated than I originally thought. In contrast to the other fuels already in the chart, hydrogen has no on-the-spot greenhouse gas emissions when the electricity is produced.

Therefore we should think about what we want this chart to show: domestic or total emissions? This is especially relevant when the hydrogen that is used for electricity production is imported hydrogen.

**Comment by michieldenhaan** [comment]
Fair point, I think I would prefer the chart to show all on-the-spot/direct emissions (emissions that are statistically attributed to the power sector). So no hydrogen emissions nor emissions of imported electricity. My reasoning is that the chart currently shows emissions of domestic power _production_, also of power that is exported. It would be odd if the chart then also shows emissions of imported electricity, or other emissions not directly taking place in the power sector (such as hydrogen production, with imported hydrogen indeed being a good example).

As a nice-to-have we could make a similar chart for hydrogen production and heat production and/or make a similar chart that shows emissions associated with domestic power _consumption_.

**Comment by marliekeverweij** [comment]
I agree with Michiel. @mabijkerk is it okay to close this issue?

**Comment by mabijkerk** [comment]
My preference would be to add a short description to the chart, stating that it shows the on-the-spot emissions of domestic power production. I can add this description and then close the issue.

**Comment by marliekeverweij** [comment]
Great. If you do it before tomorrow 12am, then it will be deployed :)
