### ISSUE TITLE
Cooling for airconditioning seems to miss in LV network calculation. 

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3742]
![image](https://user-images.githubusercontent.com/33415156/122200562-7306a480-ce9b-11eb-910f-7e9e9d0a38c6.png)

@ChaelKruip Do you think this is an urgent issue? 
@michieldenhaan Do you think this check can be part of the mechanical turk?  Peak load future of chart 'Electricity demand on low voltage net' should be equal to peak load future of chart 'Electricity network capacity and peaks'?

**Comment by michieldenhaan** [comment]
@Charlottevm Would you mind looking into this when time permits?

**Comment by ChaelKruip** [comment]
I don't think this is urgent but perhaps it is easy to fix. This might be a matter of adding a line to the node file right @michieldenhaan ?

**Comment by marliekeverweij** [comment]
@Charlottevm do you have time to pick this up before the deploy next Tuesday?

**Comment by Charlottevm** [comment]
I do not entirely understand the issue yet as I cannot recreate it. When I apply maximum cooling demand it is visible in the LV network calculation. What is the problem exactly?

<img width="609" alt="afbeelding" src="https://user-images.githubusercontent.com/74194356/124573231-a2c91c80-de49-11eb-9ef0-8d0b1b62afc3.png">

**Comment by Charlottevm** [comment]
@MartLubben

**Comment by MartLubben** [comment]
I cannot reproduce it anymore. Interesting. It can be closed IMO.
