### ISSUE TITLE
Emissions factsheet button not working

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etmodel#3747]
The 'year button' on the emissions factsheet is not working. The start year also shows the future scenario outcome instead of the current emissions. Example: https://pro.energytransitionmodel.com/regions/GM1586_oost_gelre?scenario=846488&time=present.

![afbeelding](https://user-images.githubusercontent.com/74194356/123602335-ed6ae900-d7f8-11eb-9072-9e89e78f4478.png)

**Comment by noracato** [comment]
What exactly happens?

When I press the button using the link you sent, I see the values changing:

<img width="1187" alt="Screenshot 2021-06-28 at 10 48 30" src="https://user-images.githubusercontent.com/14875123/123607779-7b959e00-d7fe-11eb-8c9b-1c85f01a8ecc.png">
<img width="1187" alt="Screenshot 2021-06-28 at 10 48 37" src="https://user-images.githubusercontent.com/14875123/123607794-7e908e80-d7fe-11eb-8030-9cfcaf296054.png">

**Comment by Charlottevm** [comment]
In this example the area has 366 KT emissions...
<img width="974" alt="afbeelding" src="https://user-images.githubusercontent.com/74194356/123623617-f4502680-d80d-11eb-96d2-b33d2b7fc29a.png">

...whilst here is has 349 KT emissions. Both are numbers from 2018 and therefore should not diverge.
<img width="972" alt="afbeelding" src="https://user-images.githubusercontent.com/74194356/123623850-34afa480-d80e-11eb-9529-47bf60c5255a.png">

We thought this was due to a bug in the button?

**Comment by noracato** [comment]
Yes, I understand now, thanks!

I still can not reproduce this for other scenarios then this one. In this scenario it looks like 17kT of emissions have appeared in the built environment for the present day. Can this possibly be due to the `electricity_interconnector_1_co2_emissions_present` you uploaded? That's the only present-input I can see that was set.
