### ISSUE TITLE
Adding future efficiencies to the Costs section

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etmodel#3749]
@quintel/core:

As part of the NI updates we want to include the future efficiencies of technologies within the Costs section and possibly restructure the cost section. If you have an opinion on the matter then we would love to hear what you think about our suggestions below. 

The update regards the following technologies: 

**Electricity**

_Coal plants_
- Pulverized coal 
- Pulverized coal with co-firing 
- Coal IGCC 
- Coal conventional 
- Coal plant for district heat (CHP) 
- Co-firing coal plant for district heat (CHP) 

_Gas plants_
- Gas CCGT 
- Gas turbine 
- Gas conventional 
- Gas combustion engine 
- Large-scale gas plant for district heat (CHP) 
- Small-scale gas plant for district heat (CHP) 

_Oil plants_
- Oil-fired
- Diesel generator

_Nuclear_
- Nuclear conventional
- Nuclear 3rd Gen

**Renewable electricity**
- Solar
- Hydro
- Biomass
- Waste power
- Hydrogen plant
- Geothermal

**Heating**

_Households_
- Condensing combi boiler
- Heat pump (ground)
- Wood pellet stove
- Electric heater
- Gas-fired heater

_Buildings_

- Gas-fired heater
- Heatpump with TS
- Electric heater
- Biomass-fired heater

We have two options at the moment:

**1. We simply add the efficiencie sliders to the existing technologies in the cost section like so:**
<img width="473" alt="afbeelding" src="https://user-images.githubusercontent.com/74194356/124261474-207ee680-db31-11eb-920f-8ef203b09372.png">

**2. We add the efficiency but in addition we also restructure the sidebar of the cost section as follows:**

**Costs**
- Merit Order
- Fuel Prices
- Electricity
- Renewable electricity
- Imported electricity 
- Infrastructure
- Heat
- Transport
- Hydrogen
- Flexibility
- CCUS
- WACC

_We are currently in favor of option 2 as it would improve the user experience due to the recognition of the sidebar items compared to the suppy section. Which option do you prefer? & do you think this is the right (most intuitive) place to add the future efficiencies for technologies?_

Furthermore we were wandering whether the sliders describing the 'investment' as well as 'operation & maintenance' should be combined into one slider (describing the LCOE?). This would reduce the number of sliders and possibly make it easier for users to use the cost section. 

_Is this an important asset of the cost section? What are possible hurdles in doing this? Do you agree this would be easier for users?_

<img width="466" alt="afbeelding" src="https://user-images.githubusercontent.com/74194356/124262399-4b1d6f00-db32-11eb-9f8d-b3dbfc51846c.png">

**Comment by michieldenhaan** [comment]
Nice overview @Charlottevm! I'm also in favour of option 2.

> Furthermore we were wandereing whether the sliders describing the 'investment' as well as 'operation & maintenance' should be combined into one slider (describing the LCOE?).

Sounds good! We might have to do a small scenario migration but other than that I think less sliders = better.

One side note: I would prefer only adding efficiency sliders for technologies for which this has a meaningful impact in scenarios. I don't think that's the case for wind, hydro and (arguably) geothermal power, so would prefer not to add those.

**Comment by mabijkerk** [comment]
> Which option do you prefer?

I also like option 2! I do wonder whether 'Costs' still is a suitable term when efficiencies are added to the slides of that section. As a user you would have to know that efficiencies can be set in the 'Costs' section: it's not likely that it's the first place you'll look. Is it an option to rename it?

> What are possible hurdles in doing this?

How would the ETM update technology specifications based on the user input for LCOE? Currently user inputs for investment costs and O&M costs directly affect the related node attributes, but there is no node attribute for LCOE.

> Do you agree this would be easier for users?

I definitely think it would be easier for users e.g. to make changes to the merit order. The only downside that I can think of is that by using LCOE as costs input, users lose some insight in the relative impact of changing the investment costs compared to the O&M.

**Comment by marliekeverweij** [comment]
Thanks for your input @mabijkerk & @michieldenhaan 

>  I do wonder whether 'Costs' still is a suitable term when efficiencies are added to the slides of that section. As a user you would have to know that efficiencies can be set in the 'Costs' section: it's not likely that it's the first place you'll look. Is it an option to rename it?

Yes good one, we want to rename it indeed! We are thinking of "Costs & efficiencies". If you have better names, let us know.

We will focus on the efficiency sliders first and if we have time left, we'll focus on the costs sliders. @michieldenhaan had the idea to have one slider per technology: set the absolute investment costs (euro/MW) with a slider and also update the OPEX costs with the same % change.

I think setting the LCOE will not work, was it's dependent on the amount of energy produced. And the amount of energy produced varies for a technology due to the merit order of heat / electricity.
