### ISSUE TITLE
Is lighting technology split for nl2019 is identical to 2015?

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#3754]
![image](https://user-images.githubusercontent.com/308563/124782217-58789600-df44-11eb-90f0-92490f8cef88.png)

This seems unlikely not to have changed in 4 years. I expect far fewer incandescent lamps. The shares for non-residential buildings have changed. I guess we haven't been able to locatie new data sources for residences?

re-assign as needed

**Comment by marliekeverweij** [comment]
This was indeed not updated. Thanks for your sharp eye!
