### ISSUE TITLE
Test future efficiency sliders and hydrogen boilers in built environment when they are on BETA

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3768]
Will let you know when it is merged and where you can find these features, expecting this Friday

I would be great if you could find 2 hours for testing somewhere between Monday 26th and Wednesday 28th of July

**Comment by marliekeverweij** [comment]
Most of the work is ready for testing! Charlotte is working on the last efficiency sliders for hydogen boilers and air-source (hybrid) heat pumps. This will probably be merged by tomorrow end of the day, so better to test on Wednesday if that is possible.

The hydrogen boilers can be found in the [households heating section](https://beta-pro.energytransitionmodel.com/scenario/demand/households/space-heating-and-hot-water) and [buildings heating section](https://beta-pro.energytransitionmodel.com/scenario/demand/buildings/space-heating).

The efficiency sliders are located [here for fossil power plants](https://beta-pro.energytransitionmodel.com/scenario/costs/specs_electricity/coal-plants), here for [renewable power plants](https://beta-pro.energytransitionmodel.com/scenario/costs/specs_renewable_electricity/wind-turbines) and [here for heating in houses/buildings](https://beta-pro.energytransitionmodel.com/scenario/costs/costs_heat/heating-in-houses-and-buildings). 

Let me know when you have questions!

**Comment by marliekeverweij** [comment]
The remaining sliders have now also been added, so it's ready for testing :) 

Two remarks about the air-source (hybrid) heat pump sliders:
- For the air-source heat pumps we have added %-change sliders for the COP and not absolute sliders (like for the other heaters). This is because we cannot directly set the yearly COP or seasonal COP (SCOP): it is a result of hourly COP calculations depending on the outside temperature. With the %-sliders we change the base COP in the formula outside temperature vs. COP (see our documentation: https://docs.energytransitionmodel.com/main/heat-pumps)
- The new SCOP in the specs table underneath the slider is not [old COP] * [% change]. We kind of expected this for the air-source heat pump. If you know why this is, let me know!

**Comment by mabijkerk** [comment]
I would include a reference to the new location of transport efficiencies in the Demand > Transport section.

<img width="500" alt="Screenshot 2021-07-28 at 10 19 05" src="https://user-images.githubusercontent.com/67338510/127288963-c2bb7264-9338-4825-8274-765f17556cd2.png">

**Comment by mabijkerk** [comment]
When I go to Cost & efficiencies > Heat > Heating in households and buildings I can adjust all kinds of efficiencies, but the chart that shows is one about costs per household. When I'm working with efficiencies I would expect to see a chart showing the **energetic** effect of my changes.

<img width="500" alt="Screenshot 2021-07-28 at 10 36 47" src="https://user-images.githubusercontent.com/67338510/127291616-7738a074-3362-4983-909c-afd5b259f5ee.png">

**Comment by mabijkerk** [comment]
For me it wasn't immediately clear that Other heating sources, in Costs & efficiencies > Heat, were about costs. The small text that explains it does not stand out that much. Two suggestions that could make it more clear: 1) change the section headers to something like "Heating efficiencies in houses and buildings" and "Costs of other heating sources" and 2) include it in the slide group sub-headers, like "Heat pumps costs", "Geothermal costs".

<img width="460" alt="Screenshot 2021-07-28 at 10 41 21" src="https://user-images.githubusercontent.com/67338510/127292293-1f5b49b7-1f35-46e1-874c-91066040914c.png">

**Comment by mabijkerk** [comment]
In Costs & efficiencies > Heat > Other heating sources, should changing the sliders for a certain technology e.g., heat pumps affect the costs for **all** heat pumps in the model? Based on the description of the slider "Electric heat pumps" I would think so. When I set the slider to -100% I would expect the costs of heat pumps in the chemical industry to go to 0, because the slider description explicitly names the chemical industry:

<img width="464" alt="Screenshot 2021-07-28 at 11 03 07" src="https://user-images.githubusercontent.com/67338510/127295352-f2079ba2-8325-41a6-9105-af980cba1b71.png">

However, when I go heat pumps in the chemical industry, the costs are unchanged:

<img width="500" alt="Screenshot 2021-07-28 at 11 04 22" src="https://user-images.githubusercontent.com/67338510/127295515-6aca1617-bbdf-4876-8a86-214c1e442c60.png">

**Comment by mabijkerk** [comment]
> For the air-source heat pumps we have added %-change sliders for the COP and not absolute sliders (like for the other heaters).

For clarity I might be in favour of moving the heat pump (ground) to Households - change in COP as well. Now it seems weird that two sliders for COP are separate, while one is part of the efficiencies. For Buildings I would then make a similar distinction between sliders about efficiencies and sliders about COP.

> We kind of expected this for the air-source heat pump. If you know why this is, let me know!
I have not spent much time thinking about it, so I don't know the answer, but when I adjust the slider it does feel counter-intuitive.

**Comment by mabijkerk** [comment]
@jorisberkhout I have tested the hydrogen boilers on their description and behaviour and not found any issues. I have also tested the heat costs & efficiencies, mainly on their description, see the comments above.

I have not been able to thoroughly test the efficiency sliders for fossil power plants, renewable power plants, and the behaviour of heat efficiency sliders, so if you want you can focus on testing those.

**Comment by jorisberkhout** [comment]
I think there is a bug in the way the CHP - electricity sliders are modelled. I have created a [scenario](https://beta-pro.energytransitionmodel.com/saved_scenarios/4904) with just some coal CHP and an interconnector.
![Screenshot 2021-07-28 at 16 36 36](https://user-images.githubusercontent.com/4669028/127341664-42b2f21c-7ecd-426d-b6d5-902341d4eade.png)

The coal CHP is always running at full capacity. The new `Coal CHP - heat slider` works as expected. If I double the heat efficiency, the heat production doubles according to this table
![Screenshot 2021-07-28 at 16 37 51](https://user-images.githubusercontent.com/4669028/127341996-7006ca24-3ee6-4da0-a1a7-c1f2f17689d3.png)

However, if I change the `Coal CHP - electricity` slider setting, the electricity production as reported in the table above does *not* change, but the heat production does.

@marliekeverweij , this seems to be a bug. Do you have any clue what causes this?

**Comment by marliekeverweij** [comment]
Thanks @jorisberkhout & @mabijkerk for your thorough testing!!!

I will have a look at the issues today

**Comment by marliekeverweij** [comment]
> However, if I change the Coal CHP - electricity slider setting, the electricity production as reported in the table above does not change, but the heat production does.
> @marliekeverweij , this seems to be a bug. Do you have any clue what causes this?

@jorisberkhout and I just concluded that this is not a bug, but expected behaviour 😅 BTW: the above behaviour applies to all power plants, not only CHPs. It feels a bit counterintuitive, but actually it is quite logical. It does require some additional explanation in the slide for the users to be able to understand it, I will add it a short version of the following explanation:

In the ETM the user sets the _electrical output capacity_ for the power plants, so this is fixed. When changing the _electrical effiiciency_ for a plant, then the electricity output will not change _for power plants running at max full load hours_ (since the output capacity is fixed). So changing the _electrical effiiciency_ will impact the _fuel input_ (higher electrical effciency -> less fuel needed, lower electrical efficiency -> more fuel needed). 
Please note: this change in fuel input impacts the marginal costs of that plant and thus the position in the merit order (and thus could also potentially also impact the full load hours & electricity production, but in the above case only one plant at max full load hours is assumed!

For CHPs another effect happens: because the electrical efficiency slider impacts the fuel input, the heat production will change as well! That is exacty what @jorisberkhout noticed :)
