### ISSUE TITLE
The other industry sliders cannot be set for a certain scenario

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3769]
For one of my scenarios (https://pro.energytransitionmodel.com/saved_scenarios/10769), setting the industry other sliders results in 422 errors. This doesn't seem to be the case for other scenarios. Not sure what's going on here.. @antw / @noracato, would one of you have time to help me out here?

![image](https://user-images.githubusercontent.com/5946498/126184921-841921c7-8c6f-45a3-9366-b11bea4143d1.png)

**Comment by antw** [comment]
> pro.energytransitionmodel.com/saved_scenarios/10769

Is this definitely the correct scenario? I've tried several clones of this scenario and have no trouble moving these sliders.

422 errors indicate that the data being sent to ETEngine isn't passing validation checks: inputs higher or lower than the allowed value, or most often a share group that doesn't sum to 100%. The "other_industry_energetic" group does sum to exactly 100% in your scenario so either ETModel is sending new values that don't, or something else is going on.

Next time it happens can you please click on the address in the error message ("https://engine.energytransitionmodel.com/...") to view the request. Then you can press "Preview" to view the error data returned by ETEngine (click the triangles to expand the messages):

![Screenshot 2021-07-19 at 16 43 08](https://user-images.githubusercontent.com/4383/126188012-da9a1f62-7db2-4173-a7c5-f359739482b8.png)

If this is only experienced occasionally, it would be useful to keep track of which sliders were moved in which order, and to what values.

**Comment by redekok** [comment]
Thanks for looking into this Anthony! Strangely enough, it seems to be working today.. Maybe my local machine encountered some internet connection issues? Although I don't understand why that would result in a 422 error though..

Anyways, closing this issue!

**Comment by redekok** [comment]
Btw, I got this error message for another scenario where I encountered this issue:

`0: "\"other_industry_energetic\" group does not balance: group sums to 114.30000000000001 using industry_aggregated_other_industry_wood_pellets_share=0.0 industry_aggregated_other_industry_network_gas_share=51.7 industry_aggregated_other_industry_useable_heat_share=0.2 industry_aggregated_other_industry_coal_share=0.0 industry_aggregated_other_industry_hydrogen_share=23.1 industry_aggregated_other_industry_electricity_share=25.0 industry_aggregated_other_industry_crude_oil_share=14.3"`

![image](https://user-images.githubusercontent.com/5946498/126278576-41b38f5b-c151-4bc1-8a95-bc16a4e8f9f0.png)

It seems as if ETEngine didn't notice the change for the oil slider from 14.3% to 0%. Could that be due to some caching problem (or a slow wifi connection) or something along those lines?

**Comment by antw** [comment]
> It seems as if ETEngine didn't notice the change for the oil slider 

That seems possible. ETModel only sends information about what changed. If you move one slider up and another moves down, it sends the values for those two sliders rather than the whole group. If ETEngine thought the oil slider was still 14% and ETModel thought it was 0%, then a balancing error could occur.

If your first request – setting oil to 0% – failed for some reason, that would explain how the two could have different views of the same slider.

I will definitely keep this in mind for the refresh (we should retry the request, and roll back if the failures continue). I'm having trouble doing the same in the current front-end; there are some workarounds, but might take half a day to a day.
