### ISSUE TITLE
Unit in HHP threshold chart is wrong

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#3773]
As pointed out by a user, the unit on the Y-axis of the chart 'Hybrid heat pump threshold COP for space heating' should be `ct/MJ` instead of `EUR/MJ`.

Note that a screenshot of this chart is included in the documentation and needs to be changed there too https://docs.energytransitionmodel.com/main/heat-pumps/#threshold-cop

![Screenshot 2021-07-23 at 15 06 50](https://user-images.githubusercontent.com/4669028/126786155-169addf2-dfdf-44f2-80b9-ec83f78f16fe.png)t

Assigning @marliekeverweij , reassign as you see fit.

**Comment by Charlottevm** [comment]
@antw has fixed this issue 👍
