### ISSUE TITLE
Investment table is missing several translations

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#3780]
See, screenshot as an example. I counted 8 missing translations in total.

![Screenshot 2021-07-28 at 15 41 56](https://user-images.githubusercontent.com/4669028/127332877-8a7cd178-878a-4416-9194-f7fdee557748.png)

Assiging @mabijkerk , re-assign at will.

**Comment by mabijkerk** [comment]
Added missing labels. After inspection it seems that this table could you a critical review, I will open another issue for this.
