### ISSUE TITLE
Renewability of final demand seems to be calculated incorrectly

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3795]
One of our clients pointed out that the renewability of final demand calculation seemed to result in incorrect values for their [scenario](https://pro.energytransitionmodel.com/scenarios/856639). In this scenario a significant capacity of renewable electricity (solar/wind production) is installed, which results in a high renewable electricity percentage of 97.4%. The renewability of final demand (8%) seems to be too low though, partly because the share of renewable electricity drops to 0% in the future.

![image](https://user-images.githubusercontent.com/5946498/129032378-31fe1088-14a1-4aeb-8f0d-73c0868287f3.png)

![image](https://user-images.githubusercontent.com/5946498/129032555-4bbacb43-c617-4099-b8d2-df1310be9f14.png)

![image](https://user-images.githubusercontent.com/5946498/129032724-6e5d9f8d-25a7-4cba-87ad-44642878b5cf.png)

![image](https://user-images.githubusercontent.com/5946498/129032949-100e680d-6c64-49e2-816d-5c6acf1287fb.png)

@antw, could it be the case that something's going wrong in the `sustainability_share` calculation? When I check the `[households_locally_available_electricity](https://engine.energytransitionmodel.com/inspect/857280/graphs/energy/nodes/households_locally_available_electricity)` node in the graph, I notice that part of the electricity demand is supplied by solar PV on rooftops (with a sustainability share of 1). The sustainability share of the node still drops to zero though..

**Comment by antw** [comment]
I think this is related to quintel/etengine@58de896 in which I removed a fallback for calculating sustainability share when a node has an "infinite" carrier.

To clarify, when calculating `sustainability_share` for a node ETEngine propagates a value from the right of the graph to the node being queried: it will look at all of the node's inputs, and their inputs, until either reaching the far-right of the graph or nodes that belong to the "primary_energy_demand" group.

When it encounters a primary demand node it calculates the `sustainability_share` by first checking if the node has a `sustainability_share` defined in ETSource, and if not it looks at the `sustainable` attribute on the carrier. If neither is set it defaults to 0.

For the "households_locally_available_electricity" node, ETEngine will recurse starting with the three inputs:

* energy_power_lv_network_electricity – which I will ignore for this example.
* households_flexibility_p2p_electricity – which has no energy flow.
* households_solar_pv_solar_radiation – which provides electricity derived from solar radiation.

When ETEngine then hits the "households_solar_pv_solar_radiation" node, it finds that it belongs to the "primary_energy_demand" group and therefore doesn't continue any further to the right.

The "households_solar_pv_solar_radiation" node:

* ... doesn't have a `sustainability_share` set in the node file.
* ... is connected to the locally available electricity node with an "electricity" edge. Electricity does not have a `sustainable` attribute.
* ... **therefore its `sustainability_share` defaults to 0.**

Previously we also detected if a node had any infinite carriers. The solar PV node does have an infinite carrier (it receives "solar_radiation") and we'd fall back to calculating `sustainability_share` like so:

```
sustainability_share = 1 - loss_ouput_conversion
```

The removal of the fallback may have been a mistake, but I think it is *probably* correct to do so: a node having one or more infinite inputs or outputs doesn't guarantee that its sustainability share should be 1.0.

### Solutions

1. Revert to the older functionality of `sustainability_share` and detect nodes with infinite carriers.
2. Consider it an error for a "primary_energy_demand" node to either not have a `sustainability_share` attribute, or for its input carriers to not define `sustainable`.

I think the second solution is the *technically correct* approach but is more work to track down all these nodes and add a share. The first is easy to implement and restores the old behaviour.

Including @ChaelKruip.

**Comment by antw** [comment]
I've gone ahead and implemented the first solution *for now* since this affects quite a few nodes and would rather not wait to fix it. If you're happy with this and don't want to consider the second solution, this issue can be closed.

**Comment by michieldenhaan** [comment]
I would be in favour of the second solution, I think it's not that much work and more transparant than relying on a fallback option.

Your solution is already on PRO right @antw? A client notified us of some outcomes I can't really explain. E.g. in [this](https://pro.energytransitionmodel.com/saved_scenarios/9185) scenario with close to 100% CO2 reduction renewability is only at 46%. When looking at the chart it says that 50% of final demand is fossil electricity. However, the electricity production chart shows almost exclusively wind and solar (and a bit of imports and hydrogen). The renewable electricity figure is at 169%.. Would you mind looking into this?

![image](https://user-images.githubusercontent.com/32056448/129911331-1e20f0b3-6c4d-4431-b7d2-8e318c69aa0a.png)

![image](https://user-images.githubusercontent.com/32056448/129911345-7c76cb01-86dc-4006-8a05-e473add417f7.png)

**Comment by antw** [comment]
Sorry, the fix hadn't been deployed to production. It has now:

![Renewability of final demand 831483](https://user-images.githubusercontent.com/4383/130081262-1d4d5a75-10ac-4ca4-ac13-da271e403367.png)

**Comment by michieldenhaan** [comment]
Thanks! I'm still a bit confused by the high share of fossil electricity (13% of final demand, whereas according to the production chart atleast 93% of total power production is sustainable).

When looking at this [node](https://engine.energytransitionmodel.com/inspect/858869/graphs/energy/nodes/households_locally_available_electricity) it shows an electricity demand for households of 138 PJ, of which 85 PJ is supplied by local solar PV.
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/32056448/130086645-9609f6ac-2929-4ea4-99af-098d37f73986.png">

However, the primary demand of sustainable is only 64 PJ, so less than the solar production.
<img width="653" alt="image" src="https://user-images.githubusercontent.com/32056448/130086987-1a22f294-2ec3-44a4-a4be-b0ef348282c8.png">

I would expect this to be at least 85 PJ (and likely much higher given that also the non local power production is largely sustainable). Do you have an explanation for this?

**Comment by antw** [comment]
Good catch. I think that dates back to when we changed primary_demand to ignore losses on the PD nodes: sustainability_share was already doing that, and so we were ignoring losses *twice*. A fix is on its way to beta and will be on production soon.

![Screenshot 2021-08-19 at 16 02 56](https://user-images.githubusercontent.com/4383/130092694-bb6244b7-b4c2-4114-8a3d-5564ede0c145.png)

![Renewability of final demand 831485](https://user-images.githubusercontent.com/4383/130092711-28f4d763-a8a7-42df-9166-28de1055a0aa.png)

**Comment by antw** [comment]
It seems that fix is not quite right either. 😠 

Removing the compensation for loss from sustainability_share results in renewable electricity exceeding 100%. Back to the drawing board...

**Comment by antw** [comment]
Sorry for the comment spam...

I'm looking at the "Renewable electricity" chart, which for this II3050 scenario has values greater than 100%:

![Renewable electricity 831485](https://user-images.githubusercontent.com/4383/130095715-64175836-8512-4337-b9a3-24ca05b4f95d.png)

I assumed this was related to `sustainability_share`, but it seems not to be the case. The queries for this chart look something like this:

```ruby
DIVIDE(Q(electricity_produced_from_wind), Q(total_electricity_consumed)) * 100
```

Dividing energy produced by consumption may result in errors when more energy is consumed than produced (energy is curtailed), and indeed this scenario does have 16.5B curtailed. I think the queries should look like:

```ruby
DIVIDE(Q(electricity_produced_from_wind), Q(total_electricity_produced)) * 100
```

**Comment by michieldenhaan** [comment]
Thanks @antw! 🚀 

The renewable electricity share exceeding 100% is indeed odd, but apparently the official (EU) definition is to divide by consumption (see https://github.com/quintel/etsource/issues/2391).

@redekok Shall we leave this open to remind us of explicitly setting the `sustainability_share` on the primary demand nodes?

**Comment by antw** [comment]
> but apparently the official (EU) definition is to divide by consumption (see quintel/etsource#2391).

Thanks. Lesson to myself to search for other issues first.

I've taken care of the missing sustainability shares and sent a PR. I'll close this once that is merged and the ETEngine side has been done.
