### ISSUE TITLE
Slider info of hydrogen trains should be updated

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3797]
@Charlottevm:

> At the moment the slider info mentions that "hydrogen trains are a new development that we might see more of in the future, because of their clean and effective way of transportation." Maybe I would refrain from saying 'effective' as electrifying trains would still be way more efficient & cheap compared to using hydrogen as a fuel. And the hydrogen ladder often puts using hydrogen for trains in the last category ('refrain from using it, other alternatives possible'). We could simply mention the technology and what the slider does and leave the debate regarding efficiency/effectiveness to the user? It might also be nice to connect more to the other hydrogen slider info such as the 'Hydrogen trucks'. That one is also more 'technical' rather than 'speculative'. 

@jorisberkhout:

> * Issue: The 4 sliders in the freight transport -> train technology slide are missing a download button for the Technical and financial properties Excel-file (the 4 sliders in the passenger transport -> train technology slide do have does download links);
> * Suggestion: I would include a link the Supply -> hydrogen sidebar item in the slide texts for both the passenger and freight train technology slides. The achieved emission reduction is highly dependent on the type of hydrogen that is supplied to the train and it feels odd not to mention this here explicitly as we do mention it for (bio)diesel trains.

**Comment by michieldenhaan** [comment]
I also find this sentence a bit confusing: "Currently there are not many hydrogen trains in operation, as the expensive infrastructure is not in place." What infrastructure does this refer to? The train infrastructure (train tracks) is cheaper than electric trains as you only need tracks, no power lines. I think that's one of the main reasons to choose hydrogen trains: to use it in (remote) areas where electrification is very expensive (and where currently diesel trains are used). On the other hand you do need energy infrastructure for refueling hydrogen, which currently doesn't exist in most places. However this infrastructure isn't necessarily more expensive than new power infrastructure.
