### ISSUE TITLE
Sustainability share of flex demand options should be double-checked

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3811]
Noticed that some battery nodes have `sustainability_share = 1.0`. I think it would be better to remove this to let ETEngine calculate the sustainability instead based on the electricity inputs (annual mix).

**Comment by mabijkerk** [comment]
Addressed in https://github.com/quintel/etsource/commit/3643a9e9249f73cfa6865213bb644407a07180bd.
