### ISSUE TITLE
CCUS for waste incineration should be added to the investment table

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3817]
The investment table now only includes the waste incinerator and waste CHP without CCS:

![image](https://user-images.githubusercontent.com/5946498/131513289-c52dbcdb-3d76-4e84-8a4c-668014aa2265.png)

**Comment by MartLubben** [comment]
We are maybe removing this investment table: https://github.com/quintel/etmodel/issues/3781

Let's remove deploy September 2021. Don't you think @redekok Roos?

**Comment by redekok** [comment]
Do you know when the investment table will be removed @MartLubben? It's just a minor effort to update it so I wouldn't mind fixing that before the deploy. 

 What are your thought on this @mabijkerk ?

**Comment by mabijkerk** [comment]
As I understood from Mart it is not yet fully clear what will happen with the investment table. It might be decided that it will stay in the model. If @MartLubben agrees and you have time to pick this up @redekok then that would be great!

**Comment by redekok** [comment]
Unfortunately by now I don't have any time to pick this up anymore anytime soon. Perhaps @Charlottevm or @MartLubben could help out here?
