### ISSUE TITLE
Adding CCUS to waste incineration results in zero (or a negative) energy use

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3818]
Adding CCUS to gas CCTGs results in an additional energy use:

![image](https://user-images.githubusercontent.com/5946498/131513715-0f999dc0-eb7a-4f76-ad8f-8725b8c30d70.png)

However, when adding CCUS to waste CHPs, nothings happens:

![image](https://user-images.githubusercontent.com/5946498/131513834-3d750eb0-f667-46c3-b482-0680d3face96.png)

And when adding CCUS to waste incineration, the energy use even decreases? 

![image](https://user-images.githubusercontent.com/5946498/131513952-2c3c762d-7a18-46a1-b76b-3127ce4f9343.png)

**Comment by MartLubben** [comment]
Fixed with: https://github.com/quintel/etsource/pull/2531

![image](https://user-images.githubusercontent.com/33415156/131856569-fd295cf3-a08d-49dd-9a98-3040182d44e2.png)
