### ISSUE TITLE
CCUS for waste incineration should be added to the hourly electricity production

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3828]
CCUS for waste incineration is missing from the hourly electricity production chart. This means that if a waste incinerator is added to the model on beta and CCUS is added to it, the electricity production will show gaps:

![Screenshot 2021-09-07 at 10 12 26](https://user-images.githubusercontent.com/67338510/132309191-1864f107-f3a3-4aae-b5bb-159009976c9f.png)

The plant should therefore be added to the chart. Additionally, because the plant was already missing from two other charts (#3823 and #3817) it would be good to scan whether the plant still needs to be added to other charts.

@MartLubben or @lottevanvlimmeren do you have time to pick this up?

**Comment by MartLubben** [comment]
Solved with: https://github.com/quintel/etmodel/pull/3825#event-5260067060
