### ISSUE TITLE
Kerosene mekko does not show demand in sectors other than transport

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etmodel#3832]
The kerosene mekko does not yet show demand for kerosene in households/buildings/agriculture/industry.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/32056448/132645857-2e208fd4-a110-46d7-aa11-0fb166c399bc.png">

**Comment by redekok** [comment]
@lottevanvlimmeren would you have time to pick this up?
