### ISSUE TITLE
AVI (CHP) CCS missing in some charts

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3833]
1. Profitability of dispatchable power plants: `plant_profitability`
2. Properties of combined heat and power (CHP) plants: `chp_properties`

Relevant node: `energy_chp_supercritical_ccs_waste_mix`

**Comment by mabijkerk** [comment]
The Waste incinerator with CCS also seems to be missing from the `Total costs of electricity production` chart. In a blank NL scenario, when I add a Waste incinerator, it shows up in the chart, but when I set CCS to 100% the plant does not show up. It clearly cannot be selected in the 'Waste' dropdown:

<img src="https://user-images.githubusercontent.com/67338510/133574197-bbbdb1d2-9c1f-4a22-9a6e-d3045ca7fe57.png" width="500">

It seems as though at least the Waste CHP and Waste CHP with CCS are also missing from this chart. It would be good to add those too and check for any other missing plants.
