### ISSUE TITLE
Electricity should not be exported when domestic and foreign electricity prices are both 0

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3836]
In our [discussion on Basecamp](https://3.basecamp.com/3797409/buckets/17880366/messages/4024474037) about the flex-modelling improvements, an edge case was described where both the domestic and the foreign electricity price are 0 euro/MWh. In this case we would expect no electricity to be exported, because the neighbouring country is not likely to want any excess electricity when it has a price of 0 euro/MWh. This led to the addition of a new node attribute, `max_consumption_price`:

> If the max. consumption price is set to zero, the technology will not receive energy from always-on producers. This is to avoid exporting when both the domestic and foreign electricity prices are zero. We'll need to ensure that all other flex technologies have a non-zero price.

However, when I run the model locally on the `price-sensitive-flex` branches, there are occurrences of electricity being exported while both the `merit_order_price_curve` and the `interconnector_1_marginal_cost_curve` are 0.

It also visible in the following charts (scenario is II3050 National governance, with the power-to-gas installed capacity set to 0 MW). In a number of hours at the beginning of the year there clearly is some export, even though both the hourly electricity price and the price of interconnector 1 are 0:
<img width="613" alt="Screenshot 2021-09-13 at 16 46 50" src="https://user-images.githubusercontent.com/67338510/133105315-541acf6c-3ecc-4a24-bbb0-40be0595de40.png">

<img width="624" alt="Screenshot 2021-09-13 at 16 47 12" src="https://user-images.githubusercontent.com/67338510/133105396-a4674713-8835-4dca-88d2-ddb779a6633e.png">

@antw can you reproduce this issue or am I doing something wrong? Did I miss some commits, am I on the wrong branch or is this yet to be implemented?

**Comment by antw** [comment]
This should now be fixed on the ETEngine price-sensitive-flex branch.
