### ISSUE TITLE
Axis of new flex chart does not scale when most series are hidden

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3838]
The new flex chart `hourly_flexibility_electricity` on the `price-sensitive-flex` branch allows the user to deselect series by clicking on them in the legend. This is a useful feature, because users can choose what series they want to see and explore specific questions. For example a user could visualise the relation between power-to-gas and hydrogen power plants:

![Screenshot 2021-09-21 at 10 29 14](https://user-images.githubusercontent.com/67338510/134138184-41fc1290-f936-4e3a-86c8-c05ef084e276.png)

However, when all flexible supply series and the residual load curve are deselected, so only flexible demand technoloies (or negative areas) are selected, the chart axis does not scale properly anymore:

![Screenshot 2021-09-21 at 10 28 42](https://user-images.githubusercontent.com/67338510/134138092-7292fa77-17a7-4f28-9a13-c609b2936e75.png)

@antw could you look into this?

**Comment by antw** [comment]
This should now be fixed on the price-sensitive-flex branch.

<img width="608" alt="Screenshot 2021-09-21 at 10 26 24" src="https://user-images.githubusercontent.com/4383/134146679-47997c86-472c-43c8-875a-b46fd42da110.png">
