### ISSUE TITLE
Should we hide interconnectors with 0 capacity from hourly electricity price chart

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3840]
For a new II3050 National governance scenario on PRO, the `merit_order_price_curve` chart looks like this for a randomly selected week:

![Screenshot 2021-09-21 at 11 05 22](https://user-images.githubusercontent.com/67338510/134143532-d525fbee-094c-4ba5-aae0-d0bb29827945.png)

In this scenario, only interconnector 1 has installed capacity. The other interconnectors do have a standard price, which is why they show up in this chart, but they are otherwise inactive because they have no installed capacity. I think that showing their prices in the chart may be confusing for users, as it suggests that the other interconnectors play a role in the scenario. My preference would be to hide the interconnector prices when they have no installed capacity.

@michieldenhaan what do you think?

**Comment by michieldenhaan** [comment]
Yes I agree! Would make the chart much more readable. @antw is this something that can be done easily?

**Comment by antw** [comment]
As this isn't directly related to the flex project, I've done this on the **master** branches for ETModel and ETSource. They can be cherry-picked to the price-sensitive-flex branches if you need them.
