### ISSUE TITLE
Electricity price should be 0 for curtailment

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3843]
In a new II3050 National governance scenario on the `price-sensitive-flex` branch, when I remove all the installed capacity of flexible demand technologies (including export and batteries), all excess inflexible electricity supply is curtailed:

<img width="500" alt="Screenshot 2021-09-22 at 10 19 38" src="https://user-images.githubusercontent.com/67338510/134308129-3773b166-e0af-4ca3-9055-d62191cab5a2.png">

During these hours, the electricity price should go to 0. Instead, it goes to 64.9254. See the following figure, with the hourly electricity price in dark green:

<img width="500" alt="Screenshot 2021-09-22 at 10 20 37" src="https://user-images.githubusercontent.com/67338510/134308281-30fc1490-d62f-4166-a63f-8c1235da1ad3.png">

@antw could you look into this? The price of 64.9254 euro/MWh exactly aligns with the marginal costs of the 
`energy_chp_supercritical_waste_mix`, which I think is the first power plant in the merit order.

**Comment by mabijkerk** [comment]
A possibly related issue is that when I then add to this scenario: 40.0 GW installed capacity of `energy_hydrogen_flexibility_p2g_electricity` with a WTP of 30 euro/MWh and 1.0 GW installed capacity of `energy_power_nuclear_gen3_uranium_oxide` with marginal costs of 5.37 euro/MWh, the nuclear power plant sets the price when there is an excess of inflexible electricity supply.

In hours 0 to 10 I would expect the power-to-gas unit to set the price at 30 euro/MWh. In hours 10 to 15 I  would expect curtailment to set the price at 0 euro/MWh:

<img width="500" alt="Screenshot 2021-09-22 at 10 40 16" src="https://user-images.githubusercontent.com/67338510/134311354-ca0a355d-d987-4775-98e1-e8220a833bda.png">

As expected in hours 0 to 10 the price is 30 euro/MWh. However, in hours 10 to 15 the nuclear power plant sets the price at 5.37 euro/MWh instead of curtailment:

<img width="500" alt="Screenshot 2021-09-22 at 10 44 18" src="https://user-images.githubusercontent.com/67338510/134312002-867af563-c521-4795-b3c3-1f6f70e025c1.png">

This is strange because the nuclear power plants does not produce in hours 10 to 15. If I query its `electricity_output_curve` this is the result:

<img width="191" alt="Screenshot 2021-09-22 at 10 46 08" src="https://user-images.githubusercontent.com/67338510/134312287-ab55c913-cad6-4a32-9e68-f134b8ca692e.png">

**Comment by antw** [comment]
This should be fixed now.

![Electricity price per hour 1469401 (1)](https://user-images.githubusercontent.com/4383/134365681-064fb320-0ae7-4a01-802d-0e1af9619303.png)
