### ISSUE TITLE
Allow open_chart to place a new chart in chart holder

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3851]
Currently when the `open_chart` function is used in a locales file, for example in `en_supply_ccus` for the `output_of_energy_production_synthetic_kerosene` slider, the chart will open as a pop-up:

<img width="600" alt="Screenshot 2021-09-28 at 12 23 30" src="https://user-images.githubusercontent.com/67338510/135069880-1ac17835-fb1f-4499-8b3d-c89c1ffcfa92.png">

In the updated flex section we want to refer to the new charts that have been added. Preferably, we would be able to specify in the locales file whether these charts should open in a pop-up, in the existing chart holder or in a new chart holder.

**Comment by antw** [comment]
This is now done. A link requires a `data-chart-location="side"` attribute to tell ETModel to load the chart at the side, in the main list of charts. When no `data-chart-location` is provided ETModel will default to showing the zoomed chart as before.

```diff
  <a
      href="#"
      class="open_chart"
      data-chart-key="my_chart_key"
+     data-chart-location="side"
  />
```
