### ISSUE TITLE
Import and export should not be active simultaneously for the same interconnector

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3865]
When I open the [KEV 2020 scenario](https://pro.energytransitionmodel.com/saved_scenarios/9804) on PRO and look at the interconnector, it seems as though it is currently possible for electricity to be imported over an interconnector, while electricity is exported over that same interconnector in the same hour. See the example below, dispatchables for export is enabled in this scenario:

For example, for `energy_interconnector_1_imported_electricity` this is the electricity output curve for the first hours:
<img width="500" alt="Screenshot 2021-11-25 at 13 17 10" src="https://user-images.githubusercontent.com/67338510/143440294-ea3a44d5-b14f-475d-9adf-f1940a242682.png">

Then for `energy_interconnector_1_exported_electricity` this is the electricity input curve for the first hours:
<img width="500" alt="Screenshot 2021-11-25 at 13 18 02" src="https://user-images.githubusercontent.com/67338510/143440410-e72b3d7c-df2e-44e0-8db9-99a88da923ad.png">

Conceptually this does not make sense to me. If NL imports electricity over this interconnector, it should mean that the market clearing price of NL is equal or greater than the price of the interconnector. However, if this is the case, then the interconnector should not be willing to accept exported electricity from NL, since the market clearing price exceeds its willingness-to-pay.

@antw this issue seems to be fixed on the `price-sensitive-flex` branch already. We therefore do not necessarily need to solve it on PRO. It would be valuable if you could determine the cause of this issue on PRO and confirm whether it is fixed on the `price-sensitive-flex` branch.

Notifying @ChaelKruip @michieldenhaan.

**Comment by ChaelKruip** [comment]
@antw what is the status of this?

**Comment by antw** [comment]
> what is the status of this?

I was fixed when we merged the price-sensitive-flex branch earlier this month.

```ruby
V(energy_interconnector_1_imported_electricity, electricity_output_curve)
  .zip(V(energy_interconnector_1_exported_electricity, electricity_input_curve))
  .any? { |(import, export)| !import.round(10).zero? && !export.round(10).zero? }

# => false
```
