### ISSUE TITLE
On Beta Households and Buildings final demand in Mekko charts for final energy demand differs between present and future 

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#3875]
@marliekeverweij and I came across this issue yesterday, while trying to compare the 2019 ETM version for Germany with the 2018 data in the Ambition Tool. 

It concerns the `Final energy demand (energetic)` and `Final energy demand (energetic + non-energetic)` mekko charts on Beta. It is also the case on Live, but for that 2015 Germany dataset the differences are smaller.

The HH final demand number shown on the x-axis doesn't seem to be correct. At least, the numbers in the table behind it add up to a different total. Then I saw that I was comparing 2019 data in the table to the x-axis of the chart in a blank scenario, assuming that there would be no differences in final demand.

It appears there are:

1. In the chart below, the x-axis shows: `2.39 EJ`
2. In the table, 2019 adds up to `2.362 EJ`, whereas 2050 adds up to `2.390 EJ` (see screenshot from Excel below). The screenshot also shows differences for the Buildings sector. 
3. The difference comes from final demand for `Network gas` and `Electricity`, which are not equal (see final screenshot from Excel below).

![image](https://user-images.githubusercontent.com/308563/146547362-d1be8bc3-65e4-4f09-970d-5ed118d2eac3.png)

and 

![image](https://user-images.githubusercontent.com/308563/146548010-1eeb9abb-67f4-4cef-a4f7-6c937377c39e.png)

and 

![image](https://user-images.githubusercontent.com/308563/146548418-3424790d-236e-4ebb-ab75-dc8f3433b517.png)

The differences seem quite large to me and I cannot explain them easily. I know Merit runs for the future, but not the present, but how does this affect demand? Is this due to Fever? Could it be related to the quality of the 2019 dataset, since the 2015 dataset on Live shows much smaller differences?

Assigned @marliekeverweij . Re-assign as needed. Notifying @antw and @ChaelKruip

**Comment by marliekeverweij** [comment]
I just looked into this and it has to do with the different efficiencies of heat pumps in present and future. For the present the efficiencies of hybrid heat pumps are based on the final demands & POTENcIA splits in the present year and for other heat pumps on research data. For the future the heat pump COP is based on the outside temperature curve!

For example see the difference below for hybrid heat pumps in space heating:

**PRESENT**
![Screenshot 2021-12-17 at 14 11 08](https://user-images.githubusercontent.com/32833996/146549714-35e3c833-a6c2-4646-bf6a-0e19141919dd.png)

**FUTURE**
![Screenshot 2021-12-17 at 14 11 13](https://user-images.githubusercontent.com/32833996/146549612-dc9e1d82-ede9-4772-bba6-2611203b534c.png)
!

**Comment by AlexanderWirtz** [comment]
@marliekeverweij does this mean it is sth we cannot solve?

**Comment by marliekeverweij** [comment]
Yes indeed!
