### ISSUE TITLE
The calculation for the present peak load and capacity fails.

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3876]
The calculation for the present peak load and capacity fails.
Resulting in higher costs, because in the future scenario all needed capacity is built:

![image](https://user-images.githubusercontent.com/33415156/146746410-80aeb5ae-29d9-4c8d-bd8f-ab86ca3cdebf.png)

In absence of @michieldenhaan I have assigned you @antw. If it is something that can be fixed by a modeller feel free to re-assign.

**Comment by ChaelKruip** [comment]
@MartLubben please try to state the expected behaviour in the title of the issue as much as possible. This improves clarity. Example: "Table for capacity and peak load should display non-zero capacity for present LV, MV and HV networks." Thanks!
