### ISSUE TITLE
Solar offshore does not respond to "dependent_on"

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3879]
On the `innovations-flex` branch offshore solar PV plants have been added to the model. Because the curves are only researched for the Netherlands, this technology should be available for the `nl` datasets only. To facilitate this `has_offshore_solar = true` is added to the region files, for example in the `nl2019` [region file](https://github.com/quintel/etsource/blob/cf5ee5927da7e59da90453381eb0f2a5d14ff077/datasets/nl2019/nl2019.full.ad#L22).

I then add this attribute to the input element [here](https://github.com/quintel/etmodel/blob/e3dd1791f5d0dd576ecdacfa0179be2008628865/config/interface/input_elements/supply_electricity_renewable_solar_power.yml#L26) as follows:

```
- key: capacity_of_energy_power_solar_pv_offshore
  step_value: 1.0
  unit: MW
  related_node: energy_power_solar_pv_offshore
  position: 2
  dependent_on: has_offshore_solar
  slide_key: supply_electricity_renewable_solar_power
```

The issue is that when I open an nl2019 scenario locally on ETModel, the offshore solar PV plant slider is not visible:
<img width="467" alt="Screenshot 2022-01-04 at 11 22 02" src="https://user-images.githubusercontent.com/67338510/148044711-2c563df7-a696-4749-8e0c-74149f109ace.png">

@antw / @noracato would either of you have time to look into this?

**Comment by noracato** [comment]
I forgot to bump Atlas on Etengine (only did Etsource at the time...) when I added the attribute there. My bad!
