### ISSUE TITLE
Remove investment table from ETModel

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3893]
When I open a new scenario and try to load the investment table, the chart loading is stuck:
<img width="500" alt="Screenshot 2022-01-20 at 13 06 26" src="https://user-images.githubusercontent.com/67338510/150335739-339a91ae-7056-4b62-b003-c864a87b9606.png">

The console shows the following error message:
<img width="629" alt="Screenshot 2022-01-20 at 13 06 46" src="https://user-images.githubusercontent.com/67338510/150335791-33bf9bc6-1a4c-41b2-a120-5946485e22c4.png">

@DorinevanderVlies, do you know if this problem is fixed within the costs project? Is there anyone within the costs project that could pick this issue up? I remember from another issue that it was still up for discussion whether the investment table would stay in the model.

**Comment by DorinevanderVlies** [comment]
This table will be replaced by a data export with all investment and fuel costs. 
As far as I was aware none of the changes of the flex projects have been merged yet.
We can decide not to fix this bug and wait for the changes in the cost project to be merged. I expect the cost project to be finished before the next deploy.

**Comment by mabijkerk** [comment]
Thanks for your input. I think that fixing this bug is not worth the effort if we expect to replace it with an export by the next Deploy (the first week of February).

@ChaelKruip my proposal would be to hide the investment table for the time being. I can then reply to the client who notified us about this issue that it will be replaced soon.

**Comment by mabijkerk** [comment]
FYI: on BETA the underlying missing queries are shown. The investment table fails to load due to changes in the steel sector:

<img width="600" alt="Screenshot 2022-01-20 at 16 26 07" src="https://user-images.githubusercontent.com/67338510/150368717-e7fe7e25-6f47-4818-95ec-a448a4ec2b0d.png">

**Comment by mabijkerk** [comment]
I have temporarily hidden the investment table, as it will be replaced by a data export. After merging the costs project the table can be removed.
