### ISSUE TITLE
Breakdown of electricity costs chart crashes the model

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3894]
Thanks to @MartLubben for spotting this issue. When I try to open the Breakdown of electricity costs chart the model crashes:
```
- cost_of_capital_in_breakdown_electricity_costs/present - undefined method `zero?' for nil:NilClass
- cost_of_capital_in_breakdown_electricity_costs/future - undefined method `zero?' for nil:NilClass
- depreciation_in_breakdown_electricity_costs/present - undefined method `zero?' for nil:NilClass
- depreciation_in_breakdown_electricity_costs/future - undefined method `zero?' for nil:NilClass
- operation_maintenance_cost_in_breakdown_electricity_costs/present - undefined method `*' for nil:NilClass
- operation_maintenance_cost_in_breakdown_electricity_costs/future - undefined method `*' for nil:NilClass
- fuel_cost_in_breakdown_electricity_costs/present - nil can't be coerced into Float
- fuel_cost_in_breakdown_electricity_costs/future - nil can't be coerced into Float
- co2_emission_rights_in_breakdown_electricity_costs/present - nil can't be coerced into Float
- co2_emission_rights_in_breakdown_electricity_costs/future - nil can't be coerced into Float
```

Similar to the question in https://github.com/quintel/etmodel/issues/3893, @DorinevanderVlies do you know if this problem is fixed within the costs project? In contrast to the investment table, I expect this chart to remain in the model. Is there anyone within the costs project that can pick this up?

**Comment by lottevanvlimmeren** [comment]
The same issue occurs with another charts within the cost category: Breakdown of transport fuel costs.

**Comment by DorinevanderVlies** [comment]
> @DorinevanderVlies do you know if this problem is fixed within the costs project?

Unfortunately this problem is not magically fixed within the cost project. These charts will remain. 


@lottevanvlimmeren can you have a look at this? Perhaps we need some help from @antw. 
It might also be relevant for the clean-up of the old method. We should check if this chart still functions after the clean-up.

**Comment by lottevanvlimmeren** [comment]
The charts are based on the old cost calculation method, and are not compatible with the new cost method. It is decided to remove them in the discussion on Basecamp.

**Comment by mabijkerk** [comment]
@lottevanvlimmeren you can link this issue to close in the PR for the costs project.
