### ISSUE TITLE
Wish: add a chart that shows final demand per carrier

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3935]
Pretty often I want to know the final demand per carrier, however the ETM does not show this directly. I think it is a nice improvement to add a chart that shows that.

@quintel/core feel free to reassign yourself if you want to pick this up.

**Comment by mabijkerk** [comment]
This should be relatively straightforward now that there are final demand per carrier queries for the `multi_year_charts` tool: see the folder [per_carrier](https://github.com/quintel/etsource/tree/master/gqueries/modules/multi_year_charts/final_demand_chart/per_carrier).

Though when we add this queries it would be better to move them to the `gqueries > general > final_demand` folder and then reference those queries in the `gqueries > modules > multi_year_charts` folder.

**Comment by mabijkerk** [comment]
I would also **strongly** advocate a similar chart that shows **non energetic** final demand per carrier (and/or per sector).

We currently have no dedicated non energetic final demand charts, only energetic final demand charts and total (energetic + non energetic) final demand charts. This can be quite frustrating if you want to look up a non energetic final demand quickly.

**Comment by MartLubben** [comment]
🎉
