### ISSUE TITLE
Make slide names "prosperity/welvaart" in households and "demand growth/groei van de vraag" consistent

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3936]
The slide names: "prosperity/welvaart" in households and "demand growth/groei van de vraag" in buildings are inconsistent and IMO incorrect (demand does not always grow...). Proposal:
- English: development of demand
- Dutch: vraagontwikkeling

**Comment by mabijkerk** [comment]
@DorinevanderVlies we picked this up in https://github.com/quintel/etmodel/pull/3939 right? Can we close this?
