### ISSUE TITLE
The excel for the technical specs should be downloadable for flow batteries

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3959]
A link should be added from the front-end to ETDataset: https://github.com/quintel/etdataset/blob/master/nodes_source_analyses/energy/energy/energy_flexibility_flow_batteries_electricity.converter.xlsx

See current situation and a correct example for EV batteries below:

Current situation without link:
![image](https://user-images.githubusercontent.com/33415156/166698386-30ecbc1f-9cf7-481f-bc21-cd8415a86204.png)

Current situation of EV batteries with link:
![image](https://user-images.githubusercontent.com/33415156/166699087-cb12729d-f0ea-4ac3-8add-1b7692b97ced.png)

**Comment by marliekeverweij** [comment]
We have to update [this file](https://github.com/quintel/etmodel/blob/master/config/nodes_download_source.yml) to add the Excels to the front-end

The last time we did this was almost a year ago. I think that it would be nice to do this before next deploy, then the Excels will be available for all new technologies: steel technologies, flow batteries, PVT and more!

I do not know how this yml can be automatically updated. @noracato could you take care of this?
