### ISSUE TITLE
Decrease of costs of green gas should not lead to increase of total costs and costs for biogas

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3960]
When I decrease the costs of green gas the scenario costs increase. I find this counter-intuitive and think it is a bug.

### Example:
Scenario for The Netherlands where I changed all network gas to green gas

**Default costs**
![image](https://user-images.githubusercontent.com/19907658/167113264-9046c78d-ab23-40b1-816b-6edf49c8cb04.png)

**Changing costs of green gas to 0**
![image](https://user-images.githubusercontent.com/19907658/167113315-5a39b76f-44b0-4541-ad1e-bb2780cba597.png)

**Changing costs of biogas to 0**
![image](https://user-images.githubusercontent.com/19907658/167113342-94cfac88-3d57-4744-bff7-e46874eaf094.png)

### Some ideas from my side:
The costs query for biomass contains costs for primary carriers 
https://github.com/quintel/etsource/blob/master/gqueries/general/costs/mece_costs/4_energy_carriers/costs_carriers_biomass.gql#L10-L12

It seems that the costs for biogas increase (a lot) when the costs for greengas decrease. The use of biogas increases as well.
As far as I can see energy_biogas_fermentation_wet_biomass, energy_greengas_gasification_wet_biomass and energy_greengas_gasification_dry_biomass are primary cariers. However it seems that biogas is used to make green gas?? If both are primary carriers that should not be the case right?

Is it correct behaviour that the energy use of biogas increases when the costs of green gas decrease? I would not expect this. 

### Assignment
I assigned @marliekeverweij since you were involved in changes to modelling biomass and @antw since I hope you might have some useful ideas about this.
Notifying @noracato with whom I had a first look at this issue
I posted this issue in ETModel as I am not sure whether it is a bug on ETEngine or on ETSource.

**Comment by marliekeverweij** [comment]
> It seems that the costs for biogas increase (a lot) when the costs for greengas decrease. The use of biogas increases as well. As far as I can see energy_biogas_fermentation_wet_biomass, energy_greengas_gasification_wet_biomass and energy_greengas_gasification_dry_biomass are primary cariers. 

Yes, _biogas_ produced by `energy_biogas_fermentation_wet_biomass` and _green gas_ produced by `energy_greengas_gasification_wet_biomass`& `energy_greengas_gasification_dry_biomass` are both primary carriers.

> However it seems that biogas is used to make green gas?? If both are primary carriers that should not be the case right?

In your scenario all green gas is made through anaerobic digestion / fermentation, so first biogas is produced and this is upgraded to green gas. The biogas that is used to make this green gas is the primary carrier and these costs are included in the total costs. 

> Is it correct behaviour that the energy use of biogas increases when the costs of green gas decrease? I would not expect this.

Yes I think it's correct behaviour: 1. decreasing the costs of green gas -> 2. lowers the marginal costs of gas power plants -> 3. increases the total green gas demand -> 4. increases the biogas demand -> 5. increases the biogas costs -> 6. increases the total costs

The only thing I am not sure about is the marginal costs: is it correct that the green gas price is used here, even though it's not the primary carrier? I am not sure who to ask this question to!
