### ISSUE TITLE
Households final demand in future year is higher than base year for blank scenario

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3963]
In a blank scenario on ETModel pro, for example nl2019, the households final demand in the future year exceeds the final demand in the base year. The difference seems to be caused by ambient heat, network gas, and electricity, for hot water and heat. This means that it is likely caused by a (hybrid) heat pump:

<img width="622" alt="Screenshot 2022-05-17 at 10 26 06" src="https://user-images.githubusercontent.com/67338510/168765882-8ca0f8bc-3ade-44bf-83b5-7a20588c5dfc.png">

<img width="614" alt="Screenshot 2022-05-17 at 10 27 43" src="https://user-images.githubusercontent.com/67338510/168766219-f21f27a9-acb5-4019-bddb-2184999a33a8.png">

**Comment by mabijkerk** [comment]
The difference occurs for the hybrid heat pump and the heat pump (air), both in hot water and space heating:

- `households_space_heater_heatpump_air_water_electricity`
- `households_space_heater_hybrid_heatpump_air_water_electricity`
- `households_water_heater_hybrid_heatpump_air_water_electricity`
- `households_water_heater_heatpump_air_water_electricity`

For example, for households_space_heater_hybrid_heatpump_air_water_electricity the present and future:
<img width="1477" alt="Screenshot 2022-05-17 at 10 33 53" src="https://user-images.githubusercontent.com/67338510/168767544-5c4aede3-a96b-4fb8-9229-a2de0aa45700.png">

<img width="1474" alt="Screenshot 2022-05-17 at 10 34 14" src="https://user-images.githubusercontent.com/67338510/168767602-073efa51-3e38-455f-9d8e-12c4337e2df0.png">

The useable heat output exceeds 100% in the base year, and all the input flows change for the future year.

**Comment by MartLubben** [comment]
I think it would be a better discussion to talk about what diffs do we thinks are acceptable and how many digits do we want to show?

I we round it to 224 PJ, then we do not have a diff. May be I am 'cursing in the church', but in my opinion we should not focus on these details so much and we should prevent users from getting distracted by minor diffs too.

**Comment by mabijkerk** [comment]
I agree that it is a good point of discussion @MartLubben, especially about how many digits we want to present to the users. 

In this particular case however, I don't see a **conceptual** reason yet for there to be any change to the final demand at all: generally in blank scenario, final demand should be unchanged for the future year. This would mean that there likely is a bug in **implementation**, which I do think we should correct.

**Comment by mabijkerk** [comment]
The fact that there can be a difference between the base year and the future year is a feature. For the base year we determine a fixed split between ambient, electricity and (for hybrid) network gas. For the future year we calculate this split dynamically based on the outside temperature.

The only strange thing still is that `households_space_heater_hybrid_heatpump_air_water_electricity` has an output > 100% in the base year and the `households_water_heater_hybrid_hydrogen_heatpump_air_water_electricity` has a loss in the base year which is no longer present in the future year.
