### ISSUE TITLE
It should be possible to modify profiles for EU27 2019 dataset on beta

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3976]
At the moment this functionality does not appear. Do you know what's going on @antw ?

![Screenshot 2022-06-01 at 12 27 21](https://user-images.githubusercontent.com/32833996/171384117-90c886a0-28f6-44fd-9b6e-b5f2365d960d.png)

**Comment by mabijkerk** [comment]
This issue does not seem to occur on beta for me, see screenshot below. Maybe @antw already fixed or it is a local issue for your computer @marliekeverweij? Can we close this issue?

<img width="600" alt="Screenshot 2022-06-07 at 09 28 52" src="https://user-images.githubusercontent.com/67338510/172321544-0641c48c-681c-45df-9436-e615fd247ff9.png">

**Comment by marliekeverweij** [comment]
It still occurs on mine. I use Firefox, maybe the issue is only in this browser?

<img width="830" alt="Screenshot 2022-06-07 at 11 00 07" src="https://user-images.githubusercontent.com/32833996/172340681-e9cf2876-15c9-4183-983b-a9a53b9b8144.png">
