### ISSUE TITLE
Uploading hourly curves in the import/export should be explained more clearly

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3981]
The current description (at the interconnector section, see screenshot below) does not clearly state how users should upload new curves. This is also related to https://github.com/quintel/documentation/issues/119

<img width="471" alt="Screenshot 2022-06-16 at 14 43 47" src="https://user-images.githubusercontent.com/67338510/174072293-c6f77b6c-3371-470d-93c2-c5cf70573892.png">

**Comment by mabijkerk** [comment]
I think the most commonly used feature is to upload a price curve. Currently the export availability is shown first.

@antw is there a way to show the price curve first in the interconnector dropdown?

<img width="475" alt="Screenshot 2022-07-07 at 13 24 32" src="https://user-images.githubusercontent.com/67338510/177762428-0805c721-1f56-45c3-b98a-c1191c4920ac.png">

**Comment by antw** [comment]
The curves are sorted alphabetically. Currently, there's no option to apply a custom odrer.
