### ISSUE TITLE
Coal gas power plants should have a separate slide

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3986]
It may not be clear for users where coal gas power production is coming from, and especially why they cannot change it by setting the gas power plant sliders (see screenshot below).

The proposal is to add a slide for coal gas power plants to the[ electricity section](https://pro.energytransitionmodel.com/scenario/supply/electricity/coal-plants). Instead of sliders, this slide would explain how the coal gas power plants are modelled and link to the [steel production](https://pro.energytransitionmodel.com/scenario/demand/industry/steel) slide and the coal gas slide in the [CCUS section](https://pro.energytransitionmodel.com/scenario/emissions/ccus/coal-gases-from-blast-furnaces-steel).

<img width="1126" alt="Screenshot 2022-07-07 at 11 42 38" src="https://user-images.githubusercontent.com/67338510/177744017-ccfb569d-b166-47e5-be9e-e32d8d36a30a.png">

Notifying @Charlottevm

**Comment by mabijkerk** [comment]
@marliekeverweij @DorinevanderVlies how do you feel about this enhancement?

**Comment by marliekeverweij** [comment]
Good idea! That's indeed more clear

**Comment by mabijkerk** [comment]
Instead of adding a new slide that references the [Coal gases from blast furnaces (steel)](https://pro.energytransitionmodel.com/scenario/emissions/ccus/coal-gases-from-blast-furnaces-steel) slide (see screenshot below), another option is to move the existing slide from `Emissions > CCUS` to `Supply > Electricity`.

<img width="1090" alt="Screenshot 2022-11-07 at 11 20 57" src="https://user-images.githubusercontent.com/67338510/200286462-2816fdcf-7481-46ca-ad25-8897f7e73ad3.png">


**Pro**: we don't add a new slide without actionable content, but keep the same number of slides and actually allow the user to choose whether to produce electricity with the coal gases in the electricity section.

**Con**: coal gas use might be too advanced for the `Supply > Electricity` section.

I would be in favour of moving the slide. What do you think @Charlottevm / @DorinevanderVlies / @marliekeverweij?

**Comment by DorinevanderVlies** [comment]
> I would be in favor of moving the slide. What do you think @Charlottevm / @DorinevanderVlies / @marliekeverweij?

Sounds good. However I do think that the title of the slide is pretty far out of line with the other slides in that section.
How about changing that to: "Plants using coal gases (from steel sector)"?

Furthermore I would like to add a technology specifications to the "?". Now I have to open the merit order table to be able to see the installed capacity.
