### ISSUE TITLE
Average air temperature slider should be set when uploading different air_temperature curve

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#4009]
Last week we made it possible to set a custom `air_temperature` curve through [the front-end ](https://pro.energytransitionmodel.com/scenario/flexibility/curve_upload/upload-curves).

When uploading this new curve, it would be logical that then the yearly heating / cooling demand would automatically scale. Colder year -> more heating demand, less cooling demand and vice versa.

However, this is not the case: when uploading a different `air_temperature` curve, the yearly demands stay the same. 

Therefore, we would like to implement that when uploading a different `air_temperature` curve, that then automatically the ["outdoor temperature" slider ](https://pro.energytransitionmodel.com/scenario/flexibility/flexibility_weather/extreme-weather-conditions) is set. This slider scales the yearly heating / cooling demand. 

For this we would need to calculate:

1. The average outdoor temperature in the present year
2. The average outdoor temperature of the new curve
3. With 1 + 2 we can calculated the delta and with this value we can update the outdoor temperature slider ([`flexibility_outdoor_temperature`](https://github.com/quintel/etsource/blob/master/inputs/flexibility/weather/flexibility_outdoor_temperature.ad))

@antw could you have a look at this?

Notifying @robcalon

**Comment by ChaelKruip** [comment]
Excellent suggestion to improve this feature!

One thing that comes to mind is the concept of '[degree days](https://en.wikipedia.org/wiki/Degree_day)'. This is a useful measure for the heating (or cooling) demand in a given year. It is used a lot so some users might compare the (increase) with this measure. I would suggest looking into a solution that is either based on, or consistent with degree days.

**Comment by antw** [comment]
@marliekeverweij I've sent this to beta so you can test it.

I haven't done anything with degree days yet. I'm not sure we have enough information in the model to calculate degree days for the default and user curves since they depend on knowing the wind speed. I'm open to ideas.

For now, we calculate the average temperature from the default and user curves and use the difference to set the slider value.

**Comment by marliekeverweij** [comment]
Thanks @antw for your fix!

I have just tested it and it works! I have tested it using the air temperature curves of the weather years and the correct temperature difference is calculated for the outdoor temperature slider.

<img width="409" alt="Screenshot 2022-09-21 at 16 28 38" src="https://user-images.githubusercontent.com/32833996/191531779-41192c64-548b-4560-ac5e-ca6d36f86186.png">
