### ISSUE TITLE
Horizon of ETM scenarios should be extended beyond 2050

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#4013]
When the ETM was created, 2050 was farther away than it is now. For now, 2050 remains the most import 'target year' for energy policy goals, but I don't think it will remain so forever. 

1. What will it take to extend the horizon?
2. Who among our clients would be most interested in paying for this?

**Comment by AlexanderWirtz** [comment]
I would love to know how much effort this would be. I hear this ever more often in scenario workshops. @marliekeverweij and @mabijkerk do you have any idea?

**Comment by mabijkerk** [comment]
I can't imagine it would take a lot of work. I suspect it might be as simple as expanding the range in the scenario year selection dropdown: the ETM should be able to calculate any future year. I think @antw would actually be the right person to ask this question.

**Comment by AlexanderWirtz** [comment]
> It is this easy.

Great. 
I suggest letting the future year run until at least 2070. Does this mean that users can automatically select 2069 via the `Present - other` option in the drop down?
