### ISSUE TITLE
Should ambient be included in "Renewability" queries

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#4021]
**Background**
The dashboard item 'Renewability' has an accompanying chart that shows how the dashboard value is calculated. This is the chart 'Renewability of final demand', which shows the share of fossil and renewable carriers in the total final demand, here for a blank `nl2019` scenario:

<img width="500" alt="Screenshot 2022-10-11 at 16 56 47" src="https://user-images.githubusercontent.com/67338510/195126265-caa5648d-4ebe-488a-843f-bd11d8a75f80.png">

The total final demand also includes the ambient heat pumped by heat pumps and the geothermal own use, which you can see in the query `final_demand_of_ambient_in_renewability`:

<details>

```ruby
- query =
    100 * SUM(
        V(INTERSECTION(G(final_demand_group),USE(energetic)), "sustainability_share * supply_of_ambient_heat"),
        V(INTERSECTION(G(final_demand_group),USE(energetic)), "sustainability_share * supply_of_ambient_cold"),
        Q(ambient_heat_pumped_by_heat_pumps)
    ) / 
    SUM(
        V(INTERSECTION(G(final_demand_group),USE(energetic)), demand),
        Q(ambient_heat_pumped_by_heat_pumps),
        Q(geothermal_own_use_in_sectors)
    )
```

</details>

**Problem**
The first issue is that this dashboard item and accompanying chart explicitly take ambient heat and cold into account, even though these products are excluded from the final and primary demand mekkos.

The second issue is that for the share of ambient in renewability, both heat and cold are taken into account, while the `ambient_heat_pumped_by_heat_pumps` only takes heat into account:

<details>

```ruby
- query =
    V(
    	households_water_heater_heatpump_ground_water_electricity,
    	households_water_heater_heatpump_air_water_electricity,
    	households_space_heater_heatpump_air_water_electricity,
    	households_space_heater_heatpump_ground_water_electricity,
    	agriculture_heatpump_water_water_ts_electricity,
    	agriculture_geothermal,
    	households_space_heater_hybrid_heatpump_air_water_electricity,
        households_water_heater_hybrid_heatpump_air_water_electricity,
    	buildings_space_heater_heatpump_air_water_network_gas,
    	buildings_space_heater_collective_heatpump_water_water_ts_electricity,
        industry_chemicals_other_heatpump_water_water_electricity,
    	input_of_ambient_heat
    ).sum
```

</details>

The third issue is that this query is outdated: its latest update stems from 2017. Since then a number of heat pumps have been added.

**Solution**
The first issue should be tackled in #3641, where it is already discussed.

For second and third issue I propose to update the `ambient_heat_pumped_by_heat_pumps` query so that it is dynamic and includes both ambient heat and cold. I propose to use the following filters, as they seem to produce the desired results:
```ruby
FILTER(G(application_group),"ambient_heat_input_conversion > 0")

FILTER(G(application_group),"ambient_cold_input_conversion > 0")
```

@marliekeverweij and @DorinevanderVlies I'm interested to hear your opinion on this. I feel like it is quite a relevant issue since it affects one of the main dashboard items.

**Comment by DorinevanderVlies** [comment]
> For second and third issue I propose to update the ambient_heat_pumped_by_heat_pumps query so that it is dynamic and includes both ambient heat and cold. 

Sounds good. I have a feeling that @AlexanderWirtz might have an opinion about this.

> I feel like it is quite a relevant issue since it affects one of the main dashboard items.

More general, I doubt whether this dashboard item is often used. I haven't used it for years myself.

**Comment by mabijkerk** [comment]
> More general, I doubt whether this dashboard item is often used

I'm not sure to which extent it is used at the moment, but was at least part of the 20-20-20 climate goals of the EU. The focus now seems to be mainly on CO2 emissions reduction. I can imagine though that a certain level of renewability is relevant KPI for scenario-makers.

**Comment by mabijkerk** [comment]
I've addressed the third issue and updated the `ambient_heat_pumped_by_heat_pumps` query to use a dynamic group instead of hardcoded nodes. 

**Open issue**
This still leaves the main question: should ambient heat, ambient cold and geothermal be included in the renewability queries, which means that we implicitly count them as final demand.

If so, then a query ambient_cold_pumped_by_heat_pumps should be added to the renewability queries, since they currently only include geothermal and ambient heat. See e.g. for hydrogen:

```ruby
- query =
    100 * SUM(
        V(INTERSECTION(G(final_demand_group),USE(energetic)), "(1.0 - sustainability_share) * supply_of_hydrogen")
    ) / 
    SUM(
        V(INTERSECTION(G(final_demand_group),USE(energetic)), demand),
        Q(ambient_heat_pumped_by_heat_pumps),
        Q(geothermal_own_use_in_sectors)
    )
```

**Comment by mabijkerk** [comment]
I have copied the remaining open issue to #3641, so that it can be picked up in a single issue. I will therefore close this issue.
