### ISSUE TITLE
Hiding sliders of non-existent housing categories?

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etmodel#4025]
In the UK there are no terraced houses and corner houses (as there is no data availbale for these types of houses). This confuses users when they use insulation sliders for these types of houses but see nothing happening in the graph (as there was no energy demand to begin with). 

There are 3 potential solutions (feel free to add more):
1. Hide the sliders
2. Decrease the types of housing 
3. Research better / new data for EU countries when it comes to housing types

Long term I would suggest going for the second option because data for this is hard to find or inconsistent (what do you define as a 'detached' home?) and mostly based on the dutch way of defining the housing stock. However, there might be good reasons to keep it this way (@marliekeverweij @MartLubben ?).
Short-term I would go for option 1. as this might remove any confusion around the topic for now, is this easily done @antw?. 

Let me know what you think @marliekeverweij (from a modelling perspective) @MartLubben (from a local perspective) @antw (from a technical perspective)!

<img width="1437" alt="afbeelding" src="https://user-images.githubusercontent.com/74194356/199449380-cebd4d0f-6678-4fb4-b7f0-4370dfe6d5af.png">

<img width="633" alt="afbeelding" src="https://user-images.githubusercontent.com/74194356/199449790-6fed4f99-a0ae-4bf6-9ae3-1fec8d6ffaa4.png">

**Comment by antw** [comment]
As long as the default values for these sliders are 0, it would be possible to add fields to the dataset `has_corner_houses` and `has_terraced_houses` and configure it in the front-end like we do with [other `has_...` features](https://github.com/quintel/atlas/blob/791993e98ea67072692f2de7fff1042e69daf965/lib/atlas/dataset.rb#L20-L42).

However, this is only a thing in ETModel; as far as I know, `has_...` isn't supported in the dataset manager at this time.
