### ISSUE TITLE
Adjust position of free space when scrolling up

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#4101]
If I am at the top of the page on LinkedIn, scrolling further up will cause some free space to show **between** the content and the navbar. In the ETM, the same action will cause free space to show **above** the navbar. See the difference in the screen recording below.

It would be cool if we could implement a similar feature as LinkedIn in the ETM. What do you think @noracato @Charlottevm?

https://user-images.githubusercontent.com/67338510/231139298-f0f6a7f3-d93b-48c0-8f7c-9ad1fabbb5be.mov

**Comment by noracato** [comment]
In linkedin the header is `fixed` which means that when you scroll it stays fixed in place: the content scrolls but the header stays. Is that also what we want? The on the homepage the blocks will scroll under the header.


https://user-images.githubusercontent.com/14875123/231144824-a7edacf4-3889-4ec3-89fc-cbe0c1098799.mov

**Comment by noracato** [comment]
And another consequence on the `play` pages:

https://user-images.githubusercontent.com/14875123/231146576-ad8ecdd5-55d9-4fa0-9b8d-713f90035da5.mov

**Comment by mabijkerk** [comment]
> In linkedin the header is fixed which means that when you scroll it stays fixed in place: the content scrolls but the header stays. Is that also what we want?

As far as I am concerned this looks very good!

> And another consequence on the play pages:

The same goes for this. I would be in favour of changing it to your examples! I am curious to know what you think yourself @noracato but also what @Charlottevm and @redekok think.

**Comment by noracato** [comment]
If we also fixate the sidebar menu, then #4100 is tackled as well. I think this looks more neat than what we had! Nice ideas @mabijkerk!

It's only 3 extra lines of css so I can fix it whenever I find 5 minutes between meetings 🙂

**Comment by redekok** [comment]
Yes, I like it a lot! Looks much neater this way 😄
