### ISSUE TITLE
When there are 0.0% vans in startyear it is not possible to 'add' them

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etmodel#4107]
Example: In the dataset for Aarhus no vans were added. If you change the applications of freight transport from trucks to vans, nothing shows up in the graph even thought the energy demand for trucks declines.

<img width="1111" alt="afbeelding" src="https://user-images.githubusercontent.com/74194356/235636349-da2d1dc2-6e80-43f1-997a-5a3677e5eda5.png">

**Comment by mabijkerk** [comment]
@Charlottevm well-spotted! This is the same issue we have encountered before in the industry: https://github.com/quintel/etlocal/issues/378

I think the same solution would apply here:

> This should be fixed by setting one slider to 100% by default when the sub sector demand is 0. For the steel industry for example the blast furnace slider is set to 100% if there is no steel production.

We would therefore have to make sure that **for each transport technology** one of the shares falls back to 100%. Below you can see for Aarhus that all the shares are 0%. For Slovakia the same issue occurs for inland shipping.

<img width="500" alt="Screenshot 2023-05-02 at 14 21 23" src="https://user-images.githubusercontent.com/67338510/235664617-2712167c-604b-444c-aacd-f6a31d7a0bab.png">
