### ISSUE TITLE
Non-energetic energy-use in 'other' industry sectors cannot be changed

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etmodel#4116]
Currently users are unable to influence **non-energetic energy demand** attributed to the **other industry** sector. This means that, for example, if there is a demand for coal in the present users are unable to change or remove this in the future.

To resolve this we could 'easily' duplicate the sliders which influence energetic demand for non-energetic demand.

What are your thoughts @mabijkerk & @ChaelKruip ?

**Comment by mabijkerk** [comment]
I'm not sure what you mean by 'duplicate'. Adding inputs that can be used to adjust the non energetic demand in the other industry seem like a good idea to me.

**Comment by Charlottevm** [comment]
@mabijkerk, I guess there are two options: 

1. we can either keep the current sliders but make sure they influence the energetic _and_ non-energetic demand 
2. or create ('duplicate') similar sliders which influence the nonenergetic demand seperately

![afbeelding](https://github.com/quintel/etmodel/assets/74194356/04f22ad4-d7a4-46bf-9601-7caeb003e027)

**Comment by mabijkerk** [comment]
Adding them to the existing sliders does allow us to keep the front-end a bit more clean. However, changing the sliders will also change all existing scenarios and users may not have had the intention to change the non-energetic demand.

**Comment by KoenvanB** [comment]
To do:

- split size slider into size slider for energetic and non-energetic. Use use:energetic as intersection property
- add input in etsource for non-energetic sliders
- add accordeon + sliders including texts and translations in etmodel

@MartLubben @mabijkerk

**Comment by mabijkerk** [comment]
Overview of work to be done:

- [ ] Add inputs for non energetic shares on ETSource @KoenvanB 
- [ ] Split input of sector size into energetic sector size and non energetic sector size (new on ETSource @KoenvanB 
- [ ] Add inputs to ETModel, add translations and groups @KoenvanB 
- [ ] Add a migration that duplicates the value for sector size of the old input to the new inputs for energetic sector size and non energetic sector size on ETEngine @noracato
