### ISSUE TITLE
Add chart that shows energy demand per carrier for buildings appliances

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#4120]
In the buildings sector, there can be energy demand for appliances for different carriers than electricity. For example in France, for network gas:

![Screenshot 2023-06-02 at 10 02 50](https://github.com/quintel/etmodel/assets/67338510/288a0944-32d3-4f7e-a060-7d4e2802d6b4)

However, the chart that is shown at the appliances section in buildings is the chart "Electricity demand in buildings". There is no chart that shows the energetic final demand **per carrier** in buildings, let alone the energetic final demand **per carrier for appliances**. This is not transparent, as it is difficult for users to see that there is energy demand for appliances from other carriers. I therefore propose to add the latter chart. What do you think @Charlottevm / @DorinevanderVlies?

**Comment by DorinevanderVlies** [comment]
Good catch.

>There is no chart that shows the energetic final demand per carrier in buildings
Indirectly there is. The chart `Final energy demand (energetic)` provides this information.

> `energetic final demand per carrier for appliances` I therefore propose to add the latter chart. 

I agree. For Just to check: for The Netherlands this will just show electricity and the user will not be able to change the share of electricity vs other carriers, just the amount, right?

**Comment by mabijkerk** [comment]
> for The Netherlands this will just show electricity and the user will not be able to change the share of electricity vs other carriers, just the amount, right?

The answer to your first question is no: in the `nl2019` dataset, some coal, oil and gas is used by appliances in the buildings sector (see screenshot below).

The answer to your second question is yes: this is precisely what inspired me to investigate this topic. An ENTSO member attempted to reduce network gas demand in the buildings sector but found it difficult to fully remove it, because for appliances only the overall demand efficiency can be changed. I have added the suggestion to include more sliders in this section to the list of potential improvements for ENTSO.

![Screenshot 2023-06-02 at 11 29 47](https://github.com/quintel/etmodel/assets/67338510/ce1e313a-fa0c-453d-9893-39d666ff53bd)

**Comment by mabijkerk** [comment]
Solved in https://github.com/quintel/etmodel/pull/4178.
