### ISSUE TITLE
Restyle and rename "Reset scenario" button and popup

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#4129]
Recently, the pop-up displayed when clicking the "reset" and "uncouple" button has been visually improved. Minor improvement could be that the size of the pop-up should depend on the text size. It seems to me that the pop-up currently is a fixed element that is used for both "reset" and "uncouple". This however means that there is some whitespace for "reset", since it has less text than "uncouple". See screenshot below:

![Screenshot 2023-06-29 at 10 00 26](https://github.com/quintel/etmodel/assets/67338510/e1bad6b9-4b14-4fc5-8996-83093069a7c0)

The larger suggested enhancement is to trace all old style pop-ups in the model and replace them with the new style. I think it looks much more professional and therefore adds a lot of value for the ETM! For example when reverting a curve, I still get:

![Screenshot 2023-06-29 at 10 02 54](https://github.com/quintel/etmodel/assets/67338510/4f211599-5098-4fbf-834c-7774a2b86d9e)

There may be more old style pop-ups throughout the model. Let me know what you think @noracato !

**Comment by Charlottevm** [comment]
Nice suggestions. For me the "Revert unsaved changes" is clear! 

The text in the current pop-up is also not clear to me (what are 'default' settings? etc.), I think it should also be along the lines of "are you sure you want to revert all unsaved changes? You will lose any unsaved changes."
