### ISSUE TITLE
Add a combined downloads for each of the three heat networks

### ISSUE THREAD

**Issue by noracato** [quintel/etmodel#4131]
The download of the heat network curves should be combined into one large one for HT, MT and LT. Sorted by network.

**Comment by mabijkerk** [comment]
As discussed I would propose one large download. The download should have a clear structure though: each temperature level should clearly separated e.g. LT demand and supply, then MT demand and supply and then HT demand and supply.

**Comment by noracato** [comment]
Done on branch `heat-2023`, will be merged on completion of full project
