### ISSUE TITLE
Maximum for geothermal and import of heat should be increased

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#4134]
For a municipalities the maximum value of geothermal is too low for the potential production:

1. Maximum is 34MW while the potential is 200 MW. The current maximum is also not sufficient for the total heat demand in the municipality when al households and buildings use the heat network:

<img width="613" alt="image" src="https://github.com/quintel/etmodel/assets/33415156/579384b0-f804-4e37-90df-694fab263f77">

2. The imported heat is too low for a municipality. I wanted to import 3600 TJ, but the maximum is 1600 TJ. 

<img width="613" alt="image" src="https://github.com/quintel/etmodel/assets/33415156/2d20d700-be82-4d40-944b-32f34147fb84">

**Comment by MartLubben** [comment]
> Power plants follow a different logic. Any power plant is able to produce twice the electricity consumed in the base year. We could adopt the same logic for heat producers and set the inputs to twice the heat consumed. What do you think @MartLubben?

That would be a better logic, because heat sources as like power plants can produce for area's outside their boundaries.

**Comment by mabijkerk** [comment]
> heat sources just like power plants are able to produce for area's outside their boundaries

At the moment this is not true in the ETM though right? There is no export slider for heat.

**Comment by MartLubben** [comment]
True, but you it will allow users model te surplus to show that it is more than enough for an area.
