### ISSUE TITLE
Industrial steam (heat) network sliders are mistranslated as 'District heating'

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#4142]
The Dutch term 'warmtenet' is already not ideal as it is actually a 'industrieel stoomnet' or 'industrial steam network'. 'District heating' is something that doesn't really apply to industry.

I suggest we switch to 'stoomnet' and 'steam network' as translations. No need to change the keys in the graph.  

notifying @mabijkerk as project manager of the project to improve heat modelling.

**Comment by mabijkerk** [comment]
Well-spotted @AlexanderWirtz. I've made the changes on the `heat-2023` branches and fix relevant links.
