### ISSUE TITLE
Monthly & yearly charts showcase differences

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etmodel#4143]
The visual representation of yearly hourly curves in the ETM is quite different from the monthly representation of curves.
It seems like the yearly hourly representation showcases daily averages whilst the monthly or weekly representation of hourly curves is more precise.
This can lead to confusion for users.

_For example:_ for heat grids the back-up burner visually to exceed the yearly demand (which is not possible given it is a back-up burner) whilst on a monthly or weekly level it all adds up again. 

<img width="647" alt="afbeelding" src="https://github.com/quintel/etmodel/assets/74194356/72d9aeb4-88ce-443b-8ecc-74094bb6bc69">

<img width="621" alt="afbeelding" src="https://github.com/quintel/etmodel/assets/74194356/d509164a-7488-4075-96d0-18c4225bcbc7">

Notifying @redekok & @mabijkerk 

Do you know if there is a possible solution for this @noracato ?

**Comment by mabijkerk** [comment]
@Charlottevm a similar issue has been noted in #3901. As far as I can tell (which you can read in the issue description), there is no single solution to this issue. I propose you add this example to #3901, after which we can update the issue title to fit this more generic issue with yearly curve visualisation.
