### ISSUE TITLE
Update logo in energy mix factsheet

### ISSUE THREAD

**Issue by noracato** [quintel/etmodel#4147]
The energy mix factsheet still shows the old Quintel logo. Let's update this!

<img width="621" alt="Screenshot 2023-10-03 at 11 26 26" src="https://github.com/quintel/etmodel/assets/14875123/abffa5bf-6b21-4dc5-b2df-dfcd2b73a888">

**Comment by mabijkerk** [comment]
@kaskranenburgQ could you pick this up?

**Comment by mabijkerk** [comment]
Closed in https://github.com/quintel/etmodel/pull/4175
