### ISSUE TITLE
Represent slider groups as table view

### ISSUE THREAD

**Issue by noracato** [quintel/etmodel#4149]
## Background: slider groups
Some inputs in the ETM are grouped together in what we call `share_groups` or `slider_groups`. This means the inputs in this groups represent percentages, that should together sum to 100%. For instance in the image below.

<img width="463" alt="Screenshot 2023-10-05 at 15 57 04" src="https://github.com/quintel/etmodel/assets/14875123/a9f310e0-7e2e-40c7-a26c-b6260e8cd0e4">

When you pull one slider, the others are [automatically autobalanced by ETModel](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/models/input_element_balancer.js). Then an update is sent to the engine, like we do for any input. Up until now all slider groups were always represented in this way.

## New type of view for slider groups
For the heat improvements project we are looking at a new way of adjusting the inputs in a group: a table view.

We have 5 different housing types and we will have 6 different gradations of insulation: from low to high insulation.
Normally that would mean 5 sliders groups with 6 sliders each: the percentage of apartments that have low insulation, medium-low, medium, etc.

 Instead of showing these as sliders, we would now like to show them as input fields in a table.

<img width="1110" alt="Screenshot 2023-10-05 at 16 27 46" src="https://github.com/quintel/etmodel/assets/14875123/33766ba0-29b1-40a1-814e-ca17b7f16006">

Above you can see an example in Dutch of how such a table for insulation types would look like. Each cell of the table should be adjustable by the user (similar to how we fill in our planning in the internal project tool - see below).

<img width="640" alt="Screenshot 2023-10-05 at 19 17 12" src="https://github.com/quintel/etmodel/assets/14875123/0c0f0c57-f5f3-488b-936c-dde7b5d171d7">

The looks of the final table are probably a mix of the two pictures.

### Requirements
When a user updates a cell in the table:
- The cells in the same row are autobalanced in the same way as a 'normal' share group would
- The input is sent in an update to ETEngine in the same way as happens now for share groups

The table should have:
- A configuration similar to the share groups in the interface config files. You can choose to either
  - Add a new attribute to make this group show as a table (mind that even though these files are loaded through [YModel](https://github.com/quintel/etmodel/blob/master/lib/ymodel/base.rb) and not ActiveRecord specifying things about default is almost the same); or
  - Hard-code this specific share group to grab the correct table view (we do this from time to time, it's very OK and will make it easier)
  - => Discuss with @redekok if a table view like this is something we will reuse in the future
- A new view in the [slides folder](https://github.com/quintel/etmodel/tree/master/app/views/scenarios/slides) and javascripts containing
   - Table headers and their translations (discuss with @redekok about if the headers should contain gqueries for the numbers as well)
   - Support for this big arrow on top (discuss with @redekok)
   - A way to fit all of this in our small slides. I think that that could be a challenge. Draw some mockups and discuss with @redekok 

### Challenges
The balancer part of the input elements happens in the 'old' javascript, so you will probably be stuck to that part of the app. However, you will find that most custom inputs we currently have, like the interconnectors are part of the 'new' javascript. You will need to find your way around this, but remember it is **NOT** the point of this issue to change or port the current balancing.

### Inspiration
- The interconnector input: [view](https://github.com/quintel/etmodel/blob/master/app/views/scenarios/slides/_interconnector_curves_upload.html.haml), ['new' javascript](https://github.com/quintel/etmodel/blob/master/app/javascript/views/MultiCurveChooserView.js), [config](https://github.com/quintel/etmodel/blob/master/config/interface/input_elements/flexibility_electricity_import_export_interconnectivity.yml)
- The internal projects tool
- The powerpoint @redekok can supply with background info

---

Discuss time-budget with @redekok, estimation: 3 days

**Comment by redekok** [comment]
Thanks for the detailed elaboration on this issue @noracato! We've just discussed that this issue will be on hold until we've discussed the priorities with the client tomorrow morning. Also notifying @thomas-qah.

**Comment by redekok** [comment]
Closing since not relevant anymore
