### ISSUE TITLE
Create expandable 'expert' inputs

### ISSUE THREAD

**Issue by noracato** [quintel/etmodel#4150]
# DISCUSS FURTHER  ON MONDAY ON IF WE HIDE OR DISABLE

For some inputs we would like to create a way to show only _general_ inputs on a slide, until a user specifies they would like to see the _expert_ inputs instead. Then the general inputs should disappear and the expert ones appear. 

## Looks

Currently we have features in the front-end that disable inputs when activated. For instance in Flexibility->Weather:

1. When the default option is active, the sliders above are enabled
<img width="466" alt="Screenshot 2023-10-06 at 14 21 33" src="https://github.com/quintel/etmodel/assets/14875123/388da5cc-5080-4b63-9c86-15a054ebab68">

2. When choosing a preset, the sliders above are disabled
<img width="476" alt="Screenshot 2023-10-06 at 14 21 44" src="https://github.com/quintel/etmodel/assets/14875123/96e36644-efa2-426c-b6dd-1a927f5eb11c">

For the expert mode something similar should be implemented.

--> insert a drwaing here of expert toggle off
--> and one with expert toggle on

First we should create mockups and discuss if the user experience suits the goal. -> with Roos!

### Button to show expert mode
There should be a switch to toggle the expert mode for the inputs.
Inner workings
Toggle in config
- [ ] Add an option to configure input elements in the ETModel interface files, that specifies which keys are general and expert and how they relate
   -----> give an example code thing
- [ ] 

### When revisiting the slide
The expert sliders will have their`disabled_by` attribute set correctly by the modellers in ETSource. This means the general sliders will be seen by ETModel as `disabled` when the expert inputs are touched. Usually, [disabled sliders](https://github.com/quintel/etmodel/blob/9df7268bce7917e4bbbf6bcaa75111f8601aeb01/app/assets/javascripts/lib/models/input_element.coffee#L24-L25) are simply [greyed out and untouchable](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/views/input_element_view.js). However, in our case the general sliders being disabled will mean that they are greyed out **and** the expert sliders are shown. 
- [ ] Next to 'normal' disabled, 'disabled by coupling', and 'disabled by other feature' input elements should also be able to be disabled by 'expert mode' (see the js model/view)
- [ ] When they are disabled by expert mode, expert mode sliders should be visible

The 

---
Still to discuss:
- Do we save this state/how do we handle coming back to the slide? E.g if someone touched both general and expert inputs which ones we show when opening the slide again?
- On a modelling perspective: if the expert inputs `disable` the general ones, solving the state problem above would be easy

**Comment by redekok** [comment]
This issue is on hold until we've met with our stakeholders tomorrow morning!

**Comment by mabijkerk** [comment]
No longer relevant for the Heat improvements project.
