### ISSUE TITLE
Homepage transition paths contains old text

### ISSUE THREAD

**Issue by DionB10** [quintel/etmodel#4217]
Op de voorpagina van ETM staat 'wat dit betekent voor tussentijdse doelstellingen in 2023'. Dit is al geweest, leest alsof de info outdated is:
![image_720](https://github.com/quintel/etmodel/assets/148070661/879b580e-0064-4465-8c25-fc46ed5b275e)

**Comment by mabijkerk** [comment]
Well-spotted, thanks @DionB10. @kndehaan is this something you can pick up at some point?

**Comment by kndehaan** [comment]
Sure! I'll put it on my todo list

**Comment by kndehaan** [comment]
Text is updated
