### ISSUE TITLE
The Sankey should have the right translations

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#4224]
"wind electricity"  --> NL 

![image](https://github.com/quintel/etmodel/assets/33415156/39def039-a50f-47fa-911d-658a075c021f)

**Comment by kaskranenburgQ** [comment]
This issue has been solved with PR #4214 and is implemented on beta:
<img width="528" alt="Screenshot 2024-03-22 at 14 41 57" src="https://github.com/quintel/etmodel/assets/150331345/aa2b123b-76ef-4eeb-a48d-976537df7e2e">
Will go to production with the next deploy.
