### ISSUE TITLE
Link from ETModel to documentation should work

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#4232]
https://energytransitionmodel.com/%22https:/docs.energytransitionmodel.com/main/insulation/%22

<img width="1440" alt="image" src="https://github.com/quintel/etmodel/assets/33415156/70157607-dc6d-4f1b-80bb-cd82c3d441bb">

**Comment by noracato** [comment]
Where did you click to get this? It looks like a wrongly formatted url

**Comment by MartLubben** [comment]
<img width="981" alt="image" src="https://github.com/quintel/etmodel/assets/33415156/ee99d865-3544-4fde-91f7-394f26bda03f">

**Comment by mabijkerk** [comment]
Thanks for this @MartLubben! It's now fixed on `master`.
