### ISSUE TITLE
"ppartementen" should be appartementen in the chart

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#4244]
<img width="663" alt="image" src="https://github.com/quintel/etmodel/assets/33415156/22730216-5514-4ff6-a63c-61b49490d96e">

**Comment by kaskranenburgQ** [comment]
Great spot! 
In the locales the label is marked as "Appartementen", the 'A' falls of the chart in this case.

I see 2 options to solve this:

1. Place an enter in the label; This might be a bit ugly, but is easy to fix.
2. Alter the space that is given to these labels in the files that create these graphs. This could be quite hard.

What do you think @mabijkerk ?

**Comment by mabijkerk** [comment]
Maybe this is something @louispt1 can look into?
