### ISSUE TITLE
Implement IsEmpty for Sankey type charts

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etmodel#4246]
![afbeelding](https://github.com/quintel/etmodel/assets/74194356/4f600aa9-f694-4a62-b6a4-578a981eea6f)

**Proposal:**
Let's create some sort of error message similar to other graphs -->
![afbeelding](https://github.com/quintel/etmodel/assets/74194356/71d5011b-0c8a-4312-8a8e-af81f672621a)

Notifying @mabijkerk

**Comment by kaskranenburgQ** [comment]
I have tried a couple of things, but could not get any further with this issue unfortunately.
In addition I found that this issue can also occur in the CCUS tab on beta.
![Screenshot 2024-05-01 at 10 30 28](https://github.com/quintel/etmodel/assets/150331345/f30dc7e4-d162-48b5-b88e-233ff0278ef0)
@noracato When it suits you, could you take a look?

**Comment by mabijkerk** [comment]
This appears to be a generic issue for Sankey type charts. Handling of empty data should be added to the `sankey.coffee` file.
