### ISSUE TITLE
Header missing for Land use of solar and wind graphs in graph overview.

### ISSUE THREAD

**Issue by kaskranenburgQ** [quintel/etmodel#4254]
See picture below, The land use of solar and wind has a line above them indicating that they are in a another category. However, no title has been given to this category.

<img width="663" alt="Screenshot 2024-04-30 at 17 01 21" src="https://github.com/quintel/etmodel/assets/150331345/335ec69a-dbaa-4383-ab69-4dd2043848ea">

Notifying @mabijkerk, assigned myself.

**Comment by mabijkerk** [comment]
@KoenvanB or @Charlottevm, these have been added in of your projects. What is you take on this issue?

**Comment by KoenvanB** [comment]
I have probably omitted a relevant category by accident. As far as I can tell, 'Supply' seems the appropriate category for both these charts to land in. @Charlottevm do you agree?

**Comment by kaskranenburgQ** [comment]
<img width="506" alt="Screenshot 2024-07-12 at 12 21 59" src="https://github.com/user-attachments/assets/fdd98f3f-e002-4c2e-8de7-c148d5ebd2de">

I added "Land use" in english and "Ruimtegebruik" in Dutch. in PR #4299 .
