### ISSUE TITLE
Sankey should fit inside it's outside corners

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#4255]
The sankey should fit inside it's corners. I am not sure what the reason is. 

<img width="463" alt="image" src="https://github.com/quintel/etmodel/assets/33415156/25083c5c-b212-40e5-a140-e6c23ee24684">

https://beta.energytransitionmodel.com/saved_scenarios/5265

**Comment by mabijkerk** [comment]
It seems like losses are not properly taken into account in the chart margins. This is something @noracato or the new developer should pick up at some point.

**Comment by mabijkerk** [comment]
@louispt1 the issue stil persists in some cases unfortunately, even though https://github.com/quintel/etmodel/issues/3928 was no longer relevant. In the example from @MartLubben on beta, it is still relevant:

<img width="623" alt="Screenshot 2024-08-06 at 14 40 17" src="https://github.com/user-attachments/assets/dadc437d-1589-4c2e-bbc9-40876dd18253">
