### ISSUE TITLE
Users should be able to download data of a chart

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#4258]
At this moment it is not possiible to get te data out of a chart, not even a table. User have to type this by hand:

<img width="550" alt="image" src="https://github.com/quintel/etmodel/assets/33415156/0bca24fd-074e-488f-8bd3-90d4a2683874">

**Comment by mabijkerk** [comment]
@MartLubben this issue already exists in https://github.com/quintel/etmodel/issues/3580

**Comment by MartLubben** [comment]
Busted :)
