### ISSUE TITLE
Issues that came out testing

### ISSUE THREAD

**Issue by kaskranenburgQ** [quintel/etmodel#4260]
Here are some issues I spotted while testing beta

- [ ] 1.Greenhouse gas footprint export does not show negative numbers when negative emissions and prices are very low in the scenario.

- [x] 2. Modify profiles page under Flexibility does not function:
See [this link](https://beta.energytransitionmodel.com/scenario/flexibility/curve_upload/upload-curves)

- [ ] 3. heat_network_demand is used as an output_element_key at 'Hourly curves for heat networks'
This output element has been removed from the model and replaced with heat_network_demand_ht, heat_network_demand_mt & heat_network_demand_lt.

- [ ] 4. At fuel prices, the graph of the barrel price of oil could use an update ( or removal)

![Screenshot 2024-05-06 at 11 15 31](https://github.com/quintel/etmodel/assets/150331345/196b1077-34fa-4130-8ac7-253a913c4d1b)

- [ ] 5. Connection is not fully shown here,.

![Screenshot 2024-05-06 at 11 16 22](https://github.com/quintel/etmodel/assets/150331345/58bfdcba-37f3-4daf-9444-47ef7e2dd7f5)

**Comment by mabijkerk** [comment]
@kaskranenburgQ could you open dedicated issues for the items listed above? This would help in tackling them individually.
