### ISSUE TITLE
Sankey should include green gas in biomass

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#4269]
Green gas is a.t.m. part of 'aardgas' in the sankey. It should be part of biomass. 

<img width="991" alt="image" src="https://github.com/quintel/etmodel/assets/33415156/3ef0903d-fc2c-4fca-8b96-98b0dacadfe1">

**Comment by kaskranenburgQ** [comment]
This is a replica of [issue #2999 on Etsource](github.com/quintel/etsource/issues/2999#issuecomment-2105593169), this [Draft PR](https://github.com/quintel/etsource/pull/3051) can be viewed to track the progress on this issue.
