### ISSUE TITLE
Max values of slides should allow II3050 values for provinces

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#4276]
During the creation op de II3050 scenario's with the scenario-tools for provinces we encountered many max value errors. 

We propose to increase these max values, to fit with the II3050 values for provinces.

- capacity_of_energy_flexibility_mv_batteries_electricity, Currently based on 6 times baseload electricity demand in startyear, increased to 15 times baseload demand in startyear
- capacity_of_energy_heat_flexibility_p2h_heatpump_electricity: Bases on 50% of max baseload heat demand in startyear, should be increased a factor 3. 
- capacity_of_energy_hydrogen_steam_methane_reformer: Based on max (500 MW, baseload gas demand). This doens't suit well for provinces which supply more gas than they use. Changed to max (10000 MW, baseload gas demand). 
- capacity_of_energy_power_nuclear_gen2_uranium_oxide &  capacity_of_energy_power_nuclear_gen3_uranium_oxide: Based on 2 times baseload electricity demand. Does't scale well for Zeeland, which produces for the rest of NL. Max (10000, 2 times baseload electricity demand)
- capacity_of_households_solar_pv_solar_radiation & capacity_of_buildings_solar_pv_solar_radiation: Based on suitable roof size and current efficiency for provinces.. Factor 3-4 too low for II3050. Increase 4 times

**Comment by mabijkerk** [comment]
All in all, these seem fine. Only `capacity_of_energy_flexibility_mv_batteries_electricity` seems a bit excessive, by increasing it to 15 times. Can't we implement something similar to the other max values you reference: MAX(absolute_value,query_value), where absolute_value would be e.g. 10000 MW.

**Comment by mabijkerk** [comment]
Closed through https://github.com/quintel/etsource/pull/3066
