### ISSUE TITLE
Oil price graph could use an update

### ISSUE THREAD

**Issue by kaskranenburgQ** [quintel/etmodel#4311]
At fuel prices, the graph of the barrel price of oil could use an update ( or removal)
![Screenshot 2024-05-06 at 11 15 31](https://github.com/quintel/etmodel/assets/150331345/196b1077-34fa-4130-8ac7-253a913c4d1b)

**Comment by mabijkerk** [comment]
@kaskranenburgQ I'm in favour of removing it.

**Comment by mabijkerk** [comment]
Closed in d10acb5e1bde90d7f43ced3bcfbf7f46e5b0e9f9
