### ISSUE TITLE
Scenario versions

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etmodel#4324]
Something seems to be going wrong with the scenario versions.
If I try to go back to another scenario version I get the following error:

![afbeelding](https://github.com/user-attachments/assets/19eaba29-926f-4260-8536-47a02265b6c4)

This is a shared scenario (as you can see in the image). 
If information is required let me know. 
Assign at will @noracato / @mabijkerk .

**Comment by mabijkerk** [comment]
@Charlottevm is this still relevant?
