### ISSUE TITLE
When a scenario is uncoupled the sliders should change to the defuault ETM sliders

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#4329]
When I uncouple an II3050-scenario the calculations change to default. However, the sliders shown in the front-end are still the coupled sliders.

## Coupled

![image](https://github.com/user-attachments/assets/d5532ebb-c600-4f64-9754-cbde59bf4141)

## Uncoupled
![image](https://github.com/user-attachments/assets/36077b82-c5b4-41d8-b645-ba6138087a53)

**Comment by mabijkerk** [comment]
@DorinevanderVlies as far as I can tell, this issue is solved.
