### ISSUE TITLE
Coupling display issues

### ISSUE THREAD

**Issue by louispt1** [quintel/etmodel#4341]
As documented in the images below, there are some teething issues for the front end for the couplings.
Namely:

1. If coupling is toggled on/off multiple times, a model may be shown to be coupled multiple times.
2. After the interconnnectors are coupled, the front end doesn't always correctly show the 'coupling' links or grey out the disabled inputs.

There is a chance these issues are related to the browser caching issue we faced earlier, but more investigation is required. Please add any comments you might have with regard to these issues @kaskranenburgQ.

![image](https://github.com/user-attachments/assets/39135ada-dfd4-4503-b329-58e887cfb534)
![image](https://github.com/user-attachments/assets/3b68276b-2b9a-42c5-9d9a-f3e2900477a2)

**Comment by noracato** [comment]
I can't reproduce this issue. Tried uncoupling and recoupling multiple times, but for me it works as expected. Can you describe where this is happening? Beta, pro, locally?

**Comment by louispt1** [comment]
Maybe @kaskranenburgQ or @kndehaan can add detail but from my understanding the issue occurs on pro. It seems to primarily occur when the Plexos coupling is in play, which is interesting. - Kas is going to quickly retest it now that we've deployed. He did make some changes to the coupling groups in ETSource to have a main coupling and a 'sub' coupling group. I have not had time to properly investigate the issue yet!

**Comment by kaskranenburgQ** [comment]
I just tested this with the following scenario: https://energytransitionmodel.com/saved_scenarios/17738. If I toggle the soft uncoupling button and save the changes, the CTM-ETM-coupling is added:
<img width="1099" alt="Screenshot 2024-10-01 at 11 56 34" src="https://github.com/user-attachments/assets/bda2bbfb-5fb5-4023-b522-65a5136a7d54">
<img width="354" alt="Screenshot 2024-10-01 at 11 57 34" src="https://github.com/user-attachments/assets/316014c7-ae45-46f0-9114-3fc6313a4cfa">

**Comment by noracato** [comment]
@louispt1 we need to add an extra check [here](https://github.com/quintel/etmodel/blob/master/app/models/setting.rb#L116-L119). Line 118 add: `unless active_couplings.include?(group)`
