### ISSUE TITLE
Merit order link in introduction is not functional [bug]

### ISSUE THREAD

**Issue by thesethtruth** [quintel/etmodel#4352]
## Issue
When I'm at Introduction > Total energy demand, there is a link to the merit order that is not functional. (`/supply/merit_order/merit-order` instead of `/scenario/supply/merit_order/merit-order`)

## Screenshots
![image](https://github.com/user-attachments/assets/e77eae91-2275-4fd3-b50b-d6964f3f0114)

![image](https://github.com/user-attachments/assets/8a60abf4-fc65-4b77-86ff-3449cc7168f1)

**Comment by mabijkerk** [comment]
Well-spotted @thesethtruth, thanks! I fixed it on beta, it will go live with the November Deploy.
